ProcessMaker/processmaker

resources/assets/sass/layouts-app.scss

Updated global btn override to fix the button style

Fixed button styles

---

resources/assets/js/designer/Designer.vue
resources/assets/js/designer/components/modals/modal-permissions-add.vue

cancel button hides modal on permissions

#234 added cancel logic

---

resources/views/auth/login.blade.php

First Commit - Added missing links. References to #230

added missing links in login page

---

resources/views/auth/login.blade.php

Revert "added missing links in login page"

---

ProcessMaker/Http/Middleware/GenerateMenus.php
resources/views/designer/designer.blade.php

generate new menu with no icons

---

resources/assets/js/designer/components/modals/modal-variables-add.vue

go to designer
click on variables 
test variable type drop down
This is in reference to #265

#265 - added variable dropdown

---

resources/views/auth/login.blade.php

#296 login working successfully

---

ProcessMaker/Providers/ProcessMakerServiceProvider.php
composer.json
composer.lock

Updated autoloader and service provider registration to fix #267

Disable Dusk in Prod

---

resources/assets/js/app-layout.js
resources/assets/js/bootstrap.js
resources/assets/sass/app.scss
resources/views/layouts/layout.blade.php
resources/views/layouts/navbar.blade.php

Change the alerts to be a Vue component on the main app. Can be triggered via the Laravel flash messaging in a meta tag or via the VueJS data object.

Add new alerts for #351

---

ProcessMaker/Http/Controllers/Api/Designer/TaskDelegationController.php
ProcessMaker/Managers/TasksDelegationManager.php
resources/assets/js/tasks/components/TasksList.vue
routes/web.php

Add access to task from task list. Solves #395

---

database/seeds/DatabaseSeeder.php
tests/Feature/Api/Administration/UsersTest.php
tests/Feature/Api/Designer/ProcessesTest.php

Feature https://github.com/ProcessMaker/bpm/issues/402
- Add processSeeder in list
- change php units of users and process just for the amount

Add Process seeder in DatabaseSeeder

---

ProcessMaker/Http/Middleware/GenerateMenus.php
package-lock.json
package.json
resources/assets/sass/_variables.scss
resources/assets/sass/app.scss
resources/views/layouts/navbar.blade.php

Navbar changes to blue when active

---

ProcessMaker/Http/Controllers/Designer/ProcessController.php

Feature https://github.com/ProcessMaker/bpm/issues/408
- add validation if the process is not found in the designer's path

Process not found in route Designer

---

resources/assets/js/designer/components/toptoolbar.vue

feature/376 Remove Zoom

---

resources/assets/js/designer/components/designer-objects-menu.vue
resources/assets/js/designer/components/designer-options-menu-item.vue

Feature https://github.com/ProcessMaker/bpm/issues/404
- Add option visible in component designer options menu

hide Designer options menu

---

resources/views/management/groups/index.blade.php

#431 changed button class to match mockup

---

resources/assets/js/components/requests/notifications.vue
resources/assets/sass/app.scss
resources/views/layouts/navbar.blade.php

made minor changes to the right side of the navbar, added top padding and changed avatar size so all items are now inline.

clean up navbar

---

ProcessMaker/Http/Middleware/GenerateMenus.php
resources/views/processes/index.blade.php

place holder in generate menus and index for processes

process menu placeholders added

---

resources/assets/js/components/requests/notifications.vue

- also changed font styles and sizes 
#373

addressed width and position of the drop down menu 

---

ProcessMaker/Facades/InputDocumentManager.php
ProcessMaker/Facades/TriggerManager.php
ProcessMaker/Http/Controllers/Api/Designer/AssigneeController.php
ProcessMaker/Http/Controllers/Api/Designer/FormController.php
ProcessMaker/Http/Controllers/Api/Designer/InputDocumentController.php
ProcessMaker/Http/Controllers/Api/Designer/OutputDocumentController.php
ProcessMaker/Http/Controllers/Api/Designer/ProcessesController.php
ProcessMaker/Http/Controllers/Api/Designer/TaskController.php
ProcessMaker/Http/Controllers/Api/Designer/TaskDelegationController.php
ProcessMaker/Http/Controllers/Api/Designer/TriggerController.php
ProcessMaker/Managers/InputDocumentManager.php
ProcessMaker/Managers/TriggerManager.php
ProcessMaker/Serializers/ApiSerializer.php
tests/Feature/Api/Designer/FormManagerTest.php
tests/Feature/Api/Designer/InputDocumentManagerTest.php
tests/Feature/Api/Designer/OutputDocumentManagerTest.php
tests/Feature/Api/Designer/ProcessesTest.php
tests/Feature/Api/Designer/TaskDelegationManagerTest.php
tests/Feature/Api/Designer/TaskManagerTest.php
tests/Feature/Api/Designer/TriggerManagerTest.php

was changed the parameters
sort_by => order_by
sort_order => order_direction
current_page => page
in the calls of rest Api.

Change parameter sort_by, sort_order, current_page

---

composer.lock
tests/Feature/Api/Administration/ProcessCategoryManagerTest.php
tests/Feature/Api/Administration/UsersTest.php

Bugfix https://github.com/ProcessMaker/bpm/issues/459
- change phpUnit to 7.3.1

Fix problem test process category

---

resources/assets/js/designer/Designer.vue

Added validation in selected element before open dialog

feature/473 Designer Modals Broken

---

ProcessMaker/Http/Middleware/GenerateMenus.php
resources/lang/en/menus.php

- removed inbox, authentication, Language
- Moved Preferences under 'Configuration header'
- UI Customizations is now Colors and Logos
#447

admin sidebar update

---

resources/assets/js/app-layout.js
resources/assets/js/components/Confirm.vue
resources/assets/js/designer/components/modalList/modal-forms-list.vue
resources/views/layouts/navbar.blade.php
tests/js/components/ConfirmModal.test.js

feature https://github.com/ProcessMaker/bpm/issues/458
- Add global component in ProcessMaker.confirmModal(title, message, variant, callback)

Component Confirm Modal

---

ProcessMaker/Http/Controllers/HomeController.php
phpunit.xml
resources/assets/js/designer/components/toptoolbar.vue
resources/assets/js/designer/formBuilder/form.vue
resources/assets/sass/_variables.scss
resources/views/auth/login.blade.php
resources/views/auth/passwords/email.blade.php
routes/web.php

I've updated the CSS and HTML for the following:
- Login - forgot password text
- Reset Password - sub head text and back to login link
- Designer - grey toolbar top padding
- Form Designer - toolbar changed to grey, added icons, added padding to inspector
- Redirects configured with home controller to requests
- Removed unused dash route

Clean up CSS

---

ProcessMaker/Http/Controllers/Auth/RefreshController.php
ProcessMaker/Http/Middleware/GenerateApiToken.php
resources/assets/js/app-layout.js
routes/web.php

When access token expires, refresh the token and retry the request:
Ref  #491

When access token expires, refresh the token and retry the request. #491

---

resources/assets/js/processes/components/ProcessesListing.vue

Removed __checkbox from 'fields'
Tests pass locally
#526

removed checkboxes from vuetable on ProcessesListing

---

.circleci/config.yml

feature https://github.com/ProcessMaker/bpm/issues/533
add configuration by default extension php gd

Change configuration extension php GD

---

resources/assets/sass/app.scss

changed font-weight to normal
#525

Nav Bar text to normal

---

ProcessMaker/Http/Controllers/Api/Administration/GroupsController.php
resources/assets/js/management/groups/components/GroupsListing.vue
resources/assets/js/management/groups/components/modal-group.vue
resources/assets/js/management/groups/index.js
resources/views/management/groups/index.blade.php
routes/api.php
tests/Feature/Api/Administration/GroupsTest.php

Feature https://github.com/ProcessMaker/bpm/issues/539
- Add Component modal Group
- Add method update group
- Add test update group with rest api

Edit Group

---

resources/assets/js/designer/BPMNHandler/BPMNProcess.js
resources/assets/js/designer/components/modals/modal-task-configuration.vue

Fix missing save of the configuration.

Fix missing save of the configuration.

---

resources/assets/js/components/requests/card.vue
resources/assets/js/requests/components/RequestsListing.vue
routes/web.php

The route request/{instanceId}/status have been changed to  requests/{instanceId}/status
The changes were applied to:
- Route definition in web.php file.
- References to the route located in .vue components.
No other references were found through the project's source code.

Request Route Incorrect

---

docs/readme.md

Nothing fancy. Just a placeholder for @lcriscuolo 
Ref: #588

Add default docs folder with sample readme

---

tests/Feature/Api/Requests/RequestsTest.php

There is a broken test in this branch. Need to merge ASAP.
@tdondich @caleeli

Fixed broken tests

---

ProcessMaker/Http/Middleware/GenerateMenus.php
resources/assets/js/management/users/components/UsersListing.vue
routes/web.php

from the admin sidebar, route, and in the users table.
#612

removed roles

---

composer.lock

Point nayra to packagist. #614

Point nayra to packagist.

---

.circleci/config.yml
tests/bootstrap.php

Fix problems of execution of php unit test and building of npm. #616

---

ProcessMaker/Http/Controllers/Request/StatusController.php
resources/assets/js/request/components/request-status.vue
resources/assets/js/tasks/components/TaskForm.vue
resources/views/requests/status.blade.php
resources/views/tasks/open.blade.php
resources/views/tasks/show.blade.php

Updated styling for Task and Request pages

---

.circleci/config.yml
jest/globals.js
package.json
resources/assets/js/management/preferences/index.js
tests/js/processes/categories/components/CategoriesListing.test.js

Requires jest config `transformIgnorePatterns` to allow rending vuetable-2

Feature/622 - Fix failing CategoryListing jest test

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
ProcessMaker/Models/User.php
resources/js/components/common/mixins/datatable.js
resources/js/processes/components/ProcessesListing.vue
resources/js/processes/index.js
resources/views/processes/index.blade.php

feature https://github.com/ProcessMaker/bpm/issues/665
- change template list process
- change model user and add fields appends

VueTables Update List Process

---

.circleci/config.yml

Changes to the Circle CI config to fix uploading of documents on the development server.
#652

FIX: CircleCI Media Storage

---

resources/js/admin/users/components/UsersListing.vue
resources/js/admin/users/index.js
resources/views/admin/users/index.blade.php

- change list to list vuetable.
- remove code of forms edit in list.
- Functionalities applied only in list, filter, order.
- todo create, edit and remove user.

List users

---

.circleci/config.yml

run artisan passport:keys to generate encryption keys.

Update circle ci config for passport keys

---

laravel-echo-server.json

Adding the "port" option for the redis database config. This port line is set later to whatever port it is assigned from the QA server.

update laravel-echo-server for dynamic redis port

---

resources/views/auth/login.blade.php

Login.blade updated terminology

#764 - LOGIN to LOG IN

---

ProcessMaker/Models/User.php
database/factories/UserFactory.php
database/migrations/2014_10_12_000000_create_users_table.php
database/seeds/UserSeeder.php

Add the field **is_administrator** to the **users** table, model, factory and seeder.
#749

Add is_administrator property to User. #749

---

ProcessMaker/Http/Controllers/Process/ProcessCategoryController.php
ProcessMaker/Http/Middleware/GenerateMenus.php
routes/web.php

#757 
added controllers to web.php 
correct routes added to sidebar icons

Enable Process Menu Links

---

config/database.php
laravel-echo-server.json

Add host to redis server and add placeholder for echo server and redis ports. Changed during container deploy

Update echo server config

---

resources/views/admin/about/index.blade.php

About page

---

ProcessMaker/Http/Controllers/Api/TaskController.php
tests/Feature/Api/ProcessCollaborationTest.php
tests/Feature/Api/ProcessScriptsTest.php

feature https://github.com/ProcessMaker/bpm/issues/580
- Validation in list task display only tasks

Filter only task in task list

---

ProcessMaker/Models/EnvironmentVariable.php
resources/js/processes/environment-variables/components/VariablesListing.vue
resources/js/processes/environment-variables/index.js
resources/views/processes/environment-variables/index.blade.php

feature https://github.com/ProcessMaker/bpm/issues/842
- Add Create modal
- Add option delete

Create Environment Variables

---

ProcessMaker/Http/Controllers/Api/EnvironmentVariablesController.php
ProcessMaker/Http/Controllers/Process/EnvironmentVariablesController.php
resources/views/processes/environment-variables/edit.blade.php
tests/Feature/Api/EnvironmentVariablesTest.php
tests/Feature/Processes/EnvironmentVariablesTest.php

Feature https://github.com/ProcessMaker/bpm/issues/844
- Add page environment variable.
- Add test route
- Add test if value is empty not update field.

Edit Environment Variables

---

resources/views/admin/users/edit.blade.php
resources/views/admin/users/index.blade.php
resources/views/profile/show.blade.php

bugfix https://github.com/ProcessMaker/bpm/issues/870
- Add promise in multiple save of members

Verify save of members in User

---

resources/views/processes/scripts/index.blade.php

feature/875 - Fix merge conflict in scripts index

---

ProcessMaker/Http/Controllers/Api/ScriptController.php
ProcessMaker/Models/Script.php
database/factories/ScriptFactory.php
database/migrations/2018_09_07_174216_create_scripts_table.php
tests/Feature/Api/ScriptsTest.php

Add key field to scripts

---

ProcessMaker/Http/Controllers/ProcessController.php
ProcessMaker/Models/Process.php
database/migrations/2018_09_07_170019_create_process_table.php
resources/views/processes/edit.blade.php

Solves #855 
- Added a new "summary screen" field in processes table
- Process model modified to add a summaryScreen relationship
- Process edit blade template was modified to add the summary screen
How test the PR:
- Go to the processes list and edit a process
- select a summary screen and save.
- Enter again to edit the same process an verify that the selected screen is set.

Process Configuration Screen

---

ProcessMaker/Http/Controllers/RequestController.php
ProcessMaker/Models/Process.php
resources/js/requests/show.js
resources/views/requests/show.blade.php

Feature https://github.com/ProcessMaker/bpm/issues/853
- Add summary page if it is configured in the process.
- not configured
- configured

Render summary in page request detail

---

.circleci/config.yml
ProcessMaker/Models/Script.php
ProcessMaker/Models/ScriptDockerTrait.php

Change docker mount by docker cp to share files in script execution. #795

---

ProcessMaker/Facades/WorkflowManager.php
ProcessMaker/Jobs/RunServiceTask.php
ProcessMaker/Listeners/BpmnSubscriber.php
ProcessMaker/Managers/WorkflowManager.php
ProcessMaker/Models/Process.php
composer.json
composer.lock
database/processes/templates/ServiceTaskProcess.bpmn
public/definitions/ProcessMaker.xsd
tests/Feature/Api/ServiceTaskExecutionTest.php

- Implementation of Service Tasks as Scripts identified by a Key
- Update Nayra version to support service tasks
- Added a Unit Test to execute a service task (EchoConnetor)
- Added a process example with ServiceTask

Add implementation of Service Task/Connectors. #878

---

resources/views/processes/index.blade.php

when creating a new process you will be redirected to modeler/{process}

fixed redirect path to modeler

---

package-lock.json
package.json

- Fix issues with conditional flows
- Fix issues with text annotations
- Fix issues during saving and loading processes

Update the process modeler.

---

tests/Feature/Api/GroupsTest.php
tests/Feature/Api/NotificationsTest.php
tests/Feature/Api/ProcessRequestsTest.php
tests/Feature/Api/ProcessTest.php
tests/Feature/Api/ScreenTest.php
tests/Feature/Api/ScriptsTest.php
tests/Feature/Api/TasksTest.php
tests/Feature/Api/UsersTest.php

The tests are changed by adding the filter when obtaining the list.

Fix test timezone

---

ProcessMaker/Http/Controllers/AboutController.php
ProcessMaker/Http/Middleware/GenerateMenus.php
resources/views/about/index.blade.php
routes/web.php

moved to the profile drop down

about page has been moved

---

ProcessMaker/Http/Controllers/Api/ScreenController.php
resources/js/processes/modeler/components/inspector/ScreenSelect.vue

fixes #977 
to test: open a process and click on a task, in the drop down for screen selection there are only forms available to choose from.

When assigning a task there will not be an option to see display screens 

---

resources/js/processes/screen-builder/screen.vue

Add validation in screen preview with data json error

Screen Preview JSON Error

---

ProcessMaker/Http/Controllers/Api/NotificationController.php
ProcessMaker/Http/Controllers/NotificationController.php
ProcessMaker/Http/Controllers/TaskController.php
ProcessMaker/Models/User.php
resources/js/bootstrap.js
resources/js/components/requests/notifications.vue
resources/js/notifications/components/NotificationsList.vue
resources/js/notifications/index.js
resources/views/layouts/layout.blade.php
resources/views/notifications/index.blade.php
resources/views/tasks/edit.blade.php
routes/api.php
routes/web.php
tests/Feature/Api/NotificationsTest.php
webpack.mix.js

Solves #988
- New notification list added with options to mark as read/unread a notification
- The notification list has filtering and sorting options
- The user_notifications endpoint was removed. Now, only the notifications index (get) endpoint is used

Notifications

---

ProcessMaker/Providers/WorkflowServiceProvider.php
composer.lock

Fix textAnnotation ElementNotImplementedException. #998

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Http/Controllers/Api/TaskController.php
ProcessMaker/Http/Controllers/TaskController.php

Solves #1001 
Route permissions are ignored in Tasks and Requests controllers

Remove of route permissions for task and request controllers

---

tests/Browser/UserListTest.php

Turn off dusk test. Close #1071

Disabled dusk test

---

ProcessMaker/Models/Process.php
ProcessMaker/Traits/ProcessTaskAssignmentsTrait.php
resources/lang/en/exceptions.php

- Fix update of the bpmn definition
- Add validation for tasks without user assigned.

Fix sync and validation for user assignment. #1090

---

resources/views/profile/edit.blade.php
resources/views/requests/show.blade.php

Copy Changes

---

resources/views/processes/index.blade.php

fixes #1097 
to test:
remove current process and categories (or shortcut is to set processCategories to "" in the processes.index.blade) create a process.

Categories are required

---

ProcessMaker/Http/Controllers/Api/FileController.php
ProcessMaker/Models/Media.php

Solves #936 
Annotations added to:
- FileController methods
- Media model

Annotate request file API endpoint

---

ProcessMaker/Http/Middleware/GenerateMenus.php
resources/sass/app.scss

all routes should now be highlighted.

Navigation highlight

---

database/seeds/PermissionSeeder.php
routes/web.php

to test:
Run php artisan:migrate --seed
Create a new user and give them all permissions
Log in as that new user
create a process 
BAM
fixes #1123

fixed modeler permissions

---

ProcessMaker/Http/Controllers/ProfileController.php

All users can now edit their profiles. Fixes #1138.

Added skip permission check for profile.edit

---

ProcessMaker/Models/User.php
resources/js/components/NavbarProfile.vue
resources/js/tasks/components/TasksList.vue

fixes #1141 
This ticket is not complete as there is still some choices to be made. However, this PR solves the issue of a user not having a first and last name not being able to see the navbar drop down. 
this also solves the task todo list displaying the users name next to the avatar.

Avatar enhancements 

---

ProcessMaker/Models/Screen.php
database/migrations/2018_09_07_171508_create_screens_table.php
database/migrations/2018_09_07_173804_create_screen_versions_table.php
resources/js/processes/screen-builder/screen.vue
resources/js/tasks/components/TaskForm.vue
resources/js/tasks/components/TaskView.vue
resources/views/tasks/edit.blade.php

Solves #1148 
- Computed properties now are saved in the database
- Computed properties are read when editing a screen and when processing a task
* Need to run the migrations

Computed Properties not working

---

composer.json
composer.lock
package-lock.json
package.json
resources/js/processes/modeler/components/inspector/ConfigEditor.vue
resources/js/processes/modeler/components/inspector/ExpressionEditor.vue
resources/js/processes/modeler/components/inspector/ScreenSelect.vue
resources/js/processes/modeler/components/inspector/ScriptSelect.vue
resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/initialLoad.js
resources/js/processes/screen-builder/screen.vue
resources/views/processes/modeler/index.blade.php

Update Modeler to the latest version 0.2.*, with this the following features are included:
- Pools and Lanes
- Undo/Redo
- Many improvements in the modeler usage.
- Update email connector plugin (compatible with the last version of modeler)

Update Modeler and enable pools lanes undo redo

---

ProcessMaker/Http/Controllers/Api/ProcessController.php

closes #1213 
As a user with permission to create and edit a process, I can now see the process I create in the processes list.

removed auth check from processes index

---

resources/views/admin/users/edit.blade.php
resources/views/profile/edit.blade.php

updated language drop down

---

resources/views/requests/show.blade.php

updated date format in request show

---

resources/views/admin/auth-clients/index.blade.php

breadcrumbs added to auth clients

---

resources/views/processes/environment-variables/edit.blade.php

fixes #1222 
we will not be adding the dots as to not introduce anything new. however there was some helper text added so the user does not feel that their values were not saved.

added helper text to value field

---

resources/views/admin/groups/edit.blade.php
resources/views/admin/groups/index.blade.php
resources/views/admin/users/edit.blade.php
resources/views/admin/users/index.blade.php
resources/views/processes/categories/index.blade.php
resources/views/processes/environment-variables/index.blade.php
resources/views/processes/index.blade.php
resources/views/processes/screens/index.blade.php
resources/views/processes/scripts/index.blade.php

fixes #1231 
- Add Clear fields in event close in modals

Modals Not Clearing #1231

---

resources/views/errors/403.blade.php
resources/views/errors/404.blade.php
resources/views/errors/500.blade.php

403 error 
404 error 
500 error

Add Nav to 404, 403 and 500 error pages

---

ProcessMaker/Models/Screen.php
tests/Feature/Api/ScreenTest.php

Fixes #1266. Screens now handle validation properly.

Fix Screen validation rules

---

resources/views/tasks/edit.blade.php

Fix request data (when empty) must be an object not array. #1278

---

README.md

Fixes to README file

---

resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/initialLoad.js

This PR:
- Validate the introduction of positive number in dueIn property
- Validate the copy/paste
- If the value is deleted or 0 the property is removed from the node (not stored).
Related to: #1280

Validate due in could accept only positive numbers.

---

package-lock.json
package.json

- The problem is solved in the project vue-form-builder with the issue  https://github.com/ProcessMaker/vue-form-builder/issues/41
- package.json and package-lock.json are updated to use the new version for vue-form-builder

Cannot edit a Date Picker when it is inside a multi-column control #1287

---

resources/views/requests/show.blade.php

This PR includes the following changes:
- Fix cancel confirm popup for small devices
- Fix translatable labels in the popup
Fixes: #1285

Fix cancel confirm popup.

---

resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/initialLoad.js

- Set "requestor" as the default assignment rule for tasks
Related: #1311

Set default "requestor" as default assignment

---

ProcessMaker/Models/Process.php
package-lock.json
package.json
public/definitions/ProcessMaker.xsd
resources/js/processes/modeler/components/inspector/TaskAssignment.vue

- Modeler Inspector was modified to add the new section for special assignments
- A new assignment rule function was created. This functions evaluates all the rules configured in a task. The first one that is true is used to make the assignment.
- processmaker-bpmn-moddle was modified to include a new attribute assignmentRules to store in the bpmn the rules to create an assignment by value (https://github.com/ProcessMaker/processmaker-bpmn-moddle/issues/10).
- package.json was updated to use the lates version of processmaker-bpmn-moddle

Assign to User by Eval #1310 

---

ProcessMaker/Http/Controllers/Api/UserController.php
ProcessMaker/Policies/UserPolicy.php
ProcessMaker/Providers/AuthServiceProvider.php
routes/api.php

This PR solves the issue #1328
- User policy file added.
- Routes and controller modified to use the new policy.

User is unable to update own profile without "edit users" permission #1328

---

resources/views/admin/groups/edit.blade.php
resources/views/admin/users/edit.blade.php
resources/views/processes/categories/edit.blade.php
resources/views/processes/edit.blade.php
resources/views/processes/environment-variables/edit.blade.php
resources/views/processes/screens/edit.blade.php
resources/views/processes/scripts/edit.blade.php

all config and edit screens now have the same save/cancel buttons in secondary class.

updated all config/edit screens to have uniform buttons

---

resources/js/components/Comments.vue
resources/views/requests/show.blade.php
resources/views/tasks/edit.blade.php
resources/views/tasks/editdata.blade.php

- Change data editor to use monaco and edit data in JSON format.
Resolves: #1175

Use monaco to edit request data in JSON format

---

resources/views/shared/breadcrumbs.blade.php

sticky top for breadcrumbs

---

resources/views/admin/users/edit.blade.php

update admin to super admin

---

resources/views/layouts/navbar.blade.php

Fixes #1361 
- Delete unnecessary line to load avatar.

ErrorException: Creating default object from empty value

---

ProcessMaker/Console/Commands/Install.php

Closes #1374. Adds a step in the installer which checks to see if `php artisan schedule:run` has been installed as a cron job. If not, it installs it.

Add Laravel scheduled task cron job to installer

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue
resources/js/processes/modeler/components/inspector/TaskAssignment.vue

In the modeler screens, users, and groups are no longer only returning 10.

API returning 10

---

resources/views/processes/edit.blade.php

Fixes #1353 
- Fix error name field

No error message when trying to rename process to an existing name 

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
package-lock.json
resources/js/components/Comments.vue
resources/views/tasks/edit.blade.php

Fixes #1367 
- Now shows appropriate "request" or "task" data edited
- Add a title hover to show the ISO timestamp with seconds

Add appropriate text to comment when editing data

---

package-lock.json
package.json

Update modeler to 0.5.2

---

resources/views/processes/edit.blade.php

Removing excess Cancel Request field

---

tests/Feature/Api/ProcessTest.php

Fix to testStartProcessesWithPermission

---

database/seeds/DatabaseSeeder.php

Removing old default "Leave Absence Request" process. Closes #1436.

Remove ProcessSeeder from main seeder

---

ProcessMaker/Models/ProcessRequest.php

Solves #1452 
Code by mistake commented was restored

testRegisterIntermediateTimerEvents is failing #1452

---

resources/js/components/requests/notifications.vue
resources/js/processes/screens/components/ScreenListing.vue
resources/js/processes/scripts/components/ScriptListing.vue
resources/views/admin/groups/edit.blade.php
resources/views/admin/users/edit.blade.php
resources/views/processes/categories/index.blade.php
resources/views/processes/environment-variables/index.blade.php
resources/views/processes/index.blade.php
resources/views/processes/screens/index.blade.php
resources/views/processes/scripts/index.blade.php

closes #1453 
Modals now all say "cancel"
notification drop down has new css

UI clean up

---

resources/views/admin/users/edit.blade.php

Fixes #1394 
- Change layout edit user

Align UI layout for /profile/edit and /admin/users/*/edit

---

resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/initialLoad.js

Closes #1406. Improves the special assignment UI.

Improved special assignment UI

---

package.json

Closes #1461. Updates vue-form-builder to 0.10.2.

Updating vue-form-builder to latest

---

package-lock.json

Update package-lock with latest vue-form-builder

---

resources/views/admin/users/edit.blade.php

Fix buttons in permissions page

---

README.md

---logo updated
---license updated

Update logo and license info for Readme

---

resources/views/layouts/layout.blade.php
resources/views/layouts/minimal.blade.php

new favicon

---

ProcessMaker/Console/Commands/Install.php
composer.json
database/seeds/DatabaseSeeder.php
database/seeds/GroupSeeder.php

The installer has been updated to remove all of the setup for email, docker and cron to satisfy #1483

Updated Installer

---

resources/js/processes/screen-builder/screen.vue
resources/views/processes/screen-builder/screen.blade.php
tests/Browser/ScreenTest.php

Fixes #1493 
- Change custom styles in screen builder

Styles in screen builder

---

after.sh

Fixes #1456. Docker now installs property in new Vagrant machines.

Vagrant provisioning: fixing Docker install

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php

Add filter by id and participants in request search

---

resources/js/components/requests/modal.vue

Resolves #1535 
- Fix New Request label
Other fixes:

Fix New Request label.

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Http/Controllers/RequestController.php
ProcessMaker/Models/ProcessRequest.php

Resolves #1527 
- Add filter in Requests controller to filter completed from My Requests list
- Add scope NotCompleted in Request Model

Filter completed processes from My Requests

---

resources/views/auth/login.blade.php
tests/Feature/Api/ScriptsTest.php

closes #1488 
This also fixes the duplicate import of users in the scripts test

Fix unit tests

---

ProcessMaker/Console/Commands/Install.php

resolves #1515 
- Fix double colons install

Installer has double colons when asking for db questions

---

ProcessMaker/Http/Controllers/Api/NotificationController.php
ProcessMaker/Models/Process.php
ProcessMaker/Notifications/TaskOverdueNotification.php
database/migrations/2018_09_07_180640_create_process_request_tokens.php
resources/js/processes/modeler/components/inspector/TaskNotifications.vue

Resolves #1522 
- Implementation on due notifications
- Enable due notifications in modeler

Implement Due notifications

---

resources/js/admin/auth-clients/components/AuthClientsListing.vue

revolves #1552 
- Add message of confirmation delete auth client

Add Alert When Removing Auth

---

resources/js/processes/scripts/components/ScriptListing.vue

resolves #1551 
- Fix title in modal duplicate script

Duplicate Script

---

ProcessMaker/Models/DataStore.php
ProcessMaker/Repositories/TokenRepository.php
resources/js/processes/modeler/components/ModelerApp.vue
tests/Feature/WebhookTest.php

Resolves #1542 
- Add _user to request data when an activity (human task or script) is activated.
- Removes _user from request data when an activity (human task or script) is completed.

Add/remove current user in tasks.

---

resources/views/requests/show.blade.php

Remove extra space in the request detail page

---

package-lock.json
package.json
resources/js/processes/screen-builder/screen.vue

This PR uses the validation of control properties in the form-builder.
Fixes #1536

Use form builder validation.

---

resources/js/requests/components/RequestsListing.vue

Resolves #1519 
- Add request id Column in list Request and open link

Add Request ID Column 

---

resources/views/admin/users/index.blade.php

Resolves #1567 
- Add placeholder in dropdown status in form create user

New User Default Values

---

resources/views/admin/users/edit.blade.php
resources/views/tasks/edit.blade.php

Resolvers #1573 
- Change modal reassign element multiselect.

Task Reassign Modal

---

resources/js/processes/modeler/components/ModelerApp.vue

css navbar for modeler

---

resources/views/admin/auth-clients/index.blade.php

Resolves #1570 
- Change title edit auth client

Fix Auth-Client Title 

---

resources/js/processes/modeler/initialLoad.js

change order of modeler controls

---

resources/views/admin/users/edit.blade.php
resources/views/profile/edit.blade.php

Resolves #1612 
- Remove password of data when edit information user if field is empty.

Cant Save Profile without Password

---

resources/views/requests/show.blade.php

bring back cancel button

---

.circleci/config.yml
tests/Feature/Api/ScriptsTest.php

Update circleci config to point to QA-SparkBuilds

Qa sparkbuilds

---

composer.json

- Adds the PMQL project to Spark via composer.json
Closes #1665.

Requiring PMQL via Composer

---

ProcessMaker/Models/Process.php
resources/js/processes/components/ProcessesListing.vue
resources/views/processes/edit.blade.php
tests/Feature/Api/ProcessTest.php
tests/Feature/Api/processes/ProcessStartTimerEvent.bpmn

Resolves #1646 
- Process::hasTimerStartEvents() which returns true|false if the process has Timer Start Events.
- Show|Hide configuration option in Process List

Add a Play / Pause action button the the process list

---

resources/js/admin/users/components/UsersListing.vue
resources/lang/en.json

closes #1641 
@velkymx I know there wasn't a PRD for this but wanted something to work on, I can change anything we might want to.

avatar in user listing

---

resources/js/components/requests/modal.vue
resources/lang/en.json

update copy in request modal and en file

---

resources/js/admin/groups/components/UsersInGroupListing.vue
resources/js/notifications/components/NotificationsList.vue
resources/js/tasks/components/TasksList.vue

closes #1683 
Auth clients were handled in a different ticket but I did find a few more places where $t was being properly references as this.$t

Transaltions causing errors

---

resources/views/processes/scripts/edit.blade.php

remove language select in script config 

---

resources/views/admin/users/edit.blade.php
resources/views/admin/users/index.blade.php
resources/views/processes/index.blade.php
resources/views/processes/screens/index.blade.php
resources/views/processes/scripts/index.blade.php
resources/views/profile/edit.blade.php

closes #1722 
also please be aware that the profile/user edit screen will have some empty values but they are resolved in https://github.com/ProcessMaker/spark/pull/1721

set placeholder for selects

---

ProcessMaker/Models/Script.php
tests/Feature/Api/ScriptsTest.php

make script description required

---

build_script.sh

The following script allows to create a tar.gz ready to be distributed to the public. 
it works in Linux environments with the Spark Development stack installed.
At the beginning will ask for the final name of the installer
The tar.gz file will be placed inside the spark folder.

script to automatically build a installer

---

resources/views/processes/screens/edit.blade.php

remove type select in screen config

---

database/factories/ProcessFactory.php
tests/Feature/Shared/ResourceAssertionsTrait.php

Resolves #1700 
- Fix process factory to prevent to load process from hidden files

Fix process factory and test validation

---

ProcessMaker/Jobs/ImportProcess.php
ProcessMaker/Jobs/ImportScreen.php
ProcessMaker/Models/Screen.php

resolves #1697 
- Save custom_css when importing process

Custom CSS Import broken

---

resources/js/processes/modeler/components/ModelerApp.vue

fix non standard modal for bpmn upload

---

ProcessMaker/Http/Middleware/GenerateMenus.php

change Env Var icon

---

resources/js/processes/screen-builder/typeForm.js

Resolves #1746 
Code to add a regular expression validation for the variables was included at the moment of adding spark custom elements (e.g. File Upload, Download, etc.)

Validate Data Name 

---

resources/js/processes/screens/components/ScreenListing.vue

- Fixes a translation issue which caused an error when duplicating a screen
Fixes #1751.

Show confirmation when duplicating a screen

---

resources/views/processes/edit.blade.php

remove notify request started

---

resources/views/shared/breadcrumbs.blade.php
resources/views/tasks/edit.blade.php

Do not link breadcrumb if the user does not have access

---

resources/js/notifications/components/NotificationsList.vue

resolves #1718 
- Add request id in list notifications

Notifications List Request ID

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Models/ProcessRequest.php
tests/Feature/Api/ProcessRequestsTest.php

Resolves #1682 
- Tests to validate the behavior added.
- Canceled requests are show in completed and all requests only.

Remove Canceled Request from My Requests

---

ProcessMaker/Http/Controllers/Api/TaskController.php
resources/js/tasks/components/TasksList.vue

Fix request task list

---

resources/js/processes/screen-builder/screen.vue

Fix screen builder style

---

resources/js/processes/categories/components/CategoriesListing.vue

Fix category show create new

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Jobs/CancelRequest.php

Resolves #1797 
This PR resolves the CANCEL request status.

Fix cancel status

---

ProcessMaker/Http/Controllers/ProfileController.php
ProcessMaker/i18nHelper.php
resources/js/bootstrap.js
resources/views/layouts/layout.blade.php

Fixes #1802 
Automatically invalidate cache when a language file changes

Add cache invalidator for languages

---

resources/views/processes/edit.blade.php

Closes #1796 
I was only able to find it in the config of processes

Remove Lorem Ipsum

---

resources/js/components/Comments.vue

fix path to system user image

---

resources/js/processes/screen-builder/screen.vue
resources/js/processes/screen-builder/typeDisplay.js
resources/js/processes/screen-builder/typeForm.js
resources/js/tasks/components/TaskForm.vue
resources/js/tasks/components/TaskView.vue

Changes required to integrate the new design update from https://github.com/ProcessMaker/spark-screen-builder/pull/164.

Fix Screen builder design

---

resources/js/app-layout.js
resources/js/tasks/components/TaskForm.vue
resources/views/layouts/navbar.blade.php

Resolves #1717 
- A new parameter for window.ProcessMaker.alert =
function (msg, variant, showValue = 60, **stayNextScreen** = false)
This parameter keeps could be used to keep an alert message after a redirect.
- Add a Task Completed Alert after a task is completed.

Add Task Completed Alert

---

resources/js/processes/modeler/components/ModelerApp.vue
resources/js/processes/modeler/initialLoad.js

This PR contains changes to integrate the new modeler re-design.
Once https://github.com/ProcessMaker/spark-modeler/pull/359 has been merged, and a new version of `"@processmaker/spark-modeler` has been published, this PR will be updated to point to the new modeler re-design release.

Fix modeler integration

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue

Resolves #1698 
This PR includes the following changes:
- Add a validation to the screen selector value and check if the screen exists in the system.
- This change also applies to tasks.
- If does not exists it shows a error message:

Validate if select screen exists.

---

resources/views/requests/show.blade.php

Fix Request Status Created

---

public/definitions/ProcessMaker.xsd

Fixes #1815 
Will be used to save web entry settings in the bpmn, like how email connector does

Update definition to include config json on start event

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue

Optionally show error if screen is not selected in ScreenSelect compoent

---

.babelrc
resources/js/processes/screen-builder/screen.vue
webpack.mix.js

Related to design updates in screen builder PR https://github.com/ProcessMaker/spark-screen-builder/pull/164.

Update markup and styles

---

package-lock.json
package.json

Use new bpmn-moddle version

---

ProcessMaker/Jobs/RunScriptTask.php

Resolves #1824 
This PR changes the script error message when no script is assigned;

Fix exception message for empty script tasks

---

resources/js/processes/modeler/components/inspector/ConfigEditor.vue

Update highlighted node in config editor

---

resources/js/processes/modeler/components/inspector/ConfigEditor.vue
resources/js/processes/modeler/components/inspector/ExpressionEditor.vue

Fix config editor and expression editor

---

ProcessMaker/Http/Controllers/Api/ScreenController.php

Do not strip html tags from rich text content

---

ProcessMaker/Jobs/ImportProcess.php

- Adds a check for previous package names when importing Spark files
Closes #1856.

Handle backwards compatibility with old packages on import

---

resources/js/processes/modeler/components/inspector/TaskAssignment.vue

resolves #1840 
- Adjust width of panel  assign by expression

Assign by Expression UI

---

package-lock.json
package.json

Resolves #1850 
Croppie version has been reverted to 1.3.12

Avatar Upload Broken

---

resources/views/requests/show.blade.php
resources/views/tasks/edit.blade.php
resources/views/tasks/editdata.blade.php

fix margin in request screens

---

ProcessMaker/Facades/WorkflowManager.php
ProcessMaker/Http/Controllers/ProcessController.php
ProcessMaker/Jobs/BpmnAction.php
ProcessMaker/Jobs/RunScriptTask.php
ProcessMaker/Jobs/RunServiceTask.php
ProcessMaker/Managers/WorkflowManager.php
ProcessMaker/Traits/HasControllerAddons.php
resources/js/bootstrap.js
resources/js/components/requests/card.vue
resources/js/tasks/components/TaskForm.vue
resources/views/processes/edit.blade.php

Implements changes required for package Vocabularies

---

ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Providers/WorkflowServiceProvider.php
resources/js/processes/modeler/initialLoad.js
resources/views/tasks/edit.blade.php
tests/Feature/Api/ProcessManualTaskTest.php
tests/Feature/Api/processes/ManualTask.bpmn

Resolves #1874
Requires: https://github.com/ProcessMaker/spark-modeler/pull/401

Implementation of Manual Tasks

---

resources/views/tasks/edit.blade.php

This PR fix the way to check if a task is a ManualTask.

Fix check manual task tag name

---

resources/js/app-layout.js

resolves #1864 
- Validate redirect login in error api with error 401

Cannot read property 'status' of undefined

---

resources/js/processes/categories/components/CategoriesListing.vue

resolves #1877 
- Remove code of old pagination

The list of categories does not show paging.

---

resources/js/processes/screen-builder/components/form/file-upload.vue

Wait for the files to load

---

ProcessMaker/Models/User.php
database/migrations/2014_10_12_000000_create_users_table.php

Resolves #1827 
Soft delete added to user table
soft deletes added to user model

When deleting a user everything they have ever created is deleted

---

resources/js/components/requests/notifications.vue
resources/views/processes/import.blade.php

closes #1830 
I also fixed a few other hard coded colors

Theme fixes

---

resources/js/processes/screen-builder/screen.vue
resources/js/processes/screen-builder/typeForm.js
resources/js/tasks/components/TaskForm.vue

This PR accompanies https://github.com/ProcessMaker/spark-screen-builder/pull/213 and provides fixes for the same issues mentioned in that PR. Both that PR and this one should be merged together for a complete fix.

Load initial config by default

---

resources/views/processes/import.blade.php

fix padding for upload button

---

resources/js/processes/modeler/components/ModelerApp.vue

remove old xml upload

---

ProcessMaker/Http/Middleware/GenerateMenus.php

change sidebar title to My requests

---

ProcessMaker/Http/Controllers/RequestController.php
ProcessMaker/Policies/ProcessRequestPolicy.php
resources/views/layouts/minimal.blade.php
resources/views/requests/index.blade.php

closes #1906 
fixed the auth check so it now respects the "view all requests" permission.
to test: create a new user and give them "view all requests" permissions, login as that user and see all of the beautiful requests

All Requests Permission Broken

---

resources/js/tasks/components/TaskView.vue
tests/Browser/ScreenTest.php

resolves #1924 
- Import elements in task view

Unknown custom elements

---

resources/js/components/AvatarImage.vue
resources/js/components/NavbarProfile.vue

- Fixes issue with avatar menu not appearing on certain saved search pages
Fixes #1910.

Fixing issue with avatar menu in Saved Search

---

resources/lang/en.json
resources/views/admin/users/edit.blade.php
resources/views/admin/users/index.blade.php

add job title edit

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/PmqlHelper.php

Fixes #1943 - Needed for Pulses

Refactor pmql helpers into their own file

---

config/database.php

Fixes database connection issue if using other hostname than localhost

---

resources/js/tasks/components/TaskForm.vue

Fixes https://github.com/ProcessMaker/spark-screen-builder/issues/222.
Video of working datepicker: https://www.dropbox.com/s/dno7g8y0dw4uoug/datepicker_fixed_styling.mov?dl=0

Fix datepicker styling

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Http/Resources/ProcessRequests.php
resources/sass/sidebar/sidebar.scss
resources/views/layouts/sidebar.blade.php
tests/Feature/Api/ProcessRequestsTest.php

closes #1953 
this PR will need to be merged before https://github.com/ProcessMaker/spark-package-savedsearch/compare/feature/3?expand=1

Process Request API: return data, sort by data field

---

resources/views/profile/show.blade.php

resolves #1967 
- remove style in contact information

User Profile Layout Issue

---

ProcessMaker/PmqlHelper.php

- Fixes an issue where we could not search by process request name
Before
After
Fixes #1996.

Bugfix to PMQL helper

---

resources/js/processes/modeler/initialLoad.js
resources/views/tasks/edit.blade.php

Resolves #1965 
- Add assignment configuration for Manual Tasks in the modeler
- Fix Manual Task execution template
Attachments:
[manual_task.spark.zip](https://github.com/ProcessMaker/spark/files/3281326/manual_task.spark.zip)

Reassign Manual Task

---

resources/js/components/requests/modal.vue

resolves #1949 
- Load  of processes start is only called when opening modal

New Request Modal population

---

resources/js/admin/queues/index.js

resolves #1962 
- change interceptor request horizon

Horizon 404s

---

ProcessMaker/Models/ProcessRequest.php
composer.json
composer.lock
phpunit.xml
tests/Feature/Api/ProcessRequestsTest.php
tests/Feature/RequestTest.php

Fixes #1994 
Count was including canceled. Fixed that

Fix completed process count

---

resources/js/components/AvatarImage.vue

Do not add cache buster to base64 encoded images

---

phpunit.xml

Specify the data database for testing

---

tests/Browser/ScreenTest.php

Resolves #1973 
Incorrect selector and browser resizing the browser were fixed

testHideControls Test Failing 

---

ProcessMaker/PmqlHelper.php

- Fixes issue with PMQL data searches returning a 500 error
Fixes #2021.

Checking for string type on PMQL aliases

---

tests/Browser/RequestListTest.php

Resolves #1995 
Tests that browse the requests lists and verify that no error messages are displayed were added.

All Requests 500

---

ProcessMaker/Console/Commands/Install.php

Resolves #2000 
- Add input to configure the data connection in Spark Installer

Update Spark Installer

---

ProcessMaker/Repositories/ExecutionInstanceRepository.php
ProcessMaker/Repositories/TokenRepository.php
composer.lock
database/migrations/2018_09_07_180640_create_process_request_tokens.php

Resolves #2013 
- Update Nayra version
- Save and update gateway tokens

Fix missing gateway tokens

---

resources/js/processes/modeler/components/ModelerApp.vue

Required for testing purposes for Modeler.

Add data-test attribute to save button

---

resources/js/processes/screen-builder/typeDisplay.js
resources/js/processes/screen-builder/typeForm.js

File Upload/Download and typeDisplay form builder were missing icons

Fix missing icons

---

resources/js/processes/modeler/components/inspector/ConfigEditor.vue

Resolves #1990 
This PR fix the Script Config popup size

Fix script config popup

---

resources/js/processes/screens/components/ScreenListing.vue
resources/lang/en.json
tests/Feature/Api/ScreenTest.php

Resolves #2031 
- Change the copy screen title.

Change copy screen title

---

package-lock.json
package.json

Resolves #2027 
This PR removes the fs package because it is internal.

Remove fs package

---

resources/js/components/NavbarProfile.vue

new link to gitbook

---

resources/js/processes/screen-builder/typeDisplay.js

**Spark Video Demo**
https://drive.google.com/open?id=14vjkZyP4UwxB_PbsDmTAm8euXWF9QbhX
Fix https://github.com/ProcessMaker/screen-builder/issues/267

Fix missing rich text component in display form builder

---

resources/js/processes/modeler/initialLoad.js

Fixes https://github.com/ProcessMaker/modeler/issues/448.

Fix node ID references

---

resources/js/processes/scripts/components/ScriptListing.vue
resources/lang/en.json
tests/Feature/Api/ScriptsTest.php

Resolves #2032
- Change copy script title

Change copy script title

---

resources/js/processes/modeler/components/inspector/TaskAssignment.vue

Resolves #2066 
- Fix use of __() by $t() in task assignment component
- Add missing data variable definition

Fix task assignment component

---

resources/js/processes/modeler/components/ModelerApp.vue
resources/views/processes/index.blade.php
resources/views/processes/modeler/index.blade.php
resources/views/shared/breadcrumbs.blade.php

This PR is for fixing https://github.com/ProcessMaker/modeler/issues/453 in `processmaker`. The associated PR in `modeler` is https://github.com/ProcessMaker/modeler/pull/454.

Fix modeler container padding

---

resources/js/processes/screen-builder/screen.vue

This PR is for fixing https://github.com/ProcessMaker/screen-builder/issues/269 in `processmaker`. The associated PR in `screen-builder` is https://github.com/ProcessMaker/screen-builder/pull/270.

Screen builder style updates

---

resources/js/processes/modeler/components/ModelerApp.vue
resources/views/processes/index.blade.php
resources/views/processes/modeler/index.blade.php
resources/views/shared/breadcrumbs.blade.php

This update breaks too much of the UI. Need to test better. Reverts ProcessMaker/processmaker#2048

Revert "Fix modeler container padding"

---

resources/js/processes/screen-builder/typeDisplay.js

**Spark Video Demo**
https://drive.google.com/open?id=1rYsw3sjBKlWwz5HkszULhvnVj6Egu7ny
Fixes https://github.com/ProcessMaker/screen-builder/issues/159 (Screen Builder Repo)

Screen Builder: controls incomplete in type display

---

resources/js/processes/screen-builder/formTypes.js
resources/js/processes/screen-builder/screen.vue
resources/js/processes/screen-builder/typeDisplay.js

Fixes https://github.com/ProcessMaker/screen-builder/issues/280.
Video of fix: https://www.dropbox.com/s/uvv6vj7fnilsyqv/required_save_button.mov?dl=0.

Require submit button for form screen type

---

resources/js/processes/modeler/components/ModelerApp.vue
resources/views/processes/index.blade.php
resources/views/processes/modeler/index.blade.php
resources/views/shared/breadcrumbs.blade.php

This PR reverts the changes in https://github.com/ProcessMaker/processmaker/pull/2086/commits/12f13d37fc0de9b7b05c66e377cc4e9452c691e2 and fixes the margin issues without affecting other pages in the app.
Related PR: https://github.com/ProcessMaker/processmaker/pull/2096#issue-296019275.
Video of fix: https://www.dropbox.com/s/q7umrip824295rr/margins_fixed.mov?dl=0.

Fix modeler layout

---

resources/lang/en.json
resources/views/processes/modeler/index.blade.php

resolves #2052 
- Change modeler breadcrumbs

Modeler Breadcrumbs

---

resources/lang/en.json
resources/views/requests/show.blade.php

resolves #2075 
- add validation when the summary has no data

Request Summary No Data

---

resources/js/processes/categories/components/CategoriesListing.vue

Resolves #2092 
The name of the parameter send in the query string was corrected

Process Category Pagination

---

resources/js/components/requests/card.vue

Redirect to request show page after starting a request

---

resources/lang/en.json

- Fixes an issue that was preventing lang file (and thus the entire app) from loading
Fixes #2137.

Fix invalid JSON

---

resources/js/processes/screen-builder/screen.vue

Fixes https://github.com/ProcessMaker/screen-builder/issues/291.

Fix submit button validation

---

ProcessMaker/Policies/ProcessRequestPolicy.php
routes/api.php
tests/Feature/Api/RequestFileUploadTest.php
tests/Feature/Api/processes/FileUpload.bpmn

Resolves #2084 
- Test to verify user permission
- Fix request file upload permissions to include the assigned user
[upload_file.json.txt](https://github.com/ProcessMaker/processmaker/files/3393099/upload_file.json.txt)

Fix request file upload permissions

---

resources/views/processes/categories/index.blade.php

resolves #2073 
- Add dropdown status in create modal category.
- After create category refresh list categories

Modal Process Category Status

---

.circleci/config.yml
tests/Feature/Api/RequestFileUploadTest.php

Fix phpunit/circleci

---

resources/js/processes/modeler/components/ModelerApp.vue
resources/views/layouts/layout.blade.php

**Spark Video Demo**
https://drive.google.com/open?id=1pmVDo1NFREUliXp_jjcrE5_R37aAYSHF
PR from modeler(https://github.com/ProcessMaker/modeler/pull/483) needs to merged for fix.

Fix drag-drop on safari on modeler

---

resources/js/processes/screen-builder/typeForm.js

Resolves #1746 
The field name has been corrected and now the validation is applied

fix to field name to be validated

---

ProcessMaker/PmqlHelper.php

Resolves #2112 
Methods that maps task table aliases were added in the PmqlHelper.php file

Add aliases for counting tasks with PMQL

---

resources/js/components/NavbarProfile.vue

As reported in https://processmaker.atlassian.net/browse/FOUR-480

Removed invalid URL for "Get Help" link on user nav drop-down menu.

---

ProcessMaker/Providers/WorkflowServiceProvider.php

Resolves #2174 
This PR skip loading BPMN non implemented elements
When BPMN has broken references it shows a validation message.

Skip loading BPMN non implemented elements

---

.circleci/config.yml

Commented out SauceLabs

---

resources/js/requests/components/RequestsListing.vue
resources/js/tasks/components/TasksList.vue

Changed the request and task detail to sort by the ID DESC by default. In the task screen I added the Task ID as a new column.
Closes #2194

Default Sorting Changed

---

resources/js/processes/screen-builder/typeForm.js

This PR is required to complete the changes in https://github.com/ProcessMaker/screen-builder/pull/311.

Update File Upload/Download configs

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
ProcessMaker/Jobs/ExportProcess.php
ProcessMaker/Jobs/ImportProcess.php

resolves #2185 
- Add import/Export screen manual task.
- add import/export assignment manual task.

Process Export Missing Manual Task Screens

---

resources/views/layouts/layout.blade.php

Related PR: https://github.com/ProcessMaker/screen-builder/pull/312.
This PR is required to complete the fix for https://github.com/ProcessMaker/screen-builder/issues/306.

Fix content overflow

---

ProcessMaker/Jobs/CompileSass.php

Resolves #2205 
The route to access the font Open Sans is fixed

Fix route to Open Sans font

---

tests/Feature/Api/IntermediateTimerEventTest.php

Login User for test - fixes failing test

---

resources/views/tasks/edit.blade.php
resources/views/tasks/editdata.blade.php

Resolves #2147 
- Add resize in editor detail task

Data Editor Too Small

---

composer.json
composer.lock

Resolves #2216 
- Remove debug bar.
- require library mustache

Remove Debug Bar

---

resources/js/processes/screen-builder/screen.vue

Fixes https://github.com/ProcessMaker/screen-builder/issues/325.
Video of fix: https://www.dropbox.com/s/9v2fi3gk9kcqf9j/submit-validation-working.mov?dl=0.

Validate nested submit buttons

---

resources/js/processes/modeler/initialLoad.js

Add boundary events to list of node types.

Add boundary events

---

webpack.mix.js

Add tinymce resources

---

resources/js/processes/screen-builder/components/file-download.vue
resources/js/requests/components/screenDetail.vue
resources/views/requests/preview.blade.php

Resolves #2238 
- disable elements in view print.

Request Forms Are Editable

---

ProcessMaker/BpmnEngine.php
ProcessMaker/Jobs/BpmnAction.php
ProcessMaker/Models/CallActivity.php
ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Providers/WorkflowServiceProvider.php
tests/Feature/Api/CallActivityTest.php
tests/Feature/Api/processes/child.bpmn
tests/Feature/Api/processes/parent.bpmn
tests/Feature/Shared/ProcessTestingTrait.php

Resolves #2240
- Fix CallActivity synchronization 
- Add test for CallActivity with external process definitions

Fix Call Activity Element

---

resources/js/processes/screen-builder/screen.vue

This PR is required to complete the fixes in https://github.com/ProcessMaker/screen-builder/pull/346.

Fix nested validation

---

resources/lang/en.json
resources/sass/admin/queues.scss
resources/views/admin/cssOverride/edit.blade.php

Resolves #2273 
The dark variable has been added. In our site, currently is used just in the queues.css file.

Customize UI: Dark

---

resources/js/processes/screen-builder/screen.vue
resources/js/processes/screen-builder/typeDisplay.js

- Remove the text component in controls and replace it with the rich text component
- Pass additional screen type prop for disabling toolbar in typeDisplay

Add additional prop to screen-builder

---

resources/views/processes/scripts/index.blade.php

Resolves #2279 
Problem fixed and User list was moved to a vue component

Create Script - Run Script As is empty

---

ProcessMaker/Http/Controllers/AboutController.php
resources/views/about/index.blade.php

Displays installed packages on the about page.
closes #2287

List Installed Packages

---

ProcessMaker/Managers/TaskSchedulerManager.php
composer.lock
config/app.php
tests/unit/ProcessMaker/Managers/TaskSchedulerManagerTest.php

Resolves #2284 
- Remove seconds when calculate when a timer event should be triggered.
- Add a config "app.timer_events_seconds" to configure the method to remove seconds: truncate, round
- Add unit test for remove seconds methods

Remove seconds to calculate when a timer event should be triggered.

---

resources/lang/de.json
resources/lang/en.json
resources/lang/es.json
resources/lang/fr.json

Fix translation for Event-Based Gateway.
closes #2186

Fix translation for 'Event-Based Gateway' Modeler

---

resources/lang/de.json
resources/lang/en.json
resources/lang/es.json
resources/lang/fr.json

Upload a new translation .json file.
closes #2064

Add missing translations

---

resources/js/admin/auth-clients/components/AuthClientsListing.vue
resources/js/admin/groups/components/GroupsListing.vue
resources/js/admin/users/components/UsersListing.vue
resources/js/components/common/DataLoading.vue
resources/js/processes/categories/components/CategoriesListing.vue
resources/js/processes/components/ProcessesListing.vue
resources/js/processes/environment-variables/components/VariablesListing.vue
resources/js/processes/screens/components/ScreenListing.vue
resources/js/processes/scripts/components/ScriptListing.vue
resources/js/requests/components/RequestsListing.vue
tests/js/processes/categories/components/CategoriesListing.test.js

Resolves #2256 
- Jest tests fixed to work with new loading icon
- All lists shows a "Loading..." icon 
- In case that the list is empty, a "No Data Available" message is displayed

Vuetables Loading

---

ProcessMaker/Managers/TaskSchedulerManager.php
ProcessMaker/Models/CallActivity.php
ProcessMaker/Models/ScheduledTask.php
ProcessMaker/Models/TimerExpression.php
composer.lock

Resolves #2295 
- Fix calculation of timer events inside boundary events
- Fix boundary timer events in call activity

Fix Duration timer in boundary timers events

---

ProcessMaker/Managers/TaskSchedulerManager.php

Resolves #2305 
Fix carbon test now for timer events tests.

Fix carbon test now in Timer Tests

---

ProcessMaker/Models/FormalExpression.php
tests/Model/FormalExpressionTest.php

Resolves #2307 
- Add mustache syntax in evaluate expression

Allow for mustache syntax before Evaluate Expression

---

resources/js/processes/scripts/components/ScriptListing.vue
resources/views/admin/auth-clients/index.blade.php
resources/views/admin/groups/index.blade.php
resources/views/admin/users/index.blade.php
resources/views/processes/index.blade.php
resources/views/processes/scripts/index.blade.php

Add Asterisk to the required fields in modals.
closes #2333

Add an Asterisk on required fields in modals

---

ProcessMaker/Http/Middleware/GenerateMenus.php

Changed string "Request All" to "All Requests" in
* `ProcessMaker/Http/Middleware/GenerateMenus.php`
* The string for en.json has already been merged into develop
* The strings have been updated for DE/FR/ES languages here: ProcessMaker/package-translations#16

Changed string "Request All" to "All Requests" (take 3)

---

database/factories/ProcessRequestTokenFactory.php

Resolves #2343 
- Process Request Token faker generates dates betwee -15 years and the current date.

Circle CI tests are failing in performance tests

---

resources/views/about/index.blade.php

- Updates about screen to **Beta 9**
Closes #2352.

Update About screen to Beta 9

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
ProcessMaker/Models/Process.php
ProcessMaker/Traits/ProcessTimerEventsTrait.php
composer.lock
database/factories/ProcessFactory.php
database/migrations/2019_09_03_190137_add_warnings_to_processes.php
database/migrations/2019_09_03_212228_add_warnings_to_process_versions_table.php
package-lock.json
package.json
resources/js/processes/components/ProcessesListing.vue
resources/js/processes/modeler/components/ModelerApp.vue
resources/lang/en.json
resources/views/about/index.blade.php
resources/views/processes/modeler/index.blade.php
tests/Feature/Api/ConvertBPMNTest.php
tests/Feature/Api/processes/CP.01.00 Create new customer.bpmn
tests/Feature/Api/processes/adonis.bpmn

Conversion of not supported BPMN elements:
-  subProcess -> callActivity
- sendTask -> scriptTask
[diagram_3.bpmn.txt](https://github.com/ProcessMaker/processmaker/files/3571580/diagram_3.bpmn.txt)
to:

Feature convert elements

---

resources/js/processes/modeler/initialLoad.js

Closes #2397 
Added Boundary Timer Event to menu.
Grouped Intermediate Message Catch Event with other events, instead of leaving it at the bottom of the menu.

Added Boundary Timer Event

---

resources/js/processes/screen-builder/components/form/file-upload.vue
resources/js/processes/screen-builder/typeDisplay.js
resources/js/processes/screen-builder/typeForm.js

Fixes #2414 
Required for https://github.com/ProcessMaker/screen-builder/issues/401

Fix upload and download components

---

resources/js/processes/screen-builder/screen.vue
resources/js/requests/components/screenDetail.vue
resources/js/tasks/components/TaskForm.vue
resources/js/tasks/components/TaskView.vue

Fixes #2417 
- Emits a form update event on the global event bus, needed by new Collection Select control
- Supports changes in [ProcessMaker/package-collections#130](https://github.com/ProcessMaker/package-collections/pull/130)

Emitting form update event on global event bus

---

resources/js/processes/screen-builder/typeDisplay.js

Fixes #2408 
Needs https://github.com/ProcessMaker/screen-builder/pull/404

Updates for record list

---

resources/js/processes/modeler/initialLoad.js

Closes #2411 
Moved eventBasedGateway near gateways.
There only seemed to be one control that was not near similar controls. If the order should be changed to a specific order, let me know @velkymx.

Move like controls together

---

ProcessMaker/Http/Controllers/Api/UserController.php
ProcessMaker/Models/User.php
resources/js/admin/users/components/AddUserModal.vue
resources/js/admin/users/index.js
resources/views/admin/users/index.blade.php
routes/api.php
tests/Feature/Api/UsersTest.php

This PR adds the ability to restore soft-deleted users.
**To Test:**
- Create a user
- Delete a user
- Try to recreate the same user (same username and or same email)
**Result:**
A modal appears that indicates a deleted user exists with the email address or username and asks if they would like to restore the user.
If they select 'save', then restore the user.

Soft Deleted User Restore

---

ProcessMaker/Http/Controllers/Api/UserController.php
resources/js/processes/scripts/components/ScriptEditor.vue
resources/js/processes/scripts/customFilters.js

This PR adds a boilerplate template to newly created scripts in all supported programming languages. 
Closes #2252 #2158

Add boilerplate code to new scripts

---

resources/views/tasks/edit.blade.php

Resolves #2440 
- Fix data loading in task screens, to fix grid data rendering

Fix data loading in task screens

---

resources/js/processes/screen-builder/typeDisplay.js

resolved #2423 
- remove item duplicate.
- add global properties.

Form type diplay record list duplicated

---

ProcessMaker/Models/Process.php

Fix logic for checking if a task can be anonymous

---

ProcessMaker/Models/CategoryAssignment.php
ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessCategory.php
ProcessMaker/Models/Screen.php
ProcessMaker/Models/ScreenCategory.php
ProcessMaker/Models/Script.php
ProcessMaker/Models/ScriptCategory.php
ProcessMaker/Traits/HasCategories.php
ProcessMaker/Traits/HideSystemResources.php
database/migrations/2019_09_30_192339_create_category_assignments_table.php
package-lock.json
resources/js/processes/categories/components/CategorySelect.vue
resources/js/processes/components/ProcessesListing.vue
resources/js/processes/edit.js
resources/js/processes/screens/components/ScreenListing.vue
resources/js/processes/scripts/components/ScriptListing.vue
resources/views/processes/edit.blade.php
webpack.mix.js

Resolves #2428 
- Changes in Migrations, Model, Views, Vue components to support multiple categories for: Processes, Screens and Scripts

Implement multiple categories for Process/Screens/Scripts

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
resources/js/app-layout.js
resources/js/components/common/DataLoading.vue
resources/js/requests/components/RequestsListing.vue
tests/Browser/LoginTest.php
tests/Browser/Pages/RequestsPage.php
tests/Browser/RequestsSearchTest.php
tests/Browser/RequestsTest.php
tests/Browser/mysql_backup.sh
tests/Browser/mysql_restore.sh
tests/DuskTestCase.php

Fixes #2360 
- Output useful error messages for request pmql search
- Move frontend error handling responsibilities to appropriate places

Output useful error messages for request pmql search

---

package-lock.json
package.json
resources/js/processes/modeler/initialLoad.js

- Updated Modeler project to 0.17.2
- Removed duplicated node setup code from project in favour of calling exported function from Modeler.

Removed duplicated node registration code.

---

resources/js/processes/modeler/components/inspector/TaskAssignment.vue

Resolves #2458 
- Fix refresh information task assigment

Process designer - Assigned user dropdown is not refreshed

---

ProcessMaker/Http/Controllers/Process/ScriptController.php
resources/js/processes/scripts/components/ScriptEditor.vue
resources/views/processes/scripts/builder.blade.php

Resolves #2449 
- Adds mocked _user and _request magic variables for script preview.

Mock _user, _request variables for script preview

---

package-lock.json
package.json

This is required to complete the fix for ProcessMaker/modeler#757.

Update screen builder

---

composer.lock

- Regenerates composer.lock file and removes references to local PMQL instance that was causing `Source path "/home/vagrant/processmaker-plugins/pmql" is not found for package processmaker/pmql` error message
Fixes #2476.

Regenerate composer.lock

---

ProcessMaker/Http/Controllers/Api/FileController.php

To test, use the provided export. The file will upload via the script and then be available as a download in the next task.
[test.json.txt](https://github.com/ProcessMaker/processmaker/files/3795771/test.json.txt)

Fix for script file uploads

---

ProcessMaker/Http/Middleware/GenerateMenus.php
resources/js/components/NavbarProfile.vue
resources/sass/app.scss
resources/views/about/index.blade.php

This update resolves #2575 
Changes:
- Profile menu changed to use list group
- Profile menu cleaned up to removed duplicate links
- About menu updated to change report bug to github issue
- About page updated to remove Get Help link
- About menu updated to change report bug to github issue
- Changed text to Profile Settings
- Added View Profile

Profile and About Pages Refreshed

---

ProcessMaker/Models/Screen.php
ProcessMaker/Models/Script.php
ProcessMaker/Validation/CategoryRule.php
tests/Feature/Api/ScreenTest.php
tests/Feature/Api/ScriptsTest.php

Make category required for screens and scripts

---

ProcessMaker/Traits/MakeHttpRequests.php

- fix types authentication oauth2
- set verify certicate to false

Evaluate data source with SSL certificate fails.

---

ProcessMaker/Http/Controllers/Api/ScreenController.php
ProcessMaker/Http/Controllers/Api/ScriptController.php
tests/Feature/Api/ScreenTest.php
tests/Feature/Api/ScriptsTest.php

resolves #2574 
- add query for filter screen and scripts
- add test

Filter Categories for Screens and Scripts

---

ProcessMaker/Models/Screen.php
ProcessMaker/Models/Script.php
ProcessMaker/Validation/CategoryRule.php
tests/Feature/Api/ScreenTest.php
tests/Feature/Api/ScriptsTest.php

Fixes #2581 
Steps to test:
- Create a new screen. Add an element and save it. If it saves without error then the fix works
- Create a new script. Edit the code and save. If it saves with out error then the fix works

Fix screen and script category requirements

---

ProcessMaker/Models/User.php

Fixes #2550 
expires_at shouldn't be editable so I took it out of the fillable array. Added validation for birthdate

Add date validation and remove unused guarded array for User

---

database/seeds/CategorySystemSeeder.php
database/seeds/DatabaseSeeder.php

Resolves #2552 
- Add seeder for:
- processes
- screens
- scripts

Add default category

---

resources/js/processes/categories/index.js
resources/views/categories/list.blade.php

- Switches back to the resources tab after creating a resource category
Closes #2514.

Changing default behavior after creating category

---

resources/js/app-layout.js
resources/js/processes/screen-builder/components/file-download-control.js
resources/js/processes/screen-builder/components/file-download.vue
resources/js/processes/screen-builder/components/file-upload-control.js
resources/js/processes/screen-builder/components/form/file-upload.vue
resources/js/processes/screen-builder/typeDisplay.js
resources/js/processes/screen-builder/typeForm.js
resources/js/requests/components/screenDetail.vue
resources/js/tasks/components/TaskForm.vue

Fixes #2580 
Requires these PRs
https://github.com/ProcessMaker/package-webentry/pull/38
https://github.com/ProcessMaker/package-collections/pull/156
Test file upload component works for a screen
- in a regular task
- in a web entry start event
- in an intermediate web entry task
- in a collection add and edit record
Test file download component works for a screen
- in a regular task
- in an intermediate web entry task
- that is a summary display screen
- in a collection view

Fix file upload and download components

---

resources/js/tasks/components/TaskForm.vue

closes #2545
- Disable additional clicks in submit form
- in run case, click several times on the submit form button.

Task Submit Button

---

ProcessMaker/Models/User.php

closes #2537 
- Add rule max digits in fields firstname and lastname (Model User)
- Edit information of user and save.

Edit User Vue Errors

---

resources/views/profile/edit.blade.php

closes #2589 
- Add field title in edit Profile
- Enter edit profile, and view the new field job title

Change Title

---

ProcessMaker/Models/ScreenVersion.php

Fixes #2608 
Need to cast watchers field the same way as the base model

Cast watchers correctly in screen versions

---

tests/Feature/Api/ScreenTest.php
tests/Feature/Api/ScriptsTest.php
tests/Feature/OnSiteStorage/OnSiteStorageTest.php
tests/Feature/Processes/ExportImportTest.php
tests/Feature/Processes/ScriptUserTaskTest.php
tests/Feature/Shared/ResourceAssertionsTrait.php

Skip tests until versioning problems can be addressed

---

resources/js/components/NavbarProfile.vue
resources/views/profile/show.blade.php

Resolves #2539 
The Profile Menu and profile view screen were modified as is shown in the next screen captures:
**Before:**
----------------------------
**After:**
-----------------------------------

Profile Menu Username 

---

ProcessMaker/Models/DataSource.php
ProcessMaker/Models/DataSourceCategory.php
ProcessMaker/Models/EnvironmentVariable.php
ProcessMaker/Models/Group.php
ProcessMaker/Models/Media.php
ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessCategory.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/Screen.php
ProcessMaker/Models/ScreenCategory.php
ProcessMaker/Models/ScreenType.php
ProcessMaker/Models/Script.php
ProcessMaker/Models/ScriptCategory.php
ProcessMaker/Models/User.php
ProcessMaker/Providers/ProcessMakerServiceProvider.php
resources/lang/en/validation.php

Resolves #2540 
- As Laravel's default validator are limited, a new validator that accepts just letters (UTF-8) + spaces + dashes (_ -)  was added. 
- The validations were added to all models that have names or titles.

Export 500

---

resources/js/processes/categories/components/CategorySelect.vue

closes #2529 
- select first value in Select Category
- create new (Screen, Script, Process), if there is only one category it should be selected.

Single Category Selected

---

ProcessMaker/Jobs/ImportProcess.php
ProcessMaker/Jobs/ImportScreen.php
ProcessMaker/Models/Screen.php

closes #2640 
- fill the parameters of Screen 
- import screen (Old and other with wathers)
- import Process (Old and other with screen wathers)

Screen Export Missing Watchers

---

ProcessMaker/Notifications/SassCompiledNotification.php

closes #2538 
remove notification css changes of database
- make changes to the UI Customize and save, no notification should appear in the notification bell.

Custom CSS Changes Notification

---

ProcessMaker/Exception/InvalidUserAssignmentException.php
ProcessMaker/Models/Process.php
resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/components/inspector/UserById.vue
resources/js/processes/modeler/initialLoad.js
resources/lang/en.json
resources/lang/en/exceptions.php
tests/Feature/Api/TaskAssignmentExecutionTest.php
tests/Feature/Api/processes/ByUserIdAssignment.bpmn

Fixes #2502 
To Test:
- Create a process with task (or manual task)
- Set the Task Assignment dropdown to "By User Id"
- Enter the name of the variable, for example `myUserId`
- Start the process with the variable, for example `{"myUserId":1}` (you can use postman to start a process with data, or set the data with a script task)
- Verify the task is assigned to the correct person
- Verify the task fails if the user id is missing or invalid

Implement assign user by variable

---

ProcessMaker/Http/Controllers/Admin/UserController.php
ProcessMaker/Http/Controllers/ProfileController.php
resources/views/admin/users/edit.blade.php
resources/views/profile/edit.blade.php

Resolves #2549 
The problem was caused for the use of the b-form-select element instead of Laravel's Form::select . There were just 2 places with the problem: 
- profile/edit
- users/1/edit (admin menu). 
Before the fix:
After the fix:

Select Double Arrows

---

ProcessMaker/Models/ProcessVersion.php
ProcessMaker/Models/ScreenVersion.php
ProcessMaker/Models/ScriptVersion.php
resources/js/processes/screens/components/ScreenListing.vue
tests/Feature/Api/ProcessTest.php
tests/Feature/Api/ScreenTest.php
tests/Feature/Api/ScriptsTest.php

closes #2617 
- Add seter category (Screen, script, process)
- add test
- fix duplicate screen 
- Update (Screen, Script, Process) and select more of one category.
- copy screen

Edit category with several selected fails.

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue
resources/js/processes/modeler/components/inspector/ScriptSelect.vue

Closes https://github.com/ProcessMaker/modeler/issues/942

Added Open links to Task Screens and Scripts

---

ProcessMaker/Http/Controllers/Process/ScriptController.php

Fixes #2515 
Get process request attributes without using a factory

Fix new scripts creating weird assets

---

ProcessMaker/Models/User.php
resources/js/admin/users/components/AddUserModal.vue
resources/js/admin/users/index.js
tests/Feature/Api/UsersTest.php

Fix create user validation logic

---

package-lock.json
package.json

- modeler to [v0.17.8](https://www.npmjs.com/package/@processmaker/modeler/v/0.17.8)
Closes #2663.

Bumping modeler version

---

ProcessMaker/Repositories/TokenRepository.php
ProcessMaker/Traits/HasVersioning.php

Resolves #2672 
- Fix Process versioning, BPMN in the process versions was being saved in NULL
- Validation when finding self service tasks

Fix versioning/self service issue when creating tokens

---

resources/js/components/NavbarProfile.vue

- Fixes placement of navbar popover with minor padding adjustments

Fix navbar menu placement

---

package-lock.json
package.json

- screen-builder to v0.20.10
Closes #2682.

Bump screen-builder

---

ProcessMaker/Models/Process.php
ProcessMaker/Models/User.php
ProcessMaker/Policies/ProcessRequestTokenPolicy.php
tests/Feature/Api/TaskAssignmentExecutionTest.php
tests/Feature/Api/processes/SelfServeAssignment.bpmn

Fixes #2680 
Test: 
- Create a regular user
- Assign them to a group
- Create a process with a self-serve task assigned to that group
- Start the process
- Log in as the regular user
- Verify the user can see, claim, and complete the task

Check policy if a user can claim a self-serve task

---

ProcessMaker/Traits/MakeHttpRequests.php

closes #2687 
- http request now review configuration of verify certificated.
- create data-source with flag verify certicate true/false
- create process with data-source created.
- verify call with ssl correct/incorrect
need https://github.com/ProcessMaker/package-data-sources/pull/34

Move SSL Verify

---

ProcessMaker/Events/ProcessUpdated.php
ProcessMaker/Http/Controllers/TaskController.php
ProcessMaker/Http/Resources/Task.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Repositories/ExecutionInstanceRepository.php
ProcessMaker/Repositories/TokenRepository.php
resources/js/tasks/components/TaskForm.vue
resources/views/shared/breadcrumbs.blade.php
resources/views/tasks/edit.blade.php

Resolves #2662 
- Remove window.location.reload() to refresh Task
- Refresh Task data and screen config using axios
- Improve process events broadcast
- Complete Task GET record api
- Improve Task Events broadcast

Improves Interstitial Redirect

---

ProcessMaker/Events/ProcessUpdated.php
ProcessMaker/Http/Controllers/TaskController.php
ProcessMaker/Http/Resources/Task.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Repositories/ExecutionInstanceRepository.php
ProcessMaker/Repositories/TokenRepository.php
resources/js/bootstrap.js
resources/js/tasks/components/ProcessRequestChannel.js
resources/js/tasks/components/TaskForm.vue
resources/views/shared/breadcrumbs.blade.php
resources/views/tasks/edit.blade.php
tests/Feature/Api/ProcessCategoriesTest.php

Resolves #2686 
Required by https://github.com/ProcessMaker/package-advancedforms/pull/2
- Update the task workflow events management required by advanced screens

Changes required for advanced screen

---

resources/js/admin/groups/components/UsersInGroupListing.vue
resources/js/admin/users/components/AddUserModal.vue
resources/js/components/Confirm.vue
resources/js/components/requests/card.vue
resources/js/components/requests/modal.vue
resources/sass/app.scss
resources/views/admin/auth-clients/index.blade.php
resources/views/admin/cssOverride/edit.blade.php
resources/views/admin/groups/edit.blade.php
resources/views/admin/groups/index.blade.php
resources/views/admin/users/edit.blade.php
resources/views/admin/users/index.blade.php
resources/views/categories/list.blade.php
resources/views/layouts/navbar.blade.php
resources/views/processes/environment-variables/index.blade.php
resources/views/processes/list.blade.php
resources/views/processes/screens/list.blade.php
resources/views/processes/scripts/list.blade.php

- Improves padding on modals system-wide
- Improves padding on confirmation dialog
- Adds loading spinner to New Request modal
- Fixes UI issues on Group edit page
- Fixes minor UI issues on Customize UI page
Closes #2693.

UI improvements

---

resources/js/processes/modeler/initialLoad.js

Reference Modeler PR in regards to accordion bug. See comment.
https://github.com/ProcessMaker/modeler/pull/1002

Fix multiple accordion opened bug

---

resources/js/processes/modeler/components/ModelerApp.vue
resources/views/processes/modeler/index.blade.php

The purpose of this PR is to merge the breadcrumb navigation with the toolbar into a single bar.
**Note**
- Replace breadcrumbs with modeler toolbar which contains, breadcrumbs and toolbar
Associated PR in Modeler
https://github.com/ProcessMaker/modeler/pull/1010

Merge breadcrumb nav and toolbar

---

resources/js/processes/modeler/components/ModelerApp.vue

Related: https://github.com/ProcessMaker/modeler/issues/1012
Merge when modeler build is done.

Fix scrollbars on control and inspector panels

---

ProcessMaker/BuildSdk.php
ProcessMaker/Console/Commands/GenerateSdk.php
ProcessMaker/Http/Controllers/Api/DataSourcesController.php
ProcessMaker/Http/Controllers/Api/GroupController.php
ProcessMaker/Http/Controllers/Api/GroupMemberController.php
ProcessMaker/Http/Controllers/Api/PermissionController.php
ProcessMaker/Http/Controllers/Api/ProcessCategoryController.php
ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Http/Controllers/Api/ScreenCategoryController.php
ProcessMaker/Http/Controllers/Api/ScriptCategoryController.php
ProcessMaker/Http/Controllers/Api/ScriptController.php
ProcessMaker/Http/Controllers/Api/TaskController.php
ProcessMaker/Http/Controllers/Api/swagger-v3.php
ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/User.php
config/l5-swagger.php
storage/api-docs/api-docs.json
tests/sdk/BuildSdkTest.php

Fixes #2731 
Number up annotation updates and refactoring the sdk generator so it can use the latest version of OpenAPI Generator (4.2.2)

Update annotations for OpenAPI Generator 4.2.2

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Models/ProcessRequest.php
storage/api-docs/api-docs.json

Resolves #2733 
This PR includes an update of the swagger documentation for ProcessRequest Model an Controller.

Update of the swagger documentation for ProcessRequest

---

ProcessMaker/Traits/MakeHttpRequests.php

Map request data if body empty

---

ProcessMaker/Http/Controllers/TaskController.php

Resolves #2752 
When a script task is opened by URL, redirects to request details.

When open a script task by url, redirect to request details

---

resources/lang/en.json

Add missing english strings

---

ProcessMaker/Http/Controllers/Api/ScriptController.php
ProcessMaker/Models/Script.php
ProcessMaker/Notifications/ScriptResponseNotification.php
resources/js/processes/scripts/components/ScriptEditor.vue
resources/views/processes/screen-builder/screen.blade.php
resources/views/tasks/edit.blade.php
routes/api.php

Resolves #2768 
- Add an endpoint to get the script response
- Improve watchers execution using an endpoint to get the response
Requires ScreenBuilder update: https://github.com/ProcessMaker/screen-builder/pull/515

Fix watchers execution

---

resources/js/processes/screen-builder/components/form/file-upload.vue

Fixes #2774 
Fixes https://github.com/ProcessMaker/screen-builder/issues/516

Fix file uploads when used with record lists

---

package-lock.json
package.json

- screen-builder
- modeler
Closes #2776.

Update screen-builder to v0.21.4 & modeler to v0.18.2

---

resources/views/admin/groups/edit.blade.php

Changed "user" to "group"

---

ProcessMaker/Traits/MakeHttpRequests.php

Overwrite the data connector request body when the data mapping is configured.
- Install Data Connector
- Create a POST endpoint and configure the request body.
- Create a process using the Data Connector
- Configure the Data Mapping to overwrite an existing key in the request body  
The data mapping overwrites the request body in the posted data.
Closes [package-data-sources/#43](https://github.com/ProcessMaker/package-data-sources/issues/43)

Update Data Mapping Payloads

---

resources/lang/en.json

Add translation strings for default value inspector setting screen builder

---

ProcessMaker/Console/Commands/Install.php

- Changes incorrect DOCKER_SCRIPTS_HOME variable to PROCESSMAKER_SCRIPTS_HOME in installer
Closes #2791.

Fix minor issue with installer

---

ProcessMaker/Http/Controllers/RequestController.php
ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Models/ProcessVersion.php
ProcessMaker/Traits/ProcessTrait.php
public/definitions/ProcessMaker.xsd
resources/js/processes/modeler/initialLoad.js
resources/js/tasks/components/TaskForm.vue
resources/views/tasks/edit.blade.php

Resolves #2763 
- Add interstitial properties to Start Event in modeler
- Implement interstitial behavior when a request is started using an interstitial start event
- Fix getDefinition to get the BPMN definition used when a process is started
Requires: https://github.com/ProcessMaker/processmaker-bpmn-moddle/pull/35
Requires: Modeler updated with moddle plugin

Implements Start Event Interstitial

---

ProcessMaker/Http/Controllers/Api/ScreenController.php
ProcessMaker/Models/Screen.php
resources/js/processes/screen-builder/screen.vue

Resolves #2793 
- Add the PMQL parameter to screen index API
Required by: Nested screen feature

Filter screens listed in nested screens control

---

package-lock.json
package.json

Update modeler to v0.18.4

---

ProcessMaker/Http/Controllers/RequestController.php
package-lock.json
package.json
resources/js/processes/modeler/components/inspector/Interstitial.vue
resources/js/processes/modeler/components/inspector/ScreenSelect.vue

closes #2783 
- Enable default interstitial screen.
- Update processmaker-bpmn-moddle
- Update modeler version
https://github.com/ProcessMaker/modeler/pull/1089
- create process with interstitial enabled but without screen select.
- run process
Configuration
Screen by default

Interstitial Screen Required

---

resources/views/processes/screen-builder/screen.blade.php

Updates the 'Data Source' label within the Watchers 'Scripts' selection to 'Data Connector'
Closes #2820

Update data connector label

---

ProcessMaker/Jobs/ImportProcess.php

- Moves saving of screens into its own method in order to make code more reusable in packages
- Required by https://github.com/ProcessMaker/package-collections/pull/171 in order to prevent copying and pasting code between core and package
Closes #2830.

Export screens with collections

---

ProcessMaker/BpmnEngine.php
ProcessMaker/Jobs/BpmnAction.php
ProcessMaker/Models/CallActivity.php
ProcessMaker/Providers/WorkflowServiceProvider.php
composer.json
composer.lock
tests/Feature/Api/CallActivityMultilevelTest.php
tests/Feature/Api/processes/multilevel_child1.bpmn
tests/Feature/Api/processes/multilevel_child2.bpmn
tests/Feature/Api/processes/multilevel_parent.bpmn

Resolves #2785 
- Fix the code to synchronize requests executed using CallActivity
- Update Nayra with engine support to execute multiple BPMN definitions at a time
- Add test to verify call activity with multiple levels

Fix call activity execution with multiple levels

---

resources/js/processes/screen-builder/screen.vue

Closes #2834 
- remove error in "Console errors"
- change error to secction input data.
- create a screen and preview
- put an invalid json and view message of invalid json
configuration
Screen save

Empty Data Input

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
resources/views/processes/list.blade.php
tests/Feature/Api/ProcessTest.php

Handle XML errors when creating a process

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
ProcessMaker/Managers/TaskSchedulerManager.php
ProcessMaker/Models/Process.php
database/migrations/2020_02_05_112349_update_processes_whithout_version.php

Fix and validate process without versions

---

resources/views/shared/users/sidebar.blade.php

Resolves #2862 
The settings sections was duplicated, it was removed the last one.

Edit user has two settings sections

---

ProcessMaker/Traits/ProcessTaskAssignmentsTrait.php

closes #2870 
##Changes
- Add validation by saving the types of assignments in tasks
##Test
- create process 
- create task with assignment task "By User Id"
- The process must be saved correctly
##Screenshot

Task assignment: error in the assignment "By user ID" when saving

---

resources/js/processes/categories/components/CategorySelect.vue
resources/js/processes/screens/components/ScreenListing.vue
resources/views/auth/passwords/reset.blade.php
resources/views/categories/list.blade.php
resources/views/processes/edit.blade.php
resources/views/processes/environment-variables/edit.blade.php
resources/views/processes/environment-variables/index.blade.php
resources/views/processes/list.blade.php
resources/views/processes/screens/edit.blade.php
resources/views/processes/screens/list.blade.php
resources/views/processes/scripts/edit.blade.php
resources/views/processes/scripts/list.blade.php
resources/views/shared/users/profile.blade.php

Add asterisks to required form fields.
closes #2879

Add asterisks to required form fields

---

resources/js/processes/modeler/components/inspector/Interstitial.vue
resources/js/processes/modeler/components/inspector/ScreenSelect.vue
resources/js/processes/modeler/components/inspector/ScriptSelect.vue
resources/js/processes/modeler/initialLoad.js

Add front-end 'required' validations for the Select Screen & Select Script dropdowns.
<h2>Test</h2>
1. `npm link` all the listed dependency PR's below.
2. Create a process and Toggle the 'Auto Validate' to on. 
3. Add a new Task onto the paper.
- The Screen Input dropdown in the inspector is highlighted red with an error text displaying. 
- The Task is highlighted red on the paper.
- An error for selecting a screen is displayed in the Error Console.
**Video**
<a href="https://www.loom.com/share/3fe1dda247db4804a5e91df6e7c9ba66"> <p>Edit Process - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/3fe1dda247db4804a5e91df6e7c9ba66-with-play.gif"> </a>
<h2>Dependencies</h2> …

Unmet Process Validation Errors

---

resources/lang/en.json

Fixes https://github.com/ProcessMaker/screen-builder/issues/594.
Goes hand in hand with screen builder PR https://github.com/ProcessMaker/screen-builder/issues/594

Updates "computed properties" to "calculated properties"

---

resources/js/processes/categories/components/CategoriesListing.vue

Resolves #2911 
- Tooltip is changed.
- This PR resolves the issue [58](https://github.com/ProcessMaker/package-data-connectors/issues/58) of the data-sources project.

Change Delete Tooltip for categories

---

resources/js/processes/screen-builder/screen.vue

Fixes https://github.com/ProcessMaker/screen-builder/issues/567.

Update missing form submit button warning text

---

ProcessMaker/Http/Controllers/Api/UserController.php
resources/js/admin/users/components/DeletedUsersListing.vue
resources/js/admin/users/index.js
resources/js/components/common/DataLoading.vue
resources/lang/en.json
resources/views/admin/users/deletedUsers.blade.php
resources/views/admin/users/index.blade.php
resources/views/admin/users/list.blade.php
routes/api.php

- Add a 'Deleted Users' tab on the user's index page; Lists all soft-deleted users and allows the ability to restore the user.
- Adds translations for new strings.
- Fixes height of loading icon; The loading icon was not displaying.
<a href="https://www.loom.com/share/181796c17b16412da2ed8a38dd756b92"> <p>Users - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/181796c17b16412da2ed8a38dd756b92-with-play.gif"> </a>
1. Navigate to Admin > Users Tab
2. Delete any user
3. Navigate to the Deleted Users Tab
**expected behavior**
The deleted user is listed in the data table.
4. Select the restore button and confirm
**expected behavior**
The deleted users tab does not display the restored user.
5. Navigate …

Deleted Users Tab

---

ProcessMaker/Traits/PluginServiceProviderTrait.php
resources/js/processes/modeler/components/ModelerApp.vue

Resolves #2809 
This PR is required to implement the Process Optimizer package:
- Add decorations and extensible custom status bars in modeler
- Packager version constant is optional in package provider
Requires: https://github.com/ProcessMaker/modeler/pull/1126
Package: https://github.com/ProcessMaker/package-process-optimization

Code base required for Process Simulation Tests

---

resources/lang/en.json

Fixes https://github.com/ProcessMaker/screen-builder/issues/569.

Update form record list warning text

---

config/database.php

Move redis prefix to options array

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue

Fixes #2921 
Get the highlighted node relative to the root. Broke for web entry in this commit https://github.com/ProcessMaker/processmaker/commit/ab0a842800fd2696d04b665af2d840c3b194b517#diff-991bb2b37af7e46c18940bcaf22292e0R58

Fix ScreenSelect so it does not directly modify the bpmn

---

package-lock.json
package.json

Upgraded the modeler package. 
**New Features**
- BPMN export in toolbar
- Select multiple elements
- Align / Distribute multiple elements
Closes #2924

Modeler 18.5

---

ProcessMaker/Models/User.php
database/migrations/2020_03_04_130859_add_meta_field_to_users_table.php

- Adds a `meta` column to the users table via migration as type `json`
- Adds `meta` column to the `fillable` array in the User model
- Casts `meta` as type `object` in the User model
Closes #2920.

Add meta column to User model

---

resources/js/processes/modeler/components/ModelerApp.vue

- Sets the xmlManager prop on the ValidationStatus component to enable the **Download BPMN** button
Closes #2937.

Enable Download BPMN button

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Models/RequestUserPermission.php
ProcessMaker/Models/User.php
database/migrations/2020_03_03_100305_create_request_user_permissions_table.php
tests/Browser/RequestsSearchTest.php
tests/Feature/Api/ProcessRequestsTest.php

Resolves #2913 
This PR fixes:
- Query to get the list of requests
- Query to get the assignable users of a task
- Add request_user_permissions table to improve the performance of permission check of multiple request records.

Add missing paginate and where parameter

---

resources/views/about/index.blade.php

Changed the about page to say the final version number

ProcessMaker 4 Version 4.0.3 About

---

package-lock.json
package.json

- screen-builder to v0.22.2
Closes #2951.

Update to screen-builder v0.22.2

---

package-lock.json
package.json

- Switches from modeler v0.18.5 to v0.18.4
Closes #2963.

Switch to modeler 0.18.4

---

config/app.php

Hides all usernames & passwords when in Debug mode. 
closes #2897

Hide usernames & passwords in ENV

---

resources/js/processes/scripts/components/ScriptEditor.vue
resources/js/processes/scripts/customFilters.js

Add API Documentation Links to script boilerplate templates.
closes #2896

API Doc Link

---

resources/lang/en.json

Add translations for the Screen Builder Select List inspector panel.
Dep PR: [package-translations/#32](https://github.com/ProcessMaker/package-translations/pull/32)

Update translations for screen builder

---

resources/js/admin/users/components/DeletedUsersListing.vue
resources/js/admin/users/components/UsersListing.vue

Resolves #2997 
The name of the variable used in the vuetable was fixed.

User List Pagination

---

.eslintrc
ProcessMaker/Http/Controllers/Api/SignalController.php
ProcessMaker/Jobs/CatchSignalEventProcess.php
ProcessMaker/Jobs/CatchSignalEventRequest.php
ProcessMaker/Repositories/ExecutionInstanceRepository.php
ProcessMaker/Traits/ProcessTrait.php
resources/js/components/common/mixins/multiselectApi.js
resources/js/components/requests/modal.vue
resources/js/processes/modeler/components/inspector/SignalSelect.vue
resources/js/processes/modeler/initialLoad.js
routes/api.php
tests/Feature/Api/GlobalSignalsTest.php
tests/Feature/Api/processes/GlobalSignalIntermediate.bpmn
tests/Feature/Api/processes/GlobalSignalSource.bpmn
tests/Feature/Api/processes/GlobalSignalTarget.bpmn
tests/Feature/Api/processes/GlobalSignals.bpmn

Resolves #2990 
Requires: https://github.com/ProcessMaker/modeler/pull/1168
- Add a new API endpoint to get the list of global signal events
- Add custom Signal Event Selector for Modeler
- Fix catch signal events jobs
- Update unit test to test processes modeled with Modeler
Sample processes:
[global signal target.json.txt](https://github.com/ProcessMaker/processmaker/files/4417343/global.signal.target.json.txt)
[global signal source.json.txt](https://github.com/ProcessMaker/processmaker/files/4417344/global.signal.source.json.txt)

Implement Signal Events with Modeler

---

resources/js/components/SelectUserGroup.vue

Fixes [Modeler #1033](https://github.com/ProcessMaker/modeler/issues/1033).

Append username to full names of users in user selects

---

resources/js/requests/components/RequestsListing.vue
resources/js/tasks/components/TasksList.vue

- Fixes issue where column headers did not translate on Request and Task pages
- Fixes issue where status did not translate on Task page
- Requires https://github.com/ProcessMaker/package-savedsearch/pull/128
Closes #2979.

Fix request/task listing translation issues

---

ProcessMaker/Console/Commands/BuildScriptExecutors.php
resources/js/admin/script-executors/ScriptExecutors.vue
resources/lang/en.json

Fix QA issues with script executors

---

ProcessMaker/Console/Commands/BuildScriptExecutors.php
ProcessMaker/Models/ScriptExecutor.php
config/app.php

Add instance name to custom docker executors

---

ProcessMaker/Events/ActivityAssigned.php
ProcessMaker/Events/ActivityCompleted.php
ProcessMaker/Events/ProcessCompleted.php
ProcessMaker/Events/ProcessUpdated.php

- Adds getProcessRequest method to workflow events to support highly optimized recounts in Saved Searches
Closes #3047.

Add support for improved recounts in Saved Searches

---

package-lock.json
package.json

Bump screen builder version

---

ProcessMaker/Repositories/TokenRepository.php

Do not overwrite _request data if it's already set

---

resources/js/processes/modeler/initialLoad.js
resources/js/processes/modeler/validateScreenRef.js

Fixes https://github.com/ProcessMaker/modeler/issues/1173.
**Note:** The validation for the screen ref doesn't update right away due to this bug: https://github.com/ProcessMaker/modeler/issues/1216.

Add BPMNLint validation for screen ref

---

resources/lang/en.json

- Updates translation string for related Screen Builder issue https://github.com/ProcessMaker/screen-builder/pull/687
Closes #3083.

Update empty record list message

---

ProcessMaker/Models/DataStore.php
ProcessMaker/Models/MessageEventDefinition.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Repositories/ExecutionInstanceRepository.php

Resolves #3092 
This PR merge request latest stored data after when a execution instance (request) is updated.
Fixes:
[Parallelize Tests - Sub Process Full.json.txt](https://github.com/ProcessMaker/processmaker/files/4583427/Parallelize.Tests.-.Sub.Process.Full.json.txt)

Merge request data on update

---

ProcessMaker/Repositories/TokenRepository.php
ProcessMaker/Traits/ProcessTaskAssignmentsTrait.php
package-lock.json
package.json
resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/initialLoad.js

Resolves #3082 
Requires: https://github.com/ProcessMaker/modeler/pull/1225
- Add assigment properties to CallActivity
- The requestor of the sub-processes started by CallActivity is the Assigned User of the CallActivity

Add Assignment properties to CallActivity

---

resources/lang/en.json

- Updates various language strings used in Screen Builder
- Needed for https://github.com/ProcessMaker/screen-builder/pull/703
Closes #3106.

Update language strings

---

package-lock.json
package.json

- screen-builder
- vue-form-elements
Closes #3108.

Update screen-builder and vue-form-elements

---

resources/lang/en.json
resources/views/admin/users/edit.blade.php
resources/views/profile/edit.blade.php

Also added new text string to modal and en.json. Used the W3C-recommended method of defining both the extension and mime-type when I added `accept=""` to the input tag.

Added file type enforcement to avatar image uploads.

---

package-lock.json
package.json

- screen-builder
Closes #3119.

Screen Builder v0.23.10

---

package-lock.json
package.json

- screen-builder
Closes #3126.

Screen Builder v0.23.12

---

ProcessMaker/Http/Controllers/Process/ScriptController.php

Send executor list instead of format to script edit page

---

ProcessMaker/Http/Controllers/Api/FileController.php
ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php

Update annotations for OpenAPI Code Generator

---

ProcessMaker/Http/Controllers/TaskController.php
resources/js/processes/screen-builder/components/file-download.vue
resources/js/processes/screen-builder/components/form/file-upload.vue
resources/views/tasks/edit.blade.php

Fix file uploads in loop controls

---

resources/js/processes/screen-builder/components/form/file-upload.vue

Only reload component if the ref exists

---

ProcessMaker/Jobs/ExportProcess.php
ProcessMaker/Jobs/ExportScreen.php
ProcessMaker/Jobs/ImportProcess.php
ProcessMaker/Jobs/ImportScreen.php

- Fixes exports of individual screens to include watcher scripts
- Refactors screen importer to import watcher scripts
- Handles edge cases of older export files that don't conform to newer standard
Fixes #3141.

Fix to import of Watcher scripts

---

package-lock.json
package.json

Screen Builder v0.23.18

---

package-lock.json
package.json

Updates Screen Builder to v0.23.18

Screen Builder v0.23.19

---

package-lock.json
package.json

- Screen Builder from v0.23.19 to v0.23.20

Bump Screen Builder

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue

Resolves #3149 
The code user to set focus on the screen list multiselect has been disabled.

Screen list opens automatically when clicking on a task

---

package-lock.json
package.json

- Vue Form Elements from v0.14.10 to v0.14.11
- Screen Builder from v0.23.20 to v0.23.21

Bump Vue Form Elements, Screen Builder

---

resources/js/admin/auth-clients/components/AuthClientsListing.vue
resources/views/admin/auth-clients/index.blade.php

Fixed #3159 
- Add pagination
- Add Filter
##Screenshot
pagination
filter

Auth Client Pagination Missing #3159

---

ProcessMaker/Managers/ExportManager.php
ProcessMaker/Providers/WorkflowServiceProvider.php

- Fixes export dependency manager names to allow external packages to register export dependency managers with core
- Export Web Entry screens:
https://github.com/ProcessMaker/package-webentry/pull/69
- Export email connector screens:
https://github.com/ProcessMaker/connector-send-email/pull/100
Closes #3154.

Fix dependency method and array names

---

resources/views/about/index.blade.php

First complete build for testing and QA

4.0.6 Release Candidate 1

---

ProcessMaker/Console/Commands/Install.php

Add force flag to db installer and add redis host env

---

resources/js/admin/auth-clients/components/AuthClientsListing.vue

Fixed #3159 
- Fix paginator Auth Clients to change Per Page

Auth Client Pagination Missing

---

resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/initialLoad.js
resources/lang/en.json

Resolves #3082 
- Add option `Anonymous` to CallActivity assignment:

Add Anonymous option to subprocess assignment

---

resources/js/processes/screen-builder/typeDisplay.js

Enable loops in display screens

---

ProcessMaker/Http/Controllers/Api/CommentController.php
ProcessMaker/Models/Comment.php
database/migrations/2020_06_04_121416_add_soft_delete_comments.php
resources/views/requests/show.blade.php

Resolves #3190 
- Add validation to verify if the package comments is registered
- Add code to include comments added in tasks and requests into the timeline

Comments Package issues

---

resources/js/components/NavbarProfile.vue

Change the 'My Files' link under the User Menu to 'Files'
https://github.com/ProcessMaker/processmaker/issues/3194

Update 'My Files' to 'Files'

---

resources/js/components/Timeline.vue
resources/js/components/TimelineItem.vue
resources/views/requests/show.blade.php
resources/views/tasks/edit.blade.php

Resolves #3223 
Fix to style issues in the time line:
- Do not add icons to replies and reactions
- Pass explicitly the comment status to timeline items

Timeline styles

---

resources/js/components/common/mixins/datatable.js

closes #3213 
- Fix pagination with change per page

Request Pagination Hidden

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue

closes #3219 
- add validation with deselect screen for link open screen

Clearing Screen Assignment Errors

---

resources/js/components/requests/card.vue

Add the start button URL to the HREF tag to allow copying and pasting.
- Select the `+Request` button
- Right click on the start event and select the `copy link address`  and paste somewhere.
The pasted link should be the start button URL ex. `/process_events/4?event=node_1`
The start button works as expected.
closes #3233

Process Start Button HREF URL

---

artisan
resources/js/app-layout.js
resources/js/bootstrap.js
resources/js/processes/screen-builder/components/file-upload-control.js
resources/js/processes/screen-builder/components/form/file-upload.vue
resources/js/processes/screen-builder/components/inspector/RequiredCheckbox.vue

Add required option to file upload

---

package-lock.json
package.json

Bump screen builder minor version

---

package-lock.json
package.json

- Vue Form Elements from v0.14.12 to v0.14.13
- Screen Builder from v0.24.1 to v0.24.2

Bump Vue Form Elements & Screen Builder

---

ProcessMaker/Console/Commands/Check.php
ProcessMaker/PackageChecker.php

Fixes #3153 
Can be run via artisan with `php artisan processmaker:check package-actions-by-email`

Add support for package checking using an Artisan command

---

resources/js/processes/scripts/customFilters.js

Replaces PHP code examples with Node examples.
closes #3246

Fix Node Boilerplate Code Examples

---

ProcessMaker/Http/Controllers/ProcessController.php
routes/web.php

Creates a new web route that triggers the start event API.
https://www.loom.com/share/503d203ed7d043fab625e0bb9fd17c95
- Select the `+Request` button
- Right-click on the start event and select the copy link address
- Paste in the address bar or use the URL in an `<a>` tag
The start event is triggered and redirects you to the first task.
closes #3233

Trigger Request Start Event from URL

---

composer.json
package-lock.json
package.json

- Bumps version number to 4.07 in the following files
- composer.json
- package.json
- package-lock.json
Closes #3272.

Bump version number to 4.07

---

package-lock.json
package.json

- Screen Builder from v0.24.2 to v0.24.3

Screen Builder v0.24.3

---

ProcessMaker/Console/Commands/MigrateFresh.php
ProcessMaker/Traits/SearchAutocompleteTrait.php
resources/js/bootstrap.js

Fixes #3251 
- Fix installer
- Change camel_case() to Str::camel()
- Use the global vue router on the global vue instance
**TESTING**
- Must use npm linked branches of screen-builder and vue-form-elements
- Screen Builder: feature/778
- VFE: feature/205
- email: feature/117

Additional fixes for Laravel 6 upgrade

---

.circleci/config.yml

Add coverage

---

ProcessMaker/Managers/TaskSchedulerManager.php

- Fix timer synchronization between boundary event and its task.

Fix sync of timer boundary event and its task

---

ProcessMaker/Http/Controllers/Api/ScreenController.php
resources/views/processes/screens/import.blade.php

issue https://processmaker.atlassian.net/browse/FOUR-415
- Add Validation import screen

API: POST /screens/import responds with either a 500 or 200 error when uploading invalid files

---

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
storage/api-docs/api-docs.json

Fixes https://processmaker.atlassian.net/browse/FOUR-410

FOUR-410 Fix documentation to match actual API and remove unused params.

---

composer.json
package-lock.json
package.json

- Updates Screen Builder to v1.0.0
- Bumps ProcessMaker to v4.0.8 in composer.json and package.json

Update ScreenBuilder and bump ProcessMaker version number

---

package-lock.json
package.json

Bump screen-builder to v1.0.1

---

ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Traits/HideSystemResources.php
tests/Feature/HideSystemCategoriesTest.php
tests/Feature/RequestTest.php

Update to filter system process requests when using separate data db

---

ProcessMaker/Repositories/TokenRepository.php

Fixes #3316 
Removes any relationships from _user and _request in the data object magic vars.
Before:
```
{
"_user": {
"id": 1,
"fax": null,
"cell": null,
"city": null,
"meta": null,
"email": "admin@processmaker.com",
"media": [
{
"id": 13,
"disk": "profile",
"name": "img",
"size": 133322,
"model_id": 1,
"file_name": "img.png",
"mime_type": "image/png",
"created_at": "2020-07-31 19:03:17",
"model_type": "ProcessMaker\\Models\\User",
"updated_at": "2020-07-31 19:03:17",
"order_column": 7,
"manipulations": [],
"collection_name": "profile",
"custom_properties": {
"createdBy": 1,
"updatedBy": 1
},
"responsive_images": []
}
],
"phone": null,
"state": null,
"title": null,
"avatar": "https://localhost/storage/profile/13/img.png",
"postal": null,
"status": "ACTIVE",
"address": null,
"country": …
```

Do not include relationships in data object magic vars

---

resources/views/requests/show.blade.php
resources/views/tasks/edit.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-1557
Checks if the user has permission to view comments before loading from the api

Add check for comment permission

---

package-lock.json
package.json

Update screen-builder to v1.0.2

---

resources/js/bootstrap.js

Name was wrong in bootstrap.js. Changed VueRouter to Router

Fix reference to vue router

---

package-lock.json
package.json

Update Screen Builder to v1.0.3

---

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
resources/js/processes/screen-builder/components/form/file-upload.vue

- add parameter parent to component UploadFile

Add Property Parent to upload file

---

ProcessMaker/Http/Middleware/SessionStarted.php

Reproduction Steps:
Click on 'Remember me' in your login form previously and then do a fresh migration.

Test auth check and token check

---

ProcessMaker/Http/Resources/Task.php
resources/js/tasks/components/ProcessRequestChannel.js
resources/views/tasks/edit.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-1539
Fixes reassign user list so it shows people that it can be reassigned to

[FOUR-1539] Fix users that a task can be reassignd to not showing

---

ProcessMaker/Models/MessageEventDefinition.php
ProcessMaker/Repositories/ExecutionInstanceRepository.php
tests/Feature/Processes/MessageTest.php
tests/Fixtures/message_test.bpmn

Fixes https://processmaker.atlassian.net/browse/FOUR-1657
See Jira ticket and comments for how to test

[FOUR-1657] Fix message event not continuing process

---

resources/js/processes/screen-builder/screen.vue

Update screen editor parameters to user screen builder 2

Update screen editor parameters

---

resources/views/about/index.blade.php

- Updates version number to v4.0.9 RC2

Version 4.0.9 RC2

---

ProcessMaker/Jobs/ImportProcess.php
ProcessMaker/Managers/ExportManager.php
ProcessMaker/Managers/PMConfigGenericExportManager.php
tests/Fixtures/pm_config_generic_export.bpmn
tests/Mangers/PMConfigGenericExportManagerTest.php

This PR brings over the original fix for the JIRA Ticket [FOUR-1430](https://processmaker.atlassian.net/browse/FOUR-1430) that was merged in `4.1` branch into `develop` for the `4.0.9` release. 
**Original 4.1 PR**
https://github.com/ProcessMaker/processmaker/pull/3326
<h3>Dependencies:</h3>
**Actions By Email Package**
https://github.com/ProcessMaker/package-actions-by-email/pull/39/files

Do not assign a process to an imported package call activity 

---

package-lock.json
package.json

Screen Builder v1.1.1

---

resources/views/about/index.blade.php

- ProcessMaker version to 4.0.9 RC3

Version 4.0.9 RC3

---

package-lock.json
package.json

Screen Builder v1.1.2

---

ProcessMaker/Listeners/BpmnSubscriber.php
composer.json
composer.lock
package-lock.json
package.json
public/definitions/ProcessMaker.xsd
resources/js/processes/modeler/components/inspector/GatewayFlowVariable.vue
resources/js/processes/modeler/initialLoad.js

Resolves #3276
- A new event has been created in Nayra
- The inspector for flows has been modified to include the requested variable and expression
- Expressions uses the Symphony FEEL expression evaluator and support Mustache syntax.
- A new attribute was added to ProcessMaker.xsd. This implies an update of moddle in PM and Modeler are needed

Gateway Flow Variable Refactor 

---

ProcessMaker/Traits/MakeHttpRequests.php

Add filter data soruces

---

ProcessMaker/Console/Commands/RetryScriptTasks.php

Resolves #3340 
Added code to remove tokens from locks table before attempting run them

Allow to retry script tasks that are in status ACTIVE

---

tests/Feature/ClearRequestsTest.php

This PR fix test. ProcessRequestFactory has some side effects.

Fix test. ProcessRequestFactory has some side effects

---

package-lock.json
package.json

Bump screen builder version to 1.1.3

---

package-lock.json
package.json

Update Screen Builder to v1.1.6

---

ProcessMaker/Http/Controllers/Api/GroupController.php
ProcessMaker/Http/Controllers/Api/ScreenController.php
ProcessMaker/Http/Controllers/Api/UserController.php
routes/api.php

Fixed https://processmaker.atlassian.net/browse/FOUR-1921
fix permissions with designer

Error 403 when saving a process with a user who is not super administrator

---

resources/js/admin/auth-clients/components/AuthClientsListing.vue

Fixed https://processmaker.atlassian.net/browse/FOUR-137
- Fix change per page in List Auth client

Auth Clients page is not paginating

---

resources/js/admin/script-executors/ScriptExecutors.vue
resources/views/admin/script-executors/index.blade.php

Fixed https://processmaker.atlassian.net/browse/FOUR-1968
- Add pagination in page Script Executors

There is not pagination for Script Executors when there are more than 10 entries

---

resources/js/requests/components/screenDetail.vue

Fixed https://processmaker.atlassian.net/browse/FOUR-2011
- Add validation to config event when find buttons Navs

Viewing the details of a large Screen can lock up the browser tab

---

package-lock.json
package.json

Update to Modeler v1.0.2

---

routes/channels.php

Fixed [FOUR-1841](https://processmaker.atlassian.net/browse/FOUR-1841)
- Add validation for undefined data

Broadcasting in task detail throwing 500 error

---

package-lock.json
package.json

Update to Screen Builder v1.1.8

---

resources/js/requests/components/RequestDetail.vue
resources/views/requests/show.blade.php

Fixed [FOUR-2040](https://processmaker.atlassian.net/browse/FOUR-2040)
- Add parameter isAdmin in the component request list

Super Admin access tasks

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
ProcessMaker/Models/Process.php
ProcessMaker/Observers/ProcessObserver.php
resources/js/components/requests/card.vue

Resolves https://processmaker.atlassian.net/browse/FOUR-1991
Check if the process can not be executed.

Validate if BPMN Process is executable

---

ProcessMaker/Models/Process.php
resources/views/processes/import.blade.php

Fixes: https://processmaker.atlassian.net/browse/FOUR-2059

Fix process list to assign a CallActivity

---

resources/views/about/index.blade.php

ProcessMaker 4 v4.0.13 final build

ProcessMaker 4 v4.0.13

---

config/passport.php
database/migrations/2020_10_14_002913_add_provider_to_oauth_clients.php

Needs a new migration and config file. See https://github.com/laravel/passport/blob/9.x/UPGRADE.md

Add additional configuration for new version of passport

---

resources/js/processes/screen-builder/screen.vue
webpack.mix.js

This PR fixes screen-builder-v2 configuration in PMCore

Fix screen builder v2 config

---

ProcessMaker/Managers/PMConfigGenericExportManager.php

The extra lines were causing Process exports to fail.

Remove HEAD/DEVELOP diff messages

---

ProcessMaker/Jobs/CatchSignalEvent.php
ProcessMaker/Jobs/CatchSignalEventProcess.php

Now Signal Event Jobs accepts and stores in request data the payload that comes in signals

Use signal payloads

---

ProcessMaker/Traits/MakeHttpRequests.php

Response of endpoints that don't return json is empty

---

resources/sass/app.scss

This PR fixes a layout issue within Firefox when printing a completed form.
https://processmaker.atlassian.net/browse/FOUR-2077

Fix completed form partial print (Firefox)

---

ProcessMaker/Http/Controllers/TaskController.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2146
Adds the current assigned user to the data when editing a task

Add the task user to the data when editing a task

---

ProcessMaker/Jobs/CatchSignalEventProcess.php
ProcessMaker/Jobs/CatchSignalEventRequest.php
ProcessMaker/Managers/WorkflowManager.php

Resolves https://processmaker.atlassian.net/browse/FOUR-2080

 FOUR-2080 Signal / Message Start Events doesn't start process

---

package-lock.json
package.json

Screen Builder v1.1.12

---

package-lock.json
package.json

Update to modeler 1.1.2

---

composer.json
package-lock.json
package.json

- Updates NPM and Composer files to reflect that this is version 4.1.0
- https://github.com/ProcessMaker/package-collections/pull/221
- https://github.com/ProcessMaker/package-savedsearch/pull/205

Update to v4.1.0 in package files

---

resources/js/processes/screen-builder/components/file-upload-control.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2191

Changed setting order and label names.

---

package-lock.json
package.json

Screen Builder v2.1.1

---

resources/views/categories/list.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-360
Fixes https://processmaker.atlassian.net/browse/FOUR-853

Capitalize "active"

---

routes/web.php

Fixes https://processmaker.atlassian.net/browse/FOUR-1976
Add missing middleware auth check on route

Add middleware check to trigger start event web get route

---

ProcessMaker/Http/Controllers/Api/SecurityLogController.php
ProcessMaker/Listeners/SecurityLogger.php
ProcessMaker/Models/SecurityLog.php
ProcessMaker/Providers/EventServiceProvider.php
composer.json
composer.lock
database/migrations/2020_11_16_215424_create_security_logs_table.php
resources/js/admin/users/components/SecurityLogsListing.vue
resources/js/admin/users/edit.js
resources/lang/en.json
resources/views/admin/users/edit.blade.php
routes/api.php
tests/Feature/Api/SecurityLogsTest.php
tests/Feature/AuthTest.php
tests/Feature/SecurityLoggerTest.php
webpack.mix.js

- Adds a Security Logs tab to the user edit page
- Logs security events for each user (login, login attempt, logout)
- Adds testing to ensure security events are logged and that only users with permissions can view them via the API
Closes https://processmaker.atlassian.net/browse/FOUR-2277

User security logs

---

ProcessMaker/Http/Controllers/Admin/CssOverrideController.php
ProcessMaker/Http/Controllers/Api/CssOverrideController.php
resources/js/admin/cssOverride/edit.js
resources/lang/en.json
resources/views/admin/cssOverride/edit.blade.php
resources/views/auth/login.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2275
Allows admin to to add/edit customized login page footer text

Allow customized login page footer

---

ProcessMaker/Http/Controllers/Api/ScreenController.php
resources/js/processes/modeler/components/inspector/Interstitial.vue
resources/js/processes/modeler/components/inspector/ScreenSelect.vue

Resolves [FOUR-2280](https://processmaker.atlassian.net/browse/FOUR-2280)
When configuring a task, a default interstitial screen is listed.

FOUR-2280 - Default Interstitial Screen

---

resources/js/admin/script-executors/ScriptExecutors.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-2329
Should not reference this a vue template

Fix pidFile error in script executor builder

---

package-lock.json
package.json

Screen Builder v2.2.2

---

package-lock.json
package.json

Screen Builder v2.2.3

---

resources/js/bootstrap.js
resources/views/vendor/horizon/layout.blade.php

Fixed [FOUR-2321](https://processmaker.atlassian.net/browse/FOUR-2321)
- do not load vue-router on horizon page

Horizon Not Working

---

ProcessMaker/Http/Controllers/Auth/LoginController.php
resources/js/bootstrap.js
resources/views/auth/login.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2278?focusedCommentId=202743
Adds alert when the logout was triggered by a timeout

Add alert when the logout was triggered by a timeout

---

resources/js/components/SelectUserGroup.vue
resources/js/processes/modeler/components/inspector/AssignExpression.vue
resources/js/processes/modeler/components/inspector/SelfServiceSelect.vue
resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/js/processes/modeler/components/inspector/UserSelect.vue
resources/js/processes/modeler/initialLoad.js

This PR introduces a new UI for Task Assignments
- Add a new 'FEEL Expression' dropdown within the Assignment Task select list.
- Add new UI table for listing assigned users/groups with 'Feel Expressions' and 'Self Service' selected.
- Separate the 'User' and 'Group' select options.
- Move Self Service and FEEL Expressions into their own components.
**Jira Ticket** 
https://processmaker.atlassian.net/browse/FOUR-2222

Update Task Assignment UI

---

package-lock.json
package.json

Screen Builder v2.2.4

---

package-lock.json
package.json

Screen Builder v2.2.5

---

tests/Feature/Api/OAuthTest.php
tests/Feature/Api/TaskLockAssignmentTest.php

- tests/Feature/Api/TaskLockAssignmentTest.php

Fix failing tests

---

resources/views/layouts/layout.blade.php

Fixed [FOUR-2077](https://processmaker.atlassian.net/browse/FOUR-2077)
- add style print

Printing Completed form is just taking a screenshot of the top of the form

---

ProcessMaker/Jobs/ThrowSignalEvent.php
ProcessMaker/Managers/WorkflowManager.php
tests/Feature/Api/ProcessExecutionTest.php
tests/Feature/Api/ProcessManualTaskTest.php
tests/Feature/Api/TasksTest.php

Fixe: https://processmaker.atlassian.net/browse/FOUR-2407
- Fix throw/catch with global signals
- Fix throw/catch within collaboration
- Fix tests related to PR #3470

Fix Signals Throw/Catch events

---

package-lock.json
package.json

Update version modeler

---

resources/js/components/SelectUserGroup.vue
resources/js/processes/modeler/components/inspector/AssignExpression.vue

https://processmaker.atlassian.net/browse/FOUR-2427#icft=FOUR-2427
- Fixes the issue where default assignments do not save properly.
- Fixes the issue where the saved default assignment does not load in the select list.
- Fixes an infinite loop when setting default assignments

Fix Default Assignment FEEL expression

---

ProcessMaker/Http/Middleware/GenerateMenus.php
package-lock.json
package.json
resources/views/layouts/layout.blade.php
webpack.mix.js

Resolves [https://processmaker.atlassian.net/browse/FOUR-2440](https://processmaker.atlassian.net/browse/FOUR-2440)
A font with bpmn symbols has been added.

FOUR-2440: Sidebar menu - Signal icon is not aligned

---

tests/Feature/BroadcastTest.php

Update Broadcast tests

---

resources/js/processes/modeler/components/inspector/AssignExpression.vue

https://processmaker.atlassian.net/browse/FOUR-2427
Fixes issue where the user is removed when updating the FEEL expression.

Fix removed user when updating

---

composer.json
composer.lock

Resolves [https://processmaker.atlassian.net/browse/FOUR-2444](https://processmaker.atlassian.net/browse/FOUR-2444)
A similar problem was found in PM 4.0.15. A dependency of Laravel passport has been updated the last week and is generating problems. The solution is to fix the library
"lcobucci/jwt": "3.3.1"

FOUR-2444: When running scripts tasks an error is generated

---

package-lock.json
package.json

Update to Modeler 1.3.1

---

Homestead.yaml
composer.json
composer.lock

- Updates Homestead version to support PHP 7.4
- Updates Homestead.yaml config file to support changes
- Homestead v10.15.2
- Settler v9.6.1

Update to Homestead v10.15.2

---

resources/js/components/SelectUserGroup.vue
resources/js/processes/modeler/components/inspector/AssignExpression.vue
resources/js/processes/modeler/components/inspector/SelfServiceSelect.vue
resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/lang/en.json

https://processmaker.atlassian.net/browse/FOUR-2222
- Recombines the User & Group selections into one.
- Reduces the size of the '+' button 
- Updates FEEL Expression to Rule Expression in Assignment Type dropdown
- Updates Rule Expression helper text
- Capitalizes all words in the 'Lock Task Assignment to User' label

Recombine User & Group selections

---

tests/Feature/Api/PerformanceApiTest.php
tests/Feature/Api/PerformanceModelsTest.php
tests/Feature/Api/PerformanceRoutesTest.php

This PR will improve the timing in the circleci testing workflow.

Split performance tests

---

package-lock.json
package.json

Screen Builder v2.2.11

---

package-lock.json
package.json

Update to modeler 1.3.2

---

ProcessMaker/Http/Controllers/Api/SignalController.php
resources/js/processes/signals/components/SignalListing.vue

Fixed [FOUR-2476](https://processmaker.atlassian.net/browse/FOUR-2476)
- Format pagination signals

In the signals settings, it is only possible to see 10 signals

---

ProcessMaker/ScreenConsolidator.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2451?focusedCommentId=204128
Also needs to remove buttons in container components like multi-columns

Remove buttons in container components in nested screens

---

ProcessMaker/ScreenConsolidator.php
tests/Feature/Api/PerformanceModelsTest.php
tests/Feature/Processes/ScreenConsolidatorTest.php
tests/Fixtures/test_nested_record_list.json

This PR fixes: https://processmaker.atlassian.net/browse/FOUR-2417
This PR fixes: https://processmaker.atlassian.net/browse/FOUR-2499
- Add logic to append subpages used in nested screens in RecordLists
- Update subpage references in RecordLists
- Add test to verify the consolidated nested screen

Fix FOUR-2417 record list in sub page in embedded page causes issues

---

resources/js/processes/screen-builder/typeDisplay.js

Part of https://processmaker.atlassian.net/browse/FOUR-2504
Add the nested screen control to display screens

Add support for nested display screens

---

package-lock.json
package.json

Update modeler 1.3.3

---

resources/js/bootstrap.js
resources/js/processes/modeler/index.js

Related to [https://processmaker.atlassian.net/browse/FOUR-2223](https://processmaker.atlassian.net/browse/FOUR-2223)
Modeler translation didn't load properly. At times the translation object wasn't available and translations set in vue components were not working.  In this PR I introduce a timeout to await for the translations object. When it is available, the modeler component is rendered.

FOUR-2223: Translations Update - Modeler translations

---

resources/views/about/index.blade.php

- Updates the about page to RC7

ProcessMaker 4 v4.1 RC6 → RC7

---

package-lock.json
package.json

Screen Builder v2.2.13

---

ProcessMaker/Http/Controllers/Api/SignalController.php

Fix signal count on empty collection

Fix signal count on empty collection

---

resources/js/app-layout.js
resources/js/requests/components/screenDetail.vue

Fixed [FOUR-2522](https://processmaker.atlassian.net/browse/FOUR-2522)
add waiting time when loading the print page

Request screen printer is loading faster than the page is rendering

---

ProcessMaker/ScreenConsolidator.php
tests/Feature/Processes/ScreenConsolidatorTest.php
tests/Fixtures/nested_with_navbar.json

Fixes: https://processmaker.atlassian.net/browse/FOUR-2537
This PR contains:
- Enable NavButtons from Nested Screens
- Test NavButtons inside Nested Screens

Enable NavButtons from Nested Screens

---

ProcessMaker/Jobs/ExportProcess.php
ProcessMaker/Models/CallActivity.php
tests/Feature/Api/PerformanceTest.php

Fixes: https://processmaker.atlassian.net/browse/FOUR-2569
This PR fixes:
- Export of processes with Call Activities used as Service like (data-connectors)

Structure adjustment needed to exported processes

---

package-lock.json
package.json

Update screen builder to v.2.3.0

Update screen builder to v.2.3.0

---

resources/js/processes/modeler/components/inspector/AssignExpression.vue

https://processmaker.atlassian.net/browse/FOUR-2222
- Fix loading stored Rule Expressions in the UI when deselecting and reselecting a task before saving.
**Video**
https://www.loom.com/share/b096801655bd464e9550a830df8e28bc

Fix loading Rule Expressions when the task is selected

---

package-lock.json
package.json

Screen Builder v1.1.14

---

ProcessMaker/Managers/WorkflowManager.php
composer.json
composer.lock

Required by: https://processmaker.atlassian.net/browse/FOUR-2546 
This PR Includes:
- Update Nayra v1.2.0
- Move signal/message events to queue

Update Nayra v1.2.0

---

ProcessMaker/Http/Controllers/TaskController.php
ProcessMaker/Http/Resources/Task.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2146
- Brought in from 4.0
- Also fixed it in the task api (for web entry, etc)

Fix missing _user magic var in gateway

---

routes/web.php

Fixed [FOUR-2657](https://processmaker.atlassian.net/browse/FOUR-2657)
- change name permission

Page Not Authorized appear in view all notifications with a user without permission

---

ProcessMaker/Notifications/FileReadyNotification.php
ProcessMaker/Traits/StreamsJsonToFile.php
resources/js/notifications/components/NotificationsList.vue
resources/lang/en.json

- Adds support for streaming data to JSON files rather than loading all data into memory
- Adds a new StreamsJsonToFile helper trait
- Adds support for sending "file ready" notifications to users
- Adds a new FileReadyNotification class
- Updates the notification list component to properly support file ready notifications
- Updates translation strings
- Needed by https://github.com/ProcessMaker/package-collections/pull/236
Closes https://processmaker.atlassian.net/browse/FOUR-2660

Support for exporting large files using the queue

---

ProcessMaker/ScreenConsolidator.php
tests/Feature/Processes/ScreenConsolidatorTest.php
tests/Fixtures/record_without_record_form.json

Fixes [https://processmaker.atlassian.net/browse/FOUR-2549](https://processmaker.atlassian.net/browse/FOUR-2549)
Modify page index just if it is not empty

FOUR-2549: It is not possible select a value of select list if there is a record list in the form

---

ProcessMaker/ScreenConsolidator.php

Fixed [FOUR-2537](https://processmaker.atlassian.net/browse/FOUR-2537)
- Hide nav buttons in nested form

Screens with page navigation are not shown inside a nested screen

---

package-lock.json
package.json

Modeler v1.4.1

---

resources/js/processes/modeler/components/inspector/GatewayFlowVariable.vue

Fixes [https://processmaker.atlassian.net/browse/FOUR-2424](https://processmaker.atlassian.net/browse/FOUR-2424)

FOUR-2424: Remove Flow Helper Text

---

ProcessMaker/Http/Controllers/Api/ScreenController.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2209
- Removes permission check on screens show api endpoint so all logged in users can view any screen

Remove permission check on screens show

---

ProcessMaker/ScreenConsolidator.php

Fixed [FOUR-2698](https://processmaker.atlassian.net/browse/FOUR-2698)
- add visibility rules and nested screen

Visibility rules not working with nested screens

---

README.md

Fixes https://processmaker.atlassian.net/browse/FOUR-2480

Add system requirements and install instructions to readme

---

ProcessMaker/Http/Resources/Screen.php
resources/js/processes/screen-builder/screen.vue
routes/api.php
tests/Feature/Api/ScreenTest.php

Requires: https://github.com/ProcessMaker/screen-builder/pull/901
This PR add support for navbuttons in nested screens.

Support navbuttons in nested screens

---

package-lock.json
package.json

Update modeler 1.5.0

---

resources/views/admin/users/edit.blade.php

Fixed [FOUR-2735](https://processmaker.atlassian.net/browse/FOUR-273)
- Remove attribute context

“Cannot read property 'data' of undefined” When changing a user’s email address to one that another user

---

ProcessMaker/Http/Controllers/Api/GroupMemberController.php
routes/api.php
tests/Feature/Api/GroupMembersTest.php

Fixed [FOUR-2128](https://processmaker.atlassian.net/browse/)
- Change validation of permission

user with user permission, shows a message of this action is not authorized, when I want to edit a user.

---

resources/views/auth/passwords/reset.blade.php
resources/views/auth/passwords/success.blade.php

Resolves https://processmaker.atlassian.net/browse/FOUR-2786

Fix broken/missing logo for password reset/success pages.

---

ProcessMaker/Assets/ScreensInScreen.php

Fixed [FOUR-2770](https://processmaker.atlassian.net/browse/FOUR-2770)
- decrease screen recursion

Error import the screen

---

ProcessMaker/Traits/MakeHttpRequests.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-2706](https://processmaker.atlassian.net/browse/FOUR-2706)

FOUR-2706: Watcher>> It is not possible get output variable from watcher with data connector

---

resources/views/layouts/sidebar.blade.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-2795](https://processmaker.atlassian.net/browse/FOUR-2795)
Add sidebar icons when there are items a sidebar object only

FOUR-2795: Call to a member function topMenu on null 

---

ProcessMaker/Http/Controllers/RequestController.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-1978](https://processmaker.atlassian.net/browse/FOUR-1978)
If the sure has comments for the request, he will be able to see it.

FOUR-1978: Non-admin user, who has comment permissions, cannot see comment, shared from PDF Generator

---

routes/channels.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2159

Allow admin users to subscribe to all process event channels

---

ProcessMaker/Models/User.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2467
Removes the user from any groups when deleted

Remove the user from any groups when deleted

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
tests/Feature/Api/ProcessTest.php
tests/Feature/Api/processes/RegularStartAndWebEntry.bpmn

Fixes https://processmaker.atlassian.net/browse/FOUR-2820

Remove web entry start events from the new request modal

---

ProcessMaker/Jobs/ExportProcess.php
ProcessMaker/Jobs/ImportProcess.php
database/processes/LeaveAbsenceRequest.bpmn
tests/Feature/Processes/ExportImportTest.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2812

Only remove user and group assignment rules when exporting

---

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php

Fixes:
[https://processmaker.atlassian.net/browse/FOUR-2807](https://processmaker.atlassian.net/browse/FOUR-2807)
[https://processmaker.atlassian.net/browse/FOUR-2808](https://processmaker.atlassian.net/browse/FOUR-2808)
Code that added a validation of row_id has been reverted.

FOUR-2807: File download does not update, after loading a second file

---

ProcessMaker/Http/Controllers/TaskController.php
ProcessMaker/Http/Resources/Task.php
ProcessMaker/Jobs/CompleteActivity.php
ProcessMaker/Jobs/RunScriptTask.php
ProcessMaker/Jobs/RunServiceTask.php
ProcessMaker/Managers/DataManager.php
ProcessMaker/Models/CallActivity.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Providers/WorkflowServiceProvider.php
ProcessMaker/Repositories/TokenRepository.php
resources/views/processes/scripts/edit.blade.php
resources/views/processes/scripts/list.blade.php
resources/views/requests/show.blade.php

This PR implements MultiInstance Feature for:
- User Tasks
- Manual Tasks
- Script Tasks
- Service Tasks
- Call Activity
It also was tested with:
- Data Sources
-

Implements multiinstance

---

resources/js/processes/scripts/index.js

Fixed [FOUR-2763](https://processmaker.atlassian.net/browse/FOUR-2763)
- Remove data reloading with fixed parameters.

Deleting a script makes sorting change from "name" to "updated_at"

---

ProcessMaker/Models/ProcessRequest.php
tests/Feature/Api/ProcessRequestsTest.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2796

Skip checking the permissions table if the user can view all requests

---

resources/sass/app.scss

Fixed [FOUR-2736](https://processmaker.atlassian.net/browse/FOUR-2736)
- Change style overflow to auto

Scroll bar being displayed at the bottom of view when no scroll is needed

---

ProcessMaker/Jobs/ExportProcess.php
ProcessMaker/Jobs/ImportProcess.php
tests/Feature/Processes/ExportImportTest.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2844
Turns out the issue was in core, not the web entry package

Maintain anonymous user assignment when exporting/importing

---

resources/views/about/index.blade.php

ProcessMaker 4 v4.1 RC12

---

package-lock.json
package.json

Screen Builder v2.4.4

---

resources/views/about/index.blade.php

- Updating about page to reflect new version

ProcessMaker 4 v4.1 RC13

---

package-lock.json
package.json

Update modeler 1.6.0

---

ProcessMaker/Http/Controllers/Api/ScreenController.php
ProcessMaker/Models/ProcessRequest.php
resources/lang/en.json
storage/api-docs/api-docs.json

Fixed [FOUR-2784](https://processmaker.atlassian.net/browse/FOUR-2784)
- add throw exception if participant not exists

Error on screen, when PMQL query has non-existent data

---

ProcessMaker/Http/Controllers/RequestController.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2875

When redirecting to a task, only look for active user tasks

---

resources/views/about/index.blade.php

Version 4.1 RC14

---

ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/ProcessRequestToken.php

Fixed [FOUR-2863](https://processmaker.atlassian.net/browse/FOUR-2863)
- Add operator expresion in query  value alias status

PMQL in task saved searches fail

---

ProcessMaker/Helpers/SettingsHelper.php
ProcessMaker/Http/Controllers/Admin/SettingsController.php
ProcessMaker/Http/Controllers/AdminController.php
ProcessMaker/Http/Controllers/Api/SettingController.php
ProcessMaker/Http/Middleware/GenerateMenus.php
ProcessMaker/Models/Setting.php
ProcessMaker/Observers/SettingObserver.php
ProcessMaker/Providers/ProcessMakerServiceProvider.php
ProcessMaker/Providers/SettingServiceProvider.php
config/app.php
database/factories/SettingFactory.php
database/migrations/2021_01_19_185956_add_fields_to_settings_table.php
resources/js/admin/settings/components/SettingBoolean.vue
resources/js/admin/settings/components/SettingText.vue
resources/js/admin/settings/components/SettingTextArea.vue
resources/js/admin/settings/components/SettingsGroups.vue
resources/js/admin/settings/components/SettingsListing.vue
resources/js/admin/settings/index.js
resources/views/admin/settings/index.blade.php
routes/api.php
routes/web.php
webpack.mix.js

- Implements the new Core Settings page as described in the [Core Settings PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/1864237074/Core+Settings)

Core Settings Page

---

ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Models/User.php
tests/Feature/Api/TasksTest.php

Fixes part of https://processmaker.atlassian.net/browse/FOUR-2910

Update saved search alias to get self serve tasks a user can claim

---

ProcessMaker/Bpmn/Process.php
ProcessMaker/Facades/WorkflowManager.php
ProcessMaker/Http/Controllers/Admin/UserController.php
ProcessMaker/Http/Controllers/Api/GroupMemberController.php
ProcessMaker/Http/Controllers/Api/ScreenController.php
ProcessMaker/Http/Controllers/Api/TaskController.php
ProcessMaker/Http/Controllers/Api/UserController.php
ProcessMaker/Jobs/CallProcess.php
ProcessMaker/Listeners/BpmnSubscriber.php
ProcessMaker/Managers/WorkflowManager.php
ProcessMaker/Models/FormalExpression.php
ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Models/User.php
ProcessMaker/Repositories/ExecutionInstanceRepository.php
ProcessMaker/Repositories/TokenRepository.php
ProcessMaker/Traits/HasControllerAddons.php
database/migrations/2021_02_17_095337_add_delegation_manager_users.php
database/processes/AssignmentProcess.bpmn
database/seeds/AssignmentProcess.php
database/seeds/DatabaseSeeder.php
resources/js/components/SelectFromApi.vue
resources/js/processes/modeler/components/inspector/TaskAssignment.vue
resources/lang/en.json
resources/views/admin/users/edit.blade.php
resources/views/shared/users/sidebar.blade.php
resources/views/tasks/edit.blade.php
storage/api-docs/api-docs.json

Organizational Rules

---

resources/sass/app.scss

https://processmaker.atlassian.net/browse/FOUR-2917
- Adds a `max-width` for record lists `td`, preventing screen distortion when columns contain base64 code.

Fix Record List Column Width

---

ProcessMaker/Models/User.php
tests/Feature/Api/TasksTest.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2910

Fix self serve assignments stored as strings

---

package-lock.json
package.json
resources/views/about/index.blade.php

- ProcessMaker v4.1 RC16
- Screen Builder v2.5.1

ProcessMaker 4.1 RC16

---

ProcessMaker/Http/Controllers/TaskController.php
ProcessMaker/Http/Resources/Task.php
ProcessMaker/Jobs/CompleteActivity.php
ProcessMaker/Jobs/RunScriptTask.php
ProcessMaker/Jobs/RunServiceTask.php
ProcessMaker/Managers/DataManager.php
ProcessMaker/Models/CallActivity.php
ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Providers/WorkflowServiceProvider.php
ProcessMaker/Repositories/TokenRepository.php
resources/views/processes/scripts/edit.blade.php
resources/views/processes/scripts/list.blade.php
resources/views/requests/show.blade.php

Implements: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/1758527507/Multiple+Instance+Activity
- DataManager: Is responsible to get and update data in a request, it loads the magic variables and multi-instance variables
- Add multiinstance support for Form Tasks, Script Tasks, Service Task and Call Activity
- Remove debug code in process execution

MultiInstance implementation

---

ProcessMaker/Models/Setting.php
ProcessMaker/Observers/SettingObserver.php
database/migrations/2021_01_19_185956_add_fields_to_settings_table.php
resources/js/admin/settings/components/SettingObject.vue
resources/js/admin/settings/components/SettingText.vue
resources/js/admin/settings/components/SettingTextArea.vue
resources/js/admin/settings/components/SettingsGroups.vue
resources/js/admin/settings/components/SettingsListing.vue
resources/js/admin/settings/mixins/setting.js

- Refactors the Settings page to better follow standard ProcessMaker UI conventions
- Moves most settings to a modal which can be Saved or Canceled
- Adds an Object mapping component which allows users to assign values to properties in an object
- Fixes an issue where seeding the Settings table could sometimes cause a memory leak due to an overactive observer

Settings Page UI Refactor

---

package-lock.json
package.json

Update/modeler 1.7.0

---

resources/views/processes/scripts/edit.blade.php
resources/views/processes/scripts/list.blade.php

Add hooks for scripts extensions

Add hooks for scripts extensions

---

ProcessMaker/Models/FormalExpression.php
database/processes/AssignmentProcess.bpmn

Add Signal delegate_task

---

resources/views/tasks/edit.blade.php

Fixes part of https://processmaker.atlassian.net/browse/FOUR-2915

Do not redirect closed tasks either. Redirects are handled in advanced forms

---

ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/User.php
ProcessMaker/Providers/WorkflowServiceProvider.php
ProcessMaker/Repositories/TokenRepository.php
tests/Feature/Api/TaskAssignmentExecutionTest.php
tests/Feature/Api/processes/SelfServeAssignment.bpmn

- Restore missing ManualTask declaration
- Fix Self service tests

Bugfix/fix failing tests 4/2

---

resources/views/tasks/edit.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2979
- Redo with correct base

Update the url when an interstitial changes to a new task

---

ProcessMaker/Models/User.php
resources/js/components/AdvancedSearch.vue

Resolves: https://processmaker.atlassian.net/browse/FOUR-2967
This PR fixes the Self Service filter.

Fix Self Service List

---

resources/js/data/datetime_formats.json

Once the file is updated, I had to run "npm i; npm run dev" on the command line to make it properly work in PM4.

Added d/m/Y h:i A to datetime_formats

---

resources/sass/app.scss

https://processmaker.atlassian.net/browse/FOUR-2948
- Issue resides within the bootstrap-vue library. Used this worked around to fix.
https://github.com/bootstrap-vue/bootstrap-vue/issues/5277
https://github.com/bootstrap-vue/bootstrap-vue/issues/1732#issuecomment-678806650
**Video**
https://www.loom.com/share/c2a58a4385074c989432353a715ad990

Center action column tooltips on hover

---

composer.json
package-lock.json
package.json
resources/views/about/index.blade.php

- Updates ProcessMaker to v4.1.17
- About page
- composer.json
- package.json
- package-lock.json
- Updates Screen Builder to v2.5.2

ProcessMaker v4.1.17

---

ProcessMaker/Traits/HasSelfServiceTasks.php

Fixes FOUR-3044, FOUR-3030, FOUR-3052

FOUR-3044: The task does not reach the self service tray

---

resources/js/processes/scripts/customFilters.js

Changes the apiDocsUrl to point to the correct repo so it reflects correctly in the PHP script editor comments.

Fixes FOUR-3113

---

ProcessMaker/Http/Controllers/Admin/SettingsController.php
ProcessMaker/Http/Controllers/Api/GroupController.php
ProcessMaker/Http/Controllers/Api/GroupMemberController.php
ProcessMaker/Http/Controllers/Api/SettingController.php
ProcessMaker/Jobs/ImportSettings.php
ProcessMaker/Models/Setting.php
ProcessMaker/Observers/SettingObserver.php
resources/js/admin/groups/components/GroupsInGroupListing.vue
resources/js/admin/groups/components/GroupsListing.vue
resources/js/admin/groups/edit.js
resources/js/admin/settings/components/SettingBoolean.vue
resources/js/admin/settings/components/SettingCheckboxes.vue
resources/js/admin/settings/components/SettingChoice.vue
resources/js/admin/settings/components/SettingObject.vue
resources/js/admin/settings/components/SettingTextArea.vue
resources/js/admin/settings/components/SettingsExport.vue
resources/js/admin/settings/components/SettingsImport.vue
resources/js/admin/settings/components/SettingsListing.vue
resources/js/admin/settings/mixins/setting.js
resources/views/admin/groups/edit.blade.php
resources/views/admin/users/edit.blade.php
resources/views/shared/users/profile.blade.php
routes/api.php
routes/web.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-3102](https://processmaker.atlassian.net/browse/FOUR-3102)

FOUR-3102: Implement LDAP

---

ProcessMaker/Assets/ScreensInProcess.php
ProcessMaker/Http/Controllers/Api/TaskController.php
ProcessMaker/Http/Controllers/RequestController.php
ProcessMaker/Models/FormalExpression.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/ProcessRequestToken.php
ProcessMaker/Providers/WorkflowServiceProvider.php
ProcessMaker/Repositories/TokenRepository.php
ProcessMaker/ScriptRunners/Base.php
resources/js/bootstrap.js
resources/views/tasks/edit.blade.php
routes/web.php

- Ability to register PMFunctions from packages:
```
$manager = app('workflow.FormalExpression');
$manager->registerPMFunction('foo', function ($data, $param1) {
return 'bar';
);
```
- Enable interstitial ability for CallActivity

DocuSign implementation

---

resources/views/about/index.blade.php

Update about page v4.2.2

---

ProcessMaker/Console/Commands/ProcessMakerTest.php
ProcessMaker/Events/TestStatusEvent.php
ProcessMaker/Http/Controllers/TestStatusController.php
ProcessMaker/Jobs/TestStatusJob.php
ProcessMaker/Mail/TestStatusEmail.php
database/migrations/2021_03_30_101736_create_test_status_table.php
resources/views/test/email.blade.php
resources/views/test/status.blade.php
routes/api.php
routes/channels.php
routes/web.php
tests/Feature/BroadcastTest.php

Resolves: https://processmaker.atlassian.net/browse/FOUR-3054
This PR implements a command to test the PM4 services:
```
php artisan processmaker:test
```

Test PM4 services

---

resources/lang/en.json

Fixes https://processmaker.atlassian.net/browse/FOUR-3111
- Minor label changes

FOUR-3111: Watcher should say Resource instead of end point

---

ProcessMaker/Traits/MakeHttpRequests.php

https://processmaker.atlassian.net/browse/FOUR-2985
- Fix the `Undefined body_type` error when using collections to populate a select list.
**Video**
https://www.loom.com/share/adf4246707c64da9a042e570be36c8d0

Fix Select Lists populating Collections

---

resources/views/tasks/edit.blade.php

Fixed [FOUR-3001](https://processmaker.atlassian.net/browse/FOUR-3001)
- Remove style for multiselect

The data in a select list with the option, Allow Multiple Selections is distorted with the amount of data selected

---

ProcessMaker/Repositories/TokenRepository.php

Fixes https://processmaker.atlassian.net/browse/FOUR-3132
This was already added to 4.1.18

Do not set self serve flag if lock assignment and user assigned

---

resources/js/processes/modeler/validateScreenRef.js

Fixes https://processmaker.atlassian.net/browse/FOUR-3061

Check for empty, null, and undefined screenRef

---

ProcessMaker/Traits/MakeHttpRequests.php
resources/lang/en.json

Implements enhancements described in [https://processmaker.atlassian.net/browse/FOUR-3141](https://processmaker.atlassian.net/browse/FOUR-3141)

FOUR-3141: Data Connectors immediate improvements

---

resources/js/admin/settings/components/SettingObject.vue
resources/js/admin/settings/components/SettingsGroups.vue
resources/js/admin/settings/components/SettingsListing.vue
resources/views/profile/edit.blade.php

- Minor UI improvements used by [updates to the Auth package](https://github.com/ProcessMaker/package-auth/pull/8)
- Improves display of object-based settings
- Adds ability for a setting to request a full refresh of all settings when it is updated
- Fixes a bug where a user may not be able to edit their profile if extended metadata is specified in User settings
- https://github.com/ProcessMaker/package-auth/pull/8

UI support for Auth package updates

---

resources/views/processes/scripts/edit.blade.php
resources/views/processes/scripts/list.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-3194
Note: the error was only visible when the data sources package was not installed

Fix save error when data sources package is not installed

---

ProcessMaker/Listeners/CommentsSubscriber.php
composer.json
composer.lock
resources/lang/en.json

Requires: (Nayra update) https://github.com/ProcessMaker/nayra/pull/196
This PR add comments for skipped tasks

Comment Skipped Tasks

---

resources/js/app-layout.js

Fixed [FOUR-3207](https://processmaker.atlassian.net/browse/FOUR-3207)
- stop 401 error consuming endpoints with data-sources

Error 401, when I try to configure my select list with data connector

---

ProcessMaker/Http/Controllers/RequestController.php
ProcessMaker/Managers/DataManager.php
ProcessMaker/Models/ProcessRequest.php
resources/js/requests/components/RequestScreens.vue
resources/views/requests/preview.blade.php
routes/web.php

Fixes: https://processmaker.atlassian.net/browse/FOUR-2997
- Fix the data displayed in Forms history when task is a multi-instance

Fix forms history preview 

---

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
ProcessMaker/Http/Controllers/Api/TaskController.php
ProcessMaker/Models/Group.php

- Allows the Saved Search package to retrieve counts directly from API methods
- Adds attributes to the Group model to return all users recursively (in nested groups)
- Needed to determine all users a Saved Search is shared with
- https://github.com/ProcessMaker/package-savedsearch/pull/239

Support for refactoring Saved Search counters

---

resources/js/processes/signals/components/SignalListing.vue

Fixed [FOUR-3249](https://processmaker.atlassian.net/browse/FOUR-3249)
-  Change button delete signal to disabled

Signal Manager List Icons

---

ProcessMaker/Assets/ScreensInScreen.php
ProcessMaker/Managers/ExportManager.php
tests/Feature/Api/SignalPermissionsTest.php
tests/Feature/Processes/ExportImportTest.php

Fixes https://processmaker.atlassian.net/browse/FOUR-3281

Add recursive flag prevent duplicate export dependency searches

---

ProcessMaker/Http/Controllers/Api/SettingController.php
resources/js/admin/settings/components/SettingsListing.vue
routes/api.php

Add extra buttons to settings

---

package-lock.json
package.json

Bump modeler@1.11.0

---

resources/lang/en.json

As part of fixes to [https://processmaker.atlassian.net/browse/FOUR-3295](https://processmaker.atlassian.net/browse/FOUR-3295)

FOUR-3295: Improve watcher outbound configuration helper text

---

resources/js/processes/modeler/components/inspector/SignalPayload.vue

Fixes [https://processmaker.atlassian.net/browse/FOUR-3279](https://processmaker.atlassian.net/browse/FOUR-3279)

FOUR-3279: Remove Signal by Expression

---

resources/lang/en.json

Fixed [FOUR-3073](https://processmaker.atlassian.net/browse/FOUR-3073)
- labels to tooltip

Button Tooltip

---

ProcessMaker/Managers/DataManager.php

Fixes: https://processmaker.atlassian.net/browse/FOUR-3272
- Returns request data even if it is requested before to be saved.

Get data first from memory then from DB

---

ProcessMaker/Http/Controllers/AboutController.php
resources/views/about/index.blade.php

Fixed [FOUR-3221](https://processmaker.atlassian.net/browse/FOUR-3221)
- Add version to page about from composer

Add Version to Composer File

---

resources/views/tasks/edit.blade.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-3359](https://processmaker.atlassian.net/browse/FOUR-3359)
The solution is alread present in 4.2.6. I applied the commit 856466c7e4232828a5e7b42aa6b2967b10d9ad0d  to resolve the issue.

FOUR-3359: Select List issue on ProcessMaker v4.1.18

---

ProcessMaker/Models/Process.php
ProcessMaker/Models/ProcessRequestToken.php

Fixes https://processmaker.atlassian.net/browse/FOUR-3380

Only get next user by rule if assignment type is rule_expression

---

ProcessMaker/Managers/DataManager.php

Fixed [FOUR-3328](https://processmaker.atlassian.net/browse/FOUR-3328)
- Add variable not_override_request to avoid overwriting the magic variable _request in DataManager

If we use {{_request.id}} variable in Email Notification, it add the number request and add a request

---

resources/js/processes/signals/components/SignalListing.vue
resources/lang/en.json

Fixed [FOUR-3376](https://processmaker.atlassian.net/browse/FOUR-3376)
- Change label delete to view collection in list signal of collection

Make sure Tool Tip to view collections displays View Collection

---

resources/lang/en.json
resources/views/tasks/edit.blade.php

https://processmaker.atlassian.net/browse/FOUR-3144
- Remove conditional that hide the task info when self-service was enabled
- Add a warning alert message when submitting the form and the task has not been claimed.
**Video**
https://user-images.githubusercontent.com/52755494/119040192-f353eb80-b969-11eb-9942-9b3467aed18e.mov

Show Task Info for Self Service

---

resources/js/processes/modeler/components/inspector/StartPermission.vue

https://processmaker.atlassian.net/browse/FOUR-3302
- This makes it behave like task user assignments

Remove status filter from start event user permission

---

ProcessMaker/Http/Controllers/Api/SignalController.php
ProcessMaker/Http/Controllers/Process/SignalController.php
resources/js/processes/signals/components/SignalListing.vue
resources/views/processes/signals/index.blade.php

Fixes [FOUR-3377](https://processmaker.atlassian.net/browse/FOUR-3377)
- verify that the signals of a collection are enabled.

Collection Signals with toggle on are to be listed for selection in Modeler

---

ProcessMaker/Http/Resources/Task.php

https://processmaker.atlassian.net/browse/FOUR-3423
- Add conditional to check if 'assignment' is set within the 'definition' object.
**Video**
https://user-images.githubusercontent.com/52755494/119534808-2c120d00-bd3c-11eb-80da-ced98821f0d6.mov

Fix Undefined 'Assignment' error when running email connector

---

ProcessMaker/Http/Requests/RecordRequest.php
ProcessMaker/Traits/MakeHttpRequests.php

Fixes: https://processmaker.atlassian.net/browse/FOUR-3267
This PR fixes  variables replacement in request params, headers and body

Fix variables replacement in request

---

ProcessMaker/Models/CallActivity.php
ProcessMaker/Repositories/TokenRepository.php
tests/Feature/Api/ProcessPatternsTest.php
tests/Feature/Api/bpmnPatterns/MultiInstance_SequentialCallActivity.bpmn
tests/Feature/Api/bpmnPatterns/MultiInstance_SequentialCallActivity.json
tests/Feature/Api/bpmnPatterns/SimpleTaskProcess.bpmn

Fixes: https://processmaker.atlassian.net/browse/FOUR-3323
This PR fixes the way to get the StartEventId used in a CallActivity.

Fix MultiInstance Sequential CallActivity

---

ProcessMaker/Http/Controllers/Api/ProcessController.php
ProcessMaker/Models/Process.php
resources/js/components/requests/card.vue

Fixes: https://processmaker.atlassian.net/browse/FOUR-1991
Requires: https://github.com/ProcessMaker/bpmnlint-plugin/pull/10

Show validations when building a process with EventBasedGateway

---

ProcessMaker/Http/Controllers/Admin/CssOverrideController.php
ProcessMaker/Http/Controllers/Api/CssOverrideController.php
ProcessMaker/Models/Setting.php
ProcessMaker/Providers/SettingServiceProvider.php
package-lock.json
package.json
resources/js/admin/cssOverride/components/ColorPicker.vue
resources/lang/en.json
resources/views/admin/cssOverride/edit.blade.php
resources/views/auth/login.blade.php
resources/views/layouts/sidebar.blade.php

- Adds alt tags to logos per [FOUR-2330](https://processmaker.atlassian.net/browse/FOUR-2330)
- Defaults to "ProcessMaker" and allows custom alt text to be set when uploading custom logos
- Improves accessibility of Custom UI page as part of [FOUR-3352](https://processmaker.atlassian.net/browse/FOUR-3352)
- Switches to BootstrapVue components which support better accessibility by default
- Sets `for` and `id` tags on form inputs
- Improves accessibility of color picker component

Accessibility: add alt tags to logos, improve Custom UI page

---

ProcessMaker/Http/Controllers/HomeController.php
resources/lang/en.json
resources/views/layouts/layout.blade.php
resources/views/layouts/navbar.blade.php

Resolves Resolves [https://processmaker.atlassian.net/browse/FOUR-3017](https://processmaker.atlassian.net/browse/FOUR-3017)

FOUR-3017: Servicing Multiple Dynamic UI Configurations

---

resources/js/components/common/mixins/datatable.js
resources/js/requests/components/RequestsListing.vue

Fixes [FOUR-3252](https://processmaker.atlassian.net/browse/FOUR-3252)
- Add function formatDateUser to use user configuration.
- add callback to requests list

Saved Search custom columns not using user’s date format setting

---

resources/js/admin/settings/components/SettingChoice.vue
resources/js/admin/settings/components/SettingsGroups.vue
resources/js/admin/settings/components/SettingsListing.vue
resources/views/admin/settings/index.blade.php

- Javascript handler for buttons
- Add addons to settings controller and template
- Fix SettingsChoice bug when settings are reloaded and filtered
https://user-images.githubusercontent.com/8028650/121433679-5376f580-c94a-11eb-8b0b-e4e506f2488c.mp4

Button handler settings

---

ProcessMaker/Helper/helper.php
ProcessMaker/Models/User.php
ProcessMaker/SanitizeHelper.php
resources/views/profile/show.blade.php

Fix XSS in users names (https://processmaker.atlassian.net/browse/SEC-22)
Fix XSS in users profile (https://processmaker.atlassian.net/browse/SEC-23)
- Sanitize User Profile names, title, email and phone, description, location values
- Sanitize vue expressions
- Add v-pre to prevent XSS

Sanitize and fix XSS by using curly brackets

---

resources/js/processes/modeler/components/inspector/ScreenSelect.vue

Assigned Screens or task are lost

---

ProcessMaker/Jobs/BpmnAction.php
ProcessMaker/Models/CallActivity.php
ProcessMaker/Models/ProcessRequest.php
ProcessMaker/Models/ProcessRequestLock.php
database/migrations/2021_06_28_115443_add_due_at_process_request_locks.php
tests/Feature/Api/CallActivityTest.php
tests/Feature/Api/processes/child-with-form-task.bpmn
tests/Feature/RequestLockTest.php

Fix CallActivity locks subprocess

Fix CallActivity locks subprocess

---

resources/js/components/Sidebaricon.vue
resources/lang/en.json
resources/views/layouts/sidebar.blade.php
resources/views/profile/show.blade.php
tests/Feature/Api/CommentTest.php

Fixes [FOUR-2267](https://processmaker.atlassian.net/browse/FOUR-2267)
- add aria-label to menu sidebar

Add Aria-Labels to Saved Search

---

ProcessMaker/Console/Commands/BpmnTimer.php
ProcessMaker/Console/Kernel.php
ProcessMaker/Models/User.php
tests/Feature/Api/ProcessPatternsTest.php

Fix Schedule BPMN Timer 

---

resources/js/components/SelectFromApi.vue
resources/js/components/SelectUser.vue
resources/js/components/SelectUserGroup.vue
resources/js/components/shared/IconSelector.vue
resources/js/processes/categories/components/CategorySelect.vue
resources/js/processes/modeler/components/inspector/GroupSelect.vue
resources/js/processes/modeler/components/inspector/ScreenSelect.vue
resources/js/processes/modeler/components/inspector/ScriptSelect.vue
resources/js/processes/modeler/components/inspector/StartPermission.vue
resources/js/processes/modeler/components/inspector/UserSelect.vue
resources/views/processes/edit.blade.php
resources/views/processes/import.blade.php

Fixes [FOUR-3627](https://processmaker.atlassian.net/browse/FOUR-3627)
- add aria-label to dropdwon multiselect  with event open

multi-select does not display information

---

resources/lang/en.json
resources/sass/app.scss
resources/views/layouts/layout.blade.php

Resolves: https://processmaker.atlassian.net/browse/FOUR-2262
Based on the article [Skip Navigation](https://webaim.org/techniques/skipnav/)
Show a first link at the begining of the page to send the user to the main content.
_**Note**: I've added a `tabindex="1"` to the first link because there are some other elements in the page (like the [x] button of the multiselect controls) that have a `tabindex="1"` that were always getting the first tab_
https://user-images.githubusercontent.com/8028650/124190563-7b143600-da90-11eb-8721-1b8b1f24962e.mp4

Add skip navigation link

---

resources/lang/en.json

Fixes: https://processmaker.atlassian.net/browse/FOUR-3483
Translations for FOUR-3483 (aria labels and tabindex for screen controls.)

FOUR-3483: Tab Order / Aria Tag

---

ProcessMaker/Models/User.php
ProcessMaker/Traits/MakeHttpRequests.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-3482](https://processmaker.atlassian.net/browse/FOUR-3482)

FOUR-3482: Watcher does not work in  PM 4.2.7

---

ProcessMaker/Jobs/RunScriptTask.php
ProcessMaker/Jobs/RunServiceTask.php
ProcessMaker/Listeners/BpmnSubscriber.php

Requires: https://github.com/ProcessMaker/nayra/pull/202
- Show Activity Errors including errors from MultiInstance data input validations

Display error when validating MI data input

---

resources/js/components/Breadcrumbs.vue
resources/js/requests/components/CounterCard.vue
resources/views/shared/breadcrumbs.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-2387
- Replace h1 and h6 tags
- add role = header to active breadcrumb

Request count and breadcrumb accessibility updates

---

resources/lang/en.json
resources/sass/app.scss
resources/views/processes/modeler/index.blade.php
resources/views/processes/screen-builder/screen.blade.php

Fixes https://processmaker.atlassian.net/browse/FOUR-3353
- Message is read by screen readers after the breadcrumbs

Add screen reader message to screen builder and modeler

---

resources/js/processes/screen-builder/screen.vue
resources/lang/en.json

Fixes https://processmaker.atlassian.net/browse/FOUR-3354
- Adds warning when saving if aria label is missing (aria label and label inspector settings are empty)

Add warning when aria label not present

---

ProcessMaker/Models/User.php
tests/Feature/Api/UsersTest.php

Resolves: https://processmaker.atlassian.net/browse/FOUR-3543
- Allow email characters for usernames
- Add tests to validate the allowed usernames

Allows email characters for Username

---

resources/js/components/AvatarImage.vue
resources/js/components/NavbarProfile.vue
resources/js/processes/components/ProcessesListing.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-2336
- Make avatar profile menu accessible using tab focus
- View process warning using tab focus
Package PRs
- Screen builder https://github.com/ProcessMaker/screen-builder/pull/1018
- Modeler https://github.com/ProcessMaker/modeler/pull/1365
- Saved search https://github.com/ProcessMaker/package-savedsearch/pull/255

Accessibility updates - keyboard navigation

---

resources/js/processes/screen-builder/screen.vue

Resolves: http://tickets.pm4overflow.com/tickets/167
Add warnings, recommendations and helper text.

Add warnings, recommendations and helper text.

---

resources/js/admin/settings/components/SettingsListing.vue

Fixes [https://processmaker.atlassian.net/browse/FOUR-3161](https://processmaker.atlassian.net/browse/FOUR-3161)
An option to clear an specific setting has been added

FOUR-3161: groups and departments cannot be imported with ldap

---

resources/views/tasks/edit.blade.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-3709](https://processmaker.atlassian.net/browse/FOUR-3709)

FOUR-3709: Super Admin Cannot Reassign Tasks

---

ProcessMaker/Http/Controllers/Api/TaskController.php

See https://github.com/ProcessMaker/processmaker/pull/3903
This brings the change to 4.1

Search nested json for self-serve groups and users

---

resources/views/tasks/edit.blade.php

https://github.com/ProcessMaker/processmaker/pull/3897 for 4.1.21

Prevent submitting a task multiple times

---

resources/js/processes/modeler/components/inspector/AssignExpression.vue

Fixes [FOUR-3549](https://processmaker.atlassian.net/browse/FOUR-3549)
- Verify id group in call load resource

404 error editing Rule Expression assignment and Group of users

---

ProcessMaker/Jobs/CancelRequest.php
ProcessMaker/Repositories/TokenRepository.php

Fixes [https://processmaker.atlassian.net/browse/FOUR-3746](https://processmaker.atlassian.net/browse/FOUR-3746)
Closed tokens were not persisted in the database

FOUR-3746: Timers Wakes Terminated Request
