ProcessMaker/processmaker

ProcessMaker/Http/Controllers/Auth/ForgotPasswordController.php, ProcessMaker/Http/Controllers/Auth/ResetPasswordController.php, resources/assets/sass/layouts-app.scss, resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/passwords/success.blade.php, routes/web.php
There are 4 templates overhauled to match the design provided by @meadrat in issue #334 
There are routes for all three pages.
/login
/password/reset
/password/newpass
/password/success
Design Samples: 
Login: https://zpl.io/VQqAepW
Password Reset: https://zpl.io/a7ykoYW
New pass: https://zpl.io/aN0oe7n
Password Success: https://zpl.io/awY18p7
NOTE: I made the reset, success and new pass forms a little wider and consistent.
=> Login, Reset and Password Template Updates

ProcessMaker/Http/Controllers/Designer/ProcessController.php, tests/Feature/Api/Designer/ProcessControllerTest.php
Changes done:
- When a the passed process id doesn't exist the controller redirects to the process list
- Added ProcessControllerTest.php  It tests that the ProcessController returns the view or executes a redirect depending of the existence of the process id
=> Redirect to process list when process not found

resources/assets/js/management/roles/components/RolesListing.vue
Removed checkbox name field from RolesListing 
#542 
tests pass locally
=> removed checkboxes from RolesListing

ProcessMaker/Model/Form.php, ProcessMaker/Model/InputDocument.php, ProcessMaker/Model/OutputDocument.php, ProcessMaker/Model/Script.php, tests/Feature/Api/Designer/FormManagerTest.php, tests/Feature/Api/Designer/InputDocumentManagerTest.php, tests/Feature/Api/Designer/OutputDocumentManagerTest.php, tests/Feature/Api/Designer/ScriptManagerTest.php
Bugfix https://github.com/ProcessMaker/bpm/issues/572
- Add validation to ignore the current record ( Forms, input output documents, scrips).
- Add test for validate update ignoring current record.
=> Validation in the title when updating, blocks the edition

resources/assets/js/bootstrap.js
Fixes #634
Horizon plugin requires the vue router to be included in the root app even though our app isn't using it.
=> #634 - Fix popover menus on Horizon

.circleci/config.yml
update circleci config to run local containerDeploy.sh script. This creates assigns redis and laravel ports, spins up redis container, and laravel-echo-server and horizon processes via supervisord.
=> Update circleci config for laravel

.circleci/config.yml, tests/Feature/AuthTest.php
Fixes #930 
Somehow the test db setup on CircleCi was failing but it wasn't reporting that it failed (non zero result?). This fixes the CI config and the test that should have been failing on CI but doesn't address why CI was passing but should have been failing when setting up the test db.
=> feature/930 Fix CircleCI config and fix a failing test

resources/js/app-layout.js, resources/js/data/datetime_formats.json
Solves #911 
As is stated in http://momentjs.com/docs/#default-format, when the timezone is UTC, the default format string applied is defaultFormatUtc instead of defaultFormat. 
The bug was solved setting defaultFormatUtc with the same string used by defaultFormat.
=> If user time zone is set to UTC, dates aren't formatted correctly 

ProcessMaker/Http/Controllers/ProcessController.php
in the Process controller the screens variable is now being filtered to only show 'display' screen types in the edit process screen.
=> summary screen dropdown in process edit should only show display screens

ProcessMaker/Http/Controllers/Admin/GroupController.php, ProcessMaker/Http/Controllers/Api/GroupController.php, ProcessMaker/Http/Controllers/Api/GroupMemberController.php, resources/js/admin/groups/components/UsersInGroupListing.vue, resources/js/admin/groups/edit.js, resources/views/admin/groups/edit.blade.php, resources/views/admin/users/edit.blade.php, resources/views/admin/users/index.blade.php, routes/api.php, webpack.mix.js
Solves #949 
- Edit group now has a tab to add users
- The list of users in a group has filtering, sorting
- Users can be added selecting them with a multiselect widget
- All multiselects that were used for adding groups of a en user (when editing a user) were removed.
=> User Groups

resources/views/requests/show.blade.php
fixes #1004 
to test: start a process that does not have a file upload. In the summary screen there will no longer be a tab for "attached files" unless the request has files.
=> Files tab show only if files exist

resources/views/processes/scripts/index.blade.php
We now redirect to the script builder upon script creation rather than the script editor. Closes #1085.
=> Redirecting to script builder upon script creation

resources/views/processes/index.blade.php
Disables the browser's autocomplete feature on Name field of Add A Process modal. Closes #1095.
**Before**
**After**
=> Add A Process modal: disable browser autocomplete

ProcessMaker/Console/Commands/Install.php, tests/Feature/Api/UsersTest.php, tests/bootstrap.php
Solved this issue by calling `storage:link` from the `bpm:install` Artisan command. Also created a test to ensure that avatars can be uploaded and then found in the correct location. Closes #1099.
=> Fix broken avatars

resources/js/admin/users/index.js, resources/views/admin/users/index.blade.php
Implemented vue-password component as well as password length requirements on Add A User modal on Users index screen. Closes #1104.
=> Add password strength meter to Add A User modal

resources/views/admin/users/index.blade.php
When creating a new user the errors now display in the form
=> errors now displaying in the form when creating a user

ProcessMaker/Http/Controllers/Api/NotificationController.php, resources/js/bootstrap.js, resources/js/notifications/components/NotificationsList.vue
Fixes #1109
- IDs are guids so we shouldn't need to authorize the user for updates since they would be hard to guess
- Also fixes the read/unread in the list of notifications (clicking on the left mail icon) by returning a promise
=> Ignore route authorization for notification updates

ProcessMaker/Console/Commands/Install.php, composer.json, database/migrations/2019_01_02_210148_create_failed_jobs_table.php
Fixes #1118
- Queue workers cache the .env so they need to be restarted after we modify it
- Also added a failed_jobs table to debug future errors. I think that table was supposed to be there to begin with since laravel was complaining that it did not exist. Anyway, its useful to have
=> Restart queue workers after the install script runs

ProcessMaker/Models/User.php, tests/Feature/Api/UsersTest.php
When creating a user their first and last name are now required 
fixes #1126
=> first and last name are now required

ProcessMaker/Console/Commands/Install.php
Installer now adds paths to logos and icons to the .env file it creates. Closes #1129.
=> Installer: adding logo and icon paths to env

ProcessMaker/Http/Controllers/Api/NotificationController.php, resources/js/notifications/components/NotificationsList.vue
Solves #1134 
- Added usage of the status parameter that is sent in the query string.
- Improvement of filtering in the notification list. Now the filter searches by user name, process name, task name and status.
=> Read Notifications in Inbox

resources/views/admin/users/edit.blade.php, resources/views/admin/users/index.blade.php, resources/views/profile/edit.blade.php
Autocomplete = off for email and username fields, autocomplete = new-password for password fields. New-password seems to work more consistently across browsers to prevent autocompletion of password fields. Also allows password managers to suggest high quality passwords. Fixes #1142.
=> Add appropriate autocomplete attributes to username/password inputs

.circleci/config.yml, ProcessMaker/Traits/PluginServiceProviderTrait.php, composer.json, composer.lock
This branch was tested with the email connector installer, includes the following changes:
- Remove the email connector from composer
- Remove the email connector from circleci
- Now the method updateVersion() is not required for the PluginServiceProviders
Resolves issue #1168
Installation screen:
=> Remove the email connector so it could be installed manually. Resolves issue #1168

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Models/User.php, database/seeds/UserSeeder.php, tests/Browser/UserCreationTest.php, tests/Feature/Api/PermissionsTest.php, tests/Feature/Api/ProcessPermissionsTest.php, tests/Feature/Api/ProcessTest.php, tests/Feature/Api/UsersTest.php, tests/Feature/AuthTest.php, tests/Feature/Shared/RequestHelper.php, tests/Model/UserTest.php
This PR includes the following changes:
- Remove setPasswordAttribute from User class
- Update unit tests
- Update seeder
- Update User controller
Related to: #1166 
```
// Build a user with a specified password
$user = factory(User::class)->create([
'username' =>'newuser',
'password' => Hash::make('password')
]);
```
=> Remove setPasswordAttribute from User class. #1166

resources/js/components/requests/card.vue
Fixes #1188 
Currently the modeler allows you to create a process without a start event, meaning there is no event to kick off in the "New Request" popup modal. This fix shows it even if there are no events.
=> Show the process in the New Request modal even if it doesn't have a start event

resources/views/layouts/layout.blade.php
Fixes #1193  
The size of the mainbody div was reduced so that the scroll is displayed correctly in Edge
=> Profile Cancel/Update buttons do not appear depending on window height, #1193

tests/Browser/TasksListTest.php, tests/Browser/UserCreationTest.php
Temporarily skipping Dusk tests to fix intermittent issues with CI
=> Skipping Dusk tests

ProcessMaker/Http/Resources/ApiCollection.php, tests/Feature/Api/ProcessRequestsTest.php
Fixes #1220 
- Paginated arrays should always have keys starting at zero
=> Fix pagination on request list and others

resources/views/processes/edit.blade.php
When editing the process config the success message now reads "Process Updated Successfully"
=> updated success message in processes edit

resources/js/admin/auth-clients/components/AuthClientsListing.vue
Fixes #1217 
Just removes the asc/desc arrows and makes the headers non-clickable
=> Remove sorting on auth clients list since its not supported by the oauth api

ProcessMaker/Http/Controllers/Api/CommentController.php, ProcessMaker/Http/Controllers/Api/EnvironmentVariablesController.php, ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Http/Controllers/Api/GroupController.php, ProcessMaker/Http/Controllers/Api/GroupMemberController.php, ProcessMaker/Http/Controllers/Api/NotificationController.php, ProcessMaker/Http/Controllers/Api/PermissionController.php, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, ProcessMaker/Http/Controllers/Api/ScreenCategoryController.php, ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Http/Controllers/Api/TaskAssignmentController.php, ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Http/Controllers/ProcessController.php, ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/SanitizeInput.php, routes/api.php, routes/web.php, tests/Feature/Api/SanitizationTest.php
Fixes #1195, which discovered that HTML and JS could potentially be injected into various database fields via the frontend and/or API and then displayed back to users. To mitigate this, we have introduced Sanitize middleware.
- We now strip HTML tags out of all request input by default. This occurs before request input is even accessible to controller methods or models.
- We allow for exceptions by checking for a `$doNotSanitize` property of controllers. This should be an array of field names which will allow all characters to remain in the request input.
- We have a Sanitization unit test which will attempt to pass disallowed characters into various fields and check to ensure the data has been cleaned/not cleaned based on the blacklist.
Here is an example `$doNotSanitize` array from our …
=> Prevent field injection flaws

resources/views/admin/auth-clients/index.blade.php, resources/views/admin/groups/edit.blade.php, resources/views/admin/groups/index.blade.php, resources/views/admin/users/edit.blade.php, resources/views/admin/users/index.blade.php, resources/views/processes/categories/edit.blade.php, resources/views/processes/categories/index.blade.php, resources/views/processes/environment-variables/edit.blade.php, resources/views/processes/environment-variables/index.blade.php, resources/views/processes/screen-builder/screen.blade.php, resources/views/processes/screens/edit.blade.php, resources/views/processes/screens/index.blade.php, resources/views/processes/scripts/builder.blade.php, resources/views/processes/scripts/edit.blade.php, resources/views/processes/scripts/index.blade.php, resources/views/vendor/horizon/app.blade.php
the nested sections under admin and processes now link to the dashboards to avoid any permission issues.
=> breadcrumbs now leading to dashboards

ProcessMaker/Exception/Handler.php, ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/GenerateMenus.php, ProcessMaker/Http/Middleware/SanitizeInput.php, resources/views/layouts/layout.blade.php, resources/views/layouts/sidebar.blade.php, routes/api.php, routes/web.php
Fixes #1236 
* When the user is logged in and tries to access something that does not exist
* A standard 404 page will be rendered
* This page now has the ability to add navigation with out throwing an error since we are loading middleware (that's for issue #1235 btw)
* Api will return a json error instead of html
* When NOT logged in
* Always redirects to login
=> Fix 404 errors by allowing middleware to load using Route::fallback

resources/views/profile/show.blade.php
closes #1245 
If a user does not have certain information present it will not show up in their profile.
=> hide user info if not present

ProcessMaker/Http/Controllers/RequestController.php, resources/views/requests/show.blade.php
If the user hasn't the comments permission, the comments list component is not rendered.
fixes #1259
=> When viewing the request summary screen: "This action is not authorize" #1259

resources/js/admin/auth-clients/index.js, resources/views/admin/auth-clients/index.blade.php
Fixes #1251 
- Uses the convention we are using in other modals to display errors on edit and create
=> Correctly display errors when creating/editing auth clients

resources/js/processes/screen-builder/screen.vue
To bypass validation error that prevented screens from being saved in the screen builder. Fixes #1273.
=> Passing type field when updating screens

Homestead.yaml
We need to maintain PHP 7.2 as our default version, so we have specified that we need Homestead version 6.4.0. Fixes #1210.
=> Changing Homestead version to 6.4.0

resources/views/layouts/layout.blade.php, resources/views/processes/modeler/index.blade.php, resources/views/processes/screen-builder/screen.blade.php, resources/views/processes/scripts/builder.blade.php
Fixes #1276
Move breadcrumbs to their own section, outside of content, for
- scripts editor
- screens builder
- modeler
So that they can correctly calculate their heights
=> Move breadcrumbs to their own section for scripts, modeler, and screen builder

resources/views/admin/groups/edit.blade.php, resources/views/admin/users/index.blade.php, resources/views/processes/categories/index.blade.php, resources/views/processes/environment-variables/index.blade.php, resources/views/processes/index.blade.php, resources/views/processes/scripts/index.blade.php
Several buttons throughout the codebase had the ID "disabledForNow" even though they were no longer disabled. This removes those IDs and closes #1291.
=> Removing old references to disabledForNow

resources/views/admin/auth-clients/index.blade.php
A limit of 255 characters was added to the field. Fixes #1253.
=> Validation Error when Auth Client name longer than 256 characters #1253

ProcessMaker/Models/Group.php, resources/views/admin/groups/edit.blade.php, resources/views/admin/groups/index.blade.php
- The model has a validation to limit the number of characters, so no error 500 (that was caused because the long string was truncated) is generated.
- In the new group and edit screens the name field now have a max length limitation.
Fixes #1256.
=>  500 error when making Group name larger than 256 characters #1256 

ProcessMaker/Repositories/TokenRepository.php
Fixed due date calculation, it was using an undefined property, the right one is "dueIn".
The following image shows a task with 24 hours dueIn and other with 48 hours:
Resolves: #1284
=> Fix due date calculation.

ProcessMaker/AssignmentRules/PreviousTaskAssignee.php, ProcessMaker/Contracts/AssignmentRuleInterface.php, ProcessMaker/Models/Process.php, resources/js/processes/modeler/components/inspector/TaskAssignment.vue, tests/Feature/Api/TaskAssignmentPreviousOwnerTest.php, tests/Feature/Api/processes/PreviousTaskAssignee.bpmn
- Add an option in the Modeler to use "Previous Task Assignee Rule" in the tasks
- Add the Previous Task Assignee Rule
- Add unit tests to validate this rule.
Related: #1309
=> Add Previous Task Assignee Rule

resources/js/data/datetime_formats.json
Solves #1327 
4 date formats were added in datetime_formats.json file. The formats corresponds to dd/mm/yyyy and yyyy/mm/dd with and without time.
=> Add additional date formats for user configuration #1327

ProcessMaker/Http/Controllers/Api/ProcessController.php, resources/lang/en/exceptions.php
This ticket solves #1332 
- The error message was improved to instruct to the user that he should select one specific user or group when using a group or user assignment.
- If the assignment is incorrect the server responds with status 422 instead of 500 as before.
=> Server Error when adding task assignment without target #1332

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Policies/ProcessRequestPolicy.php, database/seeds/PermissionSeeder.php, resources/views/admin/shared/permissions.blade.php, resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php, tests/Feature/EditDataTest.php
Closes #1340. This ticket:
- Adds new global "edit request data" and "edit task data" permissions that can be assigned either to groups or users.
- Adds these permissions to the permissions UI.
- Enforces these permissions in the frontend and via the API.
- Includes unit testing to ensure these permissions are respected.
=> Edit Data Permissions

resources/views/admin/groups/edit.blade.php, resources/views/admin/users/edit.blade.php
Fixes "permisssions" typo on two pages. Closes #1396.
=> Permissions typo fix

resources/js/components/requests/modal.vue
closes #1391 
to test: 
create multiple categories and multiple processes inside of those categories.
open the request modal 
the modal itself now scrolls rather than the entire screen
=> scroll bar added to request modal

ProcessMaker/Console/Commands/Install.php, ProcessMaker/Models/Permission.php, database/seeds/DefaultGroupSeeder.php, database/seeds/PermissionSeeder.php, database/seeds/UserSeeder.php, tests/Feature/Api/PermissionsTest.php
Closes #1373. Adds seeding for the below default groups if called for during `bpm:install`.
- Requesters
- Process Designers
- Administrators
Removes the following groups which were previously created by default:
- Users
- All Permissions
_Installer with new question_
_New groups listed on the groups admin screen_
=> New default group seeders

resources/views/admin/shared/permissions.blade.php
closes #1411 
In the permissions tab there are now icons indicating that the accordion can be opened.
=> added accordion icon

ProcessMaker/Http/Controllers/Api/ProcessController.php, resources/js/components/requests/card.vue
Fixes #1431 
The start_process endpoint now returns the list of start events that can be started manually (no tiemer start events).
=> Start Timer Events should not be started from +REQUEST button #1431

ProcessMaker/Managers/TaskSchedulerManager.php
Fixes #1439 
Now the timer data stored in table scheduled_ tasks includes the end date
{"type":"TimeCycle","interval":"R9\/2019-02-26T19:30:00Z\/P1W\/2029-02-27T14:38:29Z","element_id":"node_2"}
=> Timer Start Events with End Date aren't handled properly #1439

ProcessMaker/Managers/TaskSchedulerManager.php, ProcessMaker/Models/ProcessRequest.php
Fixes #1447 
The last execution date is updated just when the intermediate event runs.
=> Intermediate Timer Events aren't updating correctly the last time of execution #1447

ProcessMaker/Console/Commands/Install.php
Fixes #1362 
There was a dd() command in there that was breaking the interactive input. Error is correctly handled when it's removed
=> Fix installer script when bad db info is entered

resources/views/admin/users/edit.blade.php
Fixes #1463 
- Add style card to tab permissions.
=> The permissions tab lost established styles

resources/js/processes/scripts/components/ScriptEditor.vue
Fixes #1528 where a field was required but was not being passed to the API upon saving in the script builder.
=> Including run_as_user_id in PUT request

ProcessMaker/Managers/TaskSchedulerManager.php, tests/Feature/Api/IntermediateTimerEventTest.php
Fixes #1500 
- One test  was modified to replicate the problem
- The problem was caused because the manager tried to run the catch event even if it was closed. The issue was fixed.
- Some code clean and formatting was done.
=> The second execution an intermediate timer event generates an error #1500

resources/js/processes/modeler/components/inspector/ScriptSelect.vue
closes #1355 
When selecting a script there are now more than just the first ten being returned.
=> return more than 10 scripts in the modeler

ProcessMaker/Http/Controllers/Admin/GroupController.php, ProcessMaker/Http/Controllers/Admin/UserController.php, ProcessMaker/Models/Permission.php, database/factories/PermissionFactory.php, database/migrations/2019_03_20_214047_add_group_field_to_permissions_table.php, database/seeds/PermissionSeeder.php, resources/views/admin/shared/permissions.blade.php, tests/Feature/PermissionsTest.php
- Adds testing to ensure created permissions are added to the database
- Adds a group field to the permissions table to allow UI categorization
- Permissions UI now pulls alphabetically from database permission groups and permissions; previously was hard-coded
- PR 6 in pm4-package-collections relies on this functionality
- Permissions added by packages should follow the format **action-resource_name** (example: view-auth_clients)
- When testing, be sure to run `php artisan migrate:fresh --seed` to enable this functionality
Closes #1559.
=> Allow packages to add user & group permissions

resources/sass/app.scss
Fixes #1606 
Import the full open-sans font package, not just the regular variant. Note that this fixes the screen builder however it also changes some visual elements that were previous set to bold, but were not displaying as bold (like the active breadcrumb and table headers)
=> Use the npm-font-open-sans package correctly

resources/js/app-layout.js, resources/sass/app.scss, resources/views/layouts/navbar.blade.php, tests/Browser/UserEditDeleteTest.php
Fixes #1581 
- The default timeout is set to 3 seconds, but in reality it shows for like 5 seconds.
- To set the number of seconds it shows for, set a 3rd argument to ProcessMaker.alert
- Set to 0 to show indefinitely until it's closed by the user
- Multiple alerts are stacked
- To test, just click save a bunch of times
=> Add stackable alerts with default timeout

resources/views/processes/modeler/index.blade.php, resources/views/processes/screen-builder/screen.blade.php
Resolves #1595 
Add alert when the user wants to leave the page.
pages Screen builder and modeler.
note. 
The onbeforeunload event.
The default message that appears in the confirmation box, is different in different browsers. However, the standard message is something like "Are you sure you want to leave this page?". This message cannot be removed.
=> Browse Away Warning

resources/js/processes/modeler/components/ModelerApp.vue
Fixes #1599.
This PR adds the missing file reader `onloadend` event listener to handle modeler file uploads / imports.
=> Fix modeler file upload

ProcessMaker/Http/Middleware/SanitizeInput.php
Fixes #1648 
It was double encoding
@PMQABen need to hammer this again with injection, etc.
=> Remove htmlspecialchars since that happens automatically on output

resources/js/admin/auth-clients/components/AuthClientsListing.vue, resources/js/admin/users/components/UsersListing.vue, resources/js/processes/environment-variables/components/VariablesListing.vue, resources/js/processes/scripts/components/ScriptListing.vue
closes #1661 
Translations was causing the delete icons to throw an error. This is now resolved by add this.$t
=> fix delete method in action buttons

resources/js/processes/screen-builder/components/file-download.vue
Resolves #1591 
Add message by default when the component download file has no items to display.
=> Can't hide File Upload / Download

resources/js/processes/screens/components/ScreenListing.vue, resources/js/processes/scripts/components/ScriptListing.vue, resources/lang/en.json
closes #1739 
screens and scripts tool tips are now updated to say "copy"
=> Change tool tips

resources/js/components/requests/modal.vue
closes #1708 
added a new onClick event in the request modal, the modal was overriding the href.
=> Modal Link Not Working

resources/views/requests/show.blade.php
closes #1686 
to test, follow the steps in 1686 
When a request fails or is in an error state the sidebar will now read as "error".
=> Request Fails in Error

resources/views/tasks/edit.blade.php
closes #1719 
the reassign button is only shown when a task is open
=> Completed Tasks Cannot be Reassigned

resources/views/requests/show.blade.php
closes #1681 
The cancel button will now only show on tasks with a status of "active".
=> Remove Cancel on Completed Tasks

resources/js/admin/groups/components/GroupsListing.vue, resources/js/admin/users/components/GroupsListing.vue, resources/js/processes/categories/components/CategoriesListing.vue
Resolves #1703 
- Complete missing parameter when call ProcessMaker.confirmModal()
=> Complete missing argument in call to ProcessMaker.confirmModal()

resources/js/processes/scripts/components/ScriptEditor.vue
- Includes description when saving scripts in script builder to fix issue where scripts could not be saved from script builder
Closes #1760.
=> Include description when saving script

resources/js/app-layout.js
- Fixes an issue where we were not properly checking for a parent property's existence before checking for a child property, causing extraneous console errors to appear
Fixes #1757.
=> Fix issue with global error handler

resources/js/processes/categories/components/CategoriesListing.vue
closes #1709 
To test:
re-seed database so that you have no processes available,
go to process listing, add a new process use category modal to be redirected to the categories page and see modal auto open
=> open modal when there is no data

resources/js/components/requests/notifications.vue
- Relative time displays for each notification
- Hovering over the relative time reveals the absolute time as a tooltip
- Dismiss button for each notification is now a trash can icon with a tooltip
_Notification popover_
_Notification popover with absolute time tooltip_
_Notification popover with dismissal tooltip_
Closes #1720.
=> Notifications Tweaks

resources/js/components/common/mixins/datatable.js
closes #1687 
this doesn't 100% satisfy the requirements but we will have to wait until vuetable2 releases their update for styling the TR directly. But the table will not break any-longer in the event of a user having super long names or descriptions 
https://www.vuetable.com/guide/css-styling.html#generated-html-table
=> add text-break until vuetable2 releases a tr component to style further

resources/views/tasks/edit.blade.php
Solves #1479 
The issue was caused because in the sidebar the dueat data was always displayed, even if the task  was completed. 
Now the completed date is displayed if the task is complete.
Before the fix:
After the fix
=>  Completed Sidebar Issues

ProcessMaker/Http/Controllers/Api/UserController.php, tests/Feature/Api/UsersTest.php
Resolves #1642 
- When creating a new user, if no timezone or date format is passed, the environment variable are used as default. Those values are displayed when editing a user for the first time.
- Test to verify the functionality were added
=> Edit User Form Defaults

resources/js/processes/modeler/initialLoad.js, resources/js/processes/screen-builder/screen.vue, resources/js/processes/screen-builder/typeDisplay.js, resources/js/processes/screen-builder/typeForm.js, resources/lang/en.json
Reverts ProcessMaker/spark#1822
@chipit24 @ssshake this did not fix the issue.
[Vue warn]: Invalid Component definition: FormText
found in
---> <VueFormRenderer>
<ScreenBuilder> at resources/js/processes/screen-builder/screen.vue
<Root>
=> Revert "Fix FormText import"

resources/js/processes/screen-builder/typeDisplay.js
- Fixes imports of FormText, FormRecordList, FormMultiColumn in typeDisplay.js similar to the fix previously applied to typeForm.js
Fixes #1847.
=> Import FormText and others differently

resources/js/processes/screen-builder/screen.vue
The ticket was reported in spark-builder, but the changes needed to be done in `screen.vue` in spark.
https://github.com/ProcessMaker/spark-screen-builder/issues/172
**Video Demo**
https://drive.google.com/open?id=1PairQgUAOhZTGNTUIotqvsXbY0X-cWIa
=> Adjust inspector width

ProcessMaker/Managers/ScreenBuilderManager.php
Resolves #1862 
A variable was concatenating the directory name of every installed package. The variable that was "accumulating" the string has been renamed to work with just one directory at a time.
=> Controls installed in packages aren't added to the screen builder

resources/js/processes/screen-builder/screen.vue
- Preview Inspector height matches the renderer window
https://drive.google.com/open?id=1QalQjpvdWeL0P4mQrx_BKGWPPlFW4rAQ
=> Preview Inspector uses full height

resources/js/components/common/mixins/datatable.js
- Sorts vuetables by **sortField** property if that property is set
- Otherwise, sorts by default **field** property
- This allows fields to be rendered by slots and still remain sortable
Closes #1880.
=> Fix issue with sorting

resources/js/processes/screen-builder/screen.vue
**How to Test**
- Create new form page
- On `default page` (first form) drag a navigation component and set destination to any other page than the default page
- Click Preview, navigate to another page
- Toggle between builder and preview
**Expected**
- Toggling between preview and builder, the first form page will be set as the first one visible 
**Spark Screen Builder**
https://drive.google.com/open?id=1trotZTCBoT3d9_EWiU_5oCTNSuXMO_Bw
Fixes #1881
=> Set preview display to the form first

resources/js/leave-warning.js, resources/js/processes/screen-builder/screen.vue
Fixes https://github.com/ProcessMaker/spark-screen-builder/issues/209.
**How to test:**
1. Navigate to an existing screen or create a new one.
2. Make some changes and press the save button (ensure it successfully saves).
3. Navigate away from the page (pressing the refresh button is sufficient); you should **not** see the leave page warning.
4. Go back to the screen and make some changes, but this time, **do not** save them!
5. Navigate away from the page; you **should** see the leave page warning now.
=> Don’t trigger leave warning when there are no unsaved changes

resources/sass/app.scss, resources/views/processes/scripts/edit.blade.php, resources/views/processes/scripts/index.blade.php
- Adds global classes to allow multiselect validation to appear
- Adds standard validation to "run script as" field when creating and configuring scripts
- Now that the global classes exist, we may want to look for any other areas in the app where multiselects need standard validation
Fixes #1740.
=> Add validation to "run script as" when creating a script

package-lock.json, package.json
Update from 0.4.0 to 0.4.1
This update is required to fix https://github.com/ProcessMaker/spark-modeler/issues/407. DataName is not a property on the Intermediate Message Catch Event, and needed to be changed to `VariableName`.
Fixes #1945
=> Update processmaker-bpmn-moddle package

resources/views/layouts/minimal.blade.php
- Changes the minimal layout to load app.css using the mix helper rather than the asset helper
- This issue appeared when a production instance deployed and app.css was being incorrectly served via HTTP instead of HTTPS. It also did not have the cache busting string attached to it.
Fixes #1947.
=> Fixing issue with stylesheet loading in minimal layout

resources/js/processes/screen-builder/screen.vue, resources/sass/app.scss
PR(https://github.com/ProcessMaker/spark-screen-builder/pull/229) from Screen Builder Repo needs to be merged for fixes to be applied.
- Remove the css color overwrite on form group/checkbox labels because these rules were overwriting the bootstrap classes attached when selecting a text color.
- Fix custom css bug
**Spark Video Demo - Text Color Fix**
https://drive.google.com/open?id=15tSnFtkOju6pN3BPFcfiBIJ3nFjiyl-2
**Spark Video Demo - Custom Css Fix**
https://drive.google.com/open?id=1nZPsd_oxCWNzdVkfGUqM88qcY8O80tLo
Fixes #1954
=> Fix text color picker on screen builder

resources/js/requests/components/RequestsListing.vue
- Fixes an issue where the All Requests screen at **/requests/all** was displaying errors instead of records
Before
After
Fixes #1988.
=> Fix to All Requests screen

resources/views/requests/show.blade.php
Resolves #1966 
This PR resolves the margin in the request log.
- Fixed the margin when the process has a end event display screen:
=> Fix show log layout

resources/views/admin/users/edit.blade.php
Resolves #2006 
The problem was caused for the addition of duplicated values when the user selected/unselected  permissions. Code that eliminates duplicates from the selectedPermissions array was added.
=> Select All Permissions not working 

resources/js/processes/modeler/components/ModelerApp.vue
Fixes https://github.com/ProcessMaker/spark-modeler/issues/431.
Video of fix: https://www.dropbox.com/s/g2y6wgrjopiobhv/leave_warning_working_modeler.mov?dl=0.
=> Fix leave warning for modeler

ProcessMaker/Http/Controllers/Api/TaskController.php
- Adds a data alias for PMQL searches of tasks to allow parent request data to be searched
Closes #2020.
=> Allow PMQL searches of data belonging to a task's parent request

public/definitions/ProcessMaker.xsd
Resolves #1942 
This change is required to validate the Change the reference in the Intermediate Catch event from Data Name to Variable Name. (https://github.com/ProcessMaker/spark-modeler/issues/356)
\
=> Update ProcessMaker XSD

ProcessMaker/Jobs/CatchEvent.php
Resolves #2046 
- Fix the rename of dataName to variableName in CatchEvent BPMN action.
=> Rename variable name

resources/js/bootstrap.js
Related issue: https://github.com/ProcessMaker/screen-builder/issues/273.
Ensures vue-form-renderer is registered and available to components that need it (required for record list).
=> Import screen builder to fix component reference

resources/js/processes/screen-builder/typeDisplay.js
New PR for https://github.com/ProcessMaker/processmaker/pull/1982.
This PR registers the `FileDownload` component to be used with the display form type. This component is already registered in the form type.
**How to test:**
1. Create a display form, and drag a FileDownload component onto it.
2. Save the form and use it in a process. 
3. View the form and ensure the FileDownload component renders.
=> Register FileDownload component

resources/js/notifications/components/NotificationsList.vue
Resolves #2050 
The vue table wasn't surrounded by a div with the correct css classes.
Before:
After the fix:
=>  Notifications List Border

resources/js/processes/screen-builder/screen.vue
**Style Tweaks**
- Removed horizontal scroll bar
- Docked validation drawer
- Remove any double borders
- Change side bar font size to 14px
Some changes rely on Screen Builder PR
https://github.com/ProcessMaker/screen-builder/pull/283
=> Style tweaks

ProcessMaker/Http/Controllers/Api/UserTokenController.php, ProcessMaker/Http/Resources/UserTokenResource.php, ProcessMaker/Models/User.php, ProcessMaker/Providers/AuthServiceProvider.php, resources/views/admin/users/edit.blade.php, routes/api.php, tests/Feature/Api/UserTokensTest.php
Add our own personal access token management api endpoints and have passport lookup by username for grants that need username
How to test:
- Run test cases
- Create a sample user
- Manage api access tokens in UI for sample user
=> Add our own personal access token management api endpoints and have passport lookup by username for grants that need username

ProcessMaker/Http/Controllers/Api/UserTokenController.php, resources/views/admin/users/edit.blade.php
Resolves #2128 
- Now API uses the specified user instead of the user that executes the request
- The front-end calls the endpoints using the edited user id (before it was using the current logged user id)
=> API Tokens Returns Same ALWAYS

resources/js/processes/modeler/components/inspector/StartPermission.vue, resources/js/processes/modeler/components/inspector/TaskAssignment.vue, resources/js/processes/modeler/components/inspector/TaskNotifications.vue
Resolves #2094 
This PR fixes the padding in inspector properties.
All the core bpmn elements were reviewed.
=> Fix inspector padding

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Managers/TaskSchedulerManager.php
Resolves #2079 
This PR fixes the timer event for a loop process:
=> Fix query to get ACTIVE Intermediate Timer Events

resources/sass/_variables.scss
Table background-color was inheriting the background-color: #fff. Updated the $table-bg variable to transparent allowing the table to inherit theme colors.
Closes #1830
=> Changed the $table-bg background variable to transparent

ProcessMaker/Http/Controllers/Process/ScreenController.php, ProcessMaker/Http/Controllers/ProcessController.php
Resolves #2132 
- Add missing JSON header when exports a process
- Add missing JSON header when exports a screen
=> Fix Safari export adds .html

resources/js/processes/screen-builder/mockMagicVariables.js, resources/js/processes/screen-builder/screen.vue
This PR adds mock magic variable data to the screen builder. Related issue: https://github.com/ProcessMaker/screen-builder/issues/294.
For this to work, the related PR on screen-builder must be merged and published: https://github.com/ProcessMaker/screen-builder/pull/296.
=> Add mock magic variables

resources/js/processes/screen-builder/typeForm.js
Resolves #2059 
- Before registering the screen builder controls, the submit button value is set to 'submit' by default.
Before the enhancement:
After the enhancement:
=> Add default to submit button

ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, resources/js/processes/screen-builder/components/file-download.vue, resources/js/processes/screen-builder/components/form/file-upload.vue, routes/api.php, tests/Feature/Api/FilesTest.php
- Updated file upload and download components to handle collections as well as requests
- Added `/files/{file-id}/contents` route to allow direct downloads of files, differentiated from `/files/{file-id}` which displays file metadata
- Updated Swagger docs of File API controller
- Added Swagger docs to the separate Process Request File API controller
Closes #2061.
=> Collections file upload & download, Swagger documentation

resources/js/processes/scripts/components/ScriptListing.vue
* Removed the "Language" field and label, because that cannot be changed when duplicating a script. _(see https://processmaker.atlassian.net/browse/FOUR-361 for more details)_
=> Removed the "Language" field and label

tests/Feature/Api/CssOverrideTest.php
Resolves #2209  
The problem was caused by a rogue test that restored the app.css empty instead of the original content. The test and the restoring process were removed.
=> Styles are lost in circle CI builds

ProcessMaker/Managers/TaskSchedulerManager.php, database/processes/templates/IntermediateTimerEventMustache.bpmn, tests/Feature/Api/IntermediateTimerEventTest.php
Previously, the BPMN could only accept hard-coded durations for timerEventDefinition, for example:
```
<bpmn:timeDuration>PT1H</bpmn:timeDuration>
```
This update allows the definition to include mustache syntax where the ISO 8601 duration is taken off the data object instead. For example
```
<bpmn:timeDuration>{{ my_interval }}</bpmn:timeDuration>
```
With the data object:
```
["my_interval" => "PT1H"]
```
NOTE that I had to change one reference of `new \DateTime()` to `Carbon::now()` so I could mock the the current time in the test (I think we should actually be using Carbon instead of DateTime everywhere in the system)
=> Add ability to parse mustache syntax for timeDuration

ProcessMaker/Http/Controllers/Api/TaskController.php
Resolves #2209 
- When sorting by request, just the first task of a request was added to the request list. Now all rows are added.
=> Task List: Sort by Request

ProcessMaker/Policies/MediaPolicy.php, ProcessMaker/Providers/AuthServiceProvider.php, routes/api.php
- Adds a MediaPolicy that ensures files uploaded as part of a collection or other model will inherit that model's permissions
- Relies on a corresponding PR in collections ([processmaker/collections#110](https://github.com/ProcessMaker/package-collections/pull/110)) which also includes unit tests
=> Improve file download permissions

resources/lang/en.json
This PR updates the copy for the line input control to match the spec in https://docs.google.com/document/d/1xLekCTfdXJ8H_qlGs1mmEVO2UjRXIY-x73csCytDzsA/edit#.
This PR is required to complete the changes in https://github.com/ProcessMaker/screen-builder/pull/329.
Screenshot of fix:
=> Update copy to match spec

resources/js/components/Sidebaricon.vue
Integrated bootstrap tooltip to display alt-text for sidebar navigation.
closes #1320
=> Sidebar Icon Alt-text

ProcessMaker/Http/Controllers/Api/ProcessController.php, tests/Feature/Api/ProcessTest.php
Resolves #2154
- Added a test that verifies that a request can be started with data.
- Sawagger documentation was updated
- The process list API returns the process_id:
=> Starting Requests with Data

resources/js/requests/components/RequestScreens.vue, resources/views/requests/preview.blade.php
Resolves #2232 
- Change column title to Screen.
- Add Request id in title page preview.
=> Request Completed Forms Tweaks

resources/views/requests/show.blade.php
The data tab will only display if the request is completed and does not have errors.
closes #2191  #2229
=> Fix Request Empty Data

ProcessMaker/Jobs/CompileSass.php
Resolves #2205 
The directory where OpenSans fonts are searched has been fixed. 
This fix was already merged in this PR:
https://github.com/ProcessMaker/processmaker/pull/2206/files 
but it was reverted by this commit:
https://github.com/ProcessMaker/processmaker/commit/7012016d33748bdefa909b5ca3f03662bc7afe2f
=> Css override uses a wrong url for the OpenSans font

resources/js/processes/modeler/components/ModelerApp.vue, resources/js/processes/screen-builder/screen.vue, resources/views/layouts/layout.blade.php
In Safari and Firefox the modeler page was rendering extra height to the container of the modeler which caused a scrollbar. The expect behaviour is no scrollbar is present and the modeler app would take 100 percent of the height of the viewport. This applies to screen-builder pages.
Issue in Modeler Repo https://github.com/ProcessMaker/modeler/issues/505
Issue in Screen-Builder Repo https://github.com/ProcessMaker/screen-builder/issues/337
**Chrome**
**Safari**
**Firefox**
=> Fix scrollbar issue with Edge and Firefox in Modeler and Screen Builder

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, tests/Feature/Api/ProcessRequestFileTest.php, tests/Feature/Api/ProcessRequestsTest.php
Resolves #2058 
- The url already existed and is  api/1.0/requests/1/files/1
- The way that the files are returned was improved and made compatible to how the api/1.0/files endpoints works
- Test to validate that the file download works was added
- It was verified that files can be downloded by: super administratoras and request's participants.
=> File Upload URL

resources/js/admin/users/components/GroupsListing.vue, resources/views/admin/users/edit.blade.php
Resolves #2263 
The UI of group editing and API token now have the card wrapper
=> Edit User UI

resources/js/requests/components/RequestDetail.vue
Resolves https://github.com/ProcessMaker/modeler/issues/501
There is a related pr on https://github.com/ProcessMaker/modeler/pull/517 that doesn't rely on this pr.
Currently, the tasks list links the task id as well as the task name. 
Made the request details similar. So if the task name was empty, you can still get to the task.
=> Added linked task id for when task name is empty

ProcessMaker/Models/Process.php
* As noted in https://processmaker.atlassian.net/browse/FOUR-425, `deleted_at` was missing in the API documentation for `GET /process` requests
=> Added missing API schema "deleted_at"

ProcessMaker/Models/Setting.php
Resolves #2315 
- Change default variable logo to login.
=> Wrong Logo post Install

resources/lang/en.json, resources/views/admin/users/edit.blade.php
Updates will be needed for FR/DE/ES in "package-translate"
=> Fixed the improper sentence structure seen when deleting API tokens.

resources/js/processes/components/ProcessesListing.vue
Resolves #2361 
The regular expression used to determine if the loading icon is shown was modified to be more specific so it won't be confused with the start new processes url.
=> Loading indicator appears even if unrelated API call is made

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/Api/ScriptController.php
Resolves #2426 
The order by failed because the built query had not a join with the categories table (like is the case in the processes list). This join has been added.
=> Sorting 500

.env.example, ProcessMaker/Console/Commands/Install.php, phpunit.xml
Fixes #2371 
No changes were needed to the service provider since telescope already looks for `TELESCOPE_ENABLED` env var.
Note that telescope will log its own events until [this fix](https://github.com/laravel/telescope/pull/720) is released.
=> Add env for disabling telescope

ProcessMaker/Http/Controllers/Api/ScreenController.php, resources/js/processes/categories/components/CategorySelect.vue, resources/js/processes/screens/components/ScreenListing.vue
**Issue:**
The category selection in the duplicate screen modal was displaying and object in the input field.
**Fix:**
Converted the category input field to a dropdown and allow the user to select a category for the duplicate screen.
closes #2378
=> Fix Selection Category Modal Object Error

ProcessMaker/Policies/ProcessRequestPolicy.php, tests/Feature/Api/ProcessRequestsTest.php
Fixes #2438 
- Allow participants to view request details
- Allow users with process-specific data edit permission to view data tab
=> Fix request summary permissions

resources/js/app-layout.js, resources/js/bootstrap.js, resources/js/components/Session.vue, resources/js/leave-warning.js, resources/js/timeout.js, resources/views/layouts/layout.blade.php, resources/views/layouts/navbar.blade.php
Fixes #1524 
- Refactor modal code
- Make seconds before timeout warning appears configurable in meta tag. It's hard coded for now. This is mostly for making development easier.
- Fix how we handle the 'beforeunload' event that prevents the browser from navigating away from unsaved processes and screens.
=> Refactor timeout modal and add config for seconds before to display it

resources/js/processes/modeler/initialLoad.js
Fixes #2482.
The `allowedUsers` and `allowedGroups` attributes are no longer required and have been removed from the standalone modeler in https://github.com/ProcessMaker/modeler/pull/751. This PR also removes the code which modifies the intermediate message catch event inspector config attributes from processmaker.
=> Fix intermediate message catch event inspector config

resources/js/processes/modeler/components/inspector/TaskAssignment.vue
This PR fixes the console error `Error in render: "SyntaxError: Unexpected token u in JSON at position 0"` 
The Assignment Rules accordion renders but when creating a new rule a console error is thrown.
```
TypeError: Cannot read property 'content' of undefined
at VueComponent.saveSpecialAssignment (initialLoad.js:336498)
at invokeWithErrorHandling (vendor.js:97653)
at HTMLButtonElement.invoker (vendor.js:97978)
at HTMLButtonElement.original._wrapper (vendor.js:103331)
```
Fixes #2483
=> Add default value to specialAssignmentsListGetter

ProcessMaker/Http/Controllers/AboutController.php, resources/views/about/index.blade.php
Displays installed Node Packages on the about page. 
closes #2478
=> Add node packages to about page

ProcessMaker/Http/Controllers/Api/DataSourcesController.php, routes/api.php
Resolves #2516 
The endpoints added to core are the 3 main ones and can be used outside the data-sources package:
- data_sources -> the list of data sources
- data_sources/{data_source} -> GET 
- data_sources/{data_source} -> PUT/POST
- data_sources/{data_source} -> information of a data source
- data_sources/{data_source}/test -> test of a data source
- requests/{request}/data_sources/{data_source} -> execution of a data source
=> Datasource endpoints are not in Core

resources/js/processes/screen-builder/typeDisplay.js
The PR fixes the issue of the FormImage control not displaying for the Screen Builder type Display.
closes [#443](https://github.com/ProcessMaker/screen-builder/issues/433)
=> BugFix: Add FormImage to Screen Builder Display-type

resources/js/components/requests/modal.vue
Fixes #2521 
Test by creating a process that exists in 2 categories (must have a start event). Click the +request button and verify the same process is under both categories.
=> Show process in all caregories it belongs to when starting new request

resources/js/processes/components/ProcessesListing.vue, resources/lang/en.json
- Adds a tooltip to the warning icon on the Process list
- Adds a translation string to the English JSON file
- Run `npm run dev`
- Go to the database and place any JSON into the warnings field of said process
- Visit /processes and you should see a warning icon on the process you created
- Hover over the icon to see the tooltip
Closes #2551.
=> Adds tooltip to warning icon on Process list

resources/views/requests/show.blade.php
- Removes the **Participants** section from a Request detail screen if a Request has no participants
- Removes the **Requested By** section from a Request detail screen if a Request has no requester
- Create a process that will have no participants (i.e. a process with a Start Timer Event connected directly to an End Event)
- Wait for the process to run, then view its Request detail screen
- There should be no Requested By or Participants section
Closes #2535.
=> Remove unneeded sections from Request detail screen

tests/Browser/Pages/RequestsPage.php, tests/Browser/RequestsSearchTest.php
<h2>Issue</h2>
A dusk test was failing when looking for an attribute on a button that no longer existed.
Modified test to look for the last button.
=> Fix failing dusk test

ProcessMaker/Jobs/ExportProcess.php, ProcessMaker/Jobs/ImportProcess.php, tests/Feature/Processes/ExportImportTest.php
Fixes #2596 
To test:
- Create a screen that belongs to multiple categories
- Create a script that belongs to multiple categories
- Create a process that belongs to multiple categories
- Use the screen and script somewhere in the process
- Export the process
- Clear the db (optional)
- Import the process
- Verify the imported process, script, and screen are assigned to correct categories
=> Save script and screen categories with export

resources/js/processes/components/ProcessesListing.vue
<h2>Issue</h2>
When a process is archived, did not redirect to the processes list the first page, displayed no data. Also displayed the yellow warning alert instead of the green success alert.
- Changed the yellow warning alert to the green success alert
- Reload the first page when the process has been successfully archived.
<h2>How to Test</h2>
> 
- Create multiple processes that will paginate the process list by at least 2 pages. 
- On the second page archive a process
**Expected Results:**
A green success alert will appear. 
Redirected to the process list on the first page with displaying data. 
> 
closes #2557
=> redirect to the first page when process is archived

resources/js/requests/components/RequestsListing.vue
closes #2542 
Disable sort in list request (Column Participants)
=> Sorting by Participates

resources/views/requests/show.blade.php
Needs https://github.com/ProcessMaker/screen-builder/pull/445
Fixes #2547 
Test:
- Import process attached to the issue. Verify Final Amount and Interest Earned are showing on the summary screen after the process has finished.
- Put the same fields and calculations somewhere in a screen form task in between and verify they display correctly on the task edit page when the process is in progress
=> Add computed data to task form for summary screen

.env.example, ProcessMaker/Console/Commands/Install.php, config/database.php
- Adds variables that can be changed via the .env file
- REDIS_CLIENT will allow the user to choose phpredis, which supports prefixing
- REDIS_PREFIX will allow the user to set a Redis prefix
- HORIZON_PREFIX will allow the user to set a Horizon-specific prefix
- Follow all of the instructions laid out in the [Prefixing Redis and Horizon with PHPRedis](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/595001836/Prefixing+Redis+and+Horizon+with+PHPRedis) document. The **Verifying Your Changes** section includes instructions on verifying that your configuration changes are working.
Closes #2489.
=> Add support for Redis and Horizon prefixing

resources/js/components/Sidebaricon.vue, resources/sass/_variables.scss
- Improves tooltip visibility by using a gray background and white text
- Improves tooltips on navigation sidebar by moving them to the right, disabling them when expanded, and removing the animation and delay
Closes #2659.
=> Tooltip improvements

ProcessMaker/Models/User.php
<h2>Issue</h2>
The birthdate is not present in the edit page, but the validator is requesting some value for this field of the table.
Closes #2632 
Remove 'birthdate' from the validation rules.
<h2>Testing</h2>
- Create a user
- Edit user, changing some field.
**Expected behavior:** User is successfully updated.
=> Remove Birthdate from Validation Rules

ProcessMaker/Jobs/ImportProcess.php
Resolves #2622 
The problem was caused for not setting the status for the key 'category'. Not the keys 'categories' and  'category' are updated when importing a process.
=> Error shown in category when importing a process

ProcessMaker/Http/Controllers/Process/ScreenController.php, ProcessMaker/Http/Controllers/ProcessController.php, tests/Feature/Processes/ExportImportScreenTest.php
Resolves #2543 
The problem was caused for the use of the deprecated function snake_case. It was removed and now the exported file respects the original casing and formatting the process and screen names
=> Export with All Caps

resources/js/processes/components/ProcessesListing.vue
The problem happened when the Process List in the Archived Process tab finished. As there aren't archived processes the event 'api-data-no-results' was sent. 
The component ProcessesListing.vue, listen to this event do determine to show or hide  the process list or the data nod found message. 
The fix consists in listening to the call of active processes only.
=>  Vue Tables Clearing Incorrectly 

ProcessMaker/Jobs/ImportProcess.php
Resolves #2678 
The problem was casued by the line  $model->fill((array)...) of the Jobs/ImportProcess.php file. The problem is caused for the presence of JSON columns in the screens table.
The issue was introducing when resolving the issue:
https://github.com/ProcessMaker/processmaker/issues/2640
- Create a process with screens that have watchers.
- Export the process and verify that the process' screens are correctly imported including the watchers.
=> Process Screens Not Importing

tests/js/components/ConfirmModal.test.js
=> Fix Confirm Modal test

resources/js/app-layout.js, resources/js/components/AvatarImage.vue, resources/js/components/NavbarProfile.vue, resources/sass/app.scss, resources/views/layouts/layout.blade.php, resources/views/layouts/navbar.blade.php, resources/views/shared/breadcrumbs.blade.php
- Adds Start Request button to mobile version of navbar
- Cloaks breadcrumbs until Vue is loaded so that we no longer see them before the main navbar
- Fixes an issue where Safari was cutting off the expanded navbar on mobile
- Fixes minor issues with spacing of the navbar avatar and profile menu
Before
After
Closes #2578.
=> Navbar and breadcrumb improvements

ProcessMaker/Traits/MakeHttpRequests.php
Resolves #2711 
The problem was caused when the verify_certificate value configured in the data source is not present. Instead of testing if this key is undefined now we test if the array key exists.
=> Error when executing data sources created by collections

ProcessMaker/Listeners/BpmnSubscriber.php
Updated the grammatically incorrect sentence 'System has schedules to execute a timer ":event"' to a more accurate (and concise) 'System has scheduled timer: ":event"'
=> Changed text for "TimerEventDefinitionInterface"

resources/js/processes/modeler/components/ModelerApp.vue
The purpose of this PR is to fix the vue warning message.
```
Unknown custom element: <statusbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```
=> Remove reference of status bar

resources/js/app-layout.js, resources/js/processes/screen-builder/components/file-download.vue, resources/js/processes/screen-builder/components/form/file-upload.vue, resources/lang/en.json, resources/views/tasks/edit.blade.php
Fixes #2720 
Fixes https://github.com/ProcessMaker/screen-builder/issues/494
Disable functionality and show messages for file uploads and downloads when previewing in screen builder.
=> Add preview message cards for file upload and download

ProcessMaker/Models/ScriptDockerBindingFilesTrait.php, laravel-echo-server.json
Fixes #2715 
Remove containers after they run. Note this only applies to the runner function that binds files (normal docker execution). The function that copies files (test environment) already removes the container.
To test, check the total number of containers
`docker ps -a | wc -l`
Preview a script and check again. The number should not change.
=> Add --rm flag when running docker containers

resources/js/admin/groups/components/GroupsListing.vue, resources/js/admin/groups/components/UsersInGroupListing.vue, resources/js/admin/users/components/UsersListing.vue, resources/js/processes/categories/components/CategoriesListing.vue, resources/views/admin/groups/edit.blade.php, resources/views/categories/list.blade.php
For the edit.blade and list.blade files, I think this is more of a bandaid than an actual fix. My theory is something is sending the "inactive" status improperly, so PM4 is interpreting it everywhere as "inactive" as opposed to "Inactive", and that capital "I" is required for the translation to work correctly.
JIRA: https://processmaker.atlassian.net/browse/FOUR-276
=> Fixing missing status translations for groups, users & categories.

package-lock.json, package.json, resources/js/processes/screen-builder/components/form/file-upload.vue
Fixes #2723 
Due to the nature of the uploader package, we can not get the uploaded file display info back once the compoent has been removed (switching pages).
This change displays an icon under the upload button if a file has already been uploaded to that control. This is what will show when loading a task page or switching back to a page with an uploaded file. Needs style update but at least it will show it for now.
=> Display icon when a file is already uploaded in file upload control

config/script-runners.php
Renamed NODE to JavaScript when selecting a language in the 'Create Script' dropdown.
closes #2741
=> Update Node to JavaScript in the script language dropdown

ProcessMaker/Http/Controllers/Admin/UserController.php, ProcessMaker/Http/Controllers/Auth/LoginController.php, ProcessMaker/Http/Controllers/ProfileController.php, resources/views/admin/users/edit.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/users/sidebar.blade.php, tests/Browser/LoginTest.php
- Add Status dropdown to user profiles.
- Prevent users from logging in that have an 'Inactive' status.
- Add Dusk test to ensure if users are 'Inactive' they can not log in.
1. Admin > Users > Select user to edit.
2. Under 'Settings' change the 'Status' to 'Inactive'
3. Logout and try to login as the edited user.
Login fails and you are redirected back to the login page.
1. Admin > Users > Select user to edit.
2. Under 'Settings' change the 'Status' to 'Active'
3. Logout and try to login as the edited user.
Login is successful and you are redirected to the 'requests' page.
closes #2737
=> Add ability to activate and deactivate users.

resources/views/admin/groups/edit.blade.php
This will stop any problems that can occur if a company has two users with the same names, but different usernames.
Jira: https://processmaker.atlassian.net/browse/FOUR-956
This is something that should probably be added to the modeler for assignments as well.
=> Display usernames alongside full names for adding users to a group

resources/views/requests/show.blade.php
- Fixes padding on Task request summary screens
Closes #2748.
=> Add padding to summary task screen

resources/js/processes/modeler/initialLoad.js
Closes https://github.com/ProcessMaker/modeler/issues/1032
=> Restored Allowed Users, Allowed Groups and Whitelist fields on Intermediate Catch Event

resources/js/processes/scripts/components/ScriptListing.vue
<h2>Issue</h2>
Duplicating a script would fail during the CategoryRule validation because the screen_category_id was not being set.
- Adds a category select within the 'Copy Script' modal 
- Pass the screen_category_id in the script body.
https://www.dropbox.com/s/xb42iwlg0aonlti/Scripts%20-%20ProcessMaker%20%281%29.mp4?dl=0
- Create a script
- Duplicate script
The script successfully duplicates.
closes #2786
=> Fix copy script error

ProcessMaker/Models/CallActivity.php
Relies on https://github.com/ProcessMaker/modeler/pull/1052
and https://github.com/ProcessMaker/processmaker-bpmn-moddle/pull/33
Fixes #2764 
- Select the start event in the sub process inspector
- Increase limit of returned processes when searching in the inspector
=> Get the start event from the call activity's config

resources/js/processes/screen-builder/screen.vue
Fixes #2812 
Required for ProcessMaker/screen-builder#527
Container items are expected to be nested arrays of items (for Multi Column containers, each column contains an array of items). This is no longer the case with Loop containers. A Loop container is a single array of items. There are a number of validation checks here in core that rely on this nested array structure (I don't know why these checks are not in screen-builder)
The simple solution is to check and see if 'items' is an array, and if it is not, wrap it in a single-item array.
=> Check if container items are arrays and convert if not

ProcessMaker/Console/Commands/Install.php, config/database.php, tests/bootstrap.php
Fixes #2816 
Postgres - set to utf8 and default collation setting.
SqlServer - left to laravel defaults, which should be utf8-like
=> Hard code charset and collation settings

resources/views/admin/users/edit.blade.php
Resolves #2814 
The problem was caused when using the array notation to extract the first character of an UTF8 string. When using PHP, all UTF8  manipulations should use the mb_* string functions. 
The problem was resolved using mb_substr.
=> UTF-8 Characters in firstname and lastname

ProcessMaker/Jobs/CompileSass.php
Resolves #2811 
The problem was caused because the docker image  **jbergknoff/sass** uses and old version of sass. 
To solve the problem a new docker image **processmaker4/docker-sass-compiler** has been created. 
NOTE: to test the ticket it is necessary to have the processmaker4/docker-sass-compiler published in dockerhub.
=> Custom CSS Not Refreshing

resources/js/requests/components/RequestDetail.vue, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue, resources/sass/app.scss
- In the Task and Request listing components, converts buttons which were previously using JS events to actual links with href tags
- Requires https://github.com/ProcessMaker/package-savedsearch/pull/114 to bring these changes into Saved Searches
Closes #2851.
=> Convert Task & Request listing buttons to actual links

ProcessMaker/Repositories/TokenRepository.php, tests/Feature/Api/ProcessExecutionTest.php
Fixes #2854 
Add data to startEvent tasks (process_requests_tokens) and set initiated_at and completed_at timestamps
=> Add data to startEvent tasks and save timestamps

ProcessMaker/Models/ProcessVersion.php, ProcessMaker/Models/ScreenVersion.php, ProcessMaker/Models/ScriptVersion.php
- Fixes issue where created_at was `NULL` on Process, Screen, and Script versions
- https://github.com/ProcessMaker/package-vocabularies/pull/17 fixes the same issue for Vocabularies
Closes #2853.
=> Fix created_at on versions for Processes, Screens, and Scripts

ProcessMaker/Events/ActivityAssigned.php, ProcessMaker/Events/ActivityCompleted.php, ProcessMaker/Events/ProcessCompleted.php, ProcessMaker/Events/ProcessUpdated.php, phpunit.xml, resources/js/tasks/components/ProcessRequestChannel.js, tests/Feature/BroadcastTest.php, tests/Feature/Shared/LoggingHelper.php
- Reduces payload size of the following broadcast events by referring to API URLs instead of sending entire object:
- ActivityAssigned
- ActivityCompleted
- ProcessCompleted
- ProcessUpdated
- Updates ProcessRequestChannel component to obtain these objects via API call rather than via the broadcast event
- Adds testing around broadcast events
- To ensure that all broadcast events have a corresponding test
- To ensure that all broadcast event payloads are less than 10KB
Fixes #2857.
=> Fix issue with Pusher payload size

ProcessMaker/Console/Kernel.php, ProcessMaker/Managers/TaskSchedulerManager.php, tests/Feature/Api/IntermediateTimerEventTest.php, tests/Feature/Shared/ProcessTestingTrait.php
Fixes #2882 
- Wrap the task manager in schedule->call so it has access to the full bootstrapped app environment
- Remove unused $schedule argument for scheduleTasks method
=> Wrap task scheduler manager in schedule call method

resources/views/processes/screen-builder/screen.blade.php
- Remove the `Filter` parameter.
- Add the `per_page` and set to a high number to display all available 'Scripts' & 'Data Connectors'
Ref [ScreenBuilder/#591](https://github.com/ProcessMaker/screen-builder/issues/591)
=> Fix Watcher 'Source' selection limit

database/migrations/2020_03_03_181316_update_env_var_value_column.php, resources/views/processes/environment-variables/index.blade.php
- Change the env variable value Input to a Textarea, allowing for displaying longer data. 
- Convert the env variable value column type from 'TEXT' to 'LONGTEXT' in the database allowing storing of data larger than 64kb. 
https://www.loom.com/share/2697f4c87e9b4545a52e333ff90d46d7
- Create an Env Variable with a value longer than 64kb and save
Env variable is successfully created.
closes #2875
=> Fix Environment Variable Text Limit

ProcessMaker/BuildSdk.php, ProcessMaker/Models/Process.php, resources/js/processes/scripts/components/ScriptEditor.vue, resources/js/processes/scripts/customFilters.js, storage/api-docs/api-docs.json
Fixes #2840 
- Escape slash interpreted as unicode for python SDK - bug in OpenAPI Generator
- Remove duplicate property in process schema - causing the Python sdk builder to fail
Executor Package: https://github.com/ProcessMaker/docker-executor-python
SDK: https://github.com/ProcessMaker/sdk-python
=> Updates needed for Python executor runner and SDK

resources/js/requests/components/DataSummary.vue, resources/js/requests/show.js, resources/views/requests/show.blade.php
Fixes #2909
Displays nested data as a flat list with keys seperated with `.`
=> Display nested data summary as a flat list

ProcessMaker/Http/Controllers/Api/EnvironmentVariablesController.php, ProcessMaker/Models/EnvironmentVariable.php, resources/lang/en/environmentVariables.php
This adds validation that ensures that an environment variable has a valid name. This allows `getenv()` to access the variable correctly. 
This addresses [2908](https://github.com/ProcessMaker/processmaker/issues/2908).
The validation checks that:
- the variable name starts with a letter.
- the variable name only contains alphanumeric characters or underscores.
This also adds a custom validation feedback message should the aforementioned validation not pass. This is defined in the newly added translation file (`resources/lang/en/environmentVariables.php`).
Feedback looks as follows:
=> Disallow dashes in Environment Variable Names

ProcessMaker/Models/Process.php, resources/js/processes/modeler/components/inspector/TaskAssignment.vue
- Display input when assigning a user by User ID.
- Enable the input field to run mustache syntax. 
<a href="https://www.loom.com/share/c5c5b6c6b1494a28a44bdfad11712ed5"> <p>5 March, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/c5c5b6c6b1494a28a44bdfad11712ed5-with-play.gif"> </a>
1. Before testing ensure you have an additional user account you are able to login to. 
2. Login as an Admin and create a screen.
3. Add an input field with a variable name `foo`.
4. Add another field that will allow selecting/inputting the above user account id with a variable name `user_id`
5. Create a process and attach the above screen to a task. 
6. Add another task to the process and set the assignment …
=> Fix Assign by Expression User ID

resources/views/admin/users/deletedUsers.blade.php, resources/views/admin/users/list.blade.php
- Removes unneeded classes to fix spacing in the Users and Deleted Users tab
Closes #2933.
=> Fixing spacing in admin/users

resources/js/processes/modeler/components/inspector/ScreenSelect.vue
Fixes #2941 
Fixes task screen select loosing its value in inspector
=> Do not emit empty id when there is no screen yet

resources/js/admin/groups/components/GroupsListing.vue, resources/js/admin/groups/components/UsersInGroupListing.vue, resources/js/admin/users/components/DeletedUsersListing.vue, resources/js/admin/users/components/UsersListing.vue
- Add ID column to the Users & Group tables
closes #2899
=> User/Group ID Column

resources/views/admin/groups/edit.blade.php, resources/views/processes/screens/edit.blade.php
Adds missing Asterisks to
1. Screen config description field
2. Group Members 'Add User' modal field
3. Group Details 'Name' field
Note: 
1. queue management > monitoring > monitor tag > tag name - is part of Horizon's UI.
Closes reopened ticket #2879
=> Add missing Asterisks

ProcessMaker/Models/RequestUserPermission.php, database/migrations/2020_03_16_124924_add_id_request_user_permissions_table.php
Resolves #2961 
This PR fixes and issue when the model is registered by Telescope. To do that following changes were made:
- Remove the primary key (`request_id`, `user_id`) of request_user_permissions
- Add an auto-incremental primary key `id`
- Update the Model
=> Add autoincrement to request_user_permissions

database/migrations/2020_03_16_124924_add_id_request_user_permissions_table.php
- Fixes an issue where `Base table or view not found: 1146 Table '************develop.request_user_permissions' doesn't exist` appeared when running migration `2020_03_16_124924_add_id_request_user_permissions_table` caused by https://github.com/ProcessMaker/processmaker/pull/2962.
Closes #2967.
=> Fix issue with migration

resources/js/processes/modeler/initialLoad.js
This PR fixes an issue with the vocabularies component in modeler. Two elements were accidentally removed from the `nodeTypes` list and this PR re-adds them.
=> Add missing elements to nodes list

resources/js/processes/screen-builder/components/file-download-control.js
The issue occurs when adding a RecordList control, saving the screen, and refreshing. The File Download Control was overwriting the RecordList inspector configurations after refreshing because they shared the same `editor-control`. This PR prevents the RecordList inspector configurations from being overwritten by updating the File Download `editor-control` key value to `FileDownload`. 
<h2>Before</h2>
<a href="https://www.loom.com/share/41ba1258050d4ecd87448d548a6c4c4c"> <p>11 March, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/41ba1258050d4ecd87448d548a6c4c4c-with-play.gif"> </a>
<h2>After</h2>
https://www.loom.com/share/0d544be5732a4f82b45b7f2ecb6a637b
Drag a RecordList control onto …
=> Fix file download editor-control

ProcessMaker/Http/Controllers/AboutController.php
Parses the installed packages from the `package.json`file instead of the `node_modules` directory.
**Note:**
The packages will no longer have a description field since there is no description within the `packages.json` file.
<h4>Before</h4>
<h4>After</h4>
- Navigate to the `About` page in the UI.
- Remove your `node_modules` directory
- Refresh the `About` page.
**Expected Results**
The about page does not break and all of the installed packages are listed. 
closes #2977
=> Fix About Page fails without node_modules

resources/js/processes/modeler/initialLoad.js
This change is required for the documentation feature to work correctly: https://github.com/ProcessMaker/modeler/pull/1137. The code for setting the default Task Assignment data has been moved to that PR.
=> Remove task config override

ProcessMaker/Http/Controllers/TaskController.php, tests/Feature/NotificationControlsTest.php
Resolves #2978 
- The query used to identify the unread notifications has been fixed
- A new test to verify this notification behavior has been added.
=> Notifications Not Clearing by Broadcast

resources/js/components/Comments.vue
Closes #2932 
- Diamond displayed  when flow decisions are listed in history.
=> Use of diamond in Gateways

resources/views/admin/users/list.blade.php
Resolves #2997 
- Button styles of the pagination were fixed to center them vertically.
=> User List Pagination

resources/js/processes/modeler/components/inspector/SignalSelect.vue
Fixes #2990 
Requires: https://github.com/ProcessMaker/modeler/pull/1176
This PR includes the following fixes and improvements:
- Add validation for `id` and `name` properties
- Do not delete unused signals when a signal reference is changed
- Fix create new signal
- Clear signal reference if pointing to a non-existent signal
- Add a list of signals to edit and remove signal definitions
- Validate if a signal is used before remove it
=> Fix Signal Event - QA observations

resources/js/tasks/index.js
Resolves #3032 
The correct translation key is used for the message.
**Before:**
**With the fix:**
=> FR: Overdue Tasks Message

ProcessMaker/Listeners/ActiveUserListener.php, ProcessMaker/Listeners/LoginListener.php, ProcessMaker/Models/User.php, ProcessMaker/Providers/EventServiceProvider.php, config/session.php, database/migrations/2020_04_06_003326_add_active_at_field_to_users_table.php, resources/views/layouts/layout.blade.php
- Adds config option to specify how long a warning appears before a session ends; defaults to 3 minutes
- Adds active_at field to User model in order to better track when users were last active which will allow for better troubleshooting as well as future improvements
Closes #1524.
=> Session timeout

resources/js/admin/script-executors/ScriptExecutors.vue, resources/js/admin/users/components/AddUserModal.vue, resources/js/components/requests/modal.vue, resources/js/processes/modeler/components/inspector/ConfigEditor.vue, resources/js/processes/screens/components/ScreenListing.vue, resources/js/processes/screens/components/modal/modal-screen-add.vue, resources/js/processes/scripts/components/ScriptListing.vue, resources/views/tasks/edit.blade.php
Resolves #2991  
The property header-close-content="&times;" was added to interactive <b-modal>s used in the UI.
This is the PR that resolves the same problem in the ScreenBuilder project:
https://github.com/ProcessMaker/screen-builder/pull/670
=> Modal Close Buttons Hidden

ProcessMaker/Models/Process.php
This allows an incomplete process that contains unconfigured Signal Start Events to be saved.
The `Process` model iterates over the `startEventDefinitions` and returns all `signalRef`s in `getUpdatedStartEventsSignalEvents`.
Originally, this would cause an exception to be thrown if the `signalRef` was not set up:
`Undefined index: signalRef at /home/vagrant/processmaker/ProcessMaker/Models/Process.php:1110`
This PR refactors `getUpdatedStartEventsSignalEvents` to use a more permissive pipeline approach. It will now return an empty array if no `signalRefs` are set, allowing us to save a process that is not fully finished.
**IMPORTANT BEHAVIOUR CHANGE**
The original returned all signal references, i.e. including duplicates. Having to processes start on the same signal would return:
``` …
```
=> Add ability to save process with unset start signal references

resources/js/tasks/components/TasksList.vue
Remove the ID (#) column from the Tasks list under the `/tasks` route.
closes #3073
=> Remove ID column from Tasks

ProcessMaker/PackageHelper.php, resources/js/processes/components/ProcessesListing.vue, resources/views/processes/list.blade.php
This adds a documentation link in the processes list.
The documentation button shows conditionally if the user has `view-processes` privileges and the `package-process-documenter` is installed.
This PR adds a new helper file, `ProcessMaker/PackageHelper.php` that allows us to easily determine whether a package is installed (e.g. by calling `\ProcessMaker\PackageHelper::isPmPackageProcessDocumenterInstalled()`).
Fixes: https://github.com/ProcessMaker/package-process-documenter/issues/12
=> Add documentation view button for package-process-documenter

composer.json, composer.lock
Resolves #2990
- Fix an unsaved token when a throw event is immediately before a catch event.
1. Run the process, generates the `Request 1`
2. This `Request 1` remains in progress
3. Run the process generates the `Request 2`
5. The `Request 1` receives the signal and is completed
4. The `Request 2` remains in progress
=> Save unsaved token on a throw event immediately before a catch event

resources/js/processes/modeler/components/inspector/ScreenSelect.vue
Fixes https://github.com/ProcessMaker/modeler/issues/1216.
Video of fix: https://drive.google.com/file/d/1r9CciDnkL3fzJL1d0rOVFpctPsc0xufF/view?usp=sharing.
To keep the undo/redo history sane (i.e. to prevent every keystroke from adding a history item), we only update state on focusout. However, after selecting an item in the multiselect dropdown, focus does not return to the input and therefor no state update is triggered after making a selection. This PR fixes that issue for this dropdown component.
=> Fix screen select validation update

ProcessMaker/Jobs/ImportScreen.php, tests/Feature/Processes/ExportImportScreenTest.php
- Fixes an issue where screens would not import if they had a category ID but no actual categories
- Relies on the parent Import class for screen import to keep code more DRY
1. Attempt to import this screen specifically:
[Paid Sick Leave Request WE.json.zip](https://github.com/ProcessMaker/processmaker/files/4578043/Paid.Sick.Leave.Request.WE.json.zip)
2. Attempt to import other screens
Fixes #3088.
=> Fix issue with screen import

ProcessMaker/Exception/UserOrGroupAssignmentEmptyException.php, ProcessMaker/Models/Process.php
Resolves #3090 
The issue happened because the selected group (by the rule) is empty - it doesn't have users. 
A new and more specific exception has been added. The exception now is:
=> Assignment by Rules Broken

ProcessMaker/Models/Media.php
- Directly specifies the name of the table in the Media model
- Fixes an issue where an error message appeared on every page after doing a fresh `composer install`
Closes #3115.
=> Specify table name in Media model

resources/js/processes/modeler/components/inspector/ScreenSelect.vue
Resolves #3113 
Multiselect opens the options list when focus is set. This behavior will be resolved in the version 3 of the this component but it still in beta. [Look at this thread](https://github.com/shentao/vue-multiselect/issues/740).
For the problem mentioned above, we added the deactivation of the component so that the  option list is closed after the focus is set. 
In the attached video it can be seen that the process validator is updated when selecting a screen and that the list of screens is opened (for the focus) and closed immediately  when selecting a task.
**Note:** In pull request 3080 the change to set the  focus was added because there was a  problem with the process validator. It was not updated after a screen selection. For reference, these are the issue and the related …
=> "Screen for input" menu always expands when clicking a form task

resources/js/components/common/DataLoading.vue
Resolves #3121 
The problem was caused by the testing condition used to shoe the DataLoading component. It tests if the current request has some specific string but it is not differentiating between get/put/post calls. 
It was added the condition to restrict the DataLoading display just whit GET calls.
=> Auth Client Modal Submitting without Validation

ProcessMaker/Http/Controllers/Api/NotificationController.php
closes #3161 
- Add slashes in filter query notifications
=> Notifications API fails with Apostrophy

resources/js/processes/screen-builder/components/form/file-upload.vue
1. Removes the index stored in the `data_name` prefixes when saving the uploaded file. Allowing correct referencing when using the file download component. 
2. Update the `data_name` prefix for upload files with visibility rules, by checking if the parent of the control is within a record list.
https://www.loom.com/share/75dbb9298ddb4b7e901840308e18b56c
1. Import attached process
[Test Record List.json.txt](https://github.com/ProcessMaker/processmaker/files/4718787/Test.Record.List.json.txt)
**Expected Results**
All uploaded files are able to download in the 2nd task. 
closes https://github.com/ProcessMaker/screen-builder/issues/752
=> Fix RecordList File Upload

resources/views/layouts/navbar.blade.php
Resolves #3181 
The layout was modified so that when a topnav provider is registerd (for example the dynami-ui package) items added by packages are rendered. All PM core menu items in the topnav are removed.
=> Allow topnav items added by packages

resources/views/layouts/navbar.blade.php
Resolves #3196 
The problem was caused for the use of the in_array function to search inside a multidimensional array. This function doesn't work properly with PHPs multidimensional arrays. The search now is done with a function and array_filter
=> Find items of custom menu using array_filter

ProcessMaker/Models/ScriptDockerBindingFilesTrait.php, ProcessMaker/Models/ScriptDockerCopyingFilesTrait.php, ProcessMaker/ScriptRunners/Base.php, tests/bootstrap.php
Fixes #3167 
Requires https://github.com/ProcessMaker/docker-executor-php/pull/8
- Truncates docker log output to 500 characters
- Provides more info when a script task fails
Obscuring sensitive data is not necessary since docker output is only in the system log, not shown to any users.
=> Truncate docker output log and display more info

resources/js/components/Timeline.vue, resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
Resolves #3223 
By mistake to show the timeline it was needed that the comments option for the process was set to active. Changes were made in the requests and task edit screens.
=> Request History Missing

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/Api/ScriptController.php, resources/js/processes/modeler/components/inspector/ScreenSelect.vue, resources/js/processes/modeler/components/inspector/ScriptSelect.vue
- Add `isSelectList` param when using a screen/script select list
- Query only by `name` when using a screen/script select list
- Ensure you have multiple screens/scripts
- In Modeler select a form/script task
- Select the screen/script dropdown. 
- Search for a screen/script
Only relevant screens/scripts are returned based on the search query. 
closes #3218
=> Fix Screen/Script Select

ProcessMaker/Models/ProcessRequest.php, tests/Feature/Api/GlobalSignalsTest.php, tests/Feature/Api/processes/GlobalSignalSourceMissing.bpmn
Resolves #3216 
- A validation to check if a signal event is defined.
- Add a test to validate a process with empty signals did not crash.
=> Validate if signal is defined

ProcessMaker/Models/ProcessRequest.php, resources/js/components/common/DataLoading.vue, resources/js/requests/components/RequestsListing.vue
- Replace the 'Api failed to load` message with the 'No Data Available' message
- Removes the 404 alert error banner
- From inside /requests, run a PMQL search:
participant = "invalidusername"
The 'No Data Available' message appears in the main results.
closes #3214
=> Fix PMQL: 500 ISE "Trying to get property 'id' of non-object"

ProcessMaker/BuildSdk.php, ProcessMaker/Console/Commands/BuildScriptExecutors.php, ProcessMaker/Console/Commands/GenerateSdk.php
Fixes #3215 
I tried both staging and release-testing today and it didn't have the problem. My guess is it was waiting for some large docker image to download. This PR adds additional debugging info to the command. If it stalls at that step again we should be able to see what it's doing.
=> Add additional debug info to script executor build output

resources/js/requests/components/RequestsListing.vue
Resolves #3236 
To solve the problem in the SavedSearch package it was necessary to explicitly check  (without implicit logical comparision) if the sortable field of the column is set to true.
=> Compare explicitly to check is column is sortable

.circleci/config.yml, after.sh, package.json
Fixes #3222 
Required PR for the executor: https://github.com/ProcessMaker/docker-executor-node/pull/5
- Run 14.4.0 when building assets in circleci
- Run 14.4.0 inside homestead/vagrant (Note: vagrant rebuild required)
=> Use node v14.4.0

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Resources/ApiCollection.php, tests/Feature/Api/ProcessTest.php
- Paginates the database request for Process Requests so as to avoid memory limit errors on large datasets
- Adds support for manually passing total number of rows to ApiCollection so that pagination metadata is properly generated
- Manually retrieves the total number of rows from the database request and passes it to ApiCollection
Fixes #3245.
=> Fix issue with pagination of Requests

ProcessMaker/Models/RequestUserPermission.php, ProcessMaker/Models/User.php
- Optimizes the updatePermissionsToRequests method that runs during calls to the Requests API
- Limits **select** clause to retrieve fewer fields
- Processes results in chunks to save memory
- Inserts items as a batch to optimize for speed
Fixes #3245.
=> Optimize updatePermissionsToRequests method

.env.example, ProcessMaker/Console/Commands/Install.php, config/app.php, resources/js/bootstrap.js, resources/views/layouts/layout.blade.php
- Adds a configuration option for API timeout length in milliseconds (0 is no timeout)
- Adds this configuration option to the installer and to the example ENV file
Closes #3259.
=> Make API timeout configurable

ProcessMaker/Http/Controllers/Api/TaskController.php
Removes code that hides the system tasks, this is needed to allow task interaction with connector subprocesses.
closes #3269
=> unhide system tasks

ProcessMaker/Console/Commands/RetryScriptTasks.php
- Adds a console command to retry Script Tasks related to a specific request or process
- Run `php artisan processmaker:retry-script-tasks -h` for details
Closes #3282.
=> Add RetryScriptTasks console command

ProcessMaker/Http/Controllers/Api/ProcessController.php
- Fixes a bug where the Request modal does not display a list of processes by rekeying the list before it is sent to the API collection
Fixes #3286
=> Fix issue with New Request modal not displaying list of processes

resources/views/admin/users/edit.blade.php
This PR adds an alert message notifying the user to logout and back in when the user changes their permissions.
**Reference Jira Ticket**
https://processmaker.atlassian.net/browse/FOUR-1659
=> Fix permissions can overwrite super user status

ProcessMaker/Http/Controllers/Api/ScreenController.php
Screens were being filtered by the screen type & the screen configs. This PR removed those filters allowing it to only filter by the screen name, description & category.
**video**
<a href="https://www.loom.com/share/de5a2ca782404082aba05f13d5d215e6"> <p>Screens - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/de5a2ca782404082aba05f13d5d215e6-with-play.gif"> </a>
**Reference Jira Ticket**
https://processmaker.atlassian.net/browse/FOUR-1309
=> Fix screen search not returning accurate results

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, ProcessMaker/Models/Media.php, resources/js/processes/screen-builder/components/file-upload-control.js, routes/api.php, tests/Feature/Api/ManualTaskTest.php, tests/Feature/Api/ProcessRequestFileTest.php, tests/Feature/Api/ProcessRequestsTest.php, tests/Feature/Api/RequestFileUploadTest.php
- `data_name` is now always required when saving media. 
-  File Upload component in SB now displays a 'required' validation for the 'name' input.
=> Fix Files Package Errors

ProcessMaker/Console/Commands/ProcessmakerClearRequests.php, tests/Feature/ClearRequestsTest.php
Resolves #3307
- Artisan command to clear request/tasks data and records, includes Medias, Comments, Permissions and Collaborations.
- Tests to verify the command
Usage:
```
> php artisan processmaker:clear-requests
Are you sure you'd like to remove all requests and related data? Make sure you have backed up your database as this cannot be undone. (yes/no) [no]:
> yes
```
=> Implement processmaker:clear-requests

ProcessMaker/Jobs/ImportProcess.php, ProcessMaker/Managers/ExportManager.php, ProcessMaker/Managers/PMConfigGenericExportManager.php, tests/Fixtures/pm_config_generic_export.bpmn, tests/Managers/PMConfigGenericExportManagerTest.php
Fixes https://processmaker.atlassian.net/browse/FOUR-1430
Needed by https://github.com/ProcessMaker/package-actions-by-email/pull/39
Fix user being prompted to choose a call activity process when importing a process that contains a package that is a wrapper around call activities (actions by email)
Also adds a generic export manager for PM Config json objects inside bpmn tags
=> Do not assign a process to an imported package call activity

ProcessMaker/Console/Commands/RetryScriptTasks.php
Resolves #3340 
The status active to search for the stalled script tasks was added to the retry script task command.
=> add scripts with status active

package-lock.json, package.json, resources/views/tasks/edit.blade.php
This issue was related to the interstitial feature, once the next screen is rendered, the currentPage variable should be reset to 0
This PR fix the screen currentPage when a screen is loaded after a interstitial next task.
Process to test:
[Claims management process.json.txt](https://github.com/ProcessMaker/processmaker/files/5071835/Claims.management.process.json.txt)
=> Bugfix FOUR-1836

ProcessMaker/Listeners/BpmnSubscriber.php
Resolves #3276 
There was a mistaken in the log parameter. If the evaluated expression has some error it is logged to the process and to PM logs.
=> Fix to error logging call

ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, resources/views/vendor/l5-swagger/index.blade.php, storage/api-docs/api-docs.json
Fixes https://processmaker.atlassian.net/browse/FOUR-1783
The annotation in the controller was incorrect, resulting in wrong documentation for that endpoint.
The fix was to update the annotations to correctly reflect the file stream output
=> Add correct annotation for file downloads

ProcessMaker/Models/User.php, tests/Feature/Api/UsersTest.php
Fixes https://processmaker.atlassian.net/browse/FOUR-1831
The validation rule for users didn't require a password. It did, however, require it at the database level, meaning that if you try to create a user without a password you got a SQL error instead of a standard validation error.
This fix updates the model validation to make it required there.
```
{
"message": "The given data was invalid.",
"errors": {
"password": [
"The password field is required."
]
}
}
```
=> Update user password rule to require it for a new user

ProcessMaker/Http/Controllers/ProfileController.php, database/seeds/PermissionSeeder.php, resources/lang/en.json
Fixes https://processmaker.atlassian.net/browse/FOUR-1721
Adds a new view-other-users-profiles permission.
I also had to refactor the permissions seeder so that it can add new permissions that don't exist.
IMPORTANT: after this is deployed, devops will need to run `php artisan db:seed --class=PermissionSeeder` to add the new permission
=> Add permission to view other user's profiles

ProcessMaker/Console/Commands/IndexedSearchEnable.php, ProcessMaker/Models/ProcessRequestToken.php, config/scout.php, storage/search/.gitignore
- Improves indexing of search records
- Only indexes Tasks with an element_type of **task** or **humanTask**
- Indexes records directly rather than relying upon the built-in indexer which is prone to error
- Protects against potential table locks by catching them and trying again upon release
- Stores index files in a sub-directory for better organization
=> Improvements to search indexing

ProcessMaker/Traits/MakeHttpRequests.php
Reverts ProcessMaker/processmaker#3356
Turns out this was not part of the ticket and adding filter param to all requests will throw errors on some APIs
=> Revert "Add filter data soruces"

ProcessMaker/Jobs/CopyRequestFiles.php, ProcessMaker/Models/CallActivity.php, tests/Feature/Api/CallActivityTest.php, tests/Feature/Api/RequestFileUploadTest.php, tests/Feature/Api/processes/child-files.bpmn, tests/Feature/Api/processes/parent-files.bpmn
Fixes https://processmaker.atlassian.net/browse/FOUR-1820
Call activities (aka Sub Processes) are independent process so files were not shared between them. However, we do copy the data from parent to child and back to parent so it makes sense to do the same with files.
This fix creates a job to copy files between parent and child call activity process requests.
=> Copy files between parent and child call activities

resources/views/errors/403.blade.php, resources/views/errors/404.blade.php, resources/views/errors/500.blade.php, resources/views/errors/base.blade.php, resources/views/errors/unavailable.blade.php
Fixes https://processmaker.atlassian.net/browse/FOUR-1721?focusedCommentId=191728
Remove the toolbar and add some navigation buttons to the error pages to prevent notifications from trying to load.
=> Remove toobar from error pages

ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/ProcessMakerAuthenticate.php, tests/Feature/Api/CssOverrideTest.php, tests/Feature/Api/FilesTest.php, tests/Feature/Api/ScreenTest.php, tests/Feature/Api/ServiceTaskExecutionTest.php, tests/Feature/Api/TasksTest.php
Resolves [FOUR-1782](https://processmaker.atlassian.net/browse/FOUR-1782)
A new Authentication provider has been added. If the API call doesn't have the Accept header, this header is added as Accept:application.json. In this way the call goes through Laravel's API route and the corresponding 401 error is returned instead of redirecting to the login page.
Note that the correct error to return is 401 and not 403 as requested in the ticket FOUR-1782
=> RestApi > When a user doesn't have permissions appear an error exception

ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, storage/api-docs/api-docs.json
Fixes https://processmaker.atlassian.net/browse/FOUR-1873
Change the data_name field to not required and the file name is used as the default
=> Swagger is asking for data_name when testing /requests/.../files/ endpoint

ProcessMaker/Http/Controllers/Api/TaskController.php, resources/js/requests/components/DataSummary.vue, resources/js/requests/components/RequestDetail.vue, tests/Feature/Api/TasksTest.php
Fixes part of https://processmaker.atlassian.net/browse/FOUR-1599
Also switches to bootstrap-vue on task table to fix issue where tasks were not always shown on page load.
=> If the task is closed, check permission on the request instead

Vagrantfile, script_myconf.sh
The following change adds the my.cnf file with the following parameters to enabled the RDS configuration in the homestead development environment as requested at KR-10254
> back_log = 16000
connect_timeout = 31536000
explicit_defaults_for_timestamp = ON
host_cache_size = 653
innodb_adaptive_hash_index = OFF
innodb_change_buffering = none
innodb_checksum_algorithm = none
innodb_checksums = OFF
innodb_doublewrite = OFF
innodb_flush_method = O_DIRECT
innodb_open_files = 6000
innodb_page_cleaners = 2
innodb_purge_batch_size = 600
innodb_purge_threads = 1
innodb_stats_persistent_sample_pages = 128
innodb_use_native_aio = OFF
interactive_timeout = 31536000
max_allowed_packet = 1073741824
max_connections = 1000
max_execution_time = 18446744073709551615
myisam_recover_options = OFF …
=> mysql configuration

ProcessMaker/Console/Commands/IndexedSearchEnable.php
- Fixes an issue encountered when indexing to AWS Elasticache on release-testing server where the chunk size was too large for AWS Elasticache
=> Indexed search: reduce number of records per chunk

routes/api.php, routes/web.php
Resolves [FOUR-1863](https://processmaker.atlassian.net/browse/FOUR-1863)
Processmaker had a restriction to access files from a request. The user needed to have participated in the request. This has been changed. Now to get files from a request, the user just needs to have view access to the request.
=> FOUR-1863: Users assigned permissions to view all requests through group permissions cannot view request files

ProcessMaker/Exception/PmqlMethodException.php, ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Models/ProcessRequest.php, resources/lang/en.json
- Adds a PMQL Method Exception class to throw errors when handling PMQL alias methods
- Adds an error message when searching for invalid requester names
Closes https://processmaker.atlassian.net/browse/FOUR-1671.
=> Improve error message when user not found in PMQL search

resources/js/processes/screen-builder/components/form/file-upload.vue
Fixed https://processmaker.atlassian.net/browse/FOUR-1931
Change filename by id in return information
NOTE: as file id is returned, script tasks that expect file names will need to be modified accordingly.
=> Changes on /file api spoil all file related routines

resources/views/tasks/edit.blade.php
Resolves [FOUR-1117](https://processmaker.atlassian.net/browse/FOUR-1117)
When an API error is generated, now it is cached and the task view status updated accordingly.
=> FOUR-1117 Request Aborted" error banner seen in Firefox after completing task

ProcessMaker/Console/Commands/Css.php, ProcessMaker/Console/Commands/RegenerateCss.php
Resolves [FOUR-1522](https://processmaker.atlassian.net/browse/FOUR-1522)
A new command has been added to recreate css files in case that these are overwritten in an upgrade or other scenarios:
`php artisan processmaker:regenerate-css `
**NOTE:** this command should be added to the list of command that are executed in every PM version upgrade to insure that the users's custom colors are applied.
=> FOUR-1522: CSS customization is reset after an upgrade

resources/js/admin/auth-clients/components/AuthClientsListing.vue
Resolves [FOUR-1971](https://processmaker.atlassian.net/browse/FOUR-1971)
The error happened cause the comparison to filter clients was between a lowercase and a  not modified string.  This has been fixed.
=> FOUR-1971: Auth Client > Search bar does not find Uppercase characters

ProcessMaker/Models/Process.php, storage/api-docs/api-docs.json
The **ImportProcess** job returns the following object:
`return (object)[
'status' => collect($this->status),
'assignable' => $this->assignable,
'process' => $this->new['process']
];`
This includes the newly imported process data, the problem is when being consumed by **sdk-node**, this is not parsed in the response since the item '**process**' is not taken into account and we need this to know the new **id** created for the new one process.
=> Publish new process result in ProcessImport model

ProcessMaker/Models/User.php, ProcessMaker/Traits/SearchAutocompleteTrait.php, resources/js/components/AdvancedSearch.vue, resources/views/requests/index.blade.php, resources/views/tasks/index.blade.php
- Updates the Advanced Search Bar on request and task listing screens to only display current user if a user does not have "view user" permissions
- Updates the Create Saved Search modal to only display lists of shareable users and groups if a user has appropriate permissions
- https://github.com/ProcessMaker/package-savedsearch/pull/200
- https://github.com/ProcessMaker/package-collections/pull/207
Closes https://processmaker.atlassian.net/browse/FOUR-1524.
=> Improve permissions for Advanced Search Bar and Saved Search sharing

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Models/ProcessRequestToken.php, tests/Feature/Api/TaskAssignmentExecutionTest.php
- Fixes an issue where the user magic variable was still null after a user self-assigned a task
- Fixes an issue where the user magic variable was still null after a task was reassigned
- Adds testing
Closes https://processmaker.atlassian.net/browse/FOUR-1994.
=> Persist user data with self-service tasks and task reassignments

resources/js/processes/screen-builder/components/file-upload-control.js
- Fixes an issue where spaces and slashes were not allowed in the variable name for file uploads
Fixes https://processmaker.atlassian.net/browse/FOUR-1927.
=> Allow spaces and slashes in variable name for File Upload control

ProcessMaker/Jobs/CompleteActivity.php, ProcessMaker/Jobs/RunScriptTask.php, ProcessMaker/Jobs/RunServiceTask.php, ProcessMaker/Models/CallActivity.php, composer.json, composer.lock
Related to: https://processmaker.atlassian.net/browse/FOUR-2044
In order to fix the issue, this PR includes:
- Update to Nayra v1.1.1 (Fix the loop in Task 3)
- Change the internal flow when a Task is completed:
1. first update the data,
2. then run the engine (ex. evaluates conditional catch events),
3. and finally close the task
- This change was reviewed for User Tasks, Script Tasks and Call Activities.
=> FOUR-2044 Fix conditional events

composer.json, composer.lock
Fixes #3423 
- upgrade to passport 9
- remove explicit dependencies for psr message bridge and zend-diactoros. The correct versions of those packages will be included by packages that need them.
=> Upgrade to passport 9

resources/sass/app.scss
<h2>Issue</h2>
The issue was caused by the page's CSS properties. The values for `overflow-x` and `height`, were preventing the print dialog from viewing the entire form. 
Add specific CSS rules to overwrite the `overflow-x` and `height` values when printing a page. 
1. Import and run this process [Print Process Test.json.txt](https://github.com/ProcessMaker/processmaker/files/5440866/Print.Process.Test.json.txt) (remove .txt)
2. Fill out the form and submit. 
3. On the Process Summary page open the `Form` tab.
4. Select the `Print` icon.
When the print dialog appears, all form fields should be visible and separated into 2 pages.
**Closes Jira Ticket**
[FOUR-2077](https://processmaker.atlassian.net/browse/FOUR-2077)
=> Fix completed forms partially printing

ProcessMaker/BpmnEngine.php, ProcessMaker/Facades/WorkflowManager.php, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Jobs/BpmnAction.php, ProcessMaker/Jobs/CatchSignalEvent.php, ProcessMaker/Jobs/CatchSignalEventRequest.php, ProcessMaker/Jobs/ThrowSignalEvent.php, ProcessMaker/Managers/WorkflowManager.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Providers/WorkflowServiceProvider.php, ProcessMaker/Repositories/ExecutionInstanceRepository.php, ProcessMaker/ScriptRunners/Base.php, ProcessMaker/Traits/ProcessTrait.php, composer.json, composer.lock, resources/js/components/requests/card.vue, resources/js/processes/modeler/initialLoad.js, resources/js/processes/scripts/components/ScriptEditor.vue, routes/console.php, tests/Feature/Api/GlobalSignalsTest.php
Fix CallActivity-EventBasedGateway
- Fix Message Event throwing/catching Jobs
- Fix Signal Event throwing/catching Jobs
- Update tests
Use case:
The following processes runs 3 requests:
- Request 1: Calls Requests 2, then waits for a signal (`signal1` or `signal2`)
- Request 2: Runs an script, Start Request 3 and finish
- Request 3: Runs an script and then trigger randomly `signal1` or `signa2`
[Call Activity - Event Based Gateway.json.txt](https://github.com/ProcessMaker/processmaker/files/5453363/Call.Activity.-.Event.Based.Gateway.json.txt)
[Signals.json.txt](https://github.com/ProcessMaker/processmaker/files/5453364/Signals.json.txt)
=> Fix CallActivity-EventBasedGateway v4.0.15

ProcessMaker/BpmnEngine.php, ProcessMaker/Jobs/CatchSignalEventProcess.php, ProcessMaker/Jobs/CatchSignalEventRequest.php, ProcessMaker/Jobs/ThrowSignalEvent.php, ProcessMaker/Managers/WorkflowManager.php
Resolves #3449 
Start in intermediate catch signal events can receive and handle payload data. This payload is added to the request as part of its data
=> Signals with payload #3449

ProcessMaker/Jobs/ThrowSignalEvent.php
Resolves [https://processmaker.atlassian.net/browse/FOUR-2227](https://processmaker.atlassian.net/browse/FOUR-2227)
Trailing commas in function calls generate errors in versions lower than 7.3. Those commas were removed
=> FOUR-2227: I cannot edit the record of a collection

resources/js/processes/screen-builder/components/file-upload-control.js
To maintain UI consistency with Variable Name helper labels, a period was needed.
=> Added a missing period

resources/js/processes/screen-builder/components/form/file-upload.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2118
With screen builder 2, the validation prop is no longer being sent to components. It's now nested under config.
=> Fix the required message not showing on file upload

ProcessMaker/Jobs/ThrowSignalEvent.php
For some reason trailing commas were reintroduced in a commit. They were removed again
=> FOUR-2227: can't edit a record

ProcessMaker/Events/ImportedScreenSaved.php, ProcessMaker/Jobs/ImportProcess.php
Emits an `ImportScreenSaved` event after a new screen is saved.
This event is handled in https://github.com/ProcessMaker/package-migration-setup/pull/16
=> Emit an event when a new screen is imported

resources/views/layouts/navbar.blade.php, routes/web.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2127
- Only render the notification bell and and api call if the user has permission
- Add notification permission check to web route
=> Fix 403 error when logging in with a user who has only user permissions

ProcessMaker/Http/Controllers/Api/TaskController.php, resources/js/components/AdvancedSearch.vue, resources/js/tasks/components/TasksList.vue, storage/api-docs/api-docs.json
Fixes part of https://processmaker.atlassian.net/browse/FOUR-2094
Also needs https://github.com/ProcessMaker/package-savedsearch/pull/207
Calls to the tasks api endpoint were filtering by the current user ID. Since this is not always desirable, this fix removes that filter if any PMQL is passed in. Its up to the PMQL to do that kind of filtering.
This PR also adds the user_id filter to the default PMQL on the tasks index page so it returns the same results as before.
=> For tasks endpoint, do all filtering with PMQL when provided

resources/js/processes/screen-builder/screen.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2269
In screen builder, when switching back from preview mode, the defaults that were correctly setup by the renderer, were being erased. This makes it so the preview data is only reset when switching from builder to preview.
=> Don't reset preview data when changing from preview to builder

ProcessMaker/Managers/PMConfigGenericExportManager.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2203
The xml was using a prefix other than 'bpmn' so we needed to register its URI so the rest of the script can continue to reference it as 'bpmn'
=> Register the bpmn namespace when searching for items to export

resources/js/admin/cssOverride/edit.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2275
Adds the editor theme globally so it doesn't try to load it via a url. Missed this because caching was enabled in my local dev environment.
=> Add missing editor theme

resources/js/timeout.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2278
The code that keeps track of how much time is left in a session was decrementing a seconds counter. The problem is if the system sleeps, or in some cases, when the tab is not focused, browser code execution can be paused, causing the counter to be inaccurate.
The solution was to base the timeout on the current timestamp and the timestamp when the session started.
=> Calculate time remaining based of the current timestamp

resources/views/auth/login.blade.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2275?focusedCommentId=202312
Wraps the content in a flexbox so the footer doesn't overlap the login card.
=> Use flexbox for footer to prevent overlapping content

resources/views/admin/users/edit.blade.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2316
Do not load security logs list if the user does not have permission
=> Do not load security logs if the user does not have permission

resources/views/tasks/edit.blade.php
https://processmaker.atlassian.net/browse/FOUR-2426#icft=FOUR-2426
Replaces the nonexisting `this.reload()` method so that the task is properly reloaded when claiming a task.
=> Fix Reload is not a function error

ProcessMaker/Providers/WorkflowServiceProvider.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2327
- Sets the bpmn engine job manager in the singleton for BpmnDocument
=> Add missing engine job manager to workflow service provider

resources/js/processes/screen-builder/screen.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2377
vue-json-pretty v1.7.1 separates the styles and requires them to be imported. Does not effect standalone since its using 1.6.3.
=> Add explicit style import for vue-json-pretty 1.7.1

ProcessMaker/Http/Controllers/Api/NotificationController.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2395
The Notification controller was extending Laravel's base controller for some reason. This was causing a 403 for any non-admin. Fix is to use ProcessMaker's base controller.
=> NotificationController must extend processmaker's controller

ProcessMaker/Listeners/SecurityLogger.php, config/auth.php, config/database.php, phpunit.xml, tests/Feature/Api/TaskAssignmentExecutionTest.php, tests/Feature/AuthTest.php, tests/Feature/RedirectTest.php, tests/Feature/SecurityLoggerTest.php
- Fixes the following tests:
- Adds environment variables to control the MySQL timezone (`DB_TIMEZONE` and `DATA_DB_TIMEZONE`), the lack of which was causing failing tests
- Adds an environment variable (`LOG_AUTH_EVENTS`) to control the logging of security events (login, logout, attempt), the lack of which was causing tests to fail
See commit messages for further information on why tests were failing and how they were fixed
=> Fix broken unit tests

ProcessMaker/Console/Commands/Install.php
Resolves [https://processmaker.atlassian.net/browse/FOUR-2458](https://processmaker.atlassian.net/browse/FOUR-2458)
Fixed the use of UserSeeder constants.
=> FOUR-2458: Unable to complete PM4 installation: "Access to undeclared static property"

composer.json, composer.lock
Resolves [https://processmaker.atlassian.net/browse/FOUR-2444](https://processmaker.atlassian.net/browse/FOUR-2444)
- Laravel/passport has been upgraded to 9.4
- lcobucci/jwt:3.3.3 requirement has been removed
- before this change, guzzlehttp/guzzle was installed as a dependency of laravel/passport 9.3. Version 9.4 doesn't have this dependency and we have in PM code  that uses Guzzle. For that reason guzzlehttp/guzzle 7.2.0 has been added to composer.json.
=> FOUR-2444: When running scripts tasks an error is generated

ProcessMaker/ScreenConsolidator.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2451
Also needs https://github.com/ProcessMaker/screen-builder/pull/855
Removes buttons from nested screens when outputting the compiled screen.
=> Do not include buttons in nested screens

resources/views/tasks/edit.blade.php
Resolves [https://processmaker.atlassian.net/browse/FOUR-2416](https://processmaker.atlassian.net/browse/FOUR-2416)
The problem was caused by a double redirection. If the renderer used is not the standard one, this redirection won't occur.
=> FOUR-2416: Advanced screen does not display any content even by using the default code

composer.json, composer.lock
- Allow the Auth0 plugin to be installed via Composer by making the following changes:
- Downgrade to [guzzlehttp/guzzle 6.5](https://github.com/guzzle/guzzle/releases/tag/6.5.5) because the [latest version of auth0/login](https://github.com/auth0/laravel-auth0/releases/tag/6.1.0) uses [a version of auth0/auth0-php](https://github.com/auth0/auth0-PHP/releases/tag/7.2.0) that does not support Guzzle 7
- Downgrade to [laravel/passport 9.3.2](https://github.com/laravel/passport/releases/tag/v9.3.2) because it does not require any specific version of [lcobucci/jwt](https://github.com/lcobucci/jwt)
- Downgrade to [lcobucci/jwt 3.3.3](https://github.com/lcobucci/jwt/releases/tag/3.3.3) because [auth0/auth0-php](https://github.com/auth0/auth0-PHP) requires it
- QA should re-test …
=> Downgrade to package versions that are supported by Auth0 libraries

ProcessMaker/Factories/SearchRequestFactory.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/ProcessRequestToken.php, config/app.php, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
- Updates request and task list components to utilize a Saved Search endpoint if viewing a Saved Search, an endpoint which removes unneeded columns to reduce payload size and improve security
- Removes unneeded data from the search index
- Overrides the Elasticsearch Scout driver to only return the ID from the Elasticsearch server rather than all data
- https://github.com/ProcessMaker/package-savedsearch/pull/211
- https://github.com/ProcessMaker/package-collections/pull/226
Closes https://processmaker.atlassian.net/browse/FOUR-2449.
=> Saved Search Only Return Columns Needed

resources/js/requests/components/screenDetail.vue
**Resolves Jira Ticket for 4.0.16**
https://processmaker.atlassian.net/browse/FOUR-2455
The issue was caused by the print dialog loading before Nested Screens could load on the page. This PR sets a timeout for triggering the print dialog allowing the Nested Screens to load on the page entirely before printing. 
**Video**
<a href="https://www.loom.com/share/dc15db642f484d87938bab11d5c7a81b"> <p>Edit Screen - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/dc15db642f484d87938bab11d5c7a81b-with-play.gif"> </a>
=> Fix multipage printing with nested screens 4.1

resources/js/requests/components/screenDetail.vue
**Resolves Jira Ticket for 4.0.16**
https://processmaker.atlassian.net/browse/FOUR-2455
The issue was caused by the print dialog loading before Nested Screens could load on the page. This PR sets a timeout for triggering the print dialog allowing the Nested Screens to load on the page entirely before printing. 
**Video**
<a href="https://www.loom.com/share/dc15db642f484d87938bab11d5c7a81b"> <p>Edit Screen - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/dc15db642f484d87938bab11d5c7a81b-with-play.gif"> </a>
=> Fix multipage printing with nested screens 4.0.16

ProcessMaker/Http/Resources/Process.php
This PR allows the inclusion of the svg property on the serialized process when retrieving a process from the /processes/{id} endpoint. 
This is used by [this PR on modeler](https://github.com/ProcessMaker/modeler/pull/1295) to show the svg in a modal when the user clicks [+] on a subprocess.
=> Allow inclusion of SVG in serialized Process

resources/js/processes/categories/components/CategorySelect.vue
- Fixes a bug where the Category Select component did not always default to **Uncategorized** when no other value was selected
Closes https://processmaker.atlassian.net/browse/FOUR-2500.
=> Category select: default to Uncategorized

resources/js/processes/modeler/components/inspector/AssignExpression.vue
**JIRA Ticket**
https://processmaker.atlassian.net/browse/FOUR-2222
- Fix console error `cannot ready property substring of null` when saving Rule Expressions with a Default Assignment.
- Fix issue where ellipsis displays with nontruncated values.
=> Fix 'cannot ready property substring of null' console error

ProcessMaker/Assets/ScriptsInScreen.php, ProcessMaker/Jobs/ImportProcess.php, ProcessMaker/Managers/ExportManager.php
Required by: https://github.com/ProcessMaker/connector-send-email/pull/125
Related to: https://processmaker.atlassian.net/browse/FOUR-2528
Fixes: https://processmaker.atlassian.net/browse/FOUR-2545
- Add log methods that could be used by packages to register messages on importing process.
- Add a validation to check the scripts assigned to watchers
Since the file was generated by an old version of PM4, it does not contains the scripts assigned to watchers, causing an exception during the import process. It was validated and fixed so the process can be imported but without the missing resource.
=> Add log messages from packages on import

ProcessMaker/Jobs/ExportProcess.php, ProcessMaker/Models/CallActivity.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-2569 for v4.1
This PR fixes:
- Export of processes with Call Activities used as Service like (data-connectors)
=> Fix export of service call activity elements

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/ProcessController.php, ProcessMaker/Jobs/ImportProcess.php, ProcessMaker/Notifications/ImportReady.php, config/filesystems.php, resources/views/processes/import.blade.php, routes/api.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-2545
Importing large processes could take time (more than 5 seconds), this PR adds a query property (queue) the import endpoint to execute the import in background, when it is ready a notification in send to the user so it could continue with the import in the user interface.
=> Fix importing large processes

ProcessMaker/ScreenConsolidator.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2647
The screen consolidator reindexer was casting string keys as integers. Page keys must be numeric strings or null.
=> Pages must be numeric strings or null

tests/Feature/Api/CallActivityTest.php
This PR fix CallActivity Media return test, adding missing required parameter `row_id`.
=> Fix CallActivity Media return test

resources/js/components/common/Pagination.vue, resources/js/components/common/mixins/datatable.js, resources/sass/app.scss
- Fixes issues where Vuetables overflowed their boundaries and did not properly scroll horizontally
Before
After
- Requires https://github.com/ProcessMaker/package-collections/pull/240
- Requires https://github.com/ProcessMaker/package-savedsearch/pull/223
- Closes https://processmaker.atlassian.net/browse/FOUR-2677
=> Wide tables scroll horizontally

ProcessMaker/ScriptRunners/Base.php
Required by: https://github.com/ProcessMaker/package-data-sources/pull/116
This PR fix an environment variable required to execute a Script from a http request.
=> Fix missing $HOME envvar when call a script task

ProcessMaker/Models/Process.php, ProcessMaker/Traits/MakeHttpRequests.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-2716](https://processmaker.atlassian.net/browse/FOUR-2716)
Fixes a problem that occurred when a Call Activiy was after a Signal Start Event. As the request instance doens't have a user, the user assignment failed to the activity failed. The new version of data connectors uses a call activity, and for that reason the problem arose.
=> FOUR-2716: Data Connector after a Signal Start Event generates an error

ProcessMaker/Policies/ScriptPolicy.php, resources/views/tasks/edit.blade.php, routes/api.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2691
- Removes permission checks on routes
- Updates policy for core to allow all scripts if the user is not anonymous
- Adds task_id query to script URL override so anonymous users (web entry) can still run scripts in a secure way (without executing other scripts)
=> Update policy for running scripts in tasks

ProcessMaker/Http/Controllers/Api/ScreenController.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2629
- Removes permission check on screens api index so all logged in users can list screens
=> Remove permission check for screens list

ProcessMaker/Http/Resources/Task.php, ProcessMaker/Models/Process.php
https://processmaker.atlassian.net/browse/FOUR-2692
The issue was caused by returning only users assigned to a Group when the `Assignment Type` was set to `User/Group`. This PR returns all `ACTIVE` users, except the current logged in user & system users in the Reassign to dropdown regardless of the 'Assignment Type' configured.
- Ensure you have multiple users created within your environment. 
- Configure a task with any `Assignment Type`
- Enable `Allow Reassignment` 
- Run the process and select `Reassign` within the Task details page.
- The dropdown list populates with all `ACTIVE` users. 
- Selecting a User and clicking the `Reassign` button reassigns the task to the selected user.
**Video** …
=> Fix users populating the 'Reassign to' dropdown

ProcessMaker/Models/CallActivity.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-2709](https://processmaker.atlassian.net/browse/FOUR-2709)
Add the body part of the errors generated inside a Call Activity
Before:
Now:
With the fix the errors include more information. In this case is pointing to an array to string conversion.
All stack trace information is removed.
=> FOUR-2709: we get a generic error 500ish when having a wrong configuration for data connectors

resources/js/processes/scripts/customFilters.js
The PHP documentation inside the script editor for accessing an environmental variable is incorrect. It needs to be "getenv" and not "get_env" -- this fixes the docs.
=> Removed underscore for PHP accessEnvVar

resources/js/processes/modeler/components/inspector/ConfigEditor.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-2725](https://processmaker.atlassian.net/browse/FOUR-2725)
When modifying the code variable (config of the script) an undefined value was always emitted. This emit has been removed.
=> FOUR-2725: Selected script disappears when editing script config

resources/js/processes/modeler/components/inspector/AssignExpression.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2772
- Was setting with a prefix "group-". This removes that when setting in the BPMN
- NOTE: user will need to unselect and reselect group to set it to the fixed value
=> Replace prefix when setting the assigned group

ProcessMaker/Http/Controllers/Api/ScreenController.php, database/seeds/ScreenSystemSeeder.php, resources/js/processes/modeler/components/inspector/Interstitial.vue, resources/js/processes/modeler/components/inspector/ScreenSelect.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2779
NOTE: requires devops to run `php artisan db:seed --class=ScreenSystemSeeder` after code is updated
- Allows users to edit the default screen interstitial that gets seeded with the app
=> Allow users to edit the default interstitial

ProcessMaker/Http/Controllers/Api/SignalController.php, ProcessMaker/Managers/SignalManager.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-2757](https://processmaker.atlassian.net/browse/FOUR-2757)
Uses the filter sent by the inspector to exlude the current process to get the global signals
=> FOUR-2757: Start signal, it only works with the last configured process.

database/seeds/ScreenSystemSeeder.php
Addendum to https://processmaker.atlassian.net/browse/FOUR-2773
Multiple screens were being created when the seeder ran multiple times. This fixes that
=> Fix duplicate screens created in seeder

resources/js/processes/modeler/components/inspector/ScreenSelect.vue
Fixed [FOUR-2721](https://processmaker.atlassian.net/browse/FOUR-2721)
- allow emitting empty when a screen is deselected
=> Modeler: Can not un-select screen after it’s been selected.

ProcessMaker/Http/Controllers/Api/ScreenController.php, resources/js/processes/modeler/components/inspector/ScreenSelect.vue, resources/js/processes/screens/components/ScreenListing.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-2841](https://processmaker.atlassian.net/browse/FOUR-2841)
The problem occurred  for a group of screens that had a very large configurations. To avoid this a new query parameter for the endpoint that list screens has been added. The new query string parameter is named "exclude".
Swagger documentation was updated too.
=> FOUR-2841: It takes a long time to enter the screen list

ProcessMaker/Exception/Handler.php
- Fixes an issue where a 500 error was returned instead of a 404 error in certain package API routes (for example: Collections and Saved Search)
- Refactors the way a fallback route is determined when a model is not found in a bound route
- Many packages do not namespace API route names with the `api.` prefix but rather with the name of the package
- This caused the fallback routing to return the web fallback route when a model could not be found, which in turn generated a 500 error because web middleware was being used on an API route
- Now we determine whether a fallback route exists under the package namespace
- If so, we return it
- If not, we check to see whether API middleware is in use and fallback to our API fallback route if so
Closes …
=> Fix issue with fallback routing in packages

ProcessMaker/Models/User.php, ProcessMaker/Traits/HasSelfServiceTasks.php
https://processmaker.atlassian.net/browse/FOUR-2913
This PR adds self-service support for users by including the `assignedUsers` array in the `self_service_groups` array.
- Ensure to have additional users created.
- Create a process and set the 'Assignment Rules' to 'Self Service' with a user assigned.
- Log in as the assigned user and view the 'Self Service' tasks, open the task.
When selecting the task the 'Claim Task' button appears with no errors.
=> Add self service support for users

ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/ProcessRequestToken.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-2921](https://processmaker.atlassian.net/browse/FOUR-2921)
Added filtering by id and dates of process requests, and process request tokens.
=> FOUR-2921: Unable to filter the list in a Saved Search chart

ProcessMaker/Http/Resources/Task.php, resources/views/tasks/edit.blade.php
When a user enables the reassignment task option, and the system has a large number of active users it will break the task screen.
- Change the way to get the users to reassign, now get the list of users from `api/1.0/users` using the pagination and filter options
- Deprecates the `assignableUsers` include option from task endpoint
=> Fix reassignment list of users

database/migrations/2020_11_16_215424_create_security_logs_table.php
- Fixes an issue where the security logs migration was not specifying the proper connection, which is needed in a two-database system
Closes https://processmaker.atlassian.net/browse/FOUR-2969
=> Update security logs migration to use connection (v4.1.1)

database/migrations/2020_11_16_215424_create_security_logs_table.php
- Fixes an issue where the security logs migration was not specifying the proper connection, which is needed in a two-database system
Closes https://processmaker.atlassian.net/browse/FOUR-2969
=> Update security logs migration to use connection (v4.2)

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
- Adds a restriction to the Requests index endpoint to prevent users without "view all requests" permission from seeing requests in which they have not participated
https://processmaker.atlassian.net/browse/FOUR-2309
=> Restrict users without "view all requests" permission to participated-in requests

ProcessMaker/Managers/ScreenBuilderManager.php
Problem: When a package is updated, its javascript is not updated in the client browser because of the cache.
This PR adds a timestamp to screen javascript extensions to fix the problem.
=> Add timestamp to screen extensions

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Managers/TaskSchedulerManager.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/ProcessRequestToken.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-3021
This PR fixes:
- Get BPMN definitions from the request's version
=> Fix: Get BPMN definitions from the request's version

resources/views/about/index.blade.php
While looking through translations, I noticed "Report Issue" was still untranslated. Turns out at some point we changed "Report an issue" to "Report Issue" and this broke all our translations. This fixes https://processmaker.atlassian.net/browse/FOUR-744
=> Changed "report issue" string

ProcessMaker/Traits/MakeHttpRequests.php
In a previous version of collections/data-connector, some collection's data-sources were created with an incomplete url (without the protocol and server name)
This PR fixes this problem for those data-sources.
=> Fix execution of incomplete datasource URLs

ProcessMaker/Traits/MakeHttpRequests.php
Fixed [FOUR-3142](https://processmaker.atlassian.net/browse/FOUR-3142)
- remove old parameter outboundConfig
=> Error when trying to configure a Data Connector with third-party API endpoints

ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Traits/ExtendedPMQL.php
- Fixes an issue where the task counts on built-in To Do & Self Service Saved Searches were incorrect
- Refactors PMQL to accept a user parameter so that only self service tasks for the Saved Search owner are counted
- https://processmaker.atlassian.net/browse/FOUR-3095
- https://processmaker.atlassian.net/browse/FOUR-3099
- https://github.com/ProcessMaker/package-savedsearch/pull/237
=> Fix Saved Search To Do & Self Service Task counts 

ProcessMaker/Models/ProcessRequestToken.php
- Fixes an issue where Saved Searches displaying **completed** tasks may have displayed the wrong count
- Refactored the task status PMQL alias to use "COMPLETED" as a possible status in addition to "CLOSED," since the workflow engine generally sets tasks to "COMPLETED" status before they are set to "CLOSED"
Closes https://processmaker.atlassian.net/browse/FOUR-3169
=> Fix Completed Tasks counter

resources/views/requests/show.blade.php
Resolves: https://processmaker.atlassian.net/browse/FOUR-3041
The data loading was broken by an script error when disabling the buttons of the screen summary.
This PR fix the wrong reference to disable buttons in summary screen.
=> FOUR-3041: Fix The data in the Data tab disappears when the end Event has a screen

ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Jobs/ExecuteScript.php
Fixes https://processmaker.atlassian.net/browse/FOUR-3139
- Api calls to execute scripts run in sync mode instead of waiting for a broadcast event on the queue
- Data sources directly connect to the data source api instead of going through a service task
Requires
- vue-form-elements: https://github.com/ProcessMaker/vue-form-elements/pull/264
- screen-builder: https://github.com/ProcessMaker/screen-builder/pull/972
- web-entry: https://github.com/ProcessMaker/package-webentry/pull/114
Steps to deploy:
- After vue-form-elements is published to npmjs, update the version in the screen-builder pr and core (this pr)
=> Allow scripts to be run in sync mode

resources/js/admin/settings/components/SettingObject.vue, resources/js/admin/settings/components/SettingScreen.vue, resources/js/admin/settings/components/SettingsListing.vue
- Adds the option of using an exported ProcessMaker screen as a setting component
- Used by https://github.com/ProcessMaker/package-auth/pull/9 to add a cron job frequency setting
=> Add option to use a ProcessMaker screen as a setting component

ProcessMaker/Http/Kernel.php
Adding client_credentials support to routes.
See https://laravel.com/docs/6.x/passport#client-credentials-grant-tokens
```
use Laravel\Passport\Http\Middleware\CheckClientCredentials;
protected $routeMiddleware = [
'client' => CheckClientCredentials::class,
];
```
After adding this to the core, packages can use this type of granting and attach the middleware to a route:
```
Route::get('/orders', function (Request $request) {
...
})->middleware('client');
```
=> Adding client credentials route middleware

ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Managers/SignalManager.php, database/seeds/PermissionSeeder.php, resources/lang/en.json, resources/views/processes/modeler/index.blade.php, routes/api.php, routes/web.php, tests/Feature/Api/SignalPermissionsTest.php
Fixes part of https://processmaker.atlassian.net/browse/FOUR-3247
- Requires https://github.com/ProcessMaker/package-data-sources/pull/150 for webhook permissions
- Requires https://github.com/ProcessMaker/modeler/pull/1353 for modeler signal permission checks
These seeders need to be run
```
php artisan db:seed --class=PermissionSeeder --force
php artisan db:seed --class="ProcessMaker\Packages\Connectors\DataSources\Seeds\DataSourcePermissionSeeder" --force
```
=> Add signal and webhook permissions

resources/js/admin/settings/components/SettingsListing.vue
- Fixes an issue where a warning `Cannot read property 'refreshOnSave' of null` was sometimes displayed when saving settings
- Use Lodash `_.get` function to safely retrieve UI setting and simply return null if it doesn't exist
https://processmaker.atlassian.net/browse/FOUR-3285
=> Fix refreshOnSave error

ProcessMaker/Http/Controllers/Api/CssOverrideController.php
https://processmaker.atlassian.net/browse/FOUR-3258
The error occurred due to the Auth::user() returning null. There have been a few occurrences of this happening when using Laravel + Passport. 
https://stackoverflow.com/questions/61125681/authuser-returns-null-laravel-passport
https://github.com/laravel/framework/issues/30402
This may be occurring elsewhere, however, the following workaround I was able to find for this endpoint was within this answer on SO number 3.
https://stackoverflow.com/a/46111430
- Replaces `Auth::user()->getKey()` that returned `null` with `$request->user('api')->id` 
**Video**
https://www.loom.com/share/944cfc9c3e324f1b911b11dc87f55585
=> Fix Custom UI RESET button

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/RequestController.php, resources/js/requests/components/CounterCard.vue, resources/js/requests/components/CounterCardGroup.vue, resources/js/requests/index.js, resources/views/requests/index.blade.php, tests/Feature/RequestTest.php
- Fixes an issue where counts displayed at the top of the Requests index page could be inaccurate
- Utilizes same code as Requests API and Saved Searches to return counts
- Returns counts asynchronously via API rather than on page load, increasing page load speed
- Streamlines API calls to only return the total amount and not the entire data set
- Refactors counter cards as Vue components
- https://processmaker.atlassian.net/browse/FOUR-3260
- https://processmaker.atlassian.net/browse/FOUR-3261
=> Refactor counters on Requests index page

ProcessMaker/Jobs/RunServiceTask.php
Fixed [FOUR-3328](https://processmaker.atlassian.net/browse/FOUR-3328)
- Add variable not_override_request to avoid overwriting the magic variable _request.
=> If we use {{_request.id}} variable in Email Notification, it add the number request and add a request

ProcessMaker/Http/Resources/Task.php
PR [3810](https://github.com/ProcessMaker/processmaker/pull/3810) was missing declaration for the `GroupMember` class causing an error when trying to claim a self-service task. This PR adds the missing class.
=> Add missing GroupMember Class

ProcessMaker/Http/Resources/Task.php
https://processmaker.atlassian.net/browse/FOUR-3106
The `assignableUsers` was deprecated in [PR 3704](https://github.com/ProcessMaker/processmaker/pull/3704) for setting the 'Reassign to' user dropdown, however, `assignableUsers` is still being used to retrieve the users that can claim a self-service task. This PR brings over the fix from 4.1 https://github.com/ProcessMaker/processmaker/pull/3810
- Remove the deprecated code for setting the 'Reassign to' users dropdown that also affected the assignable users for claiming a self-service task. This code prevented the 'Requester' from claiming a task if they were assigned as a self-service user or a member within an assigned group.
- Retrieve all active assigned users and group members, including the …
=> Fix ability for Requester to claim Self Service Tasks when assigned or in a assigned group

ProcessMaker/Http/Resources/Task.php
https://processmaker.atlassian.net/browse/FOUR-3423
This PR brings the fix from [4.1.19](https://github.com/ProcessMaker/processmaker/pull/3823) into 4.2. 
- Add conditional to check if `assignment` is set within the `definition` object.
**Video**
https://user-images.githubusercontent.com/52755494/119534808-2c120d00-bd3c-11eb-80da-ced98821f0d6.mov
=> Fix 'undefined assignment' error when running email connector

ProcessMaker/Traits/MakeHttpRequests.php
Fixes https://processmaker.atlassian.net/browse/FOUR-3407
The UI says that if you leave the "Source" field blank in the output setting, the entire returned payload should be put into the Form Variable. It was putting a bunch of other stuff in there too, including the form data for some reason. This fixes that.
=> Return the entire payload when mapped value is blank

resources/views/admin/groups/edit.blade.php
https://processmaker.atlassian.net/browse/FOUR-3327
The `users-in-group` and `groups-in-group` components were sharing the same `filter` variable. This clashed with each other and prevented the `users-in-group` search from properly filtering the data. This PR separates the shared `filter` variable and creates a unique variable for each of the components. 
**Video**
https://user-images.githubusercontent.com/52755494/120718419-14dec800-c47e-11eb-806b-a0cd4cb0849c.mov
=> Fix Search Group Users

ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Traits/ExtendedPMQL.php
Fixes part of https://processmaker.atlassian.net/browse/FOUR-3078
- This allows us to use IN and NOT IN operators without modifying the valueAlias* methods
=> Add support for IN and NOT IN operators for value aliases

ProcessMaker/Models/Process.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-2723](https://processmaker.atlassian.net/browse/FOUR-2723)
The issue was replicated in release testing along because it was needed that at least one process (of all the list of processes in the database) to be configured with start permissions as user (or group) and let the user/group empty.
=> Verify if user or group is set to add a process to the start list

ProcessMaker/Http/Controllers/Admin/SettingsController.php, ProcessMaker/Http/Controllers/Api/PermissionController.php, resources/js/admin/settings/components/SettingsListing.vue, routes/api.php
Fixes part of https://processmaker.atlassian.net/browse/FOUR-3392
- Allows custom components to be used for settings
- Allows those custom components to be loaded from a package via addons
- Adds an endpoint to get all permissions
=> Allow packages to use a custom component to add to settings

ProcessMaker/Http/Controllers/Api/CommentController.php
Fixes [SEC-27](https://processmaker.atlassian.net/browse/SEC-27)
- Add the validation of comment when the user is owner if user is not the owner of comment return 403
=> Insecure Direct Object Reference in File Manager comments

resources/js/app-layout.js, resources/js/components/Breadcrumbs.vue, resources/views/layouts/layout.blade.php, resources/views/layouts/navbar.blade.php, resources/views/shared/breadcrumbs.blade.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2335
- Moves breadcrumbs into navbar so it's hidden by default on mobile
- Brings back necessary overflow-hidden from https://github.com/ProcessMaker/processmaker/commit/65c176dc2619e3e2a7da75337bf1363d2e5ecd23#diff-8a78110b49caab98f3f9257488caad23dc1b9401c91ecf7eca7a747606be73fdL80 (Dante is working on another solution)
=> Move breadcrumbs into navbar component

ProcessMaker/Console/Commands/RetryScriptTasks.php, ProcessMaker/Managers/TaskSchedulerManager.php, ProcessMaker/Repositories/TokenRepository.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-3598](https://processmaker.atlassian.net/browse/FOUR-3598)
- Stores service task activities with the correct label "serviceTask" in the process_request_tokens table
- Support to retry service tasks when the command  processmaker:retry-script-tasks   is run
- Remove lock from requests that are blocked for more time than the configured by the environment variable BPMN_ACTIONS_MAX_LOCK_TIME
=> FOUR 3598: In many servers requests are blocked by the process_request_locks table

ProcessMaker/Console/Commands/RetryScriptTasks.php, ProcessMaker/Managers/TaskSchedulerManager.php, ProcessMaker/Repositories/TokenRepository.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-3598](https://processmaker.atlassian.net/browse/FOUR-3598)
- Stores service task activities with the correct label "serviceTask" in the process_request_tokens table
- Support to retry service tasks when the command  processmaker:retry-script-tasks   is run
- Remove lock from requests that are blocked for more time than the configured by the environment variable BPMN_ACTIONS_MAX_LOCK_TIME
=> FOUR-3598 (for dev branch): In many servers requests are blocked by the process_request_locks table

ProcessMaker/Jobs/BpmnAction.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/ProcessRequestLock.php, database/migrations/2021_06_28_115443_add_due_at_process_request_locks.php, tests/Feature/RequestLockTest.php
- Catch exceptions while executing a Request, and log the errors in the Request
- Prevent infinite lock, implement `config('app.bpmn_actions_max_lock_time')` per BPMN element lock and lock retries
=> Fix request locks

ProcessMaker/Models/CallActivity.php, tests/Feature/Api/CallActivityTest.php, tests/Feature/Api/processes/child-with-form-task.bpmn
Related: https://processmaker.atlassian.net/browse/SCO-8636
This PR fix:
- CallActivity was loading and listening events for the latest version of the subprocess always not the version at which it was started.
=> Fix CallActivity execution when subprocess is modified

ProcessMaker/Models/User.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-3612](https://processmaker.atlassian.net/browse/FOUR-3612)
The query was modified to use a join and the user_id index to avoid the subquery that usually is slower
Before the modification the MySql planner didn't use the user_index:
After the modification the index is used:
=> FOUR-3612: Review and improve sql query request_user_permissions

ProcessMaker/Console/Kernel.php
This change is for High Availability configurations with clustering. The first server to obtain the task will secure an atomic lock on the job to prevent other servers from running the same task at the same time.
https://laravel.com/docs/6.x/scheduling#running-tasks-on-one-server
=> Add onOneServer to all commands

ProcessMaker/Managers/DataManager.php, tests/Feature/DataManagerTest.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-3457
- Add test for DataManager
- Return magic variable `_user` when no token is available
=> Return initial data when no token is available (WebEntry StartEvent)

ProcessMaker/Console/Commands/UnblockRequest.php
Fixes [https://processmaker.atlassian.net/browse/SCO-8903](https://processmaker.atlassian.net/browse/SCO-8903)
For every request with id number “REQUEST_ID” that needs to be unblocked, run the following instructions from the command line:
php artisan processmaker:unblock-request --request=REQUEST_ID
for example:
php artisan processmaker:unblock-request --request=918
=> SCO-8903: Resend requests with "Script took too long to complete. Consider increasing the timeout."

resources/views/tasks/edit.blade.php
Fixes https://processmaker.atlassian.net/browse/FOUR-3631
Fixes https://processmaker.atlassian.net/browse/FOUR-3606
- Disable the submit functionality if the api call is still in progress
=> Prevent submitting a task multiple times

ProcessMaker/Managers/TaskSchedulerManager.php
Fixes [https://processmaker.atlassian.net/browse/FOUR-2337](https://processmaker.atlassian.net/browse/FOUR-2337)
The condition to test if JSON column had and empty array has been fixed
Documentation for the conditions syntax has been added in 
https://docs.google.com/document/d/10J7f7351vGmv7UFvTI7oVwsHsynLg9qlkvBiNgfR1NY/edit?usp=sharing
=> FOUR-2337: Start Conditional Event does not work 

ProcessMaker/Models/CallActivity.php
Resolves: https://processmaker.atlassian.net/browse/FOUR-3323
Fix `_parent` variable, before the fix MultiInstance SubProcesses did not receive the parent variables inside `_parent` as expected for MultiInstance.
Fixed example:
```
{
"name": "bbb",
"row_id": "bkqmc2hdxgdkr3nbmek",
"_parent": {
"users": [
{
"name": "aaa",
"row_id": "ofqsst7l03kr3nbkv8"
},
{
"name": "bbb",
"row_id": "bkqmc2hdxgdkr3nbmek"
},
{
"name": "ccc",
"row_id": "1j9nxhu50l2kr3nboks"
}
],
"config": {
"name": "Sub Process",
"processId": 5,
"startEvent": "node_1",
"calledElement": "ProcessId-5"
},
"node_id": "node_6",
"process_id": 6,
"request_id": 1
},
"loopCounter": 2,
"numberOfInstances": 3,
"numberOfActiveInstances": 3,
"numberOfCompletedInstances": 0
}
```
=> Fix _parent data for MultiInstance CallActivity

resources/lang/en.json, resources/views/tasks/edit.blade.php
Fixes https://processmaker.atlassian.net/browse/FOUR-3647
- Show the task form when the the self-serve task is unclaimed
- Disable the submit button when unclaimed
- Show a warning if the submit button is clicked
- Append the same warning to the claim task banner so the user doesn't spend time filing out a form they can't submit
=> Show task form when uncliamed and disable submit

ProcessMaker/Http/Controllers/Api/PermissionController.php, resources/views/admin/users/edit.blade.php
- Refactors permissions UI and API call to better handle changing the is_administrator property of a user
- Prevents multiple API calls from being made when they are not necessary
- Updates inline API documentation
- http://tickets.pm4overflow.com/tickets/164
- https://processmaker.atlassian.net/browse/FOUR-3676
=> FOUR-3676: Fix for Super Admin toggle working inconsistently

ProcessMaker/Models/Comment.php
- Adds support for comments _and their replies_ to send notifications
- Adds `element_name` and `url` attributes to the Comments model to allow for both comments and replies to send notifications
- https://github.com/ProcessMaker/package-comments/pull/71
- http://tickets.pm4overflow.com/tickets/155
- https://processmaker.atlassian.net/browse/FOUR-3535
=> Comments: send notifications for users tagged in replies

resources/js/processes/screen-builder/screen.vue
Fixes: https://processmaker.atlassian.net/browse/FOUR-3699
Safari does not support regular expressions with **lookbehind**. This was stored in the json definition of some screens in the inspector section.
https://caniuse.com/js-regexp-lookbehind
This PR prevents that errors during validation check break the screen builder loading
=> Prevent errors during validation break the screen builder loading

ProcessMaker/Http/Controllers/Api/TaskController.php
Fixes https://processmaker.atlassian.net/browse/FOUR-3648?focusedCommentId=228305
- At some point self_service_groups column was changed to an object with user and group arrays, instead of just an array of group ids. This fix searches those values too.
=> Search nested json for self-serve groups and users

ProcessMaker/Http/Requests/RecordRequest.php, ProcessMaker/Traits/MakeHttpRequests.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-3735
This PR fixes the outbound configuration and check the parameters arrives properly
- Fix list of params
- Add `mustache`, `feel` labels to clarify the expressions format
- Add `mustache/feel` switch to choose the right format when required
- Fix the returned error message from endpoint
_**Request variables:**_
1. foo = "bar"
2. number = 100
3. _request = { id: 1001 }
4. array = [1, 2, 3]
_**Dataconnector:**_
- URL = `http`://example.com/api/`{{version}}`/resource?param1=`{{param1}}`
- Params:
- param2 = value
- param3 = {{ param3 }}
- param4 = {{ param4 }} *required
_**Outbound configuration:**_
- version = {{ number }}   // `{ Mustache }`
- param1 = foo   // `{ Mustache }`
- param3 = foo   // `feel`
_**Result:**_
URL: …
=> Fix params replacing

ProcessMaker/Traits/MakeHttpRequests.php
Check empty query string
Fix fail when an empty query string
=> Check empty query string

ProcessMaker/Jobs/BpmnAction.php, ProcessMaker/Jobs/CatchSignalEventInRequest.php, ProcessMaker/Jobs/CatchSignalEventRequest.php, ProcessMaker/Managers/SignalManager.php, public/definitions/ProcessMaker.xsd
Fixes: http://tickets.pm4overflow.com/tickets/326
The problem was caused because the signal catch was processed by an stand alone engine, causing that the parent process instance did not receive the end event from the subprocess.
To fix it the code to process the catch was moved to a BpmnAction Job.
**Sub Process:**
**Parent Process:**
=> Fix Subprocess triggered by a Webhook to an Intermediate Catch Event

ProcessMaker/Listeners/CommentsSubscriber.php
Fixes [https://github.com/ProcessMaker/processmaker/compare/bugfix/ticket-357](https://github.com/ProcessMaker/processmaker/compare/bugfix/ticket-357)
The label that is registered in history has been modified to be in the format GatewayName + FlowName  instead of  "Gateway: " + FlowName. 
QA Notes:
- Items in  request history are stored as comments, so the new forma will be used with new requests only
- If the gateway hasn't a name, "Gateway" will be used as default.
Example process:
New format for history:
=> ticket 357: Request summary screen/History gateway history item does not show the name of the gateway

ProcessMaker/Managers/TaskSchedulerManager.php
Fixes bug found in [http://tickets.pm4overflow.com/tickets/517](http://tickets.pm4overflow.com/tickets/517)
=> ticket 517: Boundary timer events getting wrong bpmn version

resources/views/requests/show.blade.php
Fix:http://tickets.pm4overflow.com/tickets/573
This PR fix the reference to the screen definition.
=> Fix summary screen loading

ProcessMaker/Jobs/CompileSass.php
Replacing Sass Compiling tool using node-sass included on the package.json.
=> Replacing docker sass compiler with nodejs sass

ProcessMaker/BuildSdk.php
PR to update openapitools/openapi-generator-cli to version 5.1.1.
Version Details: https://github.com/OpenAPITools/openapi-generator/releases/tag/v5.1.1
Highlights:
- [Enhancement] added support for custom type & format mapping #9285
- [Docker] support multi-arch build #9246
- Gradle plugin - @Input and @Internal should not be apply on the same property #9059
- [core] Allow using lists as global property in config files #8339
- Add executionId to filehash in OpenAPI Generator Maven Plugin #7848
- Image based on JDK 11
Development Interests:
- Add docker image support for ARM/Apple Silicon.
=> Updating openapitools/openapi-generator-cli to version 5.1.1

resources/js/processes/screen-builder/screen.vue
Found while fixing http://tickets.pm4overflow.com/tickets/510
- Re-render when switching back to design mode because it was throwing errors on nested vars (like `foo.bar`)
=> Re-render when switching to design mode too

tests/Feature/Console/InstallTest.php
This PR removes the second database parameters from the installer test `tests/Feature/Console/InstallTest.php `.
=> Remove second DB params

ProcessMaker/Models/Group.php, database/factories/GroupFactory.php, database/migrations/2021_08_24_064310_add_manager_id_on_groups_table.php, resources/js/admin/groups/edit.js, resources/js/processes/modeler/components/inspector/UserSelect.vue, resources/lang/en.json, resources/views/admin/groups/edit.blade.php, tests/Feature/Admin/GroupTest.php, tests/unit/ProcessMaker/Models/GroupTest.php
Fixes: http://tickets.pm4overflow.com/tickets/629
- Migration to add manager_id to groups table
- Model updated to load Manager
- Group Factory updated to include manager user
- Unit Tests for Group Model
- Test Group Edit page loads properly the new property
Hints: On an already existing database, the new property manager will be filled by null
https://user-images.githubusercontent.com/8028650/130637622-1edb903c-c514-48a2-a3af-f865d05409bf.mp4
=> Add Group Manager

ProcessMaker/Models/User.php, tests/Feature/Api/UsersTest.php
Fixes http://tickets.pm4overflow.com/tickets/664
- Allows for 3 character usernames and modifies existing test
Note: Email addresses as usernames (and tests) were already added by https://github.com/ProcessMaker/processmaker/pull/3889
=> Allow 3 character usernames

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/js/processes/modeler/components/inspector/TaskAssignment.vue, resources/js/processes/modeler/initialLoad.js, resources/lang/en.json, resources/views/processes/modeler/index.blade.php
Implements [http://tickets.pm4overflow.com/tickets/671](http://tickets.pm4overflow.com/tickets/671)
- Makes Assignment Rules toggles extensible
-  To extend or add toggles a page should add items to the new ProcessMaker.modeler.configurables array
-  The list of items inside the Assignment Rules is also extensible by packages adding items to ProcessMaker.modeler.assignmentTypes array.
=> ticket 671 : Task Assignment Toggles Implementation

ProcessMaker/Models/User.php, storage/api-docs/api-docs.json
This PR adds a getter/setter for User->meta to SDK.
`meta` is of type `Free-Form Object`
Example of use:
```
<?php
$apiInstance = $api->users();
$user = $apiInstance->getUserById(3);
$meta = $user->getMeta();
$meta['bar'] = 'bar';
$user->setMeta($meta);
$apiInstance->updateUser(3, $user);
return [
'user_meta' => $user->getMeta()
];
```
=> Add getter/setter for User->meta

ProcessMaker/BuildSdk.php, ProcessMaker/Console/Commands/BuildScriptExecutors.php, ProcessMaker/Facades/Docker.php, ProcessMaker/Http/Controllers/Api/ScriptExecutorController.php, ProcessMaker/Managers/DockerManager.php, ProcessMaker/Models/ScriptDockerBindingFilesTrait.php, ProcessMaker/Models/ScriptDockerCopyingFilesTrait.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, config/app.php, tests/Feature/Docker/DockerFacadeTest.php
This feature adds the capability to use a remote docker server instead a local one, also adds the capability to define a custom timeout command.
In order to enable this on ProcessMaker two new env variables can be included on the `.env` file.
**PROCESSMAKER_SCRIPTS_DOCKER_HOST=
PROCESSMAKER_SCRIPTS_TIMEOUT=**
_PROCESSMAKER_SCRIPTS_DOCKER_HOST_ allows to define the URI required to connect to the remote docker server (example: 'tcp://10.10.0.1:2376')
_PROCESSMAKER_SCRIPTS_TIMEOUT_ allows to define the path for the custom timeout command (example: In MacOS timeout command is '/usr/local/bin/gtimeout')
=> Implement Docker Remote Logic

resources/js/processes/screen-builder/screen.vue
Fixes http://tickets.pm4overflow.com/tickets/725
Removes the Calcs button on the screen builder for any type other than forms
=> Only show calcs button on form screens (4.2)

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/Api/ScriptController.php, tests/Feature/Api/SearchByCategoryTest.php
Fixes [http://tickets.pm4overflow.com/tickets/728](http://tickets.pm4overflow.com/tickets/728)
Modify query to use category_assignments table to search by category instead of the category column only
Fixes to searches for :
- Processes
- Screens
- Scripts
=> ticket-728:  Category Searching (for 4.2)

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/Api/ScriptController.php, tests/Feature/Api/SearchByCategoryTest.php
Fixes [http://tickets.pm4overflow.com/tickets/728](http://tickets.pm4overflow.com/tickets/728)
Modify query to use category_assignments table to search by category instead of the category column only
Fixes to searches for :
Processes
Screens
Scripts
=>  ticket-728: Category Searching (for 4.1)

resources/js/processes/screen-builder/screen.vue
Fixes [Ticket 739](http://tickets.pm4overflow.com/tickets/739)
[4.2 PR](https://github.com/ProcessMaker/processmaker/pull/4019)
- Removes the Custom CSS button for non-form screens (Email, Display, Conversational)
=> Show Custom Css Button on Form screens

ProcessMaker/Traits/ExtendedPMQL.php, resources/js/components/AdvancedSearch.vue, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
- [FOUR-3996](https://processmaker.atlassian.net/browse/FOUR-3996) Screen building inspector chart select showing only 10 charts - should show all
- [FOUR-4036](https://processmaker.atlassian.net/browse/FOUR-4036) No results in a search changing tabs
- [FOUR-3633](https://processmaker.atlassian.net/browse/FOUR-3633) Swagger example results in 422 error
- [FOUR-4024](https://processmaker.atlassian.net/browse/FOUR-4024) Searching with PMQL input should be expected to be in the logged in user's timezone
- [FOUR-3360](https://processmaker.atlassian.net/browse/FOUR-3360) Super-Admin permission must allow user to see ALL saved searches
- [FOUR-3932](https://processmaker.atlassian.net/browse/FOUR-3932) After clearing Task saved search you cannot search by Request name
- …
=> [4.2] Ticket #727: Saved Search Issues

ProcessMaker/Traits/ExtendedPMQL.php, resources/js/components/AdvancedSearch.vue, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
- [FOUR-3996](https://processmaker.atlassian.net/browse/FOUR-3996) Screen building inspector chart select showing only 10 charts - should show all
- [FOUR-4036](https://processmaker.atlassian.net/browse/FOUR-4036) No results in a search changing tabs
- [FOUR-3633](https://processmaker.atlassian.net/browse/FOUR-3633) Swagger example results in 422 error
- [FOUR-4024](https://processmaker.atlassian.net/browse/FOUR-4024) Searching with PMQL input should be expected to be in the logged in user's timezone
- [FOUR-3360](https://processmaker.atlassian.net/browse/FOUR-3360) Super-Admin permission must allow user to see ALL saved searches
- [FOUR-3932](https://processmaker.atlassian.net/browse/FOUR-3932) After clearing Task saved search you cannot search by Request name
- …
=> [4.1] Ticket #727: Saved Search Issues

database/factories/ProcessRequestFactory.php, resources/js/components/common/mixins/datatable.js, resources/js/requests/components/RequestsListing.vue
Part of https://github.com/ProcessMaker/package-savedsearch/pull/263
- Allows json encoded rows for vuetable to preserve numeric object keys
- Removes random element from test factory to help with debugging
=> Handle json encoded rows in vuetable (4.2)

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Models/User.php, resources/js/admin/users/components/DeletedUsersListing.vue, tests/Feature/Api/UsersTest.php
Allows soft deleted users with a non-unique email to be restored without failing.
Ticket #734:
http://tickets.pm4overflow.com/tickets/734
=> [4.2] Ticket #734: Undeleting Users blocked by Unique Email requirement

ProcessMaker/Console/Commands/Install.php, README.md, resources/lang/en.json
- Added default .env variable PROCESSMAKER_SCRIPTS_DOCKER to fix installation issues related with docker path when running the command processmaker:install under macOs.
- Updated readme documentation
=> Ticket #743: Set default Docker installation path variable in .env (For 4.2)

resources/views/tasks/edit.blade.php
Fixes http://tickets.pm4overflow.com/tickets/142
Disables the select file button and drag/drop when the task is self service
Requires: https://github.com/ProcessMaker/screen-builder/pull/1057
4.1 Equivalent: https://github.com/ProcessMaker/processmaker/pull/4029
=> Disable file upload for unclaimed self service tasks (4.2)

resources/js/processes/modeler/components/inspector/ConfigEditor.vue, resources/js/processes/modeler/initialLoad.js
Fixes http://tickets.pm4overflow.com/tickets/361
- Read 'value' and emit 'input' to set pm:config on script tasks
4.2 PR: https://github.com/ProcessMaker/processmaker/pull/4039
=> Use standard operations to set node config

ProcessMaker/Managers/DataManager.php, ProcessMaker/Models/CallActivity.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Repositories/TokenRepository.php, composer.json, composer.lock, tests/Feature/Api/CallActivityTest.php, tests/Feature/Api/processes/ParentCallActivityBoundaryError.bpmn, tests/Feature/Api/processes/SubProcessWithError.bpmn
Requires: ProcessMaker/nayra#206
Fixes: FOUR-3538
- Boundary Error on a CallActivity can catch errors in tasks inside the subprocess
- Update CallActivity implementation
- Add DataManager required by the updated CallActivity implementation
- Tests of Activity (ScriptTask) exception catch by a boundary error event
=> Boundary Error on a CallActivity can catch errors in tasks inside the subprocess v4.1

ProcessMaker/Http/Controllers/ProcessController.php, resources/views/processes/edit.blade.php, resources/views/requests/show.blade.php
Ticket [676](http://tickets.pm4overflow.com/tickets/676)
- Hide the 'Summary' tab until a request is Completed or Canceled. Fig 1.
- Remove the `Request Detail Screen` select list from the process configurations Fig. 2
- Remove references to the `screenRequestDetail` 
<h2>Fig 1</h2>
<h2>Fig 2 </h2>
=> 4.1 Remove Request Detail Screen select

ProcessMaker/Http/Controllers/ProcessController.php, resources/views/processes/edit.blade.php, resources/views/requests/show.blade.php
Ticket [676](http://tickets.pm4overflow.com/tickets/676)
- Hide the 'Summary' tab until a request is Completed or Canceled. Fig 1.
- Remove the `Request Detail Screen` select list from the process configurations Fig. 2
- Remove references to the `screenRequestDetail` 
<h2>Fig 1</h2>
<h2>Fig 2 </h2>
=> Remove Request Detail Screen select

resources/views/tasks/edit.blade.php
Fixes http://tickets.pm4overflow.com/tickets/142
Disables the select file button and drag/drop when the task is self service
Requires: https://github.com/ProcessMaker/screen-builder/pull/1056
4.2 Equivalent: https://github.com/ProcessMaker/processmaker/pull/4030
=> Disable file upload for unclaimed self service tasks (4.1)

ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessVersion.php, ProcessMaker/Models/User.php, ProcessMaker/Policies/ProcessPolicy.php, ProcessMaker/Policies/ProcessRequestPolicy.php, ProcessMaker/Policies/ProcessVersionPolicy.php, ProcessMaker/Providers/AuthServiceProvider.php, ProcessMaker/Traits/ProcessTrait.php, database/factories/ProcessRequestFactory.php, database/migrations/2021_09_28_202132_add_process_version_to_processables_table.php, tests/Feature/Api/ProcessRequestsTest.php, tests/Feature/EditDataTest.php
Processes now maintain matching processables with the version of the process when the processable was created.
[Fixes ticket #666](http://tickets.pm4overflow.com/tickets/666)
=> 4.1: Permissions can be changed after a process has started (edit data, cancel)

ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessVersion.php, ProcessMaker/Models/User.php, ProcessMaker/Policies/ProcessPolicy.php, ProcessMaker/Policies/ProcessRequestPolicy.php, ProcessMaker/Policies/ProcessVersionPolicy.php, ProcessMaker/Traits/ProcessTrait.php, database/migrations/2021_09_28_202132_add_process_version_to_processables_table.php, tests/Feature/Api/ProcessRequestsTest.php, tests/Feature/EditDataTest.php
Processes now maintain matching processables with the version of the process when the processable was created.
[Fixes ticket #666](http://tickets.pm4overflow.com/tickets/666)
=> 4.2 Permissions can be changed after a process has started (edit data, cancel)

resources/js/processes/screen-builder/screen.vue
TICKET [1016](http://tickets.pm4overflow.com/tickets/1016)
The issue is caused by rendering a custom component that does not have  `renderer` set as a `ref`.  (i.e Conversational Forms)
- Check if the `refs` renderer is set.
=> Fix `Cannot read properties of undefined (reading 'countElements')` Console Error

ProcessMaker/Models/Process.php
Fixes [http://tickets.pm4overflow.com/tickets/1019](http://tickets.pm4overflow.com/tickets/1019)
The steps used to replicate the issue are:
- Create at least 2 processes (process 1, process2)
- Create 1 users (user1) 
- create 1 group (group1)
- Assign user1  to group1
- Configure the Start Event of process1 to group1
- Configure the Start Event of process2 as in the next screenshot, that is Type=group and left empty the group:
- Login as user1 and try to start a request. The process list is empty.
With the fix, the process list (when trying to start a request) returns process1.
=> ticket-1019: Group Start Permissions Not Working (for 4.1)

ProcessMaker/Models/Process.php
Fixes [http://tickets.pm4overflow.com/tickets/1019](http://tickets.pm4overflow.com/tickets/1019)
The steps used to replicate the issue are:
- Create at least 2 processes (process 1, process2)
- Create 1 users (user1) 
- create 1 group (group1)
- Assign user1  to group1
- Configure the Start Event of process1 to group1
- Configure the Start Event of process2 as in the next screenshot, that is Type=group and left empty the group:
- Login as user1 and try to start a request. The process list is empty.
With the fix, the process list (when trying to start a request) returns process1.
=> ticket-1019: Group Start Permissions Not Working (for 4.2)

ProcessMaker/Traits/ExtendedPMQL.php, tests/Feature/ExtendedPMQLTest.php
Fixes http://tickets.pm4overflow.com/tickets/1021
- Do not call set value on the expression if its an interval expression
- Fix date parsing in mysql 5 (mysql 5 does not recognize timezones in the date string)
4.1: https://github.com/ProcessMaker/processmaker/pull/4060
=> Fix relative time parsing and filtering by user timezone (4.2)

resources/js/processes/components/ProcessesListing.vue
Processes can be edited whether they're active or inactive, but previously the vue table row only displayed the edit link if the process was active instead of active or inactive.
Fixes [ticket #1074](http://tickets.pm4overflow.com/tickets/1074)
=> [4.2] Shows the edit process link for active or inactive processes

resources/views/tasks/edit.blade.php
Fixes formatting issue when package-comments is installed. Resolves [ticket #1054](http://tickets.pm4overflow.com/tickets/1054).
=> [4.2] Missing .card class added to <task> vue component

ProcessMaker/Policies/ProcessPolicy.php
Ticket: [1056](http://tickets.pm4overflow.com/tickets/1056)
- Update the Process Policy to enable start permissions for users in a group that is nested.
- Create Groups **"Group1"** and **"Group2"**
- Create User **"User2"**
- Assign **"Group2"** as a member of **"Group1"**
- Assign **"User2"** to **"Group2"**
- Create a process **"Test Process**" and configure its Start Event to be started by **"Group1"**
- Login as **"User2"**
- Try to Start **"Test Process"**
The User assigned as request starters via a group of groups should be able to start a request.
=> Fix the start permissions of a user nested in a group

ProcessMaker/Http/Controllers/Api/ChangePasswordController.php, ProcessMaker/Models/User.php, ProcessMaker/Rules/StringHasAtLeastOneUpperCaseCharacter.php, ProcessMaker/Rules/StringHasNumberOrSpecialCharacter.php, resources/views/auth/passwords/change.blade.php, tests/Feature/Api/ChangePasswordTest.php, tests/Feature/Api/UsersTest.php
User passwords are now checked when saved (through a controller). Requirements are:
- minimum 8 characters
- must contain an uppercase letter
- must contain either a special character or a number
Resolves [ticket #1032](http://tickets.pm4overflow.com/tickets/1032).
=> Add validation rules for User passwords

resources/js/processes/screen-builder/typeForm.js
Ticket [1180](http://tickets.pm4overflow.com/tickets/1180)
Registers the ` multiselect` component in the `typeForm.js` file. This fixes the multiselect in Web Entry. Web Entry does not use the global registration in `app-layout.js`
=> Fixes Multiselect in Webentry

ProcessMaker/Notifications/ImportReady.php
When an import process is aborted because of a missing package, the import screen hangs.
- Fix the issue when no process name is included in the import response
-
=> Fix missing package error not displayed on process import

ProcessMaker/Jobs/BpmnAction.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-3681
When a StartConditionalEvent has an invalid expression, it throws and exception and breaks, the evaluations of other events like the Timer StartEvents.
This Catch conditional errors to do not break to others.
=> Catch conditional errors to do not break to others

ProcessMaker/Http/Controllers/Auth/ClientController.php
Issue:
- When creating a new Auth Client, the "Enable Password Grant" checkbox is not stored correctly.
Change:
- The provider parameter was missing in the create function.
Ticket:
- http://tickets.pm4overflow.com/tickets/910
=> Bugfix Ticket 910 - Auth Clients Store (4.2)

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Listeners/BpmnSubscriber.php, ProcessMaker/Models/ProcessRequestToken.php, tests/Feature/Api/TasksTest.php, tests/Fixtures/self_serve_notifications_process.bpmn
Fixes http://tickets.pm4overflow.com/tickets/1125
To test
- Enable "Assigned" notification for any user type for a self-serve task and run the process.
- Verify in `/notifications` that a notification is generated when the self serve task is claimed
Note the bell icon counter and notification list pop over in the navbar may not update due to a separate bug
=> Wait to send activated notification until self-serve is claimed

ProcessMaker/Bpmn/MustacheOptions.php, ProcessMaker/Providers/WorkflowServiceProvider.php, ProcessMaker/Traits/MakeHttpRequests.php
- Adds support for the following filters to mustache:
- `{{{ variable | json }}}`
- `{{{ variable | xml }}}`
- `{{{ variable | serialize }}}`
- Fixes an issue where mustache was not receiving data in the body of a data connector
- https://github.com/ProcessMaker/package-data-sources/pull/205
- http://tickets.pm4overflow.com/tickets/1179
=> [v4.2] Ticket 1179: Fix JSON support in Data Connector Send

config/app.php
Requested by Enrique and part of https://processmaker.atlassian.net/browse/FOUR-4255
Adds a timeout (default 300 seconds) to system scripts. This is in case the docker engine gets overloaded and these types of requests take longer than the default 60 seconds.
Related PRs:
https://github.com/ProcessMaker/package-actions-by-email/pull/51
https://github.com/ProcessMaker/connector-pdf-print/pull/46
Note: It's also used in connector-send-email but I added that as part of the SSR issue
=> Add config for system script timeouts

resources/js/app-layout.js
Part of https://processmaker.atlassian.net/browse/FOUR-4317
When we get 401s from any api call it automatically redirects the user to the home page. Data sources can return 401s that we do not want to redirect. There was already an exception if the URL contains 'request'. This fix adds one for the 'test' endpoint.
=> Fix 401s redirecting to home page for data source tests

ProcessMaker/Http/Controllers/Api/ProcessController.php, resources/views/processes/import.blade.php
Ticket [FOUR-4464](https://processmaker.atlassian.net/browse/FOUR-4464)
https://user-images.githubusercontent.com/90727999/142059222-94f5d760-90d2-40e8-b4fc-4f41cc77cf8c.mov
=> Bugfix/FOUR-4464: Fixed datasource ID assignment on import process (FOR 4.1)

ProcessMaker/Http/Controllers/AboutController.php, composer.json, resources/views/about/index.blade.php, tests/Feature/AboutTest.php, tests/bootstrap.php
Developer's want to know the exact commit hash for a given build without having to necessarily have command line access. This will enable better debugging for builds deployed to production and other environments.
We've added a "processmaker" property to the "extra" property in composer.json. Within that, there is a "build" property which contains a string value representing the commit hash of the build. This is read by the AboutController and shown on the about page (/about) in the footer. This value will be set automatically when builds are released.
If this value isn't present, the exception will be caught and the build commit hash won't be attempted to be shown.
Check the bottom of the /about page and there should be small text under the copyright notice with the commit hash info for …
=> [4.1][Feature] Show commit hash on about page

ProcessMaker/Http/Controllers/ProcessController.php, resources/views/processes/edit.blade.php, resources/views/requests/show.blade.php
This ticket reverts a change where the Request Detail Screen select was removed along with the summary tab. This has been requested by stakeholders currently using 4.1 who have existing processes using the summary screen.
Reverts ProcessMaker/processmaker#4044
- Ensure the Request Detail Screen select is still available in the process configuration
- Ensure the screen selected as the Request Detail Screen displays in the Summary tab both during requests and after requests have completed
- ProcessMaker/processmaker#4044
- [Ticket #676](http://tickets.pm4overflow.com/tickets/676)
=> Revert "4.1 Remove Request Detail Screen select"

ProcessMaker/Http/Controllers/AboutController.php, composer.json, resources/views/about/index.blade.php, tests/Feature/AboutTest.php
Developer's want to know the exact commit hash for a given build without having to necessarily have command line access. This will enable better debugging for builds deployed to production and other environments.
We've added a "processmaker" property to the "extra" property in composer.json. Within that, there is a "build" property which contains a string value representing the commit hash of the build. This is read by the AboutController and shown on the about page (/about) in the footer. This value will be set automatically when builds are released.
If this value isn't present, the exception will be caught and the build commit hash won't be attempted to be shown.
Check the bottom of the /about page and there should be small text under the copyright notice with the commit hash info for …
=> [4.2][Feature] Show commit hash on about page

resources/views/shared/users/sidebar.blade.php
This PR removes the option **User must change password at next login** on edit profile view. Now is only available in edit user view.
- Added a condition to show or not the control depending of the URL
- First login with an admin user and go to some user edit. The toggle should be available under login information section.
- Then go to the profile and edit profile. The option should not be available.
https://user-images.githubusercontent.com/90727999/142623532-290d3fde-ee93-4ebe-ae1f-624ede5c4d98.mov
- [FOUR-4579](https://processmaker.atlassian.net/browse/FOUR-4579)
=> Bugfix/FOUR-4579: Removed force password change from profile edit

resources/lang/en.json
Ticket [FOUR-4292](https://processmaker.atlassian.net/browse/FOUR-4292)
Added lang for Webentry welcome title
When Webentry mode is Authenticated will display: **Welcome, Agustin Busso - Processmaker**
When Webentry mode is Anonymous will display: **Welcome, Anonymous User - Processmaker**
https://user-images.githubusercontent.com/90727999/142250031-92f8f30f-966c-48ef-8428-1fd659e3d4f2.mov
=> Bugfix/FOUR-4292: Incorrect page title when you initialize a request through a web entry (For 4.2)

ProcessMaker/Http/Controllers/Api/SignalController.php, tests/Feature/Api/SignalTest.php
Trying to move to another page in signals listing pagination throws an error and could not move to the page clicked. The issue was related with the returning data from controller, that was returning an object instead an array.
- Added $signals->value to get the array
https://user-images.githubusercontent.com/90727999/142414992-c4d27040-d815-426b-a4b0-a968864e2dc4.mov
Go to Designer > Signals and ensure pagination is working.
- [FOUR-4213](https://processmaker.atlassian.net/browse/FOUR-4213)
- **Related in 4.1** [FOUR-4465](https://processmaker.atlassian.net/browse/FOUR-4465)
=> Bugfix/FOUR-4465: Fixed pagination in signals (For 4.2)

ProcessMaker/SanitizeHelper.php, tests/Feature/Api/CallActivityTest.php, tests/Feature/Api/TasksTest.php, tests/Feature/Api/screens/FOUR-4408 B.json, tests/Feature/SanitizeHelperTest.php
**Format in rich text is missing when a form text area variable is passed to a second task that use that variable in a rich text control and then is passed again to another task with form text area**
Reproduction steps:
- Create a process with 3 tasks:
The first task will be a screen with a form text area and configured as rich text with the name **form_text_area_1** with submit button.
The second task will be a screen with a rich text control. Inside de control put the name of the previous form text area name in triple mustaches **{{{form_text_area_1}}}** with submit button.
The third task should be the same screen from task 1.
- Start a new request, and in the first task add text with some formats (bold, colors, ...), submit the data
In the second task you should see the data formatted, …
=> Bugfix/FOUR-4408: Textarea Rich Text sanitizing Incorrectly (For 4.2)

ProcessMaker/Helpers/SettingsHelper.php
When cache_settings is using a force=true argument and the key 'all' is not defined, the function reset resttings but don't initialize the $cache again.
Issue can be reproduced running php `artisan package-ellucian-ethos:install`
- Adding the $cache init command after the reset
Execute `artisan package-ellucian-ethos:install` without errors 
- github.com/ProcessMaker/package-ellucian-ethos [private]
=> Fixing issue with cache get all into cache_settings when force args is enabled

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Models/Setting.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, resources/js/admin/settings/components/SettingObject.vue, resources/lang/en.json, tests/Feature/Api/SettingsTest.php
Variables should not have any spaces. The issue happen when you create an extended property with an incorrect variable name in Admin > Settings > Users > Extended properties.
- Variable names should have numbers, letters and underscores. 
- Variable names should not start with a number
- Variable names should not have any space
- Added backend validation for variable names when updating an extended property.
- Added frontend validation for variable names when updating an extended property.
Try to create an incorrect variable name, and a validation error message should be displayed.
Run unit tests under tests/Feature/Api/SettingsTest
https://user-images.githubusercontent.com/90727999/143056994-1e483ece-e026-4659-85a3-be6239922e3a.mov
- …
=> Bugfix/FOUR-4404: User screen goes blank if adding a variable with spaces in Setting/Extended Properties

ProcessMaker/Http/Controllers/Api/SignalController.php, tests/Feature/Api/SignalTest.php
This new issue is related to a wrong total_pages value calculation that was returning the value two(2) when you create exactly ten(10) signals, so when trying to move to page 2 that will fail because an index violation.
- Added a new total_pages calculation for signal pagination.
Create exactly 10 signals and you should have only page number 1 in pagination.
Create 11 signals and you should have page number 1 and 2 in pagination.
Run tests under tests/Feature/Api/SignalTest
- [FOUR-4550](https://processmaker.atlassian.net/browse/FOUR-4550)
=> Bugfix/FOUR-4550: Fixed total pages values in signals pagination (For 4.2)

ProcessMaker/Http/Controllers/Api/SettingController.php
This PR fixes an issue where LDAP certificates could not be uploaded because the default storage location for them did not exist.
This PR tests to ensure that the directory does exist prior to attempting to write to it. If it does not exist, it creates it.
1. Ensure your test instance _does not_ have an `etc` directory under your storage directory
2. Go to Settings page
3. Click the LDAP tab
4. Attempt to upload a certificate
- Requires https://github.com/ProcessMaker/package-auth
=> Fix issue where settings path does not exist

ProcessMaker/Assets/ScreensInProcess.php, ProcessMaker/Assets/ScriptsInProcess.php, ProcessMaker/Managers/PMConfigGenericExportManager.php, tests/Managers/PMConfigGenericExportManagerTest.php
1. Import the [attached process](https://github.com/ProcessMaker/processmaker/files/7557742/Update.Product.Marketing.Content_v2.1.json.zip) on a 4.2.* instance.
2. See that the process import will not finish and remains "spinning".
3. Navigate back to the processes list
4. Notice there are now 3 incomplete copies of the process.
Among this codebase and various packages, when querying the BPMN XML document for a given process, it was assumed the bpmn: namespace either existed or was registered already. The attached process has a namespace of bpmn2, which caused the import to fail. The solution was to explictly register the bpmn namespace before querying the XML document.
You should be able to upload any exported process file and in particular, the one attached to this PR without any …
=> Updated to register the "bpmn" namespace for all DOMXPath instances

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Models/Setting.php
After adding an extended property it are not showing under user/edit view. There are two settings observers in package-auth and processmaker core. When one of them was triggered the other was triggered causing an infinite loop.
- Go to Admin > Settings > Users
- On Extended Properties Click on Edit  and add some extended properties
- Go to Users and go to edit some user
- The extended properties you added are not visible
- Added on the ->save method for setting in the observer of package-auth **withoutEvents** to avoid the infinite loop.
https://user-images.githubusercontent.com/90727999/143292473-63b62af2-8a88-4b98-bae7-00c41dc27c0f.mov
- Go to Admin > Settings > Users
- On Extended Properties Click on Edit and add some extended properties
- Go to Users and then go to …
=> Bugfix/FOUR-4179: When adding extended properties they are saved but not showing on Users/Edit section (For 4.2)

ProcessMaker/Providers/ProcessMakerServiceProvider.php, resources/js/admin/settings/components/SettingObject.vue, tests/Feature/Api/SettingsTest.php
Variables should not have any hyphen. The issue happen when you create an extended property with an incorrect variable name in Admin > Settings > Users > Extended properties.
- Variable names should have numbers, letters and underscores. 
- Variable names should not start with a number
- Variable names should not have any space
- Variable names should not have any hyphen
- Added validation for variable names to not allow hyphen when updating or adding an extended property.
Try to create an incorrect variable name, and a validation error message should be displayed.
- [FOUR-4404](https://processmaker.atlassian.net/browse/FOUR-4404)
- Packages for manually testing, package-advanced-user-manager and package-auth
=> Bugfix/FOUR-4404_b: Removed hyphen for valid variables name in extended properties

ProcessMaker/Http/Controllers/Api/TaskController.php, resources/lang/en.json, tests/Feature/Api/TasksTest.php
When trying to add a PMQL with an unknown column name, the exception message is showing as internal server error 500. Go to tasks and in advance search mode add a PMQL with an unknown column eg: (my_unknown_column = "Test"). Press search, you will see an internal server error 500.
- Added exception message for unknown column names.
- Go to tasks and in advance search mode add a PMQL with an unknown column eg: (my_unknown_column = "Test").
- Press search, you will see an informative error message **PMQL Is Invalid. Column not found: "my_unknown_column".**
https://user-images.githubusercontent.com/90727999/144459963-a7ee3aab-827f-4b5f-8480-388bae70ca24.mov
- [FOUR-4792](https://processmaker.atlassian.net/browse/FOUR-4792)
- [Saved Search …
=> Bugfix/FOUR-4792: Test cases for display exception for invalid columns in PMQL saved searches

ProcessMaker/Http/Controllers/Api/SecurityLogController.php, database/factories/SecurityLogFactory.php, tests/Feature/Api/PerformanceModelsTest.php, tests/Feature/Api/SecurityLogsTest.php
User Security Logs search returning results from other users.
1. Under a users profile, navigate to the **'Security Logs'** tab
2. Take note of the number of _Logged Events_ in the pagination. 
3. Search by browser **`chrome`** or platform **`windows`**
4. Take note of the number of _Logged Events_ in the pagination.
- The `pmql()` scope was moved to the end.
Please do a search query by "OS Name" (windows) or "Browser name" (chrome, firefox). Make sure you get results exclusively from the logged in user.
- [Ticket 1034](http://tickets.pm4overflow.com/tickets/1034)
- [FOUR-4809](https://processmaker.atlassian.net/browse/FOUR-4809)
=> Bugfix Ticket 1034 for 4.2 - User Security Logs search returning wonky results

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Traits/HideSystemResources.php, resources/js/tasks/components/TasksList.vue, tests/Feature/Api/TasksTest.php
System tasks were being shown to users.
Reproduction Steps:
1. Install DocuSign package.
2. Create an application in DocuSign that has not been granted Access.
3. Go the next page.
4. Do not click "Authorize Access". Then go to `/tasks` and you should see the next records:
- The `HideSystemResources` trait was used to exclude system-type records from the `process_request_tokens` table.
Please follow the "Reproduction Steps" of above. You should not see system tasks.
Run `vendor/bin/phpunit --filter testGetListNonSystemTasks tests/Feature/Api/TasksTest.php`
- [Ticket 1175](http://tickets.pm4overflow.com/tickets/1175)
- [FOUR-4808](https://processmaker.atlassian.net/browse/FOUR-4808)
=> Bugfix Ticket 1175 - Added system tasks filter

ProcessMaker/Http/Controllers/Auth/LoginController.php, resources/views/auth/passwords/change.blade.php
If a user is forced to change their password via "force password change" toggle, then upon the next login the user is taken to the Requests route instead of their assigned dashboard.
1. Install package-dynamic-ui. 
2. Create a dashboard, assign to a user.
3. Check off "User must change password at next login"
4. After changing the password, user will be redirected to Requests
- Removed the redirect to `/requests` and instead it will be redirected to `/`. In `/`, the redirect is carried out properly to the custom dashboard or requests.
Follow the reproduction steps above.
- [FOUR-4826](https://processmaker.atlassian.net/browse/FOUR-4826)
=> FOUR-4826 Post Password Change Redirecting Incorrectly

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Models/Setting.php, tests/Feature/Api/CssOverrideTest.php
Invalid data error shows when clicking reset button in customize-ui because trying to validate config.* with valid_variable rule.
- Added conditional to only validate the rule config.* for extended properties (user.properties).
- Got o Admin > Customize UI
- Click Reset button. UI settings should save.
Run test **tests/Feature/Api/CssOverrideTest.php**
https://user-images.githubusercontent.com/90727999/144868607-e4cf049d-3c0d-4516-aa74-7358e89c677a.mov
- [FOUR-4812](https://processmaker.atlassian.net/browse/FOUR-4812)
=> Bugfix/FOUR-4812: Error "The given data was invalid." when we try reset configuration in dynamic UI

resources/js/processes/components/ProcessesListing.vue
When you go to Design > Processes you can see at first the loading message, but when you do some search, the message is not appearing.
- Show message before fetch processes on search api request.
- Go to Designer > Processes and see the loading message.
- Filter by something in the processes search bar and the loading message should appear while the request is active and hides when the request finish.
https://user-images.githubusercontent.com/90727999/144898486-4695cfa2-0d68-4850-bb84-85fd8c5fe8af.mov
- [FOUR-4793](https://processmaker.atlassian.net/browse/FOUR-4793)
=> Bugfix/FOUR-4793: "Loading.." It only appears when you refresh the screen in the process searcher

resources/js/processes/scripts/customFilters.js
Ticket [FOUR-4822](https://processmaker.atlassian.net/browse/FOUR-4822)
Broken API Documentation links in the script editor for:
- JavaScript/Node
- LUA
- Java
- Python
- Update the links to the proper documentation
Create a script in the above languages and open the API Documentation link in the commented text.
=> Fix Multiple broken SDK doc links in script editor

resources/views/shared/users/profile.blade.php, tests/Feature/Admin/UserTest.php
Go to user profile and you can see additional info at bottom.
- Not show additional info in user profile.
- Go to user profile and you **will not** see additional info at bottom.
- Go to edit some user and you **will** see additional info at bottom.
Run tests
tests/Feature/Admin/UserTest.php
https://user-images.githubusercontent.com/90727999/144668215-baa26767-bd22-4fdb-ac14-e33edaf9ff82.mov
- [FOUR-4828](https://processmaker.atlassian.net/browse/FOUR-4828)
=> Bugfix/FOUR-4828: Removed additional info from user profile

ProcessMaker/Traits/ExtendedPMQL.php
When using a PMQL query like `(data.form_date_picker_1 ="2021-12-31")` to search a record of a collection, it does not work.
1. Log in
2. Import collection [attached](https://processmaker.atlassian.net/browse/FOUR-4789) 
3. Open the collection
4. Fill following query (data.form_date_picker_1 = "2021-12-31")
- The `parseValue` function for dates in `ProcessMaker/Traits/ExtendedPMQL.php` always returned a "date with timestamp", so `2021-12-31 14:00` is different than `2021-12-31` and no records are found.
Please follow the reproduction steps of above to manually tests the search functionality by PMQL date in `/collections/{id}`.
You can also run `vendor/bin/phpunit tests/Feature/ExtendedPMQLTest.php`.
- [FOUR-4789](https://processmaker.atlassian.net/browse/FOUR-4789)
- [Package …
=> Bugfix FOUR-4789 - Searches for the date or date time in a collection are not working

ProcessMaker/Assets/ScreensInProcess.php, ProcessMaker/Assets/ScriptsInProcess.php, ProcessMaker/Jobs/ImportProcess.php
When attempting to import a process from a file, the import failed and the user was left with the "spinning" import screen without any update and with the process imported three times. This happened because the ImportProcess job ran three times and even though it imported the process, it was failing when attempting to import assets referenced in the BPMN which didn't exist in the import file data itself.
To reproduce the issue:
1. Import the [attached processes](https://github.com/ProcessMaker/processmaker/files/7645849/process-imports.zip) on a 4.2.* instance.
2. See that the process import will not finish and remains "spinning".
3. Navigate back to the processes list
4. Notice there are now 3 incomplete copies of each process after attempting to the import.
The ImportProcess job will …
=> [4.2] Multiple copies of the process are created and import doesn't finish

ProcessMaker/Http/Controllers/ProcessController.php, resources/views/processes/edit.blade.php, resources/views/requests/show.blade.php, tests/Feature/RequestTest.php
Removed functionality to allows show end event custom detail screen and select custom detail screen for a request. Now it is posible to see the custom screen if we configure it in the end event of a process or within the Request Detail Screen select in process configuration.
- Reverted changes from [PR 4043](https://github.com/ProcessMaker/processmaker/pull/4043) and changed the conditionals to show or not each summary screen.
- If no custom summary screen is configure will show the default summary
- If summary screen is configure in process > configure > Request Detail Screen select, will show the custom summary configured there.
- If summary screen is configured in the end event of a process will show the custom summary screen for the end event
- If summary screen is configure in …
=> Task/FOUR-4565 Ticket-1234: Show custom summary screen for end event and Request Detail Screen select 

ProcessMaker/Traits/MakeHttpRequests.php
Ticket: [FOUR-4876](https://processmaker.atlassian.net/browse/FOUR-4876)
When using mustache variables in a data connector's body and using the Test Request JSON to fill in that data the response body is returning `null` values. This is due to passing in an empty `data` variable when rendering mustache. The `data` variable does not contain the `requestData` needed to render properly.
1. Configure a new data resource using the POST method
2. In body use mustache variables
3. In the Response Body tab configure the Test Request JSON to populate the mustache variables
4. Select the 'Send' button
**Behavior**
The response values are null. The response should contain the values set in the Test Request JSON. 
- Fix the rendering of Mustache variables by passing in the `requestData` variable that …
=> Fix mustache variables not rendering Test Request JSON

ProcessMaker/Helper/helper.php, resources/lang/en.json
When you hover on a tasks on sidebar menu item, translation is not working
- Got to Admin and select a user to edit. 
- Change the language under settings section.
- Got to Tasks
- Hover on menu item, title is not translated
- Added __() to $menu->title.
- Got to Admin and select a user to edit. 
- Change the language under settings section.
- Got to Tasks
- Hover on menu item, title should be translated based on the language selected for the user
**IMPORTANT!**
**Self service title for German is missing**
https://user-images.githubusercontent.com/90727999/145821108-615a9835-c333-4157-8c87-dbf0df1a067d.mov
- [FOUR-4886](https://processmaker.atlassian.net/browse/FOUR-4886)
- You should install [package-translations](https://github.com/ProcessMaker/package-translations)
=> Bugfix/FOUR-4886: Translations in Tasks menu are not fully translated

resources/views/admin/groups/edit.blade.php
Can't add to a group two users with the same first and last name.
- Create two users with same first and last name, but different username
- Create a group
- Try to add those users that have the same fullname to the group.
- Changed **track by** option  to track by username instead fullname.
- Changed label of selected users to improve UX to display **fullname (username)**
- Create two users with same first and last name, but different username
- Create a group
- Add those users that have the same fullname to the group.
https://user-images.githubusercontent.com/90727999/146048167-e3c76a3b-f685-4dfb-bc54-a77a6036e751.mov
- [FOUR-4110](https://processmaker.atlassian.net/browse/FOUR-4110)
=> Bugfix/FOUR-4110: It is not possible to assign different users but with the same firstname to a group

resources/views/tasks/edit.blade.php
1. Import the [attached process](https://processmaker.atlassian.net/browse/FOUR-4881)
2. Configure the data connector to any simple GET endpoint
3. Create a request and submit the first task (loop1)
Note: The error also happens with any Simple Task. Right after submitting the task.
- Fix `error.response is undefined` console log error using JS optional chaining.
Please follow the reproduction steps from above in order to test the solution.
- [FOUR 4837](https://processmaker.atlassian.net/browse/FOUR-4881)
=> Bugfix FOUR-4837 "Console error printed in FireFox after running a data connector"

ProcessMaker/Traits/ExtendedPMQL.php, tests/Feature/ExtendedPMQLTest.php
Ticket: [FOUR-4910](https://processmaker.atlassian.net/browse/FOUR-4910)
When doing a PMQL query we are passing the value in a try-catch block to see if the value is a parsable date if not then we return the original string. Values with numbers such as `W0584` are being detected as a parsable date, which is causing this error. 
- Standardize a date format in the PMQL query based on the [PMQL Date Comparison documentation ](https://github.com/ProcessMaker/pmql/blob/master/README.md#date-comparison) and check if the value is in this date format before parsing. 
This does change how users would query for dates. Users now need to properly format the date in the query `yyyy-mm-dd` example query `Started > "1990-01-01"`
1. Create a user that includes numbers in the username (i.e W0584 or …
=> 4.2 Fix Filtering request by User when username contains numbers 

ProcessMaker/Traits/ExtendedPMQL.php, tests/Feature/ExtendedPMQLTest.php
Ticket: [FOUR-4909](https://processmaker.atlassian.net/browse/FOUR-4904)
When doing a PMQL query we are passing the value in a try-catch block to see if the value is a parsable date if not then we return the original string. Values with numbers such as `W0584` are being detected as a parsable date, which is causing this error. 
- Standardize a date format in the PMQL query based on the [PMQL Date Comparison documentation ](https://github.com/ProcessMaker/pmql/blob/master/README.md#date-comparison) and check if the value is in this date format before parsing. 
This does change how users would query for dates. Users now need to properly format the date in the query `yyyy-mm-dd` example query `Started > "1990-01-01"`
1. Create a user that includes numbers in the username (i.e W0584 or …
=> 4.1 Fix Filtering request by User when username contains numbers

ProcessMaker/Http/Controllers/Auth/LoginController.php
Ticket [FOUR-4912](https://processmaker.atlassian.net/browse/FOUR-4912)
A user logging into ProcessMaker via SSO is not redirected to their original intended URL `/tasks/{task_id}/edit`  They are instead redirected to the `/requests` page.  
- When being redirected to the login page create a `processmaker_intended` cookie for the intended URL. This cookie is then read by the Auth package when being redirected via the `acs` callback 
1. Ensure you have the Auth & Dynamic UI packages installed
2. Create a process and assign an SSO user to a task.
3. Run the process and COPY the task URL assigned to the SSO user
4. In incognito mode paste the task URL in the browser
5. When redirected to the login page, Login via SSO as the assigned user
You are redirected to the …
=> Fix SSO users not redirecting to intended URL after login

ProcessMaker/Http/Controllers/Api/ProcessController.php, database/processes/templates/StartConditionalEvent.bpmn, database/processes/templates/StartMessageEvent.bpmn, database/processes/templates/StartSignalEvent.bpmn, database/processes/templates/StartSingleEvent.bpmn, database/processes/templates/StartTimerEvent.bpmn, resources/js/components/requests/modal.vue, tests/Feature/Api/ProcessTest.php
The badge counts and process number in the pagination are incorrect in the New Request modal, because from backend comes all the process that have start events of type Message, Signal, Conditional, and are filtering in the frontend in the moment to list them but is not calculating the correct number of processes for each category (because are counting all the processes, the visibles and hidden)
- Create a process with a simple start event and assign it for example to "myCategory"
- Create a process with a conditional start event and assign it to the same category
- Create a process with a message start event and assign it to the same category
- Create a process with a signal start event and assign it to the same category
- Create a process with a timer start event and assign it to the …
=> Bugfix/FOUR-4837: Start Request modal counts are incorrect

ProcessMaker/Http/Controllers/Api/TaskController.php
Ticket: [FOUR-4914](https://processmaker.atlassian.net/browse/FOUR-4914)
A user assigned to a self-service task via reassignment can not claim/complete the task.
Reproduce:
1. Have a task with the Self Service assignment configured to a Group with multiple users.
2. Enable Allow Reassignment on the task
3. As an admin run the process and reassign the task to a user in the Group.
4. log in as the user assigned and open the task.
5. Try to claim the task
**Behavior**
Although the user is already assigned they have to select the claim task button however this button is not working and does not clear the page.
- If a user is already assigned to a self-service task before they claim it, set the task boolean `is_self_service` to false allowing the `Claim Task` button to be cleared from the …
=> Allow reassigning of a self service task before the task is claimed. 

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/Process.php
-     Create a process
-     Add Start Event -> Data Connector -> End Event
-     Configure the data connector
-     Saved the changes
-     Enable auto validate
The error appears in auto validate "Call Activity must have a child process and a start event selected." as data connector was a sub-process
Modeler will get all active process (system and not system) so it can search within system process list to validate if the process used by the callActivity exists. Our packages use system sub-processes for actions by email, data connectors, etc.
Use the following branch of modeler https://github.com/ProcessMaker/modeler/tree/bugfix/FOUR-4331
npm link to modeler the following branch of bpmnlint: https://github.com/ProcessMaker/bpmnlint-plugin/tree/bugfix/FOUR-4331
build modeler
use the built …
=>   FOUR-4331: Error in auto-validate with Data connector

package-lock.json, package.json
Incompatible jointjs versions in modeler and core.
- Remove jointjs version from core, leaving modeler to resolve it.
Rebuild modeler and test.
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-4933)
=> Remove jointjs version from core, leaving modeler to resolve it

ProcessMaker/Listeners/CommentsSubscriber.php, resources/js/components/Timeline.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-4917](https://processmaker.atlassian.net/browse/FOUR-4917)
- Listen to gateway transitions instead of activity activate
- Order comments by id instead of created_at 
- Use the next Nayra branch: **bugfix/FOUR-4923** 
- Upload the following process:
[FOUR4923.zip](https://github.com/ProcessMaker/processmaker/files/7757373/FOUR4923.zip)
- Start a request and in the first screen,  select false for the field "End Loop?"
- Advance the request until the 2 gateways are traversed
- Go to the request (url requests/{request_id}) and look at the request's history. Flows transitions from the gateways should look like this:
Before the fix, no gateway transitions were registered:
[https://processmaker.atlassian.net/browse/FOUR-4923](https://processma …
=> FOUR-4917: Wokflow is followed according to the nodes (or sequence of design) and not as expected for users

public/definitions/Semantic.xsd
1. Log in 
2. Import a process with action by email from a previous version
3. open the process
4. click on the Action By Email task
5. edit the data, for example edit the options
6. save the process
7. click on the AbE task
- The schema for Tasks was updated and now the warning "calledElement attribute is not allowed" is gone.
1. Import the attached process
2. Click on Action by Email Task
3. Edit data, for example edit the options
4. Save the process
5. Toggle "Auto Validate" Switch.
The BPMN should be VALID.
- [FOUR 4920](https://processmaker.atlassian.net/browse/FOUR-4920)
=> Bugfix FOUR 4920 - Error in the BMPN when edit a task of the type action by email

ProcessMaker/Listeners/CommentsSubscriber.php, resources/js/components/Timeline.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-4923](https://processmaker.atlassian.net/browse/FOUR-4923)
- Listen to gateway transitions instead of activity activate
- Order comments by id instead of created_at 
- Use the next Nayra branch: **bugfix/FOUR-4923** 
- Upload the following process:
[FOUR4923.zip](https://github.com/ProcessMaker/processmaker/files/7757373/FOUR4923.zip)
- Start a request and in the first screen,  select false for the field "End Loop?"
- Advance the request until the 2 gateways are traversed
- Go to the request (url requests/{request_id}) and look at the request's history. Flows transitions from the gateways should look like this:
Before the fix, no gateway transitions were registered:
[https://processmaker.atlassian.net/browse/FOUR-4923](https://processma …
=> FOUR-4923: Wokflow is followed according to the nodes (or sequence of design) and not as expected for users

resources/js/admin/users/components/AddUserModal.vue, resources/js/admin/users/components/DeletedUsersListing.vue, tests/Feature/Api/UsersTest.php
It does not allow to reactivate the recently deleted user, a 500 error is displayed.
1. Go to Admin > users
2. Delete some user
3. Click on "+ user"
4. Try to create another user with the same "username" from which it was removed
5. Enter a WRONG email address
6. Click on "save"
7. In the window that shows the reactivation of the user, click on "yes"
- The query param `username` was added. In this way, if the email does not exist, the user is found by his username.
- Searching for the user by his `username` is more convenient, since the email field is not unique.
Please follow the Reproduction Steps of above.
Clicking "yes" should reactivate the deleted user normally
- [FOUR-4965](https://processmaker.atlassian.net/browse/FOUR-4965)
=> Bugfix FOUR 4965 - The user reactivation window does not work

resources/js/admin/users/components/DeletedUsersListing.vue, resources/js/admin/users/components/UsersListing.vue
- Delete more than 10 users
- Deleted users tab. 
- Go to page 2 in navigation 
- Search for some user
- You will see empty list
- Reset current page to 1 when filtering users
- Delete more than 10 users
- Deleted users tab. 
- Go to page 2 in navigation 
- Search for some user
- You will see the users filtered
https://user-images.githubusercontent.com/90727999/148094612-d404d6ad-f149-42dc-a1fb-567d90473e23.mov
- [FOUR-4971](https://processmaker.atlassian.net/browse/FOUR-4971)
=> Bugfix/FOUR-4971: Search box for Deleted Users is not working (For 4.1)

resources/js/admin/users/components/DeletedUsersListing.vue, resources/js/admin/users/components/UsersListing.vue
- Delete more than 10 users
- Deleted users tab. 
- Go to page 2 in navigation 
- Search for some user
- You will see empty list
- Reset current page to 1 when filtering users
- Delete more than 10 users
- Deleted users tab. 
- Go to page 2 in navigation 
- Search for some user
- You will see the users filtered
https://user-images.githubusercontent.com/90727999/148099014-594c3889-9644-4b54-bf3a-80e11ce938f3.mov
- [FOUR-4971](https://processmaker.atlassian.net/browse/FOUR-4971)
=> Bugfix/FOUR-4971: Search box for Deleted Users is not working (For 4.2)

ProcessMaker/Jobs/ImportProcess.php
After importing a process, the name of the screen does not change when having a screen with the same name.
- verify exists new name generated.
- import the process several times and check the names of the generated screens
- [FOUR-5081](https://processmaker.atlassian.net/browse/FOUR-5081)
=> [4.2] When importing a process, screens do not change number

ProcessMaker/Http/Controllers/Api/ProcessController.php
The process is not shown when clicking and searching in the pop up window after clicking request.
1. Import the process `Verify Event Based Gateway Conditional and Message Event (1).json`
2. Set up the configuration
3. Run a request
- Allow to start a Request, if the process has at least one "Start Event".
- Please follow the reproduction steps of above
- You can also run `phpunit tests/Feature/Api/ProcessTest.php`
- [FOUR-5089](https://processmaker.atlassian.net/browse/FOUR-5089)
- [FOUR-5090](https://processmaker.atlassian.net/browse/FOUR-5090)
=> Bugfix FOUR-5089 - Allow start request with both signal start event and start event

resources/js/components/AvatarImage.vue
Console errors are displayed when the user who created the saved search has been deleted.
1. Generate a saved search
2. Delete the user whom created that saved search
3. Go to `/requests/saved-searches` and you will see errors in console
- The error is caught when there is no user in the `AvatarImage.vue` component.
1. Generate a saved search.
2. Delete the user whom created that saved search.
3. Go to `/requests/saved-searches` and you won't see errors in console.
- [FOUR-5061](https://processmaker.atlassian.net/browse/FOUR-5061)
=> Bugfix FOUR-5061 (4.1) - Console errors in Saved-Search listing when created_by is null

resources/js/components/AvatarImage.vue
Console errors are displayed when the user who created the saved search has been deleted.
1. Generate a saved search
2. Delete the user whom created that saved search
3. Go to `/requests/saved-searches` and you will see errors in console
- The error is caught when there is no user in the `AvatarImage.vue` component.
1. Generate a saved search.
2. Delete the user whom created that saved search.
3. Go to `/requests/saved-searches` and you won't see errors in console.
- [FOUR-5061](https://processmaker.atlassian.net/browse/FOUR-5061)
=> Bugfix FOUR-5061 (4.2) - Console errors in Saved-Search listing when created_by is null 

ProcessMaker/Bpmn/Process.php
In `release.testing.processmaker.net` server was using an "old" process "Regression 4.2.24 Start Event". This process generated a "MySQL 22001 Right truncation data exception" error when trying to update the `global_variables` table.
For this reason, no new Requests were generated from the Conditional Start Event.
1. Design a process conditional start event -> manual or subprocess -> end event. Or [import the attached](https://processmaker.atlassian.net/browse/FOUR-4843) processes. 
2. Set up process condition `date('d')%2==0)` or `date('d')%2==1)` .
3. Run on Tinker:
```php
for ($i=0; $i<1500; $i++) { \Artisan::call('bpmn:timer'); }
```
In that way you will get the MySQL error.
- Remove the cache key at the moment the MySQL error is generated. So it can continue working after.
1. …
=> Bugfix FOUR-4843 - Conditional Start Event does not work with manual and subprocess

resources/views/tasks/edit.blade.php
- create a screen with a field with text type validation.
- create a vocabulary with an integer validation field.
- add everything to a process.
- run the process, no error messages are displayed.
Expected behavior: display errors of form
- add messages in form
- add message error type field
https://user-images.githubusercontent.com/1747025/148108471-6fdb1080-d5a7-4b1e-bb1e-0f8da22f41fc.mp4
=> [4.1] Add display error in form

resources/js/requests/components/screenDetail.vue
Can't see all the records within a record list when a request is completed.
1. Create a screen with only a record list control
2. Add one column named ID to the record list
3. Create a new page in order to add values to the record list
4. add a line input with ID as the variable
5. in the first page check the Editable option and choose the new page in the record form field
6. create a process with one task and add the screen to this task.
7. start a new request
8. add more than 5 rows to the records list.
9. submit the screen, it will be set as completed.
10. try to check the second page in the record list, is not possible.
- The component had a CSS rule that prevented pagination from working properly.
Please follow the reproduction steps of above in order to test the solution. You should …
=> Bugfix FOUR 5119 - Enable pagination in Forms tab when a request is complete

ProcessMaker/Traits/MakeHttpRequests.php
Data connector task does not save the information the outbound configuration.
1. Create a collection
2. Add end-point  with method post and configure body parameters
3. Create a process with Data-connectors
4. Configure parameter of body in data-connector in the task
Note: Do not use the same variable names, use different like:
| Parameter | Value |
| ------------- | ------------- |
| doctorName  | {{form_input_1}}  |
| doctorID  | {{form_input_2}}  |
and in the DataSource POST body, something like:
```
{
"data": {
"id": "{{doctorID}}",
"name": "{{doctorName}}"
}
}
```
- Merge request data and params values.
Run a process with data source.
- https://processmaker.atlassian.net/browse/FOUR-4333 (for 4.2)
=> [4.2] Fix missing data evaluating Data connector

ProcessMaker/Traits/MakeHttpRequests.php
Data connector task does not save the information the outbound configuration.
1. Create a collection
2. Add end-point  with method post and configure body parameters
3. Create a process with Data-connectors
4. Configure parameter of body in data-connector in the task
Note: Do not use the same variable names, use different like:
| Parameter | Value |
| ------------- | ------------- |
| doctorName  | {{form_input_1}}  |
| doctorID  | {{form_input_2}}  |
and in the DataSource POST body, something like:
```
{
"data": {
"id": "{{doctorID}}",
"name": "{{doctorName}}"
}
}
```
- Merge request data and params values.
Run a process with data source.
- https://processmaker.atlassian.net/browse/FOUR-4333 (for 4.2)
=> [4.1] Fix missing data evaluating Data connector

resources/views/tasks/edit.blade.php
It was reported as a bug that subprocess inside a main process are not showing the summary screen in the subprocess, but that is not the correct behavior. It was fixed the issue related with the interstitial screen getting stuck and not getting
the next task.
- Steps to Reproduce:
- Create a process with the next configuration
- Start Event -> Task -> Sub Process -> End Event
- Create a sub process 
- Add Start Event -> Task(Assign Screen Interstitial) -> End Event (Assign Summary Screen)
- Create a request 
- Route to the sub process
- Open the sub process
- Complete the task
- Modified the flow to follow the next rules (For more clarify please watch the videos for the different scenarios):
1. Summary screen in a subprocess will show only if the process is running as standalone.
2. If a …
=> Bugfix/FOUR-5159: Summary screen is not displayed in sub process 

ProcessMaker/Models/ProcessRequest.php
When there are 1000+ requests and in every one of the the "data" json field contains a very large attribute, the endpoint requests returns a 500 error. This is noticeable when accessing the site remotely. In local dev. environments the problem is not as critical as in the remote access.  Saved search uses the controller of this endpoint (/requests)
- To avoid that Laravel parses the larga data column of tokens and requests, the queries used to filter by request starter and participant were modified to get just ids.
Verify that the list requests (endpoint /requests) behavior has not changed. 
[https://processmaker.atlassian.net/browse/FOUR-5118](https://processmaker.atlassian.net/browse/FOUR-5118)
=> FOUR-5118: Issue - Save search - CreditAccess dev server

package.json, webpack.mix.js
JointJS version is different to the Modelers JoinJS version.
1. See the process below
2. Connect a DataObject or DataStore to a Task
3. An validation error is thrown
**Expected behavior:** 
Throw validation errors.
**Actual behavior:** 
No validation errors should be catch when a DataObject/DataStore is connected to a Task.
- Fix validation rules: ID is not required for input output specification nodes (Requires: https://github.com/ProcessMaker/bpmnlint-plugin/pull/20)
- JointJS version should be solved by Modeler
Create a process like this:
- https://processmaker.atlassian.net/browse/FOUR-5102
- https://github.com/ProcessMaker/bpmnlint-plugin/pull/20
- https://github.com/ProcessMaker/modeler/pull/1425
=> JointJS version should be resolved by Modeler

ProcessMaker/Traits/MakeHttpRequests.php
201 response not consumed by Data Connectors.
- Parse content if exists for status > 200 and <300
1. Create a DS
2. Call to a random endpoint that returns a response but with status 201
3. The response should by parsed
- [201 response not consumed by Data Connectors](https://processmaker.atlassian.net/browse/FOUR-5298)
- Requires: https://github.com/ProcessMaker/package-data-sources/pull/217
=> Fix datasource response

ProcessMaker/Models/Process.php
The next error is generated when we query the `getProcesses()` endpoint in Scripts:
```
(Code: 0) Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335 Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335
```
- The comment annotations for ProcessStartEvents in the `Process.php` file were malformed.
0. Testing in `bugfix/FOUR-5377-4.2` you should go to `admin/script-executors` and click on "PHP Executor -> Rebuild and Save"
1. Create a new PHP script
2. Add the following code and run:
```
$apiInstance = $api->processes();
$result = $apiInstance->getProcesses();
return ['processes' => $result];
```
You should see no errors.
- [FOUR-5377](https://processmaker.atlassian.net/browse/FOUR-5377)
=> Bugfix FOUR-5377 - Script error using getProcesses API endpoint

ProcessMaker/Contracts/ServiceTaskImplementationInterface.php, ProcessMaker/Facades/WorkflowManager.php, ProcessMaker/Jobs/RunServiceTask.php, ProcessMaker/Managers/WorkflowManager.php
Currently the DataSource is running an unnecessary extra Docker instance to call the configured endpoints.
- Improve the ServiceTask - DataSource implementation to reduce the resources required to perform the endpoint call.
Create a process that use lots of DataSources.
Check the performace should increase.
- https://processmaker.atlassian.net/browse/FOUR-5344
- https://github.com/ProcessMaker/package-data-sources/pull/218
=> Tune DataSource Performance

ProcessMaker/Listeners/CommentsSubscriber.php
- Create a process with 2 tasks
- Configure the 2nd task to escalate to manager
- The process will fail and the manager will not be assigned
The problem was caused when trying to register comments in auto generated requests, because they are strings and not integers.
Verify that the escalate to manager manager works.
- [https://processmaker.atlassian.net/browse/FOUR-5269](https://processmaker.atlassian.net/browse/FOUR-5269)
=> FOUR-5269: Escalate to manager does not work

resources/js/processes/modeler/components/inspector/ConfigEditor.vue
When adding a Script Task in Modeler an error appears in the console.
1. Open/create a process
2. Open the browser dev tools, console page
3. Add a task to the modeler
4. Change the task to Script Task
- The vue-monaco component requires a prop "value" as a string. Currently it was passed undefined.
- The solution is, to make sure "value" prop is set to a string.
Please follow the Reproduction Steps of above. You should not see any console errors.
- [FOUR-5585](https://processmaker.atlassian.net/browse/FOUR-5585)
=> FOUR-5585 - Console error when adding Script Task

ProcessMaker/Http/Controllers/Api/SignalController.php, ProcessMaker/Managers/SignalManager.php, resources/js/processes/signals/components/SignalListing.vue, resources/lang/en.json, tests/Feature/Api/SignalTest.php, tests/Feature/Api/processes/SignalSimple.bpmn
Signals that are present in processes or in system processes should not be deleted.
- Have an instance with PM 4.2.x
- Go to Designer, Signals
- Find the signals that belong to the package-advanced-user-manager package, see the image attached
- Delete those signals
- Try a request with any existing process, you will the error attached: Element "sync_assignment" was not found
- In the **index** method in signals controller, changed the parameter **includeSystemProcesses** to true to retrieve signals with system processes, to disable the delete button in frontend.
- In the **destroy** method in signals controller, check if signals are present in some process or system process and abort the deleting operation.
**Case 1**
- Go to designer / signals and create a signal
- After create the …
=> Bugfix/FOUR-5538: [27478] System Signals able to be deleted, edited, cause processes to not work

ProcessMaker/Models/Process.php, storage/api-docs/api-docs.json
The following error is generated when we query the getProcesses() endpoint in Scripts:
`(Code: 0) Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335 Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335`
- Change response field self_service_tasks of array to object
1. Create process with assigment self-service
2. Create a new PHP script
3. the scrAdd the following code and run:
`$apiInstance = $api->processes();
$result = $apiInstance->getProcesses();
return ['processes' => $result];`
[FOUR-5377](https://processmaker.atlassian.net/browse/FOUR-5377)
=> Script error using getProcesses API endpoint

ProcessMaker/Http/Controllers/Auth/LoginController.php, tests/Feature/AuthTest.php
- Log in 
- Create a process 
- Configure start event  with  web entry Authenticated
- Copy URL
- Open new  browser (incognito)
- Paste URL
- Login  
After login in web entry is redirecting to requests instead to the webentry task
- Retrieve the correct redirect URL from cookie **processmaker_intended**.
Same as steps to reproduce. After login in web entry should redirect the webentry task.
https://user-images.githubusercontent.com/90727999/158172578-26045b0b-021c-4c5e-8a4c-ce0d991b3e07.mov
- [FOUR-5313](https://processmaker.atlassian.net/browse/FOUR-5313)
=> Bugfix/FOUR-5313: The URL does not show the request with authenticated web entry

ProcessMaker/Models/ProcessRequest.php
- Have many requests with large data (data > 300KB and number of requests > 1000). 
- Create a saved search based on the requests list.
An error 500 is displayed when going to the created saved search
Modified the Laravel query that retrieves the requests list to avoid parsing the "data" column of a request. This implies modifying code in PM 4 core. This improvement is available currently in 4.28 only.
- Have many requests with large data (data > 300KB and number of requests > 1000). 
- Create a saved search based on the requests list.
Verify that the saved search returns the expected result.
https://processmaker.atlassian.net/browse/FOUR-5693
QA Notes: The ticket is similar to this one  already merged in 4.2
https://processmaker.atlassian.net/browse/FOUR-5118
=> FOUR-5693: Remove requests with a big data on the creditaccess DEV server

resources/js/admin/users/components/AddUserModal.vue
- Go to Admin tab > Users
- Delete a user
- Click on "+ Add User"
- Try to create a new user with the username of the user you just deleted
- Click on Save
It only shows an error message "The Username has already been taken".
A modal should appear asking: Would you like to save and reactivate their account?
- Search for the correct string for error message to know if deleted user exist to show reactivate user modal
- Go to Admin tab > Users
- Delete a user
- Click on "+ Add User"
- Try to create a new user with the username of the user you just deleted
- Click on Save, a modal asking for user reactivation should appear
- Click on "Yes" on the modal to reactivate the user, the user should be active now and not showing in deleted users. …
=> Bugfix/FOUR-5829: The "Deleted user found" modal is not displayed

tests/Feature/Api/SanitizeHelperTest.php
Part of https://processmaker.atlassian.net/browse/FOUR-5827
Solution:
- Update class names to conform with psr-4
- For packages, remove autoloading tests since it's not needed for phpunit
Other PRs needed:
https://github.com/ProcessMaker/connector-docusign/pull/22
https://github.com/ProcessMaker/package-collections/pull/305
https://github.com/ProcessMaker/package-data-sources/pull/221
https://github.com/ProcessMaker/package-auth/pull/47
**Describe the bug**
See jira link above
**To Reproduce**
Steps to reproduce the behavior:
1. install the packages listed above
2. run composer dump-autoload
No psr-4 warnings
**Additional context**
Add any other context about the problem here.
=> Fix Composer PSR-4 autoload warnings

ProcessMaker/Http/Controllers/Auth/LoginController.php
When logging out with SAML, we're being redirected to the IDP portal instead of ProcessMaker /login page.
1. Log in with SAML user
2. Log out
- Removed `Saml2LogoutEvent` dispatch to avoid re-entering the handle function of the `LogoutListener::class`.
- Please configure the SSO SAML login feature and follow the reproduction steps of above.
https://user-images.githubusercontent.com/90727999/160916727-00a83f82-860b-4357-bc0e-03eabc2be5e9.mov
- [FOUR-5712](https://processmaker.atlassian.net/browse/FOUR-5712)
- [Package-auth PR](https://github.com/ProcessMaker/package-auth/pull/49)
=> Bugfix FOUR 5712 - The second login with saml is redirected to the idp portal

resources/js/components/Menu.vue
- create a screen with controls
- configure the controls with the tab order option
- test the tab order on the same scree
- create a new screen
- add a nested screen
- add in the nested screen the screen created from step 2
- add other controls in the second scren to see the difference
- add a submit
- save the screen
- click preview
- press the TAB key for each control
- Added tabindex=“1" to preview button to force jumping to the next element that was configured with some tab order.
**Explanation**
After some research about the behavior, the problem itself is related to the nature of how tabindex works. In the [documentation of tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) attribute we can found the following:
- tabindex=“0” means that the …
=> Bugfix/FOUR-5490: Tab stops working on nested screen when nested controls have tab order configured

package.json, resources/js/processes/screen-builder/screen.vue
The designer of screen-builder freezes with thousands of options in the selection list.
- Change of componente in preview data 
- Create Screen
- Add select list with data connector
- Add watcher to have dependency with others select list
- Press preview button
- Enable the watcher several times
https://user-images.githubusercontent.com/1747025/157733155-5ed48b91-c648-4144-859f-3d5115182883.mp4
- [FOUR-5430](https://processmaker.atlassian.net/browse/FOUR-5430)
=> 4.2.- Screen freeze with several triggers in watcher with dependency

ProcessMaker/Jobs/RunScriptTask.php, ProcessMaker/Jobs/RunServiceTask.php, ProcessMaker/Managers/WorkflowManager.php, tests/Feature/Api/ServiceTaskQueueTest.php, tests/Feature/Api/processes/ServiceTaskCustomQueue.bpmn, tests/Feature/Api/processes/ServiceTaskDefaultQueue.bpmn
- Add a pm:config property to setup the queue used for a Service Task: `pm:config='{"queue":"custom-queue"}'`
- Add a custom queue to horizon (supervisor-bpmn) e.g. install Ellucian package
- Add the custom property `"queue":"custom-queue"` to the pm:config of your ServiceTask
- Run the process, it should execute the ServiceTask on the defined queue
- https://processmaker.atlassian.net/browse/FOUR-5388
=> Customize Service Task queue

ProcessMaker/Traits/ExtendedPMQL.php
When using a PMQL query like `(data.form_date_picker_1 ="2021-12-31")` to search a record of a collection, it does not work.
1. Log in
2. Import collection [attached](https://processmaker.atlassian.net/browse/FOUR-4789) 
3. Open the collection
4. Fill following query (data.form_date_picker_1 = "2021-12-31")
- The `parseValue` function for dates in `ProcessMaker/Traits/ExtendedPMQL.php` always returned a "date with timestamp", so `2021-12-31 14:00` is different than `2021-12-31` and no records are found.
Please follow the reproduction steps of above to manually tests the search functionality by PMQL date in `/collections/{id}`.
You can also run `vendor/bin/phpunit tests/Feature/ExtendedPMQLTest.php`.
- [FOUR-4789](https://processmaker.atlassian.net/browse/FOUR-4789)
- [Pull Request 4315 …
=>  Bugfix FOUR-4789 (develop) - Searches for the date or date time in a collection 

ProcessMaker/Models/CallActivity.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Repositories/TokenRepository.php
- Calculate next user is slow and not required for Service and Script Tasks
- Add _user and _request are slow in Task Activation and should not be done in Repository anymore
- There are places where we are using Eloquent relationships to get Objects (like processRequest, processVersion, processRequestTokens) that were previously loaded this adds a lot of payload when running a process
- `function updateCatchEvents` is used during process execution and it is taking considerable time, needs to be improved.
- The user_id in Service and Script tasks are always null, there is no need to calculate its value
- To keep the backward compatibility _user and _request are still being set in Task Activation, but includes some speed improvements
- Reduce the use of eloquent relationships (do not run …
=> Improve process execution speed

ProcessMaker/Observers/ProcessRequestObserver.php, tests/Feature/Api/ProcessRequestsTest.php
**Case 1**
- Create a process with a subprocess
- Run a new request and move on to the task in the subprocess
- Verify in the database you have:
1.  In the table process_requests: 2 new requests (one per each process, parent and subprocess)
2. In the table process_request_tokens: a token for each start event and task.
- Run a delete api call fo the parent request ID **http://YOUR_HOST/api/1.0/requests/PARENT_REQUEST_ID**
- Subprocess token were not deleted
- In ProcessRequestObserver call delete() for each child process request. When called, the deleting method in the observer will trigger again looking for their children.
**Case 1**
- Create a process with a subprocess
- Run a new request and move on to the task in the subprocess
- Verify in the database you have:
1.  In the table …
=> Bugfix/FOUR-5904: Implement proposed solution to properly cascading to delete related tokens

resources/js/processes/screen-builder/screen.vue
Ticket [FOUR-5893](https://processmaker.atlassian.net/browse/FOUR-5893)
1. Create a screen
2. Add Line Input control
5. click preview
6. In the data input editor try to edit the data
Should be able to edit the data input on the screen. 
Can not edit the data input on the screen. 
The issue was due to the Data Input and Data Preview monaco editors sharing the same options set in the `monacoOptions` variable which had `readOnly` set to `true`. 
Solution is to remove the `readOnly` option from the `monacoOptions`. 
Test the above steps above and ensure the Data Preview editor is read only.
- Original Issue:  https://processmaker.atlassian.net/browse/FOUR-5430
=> Fix Data Input Read Only

config/horizon.php, resources/js/processes/modeler/initialLoad.js
Jobs execution have a large delay.
- Add configurable env variable to setup the internal queue delay when running BPMN Jobs.
Configure the following variables in `.env`:
```
BPMN_ACTIONS_LOCK_CHECK_INTERVAL=30
BPMN_QUEUE_INTERVAL=100
```
Also use the Redis queue.
Test a process with DataSources, note that takes less time to execute each DataSource sequentially.
e.g.
- You have an endpoint that runs in about 1 second
- Create a DataConnector to call that endpoint
- Add the previous data connector to the process, 8 times
- Connect the data connectors sequentially
- Without the changes the process could take about 16 seconds to complete
- With the changes the process should take less than 16 seconds to complete
- https://processmaker.atlassian.net/browse/FOUR-5878
=> Add BPMN_QUEUE_INTERVAL envvar

ProcessMaker/Http/Controllers/Api/ScreenController.php
The screen select list is slow.
- Add a parameter to reduce the data loaded to list the screens
1. Create about 500 screens
2. Create a new screen
3. Go to preview
4. Go to design
5. Add a nested screen
6. Choose a screen
7. Go back to preview
8. Go back to design
9. Add a new nested screen or select one already added
10. Choose a screen
Repeat steps 7 to 10 note the screen is getting very very slow
- REQUIRES: https://processmaker.atlassian.net/browse/FOUR-5890
- Requires: https://github.com/ProcessMaker/screen-builder/pull/1201
- TICKET: https://processmaker.atlassian.net/browse/FOUR-5890
=> Add fields parameter to screens index

resources/lang/en.json, resources/views/auth/oauth2/authorize.blade.php, resources/views/layouts/layout.blade.php, resources/views/layouts/minimal.blade.php
As a solutions engineer, I want to be able to customize the name displayed in the title bar of the application. This will allow us to more easily build out white-label solutions that obscure the name of ProcessMaker in favor of the name of the client.
In order to accommodate this, we will simply change the title in our primary layouts to a translated string so that said string can be updated by administrators with the Translations package installed, or by open source users utilizing the language files.
With the Translations package installed, visit `/admin/translations` and search for the string `ProcessMaker`. Then change that string to a different string. After a refresh, that string should now appear in the page title of your web browser.
- …
=> Allow customization of app title via language files

resources/js/components/common/mixins/datatable.js
1. Visit the /admin/translations page.
2. Type the word `test` into the search field.
An error message is returned.
Any results matching the query should be returned.
Discovered that the issue was caused because the `jsonRows` method in the datatable mixin was causing an error. This was due to the fact that it expected the first array key to be `0` which can never be guaranteed. To work around this, we use the Lodash `head` method to obtain the first element in the array and then use the Lodash `has` method to determine whether the `_json` property exists.
Follow the reproduction steps above with and without the relevant branches checked out.
- https://github.com/ProcessMaker/processmaker/pull/4338
- https://processmaker.atlassian.net/browse/FOUR-5953 …
=> Certain queries return an error when searching for Translations

ProcessMaker/Http/Controllers/Api/CssOverrideController.php, ProcessMaker/Models/Setting.php, resources/js/admin/cssOverride/components/SiteDesign.vue, resources/lang/en.json, resources/views/layouts/layout.blade.php, resources/views/layouts/minimal.blade.php
As an administrator, I want the ability to set the favicon to a custom PNG image, similarly to how I can set the three custom logos currently.
To accommodate this, we will simply add a fourth option to the list of icons allowed to be customized via the Customize UI page. We will then reference this custom icon in the primary layout blade template.
1. Visit the Customize UI page
2. Upload a new transparent PNG via the Custom Favicon file upload control
3. Click **Save** to save changes
4. Refresh the page and check to see
4a. If the source code reflects the new custom favicon after the title tag
4b. If the favicon has changed in the browser
- https://processmaker.atlassian.net/browse/FOUR-5964
=> Add favicon to list of images that can be customized in the Customize UI page

database/factories/UserFactory.php
This line of code was adding extra payload to every ProcessMaker endpoint
- Move the hash generation inside the factory.
- As a developer the add a log, dump or die to make sure `Hash::make('oneOnlyPassword');` is not executed on every endpoint.
- https://processmaker.atlassian.net/browse/FOUR-5977
=> Move hash generation inside UserFactory

resources/js/processes/modeler/initialLoad.js
- Create a new Process or edit an existing one. 
- Add two tasks to the process
- From the Advanced settings panel, edit the Node Identifier option and provide a non-unique identifier.
Modeler starts to get unresponsive
No warning that something is wrong is displayed
- Added a custom component for Node identifier input, to validate if new value of current node id is unique in store.state.nodes list
- If new id value exists, do not set the new Node identifier value, to avoid unresponsive behavior.
- Show a validation error when Node ID is not unique
**IMPORTANT:** 
- Please test it with all modeler elements (start event, end event, intermediate event, task, gateways, and also with all elements for each enterprise package)
- Test …
=> Bugfix/FOUR-5566: Modeler - When 2 nodes have the same id, modeler starts to unresponsive

resources/js/processes/screen-builder/screen.vue, resources/js/tasks/show.js, resources/views/tasks/edit.blade.php
Validation messages are duplicated according to the number of submit buttons.
**Expected behavior**: 
The global error summary (red alert message) should appear once at the top of the viewport, above all DOM elements.
- Can be closed manually via the X on the right side of the banner
- Span the entire width of the form that the user is working on
**Current behavior**: 
An error message is displayed in the validation for the required fields for each submit button.
- It should be possible to visualize the global alert message via in Core.
- [FOUR-5687](https://processmaker.atlassian.net/browse/FOUR-5687)
- [Screen Builder PR](https://github.com/ProcessMaker/screen-builder/pull/1206)
=> Bugfix FOUR 5687 - Validation messages are duplicated according to the number of submit buttons

resources/js/processes/screen-builder/screen.vue
- Create a nested screen with a couple of fields
- Create a form screen
- Add the nested screen
- On a new tab edit the nested screen
- Change the nested screen
- Go the tab of the parent screen
- Reset the cache for the modified nested screen when change from Design <--> Preview
See the video:
https://user-images.githubusercontent.com/8028650/163227831-dea8a931-d573-4678-a094-2e5c8ddd4200.mp4
- https://processmaker.atlassian.net/browse/FOUR-5933
- REQUIRES: https://github.com/ProcessMaker/processmaker/pull/4332
- REQUIRES: https://github.com/ProcessMaker/screen-builder/pull/1203
=> Refresh nested screen

upgrades/2022_04_13_085018_clean_up_and_remove_package_advanced_forms.php
If the deprecated package "[package-advancedforms](https://github.com/ProcessMaker/package-advancedforms)" is installed after upgrading to 4.2.30+, we need automatically clean up and remove it.
- Included is an upgrade migration file which will check for package-advancedforms when run.
- If the package exists and there are no screens with the ScreenType "ADVANCED", then the upgrade migration will remove the package with composer, remove the ScreenType "ADVANCED" from the table "screen_types", and will remove any package-specific published assets.
- If this upgrade migration is rolled back, it will attempt to re-install package-advancedforms.
- Make sure you're running processmaker/processmaker version 4.2.30-RC1 (at least) and make sure processmaker/package-advancedforms is installed. 
- …
=> FOUR-5868: Upgrade migration to clean-up and remove package-advancedforms

ProcessMaker/Jobs/SanitizeUsernames.php, database/factories/UserFactory.php, upgrades/2022_04_19_164837_sanitize_usernames.php
In prior versions of processmaker/processmaker, the username field allowed numerous characters which are now disallowed. The only allowed characters in a username are alphanumeric, the underscore character "_", and the hyphen character "-". 
- An upgrade migration is included in this PR which when run, spawns a UsernameSanitization job per 250 users. It spreads out the workload so the PHP process won't run out of memory in the event there are 25,000+ usernames.
- The UsernameSanitization job removes all disallowed characters and checks to make sure the sanitized username is unique. If it is not unique, it will append a number start with 0 to the end of the username and check for uniqueness again and will loop this behavior until the username is unique. It will then save the username and …
=> FOUR-5957: Create an upgrade migration to sanitize usernames 

ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Http/Controllers/TaskController.php, ProcessMaker/Models/Comment.php, tests/Feature/CommentsTest.php, tests/Feature/TasksTest.php
Fix the issue where comments referencing a username would no longer match. Instead of storing the username itself in the comment text we should store a reference to the user’s ID and parse that into a username at runtime.
Please refer to: [FOUR-5759: The Processes should be order alphabeticallyTRIAGE](https://processmaker.atlassian.net/browse/FOUR-5759).
- Add a comment and tag some user i.e. "This is my comment @myUser"
- Go to your database to the comments table and search the comment. In the body column you will see the comment with the username: "This is my comment @myUser"
- Added an accessor and mutator to comment model to parse between username and id and keep the users references in comments.
- Add a comment and tag some user i.e. "This is my comment @myUser"
- Go to your database …
=> Bugfix/FOUR-5958: Fix the issue where comments referencing a username would no longer match

resources/views/requests/show.blade.php
- Create process
- Add a task
- Create a Request
- Complete the request
Task tab is still shown on completed requests, Giving the feeling that there are even more tasks 
Task tab should not showing on completed requests. As in PM 4.1.27 
- Hide tasks in request if no pending task or process completed.
https://user-images.githubusercontent.com/90727999/166745121-3785cddd-eb03-49c2-807b-f22fe4ad4fce.mov
- Create process
- Add a task
- Create a Request
- Complete the request
- You should not see **Tasks** tab
- [FOUR-6042](https://processmaker.atlassian.net/browse/FOUR-6042)
=> Bugfix/FOUR-6042: Task tab is still shown on completed requests

ProcessMaker/Http/Controllers/Auth/LoginController.php
Users who have a custom dashboard are redirected on login to the `requests` page instead of their dashboard set by the dynamic UI package.
1. Install Dynamic UI package
2. Create a dashboard
3. Assign the created dashboard to any user
4. Log in and log out the above user
5. The problem is related to the cookie `processmaker_intended`. It will expire after 10 minutes. Instead of waiting 10 minutes, you can delete the cookie using browser developer tools or change its value to 1 minute at`LoginController` line 60.
6. Without the above cookie, after a successful login it will redirect to `requests` page because that's how it's set in the `$redirectTo` variable. 
- The proposed solution is to redirect always to `Route::get('/', 'HomeController@index')->name('home');` instead of `requests`. …
=> Bugfix FOUR-6137 - Requests page is displayed when login after lost session

ProcessMaker/Upgrades/Commands/BaseCommand.php, ProcessMaker/Upgrades/Commands/UpgradeCommand.php, ProcessMaker/Upgrades/Commands/UpgradeInstallCommand.php, ProcessMaker/Upgrades/Commands/UpgradeResetCommand.php, ProcessMaker/Upgrades/Commands/UpgradeRollbackCommand.php, ProcessMaker/Upgrades/Commands/UpgradeStatusCommand.php, ProcessMaker/Upgrades/UpgradeMigrationRepository.php
See https://processmaker.atlassian.net/browse/FOUR-6124
- We were confusing the connection name with the database name. Solution is to hard-code database connection name to `processmaker`
run artisan upgrade
- https://processmaker.atlassian.net/browse/FOUR-6124
=> Always use the `processmaker` connection

ProcessMaker/Upgrades/Commands/UpgradeCommand.php
CloudOps is requesting a `--force` flag for the `php artisan upgrade` command to skip the "Do you want to run the upgrade migrations in production?" console prompt. 
- Added the `--force` flag option to the [UpgradeCommand file](https://github.com/ProcessMaker/processmaker/blob/ba6c5bd41a38b74b3bfa20e7811bf5144c74d84b/ProcessMaker/Upgrades/Commands/UpgradeCommand.php).
1. Make sure you environment is set to production in the .env file: `APP_ENV=production` and debugging is turned off: `APP_DEBUG=FALSE`.
2. Without having previously run the upgrade command, run `php artisan upgrade`. This should prompt you to answer "y" or "n", type "n" and hit enter.
3. Now run `php artisan upgrade --force`. The upgrade migrations should run without prompting you for input.
- [JIRA ticket …
=> FOUR-6112: Adding --force flag to artisan upgrade command

resources/js/admin/users/components/AddUserModal.vue, tests/Feature/Api/UsersTest.php
- Go to admin
- Create a user
- Delete the user created
- Create a user with the same username that user deleted **but different email**
- Press YES option in reactivated your account 
- The user still in deleted users
- Added username to the request to search by username while restoring
https://user-images.githubusercontent.com/90727999/166295651-1f14dfdd-ace5-4c18-b806-6d836760ebb4.mov
-  Go to admin
- Create a user
- Delete the user created
- Create a user with the same username that user deleted **but different email**
- Press YES option in reactivated your account 
- The user still will restored and removed from deleted users tab. You should see it in Users tab.
- [FOUR-6092](https://processmaker.atlassian.net/browse/FOUR-6092)
=> Bugfix/FOUR-6092: User is not restored

resources/js/admin/cssOverride/components/SiteDesign.vue
Performing many Save request generates the Server Error: `Call to a member function each() on null at SettingsHelper.php:104`
1. Go to Admin
2. Click on Customize UI
3. Press the SAVE button more than once quickly
- Added a loading state to the Save and Reset button, in this way only one request can be made at a time.
- Please follow the reproduction steps above.
- [FOUR-6100](https://processmaker.atlassian.net/browse/FOUR-6100)
Working Video:
https://user-images.githubusercontent.com/90741874/166584688-42899aab-fe48-4ae6-b188-c1a026bfa6fa.mov
=> Bugfix FOUR-6100 - "Server Error message in Customize UI"

resources/js/processes/screen-builder/screen.vue
Ticket: [FOUR-6157](https://processmaker.atlassian.net/browse/FOUR-6157)
Inputting data into the Data Input freezes with Email Type Screens. 
An infinite loop is triggered when hitting the `formatMonaco` method with an invalid JSON object in the Data Input.
- Check if the Data Input has a valid JSON object before running the `formatMonaco` editor. 
1. Go to Designer
2. Create an Email Screen Type
3. Create a Record List
5. Press the Preview button
6. Add "data" in the Data Input section.
The Preview mode should not freeze after writing text in the Data Input section.
Test this [PR](https://github.com/ProcessMaker/processmaker/pull/4298) to ensure no additional regressions.
=> Fix Monaco Editor Freezing with Email Type Screens

ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Traits/ProcessTrait.php, resources/views/processes/import.blade.php
When Importing a process and setting the Manager, it's saved in the database as a full Object instead of just an id. 
1. Import the attached process (notification-task.json). 
2. Assign a Process Manager.
3. Save
4. Run request and submit
5. At this point you will be able to replicate the problem, because the `manager_id` property was saved as an Object instead of an int.
- Added the same function as the edit view to make sure that the ID is sent to the back-end instead of an object.
- Follow the reproduction steps of above. 
- When importing the process and assigning a Process Manager it will store the manager_id correctly on DB. 
- [FOUR-6181](https://processmaker.atlassian.net/browse/FOUR-6181)
=> Bugfix FOUR-6181 - error "Array to string conversion" with imported process

composer.json, composer.lock
Running `composer install` in Composer v2.3.x generates questions and warning messages.
- Allow plugins for typo3/class-alias-loader to remove trust question.
- Update composer.lock hash to remove warning message about outdated composer.lock.
=> Composer Updates

ProcessMaker/Http/Controllers/Api/SecurityLogController.php, storage/api-docs/api-docs.json
When running the processmaker install artisan command, the swagger docs generator fails due to a duplicate property being found in the API SecurityLogsController file. This causes the command to exit (with code 1) and prevents the remainder of the installation.
To reproduce, run the `php artisan processmaker:install` command and you'll encounter an exception being thrown.
- Rename the duplicate operationId in the SecurityLogsController.
You should be able to run `php artisan processmaker:install` without any exceptions being thrown.
- [FOUR-6265](https://processmaker.atlassian.net/browse/FOUR-6265)
=> Fix swagger docs generation

resources/lang/en.json
display the message “File ID does not exist” for each file that you want to download and the id is not found.
please review documentation https://processmaker.atlassian.net/browse/DOC-2353 for multiple files download
display other message
- change label
1. Create a screen with download file 
2. Create a process with start->task->end
3. Assign the screen on the task
4. Create a request
5. Go to data
6. Put a invalid id in file 
- [FOUR-6201](https://processmaker.atlassian.net/browse/FOUR-6201)
=> "File Download missing files" message error appears

resources/js/processes/screen-builder/screen.vue
Ticket:  [FOUR-6157](https://processmaker.atlassian.net/browse/FOUR-6157)
[Reopened Comment](https://processmaker.atlassian.net/browse/FOUR-6157)
When the Data Preview editor options were being updated to  `readOnly` an infinite loop was triggered freezing the screen.
**NOTE:**
Was ONLY able to replicate this issue on the RT server. Was not able to replicate it locally. 
1. Create an Email type screen
2. Add a RecordList and input a variable name
3. Preview the screen and input `"foo": "foobar"` into the Data Input editor
4. Delete the data
The screen does not freeze when deleting data from the data input editor.
- Configure the Data Preview editor to be readonly when the editor is mounted instead of when data is being formatted. 
Follow the …
=> Fix Infinite loop when deleting data in the Data Input editor

ProcessMaker/Contracts/SoapClientInterface.php, ProcessMaker/Contracts/WebServiceCallerInterface.php, ProcessMaker/Contracts/WebServiceConfigBuilderInterface.php, ProcessMaker/Contracts/WebServiceRequestBuilderInterface.php, ProcessMaker/Managers/WebServiceSoapConfigBuilder.php, ProcessMaker/Managers/WebServiceSoapRequestBuilder.php, ProcessMaker/Managers/WebServiceSoapServiceCaller.php, ProcessMaker/Providers/WorkflowServiceProvider.php, config/filesystems.php, tests/Feature/WebServiceSoapServiceCallerTest.php, tests/unit/ProcessMaker/Managers/WebServiceSoapConfigBuilderTest.php, tests/unit/ProcessMaker/Managers/WebServiceSoapRequestBuilderTest.php
Implement Soap base contract and classes to configure a User Password authentication
- https://processmaker.atlassian.net/browse/FOUR-6337
=> Four-6337 Configure user password

ProcessMaker/Contracts/SoapClientInterface.php, ProcessMaker/Contracts/WebServiceConfigBuilderInterface.php, ProcessMaker/Contracts/WebServiceResponseMapperInterface.php, ProcessMaker/Factories/SoapClientFactory.php, ProcessMaker/Managers/WebServiceSoapConfigBuilder.php, ProcessMaker/Managers/WebServiceSoapRequestBuilder.php, ProcessMaker/Managers/WebServiceSoapResponseBuilder.php, ProcessMaker/Managers/WebServiceSoapServiceCaller.php, ProcessMaker/Providers/WorkflowServiceProvider.php, ProcessMaker/Soap/NativeSoapClient.php, ProcessMaker/WebServices/NativeSoapClient.php, ProcessMaker/WebServices/WebServiceRequest.php, tests/Feature/WebServiceRequestTest.php, tests/Feature/WebServiceSoapServiceCallerTest.php, tests/unit/ProcessMaker/Managers/WebServiceSoapConfigBuilderTest.php
Implement Support for SOAP calls
Run the test: WebServiceRequestTest. It executes the WebService using a ServiceTask and DataConnector configuration.
- https://processmaker.atlassian.net/browse/FOUR-6336
=> Implement Support for SOAP calls

ProcessMaker/Models/Process.php
An error is generated when we query the `getProcesses()` endpoint in Scripts and we `include=category`. Also note, this only happen when a Process **has more than 1 category assigned**.
`(Code: 0) Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335 Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335`.
- It seems that by default when no type is defined, the property is set to `string`. The proposed solution is to define the property as an object.
1. Create process with 2 or more categories.
2. Create a new PHP script
3. Add the next code and run:
```
$filter = '';
$order_by = 'id';
$order_direction = 'asc'; 
$per_page = 5; 
$status = 'ACTIVE';
$include = 'category'; // string | Include data from related models in payload. …
```
=> Bugfix FOUR-6287 - Getting processes via SDK doesn't work

public/.gitignore
The file"processmaker/public/.gitignore" should be removed from the build file.
- The `.gitignore` file in the public directory didn't contain updated information. It was simply deleted
- [FOUR-6347](https://processmaker.atlassian.net/browse/FOUR-6347)
=> Remove .gitignore file from public directory

ProcessMaker/Providers/RouteServiceProvider.php, routes/api.php
In endpoints type `users/{user} ` the parameter `{user}` must be an integer.
`users/1` but if you enter `users/1something` it also returns the correct answer.
https://user-images.githubusercontent.com/1747025/171860364-aed630fe-0bc7-493f-b4c7-af7b62aed902.mp4
- Added validation with global constraints for these parameters.
Review endpoints of this type and enter wrong parameters.
- Ticket [FOUR-6346](https://processmaker.atlassian.net/browse/FOUR-6346)
Also please check this PR
[connector-docusign](https://github.com/ProcessMaker/connector-docusign/pull/26)
[package-auth](https://github.com/ProcessMaker/package-auth/pull/59)
[package-collections](https://github.com/ProcessMaker/package-collections/pull/311)
[package-comments](https://github.com/ProcessMaker/package-comments/pull/78) …
=> Validate Id parameters to be integer type

ProcessMaker/Http/Controllers/Api/ProcessController.php
When installing processmaker/docker-executor-java, the java SDK build fails which then causes the entire docker image build to fail as well.
To replicate this issue:
1. Run `composer require processmaker/docker-executor-java`
2. Now run `php artisan docker-executor-java:install`
You'll notice compilation errors in the output and an exit code of 1.
- Added a open-api-generator anonnation to [Api/ProcessController](https://github.com/ProcessMaker/processmaker/blob/019407013bf78d5af1b0d55d3c4d67a45df5279c/ProcessMaker/Http/Controllers/Api/ProcessController.php#L524).
- Added an additional compiler configuration value for the java sdk compiler.
You should now be able to run the same steps as described above and build the docker-executor-java Docker image without errors and with an exit code …
=> PM4EH-61: docker-executor-java SDK compilation bug fix

resources/sass/app.scss
Select List still mark in red the validation of the required field
1. Go to admin
2. Open Customize UI
3. Select a color different to red in "Danger" option
4. Save the changes
5. Create a Screen
6. Add controls like(line input, textarea, select list, signature)
7. Add Required validation in each control
8. Press preview button
- Another class is used for errors, since other packages like saved search overwrite using inline css and the !important property.
- Compile assets, please run `npm link` for screen builder and vue-form-elements.
- [FOUR-6101](https://processmaker.atlassian.net/browse/FOUR-6101)
=> Bugfix 6101-B: Error validations are not marked with the color selected in Customize UI

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Jobs/ImportProcess.php, ProcessMaker/Models/Process.php, ProcessMaker/Observers/ProcessObserver.php, database/migrations/2022_05_24_122028_create_webentry_routes_table.php, resources/js/components/shared/Column.vue, resources/views/processes/import.blade.php
Please read the PRD [FOUR-6178](https://processmaker.atlassian.net/browse/FOUR-6178)
> **_NOTE:_** Custom URL for web entries are only available for start event web entries
- Create some processes with web entry start events.
- Click the new **Options** button under web entry URL
- A modal should open with all the configuration fields for custom webentries URL
- Test first segment is unique
- Add some parameters like state, city
- Copy the url, in the parameters section you should have something like /{state}/{city}
- Paste the URL in the web browser and replaze the variables {state} and {city} for some param like /nevada/las-vegas
- The form for the web entry should show.
- Complete the form and go to requests
- Check in the request data tab, you should see 2 new attributes in the data …
=> Feature/FOUR-6178: Web Entry Custom URLS

ProcessMaker/Jobs/SanitizeUsernames.php
Keeps @ + . - _  characters in user names when the migration that fixes user names is run
- Added the allowed characters in the regular expressions
Add users that use  not allowed characters and allowed characters, for example
user1.lastname1
user2@lastname2
user3_lastname3
user4-lastname4
user5+lastname5
user6~lastname6
user7 lastname7
user8*lastname8
user9^lastname9
After the upgrade the user names should be modified to (not allowed characters must be removed):
user1.lastname1
user2@lastname2
user3_lastname3
user4-lastname4
user5+lastname5
user6lastname6
user7lastname7
user8lastname8
user9lastname9
[https://processmaker.atlassian.net/browse/FOUR-6432](https://processmaker.atlassian.net/browse/FOUR-6432)
=> FOUR-5432: Fix for branch 4.2.31

ProcessMaker/Jobs/SanitizeUsernames.php
Keeps @ + . - _  characters in user names when the migration that fixes user names is run
- Added the allowed characters in the regular expressions
Add users that use  not allowed characters and allowed characters, for example
user1.lastname1
user2@lastname2
user3_lastname3
user4-lastname4
user5+lastname5
user6~lastname6
user7 lastname7
user8*lastname8
user9^lastname9
After the upgrade the user names should be modified to (not allowed characters must be removed):
user1.lastname1
user2@lastname2
user3_lastname3
user4-lastname4
user5+lastname5
user6lastname6
user7lastname7
user8lastname8
user9lastname9
[https://processmaker.atlassian.net/browse/FOUR-6432](https://processmaker.atlassian.net/browse/FOUR-6432)
=> FOUR-6432: 4.2.31-Adjust upgrade migration that updates each username based on a list of disallowed not to sanitize the

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
Ticket: [FOUR-5697](https://processmaker.atlassian.net/browse/FOUR-5697)
Error is returned when using the API to delete a request file.
1. Start a request that contains at least one uploaded file.
2. Delete the uploaded file using the following API: /requests/{request_id}/files/{file_id} Delete all media associate a request.
- 'To few arguments' errors were being returned with the `destroy()` method, update the query to use the `delete()` method instead
**Video**
https://user-images.githubusercontent.com/52755494/173419700-030087e5-e8ca-484d-909a-d05f07f19c01.mov
=> Fix: Api 'Delete' method with Request Files

ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Models/User.php
Warnings are displayed when running scripts breaking script execution
1. Create a new script
2. Use the following code:
```php
$apiInstance = $api->tasks();
$result = $apiInstance->getTasks();
return $result;
```
3. Run the Script
- If the type is not defined it is set to "string"  by default. That causes settyype problems. The solution is to explicitly set the type of the property.
- Rebuild the PHP Executor at `/admin/script-executors`.
- Follow the steps of above.
- [FOUR-6006](https://processmaker.atlassian.net/browse/FOUR-6006)
=> Bugfix FOUR-6006 - Warnings are displayed when running scripts breaking script execution

ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/AuthenticateSession.php
- Set core to this PR's branch, bugfix/FOUR-6485.
- Set package-webentry to [bugfix/FOUR-6485](https://github.com/ProcessMaker/package-webentry/pull/150).
- Set package-collections to patch-1-cartegraph.
- Set package-savedsearch to patch-1-cartegraph.
**Note**: This branch fixes two (2) tickets in Jira.
For [FOUR-6485](https://processmaker.atlassian.net/browse/FOUR-6485):
1. Create a custom webentry URL.
2. Copy the standard webentry URL, then switch it over to a custom URL and save (as well as save the process).
3. Visit the standard webentry URL.
4. Notice the standard URL still works as well as the custom webentry URL.
For [FOUR-6484](https://processmaker.atlassian.net/browse/FOUR-6484):
- Create a custom URL with a segment and one or more URL variables.
- Save the webentry URL and …
=> FOUR-6484 & FOUR-6485: patch-1-cartegraph webentry fixes

resources/js/bootstrap.js, resources/js/timeout.js
Create an Anonymous Web Entry. Wait until the session timeout time happens.
-  A new property that determines if a webentry is anonymous or not has been added to the model
-  To set the time out this property isAnonymous sets a header to enable/disable the time out control
Create an Anonymous Web Entry. Wait until the session timeout time happens and verify that the pages is not redirected to the login page. 
To speed up the test, change the default session time out in .env or editing config/session.php to something like  
'lifetime' => env('SESSION_LIFETIME', 10) 
that is 10 minutes by default.
Test with embedded and not embedded web entries and with  web entries in start events and tasks.
The attached zip file has a process with the 4 combinations. Put the html files in …
=> FOUR-6466: Web entry timeout redirect in Cartegraph instances (cartegraph)

resources/views/processes/environment-variables/edit.blade.php
When editing an environment variable, a line input was used to set its value. This controls strips any line break wrote in it, so the edited environment variable lost any typed line break. 
- Use a text area instead of a line input for the value of an environment variable.
- Create an environment variable called 'env_var' it must contain  line breaks
- Use an script to get the environment variable. The code for the script should be:
`return return getenv('env_var');`
- Verify that the returned value by the script contains line breaks (\n)
- Edit the environment variable and put another string with line breaks
- Run the script and verify again that the returned value by the script contains line breaks (\n)
- [https://processmaker.atlassian.net/browse/FOUR-6383](https://processmaker.atlassia …
=> FOUR-6383: Error to update environment variables

ProcessMaker/Http/Resources/ApiCollection.php
The query parameter filter that is returned by the ApiCollection shows untrusted or unfiltered data.
1. Go to: /requests/saved-searches/
2. Click on View.
3. Open browser Web Developer Tools
4. Introduce Search < in the Search filter.
5. Go to Network - Response
You may notice that in the Response `meta.filter` will have the value Search `<` instead of Search `&lt`.
Reported endpoints:
```
GET /api/1.0/saved-searches?include=reports%2Cuser_options&page=1&per_page=10&filter=<meta content=was-tnb-leb><div 
style="was-tnb-leb"><a style="was-tnb-leb"><style id="was-tnb-leb"
>&type=request&subset=mine&order_by=title&order_direction=asc HTTP/2
GET /api/1.0/saved-searches/569/results?page=1&per_page=10&include=process%2Cparticipants%2Cdata&pmql=%28status%20%3D% …
```
=> Content Injection - Payload reflected in the page body

resources/views/layouts/layout.blade.php, resources/views/layouts/minimal.blade.php
1. Go to `/requests/{id}` page.
2. Open inspector.
3. There is no Content Security Policy in the `<head>` section of the code.
Based on the document "ProcessMaker Security Scan - Permissive Content Security Policy Detected" the Security Scan reports:
- Missing mandatory CSP directive object-src, script-src.
- Since the Security Scan only reports the absence of the CSP, this Pull Request only adds the CSP with permissive rules.
Please follow the reproduction steps of above. All pages should contain the CSP.
- [FOUR-6516](https://processmaker.atlassian.net/browse/FOUR-6516)
=> FOUR-6516 - Missing mandatory CSP directive object-src, script-src

ProcessMaker/Http/Controllers/Api/UserController.php
The Swagger documentation for the User API needs to be updated to reflect that only these keys are searched.
- First Name
- Last Name
- Username
- Email
- Updated description for Users API filter parameter.
- Run `php artisan l5-swagger:generate`.
- Go to `/api/documentation`.
- Test the getUsers endpoint.
- [FOUR-6344](https://processmaker.atlassian.net/browse/FOUR-6344)
- [Saved Search Pull Request](https://github.com/ProcessMaker/package-savedsearch/pull/316)
=> Bugfix FOUR-6344 Modify swagger documentation for Users API filter

resources/js/components/common/mixins/accessibility.js
- Create a screen with a record list
- The sub-screen used for the record list must have a Select List as **its first control** (at the top of the screen)
- Add a record to the record list. 
The issue is that  Select List is displayed expanded when the record list pop up appears.
- If the first element is a select list, do not force the focus over it.
- [https://processmaker.atlassian.net/browse/FOUR-6509](https://processmaker.atlassian.net/browse/FOUR-6509)
=> FOUR-6509: Problem with Record list and Select List Display

ProcessMaker/Jobs/ImportScreen.php, resources/lang/en.json, resources/views/processes/screens/import.blade.php
1. Have a screen that has a watcher configured and working correctly
2. import the screen
3. Open the imported screen
4. Click the preview option
5. Fill the field that triggers the watcher
6. A message error is displayed
- Display a warning message when a screen is imported, and the same has watchers assigned, so the process architect will be informed that the script related needs to assign a user to run correctly.
After importing the screen, if it has watchers assigned in the import summary panel, a warning message is displayed. Before the changes, the message displayed indicates that no errors/warnings were detected in the importation. This is not true because it is required to have the architect's intervention to complete the setup. …
=> FOUR-1267 Importing a screen with scripts (watchers) does not assign a user to the script

ProcessMaker/Helpers/SettingsHelper.php, ProcessMaker/Models/Setting.php
**Dupe of #4460 but based on 4.2.30 for Ellucian.**
----
Original PR by @caleeli:
At Ellucian servers the Redis usage is too high, overflowing the network usage.
This is caused by the use of Redis Cache to store, get, update the settings.
- Temporal solution. Use Array Cache to store the settings.
You need a PM4.2 with enterprise packages.
- Configure CACHE_DRIVER to redis (.env)
- Monitor the use of network while using ProcessMaker.
- Before the fix the usage of redis is high reaching 64MB 126MB while running a process and navigating through the menus (Requests, processes, ...)
- https://processmaker.atlassian.net/wiki/spaces/SCO/pages/2858844161/Ellucian+High+Redis+Network+traffic
- - https://processmaker.atlassian.net/browse/FOUR-6578
=> Fix overflow Redis usage (Ellucian Patch 1)

ProcessMaker/Helpers/SettingsHelper.php, ProcessMaker/Models/Setting.php
At Ellucian servers the Redis usage is too high, overflowing the network usage.
This is caused by the use of Redis Cache to store, get, update the settings.
- Temporal solution. Use Array Cache to store the settings.
You need a PM4.2 with enterprise packages.
- Configure CACHE_DRIVER to redis (.env)
- Monitor the use of network while using ProcessMaker.
- Before the fix the usage of redis is high reaching 64MB 126MB while running a process and navigating through the menus (Requests, processes, ...)
- https://processmaker.atlassian.net/wiki/spaces/SCO/pages/2858844161/Ellucian+High+Redis+Network+traffic
- - https://processmaker.atlassian.net/browse/FOUR-6578
=> Fix overflow Redis usage

composer.json
CICD was broken due to a custom package being listed in the enterprise package property of composer.json. It was listed there to provide Cloud Ops with a way of programmatically installing the correct version of said package.
Move the custom package to its own section. Could be used in the future by other custom packages without impacting CICD.
- https://processmaker.atlassian.net/browse/FOUR-6593
=> [FOUR-6593] Ethos Package is breaking Core CI

ProcessMaker/SanitizeHelper.php, tests/unit/ProcessMaker/SanitizeHelperTest.php
data_enconded is a computed property that contains an object encoded as JSON string. When a property of this object contains a < symbol, the form data is sanitized the json variable is truncated. The following is and example of the content of data_encoded that has the problem:
```
{
"REQUEST_ID": 183681,
"STATUS": "IN_PROGRESS",
"USER_ID": 48252,
"ADOA_RWA_REMOTE_AGREEMENT_VALID": "N",
"ADOA_RWA_AGENCY_NAME": "DEPT OF ECONOMIC SECURITY",
"ADOA_RWA_EMPLOYEE_NAME": "BEGAY, MARIE",
"ADOA_RWA_EIN": "211913",
"ADOA_RWA_POSITION": "SDE000022620",
"ADOA_RWA_JOB_TITLE": "PROG SVC EVALR 2",
"ADOA_RWA_FLSA": "Non-Exempt",
"ADOA_RWA_TYPE_REQUEST": "NEW",
"ADOA_RWA_STREET_ADDRESS": "5205 W Thunderbird W Rd. # 2054",
"ADOA_RWA_CITY": "914",
"ADOA_RWA_CITY_OTHER": null,
"ADOA_RWA_STATE": "3", …
```
=> Improve strip_tags function

ProcessMaker/Bpmn/Process.php
Currently, when the "Condition" field of a Conditional Start Event is empty it always evaluates to true. A workspace would constantly have script tasks running non stop and this would create huge log files: ~10GB per day.
In order to avoid huge log files, please remove the following line at ProcessMaker/Bpmn/Process.php line 44
- Removed line 44 at ProcessMaker/Bpmn/Process.php
- [FOUR-6598](https://processmaker.atlassian.net/browse/FOUR-6598)
=> Bugfix/FOUR-6598: Remove Log Line from Conditional Start Events

resources/sass/_variables.scss
Ticket: [FOUR-6642](https://processmaker.atlassian.net/browse/FOUR-6642)
There are some instances in ProcessMaker where the .text-muted class has its color set to `#788793`. This shade of grey does not meet web accessibility contrast standards.
The color of the .text-muted class has been reset to the Bootstrap default of `#6c757d`.
1. Update core branch to `bugfix/FOUR-6642`
2. Open local environment, go to a Process.
3. In the Configuration menu, inspect the helper text under the Node Identifier field. The .text-muted color should be `#6c757d`.
- [FOUR-5110](https://processmaker.atlassian.net/browse/FOUR-5110) | Design Bugs
=> FOUR-6642: The .text-muted class for helper text is a non-accessible color

resources/sass/app.scss
Ticket: [FOUR-6607](https://processmaker.atlassian.net/browse/FOUR-6607)
There are currently no border-radius attributes on the multiselect field. It needs a border-radius of .125em to make it consistent with other screen elements, like the .card class used for our table.
Updated border radius of `multiselect__tags` to 0.125em
1. Update core branch to `bugfix/FOUR-6607`
2. Open local environment, go to Requests
3. Inspect the Process, Status, Requester, or Participants drop-down. The `multiselect__tags` field border-radius should be 0.125em.
4. You can inspect other multiselect dropdowns throughout the application. Packages such as package-savedsearch and package-data-sources use `multiselect__tags` fields in their configurations. The border-radius for those fields should be 0.125em as …
=> FOUR-6607: Border-radius on multiselect__tags field needed

ProcessMaker/Traits/HideSystemResources.php
The "Setup User" and "User Setup Signal Throw" requests from previously executed runs of Ethos User Sync are now viewable under All Requests.
1. Create or locate a System Process.
2. Generate a request from that Process.
3. Delete the Process from step 1.
- The scope `withTrashed` was added, to take into account soft-deleted processes so we can correctly filter system requests.
Follow the reproduction steps of above. You should not see system requests at `/requests` page.
- [FOUR-6398](https://processmaker.atlassian.net/browse/FOUR-6398)
test with 'single' quotes
=> Bugfix FOUR-6398 "Setup User" and "User Setup Signal Throw" are displayed under All Requests

resources/js/processes/screen-builder/screen.vue
Please see: https://processmaker.atlassian.net/browse/FOUR-6409
- Create a form with some elements
- Mark some of them as required
Current behavior: When start a new request and start the task or go to preview in screen builder, the validation errors appears before clicking on submit, and not showing as alert
Expected behavior: Validation error message shouldn't appear until the submit button is pressed. Message should appear as the "success" alert when submitting a form
- When submit a form, while checking if is valid, if not show ProcessMaker.alert()
- Removed old alert divs
https://user-images.githubusercontent.com/90727999/176259628-06e0ccc5-f2f8-4022-9fbe-dcf215ebb6a4.mov
- …
=> Bugfix/FOUR-6409: Form Validation Error messaging not displaying correctly

ProcessMaker/Providers/RouteServiceProvider.php, ProcessMaker/SanitizeHelper.php, tests/Feature/Api/CssOverrideTest.php, tests/Feature/Api/ProcessTest.php, tests/Feature/Api/SanitizeHelperTest.php, tests/Feature/Console/GarbageCollectorTest.php, tests/Feature/Docker/DockerFacadeTest.php, tests/Feature/HideSystemCategoriesTest.php, tests/Feature/Processes/ExportImportScreenTest.php, tests/Feature/Processes/ScreenConsolidatorTest.php, tests/Feature/SessionTest.php, tests/Feature/Shared/PerformanceReportTrait.php, tests/Resources/TaskTest.php, tests/ScreenConsolidatorTest.php, tests/Sdk/BuildSdkTest.php, tests/Traits/HasVersioningTest.php, tests/unit/ProcessMaker/SanitizeHelperTest.php
Circle CI was not running unit tests for a few weeks now. As a result, several tests are now failing.
- This PR marks a number of failing tests as skipped, to be reviewed later.
phpunit should pass for all tests in core
- https://processmaker.atlassian.net/browse/FOUR-6658
.
=> Skip failing tests in core to re-enable tests in CircleCi

ProcessMaker/ImportExport/ExportEncrypted.php, tests/Feature/Processes/ExportEncryptedTest.php
Add a new class ProcessMaker/ExportEncrypted.php.
- Added a new class `ProcessMaker/ExportEncrypted.php`.
- It returns an array that run `json_encode` on the export value, encrypts it, and adds "encrypted" => true.
- Added `ExportEncryptedTest.php` test.
- Run `phpunit --filter testExportEncrypted tests/Feature/Processes/ExportEncryptedTest.php`
- [FOUR-6727](https://processmaker.atlassian.net/browse/FOUR-6727)
=> FOUR-6727 - Add ExportEncrypted class to core

ProcessMaker/Jobs/ImportScreen.php, tests/Feature/Processes/ExportImportScreenTest.php, tests/Feature/Processes/ScreenConsolidatorTest.php
- Go to Screens > import screen
- Select a screen without any watcher or use the file attached
- Click on import
[test_nested_record_list.json.zip](https://github.com/ProcessMaker/processmaker/files/9657594/test_nested_record_list.json.zip)
You can see a 500 server error when trying to import the screen.
Screen that doesn't have watchers should be imported correctly.
- Added condition to check if screen have watchers before trying to do the foreach
https://user-images.githubusercontent.com/90727999/192571703-f793ecf9-0c7f-46c9-a051-66bd2f72e413.mov
Skipped test now passing
- Test the above steps
- [FOUR-6783](https://processmaker.atlassian.net/browse/FOUR-6783)
=> Bugfix/FOUR-6783: Import screen that doesn't have any watcher fails 

resources/js/processes/screen-builder/main.js
* Errors were happening when opening a screen complaining about Vuex modules not registering from ScreenBuilder and these modules were crucial to sending the errors from Validations
* Importing the Vuex modules in core. We did it on the ScreenBuilder side but apparently, we needed to do it on Core side.
* Check if no errors from Vue / Vuex are being thrown on console when opening a screen.
Usually the errors will happen if there's a problem registering the modules from ScreenBuilder
- https://processmaker.atlassian.net/browse/FOUR-6752
=> FOUR-6752 Added ScreenBuilder modules to be initialized on app load

ProcessMaker/Http/Controllers/Api/SecurityLogController.php
Open the api documentation at api/documentation
Security is spelled wrong in the header for the Security Logs section.
Security should be spelled correctly.
=> [FOUR-6856] API docs typo in Security Logs section
