resources/views/tasks/edit.blade.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-3741
- Add condition to show REASSIGN for overdue tasks
=> Allow reassign overdue tasks

resources/js/components/shared/ColumnChooser.vue
- Emits an update event from the Column Chooser component so that changes can be detected in other components
- https://github.com/ProcessMaker/package-collections/pull/277
- http://tickets.pm4overflow.com/tickets/285
- https://processmaker.atlassian.net/browse/FOUR-3769
=> Emit input event from ColumnChooser

ProcessMaker/Http/Controllers/RequestController.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-2883
Any user with permissions Edit Request Data, Edit Task Data and view All Requests, can view the Forms Tab
=> Fix Forms Tab Missing

ProcessMaker/Traits/SearchAutocompleteTrait.php, tests/Traits/SearchAutocompleteTraitTest.php
Fixes http://tickets.pm4overflow.com/tickets/359
=> Hide system processes from advanced search

resources/js/components/SelectUserGroup.vue
Fixes [http://tickets.pm4overflow.com/tickets/336](http://tickets.pm4overflow.com/tickets/336)
Code that added an empty element to the list of groups and users has been removed
=> ticket 336: task assignment left an empty box when the assigned user/group is deleted

ProcessMaker/Http/Controllers/Auth/ClientController.php
Fixes http://tickets.pm4overflow.com/tickets/369
=> Add missing param in oauth client create call

resources/js/processes/modeler/components/inspector/TaskAssignment.vue, resources/js/processes/modeler/initialLoad.js
Resolves: http://tickets.pm4overflow.com/tickets/488
Fix duplicated option in Assignment.
=> Fix duplicated option in Assignment

ProcessMaker/Managers/TaskSchedulerManager.php
Fixes [http://tickets.pm4overflow.com/tickets/487](http://tickets.pm4overflow.com/tickets/487)
- Adds a catch/try block for every processed task so if one fails the next ones are still executed
- When a task fails contextual information of the task is logged.
=> ticket 487: If a scheduled task fails the rest of the queue is not executed.

resources/views/admin/users/list.blade.php
Fix field name from "size" to "status"
=> Fix Status field name

resources/js/processes/scripts/components/ScriptEditor.vue
The response was not arriving to script editor.
=> Script Editor: Fix test script response

resources/js/components/SelectUserGroup.vue
Fixes http://tickets.pm4overflow.com/tickets/501
=> Add inactive indicator to users and groups

resources/js/processes/categories/components/CategorySelect.vue, resources/views/processes/list.blade.php, resources/views/processes/screens/list.blade.php, resources/views/processes/scripts/list.blade.php
Fixes http://tickets.pm4overflow.com/tickets/554
=> Refactor category select to fix resetting to Uncategorized

ProcessMaker/Http/Controllers/Auth/LoginController.php, tests/Feature/AuthTest.php
Fixes http://tickets.pm4overflow.com/tickets/557
=> Go back to login with error if user is not found

ProcessMaker/Traits/MakeHttpRequests.php
This PR fixes params replacements in DataConnectors.
Requires: https://github.com/ProcessMaker/package-data-sources/pull/180
Requires: https://github.com/ProcessMaker/screen-builder/pull/1038
https://user-images.githubusercontent.com/8028650/129282109-45d11006-6c2c-43e7-8b72-b5d5a273b5b6.mp4
PROCESS: [Test DataConnector.json.txt](https://github.com/ProcessMaker/processmaker/files/6979034/Test.DataConnector.json.txt)
COLLECTION: [persons.json.txt](https://github.com/ProcessMaker/processmaker/files/6979036/persons.json.txt)
Notes to test:
- Make sure you add `pmql` as a non required parameter into the ListAll endpoint
- Make sure the body of the creation and update endpoints have the following body:
```
{
"data": {
"dni": "{{dni}}",
"name": {
"first": "{{first}}",
"last": "{{last}}"
}
}
} …
```
=> Fix params replacements and output mapping

ProcessMaker/Console/Commands/Install.php
1. Run the installer
2. Confirm database and data-database config are the same
=> Comment out data database in installer

resources/js/components/requests/notifications.vue
Fixes http://tickets.pm4overflow.com/tickets/607
- Prevents redirecting until the api call to remove the notification has finished
=> Do not redirect until notification is removed

resources/views/admin/users/edit.blade.php
Fixes [ticket 499](http://tickets.pm4overflow.com/tickets/499)
- change options in props
=> Setting prop "options" to an object is deprecated. Use the array format instead

ProcessMaker/Http/Controllers/Api/NotificationController.php
Resolves: [http://tickets.pm4overflow.com/tickets/622](http://tickets.pm4overflow.com/tickets/622)
=> ticket 622: DocumentationTest Failing

ProcessMaker/Http/Controllers/Admin/UserController.php, ProcessMaker/Http/Controllers/ProfileController.php, resources/lang/en.json
Part of fix for [http://tickets.pm4overflow.com/tickets/627](http://tickets.pm4overflow.com/tickets/627)
- Fixed the capitalization of uses statuses in Edit User section.
- Fixed the capitalization of uses statuses in Edit Profile section.
=> Ticket-627: User Edit - Status Drop Down

ProcessMaker/Models/Process.php, resources/js/processes/components/ProcessesListing.vue, resources/js/processes/modeler/components/inspector/TaskNotifications.vue, resources/lang/en.json
Fixes http://tickets.pm4overflow.com/tickets/634
Adds a warning in the process list if the process manager is not set
=> Add warning if the process manager is not set

ProcessMaker/Policies/ProcessVersionPolicy.php, database/factories/ProcessRequestFactory.php
Fixes failing tests from https://github.com/ProcessMaker/processmaker/pull/3973
=> Add edit data policy and fix tests

resources/js/admin/settings/components/SettingsListing.vue
- Temporarily removes Settings import and export from the UI
- http://tickets.pm4overflow.com/tickets/698
=> Temporarily remove Settings import/export

resources/views/layouts/navbar.blade.php
As part of fixes to [http://tickets.pm4overflow.com/tickets/710](http://tickets.pm4overflow.com/tickets/710)
Aligns menu items div to left
=> ticket-710 [Dynamic UI 2] Multiple Menus 

ProcessMaker/Http/Controllers/Admin/CssOverrideController.php, resources/js/admin/cssOverride/components/SiteDesign.vue, resources/js/admin/cssOverride/edit.js, resources/views/admin/cssOverride/edit.blade.php, routes/web.php
- Adds support for Dynamic UI package to add extra tabs to Customize UI page
- https://github.com/ProcessMaker/package-dynamic-ui/pull/45
- http://tickets.pm4overflow.com/tickets/708
=> Ticket #708: Merge Customize UI and Dynamic UI

database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2021_09_10_132727_change_user_table_email_unique.php
Per Ellucian request:
I've remove the unique constraint on the user's table. This will allow for duplicate email address or no emails at all.
=> Removed unique constraint on the db table on install

ProcessMaker/Http/Controllers/Api/SettingController.php
Save upload file for private settings into storage folder
=> Saving upload files into storage folder

ProcessMaker/Models/User.php, tests/Feature/Api/UsersTest.php
Remove unique validation at User model
This PR is complementing #3993
=> Removing unique validator from User model

resources/js/processes/screen-builder/screen.vue
https://github.com/ProcessMaker/processmaker/pull/4013 for 4.1
=> Only show calcs button on form screens (4.1)

database/factories/ProcessRequestFactory.php, resources/js/components/common/mixins/datatable.js, resources/js/requests/components/RequestsListing.vue
Ref https://github.com/ProcessMaker/package-savedsearch/pull/264
https://github.com/ProcessMaker/processmaker/pull/4020 for 4.1
=> Handle json encoded rows in vuetable (4.1)

composer.json, package-lock.json, package.json
=> Processmaker 4.1.21-RC

package-lock.json, package.json
=> Modeler v1.18.1

composer.json, composer.lock, tests/Feature/Api/CallActivityTest.php, tests/Feature/Api/processes/ParentCallActivityBoundaryError.bpmn, tests/Feature/Api/processes/SubProcessWithError.bpmn
Requires: https://github.com/ProcessMaker/nayra/pull/206
- Tests of Activity (ScriptTask) exception catch by a boundary error event
https://user-images.githubusercontent.com/8028650/134944935-4beed5ba-e74d-4303-bd14-596aa1bab2ed.mp4
=> Test CallActivity catch error

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/RequestController.php, tests/Feature/Api/ProcessTest.php
Fix for [ticket #755](http://tickets.pm4overflow.com/tickets/755)
=> 4.1: Update ProcessController and ProcessRequestController so they use ProcessVersion when checking for 'cancel' permission

resources/views/auth/passwords/change.blade.php
Add password requirements to the password change screen.
=> Add password requirements

ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Policies/ProcessRequestPolicy.php, tests/Feature/Api/RequestFileUploadTest.php, tests/Feature/Api/processes/ViewFileUpload.bpmn
Fixes: http://tickets.pm4overflow.com/tickets/1042
Fixes: https://processmaker.atlassian.net/browse/FOUR-4126
- Replicates the issue: "This action is unauthorized" when displaying a file from a Self Service Task
- Add a permission to request files for a user assigned to a Self Service Task.
=> Fix permission denied on Self Service Tasks

resources/views/admin/users/edit.blade.php
Fixes part of https://processmaker.atlassian.net/browse/FOUR-4138 for 4.1
=> Removed space to fix translation issue - 4.1

resources/lang/en.json
Matching the PR changes to https://github.com/ProcessMaker/package-translations/pull/39
=> Updated en.json - 4.1

resources/js/processes/modeler/components/inspector/SignalPayload.vue, resources/lang/en.json
Fixes [ticket 1073](http://tickets.pm4overflow.com/tickets/1073)
- Add save signal payload
=> Signal Throw Config Not Working

ProcessMaker/Jobs/ExecuteScript.php
Fixes [Ticket 1092](http://tickets.pm4overflow.com/tickets/1092)
- Add attribute sync to watcher
=>  Watcher stops working, after adding record in the record list

resources/sass/app.scss
**Tickets:**
[1143](http://tickets.pm4overflow.com/tickets/1143) and [1145](http://tickets.pm4overflow.com/tickets/1145)
Added focus indicator for switch, input, select, multiselect, i, a custom file, pagination nav drop.
**Focus indicator screenshots:**
=> Task/Ticket-1143-1145: Added focus indicator for switch, inputs, select, multiselect, i, a

resources/js/bootstrap.js, resources/js/components/common/mixins/accessibility.js
=> Focus within a modal/popover when shown

resources/js/admin/script-executors/ScriptExecutors.vue, resources/views/admin/users/edit.blade.php, resources/views/admin/users/list.blade.php, resources/views/processes/list.blade.php, resources/views/processes/screens/list.blade.php, resources/views/processes/signals/index.blade.php
Ticket [1148](http://tickets.pm4overflow.com/tickets/1148)
- Adds / updates the aria labels for add (+) buttons throughout the platform.
- Adds missing aria labels for import buttons
<h2>Additional PRs for Ticket 1148</h2>
- https://github.com/ProcessMaker/package-data-sources/pull/201
- https://github.com/ProcessMaker/package-savedsearch/pull/280
- https://github.com/ProcessMaker/package-collections/pull/285
- https://github.com/ProcessMaker/package-vocabularies/pull/42
- https://github.com/ProcessMaker/package-dynamic-ui/pull/50
=> Add aria-labels to Add (+) Buttons

ProcessMaker/Notifications/ImportReady.php
Fixes [FOUR-3800](https://processmaker.atlassian.net/browse/FOUR-3800)
- Fix name process in notification import ready
=> Multiple copies of the process are create and import doen't finish

ProcessMaker/Jobs/CatchSignalEvent.php, ProcessMaker/Models/SignalEventDefinition.php, ProcessMaker/Providers/WorkflowServiceProvider.php, ProcessMaker/Repositories/DefinitionsRepository.php, composer.json, composer.lock, tests/Feature/Api/ProcessPatternsTest.php, tests/Feature/Api/bpmnPatterns/SignalWithCustomPayload.bpmn, tests/Feature/Api/bpmnPatterns/SignalWithCustomPayload.json, tests/Feature/Api/bpmnPatterns/SignalWithCustomPayload_Process2.bpmn
Fixes: http://tickets.pm4overflow.com/tickets/1075
Requires: https://github.com/ProcessMaker/nayra/pull/211
- Override `SignalEventDefinition::getPayloadData`
=> Fix Signal Throw event always send all request data

resources/views/tasks/edit.blade.php
Fixes [ticket 1140](http://tickets.pm4overflow.com/tickets/1140)
- Add alert error to submit task
=> Running a request with vocabulary does not have any announcement of restrictions

ProcessMaker/Traits/ExtendedPMQL.php, tests/Feature/ExtendedPMQLTest.php
Fixes Ticket [1209](http://tickets.pm4overflow.com/tickets/1209)
https://user-images.githubusercontent.com/90727999/140394388-e7db5431-258b-4de4-9c80-e462f4b79468.mov
=> Bugfix/ticket-1209: Fixed single char query in PMQL (FOR 4.2)

resources/js/processes/screen-builder/screen.vue
Ticket [FOUR-4325](https://processmaker.atlassian.net/browse/FOUR-4325)
https://user-images.githubusercontent.com/90727999/140958334-8f83a2dc-d33e-4525-affc-683388b8a73f.mov
=> Task/FOUR-4325: Revert changes, added by default calcs and customCss to display screens (FOR 4.2)

ProcessMaker/Traits/HasVersioning.php, tests/Feature/Api/ScriptsTest.php, tests/Resources/TaskTest.php, tests/Traits/HasVersioningTest.php
https://github.com/ProcessMaker/processmaker/pull/4139 for 4.1
=> Skip version locking for now

ProcessMaker/Http/Controllers/Api/ProcessController.php
Fixes https://processmaker.atlassian.net/browse/FOUR-3980
To test, export and re-import a process with a script task. Assign a user to the script on the page that shows up right after importing (NOT in the script config). Verify it runs.
=> Fix saving version, mass updates do not fire model events

config/app.php
https://github.com/ProcessMaker/processmaker/pull/4136 for 4.1
Requires:
https://github.com/ProcessMaker/package-actions-by-email/pull/52
https://github.com/ProcessMaker/connector-pdf-print/pull/47
Note: It's also used in connector-send-email but I added that as part of the SSR issue (https://github.com/ProcessMaker/connector-send-email/pull/190)
=> Add config for system script timeouts

resources/js/processes/screen-builder/screen.vue
Ticket [FOUR-4325](https://processmaker.atlassian.net/browse/FOUR-4325)
https://user-images.githubusercontent.com/90727999/141809596-73b5b47b-1fd1-4f8c-8875-f0671d1e49d4.mov
=> Task/FOUR-4325: Revert changes, added by default calcs and customCss to display screens (FOR 4.1)

resources/js/processes/modeler/initialLoad.js
Fixes [FOUR-4405](https://processmaker.atlassian.net/browse/FOUR-4405)
- Add register of summary on signal end event
=> Signal End Event Missing Summary Screen

ProcessMaker/Traits/MakeHttpRequests.php
Fixes [FOUR-4333](https://processmaker.atlassian.net/browse/FOUR-4333)
- Change value data for mustache
=> Data connector task does not save the information the outbound configuration.

ProcessMaker/Http/Controllers/Api/SignalController.php
Ticket: [FOUR-4465](https://processmaker.atlassian.net/browse/FOUR-4465)
https://user-images.githubusercontent.com/90727999/142072798-f744c3e9-50ea-4da8-b140-32ea7deffe9f.mov
=> Bugfix/FOUR-4465: Fixed pagination in signals

resources/views/profile/edit.blade.php
=> fixing a bug in "profile/edit.blade.php" in arabic language

resources/js/requests/components/RequestsListing.vue
Ticket [FOUR-4401](https://processmaker.atlassian.net/browse/FOUR-4401)
=> Bugfix/FOUR-4401: Nowrap request id in request listing

ProcessMaker/Helpers/SettingsHelper.php, ProcessMaker/Models/Setting.php, ProcessMaker/Observers/SettingObserver.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, ProcessMaker/Providers/SettingServiceProvider.php
Adds a layer of caching for settings. Resolves ticket [FOUR-4418](https://processmaker.atlassian.net/browse/FOUR-4418).
Related PR:
https://github.com/ProcessMaker/connector-send-email/pull/191
=> [4.2] Settings/config caching

package-lock.json, package.json
Reverts ProcessMaker/processmaker#4144
=> Revert "Bump axios from 0.21.1 to 0.21.2"

ProcessMaker/Http/Controllers/TaskController.php, ProcessMaker/Models/ProcessRequest.php, resources/lang/en.json, resources/views/requests/show.blade.php, tests/Resources/TaskTest.php
Part of https://github.com/ProcessMaker/screen-builder/pull/1113
=> Updates for multi-file screen controls

ProcessMaker/Http/Controllers/RequestController.php, resources/views/tasks/edit.blade.php, routes/web.php
See https://github.com/ProcessMaker/screen-builder/pull/1118
=> Redirect interstitial tasks from sub processes

ProcessMaker/Http/Controllers/Auth/ResetPasswordController.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php
**Issue 1**
Wrong title in **Password reset** view. 
- Go to login > Forgot your password?
- Enter your email address
- You will receive an email with a reset link
- Click on the link and you will redirect to a page to change password, look at the title you will see Welcome : name
**Issue 2**
Wrong title in **Forgot your password** view. 
- Go to login > Forgot your password?
- Look at the title, you will see Welcome : name
- Added a custom showResetForm method in ResetPasswordController to get the current username.
- Added the correct title for both issues.
Same as described in Issue & Reproduction Steps, you will see:
**For Issue 1:** Welcome <your_username> - ProcessMaker
**For Issue 2:** Forgot Your Password? - ProcessMaker 
- …
=> Bugfix/FOUR-4811: Password reset page has "Welcome, :name" in the title

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Jobs/ExportProcess.php, tests/Feature/Processes/ExportImportTest.php, tests/storage/process/test_process_import_different_tasks_assignments.json
**Issue 1:**
When you import a process that have a task with assignment rules configured as **User By Id** with some value, that ID value is lost after importing.
- Create a process with a task
- Select **By User Id** in Assignment Type select under Assignment Rules and in Variable name add some User ID
- Save and then export the process
- Import the process
- Go to edit the process and see the variable name is missing.
**Issue 2:**
When you import a process that have a task with assignment rules configured as **Users / Groups** with some user, the Assignment type select not selecting **User/Groups** option after importing.
- Create a process with a task
- Select **Users / Groups** in Assignment Type select under Assignment Rules and select some User
- Save and then export the process
- …
=> Bugfix/FOUR-4810: When I import a process that has assignment rules by user ID, the variable is lost in the configuration

resources/views/processes/signals/edit.blade.php
- Go to edit a signal
- Check the toggle **Enable Webhook access**
- Pay attention to the border missing in Accepted Form Fields section
- Pay attention to the border missing in Restrict Access From section
- Pay attention to the background color on the footer (where are buttons Cancel and Confirm and Save)
- Pay attention to the text **Security configuration**
UI changes to fit the PRD UI
- Go to edit a signal
- Check the toggle **Enable Webhook access**
- **---> Pay attention to the PRD Image in the ticket [FOUR-4869](https://processmaker.atlassian.net/browse/FOUR-4869) <---**
- Pay attention to the border in Accepted Form Fields section
- Pay attention to the border in Restrict Access From section
- Pay attention to the background color on the footer (where are buttons Cancel and …
=> Bugfix/FOUR-4869: Signal Webhook UI to fit PRD

resources/lang/en.json
Fixes https://processmaker.atlassian.net/browse/FOUR-3773
=> Grammatical fix for task escalation

ProcessMaker/Http/Controllers/Api/TaskController.php, composer.json, package.json
See https://processmaker.atlassian.net/browse/FOUR-5864
=> Filter request id exactly instead of with 'like'

resources/views/layouts/layout.blade.php
As a cloud ops engineer, I want the ability to add HTML to the head tag of the global app instance so that clients/solutions engineers who request it can have custom HTML in their instance. This will allow for things like CSS modifications and script injections for analytics platforms.
In order to accommodate this, we will allow for manual creation of a global_header setting in the settings table that will allow HTML to be entered. We will then add the global_header output to our primary layout blade template.
1. Visit the settings table in your database
2. Add a row with a key of `global_header`, a format of `text` and a config with your preferred HTML code in it
3. Run `php artisan optimize:clear`
4. Refresh any logged-in ProcessMaker page and view its source to see if the code you …
=> Allow global additions to HTML head tag

ProcessMaker/Http/Controllers/Api/FileController.php
See https://processmaker.atlassian.net/browse/FOUR-5992
=> Fix base controller

package-lock.json
- `package-lock.json` file was invalid and it was causing some issues while doing any npm tasks
- Deleted package-lock.json and redid the file to match spec file version 1 since looking at the git version history, somebody committed a spec version 2 and the syntax is quite different
- Make sure everything works accordingly, a smoke test would be nice.
- https://processmaker.atlassian.net/browse/FOUR-6016
- [] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
=> FOUR-6016 Resetted the package-lock.json file 

config/filesystems.php
unable to view file with file preview component or download with fie download component.
- a new folder has been created for saving
create form with upload file, file preview and file download.
- test run case
- test create record in package collection
- test create request in package webentry
- [FOUR-5624](https://processmaker.atlassian.net/browse/FOUR-5624)
=> Image Uploaded through web entries is not available for download or preview

config/filesystems.php
Require to store the web services files like WSDL, XSD, etc.
- https://processmaker.atlassian.net/browse/FOUR-6385
=> Create local storage disk for web services

ProcessMaker/Contracts/SoapClientInterface.php, ProcessMaker/Contracts/WebServiceCallerInterface.php, ProcessMaker/Factories/SoapClientFactory.php, ProcessMaker/Managers/WebServiceSoapRequestBuilder.php, ProcessMaker/Managers/WebServiceSoapServiceCaller.php, ProcessMaker/Providers/WorkflowServiceProvider.php, ProcessMaker/Soap/NativeSoapClient.php, tests/Feature/WebServiceSoapServiceCallerTest.php, tests/Fixtures/WithServicePort.wsdl, tests/unit/ProcessMaker/Managers/WebServiceSoapRequestBuilderTest.php
Implement the foundation for WS Security functionality
- Implement the foundational classes and interfaces for WS Security.
Run the unit tests added.
- https://processmaker.atlassian.net/browse/FOUR-6338
=> Implement the foundation for WS Security functionality

resources/sass/app.scss
Select List and signature controls, still mark in red, the validation of the required field
1. Go to admin
2. Open Customize UI
3. Select a color different to red in "Danger" option
4. Save the changes
5. Create a Screen
6. Add controls like(line input, textarea, select list, signature)
7. Add Required validation in each control
8. Press preview button
- Added styles that use the dynamic custom colors.
- Compile assets, please run `npm link` for screen builder and vue-form-elements.
- Install `package-signature`
- [FOUR-6101](https://processmaker.atlassian.net/browse/FOUR-6101)
- [Screen Builder PR](https://github.com/ProcessMaker/screen-builder/pull/1229)
- [Vue Form Elements PR](https://github.com/ProcessMaker/vue-form-elements/pull/340)
- [Package Signature …
=> Bugfix FOUR-6101 - Error validations are not marked with the color selected in Customize UI (Core)

ProcessMaker/Contracts/SoapClientInterface.php, ProcessMaker/Managers/WebServiceSoapConfigBuilder.php, ProcessMaker/WebServices/NativeSoapClient.php, ProcessMaker/WebServices/WebServiceRequest.php, tests/Feature/WebServiceRequestTest.php
=> Soap integrate

ProcessMaker/ScriptRunners/MockRunner.php, phpunit.xml, tests/Feature/AuthTest.php, tests/Feature/Docker/TimeoutsTest.php
Fix failing tests (original cicd pipeline)
Fixes https://processmaker.atlassian.net/browse/FOUR-6302
=> Fix unit test config

ProcessMaker/Managers/WebServiceSoapConfigBuilder.php, ProcessMaker/WebServices/WebServiceRequest.php
=> SOAP Integration

ProcessMaker/Helpers/SettingsHelper.php, ProcessMaker/Jobs/GenerateUuidsForTable.php, ProcessMaker/Traits/HasUuids.php, config/app.php
Support PR for https://github.com/ProcessMaker/package-collections/pull/310.
=> Support PR for FOUR-5990

composer.json, composer.lock
=> Version 4.2.32-RC2

composer.json, composer.lock
Previous versions of Guzzle (<=6.5.5) and (>=7.0.0,<=7.4.2) contain a vulnerability with the cookie middleware. See full [security advisory here](https://github.com/guzzle/guzzle/security/advisories/GHSA-cwmx-hcrq-mhc3).
Note that the cookie middleware is **disabled by default**, so most library consumers will not be affected by this issue. Only those who manually add the cookie middleware to the handler stack or construct the client with `['cookies' => true]` are affected.
- Upgrade to Guzzle >=6.5.6 or >=7.4.3.
- After reviewing Core, I noticed there are no places in code where Guzzle is used and specifically where `['cookies' => true]` is set. If you consider a test example for some use case we can discuss it to create some test.
- Package Auth and Package Data Sources define …
=> FOUR-6312 - Update guzzle (cross-domain cookie leakage)

composer.json, package-lock.json, package.json
=> Version 4.2.33

ProcessMaker/Helpers/SettingsHelper.php
Even though this branch's name is bugfix/FOUR-6579, the actual ticket this is resolving is [FOUR-6585](https://processmaker.atlassian.net/browse/FOUR-6585).
- Set core to this PR's branch, bugfix/FOUR-6579.
- Set package-webentry to this branch, patch-1-cartegraph.
- Set package-collections to patch-1-cartegraph.
- Set package-savedsearch to patch-1-cartegraph.
- Have or create a collection with records
- Configure the collection
- Create a saved search for the collection
- Run php artisan config:cache
- Configure the collection with the option Use Randomly-Generated IDs for Links checked
- Save your changes
- Go to saved search and try to view a record
The collection's configuration on whether or not to use the UUID is not working after saving (you have to save twice to make it work). …
=> FOUR-6579: Refactor the settings caching logic

resources/sass/sidebar/sidebar.scss
Ticket: [FOUR-6567](https://processmaker.atlassian.net/browse/FOUR-6567)
In the sidebar menu of ProcessMaker, the `nav-link` icon container height is inconsistent across the platform. There are instances where the `nav-link` height is 34px instead of 43px, so the sidebar menu icons appear smaller. Note: the width of the `nav-link` container is set to 58px and does not change.
The sidebar `nav-link` height attribute has been set to 43px.
1. Update core branch to `bugfix/FOUR-6567`.
2. Go to ProcessMaker → Admin.
3. Click on the Users icon in the sidebar menu and inspect the size of the icon container. The icon container, which has the `a.nav-link` class, should have dimensions of 58 x 43. 
4. Click on the Groups icon in the sidebar menu and inspect the size of the icon container. The icon …
=> FOUR-6567: Sidebar nav-item container's height changes when viewing Admin/Users

ProcessMaker/ImportExport/DependentType.php, ProcessMaker/ImportExport/Exporter.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/ImportExport/Exporters/ScreenExporter.php, ProcessMaker/ImportExport/Exporters/ScriptCategoryExporter.php, ProcessMaker/ImportExport/Exporters/ScriptExporter.php, tests/Feature/ImportExport/ExportEncryptedTest.php, tests/Feature/ImportExport/ExporterTest.php
Lets build out the ScreenExporter class `ProcessMaker/ImportExport/Exporters/ScreenExporter.php`.
- Added nested screens 
- Added watcher scripts
- Run `phpunit --filter testExportScreen tests/Feature/ImportExport/ExporterTest.php`
- [FOUR-6729](https://processmaker.atlassian.net/browse/FOUR-6729)
=> FOUR 6729 - Build out ScreenExporter class

tests/Feature/BroadcastTest.php, tests/bootstrap.php
We need to skip additional tests to get CI passing
https://github.com/ProcessMaker/package-collections/pull/330
https://github.com/ProcessMaker/package-webentry/pull/165
ci:package-webentry:bugfix/FOUR-6661
ci:package-collections:bugfix/FOUR-6709
=> Skip additional tests

resources/js/processes/export/components/ExportManagerView.vue, resources/js/processes/export/index.js, resources/views/processes/export.blade.php
Ticket: [FOUR-6733](https://processmaker.atlassian.net/browse/FOUR-6733)
The main process export page `processes/{processId}/export` needs to be updated to match the new design specified by the Import/Export [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2719481999/PRD+PM4+Export+Import#New-Designer-View.).
Update Export Process main page to include flows for Basic and Custom exports.
1. Update core branch to `bugfix/FOUR-6733`.
2. Go to ProcessMaker -> Designer -> Export a Process
3. Export Page styling should match [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2719481999/PRD+PM4+Export+Import#New-Designer-View.).
4. Basic Export should be selected by default.
5. Selecting Basic Export should take you to a Set Password Modal.
6. **Note:** Selecting Custom …
=> FOUR-6733: Import/Export | Update Export Process Main Page

ProcessMaker/Http/Controllers/Api/ExportController.php, ProcessMaker/Http/Requests/ImportExport/ExportRequest.php, ProcessMaker/ImportExport/Exporter.php, ProcessMaker/ImportExport/Exporters/ExporterBase.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/ImportExport/Utils.php, routes/api.php, tests/Feature/ImportExport/Api/ExportImportTest.php, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php, tests/Feature/ImportExport/HelperTrait.php
Work with Frontend team to review the PRD and identify methods and payloads
Added additional changes for export endpoint.
- Changed from GET to POST.
- Updated post params.
- Added `export-info` response headers.
- Review code `phpunit tests/Feature/ImportExport/Api/ExportImportTest.php`.
- [FOUR-6753](https://processmaker.atlassian.net/browse/FOUR-6753)
=> FOUR-6753 - Update download export file endpoint

resources/js/processes/screen-builder/screen.vue
Preview Data in Screen Builder is refreshing many times when a input changes.
Delay and debounce the refresh of data preview
- Open a large screen with multiple controls (see attached example)
- Go to Preview
- Focus on a input text
- Type
- Notice that the browser gets slow
**Previous performance:**
https://user-images.githubusercontent.com/8028650/191995743-8d2824c5-8142-4cab-9218-31250c9ede97.mp4
**Improved performance**
https://user-images.githubusercontent.com/8028650/191995888-b377cd05-d796-43a4-8373-6d8e6e5014ea.mp4
- Example Screen
[RAOS 1.0.0 - People 2.zip](https://github.com/ProcessMaker/processmaker/files/9634796/RAOS.1.0.0.-.People.2.zip)
Test Data:
```
{
"_user": {
"id": 3,
"email": "solutions+banker@processmaker.com",
"firstname": "Briana",
"lastname": "Banker",
"username": …
```
=> Delay refresh preview data

config/app.php, resources/js/bootstrap.js, resources/views/layouts/layout.blade.php
We don't have a GET endpoint to get the data from DataSources.
Implement a GET endpoint to get the data from DataSources.
Call to the endpoint GET `/api/1.0/requests/data_sources/{data_source_id}/resources/{endpoint}/data?...`
- Create a screen with a SelectList that gets data from DataSources
- Preview it
- Requires: https://github.com/ProcessMaker/screen-builder/pull/1260
- Requires: https://github.com/ProcessMaker/package-data-sources/pull/245
- https://processmaker.atlassian.net/browse/FOUR-6833
=> Four-6833 Endpoint to get data from DataSources

README.md
In order for people to download the application and install it, the installation guide needs to be revised.
Updating the application installation guide.
- Download the [source code](https://github.com/ProcessMaker/processmaker/releases/tag/v4.3.0-RC1).
- Follow the installation instructions
There is another bug that can cause an error during installation (`php artisan processmaker:install`).
[FOUR-6875](https://processmaker.atlassian.net/browse/FOUR-6875)
- [FOUR-6876](https://processmaker.atlassian.net/browse/FOUR-6876)
=> FOUR-6876: Updating the application installation guide

ProcessMaker/Traits/MakeHttpRequests.php, tests/Feature/MakeHttpRequestTest.php, tests/Feature/WebServiceSoapTest.php
Fixes https://processmaker.atlassian.net/browse/FOUR-6882
Note :
To test run unit tests inside PM Core directory and execute:
`phpunit tests/Feature`
ci:package-data-sources:bugfix/FOUR-6882
=> FOUR-6882: Data Sources: some tests are failing

ProcessMaker/Models/ProcessMakerModel.php, ProcessMaker/WebServices/NativeSoapClient.php, ProcessMaker/WebServices/SoapConfigBuilder.php, ProcessMaker/WebServices/SoapRequestBuilder.php, ProcessMaker/WebServices/WebServiceRequest.php, database/factories/ProcessMaker/Models/SettingFactory.php, tests/DuskTestCase.php
Fix formatting issues with php-cs-fixer
- run php-cs-fixer
=> Formatting Updates

config/app.php, resources/js/bootstrap.js, resources/js/processes/screen-builder/main.js, resources/js/processes/screen-builder/screen.vue, resources/views/layouts/layout.blade.php
Cherry-picked commits to bring requested screen builder changes into 4.2.36-RC1.
- https://github.com/ProcessMaker/package-data-sources/pull/248
- https://github.com/ProcessMaker/package-webentry/pull/171
- https://github.com/ProcessMaker/screen-builder/pull/1268
- https://github.com/ProcessMaker/vue-form-elements/pull/356
- https://processmaker.atlassian.net/browse/RM-1511
=> [RM-1511] ProcessMaker 4.2.36

webpack.mix.js
Ticket [FOUR-6987](https://processmaker.atlassian.net/browse/FOUR-6987)
- Object Event Error in screen and console when attempting to edit a formula within a screen calc.
- 404 when calling Typescript
- Added Typescript to webpack.mix.js
- Create a Screen Form
- Put date in the name of the date picker
- Create a calc with the next code 
```
var currentdate = new Date(); 
var datetime = (currentdate.getDate() < 10 ? '0' : '') + currentdate.getDate() + "-"
+ ((currentdate.getMonth()+1) < 10 ? '0' : '') + (currentdate.getMonth()+1) + "-" 
+ currentdate.getFullYear() + " "  
+ (currentdate.getHours() < 10 ? '0' : '') + currentdate.getHours() + ":"  
+ (currentdate.getMinutes() < 10 ? '0' : '') + currentdate.getMinutes()
return datetime;
```
- Save the changes
- Edit the calc 
- Click on the …
=> FOUR-6987: Object Event Error in Date Picker with calc

ProcessMaker/Models/Process.php, ProcessMaker/Models/TokenAssignableUsers.php, resources/js/requests/components/RequestDetail.vue
1. Create any process or import the attached process.
2. Select the task in modeler and configure as "Self service" in “Assignment Rules”.
3. Add a group in "Assignment User/Group".
4. Start a request to the process.
5. Login with a user of the group assigned to the task.
6. Go to the "task" tab.
7. Go to the "Self Service" option of the sidebar menu.
8. Click on the request number.
- improvement method for load users' assignments.
The user assigned could claim cases.
see also
https://processmaker.atlassian.net/browse/FOUR-6777
- https://processmaker.atlassian.net/browse/FOUR-6946
=> User assignment load improvement

ProcessMaker/ImportExport/DependentType.php, ProcessMaker/ImportExport/Exporters/GroupExporter.php, ProcessMaker/ImportExport/Exporters/UserExporter.php, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php
These changes were not added to FOUR-6570 when merged the last commit.
- Created a new branch from FOUR-6570
- Added the changes and push
vendor/bin/phpunit tests/Feature/ImportExport/Exporters/ProcessExporterTest.php
=> Added fixes to FOUR-6570

.github/workflows/codeball.yml
Add a GitHub action to implement [Codeball artificial intelligence code reviews](https://codeball.ai) to all PRs.
=> Add Codeball AI reviews

README.md
Resolves [https://processmaker.atlassian.net/browse/FOUR-7349](https://processmaker.atlassian.net/browse/FOUR-7349)
=> Update MySql requirement to 8.0

.eslintrc.js, .gitignore, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Http/Controllers/Process/ScreenBuilderController.php, ProcessMaker/Http/Controllers/Process/ScriptController.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessVersion.php, ProcessMaker/Models/ScreenVersion.php, ProcessMaker/Models/ScriptExecutorVersion.php, ProcessMaker/Models/ScriptVersion.php, ProcessMaker/PackageHelper.php, ProcessMaker/Traits/HasVersioning.php, database/migrations/2023_02_27_130520_add_draft_column_to_versions_tables.php, resources/js/components/Menu.vue, resources/js/processes/modeler/components/ModelerApp.vue, resources/js/processes/screen-builder/screen.vue, resources/js/processes/scripts/components/ScriptEditor.vue, resources/views/processes/modeler/index.blade.php, resources/views/processes/screen-builder/screen.blade.php, resources/views/processes/scripts/builder.blade.php, routes/api.php, tests/Feature/Api/ProcessTest.php, tests/Feature/Api/ScreenTest.php, tests/Feature/Api/ScriptsTest.php, tests/Feature/Api/UsersTest.php
This PR is based on:
- https://github.com/ProcessMaker/processmaker/pull/4627 Autosave Process branch.
- https://github.com/ProcessMaker/processmaker/pull/4636 Autosave Script branch.
Adds autosave feature for Screen designer.
-  Create draft version.
-  Load draft version.
- Added discard functionality (Close button).
- Display "Saved Notification" on draft update.
- `php artisan test tests/Feature/Api/ScreenTest.php --filter testUpdateScreen`
- `php artisan test tests/Feature/Api/ScreenTest.php --filter testCloseDraftScreen`.
- Execute a manual test by linking Package Version and Screen Builder in Core.
- [FOUR-7336](https://processmaker.atlassian.net/browse/FOUR-7336)
- [Package Versions PR](https://github.com/ProcessMaker/package-versions/pull/58)
- [Screen Builder …
=> FOUR-7336 - Autosave Screen

resources/js/admin/settings/components/SettingChoice.vue, resources/js/admin/settings/components/SettingSelect.vue, resources/js/admin/settings/components/SettingsListing.vue
[FOUR-7499](https://processmaker.atlassian.net/browse/FOUR-7499) based on the [IDP Connector PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3035955201/ProcessMaker+IDP+Connector?atlOrigin=eyJpIjoiYWIzOTMwYmQ4MjJmNDI2NTkwNDdhYWI4YjllYTEyZGMiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) users will need to be able to select options from a dropdown list in the settings table
- This PR adds a 'SettingsSelect' component that can be used to populate a multi select field in the settings table.
- Install the IDP Connector
- Under Admin > Settings > IDP configure your IDP connection
- Authorize your account
- Navigate back to the Admin > Settings > IDP tab
- Edit the 'Select Available Folders' config
- Configure the select list
- 
The select is is configurable with no …
=> Add Select list field to settings table

resources/views/tasks/edit.blade.php
the steps are in the ticket
the problem is that the task in selfservice can be reassigned
- Add validation in seccion reassign
create process selfservice
create a request
the task in selfservice should not be able to be reassigned
https://user-images.githubusercontent.com/1747025/229132470-de6f2ecc-f631-404f-91d5-e82a211790ef.mp4
- [FOUR-7150](https://processmaker.atlassian.net/browse/FOUR-7150)
[FOUR-7150]: https://processmaker.atlassian.net/browse/FOUR-7150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The task should not be Selfservice to be able to reassign.

resources/js/components/shared/Modal.vue, resources/js/components/templates/CreateTemplateModal.vue, resources/js/components/templates/TemplateDetails.vue, resources/js/components/templates/TemplateSearch.vue, resources/js/components/templates/TemplateSelectCard.vue
Ticket: [FOUR-7923](https://processmaker.atlassian.net/browse/FOUR-7923)
The Publish Template and Use Template modals require a few UI adjustments
UI Updates
[FOUR-7923]: https://processmaker.atlassian.net/browse/FOUR-7923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-7923: Process Template Modal UI Tweaks

ProcessMaker/Ai/Handlers/OpenAiHandler.php, ProcessMaker/Ai/Prompts/nlq_to_pmql_collections.md, ProcessMaker/Ai/Prompts/nlq_to_pmql_collections_w_mustaches.md, ProcessMaker/Ai/Prompts/nlq_to_pmql_processes.md, ProcessMaker/Http/Controllers/Api/OpenAIController.php, ProcessMaker/Models/AiSearch.php, ProcessMaker/Models/Process.php, database/migrations/2023_04_11_184245_add_user_id_to_ai_searches_table.php, database/migrations/2023_04_11_191032_add_soft_deletes_to_ai_searches_table.php, resources/js/components/shared/GlobalSearch.vue, resources/js/components/shared/PmqlInput.vue, resources/js/processes/archived.js, resources/js/processes/components/ProcessesListing.vue, resources/js/processes/index.js, resources/views/processes/list.blade.php, routes/api.php
Global AI search
- [FOUR-7864](https://processmaker.atlassian.net/browse/FOUR-7864)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/4680)
- [Screen builder PR](https://github.com/ProcessMaker/screen-builder/pull/1361)
- Bugfixes
- Clear history funcitonality
- Make history per user
- Persist search across pages after submit search
- Add an X to the search bar to remove the session
- Reduce animation for text in popup
- Added PmqlInput in dependent selects
- Added support to mustaches PmqlInput for dependent selects
[FOUR-7864]: https://processmaker.atlassian.net/browse/FOUR-7864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Epic/FOUR-7864: Global AI search

README.md
=> Update CI/CD Info in Readme

resources/js/components/templates/TemplateSearch.vue
Ticket: [FOUR-8311](https://processmaker.atlassian.net/browse/FOUR-8311)
The "Create Process" modal is currently displaying only the first 10 process templates, which is a limitation. As a result, users are unable to see all available process templates. We need to update the functionality to display all process templates as expected.
To reproduce: 
1. Have more than 10 process templates created
2. Open the Create Process modal
All process templates should be available to see by the user
Limitation of 10 process templates display.
- Increase process template page limit
1. Have more than 10 process templates created
2. Open the Create Process modal
3. Ensure all process templates are displayed …
=> Increase process template page limit

resources/js/components/templates/TemplateDetails.vue
Please see details in the ticket https://processmaker.atlassian.net/browse/FOUR-8359
- Added changes detailed in the ticket
**How looks now:**
- Go to processes 
- Select new process
- Click on some template
- The template detail modal popup
- Compare the changes with the ticket
- [FOUR-8359](https://processmaker.atlassian.net/browse/FOUR-8359)
[FOUR-8359]: https://processmaker.atlassian.net/browse/FOUR-8359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-8359: Template Details Modal UI Adjustments

resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
Reverts ProcessMaker/processmaker#4743. Caused strange issues when integrated into develop.
=> Revert "Fix url matchers for loading screen"

ProcessMaker/Events/TokenCreated.php, ProcessMaker/Events/TokenDeleted.php, ProcessMaker/Http/Controllers/Api/UserTokenController.php, ProcessMaker/Providers/EventServiceProvider.php, tests/Feature/BroadcastTest.php
N/A
N/A
- Go to admin
- Select edit an user
- Go to groups tab
- Create or Delete a Token
- Check the security_logs table for a new log "tokenCreated" or "tokenDeleted"
https://processmaker.atlassian.net/browse/FOUR-8233
ci:deploy
=> FOUR-8233: changes in Tokens

resources/js/processes/screen-builder/screen.vue
See https://github.com/ProcessMaker/screen-builder/pull/1375
=> Required Field Display Improvements

composer.json, composer.lock
TBD
- https://processmaker.atlassian.net/browse/FOUR-8059
=> Error handling / Fault Tolerance v1

ProcessMaker/Traits/PluginServiceProviderTrait.php, routes/api.php, routes/web.php
Rearrange and optimize the engine routes.
- Group the engine routes
- Fix invalid route names
- Remove old non required package version code
=> Rearrange engine routes

resources/js/admin/settings/components/SettingsGroups.vue
N/S
N/A
N/A
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-8236)
ci:deploy
=> FOUR-8236: Log Any changes CREATE DELETE UPDATE to Setting - Email Server

resources/js/processes/modeler/components/ModelerApp.vue
feature to attach process optimization package into the modeler
- package will be register with two components (button and panel)
- because the validation bar was removed, panel component will be mounted in the ModelerApp  main component
- switch to feature/FOUR-8726 branch the projects processmaker, modeler and package-process-optimization
- build the  assets
- install the package process optimization
- open the modeler
- https://processmaker.atlassian.net/browse/FOUR-8726
=> FOUR-8726: Move Check Process to the top and encapsulate results analisis

ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php
Includes:
- Implementation of ScriptTask execution
- Pass environment variables
- https://github.com/ProcessMaker/nayra-docker/pull/6
- https://github.com/ProcessMaker/docker-executor-php/pull/20
=> FOUR-8555 Refactor runScriptTask function to use Nayra BPMN engine

resources/sass/app.scss
The styles have broken on the simple error message screen.
=> FOUR-8982 Fix interstitial error message

ProcessMaker/Jobs/RunScriptTask.php, ProcessMaker/Models/Script.php, ProcessMaker/Notifications/ErrorExecutionNotification.php, ProcessMaker/Traits/MakeHttpRequests.php, resources/js/processes/modeler/components/inspector/NotifyProcessManager.vue, resources/js/processes/modeler/initialLoad.js, resources/lang/en.json, resources/sass/app.scss, tests/Feature/Processes/ErrorExecutionNotificationTest.php, tests/Fixtures/ScriptWithErrorHandling.bpmn
This PR includes the updates completed in IT3 for Error Handling
- Error Notifications: https://processmaker.atlassian.net/browse/FOUR-8062
ci:package-data-sources:feature/FOUR-8059
=> IT4 Error Handling / Fault Tolerance Updates

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/js/processes/modeler/components/ProcessMapTooltip.vue, resources/views/requests/show.blade.php, routes/web.php
We change the permission to view all request. We add the request to the parameters. 
=> FOUR-9127  In-Flight Process Map has an incorrect permission

.github/workflows/deploy-pm4.yml
=> Update GitHub Actions

resources/js/admin/users/components/SecurityLogsModal.vue
Define the order to show the fields
- FOUR-9010
ci:deploy
ci:package-data-sources:feature/FOUR-8121
ci:package-translations:feature/FOUR-8121
ci:package-vocabularies:feature/FOUR-8121
ci:connector-send-email:feature/FOUR-8121
ci:package-webentry:feature/FOUR-8121
ci:package-decision-engine:feature/FOUR-8121
ci:package-dynamic-ui:feature/FOUR-8121
ci:package-savedsearch:feature/FOUR-8121
ci:package-pm-blocks:feature/FOUR-8121
ci:package-collections:feature/FOUR-8121
ci:package-files:feature/FOUR-8121
=> FOUR-9010: Define the order to show the fields

composer.json, composer.lock
=> 4.7.0 Alpha 4

resources/js/components/pm-blocks/CreatePmBlockModal.vue
Ticket: [FOUR-9033](https://processmaker.atlassian.net/browse/FOUR-9033)
As a Block author, I want to add a value for Author, Version and Version Date to my Blocks, so that users can understand where their block comes from and how recent the block is.
The Block Author and Version fields should be part of the main Configuration settings of a block. Open text for both. Required before exporting. The Version Date should ideally be autofilled on Block update.
Locked Blocks, upon import, should not have these fields editable.
1. Go to branch `feature/FOUR-9033` in `package-pm-blocks`.
2. Go to branch `feature/FOUR-9033` in `core`.
3. Go to Designer → Processes and select the 'Save as PM Block' option for one of your processes.
4. In the `Publish PM Block` modal, there should be options to add …
=> FOUR-9033 | Add Author, Version, and Version Date fields

composer.json, config/app.php
This PR will contain all changes made to the `Process Analytics Reporting` project.
This PR will contain all changes made to the `Datalake ETL to Presentation Layer` project.
Please is important to configure the default in the ENVIRONMENT VARIABLES
```
ANALYTICS_REPORTING_GRAPH_1
ANALYTICS_REPORTING_GRAPH_2
ANALYTICS_REPORTING_GRAPH_3
```
Some links of graphs are added in the epic ticket
- **EPIC** [FOUR-7396](https://processmaker.atlassian.net/browse/FOUR-7396)
- **EPIC** [FOUR-8176](https://processmaker.atlassian.net/browse/FOUR-8176)
ci:deploy
ci:package-analytics-reporting:feature/FOUR-7396
[FOUR-7396]: https://processmaker.atlassian.net/browse/FOUR-7396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-8176]: …
=> FOUR-7396: Process Analytics Reporting IT6

resources/js/admin/users/components/SecurityLogsModal.vue
1. Create a ScriptExecutor Task
2. Check the Security Log
- [FOUR-8792](https://processmaker.atlassian.net/browse/FOUR-8792)
ci:deploy
[FOUR-8792]: https://processmaker.atlassian.net/browse/FOUR-8792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-8792: (QA observation) Responsive Design is needed in information for tickets

.github/workflows/deploy-pm4.yml, phpunit.xml
=> Attempt to fix unit tests

package-lock.json, package.json, resources/js/admin/users/components/SecurityLogsModal.vue, resources/js/app-layout.js
GroupMembersUpdated When Taking out a User with URL in Dynamic UI
- [FOUR-9391](https://processmaker.atlassian.net/browse/FOUR-9391)
ci:deploy
[FOUR-9391]: https://processmaker.atlassian.net/browse/FOUR-9391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9391: (QA observation) GroupMembersUpdated When Taking out a User with URL in Dynamic UI

ProcessMaker/Events/CategoryCreated.php, ProcessMaker/Events/CategoryDeleted.php, ProcessMaker/Events/ScreenUpdated.php, ProcessMaker/Events/TemplateCreated.php, tests/Feature/Api/SecurityLogsTest.php
Add coverage in the unit test
Run the unit test
- [FOUR-9333](https://processmaker.atlassian.net/browse/FOUR-9333)
[FOUR-9333]: https://processmaker.atlassian.net/browse/FOUR-9333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9333: Unit test

ProcessMaker/Events/TemplateUpdated.php
Process_category: needs to have another format
- FOUR-9460
=> FOUR-9460: (QA Observation) Process_category: needs to have another format

ProcessMaker/Events/CustomizeUiUpdated.php, ProcessMaker/Http/Controllers/Api/CssOverrideController.php
Do modifications in Customize UI
Reset
Do modifications in Customize UI
Check the User Activity Logging
- The reset action use other way to get the default values
Do modifications in Customize UI
Reset
Do modifications in Customize UI
Check the User Activity Logging
- https://processmaker.atlassian.net/browse/FOUR-9669
=> FOUR-9669: Customize UI User Activity Logging Registry is not Working Properly

ProcessMaker/Traits/MakeHttpRequests.php, ProcessMaker/WebServices/NativeSoapClient.php
ci:deploy
ci:connector-docusign:v1.2.1
ci:connector-idp:v1.2.2
ci:connector-pdf-print:v1.11.2
ci:connector-send-email:v1.18.2
ci:connector-slack:v1.3.1
ci:docker-executor-node-ssr:v1.2.1
ci:package-actions-by-email:v1.11.1
ci:package-advanced-user-manager:v1.4.0
ci:package-auth:v1.10.1
ci:package-collections:v2.9.3
ci:package-comments:v1.5.1
ci:package-conversational-forms:v1.2.2
ci:package-data-sources:FOUR-9668-4.6.3
ci:package-decision-engine:v1.0.0
ci:package-dynamic-ui:v1.9.1
ci:package-files:v1.7.1
ci:package-googleplaces:v1.4.2
ci:package-process-documenter:v1.3.0
ci:package-process-optimization:v1.3.0
ci:package-product-analytics:v1.2.1
ci:package-savedsearch:v1.23.2
ci:package-sentry:v1.3.1
ci:package-signature:v1.4.1
ci:package-translations:v2.3.3
ci:package-versions:v1.4.2 …
=> [FOUR-9668]

resources/js/tasks/components/TasksList.vue
- Add the eye icon 
- run `npn run dev`
- [FOUR-9578](https://processmaker.atlassian.net/browse/FOUR-9578)
[FOUR-9578]: https://processmaker.atlassian.net/browse/FOUR-9578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9578: Create an action eye column

resources/js/bootstrap.js
- Login in the page https://nightly-qa.processmaker.net/
- Go to Designer menu
- Write a Process’s name in the Search field
- Press enter key
- Set openAi to false when meta not found.
- [FOUR-9823](https://processmaker.atlassian.net/browse/FOUR-9823)
[FOUR-9823]: https://processmaker.atlassian.net/browse/FOUR-9823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-9823: Search a Process is not working after pressing `enter` key

ProcessMaker/Http/Controllers/TaskController.php, resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksPreview.vue, resources/views/tasks/preview.blade.php, routes/web.php
Task Preview: Improve the PRD request related to
Action: Open the Screen and expand to cover about 50% of the screen
Create a new view, I duplicated the view edit of tasks so I remove the code useless for this new view
npm run dev
php artisan route:clear
- [FOUR-9579](https://processmaker.atlassian.net/browse/FOUR-9579)
ci:deploy
[FOUR-9579]: https://processmaker.atlassian.net/browse/FOUR-9579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature/four-9579: Action: Open the Screen and expand to cover about 50% of the screen

ProcessMaker/Http/Controllers/TaskController.php, resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksPreview.vue, resources/views/tasks/preview.blade.php, routes/web.php
- [FOUR-9499](https://processmaker.atlassian.net/browse/FOUR-9499)
ci:deploy
[FOUR-9499]: https://processmaker.atlassian.net/browse/FOUR-9499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature/four-9499:Task Preview

resources/js/tasks/components/TasksPreview.vue
Add the Next and Previous Buttons
- https://processmaker.atlassian.net/browse/FOUR-9580
ci:deploy
=> feature/FOUR-9580: Add the Next and Previous Buttons

resources/js/tasks/components/TasksPreview.vue
Add the title, is the task name
- https://processmaker.atlassian.net/browse/FOUR-9592
=> feature/FOUR-9592: Add the title, is the task name

resources/js/components/TreeView.vue, resources/js/components/common/data-tree-toggle.vue, resources/js/tasks/show.js, resources/views/tasks/edit.blade.php, resources/views/tasks/editdata.blade.php
New tree view toggle on the task data tab with a reusable view
https://processmaker.atlassian.net/browse/FOUR-9722
https://processmaker.atlassian.net/browse/FOUR-9723
=> FOUR-9712 Tree view toggle on the task data tab with a reusable view

resources/js/tasks/components/TasksPreview.vue
- [FOUR-9595](https://processmaker.atlassian.net/browse/FOUR-9595)
[FOUR-9595]: https://processmaker.atlassian.net/browse/FOUR-9595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature/four-9595: Add the loading on Next an Previous Buttons

ProcessMaker/Http/Controllers/Api/CssOverrideController.php
Images for Customize UI are Not Fully Compiled Icon Favicon.
1. Access Customize UI
2. Change the four images files
3. Save them
- https://processmaker.atlassian.net/browse/FOUR-9859
ci:deploy
=> bugfix/FOUR-9859:  Customize UI are Not Fully Compiled Icon Favicon

composer.json, resources/js/components/SelectUserGroup.vue, resources/js/components/shared/CategorySelect.vue, resources/js/components/shared/SelectUserGroup.vue, resources/js/components/shared/index.js
This PR adds the CategorySelect and Select User Groups, to the shared component directory. These components will be utilized within the Projects package.
ci:package-projects:next
ci:deploy
[Projects Package PR](https://github.com/ProcessMaker/package-projects/pull/5)
=> Add CategorySelect & SelectUserGroups to shared components

composer.json, composer.lock, package-lock.json, package.json
ci:deploy
ci:connector-docusign:develop
ci:connector-idp:develop
ci:connector-pdf-print:develop
ci:connector-send-email:develop
ci:connector-slack:develop
ci:docker-executor-node-ssr:develop
ci:package-actions-by-email:develop
ci:package-advanced-user-manager:develop
ci:package-ai:develop
ci:package-analytics-reporting:develop
ci:package-auth:develop
ci:package-collections:develop
ci:package-comments:develop
ci:package-conversational-forms:develop
ci:package-data-sources:develop
ci:package-decision-engine:develop
ci:package-dynamic-ui:develop
ci:package-files:develop
ci:package-googleplaces:develop
ci:package-photo-video:develop
ci:package-plaid:develop
ci:package-pm-blocks:develop
ci:package-process-documenter:develop
ci:package-process-optimization:develop …
=> Nightly 20230822

resources/js/tasks/components/TasksPreview.vue
fix the iframe and the Css must be the same in figma
- https://processmaker.atlassian.net/browse/FOUR-10058
ci:deploy
=> feature/FOUR-10058: Fixing problems with the merge in the epic FOUR-9487

resources/js/app-layout.js, resources/js/components/Confirm.vue, resources/js/processes/scripts/components/CorneaTab.vue, resources/js/processes/scripts/components/ScriptEditor.vue, resources/views/layouts/navbar.blade.php
**Figma**
https://www.figma.com/file/HPlbIAFk5pPLvHX6vyUN3K/Fall-23?type=design&node-id=911-265155&mode=design&t=FqPDbvhyOck2MpvF-0
**PI Planning document**
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3149299713/AI+Script+Generation+and+Co-Pilot+for+scripting
**Epic**
https://processmaker.atlassian.net/browse/FOUR-9675
=> Epic/FOUR-9675: AI Script Generation and Co-Pilot for scripting

ProcessMaker/Http/Controllers/Auth/LoginController.php
=> FOUR-8663 Unable to login with imported LDAP users

ProcessMaker/Http/Controllers/RequestController.php, resources/js/app-layout.js, resources/views/auth/login.blade.php, resources/views/layouts/mobile.blade.php, resources/views/layouts/navbarMobile.blade.php
- [FOUR-9552](https://processmaker.atlassian.net/browse/FOUR-9552)
ci:next
[FOUR-9552]: https://processmaker.atlassian.net/browse/FOUR-9552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9552: Switch desktop - Logout NavBar for mobile version

resources/views/tasks/preview.blade.php
The CLAIM TASK button is not found.
1. Have a process with self service task configured
2. Open a self service task
- https://processmaker.atlassian.net/browse/FOUR-10093
ci:next
=> feature/FOUR-10093: CLAIM TASK not found in Self Service Task

resources/js/tasks/components/TasksPreview.vue
Size changes when opened the second time
- https://processmaker.atlassian.net/browse/FOUR-10190
ci:next
=> feature/FOUR-10190: Screen in List of Tasks Changes Size When Reopened Again

resources/js/components/shared/DownloadSvgButton.vue
Reverts ProcessMaker/processmaker#5233
=> Revert "Bugfix/FOUR-10277: Prompt not used on the image downloaded"

database/seeders/PermissionSeeder.php
Need to run `php artisan db:seed --class=PermissionSeeder` to update the permissions
- https://processmaker.atlassian.net/browse/FOUR-10252
ci:next
=> feature/FOUR-10252: Create a new permission to edit password

database/migrations/2023_09_05_164219_add_default_field_to_settings_table.php
https://processmaker.atlassian.net/browse/FOUR-9624
ci:next
=> feature/FOUR-9624: Schema add a new property to save the default

ProcessMaker/Http/Controllers/TaskController.php, ProcessMaker/Models/FormalExpression.php, resources/views/tasks/editdata.blade.php
- Run a process in an isolated environment.
- Save scenarios
- Run scenarios
- Run processes from modeler
ci:next
=> FOUR-8066 Process Testing part 1

resources/js/bootstrap.js, resources/js/components/templates/TemplateSelectCard.vue, resources/js/processes/components/index.js, resources/js/requests/components/RequestsListing.vue
* Reindented some files
* Importing Vue since the import was missing and was causing some issues on build
ci:deploy
ci:package-ai:epic/FOUR-8110
ci:screen-builder:epic/FOUR-8110
ci:next
=> Epic/FOUR-8110: Natural Language to Forms

ProcessMaker/Helpers/MobileHelper.php, tests/unit/ProcessMaker/Helpers/MobileHelperTest.php
Add the unit test for MobileHelper
- A new helper was created
- Add the unit test related to the new helper
`vendor/bin/phpunit`
https://processmaker.atlassian.net/browse/FOUR-10398
ci:next
=> feature/FOUR-10398: Add the unit test for MobileHelper

resources/js/tasks/components/TaskLoading.vue, resources/js/tasks/components/TasksPreview.vue
This is a feature defined in the document: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3123380270/Participant+Task+Preview+Pane
- QA observations
- Create a **process** with some tasks and **screen** related in the task
- Create a **Request**
- Go to the **Task** top menu
- Open a Preview and submit the data
- https://processmaker.atlassian.net/browse/FOUR-9487
ci:next
=> feature/FOUR-9487: IT4 Participant Task Preview Pane

resources/js/app-layout.js
need the notification bell popover  works 
- https://processmaker.atlassian.net/browse/FOUR-10578
ci:next
=> Feature/four 10578: Enable the notification in the desktop mode

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Models/Setting.php, resources/js/admin/settings/components/SettingDriverAuthorization.vue, resources/js/admin/settings/components/SettingForm.vue, resources/js/admin/settings/components/SettingsListing.vue, routes/api.php
Ticket: [FOUR-10490](https://processmaker.atlassian.net/browse/FOUR-10490)
This PR introduces new features related to the CDATA package settings. While this PR includes the frontend functionality to configure and authorize drivers, it does not cover backend authorization. When users select the 'Authorize' button, the settings will be saved in the database. However, please note that the Authorize badge will continue to display 'Not Authorized' until backend authorization is fully implemented.
**'Configure & Authorize Driver' Modal:**
- We have implemented a modal that enables users to configure and authorize drivers after selecting and adding them to the list of settings.
- Users can access this modal by clicking the 'edit' icon button for the respective driver in the settings.
**Driver …
=> Implement 'Configure & Authorize Driver' Modal and Driver Management

resources/js/Mobile/Card.vue, resources/js/app-layout.js, resources/views/tasks/editMobile.blade.php
- [FOUR-9540](https://processmaker.atlassian.net/browse/FOUR-9540)
ci:next
[FOUR-9540]: https://processmaker.atlassian.net/browse/FOUR-9540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9540:Task Screen: Load Screens (Forms)

resources/js/components/templates/ButtonCard.vue, resources/js/components/templates/CreateTemplateModal.vue
From SonarQube:
- [Add an "alt" attribute to this image.](https://sonarqube.processmaker.net/project/issues?issues=AYoqk5RxjVJcSJQnZwom&open=AYoqk5RxjVJcSJQnZwom&id=ProcessMaker_processmaker_AYkzkfKexYvY_isvKt07)
- [Add an "alt" attribute to this image.](https://sonarqube.processmaker.net/project/issues?issues=AYoqk5RxjVJcSJQnZwon&open=AYoqk5RxjVJcSJQnZwon&id=ProcessMaker_processmaker_AYkzkfKexYvY_isvKt07)
- [Duplicate name 'description'.](https://sonarqube.processmaker.net/project/issues?issues=AYoqk5RujVJcSJQnZwol&open=AYoqk5RujVJcSJQnZwol&id=ProcessMaker_processmaker_AYkzkfKexYvY_isvKt07)
=> Minor fixes

resources/js/tasks/components/NavbarTaskMobile.vue, resources/js/tasks/components/TaskDetailsMobile.vue, resources/views/tasks/editMobile.blade.php
In the initial list of task, we can see the following properties:
completed_at can be Null - Datetime
due_at can be Null - Datetime
due_notified can be  0 1, 1 is a request with delay
THE REASSIGN WILL COMPLETE IN OTHER TICKET
- https://processmaker.atlassian.net/browse/FOUR-9541
ci:next
=> feature/FOUR-954: Task Screen - NavBar: show the Details

resources/js/processes/modeler/components/inspector/ConfigEditor.vue
- Fix QA observations for data browser
- https://processmaker.atlassian.net/browse/FOUR-10611
ci:next
=> Fix QA observations for data browser

resources/views/layouts/navbarMobile.blade.php
The notification was removed out side the epic, please remove the notification.
- https://processmaker.atlassian.net/browse/FOUR-10976
ci:next
=> feature/FOUR-10976: Mobile: Remove the icon related to the notification (remove)

ProcessMaker/Http/Controllers/Api/CommentController.php, ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Models/Comment.php, ProcessMaker/Models/Process.php, database/migrations/2023_09_22_224306_add_parent_id_to_table_comments.php, resources/js/notifications/components/NotificationsList.vue, resources/js/notifications/components/notifications.vue, resources/js/processes/modeler/components/ModelerApp.vue, resources/views/processes/modeler/index.blade.php, resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php, routes/api.php
ci:next
ci:modeler:feature/FOUR-9709
ci:package-comments:observations/FOUR-10941
- https://processmaker.atlassian.net/browse/FOUR-10941
- Requires
- https://github.com/ProcessMaker/package-comments/pull/94
- https://github.com/ProcessMaker/modeler/pull/1683
=> UI Updates for comments

README.md
Test multiple self hosted runners running at the same time
ci:build
ci:next
...
=> Test multiple self hosted runners - do not merge

resources/js/processes/scripts/components/GenerateScriptTextPrompt.vue, resources/js/processes/scripts/components/ScriptEditor.vue
**Figma**
https://www.figma.com/file/HPlbIAFk5pPLvHX6vyUN3K/Fall-23?type=design&node-id=1-2&mode=design&t=FcADuhMGTJxndieK-0
**PI Planning document**
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3150675969/Ai+in+Modeler+-+PI+Document
**Epic**
https://processmaker.atlassian.net/browse/FOUR-9674
**Related PR's**
- [core](https://github.com/ProcessMaker/processmaker/pull/5430)
- [modeler](https://github.com/ProcessMaker/modeler/pull/1687)
- [package-ai](https://github.com/ProcessMaker/package-ai/pull/30)
ci:next
ci:deploy
ci:package-ai:epic/FOUR-9674
ci:modeler:epic/FOUR-9674
ci:screen-builder:epic/FOUR-9674
ci:package-versions:epic/FOUR-9674
=> Epic/FOUR-9674: AI in modeler

.github/workflows/deploy-pm4.yml, .github/workflows/sonarqube.yml, .github/workflows/translate_strings.yml
=> Update github runner to use variable

resources/js/components/shared/dataSourceNavigation.js, resources/js/components/shared/decisionTableNavigation.js, resources/js/components/shared/ellipsisMenuActions.js, resources/js/components/shared/index.js, resources/js/processes/designer/RecentAssets.vue, resources/js/processes/designer/RecentAssetsList.vue, resources/views/designer/index.blade.php
In Welcome Screens for designers is need to have access  for Assets and Projects Actions
- https://processmaker.atlassian.net/browse/FOUR-10987
ci:next
=> Feature/four 10987: Designer Ellipsis: Recent Assets and Projects Actions

resources/views/layouts/navbarMobile.blade.php
- Issue with logo was solved.
ci:next
=> bugfix/FOUR-11056 : The ProcessMaker Icon is not the same as the mockup.

resources/js/processes/screen-builder/screen.vue
Connector Send Email improvements
ci:next
=> FOUR-10818 Connector Send Email improvements

ProcessMaker/Nayra/Managers/WorkflowManagerKafka.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/MessageBrokers/ServiceKafka.php, config/kafka.php
- https://processmaker.atlassian.net/browse/FOUR-9988
=> FOUR-9988 Add a KAFKA_PREFIX environment option

resources/js/processes/designer/ProjectsLastModifiedListing.vue
- Figma styles were applied to fix this issue.
- QA observation FOUR-11022
ci:deploy
ci:next
=> QA observation bugfix/FOUR-11022: Recent Projects does not have the correct style

resources/js/app-layout.js
All the PR are meged, some error are showin in the console
Login into the branch on Desto
p mode and the following error is showing:
- https://processmaker.atlassian.net/browse/FOUR-10940
ci:next
=> Feature/four 10940: Solving console issues in Mobile: Cannot find element: #navbarMobile

resources/js/bootstrap.js, resources/views/layouts/layout.blade.php
**Show connected user list and their avatars**
Related PRs
- [microservice-realtime PR](https://github.com/ProcessMaker/microservice-realtime/pull/14)
- [modeler PR](https://github.com/ProcessMaker/modeler/pull/1692)
- [core PR](https://github.com/ProcessMaker/processmaker/pull/5481)
Ticket
- [FOUR-10793](https://processmaker.atlassian.net/browse/FOUR-10793)
**Working video:**
https://github.com/ProcessMaker/microservice-realtime/assets/90727999/6f64d601-d990-4a71-a7ce-1bb0217232a3
ci:next
[FOUR-10793]: https://processmaker.atlassian.net/browse/FOUR-10793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/FOUR-10793: user avatar - show connected user

resources/js/components/shared/EllipsisMenu.vue
Listing options are not displayed
Check the permissions object to see what type it belongs to.
ci:next
- [FOUR-11188](https://processmaker.atlassian.net/browse/FOUR-11188)
- [FOUR-11190](https://processmaker.atlassian.net/browse/FOUR-11190)
- [FOUR-11193](https://processmaker.atlassian.net/browse/FOUR-11193)
- [FOUR-11195](https://processmaker.atlassian.net/browse/FOUR-11195)
ci:next
[FOUR-11188]: https://processmaker.atlassian.net/browse/FOUR-11188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-11190]: https://processmaker.atlassian.net/browse/FOUR-11190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-11193]: …
=> The edit and delete user options in the ellipsis menu are not visible

ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Http/Controllers/Api/ScriptExecutorController.php, ProcessMaker/Models/Script.php, ProcessMaker/Models/ScriptExecutor.php, ProcessMaker/Models/ScriptExecutorVersion.php, ProcessMaker/Nayra/Managers/WorkflowManagerKafka.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/MessageBrokers/ServiceKafka.php, ProcessMaker/Traits/HideSystemResources.php, ProcessMaker/Traits/ProjectAssetTrait.php, composer.json, composer.lock, config/kafka.php, database/factories/ProcessMaker/Models/ScriptExecutorFactory.php, database/migrations/2023_10_16_203929_add_is_system_column_to_script_executors_table.php, database/migrations/2023_10_16_232615_add_is_system_column_to_script_executor_versions_table.php, package-lock.json, package.json, resources/js/Mobile/FilterMobile.vue, resources/js/admin/settings/components/SettingDriverAuthorization.vue, resources/js/app-layout.js, resources/js/bootstrap.js, resources/js/components/shared/EllipsisMenu.vue, resources/js/components/shared/ellipsisMenuActions.js, resources/js/components/shared/screenNavigation.js, resources/js/processes/designer/ProjectsLastModifiedListing.vue, resources/js/processes/screen-builder/screen.vue, resources/lang/en.json, resources/views/layouts/layout.blade.php, resources/views/layouts/navbarMobile.blade.php
As a Solution Developer, I want to import a Project into my environment to deploy it new or as an update so that I can moderate the lifecycle of my solution across environments.
When we have a Project with multiple assets in it, we should be able to export it and import the same projects with all of the assets.
- Implement Import functionality and FeatureTest
- Create a Project and add multiple assets.
- Export the Project from the Ellipsis menu within the Projects page
- Navigate to the Projects page, click on Import, and follow the import flow
Please ensure that the Project and its assets are imported.
FeatureTest: `phpunit vendor/processmaker/package-projects/tests/Feature/ImportExport`
- Ticket [FOUR-9547](https://processmaker.atlassian.net/browse/FOUR-9547)
- [Core …
=> FOUR-9547: Import Project

ProcessMaker/Traits/ProjectAssetTrait.php
This is a re-submission of FOUR-9547 resolving the unintended rollback.
-----------------
As a Solution Developer, I want to import a Project into my environment to deploy it new or as an update so that I can moderate the lifecycle of my solution across environments.
When we have a Project with multiple assets in it, we should be able to export it and import the same projects with all of the assets.
- Implement Import functionality and FeatureTest
- Create a Project and add multiple assets.
- Export the Project from the Ellipsis menu within the Projects page
- Navigate to the Projects page, click on Import, and follow the import flow
Please ensure that the Project and its assets are imported.
FeatureTest: `phpunit vendor/processmaker/package-projects/tests/Feature/ImportExport`
- Ticket …
=> FOUR-9547: Import Project 

ProcessMaker/Nayra/MessageBrokers/ServiceKafka.php, config/kafka.php
Integration Nayra Service in a Cluster
- https://processmaker.atlassian.net/browse/FOUR-11134
ci:next
ci:build-k8s
=> FOUR-11134 Integration Nayra Service in a Cluster

resources/js/components/shared/ellipsisMenuActions.js, resources/js/components/shared/scriptNavigation.js
This PR resolves the issues related to deleting a script from within a Project. The problem stemmed from the 'remove-item' action emitting a 'delete' event that was inaccessible via the Projects page. The solution involved refactoring the 'remove-item' action to directly call the delete endpoint for the script.
- Refactored the 'remove-item' action to directly call the delete endpoint for the script, resolving the issue with script deletion within Projects.
1. Ensure that both a script and a project are created in the system.
2. Assign the script to the created project.
3. Go to the Project Asset listing page and select the Ellipsis menu for the script.
4. Choose the 'Delete' option.
5. Confirm that the script is successfully deleted from the project without any errors or inconsistencies. …
=> Fix Script Deletion Issue within Projects

resources/js/processes/designer/RecentAssetsList.vue
- The Styles were applied as Mockup requirements
https://processmaker.atlassian.net/browse/FOUR-11260
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-11260: Alpha 2: The styles in assets is not correctly

resources/views/auth/newLogin.blade.php
Update the text of the LOG IN button 
- Change the label Sign In to Log In
- Review the button for login
- https://processmaker.atlassian.net/browse/FOUR-11308
ci:deploy
ci:next
=> FOUR-11308: Update the text of the LOG IN button 

ProcessMaker/Http/Controllers/Designer/DesignerController.php, resources/js/processes/designer/Asset.vue, resources/js/processes/designer/AssetButtons.vue, resources/js/processes/designer/WelcomeDesigner.vue, resources/js/processes/newDesigner.js, resources/lang/en.json, resources/views/designer/index.blade.php
- [FOUR-11274](https://processmaker.atlassian.net/browse/FOUR-11274)
ci:deploy
ci:next
[FOUR-11274]: https://processmaker.atlassian.net/browse/FOUR-11274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-11274:Priority 1: Update Welcome Screen (Designer /Participant) Message

.github/workflows/deploy-pm4.yml
Revert to ECS until we reconfigure k8s
ci:next
ci:deploy
=> Revert to ECS for now

resources/js/processes/designer/Assets.vue
Remove Collection option from designer Welcome Scrren, because it will be only an Admin option.
- https://processmaker.atlassian.net/browse/FOUR-11307
ci:deploy
ci:next
=> Feature/four 11307: Priority 1: Remove Collections from Designer Welcome Screen

resources/js/Mobile/Card.vue
- https://processmaker.atlassian.net/browse/FOUR-11345
ci:deploy
ci:next
=> feature/FOUR-11345:  Task: Update the styles color defined

ProcessMaker/Http/Controllers/Auth/LoginController.php
The new login needs to show the SSO login
- Configure the SSO login
Review the login page
- https://processmaker.atlassian.net/browse/FOUR-11331
ci:deploy
ci:next
=> FOUR-11331: The new login needs to show the SSO login 

resources/js/components/shared/index.js, resources/js/tasks/components/PreviewMixin.js, resources/js/tasks/components/TasksHome.vue, resources/js/tasks/components/TasksPreview.vue
My Task: Enlarge the participant task preview panel
- The preview pane needs to use the 50%
Create Request
Create Route Request
See the preview Pane From Task and Welcome Screen
- [FOUR-11278](https://processmaker.atlassian.net/browse/FOUR-11278)
ci:deploy
ci:next
ci:screen-builder:bugfix/FOUR-11278
ci:screen-builder:bugfix/FOUR-11278
[FOUR-11278]: https://processmaker.atlassian.net/browse/FOUR-11278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-11278: My Task: Enlarge the participant task preview panel

resources/js/app-layout.js
- Redirect to "/requests" was implemented to solve action button Switch to Mobile
1. Login in the https://ci-625acf5d97.eng.processmaker.net/
2. Open the developer tool
3. A welcome screen is displayed 
4. Change to Mobile size
5. Reload the page
6. Press Switch to Mobile View button
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-11367: Mobile UI is not working when the URL is different to requests or tasks

resources/js/Mobile/Card.vue
Adjust Timestamp in the Request information
- https://processmaker.atlassian.net/browse/FOUR-11392
ci:next
ci:deploy
=> Feature/four 11392: Mobile: Adjust timestamp in request information

resources/js/Mobile/WelcomeModal.vue, resources/views/layouts/navbarMobile.blade.php
Repace the Participant for the User Full Name
- https://processmaker.atlassian.net/browse/FOUR-11394
ci:next
ci:deploy
=> Feature/four 11394: Mobile: Load the name of user Full name in the welcome

ProcessMaker/Jobs/RunScriptTask.php, ProcessMaker/Jobs/RunServiceTask.php, ProcessMaker/Models/User.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/Repositories/Deserializer.php, ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php
The errors were not propagated correctly, resulting in them not notified.
- Fix error propagation.
- Create an process with an script task that throws an Exception.
- https://processmaker.atlassian.net/browse/FOUR-11358
ci:next
=> FOUR-11358 Fix error propagation

ProcessMaker/Http/Controllers/Api/NotificationController.php, resources/js/notifications/components/NotificationsList.vue, resources/views/notifications/index.blade.php
Pagination missing from notifications page
- Fix notification pagination behavior and reformat of Tabs functionality.
Re do the API call with a correct way of filtering notifications using a comments query.
- https://processmaker.atlassian.net/browse/FOUR-10562
=> Fix notification pagination behavior and reformat of Tabs functionality

resources/js/processes/designer/ProjectsLastModifiedListing.vue, resources/js/processes/designer/RecentAssetsList.vue
The API to get the assets needs to apply filters and order by columns
- https://processmaker.atlassian.net/browse/FOUR-10341
ci:deploy
ci:next
=> FOUR-10341: The API to get the assets needs to apply filters and order by columns

resources/js/processes/modeler/initialLoad.js, resources/views/processes/scripts/preview.blade.php
This PR resolves:
https://processmaker.atlassian.net/browse/FOUR-11075
https://processmaker.atlassian.net/browse/FOUR-11074
https://processmaker.atlassian.net/browse/FOUR-11284
https://processmaker.atlassian.net/browse/FOUR-10844
https://processmaker.atlassian.net/browse/FOUR-10842
https://processmaker.atlassian.net/browse/FOUR-10599
https://processmaker.atlassian.net/browse/FOUR-10597
https://processmaker.atlassian.net/browse/FOUR-10596
https://processmaker.atlassian.net/browse/FOUR-10595
ci:next
=> Fixes to Window Pane observations

ProcessMaker/Http/Controllers/Api/CommentController.php, resources/js/components/Timeline.vue, resources/js/notifications/components/notifications.vue
- Allow multiple types for comment type filter
Requires https://github.com/ProcessMaker/package-comments/pull/103
ci:next
ci:package-comments:feature/FOUR-9709
=> Notifications Overhaul - Fixes

resources/js/processes/screen-builder/screen.vue
Double scroll in email preview.
- Fix css styles.
- Create a large email (multiple lines) to enable the vertical scroll
- Go to preview
- https://processmaker.atlassian.net/browse/FOUR-11563
ci:next
=> FOUR-11563 Fix double scroll in email preview

resources/js/components/shared/ellipsisMenuActions.js
- FOUR-11954
ci:deploy
ci:next
=> FOUR-11542: Processes Setup - Ellipsis menu - Open Launchpad

resources/js/components/shared/ProjectSelect.vue
This PR refactors the logic for setting project options in the Project Select list. The changes aim to eliminate excessive API calls to the Project endpoint that were occurring unnecessarily. The refactoring ensures a more efficient and optimized process for populating project options in the Project Select list.
- Removed the code that caused excessive API calls to the Project endpoint.
Test Case A: Verify Excessive API Calls Prevention
1. Ensure that no projects are configured in the system.
2. Navigate to the Script listing page.
3. Open your network tab in the browser's developer tools.
4. Load the "Create New Script" modal.
5. Confirm that excessive project API calls are not generated during the modal loading process.
Test Case B: Project Select List Functionality
1. Create multiple …
=> Resolve excessive API calls to Project endpoint

ProcessMaker/Http/Controllers/Api/CommentController.php
=> FOUR-11818 Comments in a TASK are displaying in the history/timeline inside a Request

resources/js/admin/settings/components/SettingsListing.vue
-  The issue was fixed
ci:deploy
=> bugfix spaces between buttons

resources/views/auth/newLogin.blade.php
- [FOUR-12341](https://processmaker.atlassian.net/browse/FOUR-12341)
[FOUR-12341]: https://processmaker.atlassian.net/browse/FOUR-12341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12341:Login > password field is not displayed when the user pres in the Eye icon

resources/js/processes/designer/WelcomeDesigner.vue
- [FOUR-12420](https://processmaker.atlassian.net/browse/FOUR-12420)
ci:deploy
[FOUR-12420]: https://processmaker.atlassian.net/browse/FOUR-12420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12420:There is No Space between Icon User and "Welcome Back {User}"

ProcessMaker/LicensedPackageManifest.php
=> Build fall adjustments

resources/js/processes/scripts/components/CreateScriptModal.vue, resources/js/processes/scripts/components/LanguageScript.vue
- [FOUR-12482](https://processmaker.atlassian.net/browse/FOUR-12482)
ci:deploy
ci:next
[FOUR-12482]: https://processmaker.atlassian.net/browse/FOUR-12482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12482:Integration: New Script Modal Redesign

composer.json
Add package-jz-sonymusic, package-jz-nas and pm-platform
- https://processmaker.atlassian.net/browse/FOUR-12526
ci:next
=> Add package-jz-sonymusic, package-jz-nas and pm-platform

resources/views/processes/scripts/edit.blade.php
- [FOUR-12525](https://processmaker.atlassian.net/browse/FOUR-12525)
ci:depoly
[FOUR-12525]: https://processmaker.atlassian.net/browse/FOUR-12525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12525:The language selected on the script is not shown in settings

resources/js/processes/scripts/components/CreateScriptModal.vue, resources/views/processes/scripts/edit.blade.php
Run script as needs to be capitalized
- Update the label
Create a new script
- https://processmaker.atlassian.net/browse/FOUR-12488
ci:deploy
ci:next
=> FOUR-12488: "Run script as" needs to be capitalized

resources/js/processes/scripts/components/CreateScriptModal.vue
- Modal window clear all fields on Close, also Projects input field.
ci:deploy
=> QA Observation Bugfix/FOUR-12502-B

routes/web.php
- [FOUR-12581](https://processmaker.atlassian.net/browse/FOUR-12581)
ci:next
[FOUR-12581]: https://processmaker.atlassian.net/browse/FOUR-12581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12581:Process Launchpad: Create the initial mockup

ProcessMaker/Managers/ScreenBuilderManager.php
Filter SB components without license
- https://processmaker.atlassian.net/browse/FOUR-12688
=> FOUR-12688 Filter SB components without license

resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue
- https://processmaker.atlassian.net/browse/FOUR-12691
ci:next
ci:deploy
=> Feature/four 12691: Performance: Implement the Infinite scroll

resources/js/requests/components/RequestsListing.vue
Delete the column # (number)
- https://processmaker.atlassian.net/browse/FOUR-12573
ci:deploy
ci:next
=> FOUR-12573 Delete the column # (number)

ProcessMaker/Http/Controllers/Api/ProcessController.php
HTML is recognized in the case title field
- Sanitize case_title.
- https://processmaker.atlassian.net/browse/FOUR-12698
ci:deploy
ci:next
=> Sanitize case_title

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/utils/SearchCards.vue
- [FOUR-12222](https://processmaker.atlassian.net/browse/FOUR-12222)
ci:deploy
ci:next
[FOUR-12222]: https://processmaker.atlassian.net/browse/FOUR-12222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12222:Process Browser - Search

resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue
- [FOUR-12813](https://processmaker.atlassian.net/browse/FOUR-12813)
ci:deploy
ci:next
[FOUR-12813]: https://processmaker.atlassian.net/browse/FOUR-12813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The Process Browser -> Available Process needs to have a heigh defined like mockup

resources/views/shared/users/sidebar.blade.php
https://processmaker.atlassian.net/browse/FOUR-12793
=> FOUR-12793 The label 'Leave the password blank to keep the current password:' is displayed when password set by user is disabled

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue
- [FOUR-11987](https://processmaker.atlassian.net/browse/FOUR-11987)
ci:deploy
ci:next
[FOUR-11987]: https://processmaker.atlassian.net/browse/FOUR-11987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-11987:Processes Browser - Component Bookmark

resources/js/components/shared/ModalSaveVersion.vue, resources/lang/en.json
- Only PNG and JPG extensions are allowed in image container.
- Open a Process
- Click on PUBLISH button
- Upload or Drag Images into container
- ONLY PNG and JPG files are allowed.
- https://processmaker.atlassian.net/browse/FOUR-12787
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-12775: The upload images control does not validate the format of the files.

resources/js/components/shared/ellipsisMenuActions.js
Error with archiving process
- https://processmaker.atlassian.net/browse/FOUR-12791
ci:deploy
ci:next
=> FOUR-12791: Error with archiving process

resources/js/admin/users/index.js
https://processmaker.atlassian.net/browse/FOUR-12796
=> FOUR-12796 Minimum Password length setting does not work well when creating a user

ProcessMaker/Http/Middleware/VerifyChangePasswordNeeded.php
https://processmaker.atlassian.net/browse/FOUR-12785
=> FOUR-12785 Log in in with correct username and password works fine on the second attempt

resources/js/admin/settings/components/AdditionalDriverConnectionProperties.vue, resources/js/admin/settings/components/SettingDriverAuthorization.vue, resources/js/admin/settings/components/SettingsListing.vue, resources/js/admin/settings/components/cdata/DocusignConnectionProperties.vue, resources/js/admin/settings/components/cdata/ExcelConnectionProperties.vue, resources/js/admin/settings/components/cdata/GithubConnectionProperties.vue, resources/js/admin/settings/components/cdata/GmailConnectionProperties.vue
It's necessary to add the Gmail driver to the External Integrations section.
- Added the necessary files for integrating the Gmail driver.
Enable the Gmail API
- Navigate to the Google Cloud Console.
- Select Library from the left-hand navigation menu. This opens the Library page.
- In the search field, enter "Gmail API" and select Gmail API from the search results.
- On the Gmail API page, click ENABLE.
Create an OAuth App for User Account Authentication
- Authorize the driver in `admin/settings`. 
- Test the driver:
```sql
SELECT * FROM INBOX WHERE Id = '123'
SELECT * FROM INBOX WHERE Subject = '123'
SELECT * FROM INBOX WHERE [From] = 'test@gmail.com'
SELECT * FROM INBOX WHERE [To] = 'test@gmail.com'
SELECT * FROM INBOX WHERE [Date] >= '12/12/12 12:12:12'
SELECT * FROM INBOX WHERE …
```
=> FOUR-12880 - Add Gmail driver to External Integrations

ProcessMaker/Http/Middleware/SanitizeInput.php, ProcessMaker/Models/MustacheExpressionEvaluator.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Observers/ProcessRequestObserver.php, database/migrations/2023_12_11_180034_add_case_title_formatted_to_process_requests_table.php, resources/js/requests/components/RequestsListing.vue, resources/views/processes/edit.blade.php, tests/unit/ProcessMaker/CaseTitleTest.php
- https://processmaker.atlassian.net/browse/FOUR-12575
ci:next
ci:deploy
=> FOUR-12575 Bold variables in Case Title Columns

resources/js/processes-catalogue/components/ProcessOptions.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/optionsMenu/ProcessCounter.vue
FOUR-11533: Add Metric "Request of process"
- https://processmaker.atlassian.net/browse/FOUR-12709
ci:deploy
ci:next
=> FOUR-12709: FOUR-11533: Add Metric "Request of process"

composer.json
- https://processmaker.atlassian.net/browse/FOUR-12963
=> Add custom package-zj-adps

resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue, resources/js/processes-catalogue/components/optionsMenu/ProcessCounter.vue
Align the Process Options elements
- https://processmaker.atlassian.net/browse/FOUR-13014
ci:deploy
ci:next
=> FOUR-13014

ProcessMaker/Models/User.php, database/migrations/2023_12_22_200711_add_connected_accounts_column_to_users_table.php, resources/views/profile/connectedAccounts.blade.php, resources/views/profile/edit.blade.php
This PR introduces a `connected_accounts` column to the `users` table, providing the ability to track and update connected accounts associated with a specific user. The connected accounts can be accessed through the API using the `PUT users/{user}` endpoint. Additionally, the enabled connected accounts list is made visible in the UI under the user's 'Edit Profile' > 'Connected Accounts' tab.
1. Ensure you have access to a local development environment.
2. Run the necessary migrations to apply the changes to the users table.
3. Access the API and make a PUT request to users/{user} with connected account information.
example : 
```
"connected_accounts": "[{\"name\":\"Gmail\",\"description\":\"Provideautomatedresponses,generatedrafts,andassitwithemailcomposition\",\"icon\":\"https://img.icons …
```
=> Implement Connected Accounts API

resources/js/processes-catalogue/components/ProcessMap.vue
- [FOUR-12812](https://processmaker.atlassian.net/browse/FOUR-12812)
ci:deploy
ci:next
[FOUR-12812]: https://processmaker.atlassian.net/browse/FOUR-12812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12812:Process title and description does not have the same styles from mockup

resources/js/processes-catalogue/components/utils/SearchCards.vue
- [FOUR-12912](https://processmaker.atlassian.net/browse/FOUR-12912)
ci:deploy
ci:next
[FOUR-12912]: https://processmaker.atlassian.net/browse/FOUR-12912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12912:Search for Process Browser is not working with enter

resources/js/processes-catalogue/components/utils/pagination.vue
- [FOUR-12865](https://processmaker.atlassian.net/browse/FOUR-12865)
ci:deploy
ci:next
[FOUR-12865]: https://processmaker.atlassian.net/browse/FOUR-12865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12865:Paginator overlap on Card in Launch Pad

resources/js/components/shared/processNavigation.js, resources/js/processes-catalogue/components/ProcessMap.vue
1. Log in
2. click on Proceses
3. select a category available
4. select a process
5. click on lso 3 points ellipsis menu
6. click on archive process
- https://processmaker.atlassian.net/browse/FOUR-12791
ci:deploy
ci:next
=> Feature/four 12791: Error when archiving a process from the wizard

resources/js/processes/scripts/components/LanguageScript.vue, resources/lang/en.json
- [FOUR-12939](https://processmaker.atlassian.net/browse/FOUR-12939)
ci:deploy
ci:next
[FOUR-12939]: https://processmaker.atlassian.net/browse/FOUR-12939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12939:Rename Executor Title  of the Create Script Modal

resources/js/components/shared/ModalSaveVersion.vue
- The reported issue was solved.
Steps to Reproduce
Create a process 
Click on pusblish botton 
Upload image1
Upload image2
Upload image3
Upload image4
Upload image5 (Error appears)
Delete the image4
Try to upload the image5 again
https://processmaker.atlassian.net/browse/FOUR-13054
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-13054: Image could not be uploaded in "Images for carousel" after a failed attempt

resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/js/processes-catalogue/components/utils/SearchCards.vue, resources/sass/_scrollbar.scss
- [FOUR-12894](https://processmaker.atlassian.net/browse/FOUR-12894)
ci:deploy
ci:next
[FOUR-12894]: https://processmaker.atlassian.net/browse/FOUR-12894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12894:The design of process browser is different from the design of figma

resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json, resources/views/auth/2fa/auth_app_qr.blade.php
https://processmaker.atlassian.net/browse/FOUR-13074
=> FOUR-13074 The Google Authenticator APP screen does not have the same design as the mockup

ProcessMaker/Http/Controllers/Auth/TwoFactorAuthController.php
https://processmaker.atlassian.net/browse/FOUR-13109
=> FOUR-13109 Undefined array key 0 appear after disabling "Require Two Step Authentication" and clearing "Two Step Authentication Method"

composer.json, composer.lock, package-lock.json, package.json
The case number is not displayed in the Case Title column in a process with web entry.
- Update magic variable `_request` always to calculate `case_title`
- Import attached process 
- Copy web entry URL
- search process and edit
- Click on web entry 
- Go to configuration
- Click on web entry 
- Copy web entry URL
First scenario: Request in progress 
- Open web entry
- Open new browser
- Paste Url
- Fill any value in New Input field
- Click on submit button
- Go to PM4
- Click on Request tab
- Go to All request page
Second scenario: Request completed
- Open web entry
- Open new browser
- Paste Url
- Fill any value in New Input field
- Click on submit button
- Go to PM4
- Search last request of process
- Click on Form task
- Click on submit button
- Click on Request tab
- Go to All request …
=> FOUR-11530 Fix case number is not displayed in process with web entry or completed

resources/js/components/shared/IconDropdown.vue, resources/js/components/shared/ModalSaveVersion.vue
- [FOUR-13053](https://processmaker.atlassian.net/browse/FOUR-13053)
ci:deploy
ci:next
[FOUR-13053]: https://processmaker.atlassian.net/browse/FOUR-13053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13053:The default icon loses the text and image in Launch Pad

resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
Rename, In Request Table:
- Update column “Process Name” to “Process”
- Update column “Task Name” to “Task”
In Task Table
- Update column “Process Name” to “Process”
- Update column “Task Name” to “Task”
- Columns renamed
- Open Requests List
- Open Tasks List
- https://processmaker.atlassian.net/browse/FOUR-13104
ci:next
ci:deploy
=> FOUR-13104 Update columns titles in Request and Tasks

resources/js/processes-catalogue/components/menuCatologue.vue
- [FOUR-13105](https://processmaker.atlassian.net/browse/FOUR-13105)
[FOUR-13105]: https://processmaker.atlassian.net/browse/FOUR-13105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci: deploy
ci:next
=> FOUR-13105:Infinite scroll stop to work when resize the screen  on Launch Pad

resources/js/processes-catalogue/components/menuCatologue.vue
- [FOUR-13119](https://processmaker.atlassian.net/browse/FOUR-13119)
ci:deploy
ci:next
[FOUR-13119]: https://processmaker.atlassian.net/browse/FOUR-13119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13119: UI Separation between categories should be review

resources/lang/en.json
See https://github.com/ProcessMaker/modeler/pull/1758
Translations for modeler
=> Modeler Updates v2 - Translations

resources/js/components/shared/ModalSaveVersion.vue
the font size are different in the modal Version.
- Change styles
open process and publish changes, in the modal version review labels
- [https://processmaker.atlassian.net/browse/FOUR-12790](FOUR-12790)
ci:processmaker:next
=> The font-size of the labels in modal launch pad are different than Versioning modal

resources/js/processes-catalogue/components/WizardTemplates.vue
This PR updates the styling of the Guided Template search bar to match that of the Mockups.
- Add css to update styling
1. Navigate to Processes > Guided Templates
2. Ensure the Search Bar styling matches the mock up
- https://processmaker.atlassian.net/browse/FOUR-13172
ci:next
=> Match Guided Template Search Bar Mockups

resources/views/shared/users/sidebar.blade.php
An admin user should be able to change their password from their personal profile when "Password Set By User" is disabled
- Fix the conditional statement in the admin password change form
1. Login
2. Configure Password Set By User 
1. Go to admin tab
2. Go to setting option in sidebar menu
3. Click on Log-In Options
4. Disable Password Set By User
3. Create an user
4. Make admin to user
1. Go to admin option
2. Search user and edit
3. Go to permissions tab
4. Enable Make this user a Super Admin
5. Click on save button
5. Log in with new user
6. Go to avatar
7. Click on Edit admin Profile
8. The `New password` and `Confirm password` fields must be displayed 
[FOUR-13180](https://processmaker.atlassian.net/browse/FOUR-13180)
ci:next
ci:deploy
[FOUR-13180]: …
=> FOUR-13180  admin users should be able to change their password from their personal profile

ProcessMaker/Http/Controllers/Admin/UserController.php, ProcessMaker/Http/Controllers/Auth/TwoFactorAuthController.php, ProcessMaker/Http/Controllers/ProfileController.php, ProcessMaker/Models/User.php, ProcessMaker/TwoFactorAuthentication.php, database/migrations/2024_01_09_165046_add_preferences_2fa_column_to_users_table.php, resources/views/admin/users/edit.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/users/sidebar.blade.php
https://processmaker.atlassian.net/browse/FOUR-13085
ci:next
ci:deploy
ci:TWILIO_ACCOUNT_SID="ACf3487ba53a2b560c6a50625068fd7bc3"
ci:TWILIO_AUTH_TOKEN="15a5b1955d7ff6cc394caaa1f8b70b41"
ci:TWILIO_ACTIVE_PHONE_NUMBER="+12057511892"
=> FOUR-13085 A user cannot configure in their profile how to receive their OTP

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Replace Bookmark label
- Update the name
- https://processmaker.atlassian.net/browse/FOUR-13114
ci:next
ci:deploy
=> bugfix/FOUR-13114: Replace Bookmark label

.github/workflows/deploy-pm4.yml
Add phpunit config back into ci pipeline - next branch
ci:next
=> Enable phpunit - next

resources/js/components/PMColumnFilterPopover/PMColumnFilterForm.vue, resources/js/components/shared/PmqlInput.vue, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue, resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json
=> FOUR-13206 New Table and filters are not translated

resources/js/components/PMColumnFilterPopover/PMColumnFilterForm.vue, resources/js/components/PMColumnFilterPopover/PMColumnFilterPopover.vue
=> FOUR-13187 sort ascending always is focused

resources/js/processes-catalogue/components/charts/ListChart.vue
- Create a "ListChart" SavedSearch Chart with many rows
- Open Process with request in "Open in Launchpad"
- Select the "ListChart" previously created and Save the process
- Check The chart is working find
https://processmaker.atlassian.net/browse/FOUR-13208
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-13208: Adjust the height of the ChartList in the Chart section in Launchpad

resources/js/components/shared/IconDropdown.vue, resources/js/components/shared/IconSelector.vue, resources/js/components/shared/Icons.js, resources/js/components/shared/LaunchpadIcons.js
This PR addresses an issue where the Icon Select for PM Blocks was not loading icons. The problem occurred because the Icons.js file was overwritten with icons for the Launchpad, causing conflicts. 
To resolve this, the original icons for Icons.js were restored, and a separate file, LaunchpadIcons.js, was created and imported into the icon-dropdown component.
**PM Block Icons**
1. Create a Process.
2. Save the process as a PM Block via the process ellipsis menu.
3. Ensure the Icon Selector loads the proper icons.
4. Save the PM Block.
5. Navigate to PM Blocks.
6. Select 'Configure' in the ellipsis menu.
7. Ensure the proper icon is loaded.
8. Open Modeler.
9. Navigate to the PM Blocks tab.
10. Confirm that PM Block icons are loaded.
**Launch Pad Icons**
1. Navigate to Processes.
2. Select …
=> Fix Icon Loading Issue for PM Blocks

ProcessMaker/Http/Controllers/Auth/TwoFactorAuthController.php, ProcessMaker/TwoFactorAuthentication.php, resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json
https://processmaker.atlassian.net/browse/FOUR-13143
=> FOUR-13143 The message does not suggest other authentication possibilities

resources/js/components/PMColumnFilterPopover/PMColumnFilterPopover.vue
=> FOUR-13124 UI: The scroll of the filter section should be thinner

resources/js/components/PMColumnFilterPopover/PMColumnFilterForm.vue, resources/js/components/PMColumnFilterPopover/PMColumnFilterOpIn.vue
1. Go to page [https://ci-9d448ab1bf.eng.processmaker.net](https://ci-9d448ab1bf.eng.processmaker.net/requests)
2. Go to Request page
3. Open the filter view
The fields inside Filter view are using dynamic tags
- [FOUR-12797](https://processmaker.atlassian.net/browse/FOUR-12797)
ci:deploy
ci:next
[FOUR-12797]: https://processmaker.atlassian.net/browse/FOUR-12797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12797:Delete dynamic tags and add  tag in the all elements inside of Filter view

resources/views/shared/users/sidebar.blade.php
https://processmaker.atlassian.net/browse/FOUR-13085?focusedCommentId=380489
ci:next
ci:deploy
=> FOUR-13085 A user cannot configure in their profile how to receive their OTP - Observation by made Wendy solved

resources/js/components/shared/FilterTable.vue, resources/js/components/shared/FilterTableBodyMixin.js, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
saved search columns not previewed fix
A new method was added for nested properties
https://processmaker.atlassian.net/browse/FOUR-13103
ci:deploy
ci:next
=> FOUR-13103 saved search columns not previewed fix

.github/workflows/deploy-pm4.yml
https://github.com/ProcessMaker/processmaker/pull/6043 for next branch
ci:deploy
ci:next
=> Four 13153 FIX CICD - next

resources/js/components/templates/WizardTemplateCard.vue
This PR enhances the readability of the Guided Template select cards by implementing a color overlay. The overlay reduces the opacity of the background image, improving the visibility of the title and subtitle.
Changes include adding a pseudo :before class to the wizard-template-select-card and adjusting the opacity of the background image.
2. Observe the select cards.
3. Confirm that the color overlay enhances the readability of the title and subtitle on each card.
- https://processmaker.atlassian.net/browse/FOUR-13278
ci:next
=> Implement Color Overlay for Guided Template Select Cards

resources/js/tasks/components/TasksList.vue
=> FOUR-13287 Update columns in Task Table

resources/js/processes/categories/components/CategoriesListing.vue, resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
There is no option to sort ascending or descending in Process list
Add the option to sort ascending or descending in Process list
https://processmaker.atlassian.net/browse/FOUR-13168
https://processmaker.atlassian.net/browse/FOUR-13237
ci:next
=> observation/FOUR-13168 Add the option to sort ascending or descending in Process list

resources/js/components/AvatarImage.vue, resources/js/requests/components/RequestsListing.vue
Multiple participants not showing correctly
added a new avatar view mode
https://processmaker.atlassian.net/browse/FOUR-13276
ci:deploy
ci:next
=> observation/FOUR-13276 Multiple participants not showing correctly

resources/js/templates/assets.js
It is not possible to create a process from a template
- Add missing varible definition.
Create a new process from any template.
- https://processmaker.atlassian.net/browse/FOUR-13245
ci:next
ci:deploy
=> FOUR-13245 Define missing redirectTo variable

resources/js/common/PMColumnFilterPopoverCommonMixin.js, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
ci:next
ci:package-savedsearch:feature/FOUR-13043
=> FOUR-13043 Apply filtering to saved searches

resources/js/processes-catalogue/components/CardProcess.vue
In order to have a design alignment we need to update the Spinner design:
https://processmaker.atlassian.net/browse/FOUR-13335
ci:next
ci:deploy
=> feature/FOUR-13335: Update the Spinner in Launchpad

resources/js/processes/archived.js, resources/js/processes/components/ArchivedProcessList.vue, resources/js/processes/components/ProcessMixin.js, resources/js/processes/components/ProcessesListing.vue, resources/views/components/categorized_resource.blade.php
1.Log in
2.Go to Designer
3.Click on View all process
The process loading takes at least 10 seconds, the spinner is lost and shows the blank table for a few seconds
- [FOUR-13307](https://processmaker.atlassian.net/browse/FOUR-13307)
ci:deploy
ci:next
[FOUR-13307]: https://processmaker.atlassian.net/browse/FOUR-13307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13307:The process table takes at least 10 seconds to load processes

.github/workflows/scripts/translate.py
The translation script was returning an error.
The translation script was updated to comply with changes made to the OpenAI Python library.
- https://processmaker.atlassian.net/browse/FOUR-13273
=> [FOUR-13273] Update translation script

package-lock.json
=> Update Screen Builder to v2.82.0

resources/js/processes/screen-builder/typeDisplay.js, resources/lang/en.json
Use the correct description for Record Lists in Display screens
ci:next
=> Use the correct description for Record Lists in Display screens

resources/js/processes/designer/Assets.vue, resources/js/processes/designer/MyProject.vue
The Sections in Designer Welcome Screens are not aligned, 
- It should be aligned like figma Design
Login and go to Designer
- [FOUR-13377](https://processmaker.atlassian.net/browse/FOUR-13377)
ci:deploy
ci:next
[FOUR-13377]: https://processmaker.atlassian.net/browse/FOUR-13377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13377: The Sections in Designer Welcome Screens are not aligned

resources/js/processes/categories/components/CategoriesListing.vue
- Go to View all Processes
- Select Category tab
- Search some category
- Create many SAved Search Charts
- Go to Process Launchpad
- Open in Launchpad
- Check "Chart List"
https://processmaker.atlassian.net/browse/FOUR-13318
ci:deploy
ci:next
=> bugfix/FOUR-13318: The category search does not work.

resources/js/tasks/components/TasksList.vue
Please remove filter for test again.
=> FOUR-13415 Special Characters does not work correctly in Tasks page

resources/js/components/shared/PmqlInput.vue
Updating the query of the PmqlInput component placed the generated Pmql.
- Add a parameter for update query.
Search the mentioned sections and also review the ticket https://processmaker.atlassian.net/browse/FOUR-14004
- [https://processmaker.atlassian.net/browse/FOUR-14030](FOUR-14030)
- - [https://processmaker.atlassian.net/browse/FOUR-14004](FOUR-14004)
ci:next
ci:package-savedsearch:observation/FOUR-14030
ci:deploy
=> Search do not show the name written in the field

resources/js/components/shared/FilterTable.vue, resources/js/processes/categories/components/CategoriesListing.vue, resources/js/processes/components/ArchivedProcessList.vue, resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
multiple instances of the component repeat id's
Added an identifier for multiple instances of the table component
https://processmaker.atlassian.net/browse/FOUR-13973
ci:deploy
ci:next
=> observation/FOUR-13973-B Added an identifier for multiple instances of the table component

resources/js/components/shared/FilterTable.vue
- Update a user to use a different format
- Complete a process with date and datetime fields
- Add custom date and datetime columns to a saved search
- Dates are not in the selected format at Request and Task listing
=> FOUR-14062 Date columns are not showing in the user's format

resources/js/components/templates/mixins/wizardHelperProcessModal.js
This PR resolves an issue where the incorrect status "cancel" was displayed instead of "completed" after completing the "Re-run Wizard" request. The issue stemmed from the incorrect usage of the $this.close method, which updated the request status to "cancel" when the modal was closed by the user. The solution involves replacing the close method with the hide method for the modal.
- Implement .hide() method for Re-run Wizard modal
1. Ensure you have a Guided Template Process created.
2. Within the Launchpad of the process, select "Re-run Wizard."
3. Progress through the wizard and complete the request.
4. Once completed, navigate to "Requests -> All Requests."
5. Ensure the request displays the proper status "completed."
- [FOUR-14143](https://processmaker.atlassian.net/browse/FOUR-14143) …
=> Fix Incorrect Status Displayed After Completing "Re-run Wizard" Request

resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
See https://processmaker.atlassian.net/browse/FOUR-14096
Allows for saving advanced filters (column filters) in saved searches.
Requires: https://github.com/ProcessMaker/package-savedsearch/pull/413
ci:next
=> FOUR-14096 Save advanced filters in saved searches

resources/lang/en.json
The message is not shown translated.
- https://processmaker.atlassian.net/browse/FOUR-14083
ci:next
ci:deploy
=> feature/FOUR-14083: : "No results" message does not translate to launchpad

resources/js/components/common/DataLoading.vue, resources/js/tasks/components/TasksList.vue, resources/lang/en.json
New design for empty results in Tasks tables
Update the mesagge design for empty results in Tasks tables
https://processmaker.atlassian.net/browse/FOUR-14164
ci:deploy
ci:next
.
=> observation/FOUR-14164 Update the mesagge design for empty results in Tasks tables

resources/js/tasks/components/TasksList.vue
case_title not showing on savedsearch
added the case_title option formating the field
https://processmaker.atlassian.net/browse/FOUR-14181
ci:deploy
ci:next
=>  bugfix/FOUR-14181 fix case_title not showing on savedsearch

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Models/TaskDraft.php, database/factories/ProcessMaker/Models/TaskDraftFactory.php, database/migrations/2024_02_20_193849_create_task_drafts_table.php
Add task_drafts table and model
Add task_drafts table and model and factory
https://processmaker.atlassian.net/browse/FOUR-14128
ci:next
=> [SPRING feature/FOUR-14128] Add task_drafts table and model

resources/js/app-layout.js, resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue, resources/views/layouts/navbar.blade.php
Show the message when "Copy Link" in web entry
- Add the message in the copy link action
Go to modeler
Go to processes
- [FOUR-13732](https://processmaker.atlassian.net/browse/FOUR-13732)
ci:deploy
ci:next
ci:package-webentry:feature/FOUR-13732
[FOUR-13732]: https://processmaker.atlassian.net/browse/FOUR-13732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Show the message when "Copy Link" in web entry

resources/js/components/shared/PmqlInput.vue
- https://processmaker.atlassian.net/browse/FOUR-13713
- https://processmaker.atlassian.net/browse/FOUR-14163
- https://processmaker.atlassian.net/browse/FOUR-13719
- https://processmaker.atlassian.net/browse/FOUR-13723
- [core PR](https://github.com/ProcessMaker/processmaker/pull/6240)
- [package-ai PR](https://github.com/ProcessMaker/package-ai/pull/78)
ci:next
=> Task/FOUR-13713, Task/FOUR-14163

resources/js/processes-catalogue/components/CardProcess.vue
Launch Card - List 12 cards
-  List 12 cards
go to processes
- [FOUR-14192](https://processmaker.atlassian.net/browse/FOUR-14192)
ci:deploy
ci:next
[FOUR-14192]: https://processmaker.atlassian.net/browse/FOUR-14192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14192:UI: Launch Card - List 12 cards

resources/js/processes-catalogue/components/utils/Card.vue
- [FOUR-13810](https://processmaker.atlassian.net/browse/FOUR-13810)
ci:deploy
ci:next
[FOUR-13810]: https://processmaker.atlassian.net/browse/FOUR-13810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13810:UI: Launch Card - Bookmark and Bookmarked

resources/js/common/advancedFilterStatusMixin.js, resources/js/components/shared/FilterTable.vue, resources/js/tasks/components/TasksList.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php
Add Draft and Priority Tabs to Task List
Added a new Draft and Priority Tabs to Task List
https://processmaker.atlassian.net/browse/FOUR-14127
ci:next
=> [SPRING feature/FOUR-14127]  Add Draft and Priority Tabs to Task List

resources/js/components/shared/PmqlInput.vue
AI Migration to Microservice - AI Search
https://processmaker.atlassian.net/browse/FOUR-13472
- [package-ai PR](https://github.com/ProcessMaker/package-ai/pull/85)
ci:next
=> Epic/FOUR-13472: AI Migration to Microservice - AI Search

resources/js/components/requests/card.vue, resources/views/tasks/editMobile.blade.php
The interstitial screen not showing
- Start a process, fill in a form and submit to go to 
the next screen.
- [https://processmaker.atlassian.net/browse/FOUR-14248](FOUR-14248)
=> Interstitials not redirecting to next screen on mobile

resources/js/processes-catalogue/components/ProcessTab.vue
- https://processmaker.atlassian.net/browse/FOUR-13704
ci:deploy
ci:next
=> feature/FOUR-13704: UI: Process Information - Tabs

.github/workflows/deploy-pm4.yml
=> Fix FOUR-13939

.gitignore, config/filesystems.php
As a Designer I want to have the option to import Tables into Decision Tables from an Excel or CSV file
- Add a new storage to download the import file format
[FOUR-13425](https://processmaker.atlassian.net/browse/FOUR-13425)
https://github.com/ProcessMaker/package-decision-engine/pull/102
ci:next
ci:package-decision-engine:feature/FOUR-13425
[FOUR-13425]: https://processmaker.atlassian.net/browse/FOUR-13425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13425 import tables from excel

resources/js/processes/translations/components/CreateProcessTranslationModal.vue, resources/js/processes/translations/components/ProcessTranslationListing.vue
This PR add support for processing translation in the callback endpoint 
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-14246)
=> FOUR-14246: Backend - Remove images from html 

config/app.php, resources/views/processes/edit.blade.php
Add an extra env variable `OPEN_AI_PROCESS_TRANSLATIONS_ENABLED=false` to hide process translations
- https://processmaker.atlassian.net/browse/FOUR-14286
ci:next
ci:deploy
=> FOUR-14286: Add a variable to hide AI for Spring

ProcessMaker/Traits/HasUuids.php
This PR addresses a log error related to UUID generation when creating collection records. The error occurred due to the duplication of `generateUuid` method in the HasUuid file and in the collections package RecordObserver file. While this error did not affect functionality, it cluttered the logs unnecessarily.
- Modified conditional for the `generateUuid` method in the `HasUuid` trait to prevent UUID generation for collection records.
- Improved the original query to validate if the `uuid` property is set on the object before attempting to generate a UUID.
1. Ensure a collection is created.
2. Clear the logs.
3. Create a collection record.
4. Verify that no errors related to UUID generation are logged.
5. Ensure the creation process of collection records functions as expected.
- …
=> Fix UUID Generation Error for Collection Records

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Models/SettingsMenus.php, database/migrations/2024_02_26_182828_create_settings_menus_table.php, upgrades/2024_02_29_131833_populate_update_settings_menu.php
Add new colum **ui**
- https://processmaker.atlassian.net/browse/FOUR-11728
ci:next
ci:deploy
=> feature/FOUR-11728: Add new column ui

resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
- [FOUR-13836](https://processmaker.atlassian.net/browse/FOUR-13836)
ci:deploy
ci:next
ci:package-comments:feature/FOUR-13836
[FOUR-13836]: https://processmaker.atlassian.net/browse/FOUR-13836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13836: Collapsible Comments

resources/views/layouts/ai-qr-mobile.blade.php
This PR implements the mobile views based on the figma and camera/gallery features.
https://processmaker.atlassian.net/browse/FOUR-13863
https://www.figma.com/file/Tr2bVMtC4jr6KGWBvM6Vtp/Spring-24?type=design&node-id=9761-83380&mode=design&t=SCiaG5chHkL7cRkS-0
[package-ai PR](https://github.com/ProcessMaker/package-ai/pull/95)
=> Task/FOUR-13863: Style adjustments to fit last Figma modifications

resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
- [FOUR-14343](https://processmaker.atlassian.net/browse/FOUR-14343)
ci:deploy
ci:next
ci:package-comments:feature/FOUR-13461
[FOUR-14343]: https://processmaker.atlassian.net/browse/FOUR-14343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14343:Collapsible Comments - Review Styles

ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/ProcessTranslations/ProcessTranslation.php, composer.json, composer.lock, package-lock.json, package.json, resources/js/processes/translations/components/CreateProcessTranslationModal.vue, resources/js/processes/translations/components/ProcessTranslationListing.vue, resources/views/requests/show.blade.php, upgrades/2024_02_07_113706_web_entry_url_fixer.php
Package-AI is introducing the Image to Process project for which it needs a new overlay on the Process Preview page. This overlay handles the different choices the user has between models generated by AI from the image that they uploaded.
- The ModelerController has been modified to handle the new choices for Image to Process.
- https://processmaker.atlassian.net/browse/FOUR-13851
- https://github.com/ProcessMaker/package-ai/pull/99
=> FOUR-13851: Changed endpoint for choices in AI process previewer

.gitignore, config/filesystems.php
Includes the following improvements:
- Import from Excel
- Add calculated properties
- Columns resize
https://github.com/ProcessMaker/package-decision-engine/assets/8028650/5fbca3af-0da4-4dac-a1a2-91b5e65ea047
https://github.com/ProcessMaker/package-decision-engine/assets/8028650/5fbca3af-0da4-4dac-a1a2-91b5e65ea047
- https://processmaker.atlassian.net/browse/FOUR-13424
ci:deploy
ci:next
ci:package-decision-engine:feature/FOUR-13424
=> FOUR-13424 Decision Tables v3

.gitignore, config/filesystems.php
Reverts ProcessMaker/processmaker#6346
=> Revert "FOUR-13424 Decision Tables v3"

resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
- [FOUR-14356](https://processmaker.atlassian.net/browse/FOUR-14356)
ci:deploy
ci:next
ci:package-comments:feature/FOUR-13461
[FOUR-14356]: https://processmaker.atlassian.net/browse/FOUR-14356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> STORY Remove the Comments button

resources/js/components/shared/FilterTable.vue, resources/js/tasks/components/PreviewMixin.js, resources/js/tasks/components/TasksList.vue
Branch FOUR-14257 needs to be merged before this branch.
https://processmaker.atlassian.net/browse/FOUR-14116
ci:deploy
ci:next
=> FOUR-14116: Highlight selected row(s) while previewing task - saved search and task lists

ProcessMaker/Http/Controllers/Process/ModelerController.php
- add modeler data to the new blade template
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-11457)
=> add data to the custom blade modeler

ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Models/Process.php, resources/js/components/shared/Modal.vue, resources/js/components/shared/ModalSaveVersion.vue, resources/js/processes/components/CreateProcessModal.vue, resources/js/processes/modeler/components/ModelerApp.vue, resources/views/processes/modeler/index.blade.php
- Implements Versioning process Core integrations
[FOUR-14438](https://processmaker.atlassian.net/browse/FOUR-14438)
https://github.com/ProcessMaker/package-ab-testing/pull/12
ci:next
[FOUR-14438]: https://processmaker.atlassian.net/browse/FOUR-14438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14438 Versioning the process Core integration

resources/js/admin/settings/components/SettingsListing.vue, resources/js/admin/settings/components/SettingsMain.vue, resources/js/admin/settings/components/SettingsMenuCollapse.vue
- [FOUR-11730](https://processmaker.atlassian.net/browse/FOUR-11730)
ci:deploy
ci:next
[FOUR-11730]: https://processmaker.atlassian.net/browse/FOUR-11730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Email Layout - Action by email

resources/js/admin/settings/components/SettingsMenuCollapse.vue
- [FOUR-14389](https://processmaker.atlassian.net/browse/FOUR-14389)
ci:deploy
ci:next
[FOUR-14389]: https://processmaker.atlassian.net/browse/FOUR-14389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14389:Setting Menu: UI styles IDLE HOVE ACTIVE TAB

resources/js/admin/settings/components/SettingsListing.vue, resources/js/admin/settings/components/SettingsMain.vue, resources/js/admin/settings/components/SettingsMenuCollapse.vue
- [FOUR-13414](https://processmaker.atlassian.net/browse/FOUR-13414)
ci:deploy
ci:next
ci:connector-send-email:feature/FOUR-13414
[FOUR-13414]: https://processmaker.atlassian.net/browse/FOUR-13414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Log-In & Auth - SSO - ALL Option enabled with this

resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue
- [FOUR-14388](https://processmaker.atlassian.net/browse/FOUR-14388)
ci:deploy
ci:next
[FOUR-14388]: https://processmaker.atlassian.net/browse/FOUR-14388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14388: Process Browser: UI styles IDLE HOVE ACTIVE TAB

database/factories/ProcessMaker/Models/SettingFactory.php, database/factories/ProcessMaker/Models/SettingsMenusFactory.php, tests/Feature/Api/SettingsTest.php
Adding unit test
- https://processmaker.atlassian.net/browse/FOUR-13632
ci:next
=> FOUR-13632: Unit test

database/factories/ProcessMaker/Models/UserFactory.php, resources/js/admin/settings/components/cdata/OauthConnectionProperties.vue
We see that it shows us an error in the console, when it comes to copying the Redirect URL and  the URL is not copied..
The code was updated to use the navigator.clipboard function, which is already employed in other sections of the application for copying content to the clipboard.
https://github.com/ProcessMaker/processmaker/assets/90741874/db84482f-9730-46d1-ae91-ad4c4fa1cea2
1. Go to Admin - Settings
2. Go to External integrations 
3. Enable Gmail
4. Configure Gmail
5. Click on Copy redirect URL
- [FOUR-14482](https://processmaker.atlassian.net/browse/FOUR-14482)
[FOUR-14482]: https://processmaker.atlassian.net/browse/FOUR-14482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14482: Add copy functionality in External Integrations

resources/views/tasks/edit.blade.php
Task Actions - Full Task Edit Page
Added the new buttons style and priority functionality
https://processmaker.atlassian.net/browse/FOUR-14415
ci:deploy
ci:next
=> [SPRING] feature/FOUR-14415 Task Actions - Full Task Edit Page

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/js/components/shared/DownloadSvgButton.vue, resources/js/processes/components/CreateProcessModal.vue
Multiple fixes 
This PR implements
https://processmaker.atlassian.net/browse/FOUR-13871
[core PR](https://github.com/ProcessMaker/processmaker/pull/6443)
[package-ai PR](https://github.com/ProcessMaker/package-ai/pull/113)
=> Task/FOUR-13871: Implement history and choice navigator for images

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/js/components/shared/ModalSaveVersion.vue, resources/views/processes/modeler/index.blade.php
- https://processmaker.atlassian.net/browse/FOUR-14539
ci:deploy
ci:next
ci:package-ab-testing:feature/FOUR-14539
=> FOUR-14539 Improve the load of libraries in the iframe created to load the modeler used for the A/B Testing package

ProcessMaker/Filters/Filter.php
Fix tests by add additional operator and set a valid status code
=> Add additional operator and set a valid status code

.github/workflows/deploy-pm4.yml
=> Increase the timeout when creating and updating instances

resources/js/tasks/components/TasksList.vue
Go to Tasks, hover over one row and check the "eye" button with hand cursor.
https://processmaker.atlassian.net/browse/FOUR-14622
ci:deploy
ci:next
=> QA Observation: Bugfix/FOUR-14622

.github/workflows/deploy-pm4.yml
=> Fix SCO-22193 in CICD

resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessScreen.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/mixins/ProcessesMixin.js, resources/js/processes-catalogue/components/scss/processes.css, resources/js/processes-catalogue/components/utils/DisplayScreen.vue
- [FOUR-14561](https://processmaker.atlassian.net/browse/FOUR-14561)
ci:deploy
ci:next
[FOUR-14561]: https://processmaker.atlassian.net/browse/FOUR-14561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14561:Show the Screen in the Launchpad Information

resources/js/components/shared/InputImageCarousel.vue
After upload a big image in carousel does not work
- https://processmaker.atlassian.net/browse/FOUR-14661
ci:next
ci:deploy
=> feature/FOUR-14661: Launchpad Setup -  Validate the maximum file size 2Mb

resources/js/processes-catalogue/components/ProcessesCarousel.vue
After upload the embed URL we need to display this in the Carousel like:
- https://processmaker.atlassian.net/browse/FOUR-14701
ci:deploy
ci:next
=> feature/FOUR-14701: FOUR-13386 Carousel needs to show the Embed URL

resources/js/components/shared/ModalSaveVersion.vue
Fix error when publishing a process with AB testing not enabled
- https://processmaker.atlassian.net/browse/FOUR-14640
ci:next
ci:deploy
ci:package-ab-testing:FOUR-14640
.
=> FOUR-14640 Fix publish issues

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/Process.php, database/migrations/2024_03_28_164852_create_embed_table.php, routes/api.php
=> FOUR-14702

ProcessMaker/Jobs/BpmnAction.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Traits/HasVersioning.php, resources/js/components/shared/PmqlInput.vue, resources/js/processes/modeler/components/ModelerApp.vue, resources/js/processes/modeler/index.js
- https://processmaker.atlassian.net/browse/FOUR-14637
ci:next
ci:deploy
ci:package-testing:FOUR-14703
ci:package-ab-testing:FOUR-14637
ci:modeler:FOUR-14703
.
=> FOUR-11361 AB Alternatives and Testing v2 integration

resources/js/admin/settings/components/SettingDriverAuthorization.vue
We get an error on the screen when we start a request with a process that contains task Bamboo.
1. Click on Admin - Settings
2. Click on External Integrations
3. Enable Bamboo integration
4. Create a process
5. Place the respective query
6. Start a request
7. Open the request
- Send the formData directly from the frontend, without making additional transformations. In the AuthorizeRequest.php file, the `api` driver was manually added. This driver is not available for selection in the UI, as it is used internally exclusively for API profiles.
- Simply create a new bambooHR connection and a process and then conduct a manual test on the deployed CI Server.
- [FOUR-14569](https://processmaker.atlassian.net/browse/FOUR-14569)
- [Package CData …
=> FOUR-14569: Error when starting a request with task bamboo

resources/js/components/shared/LaunchpadSettingsModal.vue, resources/js/processes-catalogue/components/BaseChart.vue, resources/js/processes-catalogue/components/charts/PieChart.vue, resources/lang/en.json
- [FOUR-13900](https://processmaker.atlassian.net/browse/FOUR-13900)
ci:deploy
ci:next
[FOUR-13900]: https://processmaker.atlassian.net/browse/FOUR-13900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UI - The default chart needs to load when a Chart was not defined

ProcessMaker/Models/Setting.php, resources/js/admin/settings/components/SettingsMenuCollapse.vue
404 Error in SSO Integrations in Admin Settings 
- Use id instead of name
- Log in PM4
- Go to Admin Settings
- Click on SSO
- Enable any Integration like facebook
- https://processmaker.atlassian.net/browse/FOUR-14693
ci:next
ci:deploy
=> FOUR-14693

.github/workflows/deploy-pm4.yml
=> Fix SCO-22439 problem version AI

resources/js/components/shared/LaunchpadSettingsModal.vue, resources/js/processes-catalogue/components/BaseChart.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/lang/en.json
The user needs to have the posibility to select the Default value in the dropdowns after to select other specific value
- https://processmaker.atlassian.net/browse/FOUR-14717
ci:next
ci:deploy
=> feature/FOUR-14717: Launchpad Settings default values

resources/js/tasks/components/TasksList.vue
https://processmaker.atlassian.net/browse/FOUR-14617
ci:deploy
ci:next
=> Feature/FOUR-14617: Clicking on a quick fill row should open the preview

resources/views/tasks/edit.blade.php
UserInteractionListener needed on full task edit page
Added an UserInteractionListener
https://processmaker.atlassian.net/browse/FOUR-14646
ci:deploy
ci:next
=> [SPRING] feature/FOUR-14646 UserInteractionListener needed on full task edit page

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/ProcessLaunchpad.php, database/migrations/2024_04_01_161132_create_process_launchpad.php, resources/js/components/shared/LaunchpadSettingsModal.vue, resources/js/components/shared/ModalSaveVersion.vue, resources/js/processes-catalogue/components/BaseChart.vue, resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessScreen.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/utils/Card.vue, upgrades/2024_04_01_161132_populate_process_launchpad.php
Review the API used in Cards and Process Info
ci:next
ci:deploy
=> FOUR-14772: Review the API used in Cards and Process Info

resources/js/inbox-rules/components/Edit.vue, resources/js/inbox-rules/components/InboxRuleFilters.vue, resources/js/tasks/components/QuickFillPreview.vue
https://processmaker.atlassian.net/browse/FOUR-14767
ci:deploy
ci:next
=> Feature/FOUR-14767: Quick fill inbox rule not loading when Editing an existing inbox rule

resources/lang/de.json, resources/lang/es.json, resources/lang/fr.json
=> [FOUR-14179] Update translation strings

resources/js/processes/components/CreateProcessModal.vue
This PR fixes the observation https://processmaker.atlassian.net/browse/FOUR-14795
=> Observation/FOUR-14795: The name and description are not displayed when using the AI-generated process model

ProcessMaker/Http/Controllers/Api/InboxRulesController.php, ProcessMaker/Models/InboxRule.php, resources/js/inbox-rules/components/ColumnChooserAdapter.vue, resources/js/inbox-rules/components/Edit.vue, resources/js/inbox-rules/components/InboxRuleButtons.vue, resources/js/inbox-rules/components/InboxRuleEdit.vue, resources/js/inbox-rules/components/InboxRuleFilters.vue, resources/js/inbox-rules/components/InboxRules.vue, resources/lang/en.json
Modified columns are not saved when updating a rule.
- The different validations and strange behaviors have been corrected.
- Column editing is now saved in the database.
- The search field for Saved Search items has been improved.
- The sorting criteria has been improved.
=> FOUR-14615 Modified columns are not saved when updating a rule.

resources/js/components/shared/ModalSaveVersion.vue
- [FOUR-13850](https://processmaker.atlassian.net/browse/FOUR-13850)
ci:deploy
ci:next
[FOUR-13850]: https://processmaker.atlassian.net/browse/FOUR-13850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13850:Launch Settings - Behaviour in the PUBLISH action in Modeler

resources/js/processes/components/CreateProcessModal.vue
https://processmaker.atlassian.net/browse/FOUR-11383
https://www.figma.com/file/Tr2bVMtC4jr6KGWBvM6Vtp/Spring-24?type=design&node-id=1-12&mode=design&t=1qaRBFGxKqnmOuMp-0
[core PR](https://github.com/ProcessMaker/processmaker/pull/6445)
[package-ai PR](https://github.com/ProcessMaker/package-ai/pull/114)
ci:next
ci:deploy
ci:package-ai:epic/FOUR-11383
=> Epic/FOUR-11383: Create Process from Image v2

resources/js/components/shared/LaunchpadSettingsModal.vue, resources/js/components/shared/ModalSaveVersion.vue
- After publish the alternative info settings was not refreshed
- Fix some integration issues with Lauchpad
- https://processmaker.atlassian.net/browse/FOUR-14750
ci:deploy
ci:next
ci:package-ab-testing:FOUR-14750
=> FOUR-14750 Fix Publish Version Popup Issues

ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, resources/views/processes-catalogue/index.blade.php
Use Avatar is not visible in Screen Launcher Launchpad.
- https://processmaker.atlassian.net/browse/FOUR-14787
ci:next
=> feature/FOUR-14787: Use Avatar is not visible in Screen Launcher Launchpad

ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/views/processes-catalogue/index.blade.php
The bookmark is marked when a process is open from process list
- https://processmaker.atlassian.net/browse/FOUR-14813
ci:deploy
ci:next
=> feature/FOUR-14813: Process appears marked as bookmarked if these are open form process list

resources/js/components/shared/LaunchpadSettingsModal.vue, resources/js/components/shared/MultiThumbnailFileUploader.vue, resources/js/components/templates/PreviewTemplate.vue, resources/js/components/templates/ScreenTemplateCard.vue, resources/sass/app.scss
Ticket: [FOUR-14818](https://processmaker.atlassian.net/browse/FOUR-14818)
Some styles in the Create Screen Modal and Save as Screen Template Modal are being overwritten. 
- Add scope to the style tag in LaunchpadSettingsModal.vue
- Update font size and orientation of 'Set as Default Template' in Create Screen Modal
- Update padding at the bottom of the template description in Create Screen Modal
- Update template options spacing on Template Preview in Save as Screen Template Modal
- Update image-thumbnails-container styling in MultiThumbnailFileUploader
1. Go to branch `observation/FOUR-14818` in `processmaker`.
2. Go to Designer → Screens → +SCREEN.
- Ensure that the modal styles reflect the [Figma](https://www.figma.com/file/Tr2bVMtC4jr6KGWBvM6Vtp/Spring-24?type=design&node-id=1-14&mode …
=> FOUR-14818 | Resolve Styling Issues on Template Cards in Create Screen Modal

resources/views/requests/index.blade.php
- Login to PM4
- In Requests section tab "Inbox" should not be anymore
https://processmaker.atlassian.net/browse/FOUR-14707
ci:next
=> bugfix/FOUR-14707: The Request table shouldn't have the Inbox tab

resources/js/tasks/components/TasksPreview.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-14877
ci:next
=> Fix task preview height

resources/js/inbox-rules/components/InboxRuleEdit.vue
https://processmaker.atlassian.net/browse/FOUR-14786
Update notifications
=> FOUR-14786 Update notifications

resources/js/inbox-rules/components/InboxRules.vue
- Go to Tasks page
- Press Inbox rules button
https://processmaker.atlassian.net/browse/FOUR-14683
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-14683: Wrong message when there are not Inbox Rules

resources/views/tasks/edit.blade.php
- Create a normal user
- Create a Request with that normal user
- Open a task
https://processmaker.atlassian.net/browse/FOUR-14556
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-14556: Smart actions > buttons are not align correctly to a normal user

resources/views/tasks/edit.blade.php
Save Draft does not works when a Task was opened
Added new autosave validation for new tasks
https://processmaker.atlassian.net/browse/FOUR-14686
ci:deploy
ci:next
=> [SPRING] observation/FOUR-14686 Save Draft does not work when a Task was opened

ProcessMaker/Templates/ScreenTemplate.php, tests/Feature/Templates/Api/ScreenTemplateTest.php
Setting a default template for Public templates resets the default template for My templates to the blank template. This behavior occurs when a user selects a template other than the blank template as the default for My templates and then sets a default template for Public templates.
- Added a missing condition and a unit test to verify the correct behavior.
- Execute test on deployed QA server.
ci:deploy
ci:next
- [FOUR-14861](https://processmaker.atlassian.net/browse/FOUR-14861)
[FOUR-14861]: https://processmaker.atlassian.net/browse/FOUR-14861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14861: Setting Default Public Template Resets Default Template for My Templates

resources/js/common/PMColumnFilterPopoverCommonMixin.js, resources/js/inbox-rules/components/InboxRuleButtons.vue, resources/js/inbox-rules/components/InboxRuleFilters.vue
https://processmaker.atlassian.net/browse/FOUR-14713
Inbox Rule: `Clear unsaved filters` button does not workGo to server
1. Go to Tasks
2. Press Inbox Rule button
3. Press +Create Rule button
4. Select an option to Load a saved search button
5. Add some filters in the table result
6. Wait until filters are applying
7. Press Clear unsaved filters button
=> FOUR-14713 Inbox Rule: 'Clear unsaved filters' button does not work

resources/js/processes-catalogue/components/BaseChart.vue, resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/ProcessOptions.vue, resources/js/processes-catalogue/components/ProcessesCarousel.vue
Use Columns Bootstrap in order to define the alignment of elements in the differents windows sizes
Review the Launchpad in different windows size, the images can not overlap
- [FOUR-14852](https://processmaker.atlassian.net/browse/FOUR-14852)
ci:deploy
ci:next
[FOUR-14852]: https://processmaker.atlassian.net/browse/FOUR-14852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use Columns Bootstrap in order to define the alignment of elements in the differents windows sizes

resources/js/components/PMPopoverConfirmation.vue
https://processmaker.atlassian.net/browse/FOUR-14927
Inbox rule: buttons are defaced in the delete popup
=> FOUR-14927 Inbox rule: buttons are defaced in the delete popup

config/app.php
Update Analytics in Welcome Screen
- Create a new variable for define a different chart in the Default Welcome Home
- A new custom Analytics chart will create by default
1. Configure in the env.ini `PM_ANALYTICS_CHART=""`
2. Install the package `php artisan package-analytics-reporting:install`
3. The command `php artisan processmaker:update-analytics-link` will read the `PM_ANALYTICS_CHART` in order to update the link
4. Go to Admin -> Analytics Management, a new custom report `PM Analytics Chart,` the admin user can configure 
5. Go to Home -> the ANALYTICS CHART will show the chart defined in `PM_ANALYTICS_CHART`
- https://processmaker.atlassian.net/browse/FOUR-14520
ci:next
=> FOUR-14520: Update Analytics in Welcome Screen

resources/js/tasks/components/TasksList.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php
Inbox, Priority and Drafts tabs are not having counters
https://processmaker.atlassian.net/browse/FOUR-14712
ci:deploy
ci:next
=> observation/FOUR-14712 Inbox, Priority and Drafts tabs are not having counters

resources/js/tasks/components/QuickFillPreview.vue, resources/js/tasks/components/TasksPreview.vue
https://processmaker.atlassian.net/browse/FOUR-14930
**Quick fill: The user cannot close the second panel**
1. Create a Request
2. Open the Task
3. Press Create Rule button
4. Check Save and Reuse filled data option
5. Press next button
6. Press Quick Fill button
7. Wait for the first panel (cancel button closes the first panel)
8. Select one row in the first panel
9. Press over eye icon in the first panel
10. Press X button (second panel)
=> FOUR-14930 Quick fill: The user cannot close the second panel

resources/js/tasks/components/TasksList.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php
Reverts ProcessMaker/processmaker#6670
=> Revert "observation/FOUR-14712 Inbox, Priority and Drafts tabs are not having counters"

resources/js/tasks/components/TasksList.vue
- Go to Task Page
- Click on any row (blank spaces between columns) No action should be executed
- Only Hiperlinked columns should open new pages
https://processmaker.atlassian.net/browse/FOUR-14961
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-14961: Improve the Task Table behaivor

resources/js/components/shared/LaunchpadSettingsModal.vue
The upload images control in launch pad is incomplete
- [FOUR-14841](https://processmaker.atlassian.net/browse/FOUR-14841)
ci:deploy
ci:next
[FOUR-14841]: https://processmaker.atlassian.net/browse/FOUR-14841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14841:The upload images control in launch pad is incomplete

resources/js/processes-catalogue/components/BaseChart.vue, resources/js/processes-catalogue/components/ProcessesCarousel.vue, resources/js/processes-catalogue/components/optionsMenu/ProcessCounter.vue
Chart and carousel are not aligned in Launchpad
Go to Processes
Open a card
Review the Process Info
- [FOUR-14801](https://processmaker.atlassian.net/browse/FOUR-14801)
ci:deploy
ci:next
[FOUR-14801]: https://processmaker.atlassian.net/browse/FOUR-14801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14801:Chart and carousel are not aligned in Launchpad

resources/js/components/shared/LaunchpadSettingsModal.vue
Many images are displayed in carousel of launchpad
- [FOUR-14822](https://processmaker.atlassian.net/browse/FOUR-14822)
ci:deploy
ci:next
[FOUR-14822]: https://processmaker.atlassian.net/browse/FOUR-14822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14822: Many images are displayed in carousel of launchpad

resources/js/tasks/components/TasksList.vue
Task list tabs not working if the search is empty
https://processmaker.atlassian.net/browse/FOUR-15002
ci:deploy
ci:next
=> observation/FOUR-15002 Task list tabs not working if the search is empty

resources/js/processes/designer/RecentAssets.vue
1.Go to designer
2.Click on "Filter by type"
3.Select some assets
4.Click on search
https://processmaker.atlassian.net/browse/FOUR-14984
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-14948: "Filter by type" does not disappear when searching is pressed.

ProcessMaker/Http/Controllers/Api/InboxRulesController.php, resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksListCounter.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php
Includes
- https://github.com/ProcessMaker/processmaker/pull/6674
- https://github.com/ProcessMaker/processmaker/pull/6675
- https://github.com/ProcessMaker/processmaker/pull/6681
- https://github.com/ProcessMaker/processmaker/pull/6689
ci:next
...
=> Next round of fixes for Inbox Rules observations

ProcessMaker/Models/Bookmark.php, database/migrations/2024_04_17_110215_add_index_bookmarks_and_launchpad_table.php
Add some indexes for improve the queries
1. Have a lot of process
2. Go to Processes
- https://processmaker.atlassian.net/browse/FOUR-15093
ci:next
ci:deploy
=> FOUR-15093

resources/js/components/common/data-tree-toggle.vue, resources/js/processes/modeler/components/inspector/ConfigEditor.vue, resources/views/tasks/edit.blade.php, resources/views/tasks/editdata.blade.php
Data Browse: nodes do not have the correct site. Zoom in, zoom out and center canvas buttons are not work
toggle off the tree view
https://processmaker.atlassian.net/browse/FOUR-15050
ci:deploy
ci:next
=> observation/FOUR-15050 Data Browse

resources/sass/app.scss
Modal publish is overloap by AI pop up
- The publish the modal should not be overlaid by others
2. Open the process
3. Click on IA button 
4. Click on the Publish button
5. Verify the modal of the publish button 
- [FOUR-12814](https://processmaker.atlassian.net/browse/FOUR-12814)
ci:deploy
ci:next
[FOUR-12814]: https://processmaker.atlassian.net/browse/FOUR-12814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12814:Modal publish is overloap by AI pop up

resources/js/processes-catalogue/components/Breadcrumbs.vue
The breadcrumb from Processes is different to Requests.
- https://processmaker.atlassian.net/browse/FOUR-15235
ci:deploy
ci:next
=> feature/FOUR-15235: The breadcrumb from Processes is different to Requests

.github/workflows/deploy-pm4.yml
=> Test Ctt 62

.github/workflows/deploy-pm4.yml
=> Fix CTT-62 (pmai-system-next)

resources/js/processes/modeler/components/ModelerApp.vue
Alternative A overrides the changes in Alternative B
- Publish the correct BPMN alternative chosen according to the focused tab
https://github.com/ProcessMaker/processmaker/assets/3604190/f86d7148-e21a-44ee-be01-240ae7ad6f35
2. Add some start event in the process
3. Save the changes
4. Add Alternative B
5. Save the change as Alternative AB
6. Modify the alternative B Like add another start event 
7. Click on Alternative A
8. Click on publish button
9. Save the Alternative B
10. Verify in launch pad or in Requests 
11. Refresh the page in the process
[FOUR-15269](https://processmaker.atlassian.net/browse/FOUR-15269)
ci:next
[FOUR-15269]: https://processmaker.atlassian.net/browse/FOUR-15269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> FOUR-15269 alternative A overrides the changes in alternative B

resources/js/processes-catalogue/components/TaskTab.vue
https://processmaker.atlassian.net/browse/FOUR-15309
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-15309: Improve the Task Table behaivor in Launchpad

ProcessMaker/Http/Controllers/Api/TaskController.php
See FOUR ticket: https://processmaker.atlassian.net/browse/FOUR-15315
=> [FOUR-15315] Handle all exception types; return a generic error

resources/js/components/templates/TemplateSearch.vue, resources/lang/en.json
- Login as Designer
- Go to the Designer option
- Open new process
- The modal will show the Option “Generate from Text”
- The Label should be updated from  “Generate from Text” to  “Generate from AI”
https://processmaker.atlassian.net/browse/FOUR-15310
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-15310: Update the label of "Generate from Text" in processes

resources/js/tasks/components/QuickFillPreview.vue, resources/lang/en.json
Create a disclaimer for Quick fill when create a Rule
Create a disclaimer for Quick fill when create a Rule
https://processmaker.atlassian.net/browse/FOUR-15311
ci:deploy
ci:next
=> observation/FOUR-15311 Create a disclaimer for Quick fill when create a Rule

resources/views/layouts/preview.blade.php
- Log in 
- CLick on process
- Create a new  process 
- Create some controls  in modeler 
- Form Task 
- Manual task 
- Add  screen in this  task
- click on form task  or  maual task 
- Clcik on preview  eye
- Added blobs to SCP of preview panel
https://processmaker.atlassian.net/browse/FOUR-15103
ci:next
ci:deploy
=>   FOUR-15103: Error in the console, when we click on preview of windows pane, with form and manual task

ProcessMaker/Traits/TaskControllerIndexMethods.php
See https://processmaker.atlassian.net/browse/FOUR-15316
Fixes ordering by JSON columns in the task list
ci:next
.
=> Fix order by data columns

resources/js/common/PMColumnFilterPopoverCommonMixin.js, resources/js/tasks/components/TasksList.vue
In Tasks list, the columns that has links, direct to the case and not to the task.
The Column Task should re direct to the Task (form) in order to open it faster.
- change  task_title by element _title in task list list
[element_title_link.webm](https://github.com/ProcessMaker/processmaker/assets/1401911/cb1f082e-6d84-4835-8bc2-d3415450c026)
1. Open Tasks in platform
2. The Column Task should re direct to the Task (form) in order to open it faster.
- https://processmaker.atlassian.net/browse/FOUR-15323
ci:next
=> FOUR-15323: Add a link to the Task column in tasks tab

ProcessMaker/Traits/TaskControllerIndexMethods.php
https://processmaker.atlassian.net/browse/FOUR-15332
Fix sorting for status, assignee.
Refactor data sorting to handle null and non-existing keys.
Requires: https://github.com/ProcessMaker/package-savedsearch/pull/434
ci:next
ci:package-savedsearch:bugfix/FOUR-15332
=> Add status and assignee sorting. Refactor data sorting

resources/js/inbox-rules/components/InboxRuleFilters.vue
Filter are not working according to "Load a saved Search" field.
1. Go to Tasks page
2. Press Inbox Rules button
3. Press Create Rule button
4. Select Completed option in the Load a saved Search field
5. Check the filters
- The default "In Progress" status filter was removed because it is already included in the PMQL search query, making it redundant.
https://github.com/ProcessMaker/processmaker/assets/90741874/bb5db81d-030e-4994-b776-099f7b074156
- Please follow the steps of above.
- It is necessary to check if it is truly essential to maintain the "In Progress" status filter, as although this resolves the ticket issue, no indications were found that it could cause a regression after checking elsewhere.
ci:next
- [FOUR-15322](https://processmaker.atlassian.net/browse/FOUR-15322) …
=> FOUR-15322: Inbox Rule > filters are not working when a Save search is selected 

resources/js/tasks/components/TaskSaveNotification.vue
In the task preview the task names are not displayed correctly.
fix the element name render on the task preview
https://processmaker.atlassian.net/browse/FOUR-15351
ci:deploy
ci:next
=> bugfix/FOUR-15351 In the task preview the task names are not displayed correctly.

.github/workflows/deploy-pm4.yml
Pull repository name on manually run workflows.
=> Coverage on workflow call

resources/js/inbox-rules/components/InboxRuleEdit.vue, resources/lang/en.json
https://processmaker.atlassian.net/browse/FOUR-15361
- Improve message to be cohesive: 
The new message should be: “ Please take a look at it in the 'Rules' section located within your Inbox”
ci:next
=> FOUR-15361 Improve message to be cohesive.

ProcessMaker/Jobs/SyncScreenTemplates.php
This PR resolves a media sync issue for default screen templates created by the PLG Team. Previously, the preview images for a screen template were displaying out of order. The order of each image is defined within the image name (e.g., preview1.jpeg, preview2.jpeg), and it's crucial for maintaining consistency and clarity in template previews.
The solution involves extracting the order index from the image name and setting the media `order_column` accordingly after importing the media. By doing so, the preview images are displayed sequentially in the order presented in the image names.
1. Locate the template within the [screen-template](https://github.com/ProcessMaker/screen-templates/pull/1/files#diff-7ec24e9865fb90a091b48f5cdd97e64ea612a40dd2798698cb60570fff7856ee) GitHub repository. …
=> Resolve Media Sync Issue for Default Screen Templates

resources/js/components/AvatarImage.vue, resources/js/components/shared/FilterTableBodyMixin.js, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-15370
- Fix request row clickable in Firefox
- Make participant and assignee names clickable
ci:next
=> Fix row clicking and make username clickable

resources/views/processes/modeler/inflight-generative-ai.blade.php
- Log in 
- Click on Designer
- Click on Process 
- Create a new process  ( open the modeler) 
- Click on Create a Process  with  AI
- place a BPMN design for example inventory control system
- Clcik on Generate
As we see, when generating a process model from the AI, we get a message in the console. 
Clicking on USE MODEL< shows the error again
- Added to inflight generative ai modeler a check in the same way was added in inflight to verify if scripts are coming from package-ab-testing
- [FOUR-15381](https://processmaker.atlassian.net/browse/FOUR-15381)
ci:next
[FOUR-15381]: https://processmaker.atlassian.net/browse/FOUR-15381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-15381: Error in the console when creating a process design from the AI

resources/js/processes/designer/RecentAssets.vue
List is not updated automatically, we need to click on an arrow for filtering on the table to update it.
- https://processmaker.atlassian.net/browse/FOUR-15393
ci:deploy
ci:next
=> bugfix/FOUR-15393: Welcome Screen Filtering Project Assets is Not Very Automatic

resources/views/tasks/preview.blade.php
https://processmaker.atlassian.net/browse/FOUR-15419
**Validations rules not working in preview tasks.**
1. Create a request
2. Go to tasks
3. Click on preview
4. Click on submit
The task is completed without taking into account the validation rules.
**Note:**
Please, it is necessary to perform a test of the following issue: 
https://processmaker.atlassian.net/browse/FOUR-15037
ci:next
=> FOUR-15419 Validations rules not working in preview tasks.

resources/js/processes-catalogue/components/utils/SearchCategories.vue
The Available Proceess is very close to Search Categories
Added a bottom margin
https://processmaker.atlassian.net/browse/FOUR-15434
ci:deploy
ci:next
=> bugfix/FOUR-15434 The Available Proceess is very close to Search Categories

resources/views/requests/show.blade.php
Overview is overlapping the history in requests completed.
1. Create a process with large name like “TCP4-3451 Completed Task Review Options and Actions in Task Configured with No Assignment Rules Toggled In-Flight Map“
2. Add Start Event → Task Form → End Event
3. Complete the request 
4. Check the history
5. Go to Overview
- Removed fixed height from the Overview Tab.
- Follow the reproduction steps of above.
ci:next
ci:deploy
- [FOUR-15478](https://processmaker.atlassian.net/browse/FOUR-15478)
[FOUR-15478]: https://processmaker.atlassian.net/browse/FOUR-15478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15478: Overview is overlapping the history in requests completed

resources/js/components/common/mixins/datatable.js
Script/Screens search does not work from the second page
change to the first page when there is a search
https://processmaker.atlassian.net/browse/FOUR-15454
ci:deploy
ci:next
=> bugfix/FOUR-15454 Script/Screens search does not work from the second page

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, ProcessMaker/Models/Media.php, resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json
When you upload more than 1 file running a test, you will get a 404 error after submitting the form
- Put the File Preview and File Download controls into a Loop control
- Add a validation to files as an instance of Media
https://github.com/ProcessMaker/processmaker/assets/3604190/ec011df0-aa07-42c1-9442-72cc4fbc2fcd
[FOUR-15485](https://processmaker.atlassian.net/browse/FOUR-15485)
ci:next
ci:deploy
[FOUR-15485]: https://processmaker.atlassian.net/browse/FOUR-15485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15485 37736 - Runing a test case gives 404 error with multiple file upload

ProcessMaker/Http/Controllers/Api/ProcessController.php
- Create a process with Alternative A,B
- In alternative A add some controls
- In alternative B should be empty 
- Create a IA process from alternative B
- Complete the creation of alternative B
- Check both alternatives
The process was crated from alternative B , but it always replace the alternative A 
The process generated by IA should be replace in the alternative that was created
- Pass alternative when using model
- Fix issue getting last session history
- [FOUR-15458](https://processmaker.atlassian.net/browse/FOUR-15458)
- [core PR](https://github.com/ProcessMaker/processmaker/pull/6844)
- [package-ai PR](https://github.com/ProcessMaker/package-ai/pull/161)
- [modeler …
=> Observation/FOUR-15458: Alternative A is overwritten by an AI process created from alternative B

ProcessMaker/ImportExport/Exporters/ExporterBase.php
- Log in 
- create a  new process  with  save  launchpad
- create a  new  template  with that process
- create a new process
- search the template created 
https://processmaker.atlassian.net/browse/FOUR-15404
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-15404: When creating a process from a template, Launchpad settings are shown with the Unknown label

resources/js/processes/designer/Assets.vue
This PR implements the feature for the ticket https://processmaker.atlassian.net/browse/FOUR-16005
Added the new Flow Genie button in the assets button in designer view
ci:next
=> Task/FOUR-16005: FOUR-15549: Add new FlowGenie to designer section (FE)

resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/ProcessOptions.vue, resources/js/processes-catalogue/components/ProcessesCarousel.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/optionsMenu/ChartSaveSearch.vue, resources/js/processes-catalogue/components/optionsMenu/ProcessDescription.vue
- After clicking an Image from Carousel, the carousel should occupy all the screen
- Go to Launchpad
- Create or select a process with carousel images
- Click some image from Carousel
https://processmaker.atlassian.net/browse/FOUR-16111
ci:deploy
ci:next
=> Feature/FOUR-16111: Update Carousel Behavior (UI Updates)

ProcessMaker/Helpers/MobileHelper.php, ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, ProcessMaker/Models/Process.php, resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/js/processes-catalogue/components/utils/Card.vue, resources/lang/en.json, resources/sass/_variables.scss, resources/views/layouts/navbarMobile.blade.php, resources/views/processes-catalogue/mobile.blade.php, webpack.mix.js
See https://processmaker.atlassian.net/browse/FOUR-16139
- Format the process browser for mobile
- Ensure both mobile and desktop versions work as described in the PRD and Figmas
- https://processmaker.atlassian.net/browse/FOUR-16139
ci:next
=> FOUR-16139: Format the launchpad process list for mobile

resources/js/components/shared/index.js
Add the hover for preview
- [FOUR-15779](https://processmaker.atlassian.net/browse/FOUR-15779)
ci:deploy
ci:next
ci:screen-builder:feature/FOUR-15779
[FOUR-15779]: https://processmaker.atlassian.net/browse/FOUR-15779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15779: Review the Hover action preview button Tasks

resources/js/bootstrap.js, resources/views/processes/modeler/index.blade.php, webpack.mix.js
Create the main component to show the header, process map and preview
- Add support to composition API with packages
Only with package slideShow
https://processmaker.atlassian.net/browse/FOUR-15921
ci:deploy
ci:next
ci:package-slideshow:feature/FOUR-15921
=> FOUR-15921: update file for using composition API in packages

resources/js/components/shared/FilterTable.vue
Pagination is not displayed in the Data Connectors page
Changed the pagination component in the Data Sources list
https://processmaker.atlassian.net/browse/FOUR-16543
ci:next
ci:deploy
=> [SUMMER] observation/FOUR-16543 Changed the pagination component in the Data Sources list

composer.json
- https://processmaker.atlassian.net/browse/FOUR-16541
=> FOUR-16541 Rename customer-adoa to package-zj-adoa

config/services.php, resources/views/auth/newLogin.blade.php, resources/views/layouts/layout.blade.php, resources/views/layouts/minimal.blade.php
This PR serves as the Epic branch for the accessibility package and includes all merged User Stories and tasks related to accessibility. The goal is to centralize all accessibility-related work in preparation for merging summer features into the next branch.
- [FOUR-15582](https://processmaker.atlassian.net/browse/FOUR-15582)
- https://github.com/ProcessMaker/processmaker/pull/6866
ci:next
[FOUR-15582]: https://processmaker.atlassian.net/browse/FOUR-15582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EPIC FOUR-15582: Accessibility Package Integration

resources/js/models/AssetTypes.js
- [FOUR-16052](https://processmaker.atlassian.net/browse/FOUR-16052)
- Added UI and methods that call endpoints to create a new FlowGenie and redirect to the edit page
https://github.com/ProcessMaker/package-ai/pull/180
https://github.com/ProcessMaker/processmaker/pull/6922
ci:next
ci:package-ai:task/FOUR-16052
[FOUR-16052]: https://processmaker.atlassian.net/browse/FOUR-16052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> task/FOUR-16052: Added quick create for flowgenies in inspector

.github/workflows/deploy-pm4.yml
Develop automated API tests to ensure the performance and reliability of the Task endpoint under various scenarios.
Create a PR with the next keywords: 
ci:api-test
ci:api-test-saved-searches-results
ci:api-test-saved-searches-charts
ci:api-test-tasks-closed
ci:api-test-requests-show
ci:api-test-iterations:XX
https://processmaker.atlassian.net/browse/FOUR-15870
ci:deploy
ci:pm4-api-testing:FOUR-15870
ci:api-test
=> FOUR-15870 Implement Automated API Testing for Task Endpoint

ProcessMaker/Console/Commands/BuildScriptExecutors.php, ProcessMaker/ScriptRunners/Base.php
- Use nayra engine to run the script watchers to improve its performance
- Use new micro service to run scripts
- https://processmaker.atlassian.net/browse/FOUR-15873
=> FOUR-15873 Enhance Script Watcher Endpoint Performance

ProcessMaker/PackageHelper.php
- [FOUR-16070](https://processmaker.atlassian.net/browse/FOUR-16070)
- [FOUR-16068](https://processmaker.atlassian.net/browse/FOUR-16068)
- Added PackageAi to the PackageHelper
- https://github.com/ProcessMaker/package-ai/pull/193
- https://github.com/ProcessMaker/package-projects/pull/113
ci:next
[FOUR-16070]: https://processmaker.atlassian.net/browse/FOUR-16070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-16068]: https://processmaker.atlassian.net/browse/FOUR-16068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> task/FOUR-16070: Added PackageAI to PackageHelper

public/definitions/ProcessMaker.xsd
Create a new configuration toogle in the task called "Action By Email"
- https://processmaker.atlassian.net/browse/FOUR-15821
ci:deploy
ci:next
ci:connector-send-email:feature/FOUR-15821
ci:processmaker-bpmn-moddle:feature/FOUR-15821
=> FOUR-15821: Create a new configuration

resources/js/requests/components/RequestsListing.vue
Duplicate sorting icon in the Requests page
remove the duplicate sorting icon on requests list
https://processmaker.atlassian.net/browse/FOUR-16529
=> observation/FOUR-16529 Duplicate sorting icon in the Requests page

resources/js/common/PMColumnFilterPopoverCommonMixin.js
Sorting icon is not displayed in the Process column
fix column sorting style when exists a order_column.
https://processmaker.atlassian.net/browse/FOUR-16528
=> observation/FOUR-16528 Sorting icon is not displayed in the Process column

ProcessMaker/Http/Controllers/Api/TaskController.php, database/migrations/2024_06_14_143814_add_index_to_updated_at_column_for_process_request_tokens_table.php
This PR fixes the ticket [FOUR-16575](https://processmaker.atlassian.net/browse/FOUR-16575)
- Add index to updated_at column to fix issue with out of memory
- Add pagination to task list to fix issue with out of memory
- [FOUR-16575](https://processmaker.atlassian.net/browse/FOUR-16575)
[FOUR-16575]: https://processmaker.atlassian.net/browse/FOUR-16575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-16575]: https://processmaker.atlassian.net/browse/FOUR-16575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-16575: Getting OOM Memory Failueres when Calling Tasks API Endpoint

resources/js/components/shared/FilterTable.vue, resources/js/requests/components/RequestsListing.vue
Alternative column does not have the new UI in Requests page
Added badges for Alternatives column in the request lists
https://processmaker.atlassian.net/browse/FOUR-16525
=> observation/FOUR-16525 Alternative column does not have the new UI in Requests page

resources/views/tasks/edit.blade.php
Task Panel: Process Name - Launchpad access
added the launchpad access in the task right side bar
https://processmaker.atlassian.net/browse/FOUR-15731
ci:next
=> feature/FOUR-15731 Task Panel: Process Name - Launchpad access

ProcessMaker/Models/Media.php, database/migrations/2024_06_18_191149_create_process_slideshow.php
Adding a new table process_slideshow
- https://processmaker.atlassian.net/browse/FOUR-16549
ci:next
=> FOUR-16549: Adding a new table process_slideshow

resources/js/requests/components/RequestsListing.vue
Performance problems in endpoint **/api/1.0/saved-searches/XYZ/results**
- Endpoint improved, the results are converted to json and string twice for each row
Create a saved serach for an user with a lot of requests and tasks.
- https://processmaker.atlassian.net/browse/FOUR-15876
=> FOUR-15876 Improve Saved Search Get Records Endpoint

resources/js/components/shared/EllipsisMenu.vue, resources/js/components/shared/PaginationTable.vue, resources/js/tasks/components/TaskListRowButtons.vue
Options Ellipsis on Processes page
ellipsis menu button focus style adjust, change the color of the task hover options icons, Adjust pagination styles for smaller displays
https://processmaker.atlassian.net/browse/FOUR-16742
=> feature/FOUR-16742 Options Ellipsis on Processes page

ProcessMaker/Http/Controllers/Api/BookmarkController.php, ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, ProcessMaker/Traits/ProcessTrait.php, resources/js/processes-catalogue/components/Process.vue, resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessHeader.vue, resources/views/layouts/navbarMobile.blade.php
Fixes these observations:
- https://processmaker.atlassian.net/browse/FOUR-16820
- https://processmaker.atlassian.net/browse/FOUR-16824
- https://processmaker.atlassian.net/browse/FOUR-16827
ci:next
=> Fix launchpad QA Observations

resources/js/processes-catalogue/components/optionsMenu/ProcessDescription.vue, resources/lang/en.json
- Select a process
- Configure process with long text
- Check the proces Header (must be truncated) and Process Name above Details section must be completed and with Bold text.
https://processmaker.atlassian.net/browse/FOUR-16113
ci:next
=> feature/FOUR-16113: Show the complete name of the process (UI Design)

ProcessMaker/Listeners/CommentsSubscriber.php
Show if the case history was updated by action by email
- [FOUR-15983](https://processmaker.atlassian.net/browse/FOUR-15983)
ci:deploy
ci:next
[FOUR-15983]: https://processmaker.atlassian.net/browse/FOUR-15983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15983: Show if the case history was updated by action by email

ProcessMaker/Jobs/SmartInbox.php, ProcessMaker/Providers/RecommendationsServiceProvider.php, tests/unit/ProcessMaker/RecommendationEngineTest.php
https://processmaker.atlassian.net/browse/FOUR-16992
Fix failing test
ci:next
=> FOUR-16992 Fix Recommendation Test

ProcessMaker/Helpers/DefaultColumns.php, ProcessMaker/Http/Controllers/Api/InboxRulesController.php, ProcessMaker/Http/Controllers/InboxRulesController.php, ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Http/Controllers/TaskController.php, resources/js/components/Recommendations.vue, resources/js/components/shared/index.js, resources/js/inbox-rules/components/InboxRuleFilters.vue, resources/js/tasks/components/TasksList.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php
Fixes
- https://processmaker.atlassian.net/browse/FOUR-13467
- https://processmaker.atlassian.net/browse/FOUR-13466
To test, follow the instructions in [the recommendations PR](https://github.com/ProcessMaker/processmaker/pull/6999)
ci:next
=> FOUR-13467 Recommendations UI Updates

resources/js/components/shared/ellipsisMenuActions.js, resources/js/components/shared/flowGenieNavigation.js, resources/js/processes/designer/RecentAssetsList.vue
**This PR implements the following ticket**
[FOUR-16094](https://processmaker.atlassian.net/browse/FOUR-16094)
This PR implements all the necessary to include FlowGenie as part of projects.
Related PR's:
- [package-ai PR](https://github.com/ProcessMaker/package-ai/pull/219)
- [core PR](https://github.com/ProcessMaker/processmaker/pull/7039)
- [package-projects PR](https://github.com/ProcessMaker/package-projects/pull/116)
ci:next
[FOUR-16094]: https://processmaker.atlassian.net/browse/FOUR-16094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Task/FOUR-16094: FOUR-15549: Adjustments to allow add to project to FlowGenies (BE)

routes/engine.php, routes/web.php
- https://processmaker.atlassian.net/browse/FOUR-16355
ci:next
=> FOUR-16355

ProcessMaker/Console/Commands/SyncRecommendationsCommand.php, ProcessMaker/Console/Kernel.php, ProcessMaker/Jobs/SyncRecommendations.php
Delay the sync a random number of minutes so we don't hit github API limits
ci:next
=> Delay recommendations sync

ProcessMaker/Repositories/TokenRepository.php, tests/Feature/Api/ProcessRequestsTest.php
- https://processmaker.atlassian.net/browse/FOUR-17011
ci:next
=> FOUR-17011

resources/js/Mobile/Card.vue, resources/js/Mobile/FilterMobile.vue, resources/js/components/PMTabs.vue, resources/js/processes-catalogue/components/CreateSavedSearchTab.vue, resources/js/processes-catalogue/components/ProcessTab.vue, resources/js/requests/components/RequestsListing.vue
https://processmaker.atlassian.net/browse/FOUR-16919
Add Saved searches tabs
This changes fixes https://processmaker.atlassian.net/browse/FOUR-17020
ci:next
=> FOUR-16919 Add Saved searches tabs

ProcessMaker/ApplyRecommendation.php, ProcessMaker/Http/Resources/V1_1/TaskResource.php, ProcessMaker/InboxRules/ApplyAction.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Notifications/ApplyActionNotification.php, ProcessMaker/RecommendationEngine.php, resources/lang/en.json
See https://processmaker.atlassian.net/browse/FOUR-17104
ci:next
=> Notify the user when the task can not be reassigned

resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessTab.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue, resources/js/requests/components/RequestsListing.vue
https://processmaker.atlassian.net/browse/FOUR-16923
Search option (Mobile)
ci:next
=> FOUR-16923 Search option (Mobile) small corrections

resources/js/requests/components/RequestDetail.vue
When a request is completed with Action by email the tag EMAIL is not showed
- [FOUR-17155](https://processmaker.atlassian.net/browse/FOUR-17155)
ci:next
[FOUR-17155]: https://processmaker.atlassian.net/browse/FOUR-17155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17155:When a request is completed with Action by email the tag EMAIL is not showed

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/js/templates/components/ProcessTemplatesListing.vue
This PR fixes the following observation
[FOUR-16887](https://processmaker.atlassian.net/browse/FOUR-16887)
This PR adds the new documentation style for process templates
[package-ai PR](https://github.com/ProcessMaker/package-ai/pull/239)
[core PR](https://github.com/ProcessMaker/processmaker/pull/7098)
ci:next
ci:package-ai:observation/FOUR-16887
[FOUR-16887]: https://processmaker.atlassian.net/browse/FOUR-16887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-16887: Improvement-The documentation of the templates should have a new format

resources/views/admin/users/edit.blade.php
This PR fixes the following observation
[FOUR-17238](https://processmaker.atlassian.net/browse/FOUR-17238)
ci:next
[FOUR-17238]: https://processmaker.atlassian.net/browse/FOUR-17238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-17238: "This action is unauthorized." Message with specific permissions for flowGenie.

resources/js/processes/designer/Assets.vue
This PR fixes the observation https://processmaker.atlassian.net/browse/FOUR-17302
ci:next
=> Observation/FOUR-17302: Change FlowGenies for FlowGenie in the Home Screen to keep consistency in the platform

ProcessMaker/Jobs/SyncGuidedTemplates.php, ProcessMaker/Models/WizardTemplate.php, resources/js/components/shared/Modal.vue, resources/js/components/templates/WizardHelperProcessModal.vue, resources/js/components/templates/WizardTemplateDetails.vue, resources/sass/app.scss
This PR updates the design of the first slide in the Guided Template, incorporating a new background, layout, and handling of template details attributes during the sync process.
- Updated slide background for the first Guided Template slide.
- Revised the layout of the first Guided Template slide.
- Modified the Guided Template sync method to accommodate new template details attributes.
1. Ensure you are on the branch `task/FOUR-16897` in the [wizard-template](https://github.com/ProcessMaker/wizard-templates/pull/80
2. Sync the Guided Templates using the sync method `php artisan processmaker:sync-guided-templates`.
3. Navigate to the Guided Template section.
4. Open the first slide of the Guided Template.
5. Verify that the slide displays the updated background and layout.
6. Confirm …
=> Implement New Guided Template Slide Design for the First Slide

resources/js/processes-catalogue/components/ProcessScreen.vue
- The reported issue was fixed according Mockups in Figma for Launch Screen
- Login to PM4
- Create a New Process
- Save and Publish and select some previous screens create in option "Launch Screen"
- Go to processes and click on previous created process
- Screen must have the correct design according mockups
https://processmaker.atlassian.net/browse/FOUR-17019
ci:next
=> QA Observation bugfix/FOUR-17019: Content of custom screen has an incorrect design

resources/js/components/shared/PmqlInput.vue
Please see https://processmaker.atlassian.net/browse/FOUR-15004
To reproduce:
- Create a screen 
- Add an input with a default and name it **user** (you can use your custom example)
- Add a select list of type data connector (you can use the users endpoint)
- Configure Options Variable: response.data
- Type of Value Returned: Object
- Content {{data.username}}
- Data connector: Users
- Endpoint ListAll
- Add a PMQL: **data.username="{{user}}"** (user is the name of the input you added before)
- Go to preview and type some valid user in the input to make the pmql trigger and change the option list of the select
https://github.com/ProcessMaker/processmaker/assets/90727999/2fa1ce60-a5e5-44b8-9d45-4389aa603c6a
- Fix PMQL render and code refactor for dataconnector
- Fix issue …
=> Bugfix/FOUR-15004: PMQL in record list doesnt work with pm variables

resources/js/processes-catalogue/components/ProcessTab.vue, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
Pagination and No item to show image are not displayed
changed the defaulot tab no result image
Create a simple process
Go to processes menu
Search and open the process
Select my tasks option
https://processmaker.atlassian.net/browse/FOUR-17015
ci:next
=> observation/FOUR-17015 Pagination and No item to show image are not displayed

resources/js/requests/components/NavbarRequestMobile.vue, resources/views/requests/showMobile.blade.php
- Tabs tasks and summary were modified in details section
- Header text was centered in navbar mobile in details section
- Cancel Case button has the correct color
- Open PM in mobile mode
- Go to Cases
- Select Some case
https://processmaker.atlassian.net/browse/FOUR-17193
ci:next
=> QA Observation Bugfix/FOUR-17193: Mobile > Case Detail is not having the correct styles

ProcessMaker/Http/Controllers/TaskController.php, resources/js/tasks/components/NavbarTaskMobile.vue, resources/js/tasks/components/PreviewMixin.js, resources/js/tasks/components/TaskDetailsMobile.vue, resources/views/tasks/editMobile.blade.php
The draft tag is not displayed in the created Task and the auto save in the screen is not working
added the task autosave functionality in the mobile view
Change to Mobile version
Create a Request
Open the Tasks
Update a Field
Wait for the auto save  (between 20 or 30 second)
Return to Tasks tab
https://processmaker.atlassian.net/browse/FOUR-17191
ci:next
=> observation/FOUR-17191 Mobile draft status is not displayed and Auto save in the screen is not working

resources/js/processes-catalogue/components/ProcessTab.vue, resources/js/requests/components/MobileRequests.vue, resources/js/tasks/components/MobileTasks.vue
- Tabs My Tasks and My Cases were fixed to show same information in Mobile and Desktop mode
- Login to PM (Desktop)
- Go to processes
- Select any process with Tasks and Cases
- Change to Mobile Mode in Browser Emulator
- Select same process in Mobile Mode
- My Tasks and My Cases should display the same information in both modes
https://processmaker.atlassian.net/browse/FOUR-17192
ci:next
=> QA Observation Bugfix/FOUR-17192: Mobile > My Cases and My Tasks are not displaying the correct info in each card

resources/js/components/shared/PaginationTable.vue
Submit button is displayed blank  after validating the required field
- [FOUR-16834](https://processmaker.atlassian.net/browse/FOUR-16834)
ci:next
[FOUR-16834]: https://processmaker.atlassian.net/browse/FOUR-16834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-16834: Submit button is displayed blank  after validating the required field

ProcessMaker/Models/ProcessVersion.php
https://github.com/ProcessMaker/processmaker/pull/7141 for develop
=> Exclude the svg field by default (develop)

ProcessMaker/Console/Migration/ExtendedMigrateCommand.php, ProcessMaker/Http/Resources/Task.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessMakerModel.php, ProcessMaker/Models/Screen.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, ProcessMaker/Traits/TaskControllerIndexMethods.php, ProcessMaker/Traits/TaskResourceIncludes.php
**Fixes**
https://processmaker.atlassian.net/browse/FOUR-16575
ci:next
=> Bugfix/FOUR-16575: Bugfix/FOUR-16575: Getting OOM Memory Failures when Calling Tasks API Endpoint

resources/lang/en.json
This PR fix the observation:
https://processmaker.atlassian.net/browse/FOUR-17315
[Core PR](https://github.com/ProcessMaker/processmaker/pull/7158)
[Package AI PR](https://github.com/ProcessMaker/package-ai/pull/259)
ci:next
ci:package-ai:observation/FOUR-17315
=> Observation/FOUR-17315: Not all FlowGenies fields are translated

resources/js/processes/modeler/initialLoad.js, resources/js/processes/modeler/validateFlowGenieRef.js
This PR fix the observation https://processmaker.atlassian.net/browse/FOUR-17405
ci:next
=> Observation/FOUR-17405: Autovalidate does not recognize FlowGenie Configuration.

ProcessMaker/Providers/AuthServiceProvider.php
This PR fix the following observations 
https://processmaker.atlassian.net/browse/FOUR-17430
https://processmaker.atlassian.net/browse/FOUR-17431
https://processmaker.atlassian.net/browse/FOUR-17432
ci:next
=> Observation/FOUR-17430: A non-administrator user cannot copy a flow genie that is in a project assigned to the user

resources/js/components/common/ProgressLoader.vue, resources/js/components/requests/card.vue, resources/js/components/requests/requestModal.vue, resources/js/components/shared/index.js
Share progress loader
- add component to sharedComponents
Ticket [FOUR-17464](https://processmaker.atlassian.net/browse/FOUR-17464)
Add page when process is empty
ci:next
It depends on the PR
https://github.com/ProcessMaker/package-ai/pull/271
[FOUR-17464]: https://processmaker.atlassian.net/browse/FOUR-17464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improvement-Message indicating that there is nothing to document.

.github/workflows/deploy-pm4.yml
Fix for CICD, already in next. This is for develop.
=> Fix CI build

resources/js/components/shared/InputImageCarousel.vue
Text is displayed outside the carousel
Added a style class if the language is fr or de
Log in
Click on Publish
https://processmaker.atlassian.net/browse/FOUR-17324
ci:next
=> observation/FOUR-17324 Text is displayed outside the carousel

resources/views/processes-catalogue/index.blade.php, resources/views/processes-catalogue/mobile.blade.php
ProcessMaker tries to send a POST request to https://next-qa.processmaker.net/process-browser/null which causes an error
1. Select the Non-PO Invoice Approval Helper
2. Click on Get Started
3. Try to upload a file using the temporarily added File Upload control
- It is necessary to add the meta tag in the views so that its value can be set correctly and the file upload control can obtain the correct target URL.​
- Follow the steps of above.
- [FOUR-17363](https://processmaker.atlassian.net/browse/FOUR-17363)
ci:next
[FOUR-17363]: https://processmaker.atlassian.net/browse/FOUR-17363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17363: It's not possible to upload files on guided template helpers

resources/js/tasks/components/MobileTasks.vue, resources/views/tasks/editMobile.blade.php
Mobile - autosave in the screen does not works correctly
added a delay and a message for the autosave
Login in
Create a simple process
login from mobile device
Create a Case
Open the Screen
Write a word
https://processmaker.atlassian.net/browse/FOUR-17349
ci:next
=> observation/FOUR-17349 Mobile - autosave in the screen does not works correctly

resources/js/components/common/ProgressLoader.vue, resources/js/components/requests/card.vue, resources/js/components/requests/requestModal.vue
This PR fix the following observation
https://processmaker.atlassian.net/browse/FOUR-17451
https://github.com/user-attachments/assets/0ea5606e-a981-4ba7-a90a-510f1f63e047
ci:next
=> Task/FOUR-17451: When starting a case, we need to include a loading button to prevent customers from unintentionally starting multiple cases.

resources/js/tasks/components/NavbarTaskMobile.vue
Mobile > Priority Icon is not displayed When screen is opened
fix the priority validation in the mobile view
Login
Create a simple process
Create a request
Open the Task
Press Priority icon when the screen is displayed
https://processmaker.atlassian.net/browse/FOUR-17462
ci:next
=> observation/FOUR-17462 Mobile > Priority Icon is not displayed When screen is opened

resources/js/processes/modeler/components/inspector/TaskDueIn.vue
Validation rules disappears of variable task due date in a task
- [FOUR-17481](https://processmaker.atlassian.net/browse/FOUR-17481)
ci:next
[FOUR-17481]: https://processmaker.atlassian.net/browse/FOUR-17481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-16481:Validation rules disappears of variable task due date in a task

ProcessMaker/Http/Resources/V1_1/TaskResource.php
This PR fix the observation https://processmaker.atlassian.net/browse/FOUR-17406
ci:next
ci:deploy
=> Observation/FOUR-17406: Claim Task does not work

ProcessMaker/Http/Controllers/Api/ProcessTranslationController.php, ProcessMaker/ProcessTranslations/ProcessTranslation.php
This PR fix the observation https://processmaker.atlassian.net/browse/FOUR-17452
[core PR](https://github.com/ProcessMaker/processmaker/pull/7204)
[package-ai PR](https://github.com/ProcessMaker/package-ai/pull/272)
ci:next
ci:package-ai:observation/FOUR-17452
=> Observation/FOUR-17452: AI Translations disappears in a new process.

ProcessMaker/ProcessTranslations/ProcessTranslation.php
This PR fix the following observation
https://processmaker.atlassian.net/browse/FOUR-17457
ci:next
=> Observation/FOUR-17457: Processes created from a Template cannot be translated

ProcessMaker/Http/Controllers/Api/ScreenController.php
Ticket: [FOUR-17419](https://processmaker.atlassian.net/browse/FOUR-17419)
After updating a Screen used within a Process Form Task, the changes made to the Screen are not consistently displayed in Form Tasks for newly created Cases. This results in users seeing outdated information on the Form Task.
- Add the `updateScreenDetails` method in `ScreenController.php`. In this method, we only set `$screen->config = $lastVersion->config` if the Screen's configs (Name, Description, Category, Projects) are updated. Previously, the `$screen->configs` were being set to the `$lastVersion->config` before any updates made to the Screen could be saved to the database.
1. Go to branch `observation/FOUR-17419` in `processmaker`.
2. Go to Designer → Processes. Create a Process.
- Add a Start Event → Form …
=> FOUR-17419 | The Last Update In A Screen Is Not Reflected In A Case

resources/js/components/shared/FilterTable.vue
Update the yellow color for new items in task / cases pages
Changed the unread tasks and cases rows color
https://processmaker.atlassian.net/browse/FOUR-17636
ci:next
=> observation/FOUR-17636 Update the yellow color for new items in task / cases pages

ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, tests/Feature/Api/V1_1/TaskControllerTest.php
Not redirecting to subprocess task. See jira issue.
- Include subprocess tasks in endpoint
- Create subprocess Start->Task->end
- Create a main process Start->Subprocess->End
- Make sure we show the subprocess tasks after starting the main process
- https://processmaker.atlassian.net/browse/FOUR-17581
ci:next
=> Fix including subprocess in tasks endpoint

resources/js/processes/screens/components/ScreenListing.vue, resources/views/processes/screens/list.blade.php
The message "No Data Available" disappears on screens
- https://processmaker.atlassian.net/browse/FOUR-17542
ci:next
=> bugfix/FOUR-17542: "No Data Available" disappears on screens

ProcessMaker/Exception/Handler.php
When the custom error render was using a fallback route, it was re-running it through the middleware pipeline invalidating our short-lived tokens we use for API calls (I think)
- Bypass the middleware and just show the fallback route
- Open modeler with at least 2 tasks
- Click on one task
- In another tab (not incognito), open an invalid webentry url like `/webentry/9999/77777`
- Go back to modeler and without reloading, click on another task.
- You should not see any error messages
- https://processmaker.atlassian.net/browse/FOUR-17525
ci:next
=> Do not invalidate tokens when showing fallback route

ProcessMaker/Http/Controllers/Api/WizardTemplateController.php, ProcessMaker/Jobs/SyncGuidedTemplates.php, resources/js/processes-catalogue/components/WizardTemplates.vue
Intermediate branch/PR to test PLG fixes:
- https://processmaker.atlassian.net/browse/FOUR-17628
- Not an issue in Summer. Still a problem in Spring. There will be a separate PR for develop.
- https://processmaker.atlassian.net/browse/FOUR-17622
- Fixed by 17438
- https://processmaker.atlassian.net/browse/FOUR-15427
- This PR includes this Core PR: https://github.com/ProcessMaker/processmaker/pull/7221
- https://processmaker.atlassian.net/browse/FOUR-15426
- This PR includes this Core PR: https://github.com/ProcessMaker/processmaker/pull/7223
- This build references this Wizard Template PR: https://github.com/ProcessMaker/wizard-templates/pull/112 (using CI tag env var below)
- https://processmaker.atlassian.net/browse/FOUR-17438
- This build includes this Web Entry PR: …
=> PLG Observations

resources/js/Mobile/Card.vue
Tasks and Cases are not the same between mobile and desktop views
ix the tasks and cases data format after applying a filter in the mobile view
Log in
Create a USER_A
Create a simple process (start event - task -task - end event)
Assign all Tasks to USER_A
Start some Cases  from ADMIN USER
logout
login with USER_A from mobile view
Open some cases and sent to next task
Go to Tasks tab
Go to Cases tab
https://processmaker.atlassian.net/browse/FOUR-17495
ci:next
=> observation/FOUR-17495-2 Tasks and Cases are not the same between mobile and desktop views

ProcessMaker/Listeners/HandleActivityAssignedInterstitialRedirect.php
https://processmaker.atlassian.net/browse/FOUR-18851
Requires https://github.com/ProcessMaker/screen-builder/pull/1674
ci:next
=> Add nodeId to event

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, resources/js/processes-catalogue/components/BaseChart.vue
FOUR-18128 Update the component using the new colors and Ui updates
- https://processmaker.atlassian.net/browse/FOUR-18221
ci:deploy
ci:next
=> feature/FOUR-18221:  Update the component using the new colors and Ui updates

config/app.php, database/migrations/2024_08_26_190935_create_encrypted_data.php, upgrades/2024_08_26_201558_add_default_key_for_encrypted_fields.php
https://processmaker.atlassian.net/browse/FOUR-18535
Added new table "encrypted_data"
Create a new value in the environment variables from the app with an initial encryption private key for "AES-256-GCM"
ci:next
=> FOUR-18535 Preliminar work (create new table encrypted_data, seed the initial key, etc.)

ProcessMaker/Http/Controllers/Api/EncryptedDataController.php, ProcessMaker/Models/EncryptedData.php, routes/api.php, tests/Feature/Api/EncryptedDataTest.php
https://processmaker.atlassian.net/browse/FOUR-18065
Added next endpoints:
POST /api/1.0/encrypted_data/encryptText
POST /api/1.0/encrypted_data/decryptText
ci:next
=> FOUR-18065 API endpoints to encrypt/decrypt data

resources/js/components/shared/FilterTable.vue, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
The Header of the columns will change 'Capitalized Case'
https://processmaker.atlassian.net/browse/FOUR-18617
ci:deploy
ci:next
=> FOUR-18617: The Header of the columns will change 'Capitalized Case'

.github/workflows/deploy-pm4.yml
docker-compose has been deprecated, need to use docker compose.
=> update to docker compose commands

ProcessMaker/ImportExport/Exporters/ProcessExporter.php
https://github.com/ProcessMaker/processmaker/pull/7264 for next
ci:next
=> Use the first admin user if user_id is not set (next)

ProcessMaker/ImportExport/Importer.php
When importing DataSourceScripts, they contain the script_id filled, but ideally, this field should be null. 
1. The problem is that within ProcessMaker/ImportExport/Importer.php, during the execution of doImport, a $exporter->model->save(); is performed, which creates the data source scripts with the hardcoded script_id. 
2. Afterward, $exporter->runImport is executed, which triggers postImport in src/ImportExport/ScriptExporterExtension.php within the package-data-sources. 
At this point, it tries to replace the script_id with the correct ID, but it fails because, for example, it attempts to change the script_id from 40 to 47, but script_id 47 already exists as it was created earlier during doImport.
- Set the script_id of the data source scripts to null before saving. This way, when …
=> FOUR-18090: Fix conflict during data source script postImport

ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, ProcessMaker/Models/ProcessRequestToken.php
The user assigned to the task with self service enabled is not redirected to the self service task
- improve self service in the task service
Described in the related test
- https://processmaker.atlassian.net/browse/FOUR-18974
ci:deploy
ci:next
=> FOUR-18974: The user assigned to the task with self service enabled is not redirected to the self service task

resources/js/bootstrap.js, resources/views/layouts/ai-qr-mobile.blade.php, resources/views/layouts/layout.blade.php, resources/views/layouts/minimal.blade.php, resources/views/layouts/preview.blade.php, resources/views/layouts/process-map.blade.php, resources/views/tasks/preview.blade.php
Currently the "Missing Translation" warning is shown in production.
- Do not display "Missing Translation" warnings in production
- Login to processmaker
- See there are "Missing Translation" logs.
- https://processmaker.atlassian.net/browse/FOUR-18897
ci:next
=> FOUR-18897 

resources/views/tasks/edit.blade.php
Issue with Reassigning Tasks Without Claiming First in Self Service
Disable reassign until the task is claimed
Create a test process with the following elements:
A start event assigned to user0.
A task assigned to a group (user1, user2) with the following assignment options: Allow reassignment and self service.
An end event.
Start the process with user0.
Attempt to reassign the task from user1 to another user without claiming the task first.
Attempt to have user2 claim the reassigned task.
https://processmaker.atlassian.net/browse/FOUR-17453
ci:next
=> bugfix/FOUR-17453-4.11 Issue with Reassigning Tasks Without Claiming First in Self Service

package.json, postcss.config.js, resources/sass/tailwind.css, tailwind.config.js, webpack.mix.js
Add tailwind css to platform
- https://processmaker.atlassian.net/browse/FOUR-19004
ci:next
=> FOUR-19004:  Create a NEW VIEW for cases Part Counters

resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json
https://processmaker.atlassian.net/browse/FOUR-18070
ci:next
=> FOUR-18070 STORY Reveal/Conceal Content in Form Preview

ProcessMaker/Http/Controllers/RequestController.php, resources/js/cases/components/CaseDetail.vue, resources/js/cases/components/Tabs.vue, resources/js/cases/edit.js, resources/views/cases/edit.blade.php, resources/views/layouts/layout.blade.php
New view "cases" and Implement new UI tabs
- Create a new tab using Tailwind
https://processmaker.atlassian.net/browse/FOUR-18634
ci:deploy
ci:next
=> FOUR-18634: New view "cases" and Implement new UI tabs

resources/js/app-login.js
This PR implements the user story for the ticket https://processmaker.atlassian.net/browse/FOUR-18705
https://github.com/ProcessMaker/package-translations/pull/89
**Screenshots**
ci:next
=> Task/FOUR-18705: Implement Process Translations Tab UI 

ProcessMaker/Console/Commands/ChangeKeyEncryptedData.php, ProcessMaker/Models/EncryptedData.php, upgrades/2024_08_26_201558_add_default_key_for_encrypted_fields.php
https://processmaker.atlassian.net/browse/FOUR-19069
ci:next
=> FOUR-19069 Implement command to update data already encrypted

ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Http/Middleware/GenerateMenus.php, resources/jscomposition/cases/casesMain/utils/counters.js, resources/views/requests/index.blade.php, routes/api.php, routes/web.php
- https://processmaker.atlassian.net/browse/FOUR-19226
ci:next
ci:deploy
=> FOUR-19226: Rename Cases to Request

database/seeders/PermissionSeeder.php
Create a new Permission “View My Request”, this should be enable per default.
- https://processmaker.atlassian.net/browse/FOUR-19273
ci:next
=> FOUR-19273: Create a new Permission “View My Request”, this should be enable per default.

tests/Feature/Api/UsersTest.php, tests/Feature/RedirectTest.php, tests/Feature/RequestTest.php
Unit test failed
- https://processmaker.atlassian.net/browse/FOUR-19349
ci:next
=> FOUR-19349: Unit test failed

ProcessMaker/Console/Commands/ChangeKeyEncryptedData.php, database/factories/ProcessMaker/Models/EncryptedDataFactory.php, phpunit.xml, tests/Feature/Console/ChangeKeyEncryptedDataTest.php, tests/Fixtures/dummy-env
https://processmaker.atlassian.net/browse/FOUR-19070
ci:next
=> FOUR-19070 Implement tests for command to update data already encrypted

resources/jscomposition/cases/casesDetail/api/index.js, resources/jscomposition/cases/casesDetail/components/TaskTable.vue, resources/jscomposition/cases/casesDetail/config/columns.js, resources/jscomposition/system/table/cell/LinkCell.vue
- https://processmaker.atlassian.net/browse/FOUR-19319
=> FOUR-19319: Add links in the columns in "Tasks" tab

ProcessMaker/Http/Controllers/Api/ProcessController.php
This PR implements the following user stories:
- https://processmaker.atlassian.net/browse/FOUR-18664
- https://processmaker.atlassian.net/browse/FOUR-18672
- https://processmaker.atlassian.net/browse/FOUR-18721
Core PR https://github.com/ProcessMaker/processmaker/pull/7422
Package Translations PR https://github.com/ProcessMaker/package-translations/pull/104
ci:next
ci:package-translations:task/FOUR-18664
=> Task/FOUR-18664: Create list component for processes, Implement filter for processes, list processes backend

ProcessMaker/Console/Commands/ChangeKeyEncryptedData.php, ProcessMaker/EncryptedData/EncryptedDataInterface.php, ProcessMaker/EncryptedData/Local.php, ProcessMaker/EncryptedData/Vault.php, ProcessMaker/Facades/EncryptedData.php, ProcessMaker/Http/Controllers/Api/EncryptedDataController.php, ProcessMaker/Managers/EncryptedDataManager.php, ProcessMaker/Models/EncryptedData.php, ProcessMaker/Providers/EncryptedDataServiceProvider.php, composer.json, composer.lock, config/app.php, database/factories/ProcessMaker/Models/EncryptedDataFactory.php, tests/Feature/Console/ChangeKeyEncryptedDataTest.php, upgrades/2024_08_26_201558_add_default_key_for_encrypted_fields.php
https://processmaker.atlassian.net/browse/FOUR-18929
ci:next
=> FOUR-18929 Add support to use micro service in Vault server to encrypt/decrypt data

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/base/table/ContainerRow.vue, resources/jscomposition/base/table/TCell.vue, resources/jscomposition/base/table/TRow.vue, resources/jscomposition/cases/casesDetail/api/index.js, resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/CompletedForms.vue, resources/jscomposition/cases/casesDetail/components/DisplayForm.vue, resources/jscomposition/cases/casesDetail/components/EllipsisMenu.vue, resources/jscomposition/cases/casesDetail/components/TaskTable.vue, resources/jscomposition/cases/casesDetail/config/columns.js, resources/jscomposition/system/table/cell/CollapseFormCell.vue, resources/jscomposition/system/table/cell/index.js
https://processmaker.atlassian.net/browse/FOUR-18638
ci:next
=> FOUR-18638:Create a component with collpase the row and show some content

resources/views/requests/show.blade.php
- https://processmaker.atlassian.net/browse/FOUR-19366
ci:next
=> FOUR-19366:Request - Details add a button "Go to Case"

ProcessMaker/Http/Controllers/Api/V1_1/CaseController.php, tests/Feature/Api/V1_1/CaseControllerTest.php
https://processmaker.atlassian.net/browse/FOUR-18608
ci:next
=> FOUR-18608 Filter by status

resources/js/app-layout.js, resources/js/components/Menu.vue, resources/js/processes/screen-builder/screen.vue
This PR implements the following user stories:
https://processmaker.atlassian.net/browse/FOUR-18735
https://processmaker.atlassian.net/browse/FOUR-18695
https://processmaker.atlassian.net/browse/FOUR-18709
Core: https://github.com/ProcessMaker/processmaker/pull/7465
Package translations: https://github.com/ProcessMaker/package-translations/pull/112
ci:next
ci:package-translations:task/FOUR-18735
=> Task/FOUR-18735: Display translation progress modal when translating with AI Front, add language selector modal in screen builder

ProcessMaker/Http/Controllers/Api/CommentController.php, database/migrations/2024_10_04_154956_add_case_number_to_comments_table.php, routes/api.php, tests/Feature/Api/CommentTest.php
- https://processmaker.atlassian.net/browse/FOUR-18969
ci:next
=> FOUR-18969

ProcessMaker/ScriptRunners/Base.php, resources/js/print-layout.js
- https://processmaker.atlassian.net/browse/FOUR-18751
[pdfVajvLX.pdf](https://github.com/user-attachments/files/17263809/pdfVajvLX.pdf)
- Added some checks for `print-layout`
- Added support for Mac users
- https://github.com/ProcessMaker/package-ai/pull/314
- https://github.com/ProcessMaker/connector-pdf-print/pull/85
ci:next
=> task/FOUR-18751: Generate PDF from HTML

ProcessMaker/Http/Controllers/Auth/LoginController.php
Reverts ProcessMaker/processmaker#7461 due to [regression](https://processmaker.atlassian.net/browse/FOUR-19530).
=> Revert "The Block duplicate session in IP Restriction option only works the first time"

ProcessMaker/Http/Controllers/Auth/LoginController.php
Reverts ProcessMaker/processmaker#7396 due to [regression](https://processmaker.atlassian.net/browse/FOUR-19466).
=> Revert "FOUR-16704: Session Token Not Invalidated on Logout"

.github/workflows/deploy-pm4.yml
=> Fix K8s branch for CICD - develop

.github/workflows/deploy-pm4.yml
=> Fix K8s branch for CICD - release-2024-fall

devhub/pm-font/svgtofont.js, package.json
- https://processmaker.atlassian.net/browse/FOUR-19289
ci:next
=> FEATURE/FOUR-19289 : Update the fonts in platform

ProcessMaker/ImportExport/Logger.php, ProcessMaker/ImportExport/Manifest.php, ProcessMaker/Models/DevLink.php, resources/js/admin/devlink/components/AssetListing.vue, resources/js/admin/devlink/components/Instance.vue
Handle errors - forward compatability
Added a new attribute in the import endpont to show the warnings
Import a process with classes that are nmot installed
https://processmaker.atlassian.net/browse/FOUR-18405
ci:next
=> feature/FOUR-18405 Handle errors - forward compatability

ProcessMaker/Http/Controllers/Api/EncryptedDataController.php, ProcessMaker/Models/EncryptedData.php, database/factories/ProcessMaker/Models/EncryptedDataFactory.php, database/migrations/2024_08_26_190935_create_encrypted_data.php, tests/Feature/Api/EncryptedDataTest.php
https://processmaker.atlassian.net/browse/FOUR-19236
ci:next
=> FOUR-19236 Encryption is Not Working in Authenticated Web Entry

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/cases/casesMain/CasesMain.vue, resources/jscomposition/cases/casesMain/components/.prettierrc, resources/jscomposition/cases/casesMain/components/TablePlaceholder.vue, resources/jscomposition/system/index.js, resources/jscomposition/system/placeholders/EmptyPlaceholder.vue, resources/jscomposition/system/placeholders/LoadingPlaceholder.vue, resources/jscomposition/system/placeholders/index.js, resources/jscomposition/system/table/FilterableTable.vue
- https://processmaker.atlassian.net/browse/FOUR-19356
=> FOUR-19356: Cases list place holder Loading

ProcessMaker/Http/Controllers/Api/ProcessController.php
This PR implements the following user story:
https://processmaker.atlassian.net/browse/FOUR-18794
[Core PR](https://github.com/ProcessMaker/processmaker/pull/7524)
[Package Translations PR](https://github.com/ProcessMaker/package-translations/pull/119)
=> Task/FOUR-18794: Configure default language for anon we

ProcessMaker/Http/Controllers/Api/TaskController.php, tests/Feature/Api/TaskControllerTest.php
=> FOUR-19574

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/ProcessTranslations/ProcessTranslation.php, tests/Feature/Api/TranslationTest.php
implementation translations in screens
- Use table translatable for translations
-
- [FOUR-18720](https://processmaker.atlassian.net/browse/FOUR-18720)
- [FOUR-18723](https://processmaker.atlassian.net/browse/FOUR-18723)
- [FOUR-18724](https://processmaker.atlassian.net/browse/FOUR-18724)
[FOUR-18720]: https://processmaker.atlassian.net/browse/FOUR-18720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-18723]: https://processmaker.atlassian.net/browse/FOUR-18723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-18724]: https://processmaker.atlassian.net/browse/FOUR-18724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> Implementation to apply translations

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, resources/jscomposition/cases/casesDetail/components/RequestTable.vue, routes/api.php, tests/Feature/Api/ProcessRequestsTest.php
=> FOUR-19487

resources/views/cases/edit.blade.php
- https://processmaker.atlassian.net/browse/FOUR-19375
=> FOUR-19375: Breadcrumbs

ProcessMaker/Http/Controllers/CasesController.php, resources/jscomposition/cases/casesDetail/api/index.js, resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/DisplayForm.vue, resources/jscomposition/cases/casesDetail/components/Overview.vue, resources/jscomposition/cases/casesDetail/components/placeholder/LoadingFormPlaceholder.vue, resources/jscomposition/cases/casesDetail/components/placeholder/LoadingPlaceholder.vue, resources/jscomposition/cases/casesDetail/edit.js, resources/jscomposition/cases/casesDetail/variables/index.js, resources/views/cases/edit.blade.php, routes/web.php, tests/Feature/CasesControllerTest.php
- [FOUR-19269](https://processmaker.atlassian.net/browse/FOUR-19269)
[FOUR-19269]: https://processmaker.atlassian.net/browse/FOUR-19269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19269: Case Details

resources/js/processes/import/components/ImportPIModal.vue
This PR resolves the observation https://processmaker.atlassian.net/browse/FOUR-19608
Issue:
Fix:
=> Observation/FOUR-19608: Remove import file icon is not aligned

ProcessMaker/ProcessTranslations/ProcessTranslation.php, ProcessMaker/ProcessTranslations/ScreenTranslation.php
Ticket
[FOUR-18742](https://processmaker.atlassian.net/browse/FOUR-18742)
Validate cookie language to set language
ci:package-webentry:feature/FOUR-18742
ci:package-translations:feature/FOUR-18742
[FOUR-18742]: https://processmaker.atlassian.net/browse/FOUR-18742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-18726 - Select language and apply changes for the web entry screen and refresh task with translations applied

resources/jscomposition/base/ui/.prettierrc, resources/jscomposition/base/ui/AppPopover.vue, resources/jscomposition/base/ui/CollapsableContainer.vue, resources/jscomposition/cases/casesDetail/api/index.js, resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/CompletedForms.vue, resources/jscomposition/cases/casesDetail/components/RequestTable.vue, resources/jscomposition/cases/casesDetail/components/TabHistory.vue, resources/jscomposition/cases/casesDetail/components/TaskTable.vue, resources/jscomposition/cases/casesDetail/components/TimelineCases.vue, resources/jscomposition/cases/casesDetail/config/columns.js, resources/jscomposition/cases/casesDetail/edit.js, resources/jscomposition/cases/casesDetail/store/index.js, resources/jscomposition/cases/casesDetail/store/store.js, resources/jscomposition/cases/casesDetail/variables/index.js, resources/views/cases/edit.blade.php
- https://processmaker.atlassian.net/browse/FOUR-19121
=> FOUR-19121 : Integration with the Collapse UI Improvements

resources/jscomposition/cases/casesDetail/edit.js, resources/views/cases/edit.blade.php
- https://processmaker.atlassian.net/browse/FOUR-19592
ci:deploy
ci:release-2024-fall
=> FOUR-19592:Update the behavior in "Details"

ProcessMaker/ProcessTranslations/ScreenTranslation.php
Ticket
[FOUR-18741](https://processmaker.atlassian.net/browse/FOUR-18741)
Change set target language from anon webentry
ci:package-webentry:feature/FOUR-18741
ci:package-translations:feature/FOUR-18741
[FOUR-18741]: https://processmaker.atlassian.net/browse/FOUR-18741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-18726 - Create the UI for the selector button/styles

resources/views/cases/edit.blade.php, resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
- https://processmaker.atlassian.net/browse/FOUR-19440
ci:deploy
ci:package-comments:feature/FOUR-19440
=> FOUR-19440:FE (task request cases) when a comment is save a new parameter "case_number" needs to send

ProcessMaker/Models/ProcessRequestToken.php, resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksPreview.vue, resources/views/tasks/edit.blade.php
As a user assigned to a previous self-service task, I shouldn’t need to claim the task since it’s already assigned to me.
https://processmaker.atlassian.net/browse/FOUR-18102
=> feature/FOUR-18102 STORY Self-Service Reassignment

resources/js/admin/devlink/components/Assets.vue, resources/js/admin/devlink/components/DevLink.vue, resources/js/admin/devlink/components/Instance.vue, resources/js/admin/devlink/components/InstanceTabs.vue
Format tabs/headers to match figma - can this be reusable? Have other teams already created reusable components for the new tab design?
Get figma for Linked Instances > Instance → Bundles and Assets Tabs design
- https://processmaker.atlassian.net/browse/FOUR-19643
=> FOUR-19643 Remaining UI Updates

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/js/processes-catalogue/components/utils/SearchCards.vue
=> FOUR-19482 | Placeholder Text for All Templates Search Is Not Correct in LaunchPad

ProcessMaker/ImportExport/Exporters/EmbedExporter.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, database/factories/ProcessMaker/Models/EmbedFactory.php, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php, tests/Feature/ImportExport/Exporters/ProcessLaunchpadExporterTest.php
=> FOUR-19287: Incorrect model_id assignment during Import in ProcessExporter importEmbed

ProcessMaker/BuildSdk.php
=> FOUR-17328 Patch generated SDK code to fix error

ProcessMaker/Http/Controllers/Api/UserController.php, composer.json, composer.lock, package-lock.json, package.json, resources/views/admin/users/edit.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/users/profile.blade.php
Verify that a super admin user can update the email by other user 
authenticate the user that is making the change instead of the user that is being edited, fix a observation when a user saves again after editing the email
log in
edit profile
edit email
save
https://processmaker.atlassian.net/browse/FOUR-16703
ci:next
ci:deploy
=> observation/FOUR-16703-2 Verify that a super admin user can update the email by other user

resources/js/admin/devlink/components/BundleAssets.vue, resources/js/admin/devlink/components/BundleModal.vue, resources/js/admin/devlink/components/LocalBundles.vue
- Login PM4
- Go to Admin->devLink
- Go to Local Bundles
- Create a Bundle in Local
- Click on created Bundle
- A new page should be shown with the name of bundle and Edit and Reinstall this bundle buttons
https://processmaker.atlassian.net/browse/FOUR-19645
=> Feature/FOUR-19645: Add header buttons when viewing a bundle's assets

ProcessMaker/Http/Controllers/Api/UserConfigurationController.php
- https://processmaker.atlassian.net/browse/FOUR-19701
=> FOUR-19701 : The Cases details needs to show per default descollapsed

resources/views/tasks/edit.blade.php
- https://processmaker.atlassian.net/browse/FOUR-19691
ci:deploy
=> FOUR-19691:When Open a task the scroll in the Details & Comments is showing when this section is collapse

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Managers/PackageManager.php, resources/.gitignore, resources/lang/.gitignore
Add language to backup
Ticket [FOUR-19722](https://processmaker.atlassian.net/browse/FOUR-19722)
[FOUR-19722]: https://processmaker.atlassian.net/browse/FOUR-19722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add lang.orig for new installed languages for reset to default (Packages)

resources/js/admin/devlink/components/LocalBundles.vue
Add missing import on devlink LocalBundles
=> Add missing import

resources/jscomposition/base/ui/CollapsableContainer.vue, resources/views/cases/edit.blade.php
- Use the same UI that task, launchpad
Open a case 
Review the icon to collpase Details
- https://processmaker.atlassian.net/browse/FOUR-19754
=> FOUR-19754:UI: the collpase icon in cases needs to update like other places

resources/js/processes-catalogue/components/BaseChart.vue
- https://processmaker.atlassian.net/browse/FOUR-19080
ci:deploy
=> 404 Error in Per Launch pad with process imported from previous version

ProcessMaker/Http/Middleware/GenerateMenus.php
- The Icon for Collections in Designer page was moved
- Login PM4
- Go to designer page
https://processmaker.atlassian.net/browse/FOUR-19275
=> bugfix/FOUR-19275: Collection menu has a different order

resources/views/cases/edit.blade.php
1. Go to Cases List
2. Open a case
3. See the button Cancel Request
The UI for the button is not the correct
- https://processmaker.atlassian.net/browse/FOUR-19814
=> FOUR-19814:UI: The boton Cancel does not have the correct styles

resources/lang/en.json
- Adding new translations to en.json file
- Login PM4
- Go to Designer -> Screens
- Create or open a screen
- Drag Collection Record Control
- Click on Variable section in the inspector, and check the tooltip.
https://processmaker.atlassian.net/browse/FOUR-19681
=> bugfix/FOUR-19681: Add a message to indicates user that Collections won´t be available for Anonymous Web Entry

resources/jscomposition/cases/casesMain/CasesDataSection.vue
- Go to Cases
- See the list of cases
The cases list does not have a default order
- The order by per default is by Case Number DESC, in order to show the last case # first
- https://processmaker.atlassian.net/browse/FOUR-19774
=> Default order by Case # in the cases list

resources/views/layouts/navbarMobile.blade.php
1. Log in with Mobile
e get a server error message when logging in from a mobile device
You have to log in without problems with mobile devices
- The name of routes related to request was updated
- https://processmaker.atlassian.net/browse/FOUR-19842
=> FOUR-19842: It is not possible to log in to the application from mobile

resources/js/processes/scripts/components/GenerateScriptTextPrompt.vue
1.Create a script
2.Click on "generate script from text"
3.Click on "give me inspiration!"
4.Select any suggestion
5.Click on generate
6.Click on confirm
7.Before applying changes Click on "give me inspiration!" again
- Fetch suggestions on toggle suggestions list
- [FOUR-18844](https://processmaker.atlassian.net/browse/FOUR-18844)
[FOUR-18844]: https://processmaker.atlassian.net/browse/FOUR-18844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-18844: "Loading suggestion" keeps showing indefinitely in scripts

resources/views/cases/edit.blade.php
1. Create a case
2. Open the request/#id
3. Add some comments here
4. Go to Cases
5. See the comments
- https://processmaker.atlassian.net/browse/FOUR-19831
=> FOUR-19831 : The Case comments does not show the subject for the Type=ProcessRequest

resources/jscomposition/cases/casesDetail/config/columns.js, resources/jscomposition/cases/casesMain/config/columns.js, resources/jscomposition/system/table/cell/CaseTitle.vue, resources/jscomposition/system/table/cell/CaseTitleCell.vue, resources/jscomposition/system/table/cell/LinkCell.vue, resources/jscomposition/system/table/cell/TruncatedOptionsCell.vue
- Go to Cases
- See the list of cases
- Mouse over the links
When a mouse is over the link, is not possible to see the link to open:
- https://processmaker.atlassian.net/browse/FOUR-19815
=> UI: The mouse over the links does not show the link

resources/jscomposition/cases/casesMain/config/columns.js, resources/jscomposition/system/table/cell/TruncatedColumn.vue, resources/jscomposition/system/table/cell/index.js
1. Go to Cases
2. See the list of cases
3. Review the Process
This column has a link, but this link is incorrect
- Create a new component
- https://processmaker.atlassian.net/browse/FOUR-19800
=> FOUR-19800:UI: Remove the link in the process column in the cases list

resources/lang/en.json, resources/views/cases/edit.blade.php
1. Go to Cases List
2. Open a case
3. See the button Cancel Request
- Rename to Cancel Case
- https://processmaker.atlassian.net/browse/FOUR-19814
ci:deploy
=> FOUR-19814

resources/js/admin/devlink/components/Header.vue, resources/js/admin/devlink/components/Instance.vue, resources/js/admin/devlink/components/LocalBundles.vue
See jira issue
- Add the missing open option
- A few other UI tweaks
- https://processmaker.atlassian.net/browse/FOUR-19859
=> FOUR-19859 Add missing open option in menu

ProcessMaker/Http/Controllers/Api/DevLinkController.php, ProcessMaker/Models/Bundle.php, resources/js/components/shared/AddToBundle.vue, resources/js/components/shared/BackendSelect.vue, routes/api.php
Add to Bundle modal should have the correct UI according to figma design
https://processmaker.atlassian.net/browse/FOUR-19906
=> FOUR-19906 `Add to bundle` modal does not have a correct UI

resources/js/processes/components/ProcessesPermissions.vue, resources/views/processes/edit.blade.php
- The reassignment field should have the figma design
- https://processmaker.atlassian.net/browse/FOUR-19937
=> FOUR-19937 `Reassignment field` does not have the correct UI

upgrades/2024_10_09_032151_populate_case_started.php
This upgrade was not migrating all the cases.
- https://processmaker.atlassian.net/browse/FOUR-19948
=> FOUR-19948 Improve the migration of cases_started

ProcessMaker/Console/Commands/UpdateCommentsCaseNumber.php, upgrades/2024_10_08_113301_populate_comments_case_number.php
Upgrade is taking about 17 minutes for 300k requests 2024_10_08_113301_populate_comments_case_number
- https://processmaker.atlassian.net/browse/FOUR-19949
=> FOUR-19949: Upgrade is taking about 17 minutes for 300k requests 2024_10_08_113301_populate_comments_case_number

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/cases/casesDetail/components/CompletedForms.vue, resources/jscomposition/cases/casesDetail/components/RequestTable.vue, resources/jscomposition/cases/casesDetail/components/TaskTable.vue, resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/system/table/FilterableTable.vue, resources/jscomposition/system/table/SortTable.vue
1. Create cases
2. Go to cases list
3. See the completed column
The table shows blank section in right position
- https://processmaker.atlassian.net/browse/FOUR-19710
ci:deploy
=> FOUR-19710:UI: Table shows blank section in right position

resources/jscomposition/cases/casesMain/components/CaseFilter.vue
**Description**
As a user, I want to be able to find cases within the system more easily.
The use cases to consider include searching by Case Number and Case Title.
**Acceptance criteria**
Case number and case title would be covered only.
https://github.com/user-attachments/assets/216b10e9-e364-4143-a995-89d0bfec8860
- [FOUR-20019](https://processmaker.atlassian.net/browse/FOUR-20019)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/7701)
- [Package AI PR](https://github.com/ProcessMaker/package-ai/pull/344)
- [PM4_AI PR](https://github.com/ProcessMaker/pm4_ai/pull/19)
[FOUR-20019]: https://processmaker.atlassian.net/browse/FOUR-20019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Task/FOUR-20019: AI Search: Cases Search

resources/views/layouts/navbar.blade.php
This PR resolves the observation https://processmaker.atlassian.net/browse/FOUR-20065
- [Core](https://github.com/ProcessMaker/processmaker/pull/7721) 
- [Package translations](https://github.com/ProcessMaker/package-translations/pull/159)
- [Package webentry ](https://github.com/ProcessMaker/package-webentry/pull/263)
https://github.com/user-attachments/assets/af17dadd-c1fb-46e8-a9da-fd62002d4259
https://github.com/user-attachments/assets/11f50dc1-9d9c-493b-8fb2-b15e3f5b02b6
=> Observation/FOUR-20065: When changing the language, the flag is not updated from the web entry mode authenticated

resources/js/processes/designer/Assets.vue, resources/js/processes/designer/RecentAssets.vue
This PR implements https://processmaker.atlassian.net/browse/FOUR-20032
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/7707)
- [Package Projects PR](https://github.com/ProcessMaker/package-projects/pull/156)
ci:processmaker:4.11.6+patch+ellucian
ci:release-branch:release-2024-summer
=> Task/FOUR-20032: Hide FlowGenie from Ellucian's servers

resources/jscomposition/cases/casesDetail/api/index.js, resources/jscomposition/cases/casesDetail/edit.js
1. Create a Case
2. Open the case
3. Click on Cancel Case
- Add missing method
- https://processmaker.atlassian.net/browse/FOUR-20039
ci:deploy
=> FOUR-20039 : The Cancel Case does not work

resources/jscomposition/cases/casesDetail/components/DisplayForm.vue
- Create a screen with some page an pagination
- Create a process 
- Assign the screen created
- Create a case
- Complete the form with many pages
- Go to case completed url 
- Go to Completed & Form
- Check the form completed
The form with pagination does they don't show all pages as a form in request 
- https://processmaker.atlassian.net/browse/FOUR-20006
ci:deploy
=> FOUR-20006:All pages of form with pagination are not visible s from case detail

resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/views/cases/edit.blade.php
Cypress add id to get elements in Cases Details
- [FOUR-20092](https://processmaker.atlassian.net/browse/FOUR-20092)
ci:deploy
[FOUR-20092]: https://processmaker.atlassian.net/browse/FOUR-20092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20092: Cypress add id to get elements

resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
tags cypress
- https://processmaker.atlassian.net/browse/FOUR-20092
ci:deploy
=> FOUR-20092

resources/jscomposition/cases/casesMain/components/AppCounters.vue, resources/jscomposition/cases/casesMain/components/CaseFilter.vue, resources/jscomposition/cases/casesMain/utils/counters.js, resources/views/requests/show.blade.php
- https://processmaker.atlassian.net/browse/FOUR-20216
=> FOUR-20216: Cypress test

ProcessMaker/Models/DevLink.php, resources/js/admin/devlink/components/AssetListing.vue, resources/js/admin/devlink/components/assetTypes.js
Some settings in assetTypes.js were incorrect.
- Fix the settings and add pagination
See Jira Issue
- https://processmaker.atlassian.net/browse/FOUR-20242
=> FOUR-20242 Fix asset listing and add pagination

resources/jscomposition/system/table/cell/ParticipantsCell.vue, resources/jscomposition/system/table/cell/StatusCell.vue
1. Go to case details
2. See the columns Participant and Status
- apply align left
- https://processmaker.atlassian.net/browse/FOUR-20276
=> FOUR-20276

resources/jscomposition/cases/casesMain/CasesDataSection.vue
1.Log In
2.Go to cases-- my cases or all cases
3.Search for any created case
When there is any change in the filters, the page is reset to 1
- https://processmaker.atlassian.net/browse/FOUR-20254
ci:deploy
=> FOUR-20254 : Searching for cases only shows cases in progress.

resources/views/layouts/navbarMobile.blade.php
1. Go to server https://ci-5622163eea.engk8s.processmaker.net/
2. ProcessMaker Platform Winter 2025 Version 4.12.0+beta-4 (Build #c88ca571)
3. Change the browser to mobile view
4. Login 
5. Select Tasks tab
6. Select Cases tab
7. Select Processes tab
- https://processmaker.atlassian.net/browse/FOUR-21104
ci:deploy
=> FOUR-21104 : Mobile > Tabs do not have the correct style

tests/Feature/Api/UsersTest.php
Flaky test in tests/Feature/Api/UsersTest.php
- Add symbol to password
- https://processmaker.atlassian.net/browse/FOUR-20521
=> FOUR-20521 Fix flaky test

ProcessMaker/Http/Controllers/Api/UserConfigurationController.php, ProcessMaker/Models/UserConfiguration.php, database/migrations/2024_12_11_161527_add_ui_filters_column_in_user_configuration.php, routes/api.php, tests/Feature/Api/UserConfigurationTest.php
Define an column in user to save this kind of configurations
- https://processmaker.atlassian.net/browse/FOUR-20588
=> FOUR-20588: Define an column in user to save this kind of configurations

ProcessMaker/Http/Controllers/Api/UserConfigurationController.php, ProcessMaker/Http/Controllers/TaskController.php, resources/js/tasks/components/ParticipantHomeScreen.vue, resources/js/tasks/index.js, resources/js/tasks/mixins/TasksMixin.js, resources/views/tasks/index.blade.php, tests/Feature/Api/UserConfigurationTest.php
In this ticket we have the next new features:
- new Participant Home Screen Inbox component:
* index.blade.index(Tasks) keeps old functionality  and also calls new component ParticipantHomeScreen ( old and new features were divided with div's and are shown or hidden with variable showOldTaskScreen=true/false
* New Collapsable List Pane (Currently empty, the functionality for Process and Dashboards will be added in future tickets)
* Collapsable side-bar Status(open or collapsed) is saved in database per User
* New Component has all Task Page functionality
- Login PM4
- Go to TASKS
- New Participant Home Inbox should be displayed with left Pane Opened
- Click in Collapse Icon to hide Left Pane
- Switch to another page like Admin  and return to Tasks (last status for collapsable Pane should …
=> Feature/FOUR-20299: List of Processes in Home Page - Implement Process list pane collapse

ProcessMaker/Traits/ProcessMapTrait.php, resources/jscomposition/cases/casesDetail/components/NewOverview.vue
- https://processmaker.atlassian.net/browse/FOUR-20279
=> FOUR-20279:Optimize the In-Flight Modeler UI Component

resources/js/next/components/index.js, resources/js/next/config/accesibility.js, resources/js/next/libraries/broadcast.js, resources/js/next/libraries/modelerInspector.js, resources/js/tasks/loaderEdit.js, resources/js/tasks/loaderMain.js, resources/js/tasks/loaderPreview.js, resources/jscomposition/cases/casesDetail/loader.js, resources/jscomposition/cases/casesMain/loader.js
1. Create a process like tcp4_process_with_conversational_screen.json uploaded
2. Assign a conversational form in the task
3. Create a new case
- https://processmaker.atlassian.net/browse/FOUR-21371
ci:deploy
ci:package-webentry:feature/FOUR-21371
ci:connector-docusign:feature/FOUR-21371
.
=> FOUR-21371: Task: The conversational form is not showing correctly

composer.json, composer.lock
https://processmaker.atlassian.net/browse/FOUR-21469
=> FOUR-21469 Upgrade PHP to 8.3 and manual testing

database/processes/screens/default-email-task-notification.json
- https://processmaker.atlassian.net/browse/FOUR-20675
ci:deploy
=> FOUR-20675:Create the DEFAULT EMAIL SCREEN related to this email

resources/grafana/MainDashboard.json, resources/grafana/README.md
- https://processmaker.atlassian.net/browse/FOUR-21033
ci:processmaker-bpmn-moddle:release-2024-fall
=> FOUR-21033 Grafana Dashboard for Task Metrics

resources/grafana/MainDashboard.json
- https://processmaker.atlassian.net/browse/FOUR-21036
=> FOUR-21036 Top Slowest Tasks by Customer and Execution Time

resources/jscomposition/cases/casesMain/config/columns.js, resources/lang/en.json, resources/lang/es.json
- https://processmaker.atlassian.net/browse/FOUR-20624
ci:deploy
=> FOUR-20264: UI Update for show tasks and update the label Current Task

resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/cases/casesMain/utils/filters.js
1. Go cases list
2. Apply a filter 
3. Remove the filter with the action X in Badges
4. Refresh
The action X needs to remove this specific filter 
- https://processmaker.atlassian.net/browse/FOUR-21548
=> FOUR-21548:The clear action in Badges is not clear the filter

ProcessMaker/Traits/TaskResourceIncludes.php
1. Log in to processmaker
2. Go to Designer, (you can create a simple process)
3. Run a new request and in the DATA tab you can create a NEW SCENARIO 
4. Go to Designer, choose the Process click on the 3 points menu click on RUN  TEST
5. Choose the Starting Point, as well as the task and the scenario.
6. See at the bottom of the task the TEST click on.
7. Will see the form, and you will click on the DATA tab, there you can change the form values, once you finish editing the form, you will be able to click on SAVE
- https://processmaker.atlassian.net/browse/FOUR-14263
ci:processmaker-bpmn-moddle:release-2024-fall
=> FOUR-14263: The button SAVE is not working in TEST option

resources/jscomposition/cases/casesMain/config/columns.js
Case Title filter has number type
- https://processmaker.atlassian.net/browse/FOUR-21174
=> FOUR-21174: Case Title filter has number type

ProcessMaker/Http/Controllers/Api/UserController.php, database/migrations/2025_01_09_210416_add_email_task_notification_to_users_table.php
Please consider this task email notification only for new users
- https://processmaker.atlassian.net/browse/FOUR-21595
=> FOUR-21595: Please consider this task email notification only for new users

resources/grafana/MainDashboard.json
- https://processmaker.atlassian.net/browse/FOUR-21016
=> Add Script Task Metrics Collection

ProcessMaker/Http/Controllers/TaskController.php, resources/js/tasks/components/DashboardViewer.vue, resources/js/tasks/components/ProcessesDashboardsMenu.vue, resources/js/tasks/router.js, resources/views/tasks/index.blade.php
- Login PM4
- Go to Admin -> Groups
- Select some Group and EDIT
- A new dropdown called "Default Page Dashboards" should be displayed
- Choose one or more Dashboards (It is not necessary to press SAVE button)
- Go to HOME
- Select some Dashboard from left Pane
https://processmaker.atlassian.net/browse/FOUR-20304
=> Feature/FOUR-20304: Dashboards in Inbox - Implement list of dashobards asigned to Participant's group in List Pane

ProcessMaker/Services/ScriptMicroserviceService.php
=> FOUR-24596: Cases are stopped when a script task is executed

resources/js/tasks/edit.js, resources/views/tasks/edit.blade.php
There is not auto save button in task detail
- The code that was deleted, _perhaps by mistake_, has been recovered. The previous deletions occurred in the context of this ticket: https://processmaker.atlassian.net/browse/FOUR-20583.
Ensure autosave works for Requests / Tasks as expected.
- [FOUR-21622](https://processmaker.atlassian.net/browse/FOUR-21622)
[FOUR-21622]: https://processmaker.atlassian.net/browse/FOUR-21622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-21622: There is not auto save in task details

composer.json, composer.lock
Tests\Unit\JwtServiceTest::testGenerateToken
ErrorException: Undefined array key "company_name"
https://processmaker.atlassian.net/browse/FOUR-21803
##Solution
Downgrade lcobucci/jwt ^5.4 to lcobucci/jwt ^4.2, Our implementation is not compatible with version ^5.4.
=> FOUR-21803 Fix failing unit tests

ProcessMaker/ImportExport/Exporters/ExporterBase.php
- Login 
- Create a simple process (start event - task - end event)
- Select Test intertitial  
- **Translate the process to pt-BR**
- Export the created process
- Instead of searching in the array of languages constant, use the languages stored in the table languages in the DB.
- https://processmaker.atlassian.net/browse/FOUR-21829
- https://processmaker.atlassian.net/browse/FOUR-21837
=> Get available languages from database table

ProcessMaker/Models/ScriptExecutor.php, ProcessMaker/Models/ScriptExecutorVersion.php
=> Add type cast in ScriptExecutor model

ProcessMaker/Models/Script.php, ProcessMaker/Models/ScriptExecutor.php
This PR improves error handling and refines the Script Executor assignment logic to prevent issues with missing executors during package installation.
- Added error logging when a Script Executor is not found in console mode, preventing exceptions from being thrown.
- Improved validation to prevent invalid executor IDs from being assigned to scripts.
1. Ensure no Script Executors are installed.
2. Remove Script Executors from the database to simulate a fresh installation.
3. Install the following packages:
- connector-docusign
- connector-pdf-print
- connector-slack
- package-data-sources
- package-actions-by-email
- package-auth
4. Verify that:
- No errors occur during installation.
- All packages install successfully.
https://processmaker.atlassian.net/browse/FOUR-21851
=> Enhance Error Handling and Script Executor Validation for Package Installation

resources/jscomposition/system/table/filter/defaultFilter/FilterColumn.vue
The cancel button does not clear input from case list filters
Clear the data the cancel button is pressed
Steps to Reproduce
Create cases
Go to All cases list
In the filter of the columns type some values
Press the Cancel button
Open the input of the filters again
https://processmaker.atlassian.net/browse/FOUR-21805
=> observation/FOUR-21805 The cancel button does not clear input from case list filters

ProcessMaker/Http/Controllers/CasesController.php, resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/Tabs.vue
You're saying that since upgrading to version 4.13, the Overview section is taking longer to load compared to the build verified in the epic. You want to explore ways to improve this loading time.
- https://processmaker.atlassian.net/browse/FOUR-21818
ci:deploy
=> FOUR-21818: Integration: Review if we can improve the time for the Overview

ProcessMaker/Console/Commands/ProcessMakerLicenseRemove.php, ProcessMaker/Console/Commands/ProcessMakerLicenseUpdate.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php
Reverts https://github.com/ProcessMaker/processmaker/pull/8007
=> Revert license optimize command

ProcessMaker/Console/Commands/InitializeScriptMicroservice.php, ProcessMaker/Enums/ScriptExecutorType.php, ProcessMaker/Models/ScriptExecutor.php, tests/Feature/Console/InitializeScriptMicroserviceTest.php
Add initialize script microservice command
https://processmaker.atlassian.net/browse/FOUR-21943
=> Add initialize script microservice command

resources/js/processes/modeler/components/inspector/TaskNotifications.vue
1. Create a new process
2. Create two task
3. Open quickly the Notifications
- https://processmaker.atlassian.net/browse/FOUR-21712
ci:deploy
..
=> FOUR-21712:Form Task does not enable the assigne and Due

ProcessMaker/BuildSdk.php
Fixes https://processmaker.atlassian.net/browse/FOUR-21968
=> Fix multiple generators running at once and cleanup

resources/js/next/libraries/vueFormElements.js, resources/js/next/screenBuilder.js
1. Create a screen form 
2. Add signature control
3. Mark as required
4. Add more controls like: (Line input, text area)
5. Create a case
6. Open the task
7. Change the controls to auto save will be enabled
8. Clear the draft 
9. Refresh the page
10. Click on submit button
The signature control disappears after refresh the page. If the field is required the form cannot be completed 
- https://processmaker.atlassian.net/browse/FOUR-21927
ci:deploy
..
=> FOUR-21927: The signature control disappears after refresh the page

resources/js/next/libraries/vueFormElements.js, resources/js/next/screenBuilder.js
=> [DO NOT MERGE]

resources/js/admin/devlink/components/BundleConfigurations.vue
Local Bundle UI settings error
Fixed the UI settings bundle toggle
Open a local bundle
Switch on the UI Settings
The next error is displayed
https://processmaker.atlassian.net/browse/FOUR-21940
=> observation/FOUR-21940 Local Bundle UI settings error

ProcessMaker/ImportExport/DependentType.php, ProcessMaker/ImportExport/Exporters/MediaExporter.php, ProcessMaker/Models/Bundle.php, ProcessMaker/Models/BundleAsset.php, ProcessMaker/Models/DevLink.php, resources/js/admin/devlink/components/BundleConfigurations.vue, tests/Model/DevLinkTest.php
Every time a bundle is created a new notification token is created
Fix the notification when a bundle is updated
Create a new devlink
Install a remote bundle 
Publish a new version of that bunlde
Update that bundle
Check in the DB if a new record is created on the table bundle_instances after the update
https://processmaker.atlassian.net/browse/FOUR-21982
=> observation/FOUR-21982 Every time a bundle is created a new notification token is created

ProcessMaker/Http/Controllers/Api/DevLinkController.php, ProcessMaker/ImportExport/DependentType.php, ProcessMaker/ImportExport/Exporters/MediaExporter.php, ProcessMaker/Models/Bundle.php, ProcessMaker/Models/BundleAsset.php, ProcessMaker/Models/DevLink.php, database/migrations/2025_02_26_194048_modify_client_secret_in_dev_links_table.php, tests/Model/DevLinkTest.php, upgrades/2025_02_25_215239_encrypt_devlink_tokens.php, upgrades/2025_02_26_162124_encrypt_bundle_webhook_token.php
Encrypt devlink tokens
Encrypted the devlink tokens and created the upgrade scripts
Create a new devlink
See if the tokens on the  devlink table are encrypted
See if the upgrade script encrypts the old tokens
https://processmaker.atlassian.net/browse/FOUR-22128
=> observation/FOUR-22128 Encrypt devlink tokens

resources/js/processes/modeler/components/inspector/ScreenSelect.vue, resources/js/processes/modeler/components/inspector/TaskInterstitial.vue
Configure "Screen Interstitial"
- add test for interstitial reconsolidate screens
run the cypress test TCP4Interstitial.spec.js added in the related projects
- https://processmaker.atlassian.net/browse/FOUR-20488
- https://github.com/ProcessMaker/cypress-tests-platform/pull/3039
- https://github.com/ProcessMaker/cypress-utils/pull/388
=> FOUR-20488: Configure "Screen Interstitial"

README.md
=> Trigger veracode

phpunit.package.xml
Currently available in package-decision-engine
- https://processmaker.atlassian.net/browse/FOUR-21556
=> FOUR-21556 Add support for coverage report in packages

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/base/table/TCell.vue, resources/jscomposition/system/table/cell/truncatedGroupOptionsCell/TruncatedGroupOptionsCell.vue
- https://processmaker.atlassian.net/browse/FOUR-22148
ci:deploy
=> FOUR-22148: The ellipsis in the column task is always showing

resources/js/requests/components/screenPreview.vue
- Create a process or import
- Add screen with select with data connector
- Assign the screen in the form task of the process
- Click on widows pane
- Check the values of the select list
- Set the vue-form-renderer in preview mode
Use the reproduction steps
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-22186)
=> FOUR-22186: The values in select list with Data connector or collection are not visible in Windows pane

resources/views/tasks/index.blade.php
1.Log In
2.Click on +Case
3.Scroll
A fairly large white space is shown.
- https://processmaker.atlassian.net/browse/FOUR-22623
ci:deploy
=> FOUR-22623: White space in new-request-modal-pagination

resources/js/admin/devlink/components/BundleContent.vue
`Avoided redundant navigation to current location` message is displayed in `local bundles` tab
Verify the actual route of devlink sidebar
Go to server
ProcessMaker Platform Spring 2025 version 4.14.0+beta-1 (Build #131e867d)
Go to Admin > devlink > local bundle
Do double click over any option in the left menu
https://processmaker.atlassian.net/browse/FOUR-23375
=> observation/FOUR-23375 Verify the actual route of devlink sidebar

resources/js/bootstrap.js, resources/js/processes/designer/PmAgentsButton.vue
This PR implements the ticket https://processmaker.atlassian.net/browse/FOUR-23257
- [FOUR-23257](https://processmaker.atlassian.net/browse/FOUR-23257)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/8103)
- [Package AI PR](https://github.com/ProcessMaker/package-ai/pull/391)
[FOUR-23257]: https://processmaker.atlassian.net/browse/FOUR-23257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Task/FOUR-23257: FOUR-22539 - Table for list of all agents (FE)

resources/js/processes/designer/PmAgentsButton.vue
This PR implements the task https://processmaker.atlassian.net/browse/FOUR-23258
- [FOUR-23258](https://processmaker.atlassian.net/browse/FOUR-23258)
- [Package AI](https://github.com/ProcessMaker/package-ai/pull/388)
- [Core](https://github.com/ProcessMaker/processmaker/pull/8097)
[FOUR-23258]: https://processmaker.atlassian.net/browse/FOUR-23258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Task/FOUR-23258: FOUR-22539 - Base Controller for agent list(BE)

ProcessMaker/Mail/TaskActionByEmail.php
1. Create a userA
2. Edit User
3. Enable the Task Notification Email
4. Create a process assign the userA
5. Start a new Case
- https://processmaker.atlassian.net/browse/FOUR-22381
ci:deploy
=> FOUR-22381: The Email is not arriving an error in the 4.14 Beta3

ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, resources/js/tasks/components/ProcessesDashboardsMenu.vue
- Endpoint to call processes where user participates was modified to exclude system processes
-Login PM4
- Go to Home and check processes list
- https://processmaker.atlassian.net/browse/FOUR-23539
=> Observation/FOUR-23539: Process list showing system processes

ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php, tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
- Create a process with two controls dataA, dataB
- Create request in the process
- Create a saved search in base to process created
- Go to saved search configuration
- Go to columns
- Add all columns available in active columns (dataA, dataB)
- Save the changes 
- Return to the columns
- Check the Available columns  (Many records are listed in available columns)
- Delete the columns dataA, dataB
- Return to the columns
Columns that do not belong to the saved search are listed in available columns
Only the variables that belong to saved search should listed in columns available 
- Fix the query to not show duplicated variables.
- [FOUR-23515](https://processmaker.atlassian.net/browse/FOUR-23515)
[FOUR-23515]: …
=> Bugfix/FOUR-23515: Columns that do not belong to the saved search are listed in available columns

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/base/table/THeader.vue, resources/jscomposition/base/table/composables/columnComposable.js, resources/jscomposition/cases/casesMain/App.vue, resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/cases/casesMain/api/index.js, resources/jscomposition/cases/casesMain/main.js, resources/jscomposition/cases/casesMain/store/index.js, resources/jscomposition/cases/casesMain/store/store.js, resources/jscomposition/cases/casesMain/variables/index.js, resources/jscomposition/system/table/FilterableTable.vue
1. Go to cases
2. Resize the column task
3. Refresh the cases page
Current Behavior
The resize is not keep after the refresh
- https://processmaker.atlassian.net/browse/FOUR-23550
ci:deploy
=> FOUR-23550: The configure size columns configuration is not keep

resources/js/components/shared/ColumnChooser.vue, resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/defaultTaskColumns.js
In launchpad and home screen inbox, reset to defaults was not working. See Jira issue
- Correctly set the default values instead of empty values
See Jira for reproduction steps
- https://processmaker.atlassian.net/browse/FOUR-22891
=> FOUR-22891 - Fix reset to default columns

database/migrations/2025_03_24_223125_make_dev_links_client_secret_nullable.php
Column should be nullable
- Add migration to make it nullable
Add a dev link to any other instance from a Fresh instance. If there is no error, it works
- https://processmaker.atlassian.net/browse/FOUR-23614
ci:deploy
=> FOUR-23614 - Fix dev link nullable column

ProcessMaker/Repositories/SettingsConfigRepository.php, database/migrations/2025_03_26_015427_change_bundles_webhook_token_to_text.php, upgrades/2025_02_26_162124_encrypt_bundle_webhook_token.php
Make the bundle webhook token column nullable
=> Fix upgrade

resources/js/tasks/api/index.js, resources/js/tasks/components/TasksPreview.vue, resources/js/tasks/components/taskPreview/TaskPreviewAssignment.vue, resources/js/tasks/edit.js, resources/js/tasks/variables/index.js
- https://processmaker.atlassian.net/browse/FOUR-23419
ci:deploy
=> FOUR-23419: Implement new UI for new comments

resources/jscomposition/system/table/TablePlaceholder.vue
This PR implements the tickets:
https://processmaker.atlassian.net/browse/FOUR-23248
https://processmaker.atlassian.net/browse/FOUR-23256
- [Package AI PR](https://github.com/ProcessMaker/package-ai/pull/395)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/8158)
=> Task/FOUR-23248: FOUR-22539 - Endpoint to get the agents list (BE) and FOUR-22539 - Controller for the list of all agents (BE)

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Models/Setting.php, resources/js/admin/settings/components/ModalWhiteList.vue, resources/js/admin/settings/components/SettingsListing.vue, routes/api.php, upgrades/2025_03_31_140423_add_menu_frame_whitelist.php
Add the menu for white list
- https://processmaker.atlassian.net/browse/FOUR-23362
- https://processmaker.atlassian.net/browse/FOUR-23130
- https://processmaker.atlassian.net/browse/FOUR-23131
ci:deploy
=> FOUR-23362:S1 : Add in the setting the menu Iframe Whitelist Config

resources/js/tasks/components/ParticipantHomeScreen.vue, resources/js/tasks/components/ProcessesDashboardsMenu.vue
- Login PM4 as Admin
- Create new Group and new User
- Assign user to created Group
- Create a new Dashboard
- Go to Admin -> Groups
- Select Group created previously and clic on EDIT
- In dropdown called "Default Page Dashboards" select previous Dashboard created and SAVE and stay in the session
- Login with new USER in Incognito Window
- The new dashboard created should be displayed in the left side bar
- Click on the dashboard to view its contents
- In The Main session with admin, go to CustomizeUI->Dashboards and delete Dashboard created for this use case
- Go to Incognito Window and click in Home
- No error should be displayed
IMPORTANT: A new column with JSON format called "selected_dashboards"was added to "dynamic_ui" table in order to store dashboard configurations by group. …
=> observation/FOUR-23646: Server Error iin Home page with user with dashboard delete, while the session is active

resources/js/admin/devlink/components/BundleSettingsModal.vue
devLink > Options are Duplicate
Added the setting group to the description
Go to serverA 
ProcessMaker Platform Spring 2025 Version 4.14.0 (Build #91ba44d7)
Create a local bundle
Add some assets
Publish a bundle
Go to Settings
Create a new mail server
Add to bundle the settings > Email
https://processmaker.atlassian.net/browse/FOUR-23693
=> devLink > Options are Duplicate 

resources/js/processes-catalogue/components/charts/ListChart.vue
1. Import a process
2. Not create request yet
3. Go to Request 
4. Create a saved search in base the process
5. Create a  chart 
6. Go to process launchpad
7. Open any process by launchpad
8. Click on Edit launch pad
9. Open dev console
10. In Chart selected the Chart created with empty data
- https://processmaker.atlassian.net/browse/FOUR-23689
ci:deploy
=> FOUR-23689: Cannot read properties of null (reading 'colorScheme') Error with chart without data in Launchpad chart

ProcessMaker/Listeners/HandleEndEventRedirect.php
Implement redirection improvement
- improve an refactor HandleEndEventRedirect
n/a
- https://processmaker.atlassian.net/browse/FOUR-23386
=> FOUR-23386: Implement redirection improvement

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Models/ProcessRequestToken.php, database/migrations/2025_04_08_115507_add_the_comments_field_to_the_process_request_token_table.php, tests/Feature/Api/TaskControllerTest.php
- The following API to assign (reasign) a user needs to receive a comment
- or in order to register a TASK COMMENT
https://processmaker.atlassian.net/browse/FOUR-23421
ci:deploy
=> FOUR-23421 S1: BE - The comments needs to use in comment to Endpoint

resources/js/app-layout.js, resources/js/next/layout/navbar.js, resources/views/layouts/navbar.blade.php
This PR Implements the ticket https://processmaker.atlassian.net/browse/FOUR-23333
- [Core](https://github.com/ProcessMaker/processmaker/pull/8179)
- [Package AI](https://github.com/ProcessMaker/package-ai/pull/412)
=> Task/FOUR-23333: FOUR-22545 - Chat Agent - Implement Sidebar UI (blade, base structure)

upgrades/2025_04_10_220858_create_permission_view_admin_email_log.php
Missing new permission "view-admin-email-log"
Added new upgrade file.
Run artisan upgrade command
https://processmaker.atlassian.net/browse/FOUR-22848
=> FOUR-22562 Implement permission options for Email logs in admin section

resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json, resources/views/admin/email-logs/index.blade.php, routes/web.php
- https://processmaker.atlassian.net/browse/FOUR-22789
=> FORU-22789 Implement Download options CSV - PDF buttons

ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Traits/HasComments.php
- https://processmaker.atlassian.net/browse/FOUR-22982
=> FOUR-22982 Add comments relationship to be used in History Log in processes

ProcessMaker/Models/Setting.php
The SSO configurations are not showing all the information
- https://processmaker.atlassian.net/browse/FOUR-23895
ci:package-product-analytics:feature/FOUR-23926
ci:deploy
=> FOUR-23895: The SSO configurations are not showing all the information

resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonGroup.vue, resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButton.vue, resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButtonGroup.vue, resources/js/processes-catalogue/components/home/Home.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue, tailwind.config.js
- https://processmaker.atlassian.net/browse/FOUR-23575
ci:deploy
=> FOUR-22485: Open launchpad buttons appears templates edit

resources/js/processes/modeler/components/inspector/StageItem.vue, resources/js/processes/modeler/components/inspector/StageList.vue, resources/js/processes/modeler/components/inspector/StageManager.vue, resources/js/processes/modeler/initialLoad.js
##Description
Add Stage Section showed only when the element selected is a FLOW
https://processmaker.atlassian.net/browse/FOUR-23473
=> FOUR-23473 S1: Add stage section for a the flow elements

resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/ProcessOptions.vue, resources/js/processes-catalogue/components/optionsMenu/ProcessDescription.vue, resources/js/processes-catalogue/components/progressBar/ProgressBar.vue, resources/js/processes-catalogue/components/progressBar/ProgressBarSection.vue, resources/js/processes-catalogue/components/progressBar/ProgressInfo.vue, resources/js/processes-catalogue/components/slideProcessInfo/SlideProcessInfo.vue
- https://processmaker.atlassian.net/browse/FOUR-23484
ci:deploy
=> FOUR-23484: S4:FE-Process Info update & Add the UI component to show the total cases per stage

ProcessMaker/Console/Commands/Api2TypescriptCommand.php, ProcessMaker/Http/Controllers/Api/NotificationController.php, ProcessMaker/Http/Controllers/Api/OpenApiSpec.php, ProcessMaker/Http/Controllers/Api/PermissionController.php, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/TaskAssignmentController.php, ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php, ProcessMaker/Models/ProcessRequest.php, resources/stubs/api2typescript/api-index.blade.php, resources/stubs/api2typescript/api-response.blade.php, resources/stubs/api2typescript/api-spec.blade.php, resources/stubs/api2typescript/api.blade.php, resources/stubs/api2typescript/composable.blade.php, resources/stubs/api2typescript/composables-index.blade.php, resources/stubs/api2typescript/main-index.blade.php, resources/stubs/api2typescript/readme.blade.php, resources/stubs/api2typescript/types.blade.php, storage/api-docs/api-docs.json
- https://processmaker.atlassian.net/browse/FOUR-24097
- https://github.com/ProcessMaker/package-data-sources/tree/pm-apps
=> FOUR-24097 ProcessMaker SDK generator

resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonGroup.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonHome.vue, resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButtonGroup.vue, resources/js/processes-catalogue/components/home/Home.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue
- https://processmaker.atlassian.net/browse/FOUR-23577
ci:deploy
=> FOUR-23577: S12: Implement component Financial Aid - College Dashboard

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/CasesController.php, ProcessMaker/Http/Resources/V1_1/CaseResource.php, ProcessMaker/Listeners/BpmnSubscriber.php, ProcessMaker/Models/CaseParticipated.php, ProcessMaker/Models/CaseStarted.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Repositories/CaseApiRepository.php, ProcessMaker/Repositories/CaseRepository.php, ProcessMaker/Repositories/CaseUtils.php, ProcessMaker/Repositories/TokenRepository.php, ProcessMaker/Traits/ProcessMapTrait.php, database/migrations/2025_04_23_162421_add_stages_to_processes_and_process_versions.php, database/migrations/2025_04_23_183734_add_stage_id_and_stage_name_to_process_request_tokens.php, database/migrations/2025_04_23_183839_add_stage_id_and_stage_name_to_process_request.php, database/migrations/2025_04_23_184251_add_stage_id_and_stage_name_to_cases_participated.php, database/migrations/2025_04_23_184327_add_stage_id_and_stage_name_to_cases_started.php, database/migrations/2025_04_25_222214_add_stages_table.php, tests/Feature/Api/ProcessControllerTest.php, tests/Feature/CasesControllerTest.php
S2: FE - Add new columns and prepare structure in the tables
- https://processmaker.atlassian.net/browse/FOUR-22734
- https://processmaker.atlassian.net/browse/FOUR-23480
- https://processmaker.atlassian.net/browse/FOUR-23479
- https://processmaker.atlassian.net/browse/FOUR-23481
=> FOUR-23478: S2: FE - Add new columns and prepare structure in the tables

ProcessMaker/Bpmn/MustacheOptions.php
=> Added support for PRAGMA_FILTERS in mustache

ProcessMaker/Http/Controllers/CasesController.php, ProcessMaker/Http/Resources/V1_1/CaseResource.php, ProcessMaker/Models/CaseParticipated.php, ProcessMaker/Models/CaseStarted.php, ProcessMaker/Repositories/CaseApiRepository.php, ProcessMaker/Repositories/CaseRepository.php, ProcessMaker/Repositories/CaseUtils.php, ProcessMaker/Repositories/TokenRepository.php, database/migrations/2025_04_23_183734_add_stage_id_and_stage_name_to_process_request_tokens.php, database/migrations/2025_04_23_183839_add_stage_id_and_stage_name_to_process_request.php, database/migrations/2025_04_23_184251_add_stage_id_and_stage_name_to_cases_participated.php, database/migrations/2025_04_23_184327_add_stage_id_and_stage_name_to_cases_started.php, tests/Feature/CasesControllerTest.php
FOUR-24219: Update the structure of tables: process_request and cases_started and cases_participated
- https://processmaker.atlassian.net/browse/FOUR-24219
ci:deploy
=> FOUR-24219: Update the structure of tables: process_request and cases_started and cases_participated

ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, ProcessMaker/Traits/ProcessTrait.php, resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/progressBar/ProgressBarSection.vue, resources/js/processes-catalogue/components/progressBar/ProgressInfo.vue, tests/Feature/Api/ProcessLaunchpadTest.php
Create a new API to return total cases per Stage
- https://processmaker.atlassian.net/browse/FOUR-23485
=> FOUR-23485: Create a new API to return total cases per Stage

ProcessMaker/Http/Controllers/CasesController.php, resources/jscomposition/cases/casesDetail/components/StageBar.vue, resources/jscomposition/cases/casesDetail/edit.js, resources/jscomposition/cases/casesDetail/variables/index.js, resources/views/cases/edit.blade.php
- https://processmaker.atlassian.net/browse/FOUR-23483
=> FOUR-23483: Add in Details the Stage and bar

ProcessMaker/Http/Controllers/Api/CaseController.php, config/app.php, routes/api.php, tests/Feature/CasesControllerTest.php
Get information to show status of the stages in the Case Progress Bar control
- https://processmaker.atlassian.net/browse/FOUR-24229
=> FOUR-24229: Get information to show status of the stages in the Case Progress Bar control

resources/js/processes-catalogue/components/BaseChart.vue, resources/js/processes-catalogue/components/CarouselSlide.vue, resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/ProcessOptions.vue, resources/js/processes-catalogue/components/ProcessesCarousel.vue, resources/js/processes-catalogue/components/mixins/CarouselMixin.js, resources/js/processes-catalogue/components/slideProcessInfo/SlideProcessInfo.vue, resources/views/tasks/index.blade.php
- https://processmaker.atlassian.net/browse/FOUR-24148
ci:deploy
=> FOUR-24148: UI related Process Info - Carousel (refactor)

ProcessMaker/Nayra/Managers/WorkflowManagerDefault.php
The PRs implements
- The ticket https://processmaker.atlassian.net/browse/FOUR-24057
- Various callback fixes
- [Core](https://github.com/ProcessMaker/processmaker/pull/8240)
- [Package AI](https://github.com/ProcessMaker/package-ai/pull/420)
- [PM4 AI microservice](https://github.com/ProcessMaker/pm4_ai/pull/86)
- [PM Apps](https://github.com/ProcessMaker/pm-apps/pull/82)
ci:package-private-equity:main
ci:package-collection:pm-apps
ci:package-data-sources:pm-apps
ci:connector-send-email:pm-apps
ci:modeler:pm-apps
=> Task/FOUR-24057: Interest check - Generate summary for each company

ProcessMaker/Models/TimerExpression.php, database/processes/templates/IntermediateTimerEventFEEL.bpmn, tests/Feature/Api/IntermediateTimerEventTest.php
- https://processmaker.atlassian.net/browse/FOUR-24299
ci:package-private-equity:main
ci:package-collection:pm-apps
ci:package-data-sources:pm-apps
ci:connector-send-email:pm-apps
ci:modeler:pm-apps
=> FOUR-24299 Add support to FEEL expressions to timer events in Modeler

ProcessMaker/Http/Controllers/Api/CaseController.php, tests/Feature/CasesControllerTest.php
The following results example will return:
```
"parentRequest" => array:4 [
"id" => 16
"case_number" => 13
"status" => "ACTIVE"
"completed_at" => null
]
"requestCount" => 2
"all_stages" => []
"current_stage" => []
"stages_per_case" => array:3 [
0 => array:4 [
"id" => 1
"name" => "Stage A"
"status" => "Done"
"completed_at" => "2025-04-23 21:22:34"
]
1 => array:4 [
"id" => 2
"name" => "Stage B"
"status" => "In Progress"
"completed_at" => "null"
]
2 => array:4 [
"id" => 3
"name" => "Stage C"
"status" => "Pending"
"completed_at" => ""
]
]
]
```
- https://processmaker.atlassian.net/browse/FOUR-24227
=> FOUR-24227: Adding changes in order to get the status: Done, In progres, Pending

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/Process.php, routes/api.php
Return information for the Stages and Metrics
- https://processmaker.atlassian.net/browse/FOUR-24234
=> FOUR-24234: Return information for the Stages and Metrics

resources/js/components/shared/LaunchpadSettingsModal.vue, resources/js/processes-catalogue/components/Process.vue, resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/api/index.js, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonGroup.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonHome.vue, resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButton.vue, resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButtonGroup.vue, resources/js/processes-catalogue/components/home/CustomHomeScreen.vue, resources/js/processes-catalogue/components/home/CustomHomeTableSection/CustomHomeTableSection.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue, resources/js/processes-catalogue/components/home/ProcessInfo.vue, resources/js/processes-catalogue/components/home/TceDistributionCollege.vue, resources/js/processes-catalogue/components/home/TceDistributionGrants.vue, resources/js/processes-catalogue/components/home/TceDistributionStudent.vue, resources/js/processes-catalogue/components/home/config/columns.js, resources/js/processes-catalogue/components/home/config/index.js, resources/js/processes-catalogue/components/home/config/metrics.js, resources/js/processes-catalogue/components/home/config/requestDefaultColumns.js, resources/js/processes-catalogue/components/variables/index.js, resources/jscomposition/system/table/cell/ProgressBarCell.vue, resources/jscomposition/system/table/cell/index.js, resources/views/tasks/index.blade.php
- https://processmaker.atlassian.net/browse/FOUR-24089
ci:deploy
=> FOUR-24089 : S12: Create the view to show a dashboard with the components related to "Financial Aid - College Dashboard"

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/Process.php, routes/api.php, tests/Feature/Api/ProcessControllerTest.php
API Return information for the Stages and Metrics
- https://processmaker.atlassian.net/browse/FOUR-24234
=> FOUR-24234: API Return information for the Stages and Metrics 

resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
- https://processmaker.atlassian.net/browse/FOUR-24336
ci:deploy
=> FOUR-24336:Create a new View when a case is open and the TCE_CUSTOMIZATION_ENABLED is enabled

resources/js/processes-catalogue/components/api/index.js, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonGroup.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonHome.vue, resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButton.vue, resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButtonGroup.vue, resources/js/processes-catalogue/components/home/CustomHomeTableSection/CustomHomeTableSection.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue, resources/js/processes-catalogue/components/home/TceDistributionCollege.vue, resources/js/processes-catalogue/components/home/TceDistributionGrants.vue, resources/js/processes-catalogue/components/home/TceDistributionStudent.vue, resources/js/processes-catalogue/components/home/config/metrics.js, resources/js/tasks/components/ParticipantHomeScreen.vue, tailwind.config.js
- https://processmaker.atlassian.net/browse/FOUR-24454
ci:deploy
=> FOUR-24454 : S12: Update/Adjustments some behaviors the Dashboard

ProcessMaker/Events/BaseEmailEvent.php, ProcessMaker/Events/EmailComplaint.php, ProcessMaker/Events/EmailDelivered.php, ProcessMaker/Events/EmailLinkClicked.php, ProcessMaker/Events/EmailSent.php, ProcessMaker/Events/EmailViewed.php, tests/Feature/Events/EmailEventTest.php
Review Clicked Links in Email are not working as expected
- fix and improvements
https://github.com/user-attachments/assets/34996283-0d5f-4cb3-bfc7-dc02e5b0b16e
run the attached process in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-24476
=> FOUR-24476: Review Clicked Links in Email are not working as expected

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/Process.php, tests/Feature/CasesControllerTest.php
Return Metrics information
- https://processmaker.atlassian.net/browse/FOUR-24457
ci:deploy
=> FOUR-2445: S12: API - Return Metrics information

resources/js/components/templates/WizardTemplateDetails.vue
This PR addresses a visual issue where the SAVE AND FINISH button inside dynamically rendered screens (created by the PLG team and rendered via the wizard-template package) appears distorted due to a fixed width (width: 170px) applied via custom CSS:
```
.custom-css-scope [selector="btn-bx1"] button {
width: 170px;
}
```
The wizard-template repo defines this style explicitly, assuming a fixed-width button design. However, when certain fonts (e.g., Comic Sans) are used, the text width exceeds the fixed value, causing overflow or distorted layouts.
**Reproduction Steps**
1. Open a guided template with a screen that includes a submit button using the selector btn-bx1.
2. Change the font to Comic Sans (or any wide font).
3. Observe that the button gets cut off or misaligned due to the fixed …
=> FOUR-24616: The "Save and Finish" button when creating a process from a guide template is distorted

resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue, resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonHome.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue, resources/js/processes-catalogue/components/home/TceDistributionGrants.vue, resources/js/processes-catalogue/components/home/config/metrics.js
1. Create a process with stages
2. Create a case related
3. Use the Screen Distribution Bar Grants
4. See the Stages component
- https://processmaker.atlassian.net/browse/FOUR-24757
=> FOUR-24757: UI: Update Grants according the figma

resources/js/processes-catalogue/components/ProcessTab.vue
- https://processmaker.atlassian.net/browse/FOUR-24963
ci:deploy
=> FOUR-24963: Cases and Tasks are not listed in launchpad when a saved search is added

resources/js/processes/modeler/components/inspector/AgregationProperty.vue, resources/js/processes/modeler/components/inspector/StageItem.vue, resources/js/processes/modeler/components/inspector/StageList.vue
1. Create a new process
2. Click in the Flow in order to see the Stages Section
3. Open the Stage section
4. Add a new Stage with Empty
Is posible create an Empty stage only spaces
Validate the Stage name is required
- https://processmaker.atlassian.net/browse/FOUR-24705
- https://processmaker.atlassian.net/browse/FOUR-24706
- https://processmaker.atlassian.net/browse/FOUR-24780
ci:deploy
=> FOUR-24705:The Stage Name is required

ProcessMaker/Providers/JsonOptimizerServiceProvider.php, config/app.php, docs/json-optimization.md, tests/Fixtures/json_optimizer_test_example.json, tests/unit/ProcessMaker/JsonOptimizerTest.php
Code Integration with simdjson and uopz
- https://processmaker.atlassian.net/browse/FOUR-24986
ci:deploy
=> FOUR-24986: Code Integration with simdjson and uopz

resources/js/processes/modeler/components/inspector/StageItem.vue, resources/js/processes/modeler/components/inspector/StageList.vue
It is not possible to start a case if the process has large stage name
- https://processmaker.atlassian.net/browse/FOUR-24981
ci:deploy
=> FOUR-24981: It is not possible to start a case if the process has large stage name

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Providers/JsonOptimizerServiceProvider.php, ProcessMaker/Support/JsonOptimizer.php, config/app.php, docs/json-optimization.md, helpers.php, tests/unit/ProcessMaker/JsonOptimizerTest.php
Implements support for https://github.com/awesomized/simdjson-plus-php-ext.
https://processmaker.atlassian.net/browse/FOUR-25161
ci:deploy
=> FOUR-25161 Implement SIMDJSON for json_encode

ProcessMaker/Events/MessageEventThrown.php
Implements 
https://processmaker.atlassian.net/browse/FOUR-25207
Related PRs:
https://github.com/ProcessMaker/processmaker/pull/8355
https://github.com/ProcessMaker/package-private-equity/pull/66
https://github.com/ProcessMaker/pm-apps/pull/209
=> Add accesors for Message Events

resources/img/arrow_top_right.svg
- https://processmaker.atlassian.net/browse/FOUR-25240
ci:deploy
ci:connector-send-email:feature/FOUR-25240
ci:screen-builder:feature/FOUR-25240
=> FOUR-25240:Implement property linkDisplayStyle = [LINK, BUTTON]

ProcessMaker/ImportExport/Exporters/ScriptExporter.php
When selecting 'Update' while importing a Guided Template script that already exist in the system, the import process fails with a database constraint violation error:
```
Integrity constraint violation: 1062 Duplicate entry '244' for key 'data_source_scripts.data_source_scripts_script_id_unique'
```
This occurs because the `data_source_scripts` table has a unique constraint on the `script_id` column, and when updating an existing script, there are duplicate records in the `data_source_scripts` table that violate this constraint.
Added pre-save cleanup logic in the `ScriptExporter::import()` method to:
1. Check for update mode: Only run cleanup when importing in update mode
2. Verify model exists: Ensure the script model exists in the database
3. Detect data source relationships: Check if …
=> Fix data source scripts constraint violation during Guided Template script import

ProcessMaker/Console/Commands/ProcessMakerLicenseRemove.php, ProcessMaker/Console/Commands/ProcessMakerLicenseUpdate.php, ProcessMaker/Console/Commands/TenantsCreate.php, ProcessMaker/Console/Commands/TenantsTransition.php, ProcessMaker/LicensedPackageManifest.php, ProcessMaker/Multitenancy/SwitchTenant.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, ProcessMaker/Repositories/SettingsConfigRepository.php, config/filesystems.php, resources/js/bootstrap.js, resources/js/common/TenantAwareEcho.js, resources/js/next/libraries/broadcast.js, tests/Feature/LicenseCommandsTest.php, tests/Feature/LicenseTest.php, tests/Feature/MediaConfigTest.php, tests/Model/DevLinkTest.php
- FIx laravel echo subscription
- Fix tenants:create command
- Support for tenant custom languages
- Store license in a non-MT disk (storage instead of storage/app)
=> Multitenancy Fixes
