ProcessMaker/Http/Resources/Task.php, resources/js/requests/components/RequestDetail.vue
Create a table with +100000 requests that are part of a self service task
Open one of those requets (url  /requests/nnn, where nnn = request id)
It will take 5 or more seconds to render the task list
Avoid duplicated assignable users logic when returning a request detail
https://processmaker.atlassian.net/browse/FOUR-6777
=> FOUR-6777 (for 4.127) : Improve performance of request detail screen when using self service

ProcessMaker/Http/Resources/Task.php, resources/js/requests/components/RequestDetail.vue
Create a table with +100000 requests that are part of a self service task
Open one of those requets (url  /requests/nnn, where nnn = request id)
It will take 5 or more seconds to render the task list
Avoid duplicated assignable users logic when returning a request detail
https://processmaker.atlassian.net/browse/FOUR-6777
=> FOUR-6777: Improve performance of request detail screen when using self service

ProcessMaker/Jobs/ImportScreen.php
A message "Please assign a run script user to: ." showing also when the screen doesn't have any watcher.
- Have a screen without watchers
- Import the screen
Screen that does not have any configuration with script when importing get error messages related to script appears
Script message errors should appears , when the screen use them
- Show message info only when watchers exists in the screen.
https://user-images.githubusercontent.com/90727999/193351427-d1830fb4-277b-4ed9-83c2-8b34f7a5ddcc.mov
Follow the steps above.
Test a screen with watchers (should show message)
Test a screen without watchers (should not show message)
- [FOUR-6644](https://processmaker.atlassian.net/browse/FOUR-6644)
=> Bugfix/FOUR-6644: Script Message Error, to importing a single screen

ProcessMaker/Models/ProcessMakerModel.php
Ethos Sync Process has problems with https://laravel.com/docs/7.x/upgrade#date-serialization
(Check the following error log)
```
Service task failed: package-ellucian-ethos/import-users - SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2022-10-18T14:28:13.000000Z' for column 'created_at' at row 1 (SQL: insert into `group_members` (`created_at`, `group_id`, `id`, `member_id`, `member_type`, `updated_at`) values (2022-10-18T14:28:13.000000Z, 6, 161, 163, ProcessMaker\Models\User, 2022-10-18T14:28:13.000000Z), (2022-10-18T14:28:13.000000Z, 6, 162, 164, ...
```
- Keep the compatibility setting the serialization date format.
- Use ProcessMaker, the date/time fields should keep the previous behavior.
- Ethos Sync Process, should not fail.
- …
=> Date format compatibility

ProcessMaker/Console/Commands/MigrateFresh.php
This bug happens when we have an old database named `processmaker` and we try to do a new installation in another database, `processmaker_test` for example.
The solution is to create the migrations table before calling the migrate:install command.
The `ProcessMaker\Console\Commands\MigrateFresh` class seems to be no longer needed, and if confirmed it should be deleted in another PR.
- Do a normal install on a `processmaker` database.
- Create another database, like `processmaker_test` 
- Delete the `.env` file and run  `php artisan processmaker:install` 
- [FOUR-6875](https://processmaker.atlassian.net/browse/FOUR-6875)
=> FOUR-6875 - Fixing command processmaker:install failing

resources/js/requests/components/RequestErrors.vue
- Create any process with a task
- Run a request for the process
- Go to the request view ( request/{id} url )
- Open the browser inspector in console tab
An error shows in the console:
```
vendor.js?id=91fb2ab774296935e4b121c4796b09b1:111958 [Vue warn]: Error in created hook: "TypeError: this.fetch is not a function"
found in
---> <RequestErrors> at resources/js/requests/components/RequestErrors.vue
<Root>
```
No errors should show in the console
- Added fetch function to avoid console error
https://user-images.githubusercontent.com/90727999/196979260-a636a01e-85c1-4e2c-a824-fbcfb52a659a.mov
-  Follow above steps
- [FOUR-6869](https://processmaker.atlassian.net/browse/FOUR-6869)
=> Bugfix/FOUR-6869: Console error shows in request view

tests/bootstrap.php
In [MigrateFresh:35](https://github.com/ProcessMaker/processmaker/blob/develop/ProcessMaker/Console/Commands/MigrateFresh.php#L35), 
the migrations table is being manually created to resolve the bug described in this [PR]( https://github.com/ProcessMaker/processmaker/pull/4537).
Add a configuration so that the migrations table doesn't try to be created.
Run this test:
```
php vendor/phpunit/phpunit/phpunit --colors --stop-on-failure tests/Feature/Api/ChangePasswordTest.php
```
- [FOUR-6933](https://processmaker.atlassian.net/browse/FOUR-6933)
=> Fix failing test related to MigrateFresh - FOUR-6933

package-lock.json, package.json
In https://github.com/ProcessMaker/processmaker/commit/53cf828a5434a525797a47c4c794b92e9d2ecc03#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L25 we removed `@babel-eslint/parser` by mistake. Which is the parser for eslint, our Javascript linter
- Adding it back
* `npm install`
* Go to a Javascript or Vue file
* Make sure you have enabled in your IDE, the Eslint extension, you should see the errors from Eslint.
* Or run the eslint CLI and you should see the output
- https://processmaker.atlassian.net/browse/FOUR-6959
=> FOUR-6959 Added @babel/eslint-parser back

resources/js/requests/components/DataSummary.vue
After a process is completed, it goes to the summary screen, in the reported ticket, the amount of data stored in the process is very large causing the summary screen to take a long time to render it. The main problem here is the <b-table> component.
- Improve the Request Summary screen with large amount of data.
1. Import de process attached to the ticket
2. Mock a Rest Endpoint that returns a large number of data as required by the Screen of the process
3. Run the process
4. Complete the process
_Test data for the Rest Endpoint:_
[test_data.json.zip](https://github.com/ProcessMaker/processmaker/files/9870212/test_data.json.zip)
- https://processmaker.atlassian.net/browse/FOUR-6912
.
=> Improve DataSummary speed with large data

ProcessMaker/Models/ProcessRequestToken.php
Perform a PMQL search query with (IN or NOT IN)
when the search is done not return results and returns a server error.
The search with PMQL (IN, NOT IN) should work fine and not returns a server error.
- Add validation when the value in PMQL is an array
perform PMQL queries on the section to fetch (Request and Tasks)
- [FOUR-6782](https://processmaker.atlassian.net/browse/FOUR-6782)
=> Add validation when value pmql is array

README.md, package-lock.json, package.json
Node and NPM in Core weren't up to date with the latest LTS and there was a security issue with the pipeline and SecOps reported an issue with it
- The pipeline shouldn't have any errors or warnings regarding security issues
- Upgrading Node and NPM to almost the latest LTS
Installing locally node version 16.18.1 which comes with npm version 8.19
Running `npm install` in core
No errors should happen
- https://processmaker.atlassian.net/browse/FOUR-7092
=> FOUR-7092 Updating Node to 16.18.1

ProcessMaker/Http/Resources/Process.php, ProcessMaker/Models/Process.php
- Steps to Reproduce:
- Have a non super admin user with edit and view processes permissions
- Have some processes created
- Login with the non super admin user
- Go to Designer > Processes
- Create or edit a process
- Add a subprocess element
- Click on the subprocess element
- Add a parameter to the endpoint request to retrieve processes with events if the user have permissions for view or edit processes.
https://user-images.githubusercontent.com/90727999/202540656-9eff4554-317e-4e1e-ba84-95eba7555265.mov
- Try with a super admin user and with a non super admin user. Change the edit/view permissions for the non super admin user and see if works as expected.
- [FOUR-7098](https://processmaker.atlassian.net/browse/FOUR-7098)
- [Modeler …
=> Bugfix/FOUR-7098: Process list for Subprocess not showing the processes when the user is not Admin

ProcessMaker/Traits/MakeHttpRequests.php, tests/Feature/MakeHttpRequestTest.php
Important Note:
One test is failing, but is not related to this PR This test has been fixed in package-data-sources (https://github.com/ProcessMaker/package-data-sources/pull/258). After the package is published the test will run ok.
REST connectors didn't have the debug mode enabled.
- Added Logging for request calls
- Rest connectors can have debug mode enabled using the UI
- Enable log mode for a REST connector
- Use a connector in a process or in test mode
- Verify that the log information is registered in data-sources log files.
[https://processmaker.atlassian.net/browse/FOUR-6954](https://processmaker.atlassian.net/browse/FOUR-6954)
=> FOUR-6315: SOAP

resources/js/processes/screen-builder/screen.vue
In Screen Builders Preview Mode, when previewing a conversational form the Data Preview JSON does not update.
With the new changes in the screen builder, we need to emit the data variable when the form values are updated.
- Create a watcher for the data variable and emit an update event.
- Create a Conversational Screen
- Add Input component to the screen and view in Preview Mode
- Input data into the field
https://user-images.githubusercontent.com/52755494/203173778-a01df4f2-82b3-4e2a-9478-c6762c5e94a7.mov
The Data Preview JSON is updated displaying the input's variable name along with the value inputted.
- Ticket - [FOUR-7117](https://processmaker.atlassian.net/browse/FOUR-7117)
- Conversational Forms PR - …
=> Fix: Cannot see "Data Preview" on a conversational type screen

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Jobs/RunScriptTask.php, ProcessMaker/RetryProcessRequest.php, resources/views/requests/show.blade.php
This PR covers the issue(s) covered in FOUR-7110, namely a 422 error which occurred when the user rapidly used the "Retry" button to trigger the retry request feature. 
- Disables the retry button after initial click
- Switches request to "ACTIVE" upon retry
- Switched to better error logging/reporting for when script tasks fail
You should only be able to retry a request once until the page reloads. If the request is in a "In Progress" state, the retry button will not appear (as this is expected). If you refresh again and a script has errored out, it should update the request and you should be able to retry it again.
- https://processmaker.atlassian.net/browse/FOUR-7110
- https://processmaker.atlassian.net/browse/FOUR-6832
=> FOUR-7110: Improved request retry

ProcessMaker/Console/Commands/AuthSetPassword.php
Ticket: [FOUR-6616](https://processmaker.atlassian.net/browse/FOUR-6616)
As a CloudOps engineer I want PM4 to have the ability to reset the admin password via CLI in the workspace, so we no longer need to manually do it copying a script.
Add AuthSetPassword.php with script for resetting admin password from the CLI.
1. Update core branch to `feature/FOUR-6616`.
2. Run `php artisan auth:set-password` in the terminal.
3. Follow instructions to reset password.
4. Test that password has been reset in the UI.
=> FOUR-6616: Add Reset Password CLI Command

resources/js/admin/settings/components/SettingCheckboxes.vue
* Log in 
* click on ADmin
* click on settings 
* click on LDAP
* configure  LDAP 
* click on Groups to Import 
* select groups
* click on SAVE  
- The model variable used  for b-form-checkbox-group was initialized as null or an empty string. This worked with old versions of vue-boostrap. The issue was resolved initializing the variable as an emty array [] 
Documentation: ([b-form-checkbox-group](https://bootstrap-vue.org/docs/components/form-checkbox))
* Use the reproduction steps
* Verify that the console error  this.input.join... etc is no longer present.
To facilitate the test, the next LDAP configuration can be used:
services.ldap.type => openldap
services.ldap.server.address => ldap.forumsys.com
services.ldap.server.port => 389
services.ldap.server.tls => 0
services.ldap.base_dn => …
=> FOUR-6970: error TypeError: this.input.join is not a function, when saving the selected groups for synchronization

ProcessMaker/Helpers/StringHelper.php, ProcessMaker/Traits/MakeHttpRequests.php, ProcessMaker/WebServices/NativeSoapClient.php, ProcessMaker/WebServices/SoapConfigBuilder.php, ProcessMaker/WebServices/SoapRequestBuilder.php
This ticket resolves:
https://processmaker.atlassian.net/browse/FOUR-7153
https://processmaker.atlassian.net/browse/FOUR-7152
https://processmaker.atlassian.net/browse/FOUR-7151
https://processmaker.atlassian.net/browse/FOUR-7145
https://processmaker.atlassian.net/browse/FOUR-6954
- Logging file name has been changed
- Obfuscating Oauth and simple user password information
=> Fixes for SOAP: FOUR-6315

resources/js/bootstrap.js
In development the loading of js assets is fast. So right after login, we normally receive the `.SessionStarted` event coming from the websocket service (Laravel Echo).
In a cloud environment, after login, it takes some time to load the javascript, and when it loads, the `.SessionStarted` event has already been fired.
- Start the counter manually.
In a cloud environment, open an incognito tab, disable caching, log in and don't click on anything. The modal should open normally.
Locally, lower your network speed and do the test above.
The network speed can be 10mbits/s for download and upload and 50ms latency, close to 4g speed.
- [FOUR-6985](https://processmaker.atlassian.net/browse/FOUR-6985)
=> Starting counter manually due network latency - FOUR-6985

database/migrations/2022_08_24_000000_add_uuid_to_failed_jobs_table.php
A new UUID column was introduced to the failed_jobs table in Laravel 8. To account for this a new migration was created to create that column and to populate the UUID for all existing failed jobs. This migration will fail if there is more data in the failed_jobs table than the memory limit set for PHP since the migration will attempt to load all data before updating the existing rows.
1. Make sure the failed_jobs table contains enough data to trigger the memory leak (usually 1 GB or more in size)
2. Check that the migration has not been run yet (named 2022_08_24_000000_add_uuid_to_failed_jobs_table)
3. Run the command php artisan migrate
4. Notice the exception thrown (PHP ran out of memory)
Refactored the migration to use a chunking in the query. This way it will only load a given number …
=> FOUR-7210: Fix memory leak when running migration to add UUID column to failed_jobs table

ProcessMaker/Http/Controllers/Api/TaskController.php
Enable the api to receive include param
=> FOUR-7185: Update OA Definition

ProcessMaker/Http/Controllers/Api/CssOverrideController.php, tests/Feature/Api/CssOverrideTest.php
- Upload images in this  section of Dynamic UI
- Save
- Click on reset buton
Resetting images does not work
Resetting images must work
- Use destroy instead delete to delete the setting for css-override when clicking "reset" button
https://user-images.githubusercontent.com/90727999/210433970-0ca0f384-206a-4969-87f0-e2e2b07b1e19.mov
- Follow above steps. Make sure the images are correctly restored to the original
-  [FOUR-7229](https://processmaker.atlassian.net/browse/FOUR-7229)
[FOUR-7229]: https://processmaker.atlassian.net/browse/FOUR-7229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-7229]: https://processmaker.atlassian.net/browse/FOUR-7229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> Bugfix/FOUR-7229: RESET Custom Logo, Icon and Favicon Images does not work

ProcessMaker/Policies/ProcessRequestPolicy.php, tests/Feature/Api/ProcessRequestPolicyTest.php
We found an issue with the process request view policy while reviewing https://processmaker.atlassian.net/browse/FOUR-7325 that was introduced in https://processmaker.atlassian.net/browse/FOUR-7193
We fixed in on develop. This PR is to backport it to 4.3.1
- Change how we query if the process request exists in the `forUser` scope of process requests
- Create 2 users without permissions.
- Create a new group without permissions and assign the 2 users to them
- Create a simple process Start->end and assign start permission to the new group
- Login as one user and start/complete the process
- Log in as the 2nd user and start/complete the process
- Manually go to the request started by the first user (logged in as the 2nd user)
You'll notice the 2nd user has access to the 1st user's request, …
=> Fix the process request view policy check in 4.3.1

ProcessMaker/Http/Controllers/Auth/LoginController.php
Dupe of #4618 by @nolanpro, intended for v4.3.1.
----
See https://processmaker.atlassian.net/browse/FOUR-7350
The processmaker_intended cookie needs to be set with the options sameSite=none and secure=true.
This is because the SSO login post originated from a 3rd party domain (In this case, the SAML IDP) and chrome doesn't allow that unless sameSite is none. 
It looks like in Laravel 7 they [changed some defaults](https://github.com/laravel/framework/commit/f81b6ed01fb60580ade8c7fb4386aff4cb4d7719#diff-8ac2d435acb71caedbdd807ad9fb43e4c22e62db958e41b7ba91029bfd76f192). 
I didn't see anything in the release notes about it.
See reproduction steps in the the issue. You need to set up SSO (I think any provider will have the same issue). You only need an authenticated web entry and you can …
=> Set processmaker_intended cookie to sameSite=none

resources/js/components/AdvancedSearch.vue
The loading icons are not finishing and some errors are displaying in the browser’s console
This is caused because some users are corrupted (missing lastname, missing email).
- Add a defensive code to prevent the exception in request list.
- Create a user without lastname (NULL)
- Go to the Requests list
With the error:
[error_list.webm](https://user-images.githubusercontent.com/8028650/216715141-9d8b1013-39fb-4617-9395-658de8126541.webm)
With the fix:
[fixed_list.webm](https://user-images.githubusercontent.com/8028650/216715167-45daf78d-b37f-48bd-9a0a-18e0840caa81.webm)
- https://processmaker.atlassian.net/browse/FOUR-7344
=> Fix dropdowns in request list

resources/views/about/index.blade.php
The About page is missing the indexed section
- put back the missing section.
original PR https://github.com/ProcessMaker/processmaker/pull/3372
- Review the About page and see the indexed section at the bottom.
[FOUR-7419](https://processmaker.atlassian.net/browse/FOUR-7419)
[FOUR-7419]: https://processmaker.atlassian.net/browse/FOUR-7419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add section indexed on page about

ProcessMaker/Http/Resources/Task.php
After completing the task, it was redirecting to a parent request that the user did not have access to.
https://user-images.githubusercontent.com/16992680/210136587-ce333c49-a2a9-4992-987f-e5c45d7b8328.mp4
Redirect to the request where the user has access
https://user-images.githubusercontent.com/16992680/210136594-6d3b6f31-8f43-425c-a05e-958dd3e48e8f.mp4
- Include uses permission data information when fetch task data
- Create a process with the next configuration
- Create a sub-process with the next configuration
- Create a user without permissions  to assign on the sub-process. Like the next image:
- Create a request with admin user
- Route to the sub-process, where the user without permission is assigned to the sup-process
- Log in with the user on …
=> Including user permissions data regarding the request - FOUR-7187

ProcessMaker/Http/Resources/Task.php, tests/Feature/Api/TasksTest.php
Ticket [FOUR-6704](https://processmaker.atlassian.net/browse/FOUR-6704)
In a subprocess after completing a task assigned to a user "By user ID" the message "Not Authorized" is displayed.
Current behavior: 
After completing the task with the assigned user, the message "Not Authorized" is displayed.
After the thread's task completes, the summary of the completed task should be displayed, as in previous versions.
- Updated processCompleted() with a processRequestParent() in the Task.view file.
- Import the process and sub-process using the files from the ticket.
- Create a new user.
- Create a new request `test_subprocess_bsa`
- https://www.loom.com/share/f9a3ef8c56284c968085a0762d04190b
- Link to screen-builder- …
=> FOUR-6704: Updated Task API with processRequestParent()

ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Policies/ProcessRequestTokenPolicy.php, resources/js/requests/components/RequestDetail.vue, resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php, routes/channels.php
- Create 2 users (We’ll call them user1, user2). They should have just the View All Requests permission.
- Create a process with 2 tasks (task1, task2)
- Assign user1 to task1 and task2 and the start event.
- Configure task1 with option “Allow reassignment“.
- Edit the process configuration and set user2 as Process Manager
- Login as user1 and start a request
- Now login as user2, go to All Requests and open the  created request
user 2 even being Process Manager, can’t open the task and see the “Reassign” Button
Authorization to update and view tasks were changed to allow Process Managers  to reassign and view tasks.
The Process Manager user must have additionally the following permissions:
- View All Requests (To access requests that are not his own)
- View Users (To see the user list …
=> FOUR-6660: Process Manager can't reassign requests

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Models/User.php, ProcessMaker/Observers/UserObserver.php, tests/Feature/Api/UsersTest.php
As a ProcessMaker admin, I want to be able to configure a default timezone for users created. So I can create users (via UI or integration) without having to go their profile and set the timezone.
1. Go to `/admin/users`.
2. Click "+ User" to add a new user.
3. The user created above will have the default timezone of "America/Los_Angeles".
- Added a new setting in `admin/settings` to select the default timezone (see package-auth PR).
- The timezone is set using a mutator when creating the user, taking into account the new setting.
- Execute `phpunit tests/Feature/Api/UsersTest.php --filter testDefaultValuesOfUser`.
- [FOUR-7264](https://processmaker.atlassian.net/browse/FOUR-7264)
- [Package Auth PR](https://github.com/ProcessMaker/package-auth/pull/72)
- [Package …
=> FOUR-7264 - Default timezone for new users

resources/js/processes/categories/components/CategoriesListing.vue, resources/js/processes/screens/components/modal/modal-screen-add.vue, resources/views/admin/groups/index.blade.php, resources/views/admin/users/edit.blade.php, resources/views/processes/edit.blade.php, resources/views/processes/environment-variables/edit.blade.php, resources/views/processes/export.blade.php, resources/views/processes/import.blade.php, resources/views/processes/screens/edit.blade.php, resources/views/processes/screens/export.blade.php, resources/views/processes/screens/import.blade.php, resources/views/processes/signals/index.blade.php, resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
French Alert-success banner when updating user settings has `&#039;` instead of single quote.
1. Install package-translations.
2. Go to Edit Profile `/profile/edit`.
3. Change the language to `fr`.
4. Go to Admin Users `/admin/users`.
5. Click on Edit a User.
6. Click "Enregistrer" button to save.
7. Verify the pop-up success message is displayed correctly. 
Currently, there's a problem when the string passed to the alert uses the echo {{}} syntax: `ProcessMaker.alert('{{__('User Updated Successfully ')}}', 'success');`.
The problem is solved using the $t function of VueI18Next: `ProcessMaker.alert(this.$t('User Updated Successfully '), 'success');`.
- Changes were made by replacing strings to $t function.
- Checked every ProcessMaker.alert() for missing translations.
Before changes: …
=> FOUR-470 - Translations: &#039; instead of single quote

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Observers/UserObserver.php, tests/Feature/Api/UsersTest.php
This PR takes into account the use case of creating users via API and assigning a timezone that exists in the request body.
- Perform an API POST call to: `/api/1.0/user` and add the `timezone` query param.
- If the timezone is defined in the body and it different to timezone default, the user should be create with the timezone set and it should not assigned the default timezone. 
- Removed the `setTimezoneAttribute` from the Observer to prevent it from overwriting the timezone.
- Execute `phpunit tests/Feature/Api/UsersTest.php --filter testDefaultValuesOfUser`.
- [FOUR-7264](https://processmaker.atlassian.net/browse/FOUR-7264)
- [Package Auth PR](https://github.com/ProcessMaker/package-auth/pull/73)
ci:package-auth:bugfix/FOUR-7264-a
ci:connector-docusign:v1.1.0 …
=> FOUR-7264 - Default timezone for new users - a

ProcessMaker/Http/Resources/Task.php, ProcessMaker/Models/ProcessRequestToken.php, resources/views/tasks/edit.blade.php
The file preview control shows the same file in all multi-instance tasks
The file controls should shows the same file in all multi-instance tasks
The file was being uploaded to the global scope instead to the task instance scope.
- Add the proper loop context to the file-upload component
Follow the steps of the ticket.
1. Create a process with Start Event -> Task 1 -> Task 2 -> End Event
2. Configure the task 2 with parallel multiinstance
3. Create a screen with file control and line input
4. Create a Request 
5. Route to the parallel task
6. For each parallel task put a different value in the line input
7. And upload a different file in each multi-instance task
8. Go go to files Manager
9. Go to Forms 
- …
=> FOUR-3375 The file preview control shows the same file in all multi-instance tasks

.eslintrc.js, .gitignore, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessVersion.php, ProcessMaker/Models/ScreenVersion.php, ProcessMaker/Models/ScriptExecutorVersion.php, ProcessMaker/Models/ScriptVersion.php, ProcessMaker/Traits/HasVersioning.php, database/migrations/2023_02_27_130520_add_draft_column_to_versions_tables.php, resources/js/processes/modeler/components/ModelerApp.vue, resources/views/processes/modeler/index.blade.php, routes/api.php, tests/Feature/Api/ProcessTest.php, tests/Feature/Api/UsersTest.php
This PR adds backend and frontend changes for Autosave in Modeler.
- Added a new `draft` column (boolean default false) to all *_vesions tables.
- Added new column in ScriptExecutorVersion and VocabularyVersion to be consistent, even though there is no autosave for those items.
- Each process, script, screen should only have one draft (see HasVersioning@saveDraft).
- Added a global scope to HasVersioning that sets the published scope to all queries by default.
- Also, see HasVersioning@getLatestVersion to make sure we're getting always the published version.
- Delete the draft after the item is published, see HasVersioning@saveVersion.
- About: Adding API controller endpoints to get and put the version, I've followed another approach.
- GET
- Load the draft (if exists) within the …
=> FOUR-7331 - Autosave Process

.eslintrc.js, .gitignore, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Http/Controllers/Process/ScriptController.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessVersion.php, ProcessMaker/Models/ScreenVersion.php, ProcessMaker/Models/ScriptExecutorVersion.php, ProcessMaker/Models/ScriptVersion.php, ProcessMaker/PackageHelper.php, ProcessMaker/Traits/HasVersioning.php, database/migrations/2023_02_27_130520_add_draft_column_to_versions_tables.php, resources/js/components/Menu.vue, resources/js/processes/modeler/components/ModelerApp.vue, resources/js/processes/scripts/components/ScriptEditor.vue, resources/views/processes/modeler/index.blade.php, resources/views/processes/scripts/builder.blade.php, routes/api.php, tests/Feature/Api/ProcessTest.php, tests/Feature/Api/ScriptsTest.php
This PR is based on [feature/FOUR-7331](https://github.com/ProcessMaker/processmaker/pull/4627) branch.
- Create draft version for scripts.
- Load draft version.
- Added close/discard functionality.
- Added config values for autosave delay.
- Display "Saved Notification" on draft update.
- `php artisan test tests/Feature/Api/ScriptsTest.php --filter testUpdateDraftScript`
- `php artisan test tests/Feature/Api/ScriptsTest.php --filter testCloseDraftScript`.
- Execute a manual test by linking Package Version in Core.
- [FOUR-7335](https://processmaker.atlassian.net/browse/FOUR-7335)
- [Package Versions PR](https://github.com/ProcessMaker/package-versions/pull/57) 
[FOUR-7335]: https://processmaker.atlassian.net/browse/FOUR-7335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> FOUR-7335 - Autosave Script 

resources/js/processes/export/components/MainAssetView.vue
- Log in 
- Click on Designer
- Select a process 
- Click on Export 
- Choose custom option
- Click on export 
It shows us a js error when exporting a process, with the custom option
errors should not appear when exporting a process, with the custom option
- Remove prop existingAssets, because there is a computed property with the same name
https://user-images.githubusercontent.com/90727999/226998249-a3fae13f-f12b-4ada-85f8-6898f74144e1.mov
Follow the steps above
- [FOUR-7693](https://processmaker.atlassian.net/browse/FOUR-7693)
[FOUR-7693]: https://processmaker.atlassian.net/browse/FOUR-7693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-7693: Error when exporting a process with the Custom option in branch develop

resources/js/modules/isPMQL.js
Improved isPMQL function to detect IN and NOT IN operators. 
To reproduce the issue try to search in settings using the following valid PMQL query:
`name IN ["IMAP Server"]` or `name NOT IN ["IMAP Server"]`
https://user-images.githubusercontent.com/90727999/224812595-c6cb787c-5446-408c-b71d-18731f69780c.mov
It is not detecting the search input as a valid PMQL query
Should detect the IN and NOT IN operators as a valid PMQL query
- Added IN and NOT IN operators to the regular expression in the isPMQL function.
https://user-images.githubusercontent.com/90727999/224812904-794f246c-b168-4e02-858d-f8867cbf038a.mov
- [FOUR-7636](https://processmaker.atlassian.net/browse/FOUR-7636)
[FOUR-7636]: …
=> Bugfix/FOUR-7636: Fix the regex that detects PMQL

resources/js/components/shared/Modal.vue
Please see the comments in https://processmaker.atlassian.net/browse/FOUR-7718
To maintain consistency across the platform the modal should look like the other places we use it. With import export some changes were introduced to fit the PRD. Buttons should show in the footer with the correct padding and primary button of the modal should use the primary color variant.
Steps to Reproduce: 
- Create or open a process
- Click on save
- The modal to save the version shows
There is a padding in the footer (please notice the border line in the footer). The save button have an incorrect color variant.
Footer should show without the extra body padding. The primary button should have the primary color variant.
- Use the shared component Modal instead …
=> Bugfix/FOUR-7718: The save process frame is distorted, compared to the previous version

ProcessMaker/ImportExport/Dependent.php, resources/js/processes/export/DataProvider.js
Steps to Reproduce: 
- Log in 
- Import a process that has a category assigned
- select the Custom option
As we can see, the categories option is not showing the category of the process 
This replicates when the user that exports the process is created or not in the second environment.
In the categories option, the category that has the rpco that is going to be imported must be shown
- Send with the dependents the name property from the backend.
https://user-images.githubusercontent.com/90727999/228326672-dd343f4c-45f0-4b0d-a21f-ba5a240a1748.mov
- Go to export a process with some categories. 
- Choose custom export
- In the summary page, check that the categories name are listed.
- Try the same with the import
- …
=> Bugfix/FOUR-7715: The category is not shown in the custom import template of a process,

resources/js/components/shared/AssetTreeModal.vue
Please read https://processmaker.atlassian.net/browse/FOUR-7699
- Fix the attribute for update at that was wrongly used updated_at instead updatedAt.
- Hide updated by if is null.
NOTE: In sync with @nolanpro Updated By is only available when the package versions is installed. 
- Go to export or import a process
- Click on linked assets link
- In the popup, check the updated at is showing and also the updated by when you have a different version of the asset.
**Screenshots**
- [FOUR-7699](https://processmaker.atlassian.net/browse/FOUR-7699)
[FOUR-7699]: https://processmaker.atlassian.net/browse/FOUR-7699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-7699: Linked assets observations (last modified undefined, non existing user N/A hyperlinked)

ProcessMaker/Models/Process.php, ProcessMaker/Repositories/TokenRepository.php
- Import the attached process "Hospital Triage"
- Create a data source "users" with 2 resources: one to get the list of PM users and other to get PM groups
- Configure the screen used by the process, using the 2 data sources created before in each select list (doctors and specialties)
-  Configure the task "Specialist Assignment", with assign type by "process variable". Set just the variable name for users or groups and letting the other one empty.
- The attached video shows all the steps for the configuration above.
https://user-images.githubusercontent.com/14875032/228949707-c5cc3e2f-c5bb-402b-bfec-a67068d8bf27.mp4
[Hospital_Triage.zip](https://github.com/ProcessMaker/processmaker/files/11115568/Hospital_Triage.zip)
The test  fail  because one of the fields, either Variable Name (Users) …
=> FOUR-7198: Dynamic Assignment Rules (Fixes)

ProcessMaker/Repositories/TokenRepository.php
1. create a simple process (start, task, end)
3. configure task type self-service and assign user or group
5. save process and run a new request.
- add validation when value assign (user or group) is empty
https://user-images.githubusercontent.com/1747025/229219287-795ee300-5829-4f9b-abe1-a674cb1e74c3.mp4
- [FOUR-7828](https://processmaker.atlassian.net/browse/FOUR-7828)
[FOUR-7828]: https://processmaker.atlassian.net/browse/FOUR-7828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cannot route a case to a self-service task

ProcessMaker/Http/Controllers/Process/ScriptController.php, resources/js/components/Menu.vue, resources/js/processes/scripts/components/ScriptEditor.vue, resources/views/processes/scripts/builder.blade.php
An error occurs when a script with Draft status is assigned in a watcher.
1. Create a new Script. Do not edit/update.
2. Create a new Screen.
3. Add a watcher using the script of above.
4. Preview and test watcher.
5. Get error 500.
- There's an issue when creating a new Script, it's `code` column is created with an empty array [].
- Now, when a new script is created, we trigger the save-script event to store the boilerplate template.
Please follow the reproduction steps of above.
- [FOUR-7766](https://processmaker.atlassian.net/browse/FOUR-7766)
[FOUR-7766]: https://processmaker.atlassian.net/browse/FOUR-7766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-7766 - Script with Draft status can be added in a Watcher. Then an error occurs

ProcessMaker/Http/Middleware/TemplateAuthorization.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Repositories/TokenRepository.php, routes/api.php, tests/Feature/Api/TaskAssignmentByVariableTest.php
Ticket: [FOUR-7729](https://processmaker.atlassian.net/browse/FOUR-7729)
Currently, a user with all template permissions but without Processes Import/Export permissions is unable to import a template. This issue can be reproduced by following these steps:
1. Create a new user with only the permissions for Processes: Create, Edit, and all Process Templates.
2. Ensure that a template has been created.
3. Log in as the new user.
4. Navigate to the Templates tab.
5. Attempt to import or export a template.
Users with Process Templates permissions should be able to import/export templates without encountering any issues.
When Processes Import/Export permissions are disabled and only Process Templates permissions are granted, users are unable to …
=> FOUR-7729: Fix Import/Export Process Template Permissions

resources/js/components/templates/SelectTemplateModal.vue, resources/js/processes/components/CreateProcessModal.vue
Ticket: [FOUR-7913](https://processmaker.atlassian.net/browse/FOUR-7913)
This PR addresses an issue where template data was not persisting after the second use. Specifically, when attempting to use a template for a second time, all of the data would appear empty.
Add an event listener to the select template modal that listens for a 'resetModal' event from the create process modal. Whenever this event is emitted, the modal data is reset, allowing users to reuse templates without losing any data.
1. Open the Create Process modal
2. Select a Template
3. Select the 'Use Template' button
4. Close the modal by either selecting the 'cancel' or 'close' button
5. Reopen the modal and select the same template
6. Verify that the template data is present
7. Repeat 2-6 with a different template
8. …
=> FOUR-7913: Fix issue with template data not persisting after second use

resources/js/components/shared/EllipsisMenu.vue
This PR is part of [Modeler toolbar improvements PR](https://github.com/ProcessMaker/modeler/pull/1489). 
Fix drop-down menu ellipsis content overlapping in Modeler.
- The drop-down’s content should be displayed above the Inspector column.
- The drop-down’s content is displayed under the Inspector column.
- Added emit events on <b-dropdown> MenuEllipsis component to be handled in Modeler.
- run `npm run build-bundle`
- copy dist folder to `node_modules/@processmaker/modeler/`
- run `npm run dev` in core.
- manually test Modeler.
- [FOUR-7920](https://processmaker.atlassian.net/browse/FOUR-7920)
- [FOUR-7973](https://processmaker.atlassian.net/browse/FOUR-7973)
[FOUR-7920]: https://processmaker.atlassian.net/browse/FOUR-7920?atlOrigin=eyJpIjoiNWRkNTljNz …
=> FOUR-7920 - Modeler Toolbar Improvements

database/seeders/PermissionSeeder.php, resources/js/components/NavbarProfile.vue, resources/views/layouts/navbar.blade.php, routes/web.php, tests/Feature/ProfileTest.php
As an Administrator, I want to limit users from editing their own profiles so I can reliably control user details in my platform.
- Added new permission: "Edit Personal Profile" (in Users tab) for users and groups. 
- When active it allows the user to edit their own profile.
- When inactive prevents user from access the `/profile/edit` route and make changes to their profile.
1. Run `php artisan db:seed --class="PermissionSeeder"`
2. Create a new user
3. Test the "Edit Personal Profile" permission.
- Run unit test: `php artisan test --filter ProfileTest`.
- [FOUR-7891](https://processmaker.atlassian.net/browse/FOUR-7891)
[FOUR-7879]: https://processmaker.atlassian.net/browse/FOUR-7879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-7891]: …
=> FOUR-7891 - Profile Edit Permission

ProcessMaker/Http/Controllers/Api/ImportController.php, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/TemplateController.php, resources/js/components/shared/DraggableFileUpload.vue, resources/js/processes/export/DataProvider.js, resources/js/processes/import/components/ImportManagerView.vue, routes/api.php
The importers allow importing a Template or Process without validation.
Steps to Reproduce : 
- Log in 
- Click on Template->Import
- Import a Process
- The process will import 
- Created validation for each importer
Click on Process->Import a and import a Template file (It should not allow the import)
Click on Template->Import and import a Process file (It should not allow the import)
- Ticket [FOUR-7861](https://processmaker.atlassian.net/browse/FOUR-7861)
[FOUR-7861]: https://processmaker.atlassian.net/browse/FOUR-7861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> It is possible to import a process in the templates tab

resources/js/admin/cssOverride/components/SiteDesign.vue, resources/sass/_colors.scss, resources/sass/_variables.scss
1. Run `npm run prod` or `npm run dev` on a clean install with no custom CSS colors, ensuring that it runs as expected
2. Visit `/admin/customize-ui`
3. Change some of the default colors and click save, allowing the CSS to regenerate
4. Run `npm run prod` or `npm run dev` again
The build fails with the following error:
```
SassError: Undefined variable.
╷
6 │   color: $darkneutral;
│          ^^^^^^^^^^^^
```
The build should complete without error.
- Removed the color variables that were added to support the new Import/Export functionality from the _colors.scss file and moved them to the _variables.scss file. Since the Customize UI functionality was replacing the _colors.scss file without those new colors in it, the build would fail. Now, those color variables exist regardless of the …
=> [FOUR-8126] Recompiling Mix fails on instance when colors have been customized

resources/js/app-layout.js, resources/views/layouts/navbar.blade.php
The recent-searches request is triggering twice when navigating over  the pages. The problem was related to global search component that is used twice in navbar, one version for desktop and another for mobile and both of them was rendering.
- Calculate screensize and depending of the screensize, render the corresponding global search bar 
https://user-images.githubusercontent.com/90727999/233440929-ccffcbc3-783e-49ee-ae01-1847aec81468.mov
Open the browser inspector and navigate over the app. Should be only one recent-searches request
=> Bugfix: recent-search request triggering twice

database/migrations/2023_04_26_164247_add_is_template_column_to_specific_version_tables.php
When upgrading from RC's error: unknown column` is_template` for script_versions, screen_versions is thrown.
The seems to be triggered by existing data in the database having the 'is_template' column but not the assets corresponding versions table. This PR adds a migration to create a 'is_template' column for the asset versions tables.
- Add migration to create 'is_template' column for the asset versions table
1. Change your env to RC3, run migrations
2. Install connector-pdf and package-actions-by-email
3. Create scripts and screens
4. Change your env to RC4 run migrations
5. ReInstall connector-pdf and package-actions-by-email
=> FOUR-8303-Fix issues with RC upgrades is_template column

ProcessMaker/Jobs/ImportProcess.php
Main screen category was not assigned on import so it was not visible in the list of categories
- Set category IDs using the screen attribute `screen_category_id`
Import the the screen in the ticket and make sure its visible in the list of screens
- https://processmaker.atlassian.net/browse/FOUR-8135
=> Fix category assignment on screen import

resources/js/admin/settings/components/SettingObject.vue
There were changes in the style sheets, so it was misaligned on this page.
The Add button in LDAP Attributes looks distorted
- adjust settings add button
- Log in 
- Click on Admin
- Click on Settings 
- Click on LDAP 
- Clikc on  Edit  variable Map
https://user-images.githubusercontent.com/1747025/234614635-ab52d4eb-8538-4911-945b-2a45fbb3e817.mp4
- [FOUR-8174](https://processmaker.atlassian.net/browse/FOUR-8174)
[FOUR-8174]: https://processmaker.atlassian.net/browse/FOUR-8174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The Add button in LDAP Attributes looks distorted

resources/js/processes/modeler/initialLoad.js
- Enter the modeler
- Create a task of type Sub-process
- Expand the "Assignment Rules" option
- In the "Start Sub Processes" option, select "By User ID"
- change option "By user ID" to "Process Variable"
- Enter the modeler
- Create a task of type Sub-process
- Expand the "Assignment Rules" option
- In the "Start Sub Processes" option, select "Process Variable"
https://user-images.githubusercontent.com/1747025/234709946-bc4265d4-9c80-4859-8880-a4ac278d9ee8.mp4
- [FOUR-8130](https://processmaker.atlassian.net/browse/FOUR-8130)
[FOUR-8130]: https://processmaker.atlassian.net/browse/FOUR-8130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The "By user ID" assignment rule in sub-processes does not display the "Variable Name" field.

ProcessMaker/Http/Controllers/Api/FileController.php
the problem is when on table media library in filed custom_property the property parent is not defined.
you can reproduce it by uploading a file by API on the POST/files endpoint or removing the parent property in the database in some record
- add de parameter in endpoint post files.
- Upload file by API Post /files
- review request and file-manager in tab Admin (display files)
https://user-images.githubusercontent.com/1747025/234927156-34ce4814-3fb2-4413-8daa-b4a9176178e1.mp4
- [FOUR-8165](https://processmaker.atlassian.net/browse/FOUR-8165)
depends on PR https://github.com/ProcessMaker/package-files/pull/95
[FOUR-8165]: https://processmaker.atlassian.net/browse/FOUR-8165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 500 Error in Public files

ProcessMaker/Exception/ExportModelNotFoundException.php, ProcessMaker/Http/Controllers/Api/ExportController.php, ProcessMaker/Templates/ProcessTemplate.php, resources/js/components/templates/CreateTemplateModal.vue, resources/js/processes/export/DataProvider.js, resources/js/processes/export/state.js
Resolves Tickets [FOUR-8143](https://processmaker.atlassian.net/browse/FOUR-8143), [FOUR-8314](https://processmaker.atlassian.net/browse/FOUR-8314) and [FOUR-8159](https://processmaker.atlassian.net/browse/FOUR-8159)
When creating a process from an uploaded BPMN and that BPMN file references assets that do not exist in the current instance, when exporting that process or saving it as a template an 'Server Error' appears. We need to improve this error message to the user is aware of what is preventing the process from being exported or saved as a template.
**To reproduce:**
1. Create a new process and upload this BPMN file 
[bpmnProcess (4).xml.txt](https://github.com/ProcessMaker/processmaker/files/11355942/bpmnProcess.4.xml.txt)
2. Navigate back to the Process Listing page and try to …
=> Improve error message for process exporting and saving as a template

ProcessMaker/Http/Controllers/Api/ProcessController.php, resources/js/processes/modeler/components/inspector/ConfigEditor.vue, resources/sass/app.scss
This PR is part of improvements for Autosave (Processes).
- Save notification settings -> https://processmaker.atlassian.net/browse/FOUR-8155
- Settings were not being auto-saved, added the missing code.
- Save Script configuration when editing in the Modal -> https://processmaker.atlassian.net/browse/FOUR-8157
- When a Script is modified from the modal, the focusout event is not fired to save the State and trigger the autosave. Added a listener for the hide event of the modal, so the autosave can be triggered. 
- Removed a CSS rule `.autosave-btn` and added in Modeler package.
Link Modeler and Core. Run manual tests.
- [Modeler PR](https://github.com/ProcessMaker/modeler/pull/1521)
- [Vue form elements PR](https://github.com/ProcessMaker/vue-form-elements/pull/392) …
=> Bugfix FOUR-7330-a 

ProcessMaker/Models/Template.php
Ticket: [FOUR-8145](https://processmaker.atlassian.net/browse/FOUR-8145)
When saving a Template, the time zone of the user and user's machine are not accurately reflected in the Created time in the Templates listing.
Add `SerializeToIso8601` trait to Template Model, similarly to how it is used in the Process Model.
1. Change the time zone of your machine
2. Change the user's time zone in ProcessMaker
3. Login the User
4. Create a Template
5. Find the Template in the Templates listing
6. See the Created date does not match the user's local time
1. Go to branch `bugfix/FOUR-8145` in Core.
2. Repeat the steps listed above.
- The Created time for a Template should match the user's local time.
- [FOUR-7375](https://processmaker.atlassian.net/browse/FOUR-7375) | Process Templates - Spring 2023 …
=> FOUR-8145 | Template is Not Created With the Correct Time Zone

resources/views/components/categorized_resource.blade.php
- Go to Designer > Data Connector
- review all lists of categories as well.
- 
- Sort tabs for categories and process templates.
review all lists with categories
https://user-images.githubusercontent.com/1747025/234678469-cee2b757-f4d4-4383-a122-e98876197e45.mp4
- [FOUR-8187](https://processmaker.atlassian.net/browse/FOUR-8187)
[FOUR-8187]: https://processmaker.atlassian.net/browse/FOUR-8187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Category tab is not displayed in Designer > Data connectors

resources/js/components/templates/CreateTemplateModal.vue, resources/js/processes/modeler/components/ModelerApp.vue
Ticket: [FOUR-8318](https://processmaker.atlassian.net/browse/FOUR-8318)
We need to add a ‘Save as Template’ button to Modeler so that users can save a Process as a Template from the Process Modeler.
1. Go to branch `feature/FOUR-8318` in Modeler.
2. Go to branch `feature/FOUR-8318` in Core. Link Modeler to Core.
3. In the UI, open up the Process Modeler. From the Ellipsis Menu, select 'Save as Template'.
- The template should save successfully and show up in your Templates listing.
4. In the UI, open up the Template editor. In the Ellipsis Menu, there should be no option to 'Save as Template'.
- [FOUR-7955](https://processmaker.atlassian.net/browse/FOUR-7955) | Implement the New Ellipsis Menu for Specified Menus Across the Platform
- …
=> FOUR-8318 | Add ‘Save as Template’ Button to Modeler

resources/js/components/shared/EllipsisMenu.vue
NOTE: THis tickes was reporte for Decision Tables but it affects any element that has categories (screens, scripts, etc.) Just repeat the same steps but using screen, script categories.
-     Create a new user
-     Go to Admin tab
-     Click on User option in sidebar menu
-     Search the user created above
-     Click on Edit button
-     Go to permission tab
-     Click on Decision Tables option
-     Enable The following Permissions: Create Decision Table, Edit Decision Table, View Decision Table Categories, View Decision Table
-     Login with the user created in step 1
-  The categories listing does not show the button to edit a category.
- I added a check to validate if the permissions variables is an array before using the .includes function.
Repeat the reproduction steps and …
=> FOUR-8308:  Enabling the "Edit Decision Table Categories" permission for a no admin user doesn't work

ProcessMaker/Console/Commands/PopulateAvatarColumn.php, ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Models/User.php, database/migrations/2023_05_03_131855_add_avatar_to_users_table.php, upgrades/2023_05_03_131855_add_avatar_to_users_table.php
208 duplicate queries; not huge savings but unnecessary DB load If don't need avatar on every API query, don't append it
User:129
- Convert `avatar` into a real column with URL of the avatar to avoid the query that constantly gets the avatar for each user every time an User is loaded.
- This URL is updated when the User profile is updated
- Download the branch with the change.
- Run the migrations
- Run the artisan command `php artisan users:populate-avatar`
- Test the Process Maker User Avatars, changing avatars, see the proper avatar is displayed in each place:
- List of Processes
- List of requests
- Filters
- Open Request
- Open Task
- Participants in Saved Searches
- Run the migrations to add the avatar column
- Run the artisan command `php artisan users:populate-avatar` to populate …
=> FOUR-8342 Duplicate media queries

database/migrations/2023_05_02_183152_add_order_column_index_to_media_table.php, tests/unit/ProcessMaker/MediaOrderColumnIndexTest.php
[Performance] Add index to order_column in media table.
- Add index to order_column in media table.
- Run the migration to update the schema
- Check into the database the new index was created
- https://processmaker.atlassian.net/browse/FOUR-8349
=> FOUR-8349 Add index to order_column in media table

database/migrations/2023_05_02_184218_add_indexes_to_process_request_tokens.php
Task PMQL searches and charts are slow.
This adds 3 indexes recommended by Tighten
- status
- element_type
- composite status and is_self_service
- Performance will only be noticeable where there are lots of process requests and tasks
- Compare the XHR response time for http://processmaker-a.test/api/1.0/tasks when searching with PMQL `status = "active" AND is_self_service = 1` on the tasks page
- https://processmaker.atlassian.net/browse/FOUR-8347
=> Add indexes to process_request_tokens

resources/js/tasks/components/TasksList.vue
Ticket: [FOUR-8362](https://processmaker.atlassian.net/browse/FOUR-8362)
When loading the Task Listing page the Sorry, API Failed message flashes. This is due to an axios `ERR_CANCEL` being emitted. The Task List page was catching this error and displaying the Sorry API failed message even though the data was loaded successfully. The solution is to remove this catch and reference from the task listing.
**To Replicate:**
1. Load the task listing page
Load the task listing page
[FOUR-8362]: https://processmaker.atlassian.net/browse/FOUR-8362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix 'API Failed' flash on Task List load

ProcessMaker/Http/Controllers/Api/ExportController.php, ProcessMaker/ImportExport/Exporters/ExporterBase.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/ImportExport/Exporters/ScreenExporter.php
Ticket: [FOUR-8315](https://processmaker.atlassian.net/browse/FOUR-8315)
When exporting processes, missing models previously caused the export to fail, preventing users from continuing. This PR addresses this issue by implementing a try-catch block to catch the missing model exception, log the error, and continue the loop. This allows users to continue with the export even if some models are missing, improving the reliability and usability of the feature.
**To Replicate:**
1. Create a process using a data connector.
2. Download the process BPMN file in the modeler.
3. Delete the data connector used in the process.
4. Create a new process and upload the BPMN file.
5. Click on the data connector and verify that the 'not found' error is displayed.
6. Save the created process.
7. Navigate to …
=> Allow exporting when models are missing

resources/js/components/shared/GlobalSearch.vue
- Steps to Reproduce: 
- Log in 
- have processes whose name contains numbers
- in the application header search engine look for the process
- click on the number found
**Expected Behavior:** 
we see that the name of the process with numerop, has been changed to ascii code 
when we search with consonants we do not have this problem   
- Encode PMQL in URL
https://user-images.githubusercontent.com/90727999/235235188-17d849b8-986f-4cfa-a1e4-0c2bc7802491.mov
Test steps above
- [FOUR-8333](https://processmaker.atlassian.net/browse/FOUR-8333)
[FOUR-8333]: https://processmaker.atlassian.net/browse/FOUR-8333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-8333: The search by numeral digits, is changed to code on the screen

ProcessMaker/Http/Controllers/Api/TaskController.php, database/factories/ProcessMaker/Models/ProcessRequestTokenFactory.php, resources/js/tasks/components/TasksList.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php, tests/Feature/Api/TasksTest.php
The number of overdue tasks in the red alert is not consistent with the filtered data from the table.
1. Create some tokens.
2. Create an overdue token.
3. Create an overdue self-service token.
4. Filter using PMQL: `due < NOW`.
5. You will notice that the number of tasks in the red alert is not the same as the data filtered by the table.
- The number of overdue tasks is now obtained from table's filtered data to ensure consistency.
https://user-images.githubusercontent.com/90741874/235792339-f31d542e-0698-4adb-b7af-65584f099602.mov
- Please run `php artisan test tests/Feature/Api/TasksTest.php --filter testGetListOfOverdueTasks` and perform some manual testing.
- [FOUR-8391](https://processmaker.atlassian.net/browse/FOUR-8391)
[FOUR-8391]: …
=> FOUR-8391 - Get right number of overdue tasks

resources/js/processes/modeler/components/inspector/ConfigEditor.vue
The Script Editor should trigger the event to save when it loses focus and not when the Modal is closed.
1. Add a script task:
2. Open the script editor in a Modal.
3. Add some text.
4. Click anywhere on the screen outside the Script Editor to trigger the focusout event.
5. Currently, the focusout event does not trigger in the Editor within a modal.
- Added the focusout.native to trigger the autosave event in the Script Editor within a modal.
- Removed the previous behavior, when the Modal was closed.
https://user-images.githubusercontent.com/90741874/236058217-29be4a73-0864-4163-8a62-9f75e1ad9b6d.mov
- Follow the steps of above.
- [FOUR-8430](https://processmaker.atlassian.net/browse/FOUR-8430)
[FOUR-8430]: https://processmaker.atlassian.net/browse/FOUR-8430?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> FOUR-8430 - Trigger save event on Script Editor focusout

ProcessMaker/ImportExport/Exporters/ProcessExporter.php
See steps in Jira ticket.
A process that was imported may not have a user associated with it. Check if the user exists first before exporting.
- Import Process_ SImple only Task 4.5.0.json from the Jira ticket
- Try to export it
- https://processmaker.atlassian.net/browse/FOUR-8429
=> Check if user exists before adding dependent

.github/workflows/scripts/translate.py, .github/workflows/translate_strings.yml, resources/lang/en.json
As an engineering manager I need translation strings to be automatically translated when they are updated in en.json.
Use GitHub Actions to detect changes in en.json and send any missing strings in other language files to OpenAI's GPT-4 for automated translation. Then open a PR with these updated language files.
=> Translate strings automatically using GPT-4

resources/js/leave-warning.js, resources/js/modules/autosave/autosaveMixin.js, resources/js/modules/autosave/closeMixin.js, resources/js/modules/autosave/mixins.js, resources/js/processes/modeler/components/ModelerApp.vue, resources/js/processes/screen-builder/screen.vue, resources/js/processes/scripts/components/ScriptEditor.vue, resources/views/processes/scripts/builder.blade.php
When there are changes and the Close button is clicked displays a popup alert that prevents it from closing. 
1. Drag any element into modeler, screen designer, scripts builder or make any change.
2. Click close before the 5 seconds autosave delay.
**Expected behavior**:
When the Close button is clicked, it should auto-save and then redirect without showing the alert popup.
- When the Close button is clicked, the leave warning is disabled, autosave is executed, and then redirect is performed.
NOTES for other future scenarios:
- It may be challenging to implement the same behavior when clicking on an href link such as "Designer, Admin, Request, etc." because the browser immediately aborts the axios call (or maybe I just followed a bad approach :).  
- Immediate Autosaving was not attempted …
=> FOUR-8446 - Trigger autosave when clicking Close

resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
See Jira ticket
- The URL matchers for the shared data loading component were incorrect. This fixes them.
Follow steps in Jira ticket.
- https://processmaker.atlassian.net/browse/FOUR-8444
ci:deploy
..
=> Fix url matchers for loading screen

resources/js/processes/import/components/ImportManagerView.vue, resources/lang/en.json
This are additional translation for templates
added the following translations to the system.
```
The selected file is invalid or not supported for the Process importer. Please verify that this file is a Process.
The file you are importing was made with an older version of ProcessMaker. Advanced import is not available. All assets will be copied.
Select Import Type
Import all assets from the uploaded package.
Custom
Select which assets from the uploaded package should be imported to this environment.
You are about to import
Process was successfully imported
Select Import Type
You are about to import
The selected file is invalid or not supported for the Templates importer. Please verify that this file is a Template.
The selected file is invalid or not supported for the Process importer. …
```
=> Additional translations for Templates

.github/workflows/scripts/translate.py, .github/workflows/translate_strings.yml
- Allow workflow to be used in other organization repos
- Add 15 second timeout with 3 retries
=> Automated Translations Updates

resources/lang/en.json
ticket [FOUR-8120](https://processmaker.atlassian.net/browse/FOUR-8120)
We don't have translations for IDP.
- Added translations to the settings tab for IDP
- Added translations to the configuration settings within the Task
- Install the IDP connector.
- Change the language
- Go to Admin->Setting->IDP
- Translation should be added to the options
[FOUR-8120]: https://processmaker.atlassian.net/browse/FOUR-8120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added IDP translations

ProcessMaker/Models/User.php
1. Log in
2. click on requets tab
When entering the request tab, it shows us errors in the console
There should be no error in the console
- Ensure the avatar property in the API response is an empty string rather than `null`
https://processmaker.atlassian.net/browse/FOUR-8494
=> [FOUR-8494] Console error

ProcessMaker/Contracts/SecurityLogEventInterface.php, ProcessMaker/Events/SettingsUpdated.php, ProcessMaker/Listeners/SecurityLogger.php, ProcessMaker/Models/SecurityLog.php, ProcessMaker/Traits/FormatSecurityLogChanges.php, database/migrations/2023_05_22_161025_add_changes_column_to_security_logs_table.php
All changes must be stored but only some fields must be displayed in the front end.
- Create a column for unique storage of all changes for internal use.
- [FOUR-8669](https://processmaker.atlassian.net/browse/FOUR-8669)
[FOUR-8669]: https://processmaker.atlassian.net/browse/FOUR-8669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Store all changes for internal use

ProcessMaker/Events/UnauthorizedAccessAttempt.php, ProcessMaker/Exception/Handler.php, ProcessMaker/Providers/EventServiceProvider.php, tests/Feature/Api/SecurityLogsTest.php
- Create a user with only requests permissions
- Open the Admin Settings page `/admin/settings`
- [FOUR-8229](https://processmaker.atlassian.net/browse/FOUR-8229)
ci:deploy
[FOUR-8229]: https://processmaker.atlassian.net/browse/FOUR-8229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-8229 Log Unauthorized access attempts

ProcessMaker/Console/PackageInstallCommand.php, composer.json, composer.lock, package-lock.json, package.json, phpunit.xml, tests/Feature/Console/PackageInstallCommandTest.php, tests/Feature/Console/TestPackage/TestPackageInstallCommand.php, tests/Feature/Console/TestPackage/TestPackageServiceProvider.php, tests/Feature/Templates/Api/ProcessTemplateTest.php
To perform the Template Automation test, we need to ensure that all [process-templates](https://github.com/ProcessMaker/process-templates) are correctly imported into PM4. Additionally, we must confirm that these templates work properly when creating a Process.
- Created a unit test that will fetch and count all the processes within [process-templates](https://github.com/ProcessMaker/process-templates) and compare them with the ones on the Default Templates database.
- This test will also check all templates to make sure they can be added as Processes.
To successfully configure the automated default template synchronization, follow these steps:
- Open your `.env` file for your project.
- Add the following new variables and their respective values:
- The DEFAULT_TEMPLATE_BRANCH will be the …
=> FOUR-8392 Template Automation test

ProcessMaker/Events/SecurityLogDownloadJobCompleted.php, ProcessMaker/Http/Controllers/Api/SecurityLogController.php, ProcessMaker/Jobs/DownloadSecurityLog.php, routes/api.php, routes/web.php
This is a mock response from the asynchronous download.
The goal is to speed up frontend development.
1. Run `php artisan horizon` and `npx laravel-echo-server start`
2. Access the link: `/admin/security-logs/download/all?format=text`
3. In 5 seconds the frontend should receive a message in the websocket
```
0:"SecurityLogDownloadJobCompleted"
1:"private-ProcessMaker.Models.User.1"
2:{success: true|false, link:"...", message: "..."}
```
- [FOUR-8720](https://processmaker.atlassian.net/browse/FOUR-8720)
[FOUR-8720]: https://processmaker.atlassian.net/browse/FOUR-8720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SecurityLog - Mocking a response for asynchronous download - FOUR-8720

ProcessMaker/Http/Controllers/Api/SecurityLogController.php, ProcessMaker/Jobs/DownloadSecurityLog.php
This is a mock response from the asynchronous download.
The goal is to speed up frontend development.
1. Run `php artisan horizon` and `npx laravel-echo-server start`
2. Access the link: `/admin/security-logs/download/all?format=text`
3. In 5 seconds the frontend should receive a message in the websocket
```
0:"SecurityLogDownloadJobCompleted"
1:"private-ProcessMaker.Models.User.1"
2:{success: true|false, link:"...", message: "..."}
```
- [FOUR-8720](https://processmaker.atlassian.net/browse/FOUR-8720)
[FOUR-8720]: https://processmaker.atlassian.net/browse/FOUR-8720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Changing the download format validation

ProcessMaker/Http/Controllers/Api/ImportController.php, resources/js/app-layout.js, resources/js/components/Message.vue, resources/js/processes/import/components/ImportManagerView.vue, resources/views/layouts/navbar.blade.php
- Go to Admin / settings
- Configure 2 custom email servers (Email server 1 and Email server 2)
- Create a process and add a connector send email
- Configure the connector server to point to the first server (not the default server)
- Export the process
- Go to Admin / settings again
- Delete the Email server 1
- Try to import the exported process
An error is displayed: Email server does not exists, index 1 and the importing process is stopped
The importing process should continue. If the email sever configured in the connector send email does not exists in the new instance, assign the default server for the connector and show a message to the user.
- Do not throw an exception when the email server not found while …
=> Show message and assign default server for missing reference

ProcessMaker/Models/ProcessRequest.php, tests/Feature/Api/ProcessRequestsTest.php
See google doc linked in https://processmaker.atlassian.net/browse/PM4EH-400
We are passing a list of IDs to a `whereIn`. This causes performance issues when there are lots of IDs.
- Change it to a subquery
- It's not possible to see the performance improvements without a large data set so make sure searching with PMQL participant continues to work as expected.
- Create a process with a task, assign the task to a user
- On the requests page, verify using the PMQL `participant = "username"` returns the request
- https://processmaker.atlassian.net/browse/FOUR-7978
=> Use subquery instead of passing in list of IDs

ProcessMaker/Http/Controllers/Api/TaskController.php, tests/Feature/Api/TasksTest.php
See google doc linked in https://processmaker.atlassian.net/browse/PM4EH-400
We are not using the index when querying by process id since it was using `like`. This was making API task searches very slow.
If the searched value is number, use `=` operator instead of like
- It's not possible to see the performance improvements without a large data set so make sure searching by process id and element name still work as they did before the change.
- Run a process with a task
- Call the API endpoint to find the task by process ID, for example:
- `GET http://processmaker.test/api/1.0/tasks?process_id=13`
- Call the API endpoint to find the task by element name (node name), for example:
- `GET http://processmaker.test/api/1.0/tasks?element_name=foo%`
- …
=> Use mysql equals operator when matching numbers

ProcessMaker/Http/Controllers/Api/UserController.php, resources/js/processes/modeler/components/ModelerApp.vue, routes/api.php
The user will be able to click an icon on an element slat, which would then hold that slat at the top of the element list. The user can click that icon again to allow the slat to return to its normally defined position in the element list. The user will also be able to use a search bar to search for any modeler elements in the list. The bottom elements menu will reflect the pinned elements, and all pins will be preserved on a by-user basis, with each user seeing their personalized menu of pinned elements.
- 2 new endpoints were created on api.php to serve data to Modeler.
Endpoints should be able to return data.
- https://processmaker.atlassian.net/browse/FOUR-8403
- https://github.com/ProcessMaker/modeler/pull/1566
=> FOUR-8403: Added endpoints to save user pinned BPMN elements on Modeler

resources/js/requests/components/screenDetail.vue
Ticket: [FOUR-8608](https://processmaker.atlassian.net/browse/FOUR-8608)
In the Forms tab of the Request details, the Photo/Video control is live. The camera is on and you are able to record a video or take a picture.
Remove the Photo/Video control when in the Forms tab, similarly to how the File Upload control is removed.
1. Log in to ProcessMaker.
2. Create a new Screen with a Photo/Video control. Configure the Control.
3. Add the Screen to a Process and start a new Request of the Process.
4. Complete the Process, open the Request, and go to the Forms tab.
1. Go to branch `observation/FOUR-8608` in core.
2. Install `package-photo-video`.
3. Follow the Steps to Reproduce.
4. The Photo/Video control should not show in the Forms tab of the Request details.
- …
=> FOUR-8608 | Photo/Video Control Is Shown Running in the Form Tab

resources/sass/app.scss
Missing an closing '}' at the end of the app.scss file. This is causing compile errors when running `npm run watch`
```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "}".
╷
965 │ }
│  ^
╵
resources/sass/app.scss 965:2  root stylesheet
```
- Add missing closing curly brace '}'
Run `npm run watch` in your local env.
=> Add missing closing curly brace "}"

ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/Repositories/EntityRepository.php, ProcessMaker/Nayra/Repositories/ProcessRequestRepository.php, ProcessMaker/Nayra/Repositories/ProcessRequestTokenRepository.php
The WorkflowManage::completeTask function currently performs various actions within the method itself. This ticket aims to refactor the function to use the Nayra BPMN engine for executing the task. The function should be modified to invoke the appropriate Nayra Engine services and events to complete the task.
Use the message broker drive "rabbitmq", bring up consumer: php artisan processmaker:consumer, create a request and complete the same.
https://processmaker.atlassian.net/browse/FOUR-8177
=> FOUR-8552 Refactor completeTask function to use Nayra BPMN engine (RabbitMQ)

ProcessMaker/Events/SettingsUpdated.php, ProcessMaker/Http/Controllers/Api/SettingController.php
Log Enabling or disabling to User Signals
Needs to make the following actions:
- Enabling User Signals
- Disabling User Signals
- [FOUR-8240](https://processmaker.atlassian.net/browse/FOUR-8240)
ci:deploy
[FOUR-8240]: https://processmaker.atlassian.net/browse/FOUR-8240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-8240: Log Enabling or disabling to User Signals and LDAP

ProcessMaker/Nayra/Managers/WorkflowManagerKafka.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/MessageBrokers/ServiceKafka.php, config/kafka.php
Implement a Kafka Drive for PM4 Core
- Bring up consumer: `php artisan processmaker:consumer`
- https://processmaker.atlassian.net/browse/FOUR-8563
=> FOUR-8563 Implement Kafka driver

ProcessMaker/Events/SettingsUpdated.php, ProcessMaker/Helpers/SensitiveDataHelper.php
Log Enabling or changing configuration options to other systems Settings - IDP
- [FOUR-8779](https://processmaker.atlassian.net/browse/FOUR-8779)
ci:deploy
[FOUR-8779]: https://processmaker.atlassian.net/browse/FOUR-8779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-8779:Log Enabling or changing configuration options IDP

ProcessMaker/Events/FilesCreated.php, ProcessMaker/Events/FilesDeleted.php, ProcessMaker/Events/FilesUpdated.php, ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, ProcessMaker/Providers/EventServiceProvider.php
Related to the Log Access to any files -> File manager
Needs to make the following actions:
- Create Files / Folder
- Update Files / Folder
- [FOUR-8235](https://processmaker.atlassian.net/browse/FOUR-8235)
ci:deploy
ci:package-files:feature/FOUR-8235
[FOUR-8235]: https://processmaker.atlassian.net/browse/FOUR-8235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-8235: Create and Update to any files

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Traits/ExtendedPMQL.php, tests/TestCase.php
The saved searches are using json columns to do the filtering over all the process_request table.
- Implement a Data Store Table with the required columns of Saved Search to generate a faster query, avoinding to use json columns for filtering and to traverse all the process_requests table.
- Import the attached process
- Run about 1000 of requests
- Setup a Saved Search with a filter by the specific process request and some varaibles of the process.
e.g.
```
(request = "Simple Process") AND (status = "In Progress") AND (data.customer_id = 100) AND (data.account.balance > 10000) AND (data.account.balance < 100000) AND (data.transaction.date > NOW -1 day)
```
- Test the saved search.
- Check the response time of `/api/1.0/saved-searches/56354/results` is much faster
- Check the sql of the …
=> FOUR-8600 Data Store Table for Saved Search

routes/api.php
Duplicated name for route `security-logs.index`
- Fix the duplicated route name.
- Apply the cache of the routes:
```
APP_RUNNING_IN_CONSOLE=false php artisan route:cache
```
=> Fix route name

ProcessMaker/Jobs/ExecuteTranslationRequest.php, ProcessMaker/ProcessTranslations/BatchesJobHandler.php
- Create a simple process
- Create a simple screen with two inputs
- Set one of the labels with an apostrophe
- assign the screen on the process
- Go to Configure of the process and create a translation
- Open the translations once finish
The label with the apostrophe is not translated
The translation should be considered
- Fix encoding
https://github.com/ProcessMaker/processmaker/assets/90727999/9a4feb60-f261-41f6-9393-e39732f8714a
- [FOUR-8963](https://processmaker.atlassian.net/browse/FOUR-8963)
[FOUR-8963]: https://processmaker.atlassian.net/browse/FOUR-8963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-8963: Translation does not reconice apostrophes

ProcessMaker/Http/Controllers/Api/ProcessTranslationController.php, resources/js/processes/translations/components/CreateProcessTranslationModal.vue
Login as Admin
Create a process with may fields and labels
Open the Configure > Translations of the process
Create many translations at the same time
A timeout error is displayed and the modal is not closed, it continues loading
The modal should be closed after a failure
- Close modal when endpoint return an exception.
- Fixed button not disabled after translate last 
**Working videos**
https://github.com/ProcessMaker/processmaker/assets/90727999/4fa886c6-ae2a-4154-9ba7-5457a0c377a7
Other fixes
https://github.com/ProcessMaker/processmaker/assets/90727999/ef41b664-30ac-4d79-8493-167d39a0b4b6
Follow steps above.
- [FOUR-8979](https://processmaker.atlassian.net/browse/FOUR-8979)
[FOUR-8979]: …
=> Bugfix/FOUR-8979: Modal remains open when timeout

ProcessMaker/Notifications/ProcessTranslationReady.php, ProcessMaker/ProcessTranslations/BatchesJobHandler.php
- Login as banker
- Create a simple process
- Open the Configure > Translations of the process
- Create a translation
After the translation is completed a notification is displayed twice and with no additional information
The notification should be only one and provide more information about the translation
- Broadcast response only once when translation completed.
https://github.com/ProcessMaker/processmaker/assets/90727999/43611c0f-3223-43ae-b6fd-908053c3d96a
- [FOUR-8976](https://processmaker.atlassian.net/browse/FOUR-8976)
[FOUR-8976]: https://processmaker.atlassian.net/browse/FOUR-8976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> Bugfix/FOUR-8976: Notifications with no valuable information and twice

ProcessMaker/Http/Controllers/Api/ProcessTranslationController.php
**Story:**
As an administrator, I want to have the list of translations created for a process in alphabetic order or sorted by creation. So I can have more order on the list and a better access to the translations
**Details:**
The list of translations should be sorted
There should be an option to change the type of sort
- Sort translations alphabetically.
**Working screenshot**
Create some translations and check if they are correctly ordered. First it will show pending translations ordered and below that the already translated languages
- [FOUR-8981](https://processmaker.atlassian.net/browse/FOUR-8981)
[FOUR-8981]: https://processmaker.atlassian.net/browse/FOUR-8981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-8981: List of translations should be sorted

ProcessMaker/Assets/ScreensInScreen.php, ProcessMaker/ProcessTranslations/ProcessTranslation.php
- Import the attached process and be sure you don’t have a screen with id 25 in your instance
- Go to process > configure
[Steps_test.json.zip](https://github.com/ProcessMaker/processmaker/files/11839333/Steps_test.json.zip)
- Replace **findOrFail** with **find**. Verify screen exists. Added a check also for the key **content** in select lists
- [FOUR-9016](https://processmaker.atlassian.net/browse/FOUR-9016)
[FOUR-9016]: https://processmaker.atlassian.net/browse/FOUR-9016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-9016:

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Traits/ProcessMapTrait.php, resources/js/processes/modeler/components/ProcessMap.vue, resources/js/processes/modeler/components/ProcessMapTooltip.vue, resources/views/processes/modeler/inflight.blade.php, resources/views/processes/modeler/partials/map-legend.blade.php, routes/api.php
TBD
- TBD
- TBD
ci:modeler:FOUR-8000
ci:deploy
=> FOUR-8000 - IT4

ProcessMaker/Events/AuthClientDeleted.php
- Deleting Authentication Client Details are not shown in Security Logs
Create a Authentication Client
Delete Authentication Client
- [FOUR-8697](https://processmaker.atlassian.net/browse/FOUR-8697)
'
ci:deploy
[FOUR-8697]: https://processmaker.atlassian.net/browse/FOUR-8697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-8697: Deleting Authentication Client Details are not shown in Security Logs

resources/views/processes/edit.blade.php, resources/views/processes/translations/export.blade.php, resources/views/processes/translations/import.blade.php
Redirects to translations needs to be fixed:
Descripción
- When user is in export view for process translations and click the cancel button, should redirect to Process Translations tab
- When user is in import view for process translations and click the cancel button, should redirect to Process Translations tab
- When user imports a process translations, should redirect to Process Translations tab
- When user is in export view for process translations and click the Translations breadcrumb, should redirect to Process Translations tab
- When user is in import view for process translations and click the Translations breadcrumb, should redirect to Process Translations tab
- Added fixes for each of the item listed above.
- [FOUR-9135](https://processmaker.atlassian.net/browse/FOUR-9135) …
=> Fix process translations redirects to translations tab

resources/js/processes/translations/components/ProcessTranslationListing.vue
Words in Retry Empty Translations button are not capitalized
- Capitalize words for retry empty translations button.
- [FOUR-9133](https://processmaker.atlassian.net/browse/FOUR-9133)
[FOUR-9133]: https://processmaker.atlassian.net/browse/FOUR-9133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-9133: Retry Empty Translations button words are not capitalized

ProcessMaker/Http/Controllers/Api/OpenAIController.php, ProcessMaker/ProcessTranslations/BatchesJobHandler.php, resources/lang/en.json
**Steps to reproduce**
- Create a process without screens (empty process)
- Go to process configuration
- Click on new translation button
- Select some language
- Try to automatic translate the process
The translation never ends, showing 0% of progress
If there are no strings to translate in the process, should not add an item in the pending translations table and should show to the user an error.
- Fix issue when no strings to translate in a process.
Follow steps above.
- [FOUR-9139](https://processmaker.atlassian.net/browse/FOUR-9139)
[FOUR-9139]: https://processmaker.atlassian.net/browse/FOUR-9139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-9139: Progress still in 0% when a process doesn't have strings to translate

ProcessMaker/Jobs/BoundaryEvent.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, phpunit.xml
This PR refactors the throwMessageEvent function. The primary objective was to enhance the function's performance and provide it the capability to trigger a BpmnAction message event using instance ID, element ID, message reference, and an optional payload. This is important to improve the Webhook Callback in our package-data-sources.
- https://processmaker.atlassian.net/browse/FOUR-8559
=> FOUR-8559 Refactor throwMessageEvent function to use Nayra BPMN engine

resources/js/components/Menu.vue, resources/js/processes/screen-builder/screen.vue, resources/lang/en.json
Preview the screen in desktop and mobile resolutions
Add a desktop and mobile preview button next to the PREVIEW button
1. Switch to feature/FOUR-7965 branch in the projects processmaker and screen-builder
2. Build the assets
3. Open the PM Core
4. Open an existing Screen or create a new one
5. Press on Preview button
6. The new device preview buttons must be displayed
7. Press on mobile preview button
8. The screen must be displayed in mobile resolution
[FOUR-7965](https://processmaker.atlassian.net/browse/FOUR-7965)
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
[FOUR-7965]: https://processmaker.atlassian.net/browse/FOUR-7965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> FOUR-7965 add device preview behavior

ProcessMaker/Events/SecurityLogDownloadFailed.php, ProcessMaker/Events/SecurityLogDownloadJobCompleted.php, ProcessMaker/Http/Controllers/Api/SecurityLogController.php, ProcessMaker/Jobs/DownloadSecurityLog.php, ProcessMaker/Models/Media.php, composer.json, composer.lock, tests/Feature/Jobs/DownloadSecurityLogTest.php
Create an asynchronous download mechanism with AWS
Create 4 environment variables
```
AWS_ACCESS_KEY_ID = access_id
AWS_SECRET_ACCESS_KEY = access_key
AWS_DEFAULT_REGION = region_of_bucket
AWS_BUCKET = name_of_bucket_defined
```
- Run composer install for the new package
- Go to Admin -> Download LOGS
- Go to Security Log -> Download CSV or  Download XML
- A link to download needs to show in a message
- [FOUR-8720](https://processmaker.atlassian.net/browse/FOUR-8720)
ci:deploy
[FOUR-8720]: https://processmaker.atlassian.net/browse/FOUR-8720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
=> FOUR-8720: Create an asynchronous download mechanism

ProcessMaker/Providers/EventServiceProvider.php, config/app.php, tests/Feature/Api/SecurityLogsTest.php
Define a variable in ENV to turn off the security Logs
if the user needs to disable the security log needs to define in the ENV
```
SECURITY_LOG = false;
```
- [FOUR-9018](https://processmaker.atlassian.net/browse/FOUR-9018)
ci:deploy
[FOUR-9018]: https://processmaker.atlassian.net/browse/FOUR-9018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9018: Define a variable in ENV to turn off the security Logs

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Traits/ProcessMapTrait.php
We change the permission to view all request. We add the request to the parameters. 
We added a validation for In-Progress Tasks that were completed to validate the color 
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-9087)
=> Improve the color of a sequenceFlow once it has been completed

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Traits/ProcessMapTrait.php, resources/js/processes/modeler/components/ProcessMap.vue, resources/js/processes/modeler/components/ProcessMapTooltip.vue, resources/js/processes/modeler/process-map.js, resources/views/processes/modeler/inflight-generative-ai.blade.php, resources/views/processes/modeler/partials/map-legend.blade.php, resources/views/requests/show.blade.php, routes/web.php
As a developer, I want to do a code refactor for Process Map feature to ensure quality and maintainability.
- Removed the `ModelerReadonly` component and use only the Modeler component with read-only flag.
- The `Modeler` component is now able to "hide sections" like the ModelerReadonly did.
- Make sure that Modeler (read-only) works with the AI team's work.
- The color of the sequence flows has been fixed when they have been traversed at least once.
- Full names are now used instead of usernames in the Tooltip.
- The appropriate permission is now used when accessing the route that loads the Inflight ProcessMap.
- Added adaptations to ensure that the AI team doesn't encounter any issues when using the ProcessMap.
- The colors have been updated according to the feedback provided by the …
=> FOUR-8828 Process Map refactor

ProcessMaker/Events/FilesDownloaded.php, ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Providers/EventServiceProvider.php
Add logging of users actually downloading a file, either through the Files tab or as part of a form task
- Go to file tab, opens file, downloads
- [FOUR-9155](https://processmaker.atlassian.net/browse/FOUR-9155)
[FOUR-9155]: https://processmaker.atlassian.net/browse/FOUR-9155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature/FOUR-9155: Add logging of users actually downloading a file, either through the Files tab or as part of a form task

.github/workflows/deploy-pm4.yml
=> Updates to GitHub Actions

ProcessMaker/Events/FilesAccessed.php, ProcessMaker/Events/FilesDownloaded.php, ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Providers/EventServiceProvider.php
Add logging of users actually downloading a file, either through the Files tab or as part of a form task
- Go to Request, and check opens file, downloads
- [FOUR-9176](https://processmaker.atlassian.net/browse/FOUR-9176)
ci:deploy
ci:package-files:feature/FOUR-9176
[FOUR-9176]: https://processmaker.atlassian.net/browse/FOUR-9176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9176: Add logging of users actually downloading a file, either through the Files tab or as part of a form task

resources/js/components/shared/Modal.vue
Ticket: [FOUR-9149](https://processmaker.atlassian.net/browse/FOUR-9149)
In the Add Field Modal of the PM Blocks Global Settings, the `Add` and `Cancel` buttons should be right-aligned.
- In the shared Modal component in core, align custom buttons to the right.
- Note: this change will update all Modals that currently use custom buttons, such as the Create PM Block Modal, Create Template Modal, etc.
1. Log in to ProcessMaker.
2. Go to the PM Blocks listing.
3. Have a PM Block created.
4. Go to PM Block Configuration -> Global Settings.
5. Click 'Add Field'.
1. Go to branch `observation/FOUR-9149` in core.
2. Follow the Steps to Reproduce.
- [FOUR-7365](https://processmaker.atlassian.net/browse/FOUR-7365) | PM Blocks
[FOUR-9149]: https://processmaker.atlassian.net/browse/FOUR-9149?atlOrigin …
=> FOUR-9149 | Improve the User Interface in the Global Settings of PM Blocks

resources/views/processes/modeler/partials/map-legend.blade.php
Add the process map legend: Pending / Not Executed
The legend only displays information for Task with completed or in progress status. However, when a user had not participated in a Task (gray color),  that information is not displayed in the legend.
- https://processmaker.atlassian.net/browse/FOUR-9310
=> FOUR-9310 Information about a Task without participating is not displayed in the legend

resources/js/processes/modeler/components/ProcessMapTooltip.vue
The flow participated does not have a title. However, in a flow without participating. Its title is displayed.
Added the title to the sequence flow when going through the request path.
Test that the sequence flows that participated and that did not participate have a title in their tooltip
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-9311)
=> FOUR-9311 Add title to participated flows tooltip

ProcessMaker/Console/Commands/Consumer.php, ProcessMaker/Jobs/RunNayraServiceTask.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/Repositories/Deserializer.php, ProcessMaker/Nayra/Repositories/PersistenceHandler.php, ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php, ProcessMaker/Repositories/TokenRepository.php, resources/js/requests/components/RequestErrors.vue, resources/views/requests/show.blade.php
Bring up a docker ssr to render a html template is a bit overkill, so as a developer I want to use a simple php renderer with mustache and date time format support.
Add HtmlRenderer class with mustache and date format
- Implement a HtmlRenderer class with mustache and date format support.
- Create a process with date and datetime fields and with connector email (e.g. attached process)
- Check the variables are replaced in the email body and the date and time are formatted as the system configuration.
[Test_EmailConnector.zip](https://github.com/ProcessMaker/connector-send-email/files/12021230/Test_EmailConnector.zip)
- https://processmaker.atlassian.net/browse/FOUR-9229
=> FOUR-9229 Review email-connect, to avoid the launch of a docker instance to send an simple email

ProcessMaker/Events/ProcessCreated.php, ProcessMaker/Http/Controllers/Api/ProcessController.php
When Creating a Process with Bpmn and Super Admin as Process Manager, Registry is Wrong
Tickets from QA
- FOUR-8942
ci:deploy
=> FOUR-8942: When Creating a Process with Bpmn and Super Admin as Process Manager, Registry is Wrong

ProcessMaker/Helpers/DBHelper.php, ProcessMaker/Nayra/MessageBrokers/ServiceKafka.php, ProcessMaker/Nayra/MessageBrokers/ServiceRabbitMq.php, ProcessMaker/Nayra/Repositories/PersistenceRequestTrait.php, ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php
Form Task and Participant are not displayed when creating a request.
- Nayra consumers failed to connect to DB because a DB connection lost. Add a DB connection health check
Left to use the server for a night until the connection is closed automatically.
Run a process.
- https://processmaker.atlassian.net/browse/FOUR-9344
=> FOUR-9344 Fix Form Task and Participant are not displayed when creating a request

ProcessMaker/Facades/WorkflowManager.php, ProcessMaker/Jobs/RunNayraScriptTask.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/Repositories/PersistenceHandler.php
In order to properly handle and register Task failures, a new BpmnAction should be implemented.
- Implement a BpmnAction TASK_FAILED
- Create a Process with an Script that thorws an exception.
- https://processmaker.atlassian.net/browse/FOUR-9203
=> FOUR-9203 Add BpmnAction to process a Failed Task

resources/views/layouts/navbar.blade.php
Download Link and the Link Sepated are Shown when Downloading in Logs Admin/Users
Tickets from QA
- FOUR-9348
ci:deploy
=> FOUR-9348: Download Link and the Link Sepated are Shown when Downloading in Logs Admin/Users

database/migrations/2023_07_14_123928_add_index_by_name_to_process_requests_table.php
Filter by process_requests.name is commonly used. In a large DB filter by request name took a long time to complete.
- Add index by process_requests.name.
Run a search by process request name.
- https://processmaker.atlassian.net/browse/FOUR-9363
=> FOUR-9363 Fix Error is generated when creating a saved search filtered by process name

ProcessMaker/ProcessTranslations/ProcessTranslation.php
- Import a process
- Go to Configure > Translations
- Create a translation
- Export the translation
- **Delete the translation**
- Import the translation
After completing the translation a Server Error message is displayed, the list of translations is not displayed and when trying to create a new translation, the dropdown with the languages does not display
The translation should be imported with no issues
- When no translations in the DB, the fields created_at and updated_at for the translation doesn't exists. Added the fields created_at and updated_at when importing into an empty translations column.
- [FOUR-9301](https://processmaker.atlassian.net/browse/FOUR-9301)
ci:deploy
. …
=> Bugfix/FOUR-9301: Error server displayed after import a translation

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Policies/ProcessRequestTokenPolicy.php, ProcessMaker/RollbackProcessRequest.php, resources/js/components/Timeline.vue, resources/lang/en.json, resources/views/requests/show.blade.php, routes/api.php, tests/Feature/Api/TasksTest.php, tests/Fixtures/rollback_test.bpmn, tests/unit/ProcessMaker/RollbackProcessRequestTest.php
Allows the user to rollback a request to a previous task so they can fix issues and try again.
ci:deploy
See the examples in the comments in the PRD https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3081732111/Error+Handling?focusedCommentId=3124789249
Jose said the the first and second examples are the most important. To trigger an error on a form task, assign the task by "rule expression" and give an invalid expression
- https://processmaker.atlassian.net/browse/FOUR-9083
=> Rollback a failed process request

ProcessMaker/Events/FilesCreated.php
- Have package files installed
- Create a folder
- Inside the folder, create a file
- Verify Security Logs
- I added the file_name instead of name
- Upload a File
- Go to Security Logs
- Review the event Files Created
- Click in the URL and check if the route is correct
- [FOUR-9240](https://processmaker.atlassian.net/browse/FOUR-9240)
[FOUR-9240]: https://processmaker.atlassian.net/browse/FOUR-9240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9240: (QA Observation)When Creating Files After Folder Creation, the Link for FilesCreated for the File is Incorrect

ProcessMaker/Models/ProcessRequestToken.php
During the tests of logs. An error happens when a task is reassigned.
- The internal process reassign user is synchronous an should be executed by the default engine (without kafka).
- Create a process with a form task (see the attached process as example)
- Enable reassign task
- Reassign the task
Attached: process
[logs_in_requests.zip](https://github.com/ProcessMaker/processmaker/files/12098900/logs_in_requests.zip)
- https://processmaker.atlassian.net/browse/FOUR-9413
=> FOUR-9413 Run reassign process with default engine

ProcessMaker/Nayra/MessageBrokers/ServiceKafka.php, ProcessMaker/Nayra/MessageBrokers/ServiceRabbitMq.php, config/kafka.php, config/rabbitmq.php
When engine is configured with rabbitmq and it is not used for a long time the connection to the message broker times out.
- Setup the keepalive and timeout properties for the connection to keep alive the connection.
1. Run a process and wait a couple of days (do not run or complete any action in the server)
2. then check the connection is still alive by running another processes.
- https://processmaker.atlassian.net/browse/FOUR-9353
=> FOUR-9353 Fix queue connection timeout

ProcessMaker/Events/ScriptUpdated.php
(QA Observation) ScriptUpdated is automatically created after ScriptCreated
- FOUR-9389
ci:deploy
=> FOUR-9389: (QA Observation) ScriptUpdated is automatically created after ScriptCreated

resources/js/components/templates/ButtonCard.vue, resources/js/components/templates/TemplateSearch.vue, resources/js/components/templates/TemplateSelectCard.vue
- Save the process as template
- Repeat the process three more times
When there are seven templates saved the window displayed is too big and the X button is overlaped with the top of the browser
The window should not reach that size and display a scroll bar in order to prevent this issue
- Added a cards container with height and overflow.
https://github.com/ProcessMaker/processmaker/assets/90727999/42ae060d-7db4-40f7-9e76-20cf19fc80b2
- [FOUR-9387](https://processmaker.atlassian.net/browse/FOUR-9387)
ci:deploy
[FOUR-9387]: https://processmaker.atlassian.net/browse/FOUR-9387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
=> Bugfix/FOUR-9387: X button is displaced when create 7 templates

ProcessMaker/Traits/HideSystemResources.php
When we create a PM Block, we need to hide all the assets linked to the PM Block. At the moment we're only hiding the Screens. 
1. Create a Process with the following: Screen, Scripts, DataSouces.
2. Create a Pm Block from the Process.
3. The Scripts and DataSouces created based on the Pm Block are still showing on the page related to each asset.
- Added Scripts, DataSouces to HideSystemResources.php 
Follow the reproduction steps and check if the Screen and Scripts related to the PM Block are hidden from the page related to the asset.
- Ticket [FOUR-9398](https://processmaker.atlassian.net/browse/FOUR-9398)
[FOUR-9398]: https://processmaker.atlassian.net/browse/FOUR-9398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9398 - Hide Scripts and DataSources of PM Blocks

resources/js/processes/components/CreateProcessModal.vue
- Go to processes > + process > generative AI
- Generate some processes to get history items
- Click on **use model** button and then save in the modal
- You will be redirected to the modeler with the new process
- Go back to the generative ai screen
- The history should be empty
After click on use model and create a process, the history still there.
After click on use model and create a process, the history should be cleared.
- After click save in the modal emit an event to package-ai to clear the history.
https://github.com/ProcessMaker/processmaker/assets/90727999/95e738df-440d-4171-bbb2-8dd5cd07451a
- [FOUR-9438](https://processmaker.atlassian.net/browse/FOUR-9438)
- [Package AI …
=> Bugfix/FOUR-9438: Clear history after click the use model button

resources/js/components/shared/Modal.vue, resources/js/processes/translations/components/CreateProcessTranslationModal.vue
- Go to process > configure
- Click on translations tab
- Click on + translation button
The button to close the modal shows **Cancel** instead **Close**
The button should show Close
- Change cancel text to close. Fix alignment.
**Working screenshot**
- [FOUR-9437](https://processmaker.atlassian.net/browse/FOUR-9437)
[FOUR-9437]: https://processmaker.atlassian.net/browse/FOUR-9437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-9437: Change cancel button text to close in modal

ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php
Problems in service task execution because a new attribute was added to manage the timeout.
- Adapt the code using new class "ErrorHandling".
Set in ".env" file the "MESSAGE_BROKER_DRIVER" value to "rabbitmq" or "kafka" and run a process with service task that uses a Data Connector.
- Package Data Sources
=> FOUR-9410 Test Complex processes with Data Sources

resources/js/components/pm-blocks/CreatePmBlockModal.vue
When creating a PM Block from a Process, the Publish button will create multiple PM blocks when you click on Publish several times in the same request.
1. Click on Process or create a process
2. Click on the ellipsis menu
3. Click on Save as PM Block
4. Add the Pm Block info in the Create Modal
5. Click on Publish MULTIPLE times
You will notice that multiple PM Blocks will be created a the same time.
- Disabled Publish button at each Post request.
Follow the reproduction steps and you will notice that the Publish button will be disabled and only one POST request will be sent.
- Ticket [FOUR-9440](https://processmaker.atlassian.net/browse/FOUR-9440)
[FOUR-9440]: https://processmaker.atlassian.net/browse/FOUR-9440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> FOUR-9440 - Disable Publish PmBlock button at each request

resources/js/components/templates/CreateTemplateModal.vue
When creating a Template from a Process, the Publish button will create multiple Templates when you click on Publish several times in the same request.
1. Click on Process or create a process
2. Click on the ellipsis menu
3. Click on Save as Template
4. Add the Template info in the Create Modal
5. Click on Publish MULTIPLE times
You will notice that multiple Templates will be created a the same time.
- Disabled Publish button at each Post request.
Follow the reproduction steps and you will notice that the Publish button will be disabled and only one POST request will be sent.
- Ticket [FOUR-9439](https://processmaker.atlassian.net/browse/FOUR-9439)
[FOUR-9440]: https://processmaker.atlassian.net/browse/FOUR-9440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> FOUR-9439 - Disable Publish Template button at each request

routes/web.php, tests/Feature/Api/ProcessTest.php
The `process_events/{process}` route stopped working.
- The mentioned route has been restored, which may have been accidentally deleted in this commit: https://github.com/ProcessMaker/processmaker/commit/9dec5b81044b28f65e7ebecf6442ae0ef5a4d9d9.
- Added unit test to take into account this route in the future.
- Follow the steps mentioned in the JIRA ticket to test its functionality.
- Execute unit test.
- [FOUR-9417](https://processmaker.atlassian.net/browse/FOUR-9417)
[FOUR-9417]: https://processmaker.atlassian.net/browse/FOUR-9417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9417 - Rich text-html settings stopped working

ProcessMaker/Events/TemplateDeleted.php, ProcessMaker/Events/TemplateUpdated.php, ProcessMaker/Events/TokenCreated.php, ProcessMaker/Events/TokenDeleted.php, ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/Api/ScriptExecutorController.php, ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Http/Controllers/Api/UserTokenController.php, tests/Feature/Api/SecurityLogsTest.php
Add coverage in the unit test
Run the unit test
- [FOUR-9333](https://processmaker.atlassian.net/browse/FOUR-9333)
[FOUR-9333]: https://processmaker.atlassian.net/browse/FOUR-9333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9333: Unit test

ProcessMaker/Listeners/BpmnSubscriber.php, ProcessMaker/Models/Process.php, resources/lang/en.json, resources/views/processes/edit.blade.php
- Notifications were not being sent to the process manager for failings requests
- Add error notification setting for process request
- Create a process and set a process manager
- Configure the process Notification tab to notify the manager on request error
- Add a failing task to the process. For example, a script task that throws an error or a send email task when the email server credentials are wrong
- Verify the process manager gets a notification when the process is run. They should receive both an in-app notification (bell icon) and an email notification (assuming the email server credentials are correct)
- https://processmaker.atlassian.net/browse/FOUR-8062
=> Add error notification setting for process request

ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/MessageBrokers/ServiceRabbitMq.php, ProcessMaker/Repositories/TokenRepository.php, ProcessMaker/RetryProcessRequest.php
During the retry test, a failed script task that was not fixed, changed the process state to ACTIVE when the user pressed "RETRY" instead of remaining in ERROR as intended.
- Change to ACTIVE only when the script task is completed successfully.
- Create a script task with a throw exception
- Add the script to a process
- The task fails, then try RETRY, the request should keep in ERROR status
- Fix the script
- try RETRY again
- The request should continue (to ACTIVE if there is a next task or COMPLETED if it is the last)
- https://processmaker.atlassian.net/browse/FOUR-9412
=> FOUR-9412 Fix retry script task

ProcessMaker/Nayra/Repositories/PersistenceRequestTrait.php
When a instance is completed the magic variables "_user" and "_request" still present in the request data
- Clean unnecessary data before complete the instance
Set in ".env" file the "MESSAGE_BROKER_DRIVER" value to "rabbitmq" or "kafka" and run a process until complete the flow.
- [FOUR-9482](https://processmaker.atlassian.net/browse/FOUR-9462)
=> FOUR-9462 The summary of a complete request from a process that has a PMBlock shows internal data

ProcessMaker/Http/Controllers/Api/ProcessTranslationController.php, resources/js/processes/translations/components/CreateProcessTranslationModal.vue, resources/lang/en.json
When you select a language in the process translations list, if that language is not present in the languages list in User > settings, show a warning message.
- Add a warning message
- [FOUR-9292](https://processmaker.atlassian.net/browse/FOUR-9292)
[FOUR-9292]: https://processmaker.atlassian.net/browse/FOUR-9292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-9292: Show warning message for no PM languages

ProcessMaker/Console/Commands/ReviewCategoryNull.php, upgrades/2023_06_16_131342_review_categories_null.php
_Based on [original PR](https://github.com/ProcessMaker/processmaker/pull/4897) for v4.6.2 by @marcoAntonioNina._
----
It can be seen that there are several screens with the screen_category_id column null, which could be seen in versions prior to 4.6.0, but currently, they are not displayed in the list of screens since they need to have a category assigned, in addition to having a system category.
- An artisan php command was created, to review all screens with null category
- have screens with field category null, but with assignments in the category_asgments table.
- these screens are not shown in the list of screens.
- run the `php artisan category:review-category-assign` command
- [FOUR-8788](https://processmaker.atlassian.net/browse/FOUR-8788)
[FOUR-8788]: …
=> Screens aren't listed in the screen list in Oakstar Bank Development server with PM4 v4.6.1

config/services.php
Set the default process template categories to the following:
- accounting-and-finance
- customer-success
- human-resources
- marketing-and-sales
- operations
- it
- Change the default templates in the configuration
ci:deploy
ci:db:clean
=> Change default process template categories

resources/js/requests/components/screenDetail.vue
The buttons are enabled in the Request - Forms tab.
1. Create a screen
2. Add a loop check in Allow additional loops
3. inside the loop add any control
4. Create a simple process and add the previously created screen
5. create a request and complete it
6. go to the tab form and click on Details
- Previously, in the form tabs, the CSS rule `pointer-events: none` was used, that rule has been set back as the default.
- Related commit: [https://github.com/ProcessMaker/processmaker/pull/4798/commits/93f47a4d2d71e1d4debedd7567ec9601385c0330](https://github.com/ProcessMaker/processmaker/pull/4798/commits/93f47a4d2d71e1d4debedd7567ec9601385c0330)
- This change is compatible with the previous JIRA ticket ([FOUR-8608](https://processmaker.atlassian.net/browse/FOUR-8608)).
- Follow the reproduction …
=> FOUR-9331: Disable buttons in Forms Tab

database/seeders/ScreenSystemSeeder.php, upgrades/2023_07_18_168972_add_default_screens_for_tasks.php
Fix because we can't call Artisan commands on upgrade scripts for some reason. It just stalls.
ci:deploy
=> Move default screens from seeder to upgrade script

resources/js/processes/modeler/components/ModelerApp.vue
[FOUR-9450](https://processmaker.atlassian.net/browse/FOUR-9450)
This PR addresses an issue where, when editing a PM Block in the modeler and selecting the 'CLOSE' link, the user is erroneously redirected to the Process Listing page instead of the expected PM Block listing page. The update ensures that the 'closeHref' variable is made dynamic, enabling a seamless redirection experience for users, directing them to the appropriate PM Block listing page upon clicking the 'CLOSE' link.
**Test 'CLOSE' link functionality in the modeler:**
1. Edit a PM Block.
2. In modeler click the 'CLOSE' link.
3. Verify that the user is redirected to the PM Block listing page.
4. Ensure the URL matches the expected PM Block listing page address.
**Test 'closeHref' variable behavior  with Processes:**
1. Edit …
=> Enhancement: Enable Dynamic 'closeHref' Variable for PM Block Redirection

ProcessMaker/Events/AuthClientCreated.php
Create an Authenticated Client
Check the User Activity Logging
- I will remove some ids does not provide important information to the end user
Create an Authenticated Client
Check the User Activity Logging
- [FOUR-9662](https://processmaker.atlassian.net/browse/FOUR-9662)
[FOUR-9662]: https://processmaker.atlassian.net/browse/FOUR-9662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9662: remove User_id is present in AuthClientCreated

ProcessMaker/Models/Process.php, ProcessMaker/Policies/ProcessPolicy.php, routes/web.php
As of the current implementation, when a PM block is locked and imported, users retain the ability to edit the PM Block within the modeler. To ensure data integrity and avoid inadvertent modifications, we need to enhance the system behavior.
1. Import a PM Block that is locked.
2. Navigate to the PM Block listing page.
3. Observe that the 'Edit PM Block' action is still visible in the Ellipsis menu.
4. Confirm that attempting to edit a locked PM Block does not prevent modifications in the modeler.
- Updated Process Policy to prevent changes when the user manually accesses `/modeler/{id}` route of a Locked PM Block.
- [FOUR-9471](https://processmaker.atlassian.net/browse/FOUR-9471)
- [PM Block PR](https://github.com/ProcessMaker/package-pm-blocks/pull/58)
[FOUR-9471]: …
=> FOUR-9471 - Prevent Editing of Locked PM Blocks in Modeler

ProcessMaker/Policies/ProcessPolicy.php
When the PM Block package is not installed and we attempt to access the PM Block associated with a Process, a PHP Fatal error is thrown because the class does not exist.
-  An additional check is added to verify that the PM Block package is installed.
- Remove PM Block Package
- Access the route `/modeler/{id}`.
- [FOUR-9471](https://processmaker.atlassian.net/browse/FOUR-9471)
[FOUR-9471]: https://processmaker.atlassian.net/browse/FOUR-9471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue when pm-blocks-package is not installed

ProcessMaker/Events/ProcessPublished.php, ProcessMaker/Http/Controllers/Api/ProcessController.php
Full Set of Categories Updated in ProcessUpdated is Not Completed Shown
- FOUR-9706
=> FOUR-9706: (QA Observation) Full Set of Categories Updated in ProcessUpdated is Not Completed Shown

ProcessMaker/ImportExport/Exporters/ExporterBase.php
Required for https://github.com/ProcessMaker/package-data-sources/pull/307
Occasionally we need to temporarily set a foreign key to null until all the models are saved and we have a new key for it. To support this, we should not consider null values duplicates.
- Skip checking duplicates if the value is null
- See jira issue
- https://github.com/ProcessMaker/package-data-sources/pull/307
- https://processmaker.atlassian.net/browse/FOUR-9646
ci:package-data-sources:bugfix/FOUR-9646
=> Do not consider null values duplicates when importing

ProcessMaker/Assets/ScreensInScreen.php
In the file to import not exists a screen, this screen refers to a nested screen.
- Add validation when the reference of the NestedSscreen's screen not exists.
- add a log message
Import process and review the message, the process was imported but without a screen reference
[FOUR-7247](https://processmaker.atlassian.net/browse/FOUR-7247)
ci:deploy
[FOUR-7247]: https://processmaker.atlassian.net/browse/FOUR-7247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add message when missing nested screen's screen

ProcessMaker/Events/CategoryCreated.php
A link name for process category is not working
1. Create a process category process
2. Check the User Activity Logging
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-9705)
=> FOUR-9705: Process Category Link for Name is Not Working

resources/js/components/shared/PmqlInputFilters.vue
The problem was related to the `avatar` prop when is null for requester and participant lists. For some reason some users have the prop `avatar` in null and not as empty string (Maybe when the users are imported with ldap or something similar)
**Steps to reproduced:**
1.Log in PM
2.Click on Filter
3.Review Requester and Participants fields
- Check if avatar prop exists for requests and participants
**Working video and reproduction explanation**
https://github.com/ProcessMaker/processmaker/assets/90727999/a80937cf-603c-49dd-9e5f-bf124f0fe14f
- Go to the database to the `users` table and modify the `avatar` column for some user to be `NULL` instead `empty`
- Go to requests lists and click on filter
- [FOUR-9721](https://processmaker.atlassian.net/browse/FOUR-9721)
[FOUR-9721]: …
=> Bugfix/FOUR-9721: Two filter fields are no longer displayed

ProcessMaker/Http/Controllers/Api/TemplateController.php, resources/js/processes/export/DataProvider.js, routes/api.php
This PR addresses the two issues mentioned in [FOUR-9725](https://processmaker.atlassian.net/browse/FOUR-9725) related to process template import and update errors. The following changes have been made to resolve the problems:
**Issue 1: API Clash during Process Template Import**
- Modified the route for importing process templates from template/do-import/{type} to template/{type}/do-import.
- Updated the route order to ensure that the more specific route for importing takes precedence over the generic storing template route.
**Issue 2: 'getOriginal()' Error during Process Template Update**
- Removed the duplicated `getOriginal()` method that was being called on an array.
- Test the import functionality to ensure successful routing and handling of the process templates.
- Confirm the …
=> Resolve API Clash and 'getOriginal()' Error When Importing and Updating Process Templates

ProcessMaker/Http/Controllers/Api/ExportController.php, resources/js/processes/export/DataProvider.js, tests/Feature/ImportExport/Api/ExportImportTest.php
Filename formats are not consistent between the exported processes and exported PM Blocks.
Change the exported process filename to be all lowercase and replace all spaces with underscores to match PM Blocks
- Create a process with uppercase letters and spaces in the title
- Export the process and verify the filename format is correct
- https://processmaker.atlassian.net/browse/FOUR-9724
=> Update export filename format

ProcessMaker/ImportExport/Exporters/ScreenExporter.php, tests/Feature/ImportExport/Exporters/ScreenExporterTest.php, tests/Feature/ImportExport/fixtures/screen_with_nested_screens_in_loop_and_multicolumns.json
See Jira issue. Nested screens in loops are being exported but are not being re-associated to the correct ID when importing.
- Refactor the logic to include loops when looking for nested screens to re-associate.
- Bonus performance update by using an old-to-new ID map so we don't iterate the entire config for every nested screen.
Follow reproduction steps in Jira issue. Nested screens should correctly associate to the new screens
- https://processmaker.atlassian.net/browse/FOUR-9641
=> Refactor associateNestedScreen to include loops

resources/sass/app.scss
The list of options is displayed on the bottom of the page and not directly under the field, it even moves with the page when scroll down the page 
The list should be displayed under the field.
- ` overflow-x: hidden` was removed from  **html and body** styles.
https://github.com/ProcessMaker/processmaker/assets/1401911/8e494cc8-a3fc-4828-a0c4-9c3301324c9f
1. Install google places and webentry packages in your pm instances
2. Create a Screen with some controls (Any) to enable the scroll,
3. Add various Google place fields,
4. Add google places inside a nested screen
5. Add google places inside a tables 
6. Create a process with WE 
7. Assign the screen in the WE
8. Create a request
9. Scroll down to Google places
10. Set an address
- https://processmaker.atlassian.net/browse/FOUR-8032
=> FOUR-8032: Options of Physical Address are not displayed directly under the field but at the bottom of the page

ProcessMaker/Http/Controllers/TemplateController.php
When editing a default template for the first time, in some cases we will get a json_decode error or Server Error in the nightly build.
1. Click on Designer->Templates
2. Click on Edit Template within the Ellipsis menu of one of the Default Templates.
If the error doesn't show up, click on a different template.
- Implement flash message similar to what we have when we create a Process from a Template.
1. Click on Designer->Templates
2. Click on Edit Template within the Ellipsis menu of one of the Default Templates.
3. Make sure we don't get an error when editing a template and the flash message is included. (The template was created.) 
Ticket: [FOUR-9718](https://processmaker.atlassian.net/browse/FOUR-9718)
[FOUR-9718]: https://processmaker.atlassian.net/browse/FOUR-9718?atlOrigin=eyJpIjoi …
=> Implement flash message when editing a default template

ProcessMaker/Traits/MakeHttpRequests.php, ProcessMaker/WebServices/NativeSoapClient.php
The problem is related to the logs folder is missing in the installation. This happens because the logs are redirected to the stderr channel instead of the files.
- This PR moves the data-sources logs to `data-sources/logs` which is a shared path and will not have conflict with the stderr configuration.
- Wait for the deploy (should use the STDERR channel for the logs).
- Go to data sources page
- No errors should be displayed
- https://processmaker.atlassian.net/browse/FOUR-9668
=> Move data-source logs into its own folder inside storage

ProcessMaker/Http/Middleware/GenerateMenus.php, README.md, resources/js/components/NavbarProfile.vue, resources/js/processes/scripts/customFilters.js, resources/views/about/index.blade.php
As a ProcessMaker user, I want to access ProcessMaker documentation via the new, more friendly documentation subdomain [docs.processmaker.com.](http://docs.processmaker.com/)
- Change all links from [https://processmaker.gitbook.io/processmaker](https://processmaker.gitbook.io/processmaker) to [https://docs.processmaker.com/](https://docs.processmaker.com/).
- Ensure all packages also have the correct links.
- https://processmaker.atlassian.net/browse/FOUR-9740
=> [FOUR-9740] Update documentation links

ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php
A process stops when a service task fails at https://nightly-qa.processmaker.net/.
Steps to reproduces:
1. Create a decision table with invalid rules
2. Create a process that calls to the decision table (See the attached process)
3. Run the process
4. When the process runs the invalid decision table will stop to process.
Show the error response from the task
- Fix the code where the error is handled.
1. Create a decision table with invalid rules
2. Create a process that calls to the decision table (See the attached process)
3. Run the process
4. When the process runs the invalid decision table will stop to process.
[Test_OR AND.zip](https://github.com/ProcessMaker/processmaker/files/12244045/Test_OR.AND.zip)
- https://processmaker.atlassian.net/browse/FOUR-9739 …
=> FOUR-9739: Fix error handling

ProcessMaker/Assets/ScreensInScreen.php, ProcessMaker/Console/Commands/ReviewCategoryNull.php, ProcessMaker/Events/ProcessPublished.php, ProcessMaker/Events/TemplateUpdated.php, ProcessMaker/Events/TokenCreated.php, ProcessMaker/Events/TokenDeleted.php, ProcessMaker/ImportExport/Importer.php, ProcessMaker/SanitizeHelper.php, tests/Feature/Api/SecurityLogsTest.php, tests/Feature/Templates/Api/ProcessTemplateTest.php
This pull request (PR) addresses a critical issue related to exporting and importing script tasks with webhooks enabled when they are referenced in the `data_source_scripts table`. The previous error was hindering the proper export and import of PM Blocks that utilize a data source script into an instance. With this PR, we have introduced a comprehensive solution that allows for seamless import of the data source script, generating a new ID, and updating the BPMN scriptRef ID to reflect the newly generated ID.
Additionally, as part of this solution, we have created separate PRs for both Data Sources and the Collections package to ensure smooth handling of script dependencies and proper UUID generation during the export/import process.
- **Fixing Script Task Export/Import Error**: …
=> Fix PM Block Export/Import with Data Source Scripts and Collections

ProcessMaker/Traits/HideSystemResources.php, upgrades/2023_08_02_168972_add_default_screens_to_system_category.php
Please see to the ticket https://processmaker.atlassian.net/browse/FOUR-9727
- Update the scopeNonSystem function to look at category_assignments to make sure the asset does not belong to a system category.
https://github.com/ProcessMaker/processmaker/assets/90727999/07e6dd84-5e70-494a-b2ef-a0e8fa045927
Test 1
- Import the attached process in the ticket
- Go to scripts and verify that the script is showing in the list
Test 2
- In category_assignments table, modify the category_id to point to a system category (you need to go to script_categories table and modify some script category to be is_system = 1)
- Go back to scripts, and the script using the system category should not show
Test 3
- Test the same as test 2 but with processes
- Test the same as test 2 but with …
=> Bugfix/FOUR-9727: Non-system assets are being hidden from the UI as if they were system assets

ProcessMaker/Events/TemplateUpdated.php
TemplateUpdated does not Have Registry to View Information
- FOUR-9743
ci:deploy
=> FOUR-9743: (QA Observation)

ProcessMaker/Events/PermissionUpdated.php, ProcessMaker/Http/Controllers/Api/PermissionController.php
When a group permissions are changed an 404 error is displayed. This is because a missing call to the Change Log when changing the permissions.
- Implement the code to register the group permissions change log
- As an admin user, go to admin/groups
- Open a group
- Go to permissions
- Add/remove permissions
- Save the changes
[ChangeGroupPermissions.webm](https://github.com/ProcessMaker/processmaker/assets/8028650/215c541b-a378-4445-958e-ec3670d1d655)
- https://processmaker.atlassian.net/browse/FOUR-9772
=> FOUR-9772: Add group permissions change log

ProcessMaker/ImportExport/Exporters/ExporterBase.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/ImportExport/Exporters/ScriptExporter.php, ProcessMaker/ImportExport/Utils.php, tests/Feature/ImportExport/Exporters/AssignmentExporterTest.php, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php, tests/Feature/ImportExport/Exporters/ScriptExporterTest.php, tests/Feature/ImportExport/HelperTrait.php, tests/Feature/ImportExport/fixtures/process-with-different-kinds-of-call-activities.bpmn.xml
See description in Jira issue
If we export a process with a script, the script will have a "Run script as" user assigned. Users are not exported. When we import the process, the system searches for a user with the same UUID, email, or username. If found, it sets the "Run script as" user to that user. However, if the user is not found in the target instance, it does not change the "Run script as" user id. This could create a problem if the source instance had a Run script as user: bob with the id 5 and the target instance does not have bob, but does have the user alice and happens to have the same ID: 5. When the script imports, since it does not change the "Run script as" user id, the script will be accidentally assigned to alice My suggestion is that we set the "Run script as" user to …
=> Remove dependent assignment when not on target instance

ProcessMaker/Http/Controllers/Api/PermissionController.php
- Create a new user
- Go to the user’s Permissions tab
- Attempt to assign all permissions or any permissions to the user
- Click the Save button
- The property memberships was not defined and is not used
- Create a new user
- Go to the user’s Permissions tab
- Attempt to assign all permissions or any permissions to the user
- Click the Save button
- [FOUR-9787](https://processmaker.atlassian.net/browse/FOUR-9787)
[FOUR-9787]: https://processmaker.atlassian.net/browse/FOUR-9787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9787: Server error when updating user permissions

ProcessMaker/Http/Middleware/GenerateMenus.php, ProcessMaker/Managers/MenuBuilder.php, ProcessMaker/Managers/MenuManager.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, resources/views/layouts/navbar.blade.php
- Enable the Analytics package
- Check all the principal menus
- We can see some highlighting issues
- I extended the Menu Class in order to provide a way to add a Menu in the **topnav** like the following example:
`$topnav->add(__('Analytics'), [
'route' => 'package.analytics.tab.index',
'id' => 'analytics',
'afterItem' => 'requests',
'index' => '2',
])->active('package-analytics-reporting/*');`
Enable the package-analytics-reporting this will enable a menu in the topnav 
010-b525-cf18050d35ac)
- [FOUR-9666](https://processmaker.atlassian.net/browse/FOUR-9666)
[FOUR-9666]: https://processmaker.atlassian.net/browse/FOUR-9666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9666: Inconsistent top menu highlighting

config/app.php
Improve the default URL reports adding in the .env
- Add the variables in the .env in order to define the default charts
```
ANALYTICS_REPORTING_DEFAULT_GRAPH_1 = 'https://us-east-1.quicksight.aws.amazon.com/sn/embed/share/accounts/441441716351/dashboards/39d4b078-87d4-4272-8399-2b8b3324f5b7/sheets/39d4b078-87d4-4272-8399-2b8b3324f5b7_83f09431-ba5f-4a3b-99ec-456a618239ac/visuals/39d4b078-87d4-4272-8399-2b8b3324f5b7_3d430118-e980-41d8-b753-1bba4e282f35?directory_alias=researchquicksight'
ANALYTICS_REPORTING_DEFAULT_GRAPH_2 = 'https://us-east-1.quicksight.aws.amazon.com/sn/embed/share/accounts/441441716351/dashboards/39d4b078-87d4-4272-8399-2b8b3324f5b7/sheets/39d4b078-87d4-4272-8399-2b8b3324f5b7_83f09431-ba5f-4a3b-99ec-456a618239ac/visuals/39d4b078-87d4-4272-8399-2b8b3324f5b7_5fc8e340-0e63- …
```
=> FOUR-9792: Improve the default URL reports adding in the .env

resources/views/layouts/layout.blade.php
After selecting a previous version of history the Text overlap of control.
1. Generate a process using AI and Google Chrome browser.
2. Set the following text in Description: `create process for selling shoes`.
3. Update text in Description: `create process for selling shoes and reports in pdf connector`.
4. Go to History
5. Select the previous version
6. **Repeat step 5 until you see Text overlapping (it's a random bug)**
- Use the object tag instead of iframe.
- Enabling the use of the object tag for same-origin resources.
- Follow the reproduction steps of above.
- [FOUR-9742](https://processmaker.atlassian.net/browse/FOUR-9742)
- [Package AI PR](https://github.com/ProcessMaker/package-ai/pull/11)
[FOUR-9742]: https://processmaker.atlassian.net/browse/FOUR-9742?atlOrigin=eyJpIjoiNWRkNTl …
=> FOUR-9742 - AI Process>> Text overlap of control

ProcessMaker/ImportExport/Exporters/ScriptExporter.php, tests/Feature/ImportExport/Exporters/ScriptExporterTest.php
See https://processmaker.atlassian.net/browse/FOUR-9646?focusedCommentId=339247
We now allow null values for run_as_user_id (from [9747](https://processmaker.atlassian.net/browse/FOUR-9747)) however a script with null run_as_user_id is not able to export.
- Check for a null run_as_user_id before adding the user as a dependent in the script exporter.
- Create a script with a regular user as the Run Script As user
- Create process with the script
- Export the process
- Clear your DB or use another instance that does not have the user
- Import the process (this should work fine, as it did before this fix. The run_as_user_id will be null in the database)
- Create a PM block form the imported process. Before this fix we would get an error.
- https://processmaker.atlassian.net/browse/FOUR-9646
=> Allow null run_as_user_id in scripts export

ProcessMaker/Exception/ReferentialIntegrityException.php
When we try to delete a user that has requests, it shows us an unfriendly error.
- Use the correct model in the validation function.
1. Go to the Users menu /admin/users.
2. Select a user who has requests.
3. Try to remove it
- [FOUR-8856](https://processmaker.atlassian.net/browse/FOUR-8856)
[FOUR-8856]: https://processmaker.atlassian.net/browse/FOUR-8856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> User cannot be deleted in one of Ellucian's Test instances [32101]

ProcessMaker/Events/CustomizeUiUpdated.php, ProcessMaker/Http/Controllers/Api/CssOverrideController.php
- Do any modification in Customize ui
- Save these modifications
- Add validations and set some variables with default variables
- [FOUR-9800](https://processmaker.atlassian.net/browse/FOUR-9800)
[FOUR-9800]: https://processmaker.atlassian.net/browse/FOUR-9800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-9800:Customize UI Shows Server Error After Changes

resources/js/processes/components/CreateProcessModal.vue
Steps to reproduced:
1.Go to designer
2.Click on +Process
3.Complete Name
4.Complete Description
5.Add Process Manager
6.Remove Process Manager
7. Click on Save button
The process cannot be created, the save button is blocked and a message is displayed in the console "Cannot read properties of null".
You should be able to create a process without problem.
- Set manager to empty string instead to null when changing the value.
https://github.com/ProcessMaker/processmaker/assets/90727999/5c00d9f3-c95f-49a6-9315-b57384c7b4c1
- [FOUR-9798](https://processmaker.atlassian.net/browse/FOUR-9798)
[FOUR-9798]: https://processmaker.atlassian.net/browse/FOUR-9798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> Bugfix/FOUR-9798: Cannot create a process if it is added and then clears the Process Manager field

ProcessMaker/ImportExport/Exporters/ScriptExporter.php
when searching within the scripts for the name of an environment variable, the name of the environment variable was found as part of another string, therefore the variable was exported.
- Change to a regular expression to search for the environment variable.
when you have a process with scripts verify that they have environment variables and also have names as part of another string
- [FOUR-9755](https://processmaker.atlassian.net/browse/FOUR-9755)
[FOUR-9755]: https://processmaker.atlassian.net/browse/FOUR-9755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> I get "Set Password" when exporting a process with scripts

tests/Feature/Templates/Api/ProcessTemplateTest.php
This PR has been created to test the functionality of the new Templates within CI. We ran into an issue with the unitTest that may be happening based on the number of transactions needed to process the TemplateToProcessSync.
` phpunit tests/Feature/Templates/Api/ProcessTemplateTest.php --filter=testTemplateToProcessSync`
- Skip `testTemplateToProcessSync` for now.
1. Please ensure that you have the Templates env variables within PM.
```
DEFAULT_TEMPLATE_REPO=process-templates
DEFAULT_TEMPLATE_BRANCH=develop
DEFAULT_TEMPLATE_CATEGORIES=all
```
2. Wipe the database and reinstall PM. (You should see 20 templates only)
3. Now change in the .env the default branch to `DEFAULT_TEMPLATE_BRANCH=Templates-08-04-2023`
4. Please verify that we have 41 templates and that we don't have any duplicates …
=> FOUR-9814: Add new Default templates

ProcessMaker/Models/ScriptExecutor.php, config/broadcasting.php, database/seeders/UserSeeder.php, resources/views/layouts/layout.blade.php
DevOps was using old hotfix files when building the images: https://github.com/ProcessMaker/pm4-k8s-distribution/tree/b95cbada6e479a033f533b5c8f8ebfebca257632/images/hotfixes/core
The old ScriptExecutor.php file didn't have the code that generates UUIDs
This PR backports DevOps's changes into core so they don't have to use hotfixes, and as a result, will use the current ScriptExecutor.php file (and other files) and so fixes this issue.
**Note: DevOps must be alerted when this is merged so they can delete the hotfixes**
See Jira issues
- https://processmaker.atlassian.net/browse/FOUR-9830
- several other QA observations from nightly-qa.processmaker.net
=> Backport hotfix changes from STM

resources/js/tasks/components/TasksPreview.vue
Add the Close windows
- https://processmaker.atlassian.net/browse/FOUR-9594
ci:deploy
=> feature/FOUR-9594:  Add the Close windows

resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksPreview.vue
Action: See the next or previous task in their list
Select a task in the modeler.
Find and click the new Preview icon in the list (an eye icon, according to the mock up design), for each task.
Find and click the prev or next button.
See the corresponding task
- https://processmaker.atlassian.net/browse/FOUR-9581
ci:deploy
=> feature/FOUR-9581: See the next or previous task in their list

upgrades/2023_08_11_168972_add_missing_uuids_to_script_executors.php
See https://processmaker.atlassian.net/browse/FOUR-9830?focusedCommentId=349049
Due to the hotfixs, some script executors may not have UUIDs, which causes exporting to fail.
- Add any missing UUIDs for script executors
Have some script executors with null UUIDs and run the `php artisan upgrade`. They should be populated
- https://processmaker.atlassian.net/browse/FOUR-9880
- https://processmaker.atlassian.net/browse/FOUR-9830?focusedCommentId=349049
=> Add upgrade script to fix missing UUIDs

resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksPreview.vue
As a Participant, I want to jump between task and their Preview, without having to close the preview and opening the next one or previous one, so that I can understand my open tasks
1. Visit the task list.
2. Select a task and open the Preview Pane.
3. Find and click the Next and Previous Buttons.
4. See the next or previous task in their list.
5. For tasks that are first (or last) in their respective lists, will have these buttons inactive.
- https://processmaker.atlassian.net/browse/FOUR-9500
ci:deploy
=> Feature/four 9500: Next-Back Pane Navigation

package-lock.json, package.json
When using the github branch, when building the PM4 image it downloads all the dev dependencies for the package including phantomjs@2+chromium, which is not required.
Using the released version "^3.6.1" it downoads the released build and does not download the dev dependencies.
- Use svg-pan-zoom@^3.6.1.
=> Bump svg-pan-zoom@^3.6.1

config/broadcasting.php, resources/views/layouts/layout.blade.php
Backporting the hotfixes enabled Soketi but broke Pusher. We need to support all 3 broadcasting services:
- Laravel Echo Server (local development)
- Pusher (CICD)
- Soketi (k8s)
- Update config to support all 3
- Laravel Echo Server
- run `npx laravel-echo-server start` if its not already running
- Set .env
```
BROADCAST_DRIVER=redis
```
- Pusher
- Create a pusher account and add to your .env
```
BROADCAST_DRIVER=pusher
PUSHER_APP_ID=947781
PUSHER_APP_KEY=<key>
PUSHER_APP_SECRET=<secret>
PUSHER_CLUSTER=<cluster>
PUSHER_TLS=FALSE
PUSHER_DEBUG=FALSE
```
- Soketi
- run `docker run -p 6001:6001 -p 9601:9601 quay.io/soketi/soketi:1.4-16-debian`
- .env
```
BROADCAST_DRIVER=pusher
PUSHER_HOST=127.0.0.1
```
NOTE: `BROADCAST_DRIVER` is `pusher` for both Pusher and Soketi. Having `PUSHER_HOST` is …
=> Update config for Pusher and Soketi

resources/js/components/templates/TemplateSearch.vue, resources/js/processes/components/CreateProcessModal.vue
Ticket: [FOUR-9962](https://processmaker.atlassian.net/browse/FOUR-9962)
Upon attempting to select a template for process creation, a 422 error is encountered, impeding the successful utilization of the chosen template to generate the process. This error disrupts the expected workflow and needs to be resolved promptly to enable seamless template-based process creation.
-Include the template version when creating a process from a template.
1. Within the Process Designer select '+ Process' button
2. Select a template and select 'Use Template' button
3. Fill out the form
4. Select the 'save' button
A process is created from the template with no errors.
[FOUR-9962]: …
=> Resolve 'version' is required when creating a process from template

.gitignore, upgrades/2023_08_15_183028_remove_seeded_default_templates.php
When attempting to build the project, template migrations are encountering issues, leading to failures in the build pipeline. This is likely due to a missing check for the 'versions' column within the default sync job.
- After talking with @nolanpro and since we don't make any changes to the database schema, we can safely move the migration to the upgrades folder.
- This solution should also speed up our unitest since the upgrades scripts are not been called by PHPUnit
Please run the following command and make sure that we don't get any errors when running the migrations and that the Default Templates are in sync.
`php artisan db:wipe --force && php artisan migrate:fresh --seed --force && php artisan upgrade`
note: The upgrade artisan command has been added after the db wipe.
- Ticket: …
=> FOUR-9971: Move failing migration to upgrades

.gitignore, composer.json, composer.lock, package-lock.json, package.json, resources/js/components/pm-blocks/CreatePmBlockModal.vue, upgrades/2023_08_15_183028_remove_seeded_default_templates.php
This PR addresses the need to remove the custom icon upload button for PM Block icons in order to align with the intended design and user experience expectations. Currently, the custom icon upload feature does not fit within the established requirements for PM Block icons.
Remove the custom icon upload button for PM Block icons.
Create a PM Block from the Processes listing page
Ensure the custom icon upload button is not displayed.
Navigate to the configuration page of a PM Block
Ensure the custom icon upload button is not displayed.
Ticket [FOUR-9972](https://processmaker.atlassian.net/browse/FOUR-9972)
[PM Blocks Package PR](https://github.com/ProcessMaker/package-pm-blocks/pull/83)
[FOUR-9972]: https://processmaker.atlassian.net/browse/FOUR-9972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> Remove Custom Icon Upload Button for PM Block Icons

ProcessMaker/Jobs/DownloadSecurityLog.php, config/app.php
This is related to the S3 configurations
Cloud Ops team needs to have the capacity to change the folder name **security-logs** for each environment like:
- I will add a new variable in the.env in order to define a different name **security-log**
- Define a variable SECURITY_LOG_S3_URI like `SECURITY_LOG_S3_URI = 'customer-a'`
- Download the log 
- Review the S3 has created a bucket with the name defined in  SECURITY_LOG_S3_URI inside AWS_BUCKET
ci:deploy
ci:SECURITY_LOG_S3_URI="customer-ci"
=> FOUR-9970: Admin log S3 feature changes in order to support renaming the subfolders

ProcessMaker/Http/Controllers/ProcessController.php
the problem is replicated when using NayraDocker when you want to start a request by URL
http://192.168.1.205/process_events/2?event=node_21
the _request variable is not defined.
- as the request id is needed we no longer use the _request variable
try to start a case by url
http://192.168.1.205/process_events/2?event=node_21
[FOUR-9840](https://processmaker.atlassian.net/browse/FOUR-9840)
[FOUR-9840]: https://processmaker.atlassian.net/browse/FOUR-9840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Rich text-html settings stopped working to initiate a requests

resources/js/components/templates/TemplateSearch.vue
Ticket: [FOUR-9964](https://processmaker.atlassian.net/browse/FOUR-9964)
When searching for a template in the New Process Modal, the search functionality is behaving erratically.
- There was a watcher on the search filter that fetched templates with each change of the filter.
- Search functionality works without the watcher. However, the watcher is needed to fetch templates when the filter is an empty string (i.e. when a user searches and then backspaces/clears our their search term). Added a conditional to the watcher for this case.
- This PR also adds functionality to the search button in the search bar when clicked.
- This PR also removes the extra spacing above the 'No Data Available' search result so that users don't have to scroll to see the image when there are no results.
1. Go to …
=> FOUR-9964 | Template Search Behaving Erratically

ProcessMaker/ImportExport/Exporters/ExporterBase.php, ProcessMaker/ImportExport/Exporters/ScriptExecutorExporter.php, ProcessMaker/ImportExport/Exporters/ScriptExporter.php, ProcessMaker/ImportExport/Importer.php, ProcessMaker/ImportExport/Manifest.php
Currently exporting a ScriptExecutor was not enabled, for that reason when you have Custom ScriptExectors it is not reflected on the import on a new server
Just enabled the option, and added a fix to continue if a ScriptExecutor doesn't exist.
Also added the BuildScriptExecutor when creating or updating a ScriptExecutor.
Create a script executor that exists like PHP or another language
Create a Script with the script executor
Create a process with a script task
Publish the changes 
Export the process
Import the process in a new instance the PM 
Try to export the process
- [FOUR-9997](https://processmaker.atlassian.net/browse/FOUR-9997)
- [FOUR-9996](https://processmaker.atlassian.net/browse/FOUR-9996)
[FOUR-9997]: https://processmaker.atlassian.net/browse/FOUR-9997?atlOrigin=eyJpIjoiNWRkNT …
=> Cannot export a previously imported process containing a script with a missing script executor

ProcessMaker/ImportExport/Manifest.php
when a ProcessTemeplate was edited and exported, this file cannot be exported, because another uuid parameter existed in the table that should be unique.
- I removed the edit_process_uuid parameter because this template is new
steps in ticket
- [FOUR-9876](https://processmaker.atlassian.net/browse/FOUR-9876)
[FOUR-9876]: https://processmaker.atlassian.net/browse/FOUR-9876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> It is not possible to import templates that were modified

resources/js/processes/export/DataProvider.js
When we import a process it can take a long time. For the import/export call it was set to 60 seconds.
- The default was changed to 90 seconds and if the api_timeout variable in the configuration is greater than this, the configuration value is taken.
import large processes
- [FOUR-10008](https://processmaker.atlassian.net/browse/FOUR-10008)
[FOUR-10008]: https://processmaker.atlassian.net/browse/FOUR-10008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change time provider import

resources/js/admin/cssOverride/components/SiteDesign.vue
- Go to Customize UI https://ci-cd8f9a6170.eng.processmaker.net/admin/customize-ui
- Check the Save button 
- Add padding bottom.
- [FOUR-10020](https://processmaker.atlassian.net/browse/FOUR-10020)
ci:deploy
[FOUR-10020]: https://processmaker.atlassian.net/browse/FOUR-10020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-10020:Intercom Overlaps Save Icon in Customize UI

resources/js/app-layout.js
The problem happens in firefox when a request is aborted. If the user clicks on the button Generate process using AI before the templates request finished it shows a Request abort message.
Steps to Reproduce: 
- Log in with  Fire Fox  browser
- Click on +PROCESS
- click on Generate from text 
NOTE: If you can't reproduce the issue, add in TemplateController.php in the index method the following code to simulate a slow request:
`
if ($type === 'process') {
sleep(10);
}`
- Do not show the error messages related to ECONNABORTED.
- [FOUR-10079](https://processmaker.atlassian.net/browse/FOUR-10079)
ci:deploy
[FOUR-10079]: https://processmaker.atlassian.net/browse/FOUR-10079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-10079: We get a Request aborted message when we want to create a process from AI in fire fox

config/app.php
As a user I want to have a default Dashboard that will be placed in the Analytics option. 
- A Dashboard was created in the Quicksight
- This Dashboard will defined in the Analytics Default
- Configure in the .env the variable: `PM_ANALYTICS_DASHBOARD="https://quicksight.aws.amazon.com/"`
- Install the package
- Review the **Analytics Management**, this will show per default the Dashboard defined in PM_ANALYTICS_DASHBOARD
- https://processmaker.atlassian.net/browse/FOUR-10152
ci:package-analytics-reporting:feature/FOUR-10152
=> FOUR-10152: Making changes to create one Dashboard defined in the .env

ProcessMaker/Helpers/MobileHelper.php, ProcessMaker/Http/Controllers/RequestController.php, resources/js/app-layout.js, resources/views/auth/login.blade.php, resources/views/layouts/mobile.blade.php, resources/views/requests/mobile.blade.php
Create a Mobile Main View
- Create variable **isMobile** in windows.ProcessMaker, then create a cookie to handle the views (isMobile)
From Mobile device Login to ProcessMaker App
- [FOUR-10035](https://processmaker.atlassian.net/browse/FOUR-10035)
[FOUR-10035]: https://processmaker.atlassian.net/browse/FOUR-10035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:next
=> FOUR-10035:Create a Mobile Main View

resources/js/app-layout.js, resources/views/layouts/navbarMobile.blade.php
As a mobile participant I want to see the UI as it regularly displays on a desktop, so I can access otherwise tucked away sections of the app.
User visits the default mobile home page, finds the Switch to Desktop View, and is then presented with the regular UI. This is the only way to access Designer and Admin sections when appropriate.
- https://processmaker.atlassian.net/browse/FOUR-9527
-
ci:next
=> feature/FOUR-9527: Main View - Switch to desktop mode and Log Out

config/app.php
As a user I want to have a default Dashboard that will be placed in the Analytics option. 
this dashboard will show 3 initial graphics that will show this information;
https://processmaker.atlassian.net/l/cp/tDmRHXsS
- LAs a user I want to have a default Dashboard that will be placed in the Analytics option. 
this dashboard will show 3 initial graphics that will show this information;
- Go to Quicksight
- Open the Dashboard + Click Share Dashboard 
- Copy the Copy embed code
- This copy has a content like:
```
<iframe
width="960"
height="720"
src="https://us-east-1.quicksight.aws.amazon.com/sn/embed/share/accounts/441441716351/dashboards/21802b4e-8312-4d6c-b67e-d9e9cc189826?directory_alias=researchquicksight">
</iframe>
```
- Extract the link related to the src
- Add this value to the …
=> feature/FOUR-9994: Improvement of Analytics dashboard of Summer 23

resources/js/components/shared/DownloadSvgButton.vue
Please refer to acceptance criteria of ticket:
https://processmaker.atlassian.net/browse/FOUR-10277
- Replaced the ai description with the prompt entered by the user
https://github.com/ProcessMaker/processmaker/assets/90727999/e4b3c6e6-41d8-4e94-9e04-1c787147f2d2
- [FOUR-10277](https://processmaker.atlassian.net/browse/FOUR-10277)
- [package-ai](https://github.com/ProcessMaker/package-ai/pull/20)
ci:deploy
ci:package-ai:bugfix/FOUR-10277
[FOUR-10277]: https://processmaker.atlassian.net/browse/FOUR-10277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-10277: Prompt not used on the image downloaded

.github/workflows/deploy-pm4.yml, composer.lock
Since all packages use the github actions settings from the develop branch, we need to allow the settings on develop to choose the correct base image
ci:deploy
=> Set CI Base on develop

resources/js/processes/scripts/components/ScriptEditor.vue
1. Login as admin
2. Go to Designer
3. Click on Scripts
4. Click on +Script
5. Set the information required
6. Click on Cornea AI Assistant
7. Click on Any option and generate
By modifying the `v-if` that hides the Top Menu and replacing it with a `v-show` the destruction of that component is avoided. The problem was caused because `package-versions` only included the Publish button and other elements once and would not do it again when the Top Menu component was destroyed and recreated.
- [FOUR-10223](https://processmaker.atlassian.net/browse/FOUR-10223)
[FOUR-10223]: https://processmaker.atlassian.net/browse/FOUR-10223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:next
ci:deploy
=> FOUR-10223: Publish button and Top Menu elements on Script Editor now visible after Ai Assistant actions 

resources/js/processes/categories/components/CategoriesListing.vue
Ticket: [FOUR-10284](https://processmaker.atlassian.net/browse/FOUR-10284)
We need to add `data-test` or `data-cy` attributes to the following components:
- Ellipsis Menu of Projects
- Ellipsis Menu of Project Categories
- ADD Button in Add New Project Modal
- IMPORT Project Button
- Member Select in Add New Project Modal
- Category Select in Add New Project Modal
- Name Input in Add New Project Modal
- Project Search in Project Listing
1. Go to branch `feature/FOUR-10284` in `processmaker`.
2. Go to branch `feature/FOUR-10284` in `package-projects`.
3. Go to each of the elements listed above. Inspect each element to ensure it has a `data-cy` or `data-test` attribute.
ci:next
[FOUR-10284]: https://processmaker.atlassian.net/browse/FOUR-10284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> FOUR-10284 | We Need ‘data-test’ or ‘data-cy’ Attributes on Components

ProcessMaker/Contracts/WorkflowManagerInterface.php, ProcessMaker/Nayra/Managers/WorkflowManagerDefault.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php
When a request is started using webentry when it is started with the new engine it is started in background. This could cause a collition because in the same controller action the data of the request is changed after the request was started.
- Update the request data (change the file uploaded ids) before to send the startEvent to the engine.
Run the attached process as a webentry.
- Upload a file
- Submit the form
- See the interstitial get properly the next screen.
[webentry.zip](https://github.com/ProcessMaker/screen-builder/files/12501628/webentry.zip)
=> Fix data update before to start a webentry

ProcessMaker/ImportExport/Exporters/ScriptExecutorExporter.php
An issue arises when the CI executes `php artisan package-pm-blocks:sync-pm-blocks` and this action triggers an error. Furthermore, if the UUID does not exist within the `pm_blocks_category`, it results in another error.
- Checkout to the next branch on Core, PmBlocks and Package Projects
- Install the PmBlocks Package. (uuid error may occur at this time)
- Sync the PmBlocks `php artisan package-pm-blocks:sync-pm-blocks`
- Package: Create a migration that will check if the uuid of the category exists.
- Core: Add a conditional within the ScriptExecutorExporter that will check for an admin user if an authenticated user doesn’t exist.
How To Test
- Check out the following branches in Core, Pm Blocks and and Package Projects.
-- bugfix/FOUR-10388
- Install the Pm Blocks package
- Install the …
=> FOUR-10388: CI Unit Test failing when we sync-pm-blocks 

ProcessMaker/Models/FormalExpression.php
Required to extend the FormalExpression
- https://processmaker.atlassian.net/browse/FOUR-8067
=> FOUR-8067 Run Test

resources/js/components/shared/AddToProjectModal.vue, resources/js/processes/components/ProcessesListing.vue, resources/js/processes/screens/components/ScreenListing.vue, resources/js/processes/scripts/components/ScriptListing.vue
Ticket: [FOUR-10236](https://processmaker.atlassian.net/browse/FOUR-10236)
In the Assign Asset Modal, we need to provide users with additional information for better context and usability:
1. Project Name: Display the name of the project to which the asset is being added. This ensures users can easily identify the destination project.
2. Copy Asset Button: Include a "Copy Asset" button within the modal. This button empowers users to duplicate the selected asset and add it to the project efficiently.
1. Go to branch `task/FOUR-10236` in `processmaker`.
2. Go to branch `next` in `package-projects`. Install the package.
3. Go to branch `task/FOUR-10236` in `package-decision-engine`. Install the package.
4. Go to branch `task/FOUR-10236` in `package-data-sources`. Install the package.
5. Go …
=> FOUR-10236 | Ellipsis Menu Action: Enhance Assign Asset Modal Information

ProcessMaker/Repositories/ExecutionInstanceRepository.php
Signal was not catch because the collaboration_id was not saved in the second process request.
- Save the collaboration_id when the request is created.
- Run the attached request.
- Complete the task A, then D, then C
[tcp4-2158_verify_event_based_gateway_conditional_and_message_event.zip](https://github.com/ProcessMaker/processmaker/files/12528912/tcp4-2158_verify_event_based_gateway_conditional_and_message_event.zip)
**Password**: 12345678
- https://processmaker.atlassian.net/browse/FOUR-10322
=> FOUR-10322: Save collaboration id reference

routes/channels.php
A webentry interstitial page tries to connect to the created request after a submit, but sometimes it gets denied this is because the channel allowing access to the requester (the user or anon user of a webentry)
This was working on the previous engine because it synchronously creates the start event token that brings access indirectly to the requester.
- Give access to the Requester User to the ProcessRequest channel
- [FOUR-10110](https://processmaker.atlassian.net/browse/FOUR-10110)
[FOUR-10110]: https://processmaker.atlassian.net/browse/FOUR-10110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add channel access to requester

resources/js/components/shared/DownloadSvgButton.vue, resources/views/processes/modeler/inflight-generative-ai.blade.php
- Log in
- Go to designer > processes
- Click on + process button
- Open the inspector in the browser
- go to Network tab
- Add a throttle (slow connection 3G)
- Click on new process using AI
- Add a prompt
- Click on generate
- Added a watcher to detect if iframe and modeler were correctly loaded and after that emit the parsed event.
- Try all the uses cases with slow connections and fast connections
- Try reloading the AI process modeler with history, the download button should show
- Try reloading the AI process modeler without history, and generate a process. After generate the process the download button should show.
- Try downloading the file, the image should contain the model image
- [FOUR-10378](https://processmaker.atlassian.net/browse/FOUR-10378)
- …
=> Bugfix/FOUR-10378: Download button does not show when you open the first time in an incognito

ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php
When Nayra-docker is enabled, the requests that work with actions-by-email do not finish executing since the responses do not arrive correctly.
Change the instance of id to use uuid
require
https://github.com/ProcessMaker/nayra-docker/pull/23
https://github.com/ProcessMaker/package-actions-by-email/pull/119
You need nayra-docker
1. create a process  with  ABE  or import process of ticket
2. Start a new  request 
3. open the mail
4. reply
5. return to processmaker
6. open the request
- [FOUR-10307](https://processmaker.atlassian.net/browse/FOUR-10307)
[FOUR-10307]: https://processmaker.atlassian.net/browse/FOUR-10307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The task that comes after ABE does not arrive

resources/js/components/shared/EllipsisMenu.vue, resources/js/processes/translations/components/ProcessTranslationListing.vue
- Create a simple process with some screens
- Close the process and search it
- Click on the options button of the process
- Click on Configure
- Click on Translations tab
- Click on +Translation
- Select a language and Translate Process
**Issue explanation**
The problem is that we have chunks per each screen and we have a progress per chunk (not updating in real time the progress only when each chunk finish) and we have a partial progress update for the streaming responses (this makes the real time progress).
If we have multiple workers, using this configuration:
```
PM4_HORIZON_SUPERVISOR_BPMN_BALANCE=auto
PM4_HORIZON_SUPERVISOR_BPMN_MAX_PROCESSES=12
PM4_HORIZON_SUPERVISOR_1_BALANCE=auto
PM4_HORIZON_SUPERVISOR_1_MAX_PROCESSES=12 …
```
=> Bugfix/FOUR-10371: Percentage number is going up an down

resources/js/admin/settings/components/SettingsListing.vue
This PR introduces a 'No Data' message feature, enhancing the user experience in the CDATA package. The 'No Data' message is now customizable for various settings tabs, allowing for more flexibility.
To configure the 'No Data' message for a settings tab, simply follow this example:
```
Setting::firstOrCreate(['key' => 'cdata.no_data_component'], [
'format' => 'no-data',
'group' => self::SETTINGS_GROUP,
'config' => false,
'name' => 'Configure External Integrations',
'helper' => 'No external integrations are currently configured. To set up an external integration, click the "Add Driver" button.',
'hidden' => false,
]);
```
When the setting format is set to 'no-data', this PR implements a user-friendly behavior: it hides the settings table and, instead, displays the configured message and …
=> Add implementation for displaying a 'no data' message in settings

ProcessMaker/Models/Process.php
The dot in the "_parent.variable" statement was not evaluated correctly
- Change to dot notation to evaluate assign
Steps in ticket
- [FOUR-10410](https://processmaker.atlassian.net/browse/FOUR-10410)
[FOUR-10410]: https://processmaker.atlassian.net/browse/FOUR-10410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Parallel multiinstance with process variable assignment rule does not work and displays errors on screen

resources/js/processes/modeler/components/inspector/ScreenSelect.vue, resources/js/processes/modeler/components/inspector/ScriptSelect.vue, resources/js/processes/screens/components/CreateScreenModal.vue, resources/js/processes/scripts/components/CreateScriptModal.vue
- Made the `load` function to be async and did a try-catch.
- Setting the data variable instead of using emitters, the parent was listening and setting the value to multiple components 🙄 
- Checking if the query params for `created` was present to sent the broadcast message along the wire
- https://processmaker.atlassian.net/browse/FOUR-10204
- https://processmaker.atlassian.net/browse/FOUR-10225
- https://processmaker.atlassian.net/browse/FOUR-10565
ci:next
ci:deploy
=> FOUR-10501 Asset Quick Create QA Observations

ProcessMaker/Http/Resources/Task.php, ProcessMaker/Traits/ProcessTrait.php
Add a method to get the human tasks of a process required by package testing.
Run a process test and select a starting step.
- https://processmaker.atlassian.net/browse/FOUR-8069
ci:next
=> FOUR-8069 Starting Step

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/views/processes/modeler/index.blade.php, resources/views/processes/modeler/inflight.blade.php
The listing of the PMBLocks took too long and caused problems in the events to start the modeler correctly.
- The call to load the PMBlock listing is made in the modeler controller to be loaded before starting the modeler and saved in a global variable.
- Log in
- create a new  process
- create  a  PMBlocks  in process
- save the  process
- refresh the screen two or more times
note: Modeler and in-flight
- [FOUR-9860](https://processmaker.atlassian.net/browse/FOUR-9860)
depends
https://github.com/ProcessMaker/package-pm-blocks/pull/87
[FOUR-9860]: https://processmaker.atlassian.net/browse/FOUR-9860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The process in the modeler is distorted when it contains blocks and we refresh the browser

resources/js/requests/components/RequestsListing.vue
1 - use the AI search bar with any query (i.e show all completed requests) and submit
2  - click on the resulting AI link into Requests
3-  notice how the list is not actually filtered, even though the search bar does have the right pmql that matches the needed search
4 - click on the pmql search and hit ‘Enter’
5 - only then does the search update to match the original request.
See video in the FOUR ticket
Expected behavior is this should render directly 
- In the network tab in the browser inspector, two requests were triggered, one by default in vuetable and another in a watcher for the pmql filters. The pmql filters request was ending before than the default request triggered by the datatable. To avoid this race problem a cancel request was added if a new request is triggered. …
=> Bugfix/FOUR-10835: AI Search results not rendering correctly - query needs to be resubmitted

ProcessMaker/Models/ProcessRequestToken.php
- Steps to Reproduce:
- login to Processmaker
- Go to TASK and create a saved search (example for in progress and complete requests).
- Choose the saved search, and perform a simple search.
It does not find anything always shows empty no matter what the search is.
Depending on the search, it should find the parameter in any field.
- Search in process request data and by process request name in the scopeFilter for tasks.
https://github.com/ProcessMaker/processmaker/assets/90727999/09daeee6-69c9-4bce-8e6a-abee869d002f
https://github.com/ProcessMaker/processmaker/assets/90727999/64c9fbbb-0c80-47f2-9b24-f87140b2192c
- Go to tasks and search for some task using the request name
- Go to tasks and search for some task using the …
=> Bugfix/FOUR-10009: Saved Search not returning results for Tasks

ProcessMaker/Http/Controllers/Process/ModelerController.php
The per_page parameter was not passed in the response pager.
- add the per_page parameter in the pager
review the PMBlock list in the modeler with more than 10 records
- [FOUR-10863](https://processmaker.atlassian.net/browse/FOUR-10863)
[FOUR-10863]: https://processmaker.atlassian.net/browse/FOUR-10863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:deploy
=> I can only see the first 10 PMblock created in the modeler

resources/js/components/shared/ProjectSelect.vue
The Project select list currently lacks internal search functionality, which makes it challenging for users to find specific projects efficiently. This PR addresses this issue by implementing internal search capabilities in the multiselect component.
- Enable internal search functionality for the Project
1. Ensure you have multiple projects configured
2. Create a process or update an existing process
3. Within the Project select list search for a project
The search properly filters the listed Projects based on the inputed value.
- [observation/FOUR-10209](https://processmaker.atlassian.net/browse/FOUR-10209)
ci:next
=> Enable Internal Search within Project Select list

resources/js/app-layout.js
1.) Navigate to Requests/My requests.
2.) Refresh page
Actual result: Sorry API Failed to Load message displayed when refreshing requests view
https://github.com/ProcessMaker/processmaker/assets/90727999/dedfa229-b297-40dc-8e5b-8877fc0acb2e
Expected result: No data Available message if no data and data if we have it as result.
- Do not emit api client error if is request canceled
https://github.com/ProcessMaker/processmaker/assets/90727999/fe255dd9-7021-42fc-97b4-9239c003baed
- [FOUR-10886](https://processmaker.atlassian.net/browse/FOUR-10886)
[FOUR-10886]: https://processmaker.atlassian.net/browse/FOUR-10886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:deploy
=> FOUR-10886: Sorry API Failed to Load message displayed when refreshing requests view

ProcessMaker/ScriptRunners/Base.php, config/app.php
The [docker-executor-cdata](https://github.com/ProcessMaker/docker-executor-cdata) requires the `linux/amd64` platform in order to function correctly due to CData's support for AMD64 but not ARM64. This means that on Apple Silicon macOS systems, the docker executor returns a warning message when executing even though Rosetta support enables it to function correctly.
We are adding the new .env variable `PROCESSMAKER_SCRIPTS_DOCKER_PARAMS` to allow for custom parameters to be sent to the Docker executor at runtime. This enables us to add the param `--platform=linux/amd64` in order to prevent the warning message if we are running on an Apple Silicon macOS system.
Add the following to your .env file:
`PROCESSMAKER_SCRIPTS_DOCKER_PARAMS="--platform=linux/amd64"` …
=> [FOUR-10496] Add new option for custom Docker params

ProcessMaker/ImportExport/Exporters/ScriptExecutorExporter.php
The command to synchronize the PMBlocks by default was not executed because the user was not defined when it was executed through the console.
- Add validation user when building script executor
execute the command `php artisan package-pm-blocks:sync-pm-blocks`
and review the list of PMBlock default
- [FOUR-10911](https://processmaker.atlassian.net/browse/FOUR-10911)
[FOUR-10911]: https://processmaker.atlassian.net/browse/FOUR-10911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Default blocks are not shown

ProcessMaker/Http/Controllers/Auth/LoginController.php
An error is appears when the package does not exist
- Validate if the package exist
- FOUR-8501
ci:deploy
ci:next
=> bugfix/FOUR-8501: Validate if the package exist

ProcessMaker/Http/Controllers/RequestController.php
Create scenarios from a completed request
Actual behavior:
Is not possible create a scenario from a completed request
Add the feature in completed request screen
FOUR-10735
=> FOUR-10735 The create scenario button is missing from a completed request

ProcessMaker/Traits/ProjectAssetTrait.php
This PR addresses an issue encountered when selecting multiple projects for an asset (process, screens, etc.).
- Error in the foreach loop due to attempting to iterate over a non-array.
- Absence of `created_at` and `modified_at` values during record insertion.
- Corrected the foreach loop to handle non-array scenarios gracefully.
- Added the necessary code to ensure `created_at` and `modified_at` values are correctly set during record insertion.
1. Ensure you have multiple Projects created.
2. Assign multiple projects to an asset.
3. Select 'Save'.
The Asset should be successfully assigned to ALL selected projects without any errors.
- Ticket [FOUR-10945](https://processmaker.atlassian.net/browse/FOUR-10945)
ci:next
[FOUR-10945]: …
=> Resolve Error and Improve Data Handling in Asset Assignment

resources/js/components/shared/ProjectSelect.vue
This PR addresses an issue encountered when searching for projects in the Project Select list. Currently, only the first 10 projects are returned during the search. This limitation arises from the default setting of the `per_page` parameter, which is set to 10. 
To resolve this issue and improve the user experience, this PR increases the `per_page` parameter value from its default of 10 to 1000. This change ensures that users can see a more comprehensive list of projects when performing searches.
1. Ensure that your development environment contains more than 10 projects.
2. Access an Asset designer, such as Processes, Screens, etc.
3. Within the Project Select list, initiate a search for projects.
When searching, all projects should be visible, allowing for a more …
=> Increase Per Page for Project Search

ProcessMaker/Http/Controllers/Designer/DesignerController.php, ProcessMaker/Http/Middleware/GenerateMenus.php
As part of ticket FOUR-10303 this PR enables the 'Designer' link for users who have Project permissions.
- Include `view-projects` permission to enable the 'Designer' link in the top menu
1. Ensure you have the Projects package installed using this [PR](https://github.com/ProcessMaker/package-projects/pull/32)
2. Create a new user.
3. Confirm that the user has Project permissions enabled by default.
4. Log in as the newly created user.
5. Ensure that the 'Designer' tab is visible.
- [FOUR-10303](https://processmaker.atlassian.net/browse/FOUR-10303)
- [Projects PR](https://github.com/ProcessMaker/package-projects/pull/32)
ci:next
ci:package-projects:task/FOUR-10303
[FOUR-10303]: https://processmaker.atlassian.net/browse/FOUR-10303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> Resolve Project Permissions and UI Updates

ProcessMaker/Http/Controllers/Api/ProcessController.php, resources/js/processes/components/CreateProcessModal.vue, resources/js/processes/modeler/components/ModelerApp.vue, resources/js/processes/scripts/components/CorneaTab.vue, routes/api.php
**Figma**
https://www.figma.com/file/HPlbIAFk5pPLvHX6vyUN3K/Fall-23?type=design&node-id=1-2&mode=design&t=FcADuhMGTJxndieK-0
**PI Planning document**
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3150675969/Ai+in+Modeler+-+PI+Document
**Epic**
https://processmaker.atlassian.net/browse/FOUR-9674
**Related PR's**
- [modeler](https://github.com/ProcessMaker/modeler/pull/1682)
- [package-ai](https://github.com/ProcessMaker/package-ai/pull/28)
- [core](https://github.com/ProcessMaker/processmaker/pull/5399)
- [package-versions](https://github.com/ProcessMaker/package-versions/pull/72)
- [screen-builder](https://github.com/ProcessMaker/screen-builder/pull/1449)
ci:next
=> Epic/FOUR-9674: AI in modeler

resources/js/components/requests/card.vue, resources/js/components/requests/requestModal.vue
We require a new attribute data-test in `category name`, `process name` and `start button`.
Please see details in the ticket 
https://processmaker.atlassian.net/browse/FOUR-10916
- Added data-test attributes in new request modal.
- Open the inspector and be sure the attributes are there:
List of attributes added:
- Search input
- Search button
- Category name
- Category count
- Process name
- Process show detail button
- Process detail
- Process start request button
- Pagination
- [FOUR-10916](https://processmaker.atlassian.net/browse/FOUR-10916)
[FOUR-10916]: https://processmaker.atlassian.net/browse/FOUR-10916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:next
=> Task/FOUR-10916: data-cy Attribute Needed For Selectors

ProcessMaker/Http/Controllers/Auth/LoginController.php, config/app.php
Login Page configuration for design
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3196354602/Login+Screen+Redo
- Set a variable in order to define if the login can change
We nned to define the view(blade) to use for the login page
```
LOGIN_VIEW = 'auth.mobile'
```
This value needs to reflect in the login page
- https://processmaker.atlassian.net/browse/FOUR-10749
ci:next
=> feature/FOUR-10749: Login Page configuration for design

resources/js/bootstrap.js, resources/js/processes/screen-builder/components/form/file-upload.vue
The primary issue is when a request participant attempts to upload a file of a type not allowed in a form upload field where it is not allowed. The previous warning was "_File not allowed._" and has been updated to "_This file type is not accepted._".
Additionally, for the webentry warning message, the class of the notification (eg. "info", "danger") was being concatenated and used as a prefix for the warning message, changing it to "danger: File not allowed". The concatenation has been removed and only the update warning message ("_This file type is not accepted._") should appear.
Use this branch for core and the `feature/FOUR-10833`[ branch for screen-builder](https://github.com/ProcessMaker/screen-builder/tree/feature/FOUR-10833).
1.  Import the [attached …
=> FOUR-10833: Update warning messages for file upload(s)

resources/js/components/shared/PmqlInputFilters.vue
This PR addresses a 500 error that occurs when selecting multiple members and categories in Project filtering.
1. Ensure you have multiple projects configured.
2. On the Project Listing page, click the 'Filter' button.
3. Add more than one selection for each of the available filters.
4. Verify that no errors occur during the selection process.
5. Confirm that the data returns correctly based on the applied filters.
- Ticket [FOUR-11013](https://processmaker.atlassian.net/browse/FOUR-11013)
[FOUR-11013]: https://processmaker.atlassian.net/browse/FOUR-11013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:next
=> Resolve 500 error when selecting multiple members and categories in Project filtering

resources/js/components/shared/PmqlInputFilters.vue
This PR addresses the issue where Project filters did not clear when selecting the 'Reset Filter' button.
- Modified the `resetFilter` method to include project filter variables, ensuring they are cleared when the 'Reset Filter' button is triggered.
1. Ensure you have multiple projects configured.
2. On the Projects listing page, select 'Filter.'
3. Fill out the available filters.
4. Select 'Reset Filter.'
5. Select 'Filter' again.
6. Ensure the filter values are reset.
- Ticket [FOUR-11011](https://processmaker.atlassian.net/browse/FOUR-11011)
ci:next
[FOUR-11011]: https://processmaker.atlassian.net/browse/FOUR-11011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clear project filters when 'Reset Filter' button is used

resources/js/Mobile/FilterMobile.vue, resources/lang/en.json
Request Filter option names, should have this names:
As Requester insted of Requested by Me.
As Participant insted of With me as Participant
- Update the labels related to the filters
- login from  mobile
- Review the filter related to the Request filter
- [FOUR](https://processmaker.atlassian.net/browse/FOUR-11057)
ci:deploy
ci:next
=> FOUR-11057: Request filter options names should be updated

ProcessMaker/Http/Controllers/AboutController.php, ProcessMaker/LicensedPackageManifest.php, ProcessMaker/Providers/LicenseServiceProvider.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, config/app.php, tests/Feature/LicenseTest.php
Base for implementing Licensing Product Integration
- Implement a LicenseServiceProvider.
- https://processmaker.atlassian.net/browse/FOUR-11055
ci:next
=> FOUR-11055 Base for implementing Licensing Product Integration

ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Models/Script.php
This PR addresses the need for enhanced search functionality within the Project Assets by implementing PMQL search for Scripts.
- Integrate ExtendedPMQL Trait into the Script modal to enable advanced querying capabilities.
- Implement PMQL input filtering within the Script Controller index method for streamlined search operations.
1. Create a new Project.
2. Access the 'Script' section through the + Asset button and perform a search.
3. Verify that the search results are accurately displayed and aligned with the search parameters.
- [FOUR-11145](https://processmaker.atlassian.net/browse/FOUR-11145)
- [Data Sources PR](https://github.com/ProcessMaker/package-data-sources/pull/333)
- [Decision Engine PR](https://github.com/ProcessMaker/package-decision-engine/pull/74)
ci:next …
=> Implement PMQL Search Functionality for Scripts within Project Assets

resources/js/components/shared/ellipsisMenuActions.js, resources/js/components/shared/screenNavigation.js
his PR addresses the issue by updating the screen action from 'remove-item' to 'remove-screen', ensuring method uniqueness and avoiding potential conflicts within the application.
- Renamed the screen action from 'remove-item' to 'remove-screen' in the corresponding code files.
1. Create a screen within the application.
2. Navigate to the Designer and locate the created screen.
3. Attempt to delete the screen using the 'remove-screen' action.
4. Confirm that the screen is successfully deleted from the application.
5. Create a new screen and a project.
6. Add the newly created screen to the project.
7. Access the project via the Designer, then select the specific project.
8. Attempt to delete the screen from within the project using the 'remove-screen' action.
9. Verify that the screen is …
=> Refactor 'remove-item' Screen Action to Ensure Method Uniqueness

resources/js/components/shared/EllipsisMenu.vue
This PR resolves the issue by modifying the 'filterActionsByPermission' function to consider 'Object' type permissions, ensuring the proper display of category ellipsis menus.
- Updated the 'filterActionsByPermission' function to incorporate 'Object' type permissions for accurate evaluation.
1. Confirm the visibility of all category ellipsis menu actions, including those for Screens, Scripts, Projects, and Processes.
2. Verify that all actions within the category ellipsis menus function correctly and perform the intended actions without any inconsistencies.
- [FOUR-11129](https://processmaker.atlassian.net/browse/FOUR-11129)
ci:next
[FOUR-11129]: https://processmaker.atlassian.net/browse/FOUR-11129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> Fix Category Ellipsis Display Issue by Refactoring 'filterActionsByPermission' for 'Object' Type Permissions

resources/js/processes/designer/Assets.vue
The text in each asset should be a Hover, because right now you have to click to open the options and click again to Close the option, and if you don’t close the Asset Options won’t look good:
- https://processmaker.atlassian.net/browse/FOUR-11108
ci:next
=> Feature/four 11108: Modify the HOVER in Default Welcome Screen

ProcessMaker/Console/Commands/ProcessMakerLicenseRemove.php, ProcessMaker/Console/Commands/ProcessMakerLicenseUpdate.php, tests/Feature/LicenseCommandsTest.php
License Artisan commands
- Implements license artisan commands:
- processmaker:license-update 
- processmaker:license-remove
To update a license:
```
php artisan processmaker:license-update /path/to/license.json
```
To remove the current license:
```
php artisan processmaker:license-remove
```
ci:next
=> FOUR-11071 License Artisan commands

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Models/ProcessRequestToken.php
Add a new Filter overdue in the API  "/tasks"
- We need to implement a new filter over the API `/tasks` in order to filter the overdue
- 
a new parameter was added overdue=true in order to show only the overdue request
`api/1.0/tasks?page=1&include=process,processRequest,processRequest.user,user,data&pmql=(user_id = 1) AND (status = "In Progress")&per_page=10&order_by=ID&order_direction=DESC&overdue=true`
- https://processmaker.atlassian.net/browse/FOUR-11200
ci:next
=> feature/FOUR-1200: Add a new Filter overdue in the API  "/tasks"

ProcessMaker/Traits/ProjectAssetTrait.php
This PR resolves an issue that occurs when creating a script without selecting a project. The problem was attributed to the ProjectAssetTrait running on an empty array value. The solution involves checking if the $projectId variable in the trait is empty before proceeding.
- Implemented a check for the $projectId variable in the ProjectAssetTrait to prevent errors when the array value is empty.
1. Create a script within the Designer > Script page.
2. Do not select any project in the Create Modal.
3. Ensure that no errors occur during the script creation process.
4. Verify that if a project is selected, the script is successfully added to the chosen project.
-[ FOUR-11210](https://processmaker.atlassian.net/browse/FOUR-11210)
ci:next
=> Fix Issue with Script Creation Without Project Selection

resources/js/bootstrap.js
- Create a process with elements like:
- Start Event → Task Form → End Event
- Create a Requests
- Go to the Overview tab
Current Behavior 
The Overview tab does not show the status of the process (see the screenshot in the ticket)
Expected Behavior 
The Overview should show the status of the process like Version 4.8.0+next-20231016 (Build #6cc2498b)
- In inflight modeler we don't have the user, so we can't access to userfullName.content userAvatar.content Added the ? operator to handle this behavior.
https://github.com/ProcessMaker/processmaker/assets/90727999/8a12bb78-f86d-46a0-af7f-0c9011830ce0
- [FOUR-11205](https://processmaker.atlassian.net/browse/FOUR-11205)
ci:next
[FOUR-11205]: https://processmaker.atlassian.net/browse/FOUR-11205?atlOrigin=ey …
=> Bugfix/FOUR-11205: Overview is not working in requests

ProcessMaker/Http/Controllers/HomeController.php
Switch to mobile view does not work when the Default Home is enable
- Configure a Home page for a user using dynamic-ui
- Loging using mobile browser the home page defined is showed
- Loging using desktop browser the home page defined is showed
if the HomePage was defined this will show only if is not Mobile browser
- Loging using mobile browser the mobile view needs to show
- Loging using desktop browser the home page defined needs to show
- Configure a Home page for a user using dynamic-ui
- Loging using mobile browser the home page defined is showed
- Loging using desktop browser the home page defined is showed
- https://processmaker.atlassian.net/browse/FOUR-11126
ci:deploy
ci:next
=> bugfix/FOUR-11126: Switch to mobile view does not work when the Default Home is enable

ProcessMaker/Http/Controllers/Designer/DesignerController.php
-  Create a user with one of the following permissions  `view-processes|view-process-categories|view-scripts|view-screens|view-environment_variables|view-projects`
- The user can to see the Welcome Designer
- If the user can see the designer can see the Welcome Designer
Create a user with one permissions 
Review if can see the Welcome Designer
- https://processmaker.atlassian.net/browse/FOUR-11191
ci:deploy
ci:next
=> bugfix/FOUR-11191: View Project Permission

.github/workflows/deploy-pm4.yml, composer.json, database/seeders/ScriptExecutorSeeder.php
The CData executor needs to be installed.
Add a conditional to change the key from `sql` to `cdata` if it is being installed.
ci:next
ci:package-cdata:FOUR-11225
ci:deploy
=> [FOUR-11225] Add CData executor to Script Executor Seeder

resources/views/auth/newLogin.blade.php
As a PM user I would like to have the login page for mobile as the one we have in desktop, so we can relate
- Hide the text when is mobile
Login using Desktop browser the text will showed
Login using Mobile browser the text will hide
- https://processmaker.atlassian.net/browse/FOUR-11039
ci:deploy
ci:next
=> FOUR-11039: Hide the text when is mobile

ProcessMaker/Http/Controllers/AboutController.php
- Have the micro service down
- Go to about page
If micro service is down, the request to get the version failed causing the entire about page can’t load
if microservice is down the entire about screen should work normally
- Catch the error and show an offline message.
https://github.com/ProcessMaker/processmaker/assets/90727999/dff0a79a-81fe-4853-a171-27d5287a1f22
- [FOUR-11248](https://processmaker.atlassian.net/browse/FOUR-11248)
ci:next
[FOUR-11248]: https://processmaker.atlassian.net/browse/FOUR-11248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-11248: About page can't load if micro service is down

resources/views/processes/index.blade.php
- List the changes you've introduced to solve the issue.The link of Breadcrumb "Designer" in Processes was modified to link Designer Wlecome Screen
Move to Processes, click on Designer link. Designer Welcome screen should be loaded.
- https://processmaker.atlassian.net/browse/FOUR-11279
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-11279: Re Link the Designer from breadcrumb to the designer Welcome Screen

ProcessMaker/Templates/ProcessTemplate.php
Ticket: [FOUR-11165](https://processmaker.atlassian.net/browse/FOUR-11165)
When creating a Process from a Template, if a Project is selected, the Process is not added to the selected Project.
1. Go to branch `observation/FOUR-11165` in `processmaker`.
2. Have a Project and Template created in your environment.
3. Go Designer → +PROCESS. Select a template to create your Process from.
4. In the Create Process Model, add your Process to a Project.
- You can also test adding your Process to multiple Projects.
5. Create the Process.
6. Ensure that the Process was added to the correct Projects.
ci:next
ci:deploy
[FOUR-11165]: https://processmaker.atlassian.net/browse/FOUR-11165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-111165 | When Creating a Process from a Template, the Project Assignment Does Not Work As Expected

resources/js/processes/scripts/components/ScriptEditor.vue
- Log in
- Click on Designer
- Click on Scripts 
- Create a new  script 
- Click on Publish
- Add a flag to detect if redirect is needed or not. Removed the condition that checks if processId is present
- [FOUR-10874](https://processmaker.atlassian.net/browse/FOUR-10874)
ci:next
[FOUR-10874]: https://processmaker.atlassian.net/browse/FOUR-10874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-10874: It is not possible to save a created script

resources/js/admin/settings/components/SettingDriverAuthorization.vue
When clicking on the "Authorize" button of a CData driver, a 500 error appears.
- The error is related to the absence of RTK values in the .env file.
- Now a custom error is displayed correctly instead of the generic 500 error.
- Test authorizing a CData driver on the QA server.
- [FOUR-11230](https://processmaker.atlassian.net/browse/FOUR-11230)
- [Package CData PR](https://github.com/ProcessMaker/package-cdata/pull/16)
ci:next
ci:package-cdata:observation/FOUR-11230
ci:deploy
[FOUR-11230]: https://processmaker.atlassian.net/browse/FOUR-11230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-11230 - it is not possible to make the external connection with github

resources/js/processes/scripts/components/ScriptEditor.vue
In Script Editor, whenever a user wants to Generate Script from Text, a modal preview of where the code will be inserted is shown (normally where the cursor was left). This behavior should be the same for whenever the user wants to regenerate code using another prompt.
Set the cursor selection on the diff editor's original editor to the last cursor position of the previous editor. This was done whenever the variable `isDiffEditor` is set.
1. Login as admin
2. Go to Designer > Scripts
3. Click on +Script
4. Set the information required and save
5. Set any code on the script canvas
6. Click on another line that is not the first on the canvas
7. Click on AI Assistant
8. Click on Generate Script From Text
9. Set a Description and Generate
10. Click on Confirm
11. Edit the description and …
=> bugfix/FOUR-10942: Fixed cursor resetting on diff editor

ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Templates/ProcessTemplate.php
This PR resolves a 500 error encountered when attempting to create a process from a template. The issue was traced to the removal of the `comment_configurations` table from the database. As the template exports reference the `comment_configurations`, this caused the error. The solution involved unsetting the `comment_configuration` asset in the Template payload, enabling the template to be imported and saved as a process.
- Implemented a check for the asset model type. If it is a CommentConfiguration instance, the asset is removed, allowing the importing process to continue seamlessly.
1. Ensure you have the latest comments package and run migrations. 
2. Attempt to create a process from a default template.
3. Confirm that the process creation no longer triggers a 500 error.
4. Verify …
=> Fix 500 Error When Creating Process from Template

ProcessMaker/Http/Controllers/AboutController.php, ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php, resources/lang/en.json, resources/lang/es.json, resources/views/about/index.blade.php
When kafka connection fails, it throws an server error.
- Catch the exception and show the Nayra microservice waiting for connection.
Go to the about page. When kafka connection fails it shows Nayra is trying to connect.
- https://processmaker.atlassian.net/browse/FOUR-11316
ci:next
=> FOUR-11316 Catch kafka connection problem in about page

ProcessMaker/Http/Controllers/Api/ProcessController.php, routes/api.php
This PR enables the process duplication endpoint and controller, allowing for the duplication of all data, including the bpmn, from one process to another.
- Enabled the process duplication endpoint and controller to facilitate the copying of all data, including the bpmn, from a source process to a target process.
1. Ensure that a project is available with a process type asset.
2. Go to the project assets listing page.
3. From the ellipsis menu for the process, select 'Copy to Project'.
4. Fill out the form with and without selecting a process manager.
5. Submit the form.
6. Confirm that the process is created and navigate back to the project, ensuring that the process is correctly assigned to the project.
- FOUR-11128
- [Projects …
=> Enable Process Duplication Endpoint and Controller

resources/js/admin/settings/components/SettingDriverAuthorization.vue
We get errors in the console when deleting an external integration item.
- Adjusted the 'setting' prop in the component to accept 'null' as a default value, ensuring compatibility with possible prop values.
https://github.com/ProcessMaker/processmaker/assets/90741874/f2fe54c4-3ba5-41e6-9752-435527b60867
1. Log in 
2. Go to Admin
3. Click on Settings
4. Click on External integration
5. Add a new item
6. Delete the item
- [FOUR-11337](https://processmaker.atlassian.net/browse/FOUR-11337)
ci:next
ci:deploy
[FOUR-11337]: https://processmaker.atlassian.net/browse/FOUR-11337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-11337 - Console errors when deleting an external integration item

ProcessMaker/ImportExport/Exporters/ExporterBase.php
1.Login in the server https://next-qa.processmaker.net/
2.Go to process
3.Import to process
[tc-53931_verify_that_a_screen_containing_nested_screen_and_loop_is_imported (1).json](https://github.com/ProcessMaker/processmaker/files/13178342/tc-53931_verify_that_a_screen_containing_nested_screen_and_loop_is_imported.1.json)
- The table comment_configurations was removed [in this PR](https://github.com/ProcessMaker/processmaker/pull/5237) because is no longer needed. Verify if table exists, if not return a null model.
https://github.com/ProcessMaker/processmaker/assets/90727999/781a4af2-1a27-492a-b10a-2722f486f18f
- [FOUR-11320](https://processmaker.atlassian.net/browse/FOUR-11320)
ci:next
ci:deploy
[FOUR-11320]: …
=> Bugfix/FOUR-11320: Server error when importing a process

ProcessMaker/ImportExport/Exporters/ExporterBase.php
When a PMblock is exported, the process has assigned the category Uncategorized, and also the process is type template.
- Verify when the process is template also has a category Uncategorized.
- Create a process containing a script ( the process should have a ProcessCategory of Uncategorized.)
- With the previous process create a PmBlock.
- Export the PmBlock
- Go to Designer--PmBlock
- Import the PmBlock
- [FOUR-11201](https://processmaker.atlassian.net/browse/FOUR-11201)
depends
https://github.com/ProcessMaker/package-pm-blocks/pull/94
ci:next
ci:package-pm-blocks:bugfix/FOUR-11201
ci:deploy
[FOUR-11006]: https://processmaker.atlassian.net/browse/FOUR-11006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-11201]: …
=> Verify tag uncategorize

ProcessMaker/Exception/HttpResponseException.php
Since php 8.2 functions declaration must include the exact return type of the interfaces.
- Fix class declaration compatibility
- Create a data source and test it in the DS designer
- Then include it in a process
- https://processmaker.atlassian.net/browse/FOUR-11182
For testing requires: https://github.com/ProcessMaker/nayra-docker/pull/29
ci:next
=> FOUR-11182 Fix class declaration compatibility

ProcessMaker/ImportExport/Exporters/ExporterBase.php
When a PMblock is exported, the process has assigned the category Uncategorized, and also the process is type template.
- Verify when the process is template also has a category Uncategorized.
- Create a process containing a script ( the process should have a ProcessCategory of Uncategorized.)
- With the previous process create a PmBlock.
- Export the PmBlock
- Go to Designer--PmBlock
- Import the PmBlock
- [FOUR-11006](https://processmaker.atlassian.net/browse/FOUR-11006)
depends
https://github.com/ProcessMaker/package-pm-blocks/pull/93
ci:package-pm-blocks:bugfix/FOUR-11006
ci:deploy
[FOUR-11006]: https://processmaker.atlassian.net/browse/FOUR-11006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Error 500 import PmBlock with script task in diferent versions

ProcessMaker/Http/Controllers/Auth/LoginController.php
- Have the last version of next processmaker:next-fall
- Have the last version of next package-auth:develop
- The package-auth from develop (This does not have the const PM_LOGIN SSO_DEFAULT_LOGIN defined)
- The following error is showing
- Validate if the const ProcessMaker\Http\Controllers\Auth\AuthDefaultSeeder::PM_LOGIN  and ProcessMaker\Http\Controllers\Auth\AuthDefaultSeeder::SSO_DEFAULT_LOGIN exist 
- Have the last version of next processmaker:next-fall
- Have the last version of next package-auth:develop
- The package-auth from develop (This does not have the const PM_LOGIN SSO_DEFAULT_LOGIN defined)
- The following error is showing
- https://processmaker.atlassian.net/browse/FOUR-11350
ci:deploy
ci:next
=> FOUR-11350: Validate if the const PM_LOGIN exist

ProcessMaker/Http/Controllers/HomeController.php, ProcessMaker/Http/Middleware/GenerateMenus.php
Add **Home** menu in platform
- We need to add a new menu HOME
- This new menu needs to show the information related to the Dashboards
Login and review the Menu
- https://processmaker.atlassian.net/browse/FOUR-11282
ci:deploy
ci:next
ci:package-dynamic-ui:feature/FOUR-11282
=> FOUR-11282: Add Home menu in platform

resources/lang/en/validation.php
`alpha_spaces` validation label was lost after laravel upgrade.
- Check if there was additional labels removed in the file validations.php. There were multiple changes required by the next version of laravel, but only `alpha_spaces`.
- Restored label `alpha_spaces` in validations.php
- Go to decisions table.
- Create a new table
- Put `!` on name and description
- Submit
- Now will see the proper label
- https://processmaker.atlassian.net/browse/FOUR-11117
ci:next
=> FOUR-11117 Add missing translation

ProcessMaker/Http/Controllers/HomeController.php, ProcessMaker/Http/Middleware/GenerateMenus.php
Login mobile is given an error with Home
- If is mobile redirect to **request**
- If is web and the package dynamic exist redirect to **home**
- If is web and the package dynamic does exist redirect to **request**
- Login usign mobile
- Login using desktop
- https://processmaker.atlassian.net/browse/FOUR-11364
ci:deploy
ci:next
=> bugfix/FOUR-11364: Login mobile is given an error with Home

ProcessMaker/ImportExport/Exporters/ExporterBase.php
This happens when you have many identical names (Process 1, Process 2, ..., Process 100), then you have a maximum of 100.
The maximum value has been increased.
test if any attribute is duplicated more than 100 times when importing/exporting
[FOUR-11314](https://processmaker.atlassian.net/browse/FOUR-11314)
[FOUR-11314]: https://processmaker.atlassian.net/browse/FOUR-11314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:next
=> Server Error when importing a process that contains multiple connectors

resources/js/components/shared/ProjectSelect.vue, resources/js/components/templates/SelectTemplateModal.vue, resources/js/processes/components/CreateProcessModal.vue, resources/js/processes/screens/components/CreateScreenModal.vue, resources/js/processes/scripts/components/CreateScriptModal.vue
Ticket: [FOUR-11302](https://processmaker.atlassian.net/browse/FOUR-11302)
When creating an asset from within a Project, the Project is not preselected within the asset creation modals.
1. Pass the ProjectId to the asset creation modals.
2. Add functionality to the ProjectSelect component to set the current Project if a ProjectId is provided.
1. Go to branch `observation/FOUR-11302` in `processmaker`.
2. Go to branch `observation/FOUR-11302` in `package-projects`.
3. Go to Designer → Projects. Open a Project.
4. Add different assets to the Project.
- Within the asset modals, the current Project should be preselected.
ci:next
ci:package-projects:observation/FOUR-11302
[FOUR-11302]: https://processmaker.atlassian.net/browse/FOUR-11302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> FOUR-11302 | When Creating an Asset from a Project, the Project Must be Preselected When Saving the Asset

ProcessMaker/Http/Controllers/Auth/LoginController.php
Login does not enable the redirect SSO login
- We need to get the default SSO defined
- Login into plataform
- Enable the Default SSO = Processmaker
- Login using mobile using PM login
- Change other Default SSO = google
- Login using mobile using google service
- https://processmaker.atlassian.net/browse/FOUR-11398
ci:deploy
ci:next
=> FOUR-11398

resources/js/processes/screen-builder/typeForm.js
- The new controls List Table and Analytics Chart are only Available on Screen Builder with type DISPLAY
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-11393: 

resources/js/components/Timeline.vue, resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
The time line of the requests is not shown
We added the timeline with the request and task LOGS 
Create a request of a process an complete the tasks to see the LOGS on the timeline
https://processmaker.atlassian.net/browse/FOUR-11328
ci:next
=> Observation/four 11328 - bring back missing timeline

ProcessMaker/Http/Controllers/Api/TemplateController.php, resources/js/components/templates/TemplateAssetTable.vue
When creating a Process from a Template, if the assets within the template already exist in the system, users are redirected to an Assets page where they can choose actions for each asset (Update | Keep Previous | Duplicate). However, the displayed categories for each asset do not correspond to the user's input, as each Category is specific to each asset. This inconsistency can lead to confusion, especially considering that multiple categories can belong to any of the assets, and there is currently no visibility regarding the parent assets.
- This PR addresses the issue by removing any displayed Categories within the TemplateAssetTable.
- Additionally, the Screen Interstitial has been removed from the import
- Navigate to Designer/Processes.
- Create a new Process using a template.
- …
=> FOUR-10935: Remove 'Categories' from the AssetTable in Templates V2

ProcessMaker/ImportExport/Exporters/TemplateExporter.php, ProcessMaker/Jobs/SyncDefaultTemplates.php
Categories were not exported and imported in Template.
- Add Export/Import categories for template.
-
In the template modify the category, then export template, and finally import it.
also test comanda `php artisan processmaker:sync-default-templates`
- [FOUR-11330](https://processmaker.atlassian.net/browse/FOUR-11330)
ci:next
[FOUR-11330]: https://processmaker.atlassian.net/browse/FOUR-11330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> "Select Not Found" error when we create a process from an imported template

ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, resources/js/components/shared/ImportExportIcons.js, resources/js/components/templates/TemplateAssetTable.vue, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php
Templates containing SubProcesses are not recognized by the TemplateAssetsTable, resulting in failed imports.
1. Create a Process that includes a SubProcess.
2. Generate a Template from the created Process.
3. Create a new Process using the generated Template.
The SubProcesses are not exported or imported, causing the TemplateAssetsTable to be unable to recognize them.
- Enable the Import/Export functionality for SubProcesses.
- Incorporate an identifiable icon for the SubProcess table.
1. Create a Process that includes a SubProcess.
2. Generate a Template from the created Process.
3. Create a new Process using the generated Template.
4. Verify that the AssetsTable displays the SubProcesses correctly.
5. Confirm that the SubProcess is successfully included in the new Process.
Please …
=> FOUR-10931: Allow SubProcesses to be Imported and Exported

ProcessMaker/Jobs/RunNayraScriptTask.php
Wrong error handling in run script job cause to return a wrong error message
- Fix error handler in run script.
- Create a process with an script with a syntax error.
- Run the process.
- When the script is executed it should show the script error
- https://processmaker.atlassian.net/browse/FOUR-11505
ci:next
=> FOUR-11505 Fix error handler in run script

resources/js/processes/screens/components/CreateScreenModal.vue, resources/js/processes/scripts/components/CreateScriptModal.vue
This PR introduces conditionals to prevent the updating of specific configurations when copying a Screen or Script from within a project. The changes include adding a disabled flag when the asset is in Copy mode, ensuring that certain configurations remain unchanged during the copy process.
- Integrated conditionals to disable specific configurations during the copy process for Screens and Scripts within a project.
1. Ensure that projects are properly configured within the system.
2. Confirm that both Scripts and Screens are included as assets within a project.
3. Navigate to the project asset listing page.
4. From the Ellipsis menu for both scripts and screens, select 'Copy to Project'.
5. Verify that when the Copy Asset modal appears for Screens, the 'Type' select list is disabled.
6. …
=> Implement Conditionals to Prevent Updating Specific Configurations when Copying Assets

ProcessMaker/Nayra/Repositories/PersistenceHandler.php, ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php
Comments subscriber is not being triggered.
- Trigger the missing events in nayra-service
- Call to the comments subscriber
- https://processmaker.atlassian.net/browse/FOUR-11529
ci:next
.
=> FOUR-11529 Trigger Comments Subscriber

resources/js/processes/modeler/components/inspector/ScreenSelect.vue, resources/js/processes/modeler/components/inspector/ScriptSelect.vue
- When a task has a screen assigned, the 'create new screen' option should not be displayed.
- Just display the Open Screen button
Please see https://processmaker.atlassian.net/browse/FOUR-11285
- Show quick create asset only if not selected a script/screen using v-if.
https://github.com/ProcessMaker/processmaker/assets/90727999/1cf6dd40-b399-4e9b-af30-b5684d0f142c
- Add a task and a script task
- Verify in task/script task inspector you can see the Create new [asset] + link
- Select an asset for task/script task in the inspector.  You should not see the Create new [asset] + link. S=You should only see the Open [asset] if an asset is selected in the list
- [FOUR-11285](https://processmaker.atlassian.net/browse/FOUR-11285)
- [Core …
=> Bugfix/FOUR-11285: When a task has a screen assigned, the 'create new screen' option should not be displayed.

babel.config.json, package-lock.json, package.json
ci:next
ci:deploy
ci:connector-docusign:coverage
ci:connector-idp:coverage
ci:connector-pdf-print:coverage
ci:connector-slack:coverage
ci:package-actions-by-email:coverage
ci:package-advanced-user-manager:coverage
ci:package-ai:coverage
ci:package-analytics-reporting:coverage
ci:package-auth:coverage
ci:package-cdata:coverage
ci:package-collections:coverage
ci:package-comments:coverage
ci:package-conversational-forms:coverage
ci:package-data-sources:coverage
ci:package-decision-engine:coverage
ci:package-dynamic-ui:coverage
ci:package-files:coverage
ci:package-googleplaces:coverage
ci:package-photo-video:coverage
ci:package-pm-blocks:coverage
ci:package-process-documenter:coverage
ci:package-process-optimization:coverage
ci:package-projects:coverage
ci:package-sentry:coverage …
=> [FOUR-11555] Add support for Cypress coverage reporting

resources/js/processes/screens/components/CreateScreenModal.vue
Steps to reproduce:
- Click on +Process
- Click on Build Your Own
- Drag and Drop the AI Generated control
- On Configuration of the control click on Screen Form Text
Current behavior:
When try to select the type of form there is no options
The option Form should be displayed## Solution
- FOUR-11696
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/5603)
- [Package-ai PR
](https://github.com/ProcessMaker/package-ai/pull/39)
ci:next
=> Bugfix/FOUR-11696: No option of type displayed on AI Modeler - Screen

resources/js/processes/scripts/components/ScriptPreview.vue
The Scripts Preview component can be edited.
- set component read-only
Review component in preview (Modeler)
- [FOUR-11558](https://processmaker.atlassian.net/browse/FOUR-11558)
ci:next
[FOUR-11558]: https://processmaker.atlassian.net/browse/FOUR-11558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set to readonly the ScriptPreview component.

resources/js/processes/screens/components/CreateScreenModal.vue
When navigating to the Projects page, an error is encountered in the console: 'Method "isQuickCreate" has already been defined as a data property.'
**Steps to reproduce**
1. Navigate to Designer
2. Navigate to the Projects page 
3. Click on a Project
4. Open the Console
You’ll notice an error within the Console 
- Remove redundant method within the CreateScreenModal
1. Navigate to Designer
2. Navigate to the Projects page 
3. Click on a Project
4. Open the Console
Please ensure that no errors appear within the Console 
ci:next
- Observation [FOUR-11635](https://processmaker.atlassian.net/browse/FOUR-11635)
[FOUR-11635]: https://processmaker.atlassian.net/browse/FOUR-11635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-11635: Remove redundant method

package-lock.json, resources/js/processes/modeler/components/inspector/ScreenSelect.vue, resources/js/processes/scripts/components/CreateScriptModal.vue
* package-lock.json updates
The Asset Quick Create was working on the first try but subsequent tries wouldn't work since the channel may be closing before hand.
Removal of the channel closure, in theory, the channel should close on window reload / navigation
- https://processmaker.atlassian.net/browse/FOUR-12193
- https://github.com/ProcessMaker/package-decision-engine/pull/87
ci:next
ci:deploy
ci:package-decision-engine:bugfix/FOUR-12193
=> FOUR-12193 Removed Broadcast channel to be closed

resources/js/admin/settings/components/cdata/ExcelConnectionProperties.vue
The SettingsFile, which is used for storing and exchanging auth tokens, is not created during the OAuth authorization flow of the Microsoft Excel CData driver.
As part of a long discussion with the CData team, it was ultimately identified that in this case, it is necessary to add a connection property: `AuthScheme=OAuth`.
- This solution adds the missing property, allowing the driver to authenticate and function as expected.
- Additionally, an unnecessary field has been removed since the driver now handles tokens automatically.
https://github.com/ProcessMaker/processmaker/assets/90741874/64cf83a9-c9e1-453e-9013-6e8e2d9b6efd
- You can manually test this by creating an OAuth app and authorizing it in the admin settings section.
- [FOUR-11296](https://processmaker.atlassian.net/browse/FOUR-11 …
=> FOUR-11296: CData Microsoft Excel Driver - Authorization issue

resources/js/processes/screens/preview.js, resources/js/requests/components/screenPreview.vue, resources/views/processes/screens/preview.blade.php
Steps to Reproduce 
- Create a screen with a page navigator 
- Add task form 
- Assign the screen in the form task
Click on the preview option 
- Now is is allowed the interaction with buttons
https://processmaker.atlassian.net/browse/FOUR-10746
ci:next
=> FOUR-10746: Preview for screen is not working with page navigations 

.github/workflows/deploy-pm4.yml
Change default base image to php82 - for next branch
Develop and Next branches will now use php82
To use the php81 base for older version of processmaker, use the ci tag: `ci`:`php81` the PR body
ci:next
ci:deploy
=> CICD: Change default base image to php82 - next

.github/workflows/deploy-pm4.yml
Change default base image to php82
Develop and Next branches will now use php82
To use the php81 base for older version of processmaker, use the ci tag: `ci`:`php81` the PR body
ci:deploy
=> CICD: Change default base image to php82

resources/js/admin/settings/components/SettingDriverAuthorization.vue
The AUTHORIZE button of external integration (CDATA) remains disabled after a connection, if I want to perform the authorization again, I have to remove the disable attribute from the DOM.
The condition for determining whether the "Authorize" button should be disabled or not has been adjusted.
- While the driver has not been authorized, the button will remain enabled unless "isInvalid" is true.
- Once the driver has been authorized, the "changed" and "isInvalid" conditions will apply.
The above changes will enhance the user experience, especially when the driver has not been authorized and needs to perform multiple tests with the authorize button.
Follow the reproduction steps from the JIRA ticket.
- [FOUR-12334](https://processmaker.atlassian.net/browse/FOUR-12334)
[FOUR-12334]: …
=> FOUR-12334 - Enhancing UX in External Integrations Authorize Button

resources/js/processes/modeler/components/inspector/ModelerAssetQuickCreate.vue, resources/js/processes/modeler/components/inspector/ScreenSelect.vue, resources/js/processes/scripts/components/CreateScriptModal.vue
- Moved the channel `onMessage` to the mounted call on `ModelerAssetQuickCreate` to be emitted to the parent
- https://processmaker.atlassian.net/browse/FOUR-12193
- https://github.com/ProcessMaker/connector-pdf-print/pull/73
ci:deploy
ci:connector-pdf-print:bugfix/FOUR-11731
=> FOUR-12193 Added channel receipt of message to emit data to the parents

resources/js/admin/settings/components/cdata/DocusignConnectionProperties.vue
When I do not click the Use Sandbox switch the connection does not work.
When I disable it and then enable it again, it just works correctly.
1. Log in 
2. Click on Admin
3. Click on Settings 
4. create connection for docusign driver
5. configure 
6. click on AUTHORIZE
- The 'updateFormData' event is now emitted after assigning the 'use_sandbox' value in the mounted block of the Vue component. This ensures that configuration changes are properly reflected in other components listening to this event.
- Now, whenever a DocuSign CDATA driver is added, the 'UseSandbox' property will be correctly set to default.
Follow the reproduction steps of above.
- [FOUR-12338](https://processmaker.atlassian.net/browse/FOUR-12338)
ci:next
[FOUR-12338]: …
=> FOUR-12338 - You need to disable and enable the Use Sandbox toggle in external integrations

resources/js/processes/scripts/components/CreateScriptModal.vue
As a Designer, I want to find a easy, simple and visual way select the type of script, name it and add the respective settings.
- Load the initial modal
Create a new script and the new modal will show
- [FOUR-11498](https://processmaker.atlassian.net/browse/FOUR-11498)
ci:deploy
ci:next
[FOUR-11498]: https://processmaker.atlassian.net/browse/FOUR-11498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-11498:Initial script Modal

resources/js/components/shared/ProjectSelect.vue
The project select component was loading all projects and that caused a large payload that was slowing down cypress tests.
This refactor
- Only loads 10 projects initially
- Allow for backend typeahead searching when the desired project is not in the initial 10 payload
- Loads the selected projects if they do not exist in the initial 10 project payload
- Have more than 10 projects
- Search and select for projects on an asset that has projects (ie scripts create, scripts update, etc)
- https://processmaker.atlassian.net/browse/FOUR-12412
- Requires Projects PR: https://github.com/ProcessMaker/package-projects/pull/83/files
=> Refactor project select component

ProcessMaker/Http/Controllers/Process/ScreenController.php, resources/views/processes/screens/preview.blade.php
Log in 
Create a  screen with  signature  control
create a new process
create a form task
add the screen that contains signature
click in windows pane preview
As we see, the signature is not shown in the screen preview
and we get an eroor on the console
the signature must be displayed without errors
- Now scripts registered by packages are registered in the preview page.
- https://processmaker.atlassian.net/browse/FOUR-12374
- https://processmaker.atlassian.net/browse/FOUR-12343
=> FOUR-12374: The signature control is not shown in the windows pane screen preview

resources/js/processes/designer/RecentAssetsList.vue
When clicking on Scripts, Data Sources, or Decision Table assets within the Designer page within the Resent Assets section, it opens the configuration instead of the actual builder, resulting in inconsistent behavior compared to other lists.
- Create a Project
- Add assets to the Project
-- Script, Process, Screen, Data Connector, Decision Table
- Navigate to the Designer page.
- Click on each asset within the RECENT ASSETS FROM MY PROJECTS section
The asset should open the builder for each asset.
In certain cases, the configuration page is opened instead of the intended builder.
(Script, Decision Table, Data Connector)
This behavior is inconsistent with other lists. 
- Update asset endpoints within the Designer Page
Please follow the reproduction steps and ensure that when we click on …
=> Update asset endpoints within the Designer Page

resources/js/components/shared/PmqlInputFilters.vue
This PR resolves issues where the Project title filter was not populated on the initial load of the projects page. The solution involved setting the projectOptions variable to the response project data when initially loading the projects page.
- Updated the logic to ensure the Project title filter is populated with available project titles on the initial load of the projects page.
1. Ensure that projects are properly configured in the system.
2. Load the projects listing page.
3. Select the 'Filters' option.
4. Choose the project title filter.
5. Confirm that the available project titles are listed before typing in the search bar.
6. While searching, ensure that the project titles are properly listed and that the filter functions as expected.
- …
=> Fix Project Title Filter Population Issue on Initial Load

resources/js/processes/modeler/initialLoad.js
Add Script Task
Assign a script
Click on Preview
Click on external link
Current Behavior 
Link Script redirection not working in Script Task 
Fixed the URL for scripts.
https://processmaker.atlassian.net/browse/FOUR-12443
=> Fix url for script assets

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/views/processes/modeler/index.blade.php, resources/views/processes/modeler/inflight.blade.php
This PR addresses the issue of lost CDATA node configurations that occurred when refreshing the screen multiple times or while loading on a slow network. The solution involves preloading the CDATA node configurations during the initialization of the modeler, storing them in an `ExternalIntegrationsList` variable. Additionally, a fallback mechanism is implemented to fetch the CDATA configurations if the `ExternalIntegrationsList` is empty.
- Introduced a preload mechanism for CDATA node configurations during modeler initialization.
- Implemented a fallback to fetch CDATA configurations if the externalIntegrationsList is empty.
1. Ensure you have CDATA installed using this [PR](https://github.com/ProcessMaker/package-cdata/pull/21)
2. Ensure that External Integrations are enabled under …
=> Fix CDATA Node Configuration Loss on Slow Network or Multiple Screen Refreshes

resources/js/processes/scripts/components/CreateScriptModal.vue
-  https://processmaker.atlassian.net/browse/FOUR-12189
ci:deploy
ci:next
=> feature/FOUR-12189 : FOUR-11498: Create a Accordion component: Add Advanced options - Less Options

resources/js/processes/scripts/components/ScriptEditor.vue
1.Create a script in PHP language
2.Create a B script Javascript language
3.the last script B use the AI with a simple description
4.Click on Generate
5.Go to first script A
What was generated with AI is also shown in script A that is using another language (in this case PHP)
AI in script should not show what it generates in a script that uses another language.
- Verify if nonce is the same as the request after update the progress or the script
https://github.com/ProcessMaker/processmaker/assets/90727999/6bcf2359-eaf8-41f3-8e38-7351cb3a866b
- [FOUR-12440](https://processmaker.atlassian.net/browse/FOUR-12440)
[FOUR-12440]: https://processmaker.atlassian.net/browse/FOUR-12440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> Bugfix/FOUR-12440: When using AI in script it is displayed simultaneously in different scripts

resources/js/processes/scripts/components/AiTab.vue, resources/js/processes/scripts/components/ScriptEditor.vue
1. Login as admin
2. Go to Designer
3. Click on +Process
4. Click on Build Your Own
5. Drag and drop the AI Generated control
6. Select Generate Script From Text
7. Set the information
8. Change if needed the prompt on the Description 
9. Click on Generate
10. Click on Document, Clean or Explain
After apply should display the menu 
After apply the changes instead of displaying the menu options it displays the Generate Script From Text is displayed
- The variable that toggles the menu is always changed on the `mounted()` hook of `AiTab.vue` so changing it to display the main menu on mount solves the issue.
- [FOUR-12421](https://processmaker.atlassian.net/browse/FOUR-12421)
[FOUR-12421]: https://processmaker.atlassian.net/browse/FOUR-12421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> Bugfix/FOUR-12421: Main Ai Menu is shown on Apply Changes or Cancel

ProcessMaker/Models/ScriptDockerBindingFilesTrait.php
On k8s, script timeouts are showing an exception trace instead of the timeout error that we had on ECS instances.
- For some reason, on alpine linux, the timeout command can have the exit code `9` when run with php's `exec` command. This is different then on Mac and Ubutnu where it returns `137`. The solutions is to treat both exit codes as timeouts.
- On a k8s instance, set the timeout to 5 and run a script with `sleep(10);` to trigger the timeout out. It should show the timeout error instead and not the exception trace.
- https://processmaker.atlassian.net/browse/FOUR-10600
=> Docker timeouts can also have exit code 9

resources/js/processes/scripts/components/CreateScriptModal.vue
Redesign like the mockup defined in Figma:
- https://processmaker.atlassian.net/browse/FOUR-12430
ci:next
ci:deploy
=> feature/FOUR-12430: Redesign Fields

resources/js/processes/modeler/components/inspector/SignalPayload.vue
All changes related to the signal events should be reflected in the other users in collaborative mode
The assignation of the signal reference is not reflected in the other user in collaborative mode 
- Add support to the Signal Payload in collaborative mode
2. Open the process with two users with different session
3. With one user 
4. Add signal intermediate event
5. Assign a signal reference
6. Saved the changes
7. Go to the modeler of the other users
8. The signal reference must be assigned
[FOUR-12376](https://processmaker.atlassian.net/browse/FOUR-12376)
https://github.com/ProcessMaker/modeler/pull/1739
[FOUR-12376]: https://processmaker.atlassian.net/browse/FOUR-12376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> FOUR-12376 signal reference is not reflected in collaborative mode

resources/js/components/shared/ellipsisMenuActions.js
The open Launchpad need to redirect the the Menu Process
- https://processmaker.atlassian.net/browse/FOUR-12318
ci:deploy
ci:next
=> feature/FOUR-12318: Add the redirect to launchpad

ProcessMaker/Models/ScriptExecutor.php, resources/js/processes/scripts/components/LanguageScript.vue
- [FOUR-12505](https://processmaker.atlassian.net/browse/FOUR-12505)
ci:deploy
ci:next
[FOUR-12505]: https://processmaker.atlassian.net/browse/FOUR-12505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12505:Other script executor does not have an icon on the modal script list

resources/js/processes/scripts/components/LanguageScript.vue
- [FOUR-12504](https://processmaker.atlassian.net/browse/FOUR-12504)
ci:deploy
ci:next
[FOUR-12504]: https://processmaker.atlassian.net/browse/FOUR-12504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12504:It is not possible to recognize the new custom script executor created

resources/js/processes/scripts/components/CreateScriptModal.vue
- Modal window clear all fields on Close
ci:deploy
=> QA Observation: Bugfix/FOUR-12502 The fields are not cleared after closing the modal

ProcessMaker/Http/Controllers/Api/ScriptExecutorController.php
Cdata appears in the list of languages available.
- Do not show system languages.
Create or edit an executor, You shouldn't see the language Cdata.
- [FOUR-12538](https://processmaker.atlassian.net/browse/FOUR-12538)
Depends
ci:docker-executor-cdata:bugfix/FOUR-12538
https://github.com/ProcessMaker/docker-executor-cdata/pull/8
[FOUR-12538]: https://processmaker.atlassian.net/browse/FOUR-12538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CData executor appears in list of available executors

composer.json
Fix package names for:
- package-zj-sonymusic
- package-zj-nas
Build the image
- https://processmaker.atlassian.net/browse/FOUR-12549
ci:next
=> Fix customer package names

ProcessMaker/Managers/OauthMailManager.php
Email sent fail when using google oauth mail client.
- Since Laravel 10 the mail service use Symfony Mailer, it does not have the method `setAuthMode` but does not need to use it anymore. This PR removes the use of this function.
- Setup a google auth mail configuration. To enable Gmail SMTP OAuth in email server settings, follow these steps:
1. Create a new email server configuration.
2. Click the SMTP Authentication Method setting and select the "google" option.
3. Save the settings.
4. Click the Edit icon for the Use Secure Connection setting and select the "tls" option.
5. Save the settings.
6. Click the Edit icon for the Server Port setting and enter "587".
7. Save the settings.
8. Click the Edit icon for the Server Host setting and enter "smtp.gmail.com".
9. Save the settings.
10. …
=> Symfony Mailer does not use setAuthMode

ProcessMaker/Nayra/Repositories/Deserializer.php
Id related to parent request are storing the uuid instead the. numeric id.
- Before store the data the parent request id is replaced by the correct value.
Create a process that uses a sub-process and check the 'parent" values in data, specifically the request_id.
=> FOUR-12579 data._parent.request_id the value is wrong

resources/views/requests/show.blade.php
When consulting the "Process Inflight Map" in Google Chrome with the "Disable cache" option enabled, an unusual display of the process map is observed. Additionally, this behavior can be simulated by enabling a slow internet connection in the network settings to replicate the issue.
1. Create and finish a request.
2. Click on the "Overview" tab.
- The display issue is related to how Google Chrome interprets and renders the iframe.
- The proposed solution is to replace the use of the `<iframe>` tag with an `<object>` tag. Apparently, there are no issues with `<object>` tag.
- Follow the above-mentioned steps to reproduce the problem.
- [FOUR-12548](https://processmaker.atlassian.net/browse/FOUR-12548)
- [Old related issue FOUR-9742](https://processmaker.atlassian.net/browse/FOUR-9742) …
=> FOUR-12548 - Overview is overlapped when consulting it

ProcessMaker/Notifications/ProcessTranslationReady.php
1. Login https://ci-997eeda9bb.eng.processmaker.net/
2. Create a Process
3. Open the Process Configuration
4. Press + Translation button
5. Select a Lenguage
6. Press Translate process button
7. Wait for the notification
The notification is empty 
When a translation is added in a process, the notification should have the correct message.
=> FOUR-12550 Notification Empty when a Translation is added in a Process

ProcessMaker/Http/Controllers/Auth/LoginController.php, ProcessMaker/Models/User.php, config/password-policies.php, resources/views/admin/users/edit.blade.php, resources/views/auth/passwords/change.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/users/sidebar.blade.php, tests/Feature/Api/ChangePasswordTest.php, tests/Feature/Api/UsersTest.php
The passwords policies are not configurable
Added validations when the users login to the app
Add in .env the next values:
PASSWORD_POLICY_NUMBERS=TRUE
PASSWORD_POLICY_UPPERCASE=TRUE
PASSWORD_POLICY_SPECIAL=TRUE
PASSWORD_POLICY_MINIMUM_LENGTH=8
PASSWORD_POLICY_MAXIMUM_LENGTH=12
PASSWORD_POLICY_LOGIN_ATTEMPTS=5
And validate when user login to the app
https://processmaker.atlassian.net/browse/FOUR-11415
=> FOUR-11415 Password Policy Configuration

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/CatalogueEmpty.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue
Process Browser - List Available Process
- Create categories
- Go to Process Menu
- [FOUR-12111](https://processmaker.atlassian.net/browse/FOUR-12111)
ci:deploy
ci:next
[FOUR-12111]: https://processmaker.atlassian.net/browse/FOUR-12111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature/FOUR-12111: Process Browser - List Available Process

resources/js/components/shared/EllipsisMenu.vue, resources/js/components/shared/ellipsisMenuActions.js
This PR introduces a new project permission named 'view-additional-asset-actions.' This permission provides precise control over the permissions granted to Project Members for managing projects and project assets. When enabled, the permission grants access to additional actions for each asset. For example, users with this permission enabled will have access to 'archive,' 'edit,' and other actions related to processes. Similarly, for screens, users will have access to 'delete,' 'edit,' and other relevant actions.
When the permission is disabled, users will only have default actions related to projects, such as 'Add to Project,' 'Copy to Project,' and 'Remove from Project.'
- Introduced the 'view-additional-asset-actions' project permission to control access to additional actions for …
=> Implement 'View Additional Asset Actions' Project Permission

ProcessMaker/Console/Commands/SyncWizardTemplates.php, ProcessMaker/Jobs/SyncWizardTemplates.php, config/services.php
This pull request aims to resolve the begin the seamless synchronization between the GitHub repository and the ProcessMaker platform, specifically concerning Wizard Templates. The synchronization process is facilitated through a new command, `php artisan processmaker:sync-wizard-templates`.
To address the issue, the following changes have been implemented:
- Introduced a Job for `SyncWizardTemplates`.
- Implemented an Artisan Command for `SyncWizardTemplates`.
- Added `wizard_templates_github` to the `config.services` file.
Testing is not currently possible. The objective is to establish a connection between the GitHub repository and the database through the associated pull requests.
- Tickets [FOUR-11891](https://processmaker.atlassian.net/browse/FOUR-11891) and …
=> Job for Synchronizing for Wizard Templates

ProcessMaker/Traits/SearchAutocompleteTrait.php, resources/js/components/shared/PmqlInputFilters.vue
Users without Project ownership can view all projects in the filter.
1. Log in with the admin user.
2. Create several projects with the admin user.
3. Log out.
4. Log in with a different user.
5. Create additional projects with the second user.
7. Click on "Projects."
8. Notice that all projects are visible, not just the ones created by the first user.
9. Click on the project filter.
All created projects are displayed in the project filter, regardless of ownership.
The filter should only display projects that belong to the logged-in user.
- Modify the filter to show only the projects that belong to the currently logged-in user.
1. Follow the reproduction steps.
2. Ensure that the project filter exclusively displays …
=> FOUR-12450: Filter only the Projects that belong to the User

ProcessMaker/Providers/AuthServiceProvider.php
This PR resolves an issue where users with only Project Permissions encountered an Unauthorized message when creating a script in their project and being redirected to the script builder page. 
The problem was traced to the script builder endpoint not being included as an allowed endpoint for users with the `create-projects` permission. The solution includes adding the script builder endpoint `designer/scripts` to the `allowedEndpoints` array for users with the `create-projects` permission.
- Included the script builder endpoint `designer/scripts` in the allowedEndpoints array for users with the 'create-projects' permission.
1. Create a user with only Project Permissions.
2. Log in as that user.
3. Create a project.
4. Within the project, select the '+ Asset' button and create a new …
=> Fix Unauthorized Message Issue for Users with Project Permissions Creating Scripts

ProcessMaker/Nayra/Managers/WorkflowManagerDefault.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/Repositories/PersistenceHandler.php, ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php
Global signal were not being triggered when Nayra trigger them.
- Listen for the event throw_global_signal_event to trigger the signal event.
- https://processmaker.atlassian.net/browse/FOUR-12555
- https://github.com/ProcessMaker/nayra-docker/pull/36
=> Trigger global signals dispatched by Nayra Service

ProcessMaker/Console/Commands/OptimizeClearCommand.php
In production, we use the `bootstrap/cache/packages.php` file as a cached store of licensed packages which we would like to be loaded. In the case that the `php artisan optimize:clear` command is run, this flushes that file (which is generated with a separate command) and causes the framework to regenerate the file with all packages discovered, regardless of licensing.
1. Install all custom and enterprise packages using `develop`
2. Run the `php artisan license:update {pathToLicenseJsonFile}` command to generate the package manifest.
3. Interact with the platform and notice everything working as intended
4. Now run `php artisan optimize:clear`
5. Check the platform again (e.g. the `/requests` page). Notice the errors/multiple menu items added, etc. This is because there are multiple …
=> FOUR-12638: Introduce customized optimize:clear

database/migrations/2023_11_27_215150_create_wizard_templates_table.php, database/migrations/2023_11_28_150344_add_asset_type_column_to_process_templates.php
This pull request introduces two migrations to enhance the database schema. The changes include:
1. **Migration to Add a `asset_type` to `process_templates`:**
- Added a new migration file (`add__asset_type_column_to_process_templates`) to insert a string column after the existing `is_system` column in the `process_templates` table.
2. **Migration for `wizard_templates` Table:**
- Created a migration file (`create_wizard_templates_table`) to define the schema for the `wizard_templates` table.
- Included columns such as `id`, `uuid`, `process_template_id`, `process_id`, `media_id`, and timestamps.
- Defined foreign key constraints for `process_id` and `media_id` columns.
The additions to the database schema were necessary to accommodate new requirements and improve data management for the …
=> FOUR-12173: Develop Wizard Template database schema

.env.example, composer.json, composer.lock, config/filesystems.php, config/samlidp.php, resources/views/auth/newLogin.blade.php, storage/samlidp/.gitignore, tests/Feature/AuthTest.php, tests/Feature/RedirectTest.php, tests/Feature/SecurityLoggerTest.php
- Adding a library and configuration for IDP SAML support
- Set a new env variable `SAML_SP_DESTINATION`
[FOUR-12244](https://processmaker.atlassian.net/browse/FOUR-12244)
[FOUR-12244]: https://processmaker.atlassian.net/browse/FOUR-12244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12244 implement IDP for processmaker

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/MustacheExpressionEvaluator.php, ProcessMaker/Models/Process.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php, ProcessMaker/Observers/ProcessRequestObserver.php, database/migrations/2023_11_27_170308_add_case_title_to_processes_table.php, database/migrations/2023_11_27_180941_add_case_title_number_to_process_requests_table.php, resources/js/requests/components/RequestsListing.vue, resources/views/processes/edit.blade.php, tests/Feature/Api/ProcessRequestsTest.php
Request Title Configuration.
Create a process and setup the case title.
- https://processmaker.atlassian.net/browse/FOUR-12577
ci:deploy
ci:next
ci:APP_DEBUG=true
=> FOUR-12577 Request Title Configuration.

ProcessMaker/Nayra/Repositories/PersistenceTokenTrait.php
**IMPORTANT: be sure you are using Nayra micro service**
- Create a process with the following controls:
- An Star event, 2 tasks, and a End event.
- Create a screen with your desired controls and assign them to both tasks.
- In the second task, configure the Email Notifications, and in the Recipient Type, choose Email Address and enter the desired email. Also, ensure that your server has its Email Default Settings configured.
- Assign a user to the start event.
- Run a request and route it to the second task.
As you can see, you will not receive a notification email that was configured in the second task. For more details, please watch the video in the ticket https://processmaker.atlassian.net/browse/FOUR-12661.
The sending of email notifications …
=> Bugfix/FOUR-12661: [34966 - 35021] Process Not Sending Email Notifications

resources/js/components/templates/SelectTemplateModal.vue
This PR resolves the issue of the missing create process option bar from the New Process modal by adding the new attribute `showTemplateOptionsActionBar` to the template search component. The addition of this attribute provides more granular control over which components are displayed when utilizing the Template Search component in different areas of the platform.
- Added the `showTemplateOptionsActionBar` attribute to the template search component for better control over component display.
1. Navigate to Designer > Processes.
2. Select the '+ Process' button.
3. Ensure that when the modal appears, the options to 'Build your Own,' 'Generate from Text,' etc., are displayed above the Process Template options.
4. In the top navigation menu, navigate to Processes > Wizard Templates.
5. …
=> Resolve missing new process options in New Process modal

resources/js/components/shared/ellipsisMenuActions.js, resources/lang/en.json
The actual option "Edit Process" in the ellipsis menu should change the name to "Open in Modeler".
In the ellipsis menu add a "Edit Launchpad" The action related to this will work in the ticket FOUR-12634
- https://processmaker.atlassian.net/browse/FOUR-12636
ci:next
ci:deploy
=> Feature/four 12636: Update the label "Edit Process" of process options

ProcessMaker/Models/Bookmark.php, database/migrations/2023_11_30_165723_add_launchpad_properties_at_processes.php, database/migrations/2023_11_30_170839_create_user_process_bookmarks_table.php
Create table and column to save the Launchpad Settings and bookmarks
- A new table was created `user_process_bookmarks`
- A new column was added `processes.launchpad_properties`
`artisan migrate --force`
- https://processmaker.atlassian.net/browse/FOUR-12652
ci:deploy
ci:next
=> feature/FOUR-12652: Create table and column to save the Launchpad Settings and bookmarks

ProcessMaker/Http/Middleware/GenerateMenus.php
Reorder the menu, the Processes show after Home
Login and review the order like:
Home - Processes - Request - Task  - Analytics - Designer - Admin
- https://processmaker.atlassian.net/browse/FOUR-12714
ci:deploy
ci:next
=> FOUR-12714: Reorder the menu

resources/js/processes-catalogue/components/CardProcess.vue
Go to Processes
Click one process (card) and open the corresponding Process launchpad
Example:
- https://processmaker.atlassian.net/browse/FOUR-12708
ci:next
ci:deploy
=> Feature/four 12708: Process Launchpad - Click on Card need to open the process Launch

ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php
When a process have a Multi-Instance task, sometimes the request is not routed to the next task. The video attached to the ticket in JIRA show the incorrect behavior.
`state` value currently is not necessary and is outdated in some situations, send the `collaboration_uuid` is enough for `nayra service` to get the last state of the request
Create a process with a Multi-Instance task and try to route to the next task the most faster possible.
https://processmaker.atlassian.net/browse/FOUR-12667
=> FOUR-12667 Multi-Instance (Parallel) not routing the request when the parallel tasks are completed

resources/js/processes/screens/components/CreateScreenModal.vue, resources/js/utils/filterScreenType.js
- Added a check if the `filterScreenTypes` function returns undefined to default to `this.types`
You can try to create a screen, no errors should appear in the Developer Tools.
Just out of curiosity, try to test creating using the Asset Quick Create
- https://processmaker.atlassian.net/browse/FOUR-12672
ci:deploy
=> FOUR-12672 Defaulting to the prop Types

ProcessMaker/Http/Controllers/ProcessController.php, ProcessMaker/Http/Controllers/RequestController.php, resources/js/components/requests/card.vue
Currently, if the interstitial screen is configured in the start event, it never shows up and the request’s task is shown directly. We have noticed that this happens with a process with more than 50 elements (meaning tasks, events, lines, pools, etc.) at the beginning you will see this behavior intermittently but if you increase the number of elements (>50) you will see it permanently. 
If you reduce the number of elements you will see that the interstitial works normally.
Replace the `fromTriggerStartEvent` cookie with a query param
[FOUR-12665](https://processmaker.atlassian.net/browse/FOUR-12665)
[FOUR-12665]: https://processmaker.atlassian.net/browse/FOUR-12665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12665 The interstitial screen in the start event stops working

ProcessMaker/Jobs/RefreshArtisanCaches.php, ProcessMaker/Jobs/RestartKafkaConsumers.php, ProcessMaker/Jobs/RestartMessageConsumers.php, ProcessMaker/Providers/SettingServiceProvider.php
All ProcessMaker settings are persisted in the database, but are also set in the laravel `config()`. When the config is cached, it is stored in `bootstrap/cache/config.php`, which each instance of the app uses when booting up.
Currently, we restart the job queue by listening for config changes since it is a long-running command (`php artisan horizon`) and only reads from `bootstrap/cache/config.php` once when it starts.
When testing an Actions By Email feature, the settings changes which were made were not picked up by the (more recent) `processmaker:consume` artisan command, which is also long-running. This caused an exception to be thrown in the `processmaker:consume` command's process when the ABE email was attempted to be sent.
Call the `kafka:restart-consumers` command to restart all …
=> FOUR-12686: Restart `processmaker:consume` command(s) when config changes

resources/js/processes/components/CreateProcessModal.vue
This PR resolves a console error `'response' undefined` that occurs when attempting to create a new process from the Designer > Processes page. 
The issue was due to inconsistent handling of the returned response when storing the new process. The variable `response` was initially referencing the data object, but within the handling, the variable `data` was used instead of `response`, leading to the `'response' undefined` error. The solution was to update the variable name from `data` back to `response` for consistency.
- Updated the variable name from 'data' to 'response' to ensure consistent referencing.
1. Navigate to the Designer > Processes page.
2. Attempt to create a new process.
3. Confirm that no console error ('response' undefined) occurs during the new process creation.
- …
=> Fix Console Error 'response' Undefined in New Process Creation

ProcessMaker/Models/CaseNumber.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/Nayra/Repositories/Deserializer.php, ProcessMaker/Observers/ProcessRequestObserver.php, ProcessMaker/Repositories/ExecutionInstanceRepository.php, database/migrations/2023_12_04_100557_create_case_numbers_table.php, database/migrations/2023_12_04_115613_add_case_number_to_process_requests_table.php, resources/js/requests/components/RequestsListing.vue
Add Case Number Column
- https://processmaker.atlassian.net/browse/FOUR-12574
ci:deploy
ci:next
=> FOUR-12574 Add Column Case Number

ProcessMaker/Http/Resources/ProcessRequests.php, resources/js/requests/components/RequestsListing.vue
- https://processmaker.atlassian.net/browse/FOUR-12594
ci:next
ci:deploy
=> FOUR-12594 Request Columns final order

resources/js/components/shared/ellipsisMenuActions.js, resources/views/processes/list.blade.php, resources/views/processes/screens/list.blade.php, resources/views/processes/scripts/list.blade.php
This PR resolves an issue where the 'Add to Project' action in the assets' ellipsis menu was hidden, even with the correct permissions enabled. 
The problem stemmed from the lack of project permissions being included in the permissions variable, resulting in the action being hidden from the user. To fix this, 'projects' was added to the `hasPermissionsFor` check in each of the assets listing components.
- Added 'projects' to the `hasPermissionsFor` check in the assets listing components to ensure proper visibility of the 'Add to Project' action.
1. Ensure you have the 'create-projects' permission enabled under Projects.
2. Navigate to Processes, Screens, Scripts, Data Sources, Decision Tables assets, and select the ellipsis menu.
3. Confirm that the 'Add to Projects' action is visible.
4. …
=> Fix Visibility Issue of 'Add to Project' Action in Assets Ellipsis Menu

resources/js/processes/scripts/components/CreateScriptModal.vue
This PR resolves the issue of the missing category select dropdown when creating a script from within a project. The problem was caused by a `v-show` attribute on the `category-select` component in the `create-script-modal` component, which hid the dropdown if the asset being created was a project asset.
-  Remove the `v-show` attribute to ensure the visibility of the category dropdown for project assets.
1. Navigate to Designer > Projects.
2. Create a project.
3. Within the project, select the '+ Asset' button.
4. Create a new script.
5. Ensure the category dropdown is visible in the Create Script Modal.
- [FOUR-12756](https://processmaker.atlassian.net/browse/FOUR-12756)
ci:next
[FOUR-12756]: https://processmaker.atlassian.net/browse/FOUR-12756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> Fix Missing Category Dropdown in Create Script Modal for Project Assets

tests/Feature/ExtendedPMQLTest.php
The pmql should support the use of the function Lower.
1. Create a new PHP script
2. Use the attached PHP script (see JIRA ticket).
3. Execute the script.
After running the script the error displayed is “SERVER ERROR“. Only if you remove the lower function the pmql works.
When using a JSON field (`data.example`) and applying the lower function, the following error occurs:
```
An object of the Illuminate\Database\Query\Expression class cannot be converted to a string.
```
This happens because Expression is an object that cannot be directly converted into a string.
This issue likely emerged due to the version upgrade from Laravel 8 to Laravel 10. In Laravel 8, the `__toString()` method existed, but in Laravel 10,this method was removed. Now, to access the value, it is necessary to use the …
=> FOUR-12716: PMQL "lower" function is not working correctly

ProcessMaker/Http/Controllers/Api/BookmarkController.php, ProcessMaker/Models/Bookmark.php, database/factories/ProcessMaker/Models/BookmarkFactory.php, routes/api.php, tests/Feature/Api/BookmarkTest.php
Process Launchpad: API to save and get Bookmarks
- Implement a new API in order to get, store and delete a bookmark
Tes the new API's to get, save and delete a bookmark
```
GET /process_bookmarks
POST  /process_bookmarks/{process}
DELETE  /process_bookmarks/{process}
```
- https://processmaker.atlassian.net/browse/FOUR-12238
ci:deploy
ci:next
=> feature/FOUR-12238: Process Launchpad: API to save and get Bookmarks

resources/js/components/shared/DataTree.vue, resources/js/processes/export/components/ExportSuccessModal.vue
- Create a screen
- Drag and drop the rich text component
- Add some text lines 
- Use the bullet list format 
- Add the label **scoped** in the style for the components
- [FOUR-12784](https://processmaker.atlassian.net/browse/FOUR-12784)
ci:deploy
[FOUR-12784]: https://processmaker.atlassian.net/browse/FOUR-12784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12784:Bullets are not displayed in the rich text component

ProcessMaker/ImportExport/Exporters/EnvironmentVariableExporter.php, upgrades/2023_12_07_225946_delete_duplicate_environment_variables.php
This PR addresses a critical issue related to the automatic creation of environment variables with the same name, which was occurring excessively—surpassing the limit of 100 instances. 
The modifications implemented in this PR effectively resolve the problem, ensuring that the generation of environment variables can handle duplicates in increments and remove all the duplicates.
- Add $handleDuplicatesByIncrementing to the EnvironmentVariableExporter Class 
- Add an upgrade migration to delete all the env duplicates.
In this case, we need to run a few tests, the first one is to make sure all duplicate env variables are been incremented and the second test is to make sure all the duplicate env variables have been deleted.
First Test:
Import PM Block:
- Download the …
=> Add handle Duplicates to EnvironmentVariableExporter and remove duplicate env variables

ProcessMaker/Nayra/MessageBrokers/ServiceKafka.php, config/kafka.php
Forms tasks reloading in submission and not moving forward. This was caused because the message size exceded the default maximum kafka message size.
- Add environment variables to configure message max size and compression
- Set default max size to 10mb
- Set gzip as default compression
- Create a process with a Screen with a text area.
- Fill the textarea with a large content. E.g. 2mb of a character like `"`
- https://processmaker.atlassian.net/browse/FOUR-12806
=> FOUR-12806 Fix Forms tasks reloading in submission and not moving forward

resources/js/components/shared/ModalSaveVersion.vue, resources/js/processes-catalogue/components/ProcessMap.vue
- User can update Process Description from Launchpad Settings tab
- Go to Launchpad or Modeler. Open 'Edit in Launchpad' in Launchpad ellipsis or press button PUBLISH on modeler window.
- Change Process Description field and SAVE
- https://processmaker.atlassian.net/browse/FOUR-12684
ci:deploy
ci:next
=> Feature/FOUR-12684: The user can update the Process Description from Launchpad

ProcessMaker/Providers/AuthServiceProvider.php, ProcessMaker/Traits/ProjectAssetTrait.php
This PR resolves an issue where users with only Project Permissions received an unauthorized 403 error when creating a new endpoint in data sources. The problem stemmed from inconsistencies in how the modal names were being returned, as well as a 500 error when running the `syncProjectAssets` method during data source updates.
- Updated the modal name for the 'DataSource' modal to accommodate inconsistent naming conventions.
- Refactored the `syncProjectAssets` method for better clarity and manageability.
- In the `syncProjectAssets` method, handled extracting the project IDs for arrays and strings.
1. Ensure you have a user with only Project permissions enabled.
2. Log in as that user.
3. Navigate to Designer > Projects.
4. Create a project.
5. Within the project navigate to '+ Assets' …
=> Fix Unauthorized Error for Users with Only Project Permissions on Data Source Endpoint Creation

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Process with category inactive could start a reques by Launch Pad
- apply filter by status = active
1. Create a category for process
3. Assign the process to category created 
4. Inactive the category
5. Go to requests 
6. Search the process with the inactive category (The process does not appear in the list of requests)
7. Go to launch pad
8. Try to start a request of the process with inactive category
- https://processmaker.atlassian.net/browse/FOUR-12857
ci:deploy
ci:next
=> bugfix/FOUR-12857: Process with category inactive could start a reques by Launch Pad

ProcessMaker/Console/Commands/CreateSamlCertificate.php
As a Developer, I want to add more options to the artisan command to generate self-signed certificates
- add a customized artisan command to generate self-signed certificates for the IDP
1. Run `php artisan -h samlidp:cert`
2. Run `php artisan samlidp:cert --subject "/C=US/ST=New York/L=New York City/O=Example Inc/CN=example.com"`
[FOUR-12246](https://processmaker.atlassian.net/browse/FOUR-12246)
ci:deploy
ci:next
ci:SAML_SP_DESTINATION=https://keycloak.processmaker.net/realms/pm4-next/broker/pm4-saml/endpoint
[FOUR-12246]: https://processmaker.atlassian.net/browse/FOUR-12246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12246 customize artisan command to generate self-signed certificates

config/app.php
The email body is sent empty.
This happens when the laravel configuration is cached.
- Use config to cache variable NODE_BIN_PATH
With the fix:
Create a process with a send email task to send an screen type email.
- https://processmaker.atlassian.net/browse/FOUR-12933
ci:deploy
ci:connector-send-email:bugfix/FOUR-12933
=> FOUR-12933 - Fix the content of the email type screen is not displayed in the body of the message

ProcessMaker/Exception/PackageNotInstalledException.php, ProcessMaker/ImportExport/Logger.php, ProcessMaker/ImportExport/Manifest.php, resources/js/processes/import/components/ImportLog.vue, tests/Feature/ImportExport/ManifestTest.php
See https://processmaker.atlassian.net/browse/FOUR-12929
If a column or class is missing, the import fails.
- Log a warning and continue importing
Export a simple process from Winter and import it into Fall. The import should complete without errors.
The process table has a new column, `case_title`. Previously, this was causing it to fail
- https://processmaker.atlassian.net/browse/FOUR-12929
ci:deploy
=> Gracefully handle missing classes and columns when importing

ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/Jobs/ImportV2.php, resources/js/processes/export/components/MainAssetView.vue, resources/js/processes/export/state.js
See https://processmaker.atlassian.net/browse/FOUR-12903
- Need to exclude the root process when setting mode
See jira issue
- https://processmaker.atlassian.net/browse/FOUR-12903
=> Fix process export checkbox

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, routes/api.php, tests/Feature/Api/ProcessRequestsTest.php
Create an API to get the total request per process
- `GET 'requests/{process}/count'`
- https://processmaker.atlassian.net/browse/FOUR-12868
ci:deploy
ci:next
=> FOUR-12868: Create an API to get the total request per process

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/Bookmark.php, tests/Feature/Api/ProcessTest.php
The list of process per category needs to return if the process was bookmarked
add a new filter bookmark like:
- `GET /processes?page=1&per_page=10&bookmark=true`
this will return if the process was bookmarked for the user logged
- https://processmaker.atlassian.net/browse/FOUR-12886
ci:deploy
ci:next
=> FOUR-12886: The list of process per category needs to return if the process was bookmarked

ProcessMaker/Traits/SearchAutocompleteTrait.php
This PR refactors the project filtering by owner and member if the user is not an admin, allowing admins to view all projects created within the instance. The admin has all capabilities to edit/delete projects.
- Refactored project filtering logic for both admin and regular users.
1. Create a user.
2. Log in as the user and create projects.
3. Log in as an admin and view projects.
4. Ensure that the admin can see all projects created by users.
5. As an admin, create projects.
6. Log in as a user.
7. Ensure the users cannot access the admin-created projects that they are not a member of.
- [FOUR-12748](https://processmaker.atlassian.net/browse/FOUR-12748)
-[ Projects PR](https://github.com/ProcessMaker/package-projects/pull/91)
ci:next
ci:package-projects:story/FOUR-12748
ci:deploy …
=> Refactor Project Filtering for Admin and Regular Users

ProcessMaker/Models/Process.php
If some process has more than one category the cards related are not listing
- Solve the QA observations
- Create process categories
- Create process and assign in more than one category
- https://processmaker.atlassian.net/browse/FOUR-12811
ci:deploy
ci:next
=> feature/FOUR-12811: If some process has more than one category the cards related are not listing

ProcessMaker/Http/Controllers/Auth/LoginController.php, ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/SamlRequest.php, ProcessMaker/Listeners/SamlAuthenticated.php, ProcessMaker/Listeners/SamlLogin.php, config/samlidp.php
The modal to change a user's password is not shown before creating an account in keycloak
- Extend SAML library listeners and add a new middleware to preserve the SAML request
1. Log in with the admin user
2. Create a new user
3. Go to the profile of the new user
4. Go to the admin tab
5. Search for new users and edit
6. Enable User must change password at the next login checkbox
7. Click on the save button
8. Go to https://keycloak.processmaker.net/realms/pm4-next/account/#/
9. Click on Sign in
10. Click on Cool Customer Application
[FOUR-12889](https://processmaker.atlassian.net/browse/FOUR-12889)
ci:deploy
ci:next
ci:SAML_SP_DESTINATION=https://keycloak.processmaker.net/realms/pm4-next/broker/pm4-saml/endpoint
[FOUR-12889]: https://processmaker.atlassian.net/browse/FOUR-12889?atlOrigin= …
=> FOUR-12889 add middleware and listeners for saml authentication

ProcessMaker/Providers/AuthServiceProvider.php, resources/js/components/shared/ellipsisMenuActions.js
Ticket: [FOUR-12757](https://processmaker.atlassian.net/browse/FOUR-12757)
Users that only have Project permissions should not be able to see the 'Save as Template' or 'Save as PM Block' options in the Process Asset Ellipsis Menu within a Project. However, they should still be able to use PM Blocks and Templates within their projects.
- Remove `view-additional-asset-actions` from the 'Save as Template' and 'Save as PM Block' actions in the Process Ellipsis Menu.
- Add `pm-block` to the projectAssetTypes array in the `checkForListCreateOperations()` function of the Auth Service Provider. This ensures that users who only have Project permissions will not experience errors when working with PM Blocks in Modeler.
1. Go to branch `observation/FOUR-12757` in `processmaker`.
2. Create a …
=> FOUR-12757 | Non-Admin User With Project Permissions Cannot Create a PM Block from a Process Within Their Project

database/seeders/PermissionSeeder.php, resources/js/components/shared/ellipsisMenuActions.js, resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, routes/api.php, routes/web.php
Create a new permission View Process Catalog in order to see the information, per default all new usesr will have this permission and all the admin users, this permission will be enable by default.
- https://processmaker.atlassian.net/browse/FOUR-12710
ci:deploy
ci:next
=> FOUR-12710: Create a new permission View Process Catalog in order to see the information

ProcessMaker/Http/Controllers/Auth/LoginController.php
The session variable `password_hash_web` is not being cleared on login.
- Clean password_hash_web on login form.
- Login with userA
- Logout
- Login with userB
- Before the fix here goes again to login page instead of home
- https://processmaker.atlassian.net/browse/FOUR-12985
=> FOUR-12985 Fix Login failed empty, blocks the user on the second failed attempt

ProcessMaker/Ai/Handlers/LanguageTranslationHandler.php, ProcessMaker/Ai/Handlers/NlqToCategoryHandler.php, ProcessMaker/Ai/Handlers/NlqToPmqlHandler.php
According to the [announcement of OpenAI](https://openai.com/blog/gpt-4-api-general-availability) the model text-davinci-003 are going to be deprecated. We need to update process translations in order to use another model.
- Change the model from text-davinci-003 to gpt-3.5-turbo-16k
- Change completion to chat mode required for newest models.
- [FOUR-12952](https://processmaker.atlassian.net/browse/FOUR-12952)
[FOUR-12952]: https://processmaker.atlassian.net/browse/FOUR-12952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:deploy
=> Task/FOUR-12952: Update process translation project to use another model instead of deprecated text-davinci-003

routes/api.php
Ticket: [FOUR-12770](https://processmaker.atlassian.net/browse/FOUR-12770)
When a non-admin user is working in the Process Modeler, a "This Action is Unauthorized" error is shown when attempting to hit the `processes/{process}/draft` api endpoint.
Update the 'update draft' process route permission. The permission was `edit-screens` and needed to be updated to `edit-processes`.
1. Go to branch `observation/FOUR-12770` in `processmaker`.
2. Login to ProcessMaker. Open a Process and the Network Panel.
3. Make a change to the Process. Wait a few seconds.
4. When the 'draft' endpoint is hit, there should be no errors displayed on the screen.
[FOUR-12770]: https://processmaker.atlassian.net/browse/FOUR-12770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> FOUR-12770 | ”This Action Is Unauthorized" Message for Users Who Are Non-Admin w/ Process Creation Permissions

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Ticket: [FOUR-13012](https://processmaker.atlassian.net/browse/FOUR-13012)
From the Processes Page, if you click on the Guided Template option, then on a Process option, and go back to Guided Templates, the Process Info will display under the Guided Templates.
Update the handling of the Catalogue Empty, CardProcess, ProcessInfo, and WizardTemplates components in relation to one another.
1. Go to branch `observation/FOUR-13012` in `processmaker`.
2. Go to Processes → Guided Templates.
3. Next, select an Available Process.
4. Selected Guided Templates again.
- There should be no Process info under the Guided Templates.
ci:next
[FOUR-13012]: https://processmaker.atlassian.net/browse/FOUR-13012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13012 | When a Process is Clicked and Then a Templates is Clicked, the Process Shows at the Bottom of the Template Page

database/migrations/2023_12_18_104245_check_fix_status_at_users_table.php
The `status` column in the `users` table is sometimes registered as an `enum()` when is should be a `varchar`. This PR converts that column to `varchar` if it finds it that way.
1. Log in with admin user
2. Create a user
3. Go to profile of new user
4. Go to admin tab
5. Search new user and edit
**First scenario:**
1. Go to Settings 
2. Select Out of Office in Status list
3. Click on Save button
4. Reload page
**Second scenario:**
1. Go to Settings 
2. Select Scheduled in Status list
3. Click on Save button
4. Reload page
- Add a database migration to convert the status column to varchar
The reproduction steps should not reproduce the issue.
- [FOUR-12885](https://processmaker.atlassian.net/browse/FOUR-12885)
[FOUR-12885]: https://processmaker.atlassian.net/browse/FOUR-12885?atlOrigin=eyJp …
=> FOUR-12885: Added migration to convert status column from enum to varchar

ProcessMaker/Observers/UserObserver.php, database/seeders/PermissionSeeder.php, tests/Feature/Api/PermissionsTest.php, tests/Feature/Api/UsersTest.php, upgrades/2023_12_21_142322_create_permission_view_process_catalog.php
The permission View Process Catalog, needs to enable per Default for the new users
- https://processmaker.atlassian.net/browse/FOUR-12992
ci:deploy
ci:next
=> FOUR-12992: The permission View Process Catalog, needs to enable per Default for the new users

resources/js/processes/modeler/components/ModelerApp.vue
AI Unified project requires that the generated assets be shown on a reload to the Modeler project so that the bpmn has every assets in order and avoid a regeneration of screens and scripts already associated to the process's tasks.
- On core, modify the save-changes event to let the generateAssets() function on modeler be executed on a successful save of the process.
- https://processmaker.atlassian.net/browse/FOUR-12828
=> FOUR-12828: Save changes modified to suit AI asset generation

resources/js/components/templates/TemplateSearch.vue, resources/js/processes-catalogue/components/CatalogueEmpty.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Ticket: [FOUR-13011](https://processmaker.atlassian.net/browse/FOUR-13011)
If a user does not have any Guided Templates available, a 'No Templates' image should display when searching for templates. This is similar functionality to the 'No Processes' image that displays when there are no Processes available.
1. Go to branch `observation/FOUR-13011` in `processmaker`.
2. If you have Guided Templates, wipe them from your database.
3. Go to Processes → Guided Templates.
4. An image should appear letting the user know that no Guided Templates are available.
ci:next
[FOUR-13011]: https://processmaker.atlassian.net/browse/FOUR-13011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13011 | Display a ‘No Templates’ Image When Searching for a Template

resources/views/auth/passwords/change.blade.php
It shows us the window to change the password, but very quickly it shows us that {{error}} label in red, then it is lost
1. Log in 
2. create a user
3. enable the option "User must change password at next login"
4. Log out
5. and login with the created user
[FOUR-12766](https://processmaker.atlassian.net/browse/FOUR-12766)
ci:next
ci:deploy
[FOUR-12766]: https://processmaker.atlassian.net/browse/FOUR-12766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12766 error label in the frame of changing a user's password

resources/sass/app.scss
Ticket: [FOUR-13015](https://processmaker.atlassian.net/browse/FOUR-13015)
When 'Use Now' is selected from the Guided Template details modal, the modal changes size when loading the Helper Process.
Set a fixed height on the modal so that the modal does not visibly change size when the Helper Process is loaded.
1. Go to branch `observation/FOUR-13015` in `processmaker`.
2. Go to Processes → Guided Templates.
3. Select the available Guided Template.
4. When the modal opens, select the 'Use Now' button.
- The modal should not change size when the Helper Process is loaded.
ci:next
[FOUR-13015]: https://processmaker.atlassian.net/browse/FOUR-13015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13015 | When ‘Use Now’ is Clicked in the Slide, the Modal Changes Size Before Loading the Next Slide

resources/js/processes-catalogue/components/Breadcrumbs.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/WizardTemplates.vue
Ticket: [FOUR-13040](https://processmaker.atlassian.net/browse/FOUR-13040)
Currently, when a user clicks on a process from the ‘Available Processes’ dropdown, the process name appears in the breadcrumbs, but this doesn’t update when you click on ‘Guided Templates’.
Add Breadcrumb functionality for the Guided Templates option under 'Add From Templates' via the Breadcrumbs component.
1. Go to branch `observation/FOUR-13040` in `processmaker`.
2. Go to Processes → Guided Templates.
- A breadcrumb should display for 'Guided Templates'.
- When clicking between 'Guided Templates' and options for 'Available Processes', the breadcrumbs should update accordingly.
ci:next
[FOUR-13040]: https://processmaker.atlassian.net/browse/FOUR-13040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> FOUR-13040 | Update Breadcrumbs When User Clicks on Guided Templates

resources/js/processes-catalogue/components/utils/Card.vue
- [FOUR-12815](https://processmaker.atlassian.net/browse/FOUR-12815)
ci:deploy
ci:next
[FOUR-12815]: https://processmaker.atlassian.net/browse/FOUR-12815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12815:Long process names overflow cards in Launch Pad

ProcessMaker/Managers/DataManager.php, ProcessMaker/Observers/ProcessRequestObserver.php
The case number is not displayed in the Case Title column in a process with web entry.
- Update magic variable `_request` always to calculate `case_title`
- Import attached process 
- Copy web entry URL
- search process and edit
- Click on web entry 
- Go to configuration
- Click on web entry 
- Copy web entry URL
First scenario: Request in progress 
- Open web entry
- Open new browser
- Paste Url
- Fill any value in New Input field
- Click on submit button
- Go to PM4
- Click on Request tab
- Go to All request page
Second scenario: Request completed
- Open web entry
- Open new browser
- Paste Url
- Fill any value in New Input field
- Click on submit button
- Go to PM4
- Search last request of process
- Click on Form task
- Click on submit button
- Click on Request tab
- Go to All request …
=> FOUR- 13061 Fix The case number is not displayed in the Case Title column in a process with web entry.

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
- [FOUR-12960](https://processmaker.atlassian.net/browse/FOUR-12960)
ci:deploy
ci:next
[FOUR-12960]: https://processmaker.atlassian.net/browse/FOUR-12960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12960:The list of processes is not reset when you select the same tab

resources/js/components/templates/SelectTemplateModal.vue
Ticket: [FOUR-12752](https://processmaker.atlassian.net/browse/FOUR-12752)
Within a Project, if a user creates a Process using Generative AI, the Create Process Modal is not automatically filled with the Project that they were working in.
Pass the Project ID to the Package AI Process Creation page. From there, pass the Project ID to the Create Process Modal.
1. Go to branch `observation/FOUR-12752` in `processmaker`.
2. Go to branch `observation/FOUR-12752` in `package-ai`.
3. Have a Project Created. Open the Project.
4. Click +ASSET and create a new Process from AI.
- When taken to the `/package-ai/processes/create` route, there should be a Project ID appended to the end of the link.
5. Generate a Process and select 'Use Model'.
6. In the Create Process modal, the Project field should …
=> FOUR-12752 | Processes Generated from AI, Within a Project, Aren’t Being Created With the Project Assignment

resources/js/processes/scripts/components/CreateScriptModal.vue
Ticket: [FOUR-12978](https://processmaker.atlassian.net/browse/FOUR-12978)
When logged in with a non-Admin User, we receive a console error when attempting to create a copy of a Script within a Project.
The console error was coming from the `getAdminUser()` method in CreateScriptModal.vue. This method, and it's refereence, were removed in [this PR](https://github.com/ProcessMaker/processmaker/pull/5778) for ticket [FOUR-12744](https://processmaker.atlassian.net/browse/FOUR-12744).
The method was re-added in this [PR](https://github.com/ProcessMaker/processmaker/pull/5836) for [FOUR-12877](https://processmaker.atlassian.net/browse/FOUR-12877). However, the `userRunScript` value was not being passed to the method, which resulted in a console error. 
Because the `runAsUserDefault` prop is …
=> FOUR-12978 | Error In Console When Creating a Script Copy With a Non-Admin User

ProcessMaker/Models/ProcessRequestToken.php
Queries with case_title and case_number are not recognized in the tasks table and "PMQL is not valid" message appears
- Add support for `case_title`, `case_number` and `process_name` fields in PMQL queries
1. Import attached process
2. Create a new request
3. Fill any Name in New input field (for example test1)
4. Click on the submit button
5. Go to the Tasks tab
6. FIrst scenario:
a. Type case_title="CASE TITLE" in seach input (for example case_title="test1")
b. Type enter
7. Second scenario:
a. Type case_number=CASE#  in search input (for example case_number=41)
b. Type enter
[FOUR-13057](https://processmaker.atlassian.net/browse/FOUR-13057)
ci:next
ci:deploy
[FOUR-13057]: https://processmaker.atlassian.net/browse/FOUR-13057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> FOUR-13057 queries with case_title and case_number are not recognized in tasks table

ProcessMaker/Http/Controllers/Api/ProcessCategoryController.php, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue
As Participant/ Designer when open the Lauchpad, it will direct to the Uncategorized option of the menu. 
This is because is needed that user could see the avilable process.
https://processmaker.atlassian.net/browse/FOUR-13024
ci:next
=> Feature/FOUR-13024: Default option when user opens launchpad

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/utils/SearchCards.vue
- [FOUR-12988](https://processmaker.atlassian.net/browse/FOUR-12988)
ci:deploy
ci:next
[FOUR-12988]: https://processmaker.atlassian.net/browse/FOUR-12988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12988: UI Observation:  too much space between the Browser manu and process images

resources/js/components/shared/EllipsisMenu.vue, resources/js/processes/export/components/ExportSuccessModal.vue
Ticket: [FOUR-12755](https://processmaker.atlassian.net/browse/FOUR-12755)
When a non-Admin User with Project permissions attempts to export a Process asset within a Project, successful export occurs, but the subsequent redirect to `/designer/processes` results in a 'Not Authorized' page due to the user's lack of Process permissions.
After exporting a Process from a Project, the user is redirected back to the Project instead of the Processes Listing page. The `AssetRedirectMixin` in `core` was utilized to handle this solution.
1. Go to branch `observation/FOUR-12755` in `processmaker`.
2. Go to branch `observation/FOUR-12755` in `package-projects`.
3. Log in with a non-admin user that only has Project permissions.
4. Have a Project created. Open the Project.
5. Have a Process created …
=> FOUR-12755 | Non-Admin User With Project Permissions Can’t Export Processes Within Projects

resources/js/processes-catalogue/components/charts/ListChart.vue
The imported savedsearch library was removed
https://processmaker.atlassian.net/browse/FOUR-13111
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-13111 : CSS import in ListChart.vue forces the user / developer to have installed the package saved-search

ProcessMaker/Jobs/SyncWizardTemplates.php, ProcessMaker/Models/WizardTemplate.php, config/services.php, database/factories/ProcessMaker/Models/WizardTemplateFactory.php, resources/sass/app.scss
This PR introduces the Global Configuration Collection for Guided Templates, a crucial step in managing and storing all configured Guided Templates data.
The changes include:
1. Creating a collection seeder to initialize the global collection
2. Removing the deprecated `config_collection_id` column from the `wizard_templates` table via migration
3. Removing deprecated code related to collection imports in the wizard sync job
4. Updating the default branch reference for the `wizard-template` GitHub repo to `2023-winter` 
5. Make UI adjustments for a responsive modal when rendering the helper process.
1. Ensure the php artisan `processmaker:sync-wizard-templates` command has been executed, or run the command manually to sync the wizard templates.
2. Navigate to `Processes > Guided …
=> Implement Global Configuration Collection for Guided Templates

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/views/processes/modeler/index.blade.php
This PR resolves https://processmaker.atlassian.net/browse/FOUR-13088
- Add to modeler a variable to check if package-ai is installed
- Go to modeler without install package-ai, verify that the AI Assistant icon does not shows.
- Go to modeler after install package-ai, verify that the AI Assistant icon shows.
- [FOUR-13088](https://processmaker.atlassian.net/browse/FOUR-13088) 
- [FOUR-12816](https://processmaker.atlassian.net/browse/FOUR-12816)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/5922)
- [Modeler PR](https://github.com/ProcessMaker/modeler/pull/1775)
[FOUR-13088]: https://processmaker.atlassian.net/browse/FOUR-13088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-12816]: …
=> Observation/FOUR-13088: Check if package-ai is installed for Ai Unified generation

resources/js/processes-catalogue/components/CatalogueEmpty.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue
1. Log in 
2. Clcik on processes 
3. Click on “Show Me  The templates“
- https://processmaker.atlassian.net/browse/FOUR-12794
ci:next
=> Feature/four 12794: The show me the templates button does not show the available templates

resources/js/processes/scripts/components/LanguageScript.vue
The names of the list Script Executors have the same identifier
- Change identifier for the executors items.
Have executors created with the same name.
create a script and select an executor script.
- [https://processmaker.atlassian.net/browse/FOUR-12883](FOUR-12883)
=> It is not possible to select script executor with the same configuration

resources/js/processes-catalogue/components/ProcessesCarousel.vue
-  Open any Process in Launchpad
- Add Images to Carousel
- Carousel should be stopped and images changes only with click on small Indicators (small horizontal lines over the image)
https://processmaker.atlassian.net/browse/FOUR-13112
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-13112: Carousel of images should not be automatic

resources/js/processes-catalogue/components/Breadcrumbs.vue
- [FOUR-13115](https://processmaker.atlassian.net/browse/FOUR-13115)
ci:deploy
ci:next
[FOUR-13115]: https://processmaker.atlassian.net/browse/FOUR-13115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13115:UI: the Process Browser is  very close to the breadcrumb

.github/workflows/deploy-pm4.yml
ci:package-data-sources:FOUR-12410
ci:DATASOURCES_TEST_ENV="Custom Env Var From CI"
ci:modeler:FOUR-12410
ci:screen-builder:FOUR-12410
ci:deploy
..
=> FOUR-12410 Use K8S CICD Pipeline - develop branch

resources/js/processes-catalogue/components/menuCatologue.vue
- [FOUR-12987](https://processmaker.atlassian.net/browse/FOUR-12987)
ci:deploy
ci:next
[FOUR-12987]: https://processmaker.atlassian.net/browse/FOUR-12987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-12987:UI observation the line between Processes and Templates is missing

ProcessMaker/Http/Middleware/SessionControlBlock.php, ProcessMaker/Http/Middleware/SessionControlKill.php, ProcessMaker/Listeners/UserSession.php
The user remains logged in in the different browsers
- Include IP address check into session control and kill logic 
1. Log in 
2. Create a new user
3. From admin user configure IP Restriction
a. Go to Admin tab
b. Go to settings option in sidebar menu
c. Go to Session Control tab
d. Go to IP Restriction and edit
e. Enable Kill existing session
f. Click on save button
4. Login with a new user in different browsers (in the same IP same device)
[FOUR-13091](https://processmaker.atlassian.net/browse/FOUR-13091)
ci:next
ci:deploy
[FOUR-13091]: https://processmaker.atlassian.net/browse/FOUR-13091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13091 enable kill existing session is not working with different browsers

resources/js/processes/scripts/components/LanguageScript.vue
- Go to the Script page
- Click on + Script
- Fill all field except the selection of the language 
- Click on Save button
If I do not select un executors the error message is not visible 
The executors box should be painted or have a mark to know that the error is there because we have to scroll down to know about the error
- In sync with Franz Villaroel a red border is added when language is not selected
- [FOUR-12884](https://processmaker.atlassian.net/browse/FOUR-12884)
[FOUR-12884]: https://processmaker.atlassian.net/browse/FOUR-12884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-12884: The error message when a language is not selected is not seen

resources/js/processes-catalogue/components/utils/Card.vue
There is no default icon on the process cards
- Load the default icon or the custom
Create a new process
Does not select any icon in launch pad settings
Save the changes
Go to process-catalogue
Search the process
Check the card
- [FOUR-13159](https://processmaker.atlassian.net/browse/FOUR-13159)
ci:deploy
ci:next
[FOUR-13159]: https://processmaker.atlassian.net/browse/FOUR-13159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13159:There is no default icon on the process cards

ProcessMaker/Http/Controllers/ProcessController.php, resources/js/processes/export/components/CustomExportView.vue, resources/js/processes/export/components/ExportSuccessModal.vue, resources/js/processes/export/components/MainAssetView.vue, resources/js/processes/export/index.js, resources/views/processes/export.blade.php
Ticket: [FOUR-12755](https://processmaker.atlassian.net/browse/FOUR-12755)
When a non-Admin User with Project permissions attempts a Custom Export of a Process asset within a Project, successful export occurs, but the subsequent redirect to 'designer/processes' results in a 'Not Authorized' page due to the user's lack of Process permissions.
After completing a Custom Export of a Process from a Project, the user is redirected back to the Project instead of the Processes Listing page. 
The `projectId` is retrieved from the Export URL (`/processes/{processId}/export?project_id={projectId]`) and passed to the appropriate views. The projectId is then used to return the user back to their Project after Custom Export.
1. Go to branch `observation/FOUR-12755-b` in `processmaker`.
3. Log in with a …
=> FOUR-12755 | Non-Admin User With Project Permissions Can’t Custom Export Processes Within Projects

resources/js/components/templates/TemplateSearch.vue, resources/js/components/templates/WizardTemplateDetails.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue
This PR introduces link generation for triggering guided template modals. The PLG team can access the modal either within the UI by navigating to the targeted guided template or via URL generation methods. 
Two URL parameters are added to facilitate this functionality: 
1. `/processes-catalogue?guided_templates=true` is used to navigate directly to the guided templates section
2. `/processes-catalogue?guided_templates=true&template=[TEMPLATE_ID]` is utilized to open a specific guided template modal. 
example `/processes-catalogue?guided_templates=true&template=1`
1. Ensure guided templates are synced in your environment `php artisan processmaker:sync-wizard-templates`.
2. Navigate to the Processes section.
3. Note the URL.
4. Select 'Guided Templates.'
5. Verify that the URL is updated …
=> Implement link generation for triggering guided template modals

resources/js/processes-catalogue/components/RequestTab.vue
Requests completed are not listed in the Requests Table
- The requests completed should be listed in the request table
Create  a process
Create a requests
Complete the request
Go to process-catalogue
Search the requests completed
Current Behavior
The requests completed are not listed in my requests 
- https://processmaker.atlassian.net/browse/FOUR-13082
ci:next
ci:deploy
=> FOUR-13082: Requests completed are not listed in the Requests Table

ProcessMaker/Traits/HideSystemResources.php
This PR introduces the HideSystemResources trait for collections, specifically to hide the Guided Template Collection from the UI. This trait ensures that system-related collections, such as the one for guided templates, are not visible in the user interface.
1. Navigate to the Collections section.
2. Verify that the Global Template Collection is not visible in the UI.
-  [FOUR-13197](https://processmaker.atlassian.net/browse/FOUR-13197)
- Collections PR - https://github.com/ProcessMaker/package-collections/pull/375
ci:next
ci:package-collections:observation/FOUR-13197
[FOUR-13197]: https://processmaker.atlassian.net/browse/FOUR-13197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement HideSystemResources Trait for Guided Template Collection

resources/js/components/requests/modal.vue, resources/js/components/requests/modalMobile.vue, resources/js/components/requests/requestModal.vue
Change the label of +REQUEST Button to +CASE
- Change the label of +REQUEST Button to +CASE
- Open ProcessMaker in desktop mode
- See the change
- Open ProcessMaker in mobile mode
- See the change
https://github.com/ProcessMaker/processmaker/assets/8028650/693fe9de-8653-43e3-8b61-94c738511692
- https://processmaker.atlassian.net/browse/FOUR-13161
ci:next
ci:deploy
=> FOUR-13161 Change the label of +REQUEST Button

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue
The show me the templates button does not show the available templates
1. Log in 
2. Clcik on processes 
3. Click on “Show Me  The templates“
https://processmaker.atlassian.net/browse/FOUR-12794
ci:next
ci:deploy
=> feature/FOUR-12794: The show me the templates button does not show the available templates

resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/utils/SearchCategories.vue
2. Go to Process catalogue
3. Enter a process inexistent o invalid search like xxxxxxxxxx
4. Clear the input search
5. Click on search button
After entering an invalid search the category search engine stops working 
- [FOUR-13204](https://processmaker.atlassian.net/browse/FOUR-13204)
ci:deploy
ci:next
[FOUR-13204]: https://processmaker.atlassian.net/browse/FOUR-13204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13204:After entering an invalid search the category search engine stops working

ProcessMaker/Http/Controllers/Process/ModelerController.php, ProcessMaker/Http/Controllers/Process/ScriptController.php, resources/js/processes/scripts/components/CreateScriptModal.vue, resources/views/processes/modeler/index.blade.php
- Click on Processes menu
- Click on +Process
- Click Build Your Own
- Set the information and Save
- Drag and Drop the AI Generated control
- Select the Script From Text option for the control
- Set the information required and click on Save
Nothing happens, there is no action to save and continue, but if opens the Advanced Options menu it displays that the Run Script As option is required
The option Run Script As should be displayed out of the Advanced Options as it is required
- Add default user in run as default in modeler AI Script Generation
- [FOUR-13209](https://processmaker.atlassian.net/browse/FOUR-13209)
- [package-ai PR …
=> Observation/FOUR-13209: Save button is not working when create a AI Script

resources/js/processes-catalogue/components/ProcessMap.vue
1. Create a user with permission in process catalog and project
2. Login with the user-created
3. Go to Process catalog
The are no options in ellipsis menu Launch Pad for users wihout full permission 
https://processmaker.atlassian.net/browse/FOUR-13073
ci:next
ci:deploy
=> feature/FOUR-13073: There are not options in elipssis menu for launch pad

resources/views/processes-catalogue/index.blade.php
- Go to Launch pad menu
- Click on a process
- Click on the ELipsis menu
- Check Add Project option
There si not option Add project option
**Expected Behavior** 
The Add project option should be present in options menu to launch pad as figma 
https://processmaker.atlassian.net/browse/FOUR-13059
ci:next
ci:deploy
=> feature/FOUR-13059: Add project options is not present in menu options of Launch Pad

resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/utils/SearchCategories.vue
There is no separation line on the Search category and categories in LaunchPad .
ci:deploy
ci:next
=> FOUR-13200:There is not separation line on Search category and categories in LaunchPad

.github/workflows/deploy-pm4.yml
Add phpunit config back into ci pipeline
=> Enable phpunit

ProcessMaker/Jobs/SyncWizardTemplates.php
This PR addresses an issue where, if a guided template name was changed, the deprecated template name would still exist within the instance. To fix this, the PR introduces a check during the syncing process to remove any templates that are not part of the index.json file generated within the wizard templates repo. This ensures that only the templates listed in the latest index.json file are present in the instance.
1. Test this in your local environment.
2. Ensure you already have the old 'Invoice Approval' template in your instance.
3. Run the command php artisan processmaker:sync-wizard-templates.
4. View the guided templates.
5. Confirm that only one guided template is present, and its name is updated to 'Guided Invoice Approval'.
- https://processmaker.atlassian.net/browse/FOUR-13201 …
=> Resolve Issue with Deprecated Guided Template Names

resources/js/components/shared/FilterTable.vue, resources/js/processes/categories/components/CategoriesListing.vue, resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
- Log in 
- Click on Designer 
- Click on Processes
As we see the UI of the list of processes, It is showing with a space at the bottom of the screen
()please see the image attached in the ticket)
- Calculate the height based on the viewport height.
- [FOUR-13181](https://processmaker.atlassian.net/browse/FOUR-13181)
[FOUR-13181]: https://processmaker.atlassian.net/browse/FOUR-13181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-13181: UI the process list needs to take up the entire screen size at the bottom

ProcessMaker/Http/Controllers/Api/UserController.php
This PR includes a check for the 'create-projects' permission when accessing the show method in the UserController. The addition of this permission allows users with Project permissions to configure project members in their projects.
1. Create a user with only Project permissions.
2. Log in as the user.
3. Create a project.
4. Add members to the project.
5. From the ellipsis menu, select 'Configure'.
6. Confirm that no errors appear when opening the configuration modal.
7. Verify that the preselected project members are visible.
8. Add or remove users.
9. Confirm that no errors occur during the process.
- https://processmaker.atlassian.net/browse/FOUR-13210
ci:next
=> Add Permission Check for Project Configuration in UserController@show

resources/js/components/templates/WizardTemplateDetails.vue
This PR modifies the button text for Guided Templates from 'Use Now' to 'Get Started' for improved clarity.
2. Select a Guided Template.
3. Confirm that the button text now reads 'Get Started'.
- https://processmaker.atlassian.net/browse/FOUR-13217
ci:next
=> Update Guided Templates Button Text to 'Get Started'

ProcessMaker/Http/Controllers/Api/UserController.php, resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json
Validation is missing when the user does not have their cell phone number configured correctly and chooses By message to phone number in 2FA.
- Add validation for Cell phone number
- https://processmaker.atlassian.net/browse/FOUR-13223
=> FOUR-13223 Validate Cell phone number when 2FA SMS is enabled

resources/js/components/templates/WizardTemplateCard.vue, resources/js/processes-catalogue/components/WizardTemplates.vue
This PR reduces the space between the Category List and Guided Templates to align with the spacing of Available Processes.
2. Observe the spacing between the Category List and Guided Templates.
3. Confirm that the space is reduced to match the spacing with Available Processes.
- https://processmaker.atlassian.net/browse/FOUR-13175
ci:next
=> Adjust Spacing Between Category List and Guided Templates

upgrades/2023_12_06_182508_add_session_control_settings.php
Helper is not consistent with PRD.
- Change helper to: Restrict logins made by the same user from the same IP.
- https://processmaker.atlassian.net/browse/FOUR-13229
ci:next
ci:deploy
=> FOUR-13229 Change settings helper

ProcessMaker/Http/Middleware/ProcessMakerAuthenticate.php
A non-admin user with permission to edit your password cannot edit it
- Refactor has permission handling
1. Login
2. Configure Password Set By User
1. Go to admin tab
2. Go to setting option in sidebar menu
3. Click on Log-In Options
4. Enable Password Set By User
3. Create an user
4. Assign permission to user
1. Search user and edit 
2. Go to permission tab 
3. Enable "Edit Personal Profile" in Users 
4. Enable "Edit User And Password" in Username and password 
5. Click on save button
5. Log in with new user
6. Go to avatar
7. Click on Edit user Profile
8. The user must be able to change their password
[FOUR-13205](https://processmaker.atlassian.net/browse/FOUR-13205)
ci:next
ci:deploy
[FOUR-13205]: https://processmaker.atlassian.net/browse/FOUR-13205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> FOUR-13205 non-admin user cannot edit its password with permission to edit

ProcessMaker/Filters/Filter.php
1. Go to server https://ci-2d99bcfae6.engk8s.processmaker.net/
2. Go to Requests page
3. Select Regex option in the filter modal
4. Press apply button
The table is displayed empty
- [FOUR-13166](https://processmaker.atlassian.net/browse/FOUR-13166)
ci:deploy
ci:next
[FOUR-13166]: https://processmaker.atlassian.net/browse/FOUR-13166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13166: filter option are not working correctly

upgrades/2023_12_14_160541_populate_process_requests_case_number.php
Query to populate the Case title has the same condition twice
- Remove the condition repeated
`process_requests.process_id = category_assignments.assignable_id`
Run execute upgrade
`nginx php  artisan upgrade --force`
- https://processmaker.atlassian.net/browse/FOUR-13253
ci:next
ci:deploy
=> FOUR-13253: Query to populate the Case title has the same condition twice

.github/workflows/deploy-pm4.yml
=> Four 13153 FIX CICD

resources/js/components/templates/WizardHelperProcessModal.vue, resources/js/components/templates/mixins/wizardHelperProcessModal.js
This PR resolves an intermittent 422 error that occurred when running a guided template helper process. The issue was caused by attempting to update a task status to 'completed' through an API request when the task had already been completed. 
The solution involves checking the task's `advanceStatus` to ensure that it has not already been marked as completed before making the API request.
Note: The issue was encountered on CI servers and could not be replicated locally. However, to test the resolution:
1. Navigate to Processes -> Guided Templates.
2. Select a guided template.
3. Click on 'Get Started' and run through the process.
4. Ensure that no 422 errors occur.
5. Upon completion of the guided template, run another guided template.
6. Confirm that no 422 errors occur.
- …
=> Resolve intermittent 422 error in Guided Templates

ProcessMaker/Console/Commands/SyncGuidedTemplates.php, ProcessMaker/Console/Kernel.php, ProcessMaker/Jobs/SyncGuidedTemplates.php, config/services.php
This PR updates the `php artisan processmaker:sync-wizard-templates` command to `php artisan processmaker:sync-guided-templates`. Additionally, it modifies references in `services.php` files and updates variables and methods in the `SyncGuidedTemplate` files from `wizard` to `guided`.
- GUIDED_TEMPLATE_REPO
- GUIDED_TEMPLATE_BRANCH
- GUIDED_TEMPLATE_CATEGORIES
.
1. Ensure you have no guided templates in your database.
2. Run the command `php artisan processmaker:sync-guided-templates`.
3. Ensure the command runs with no errors.
4. Confirm that the guided template is updated in the database.
- https://processmaker.atlassian.net/browse/FOUR-13259
ci:next
=> Update Artisan Command and Environment Variables for Guided Templates Sync

resources/js/processes-catalogue/components/utils/Card.vue, resources/lang/en.json
1. Have to process
2. Go to Launch Pad
3. Open a process from cards
4. Marked as Favorite
5. Go to the Favorite category
6. Hover in a process marked as favorite
7. Check the title of tooltip
The title for the process in favorite category is incorrect, because these already marked as favorites 
[recording.webm](https://github.com/ProcessMaker/processmaker/assets/5005237/8ba33c31-4b22-4964-8538-134507f27acd)
- [FOUR-13248](https://processmaker.atlassian.net/browse/FOUR-13248)
ci:deploy
ci:next
[FOUR-13248]: https://processmaker.atlassian.net/browse/FOUR-13248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13248:Processes marked as favorites keep the same label in tooltip

resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue, routes/api.php
**Steps**
1. Create a new user
2. Login with this user
3. Go to Lauchpad and open the process
The following error apears
when the user does not have permission to start a case the button needs to disable
ci:next
ci:deploy
=> bugfix/FOUR-13250: Action Unauthorized: when the user does not have permission to start a Request

resources/js/components/shared/ModalSaveVersion.vue
This issue was partially solved, but this PR aims to completely fix this issue.
2. Search process and edit
3. Add any control to modeler
4. Click on publish button
- Deleted the extra message that appears when saving.
- https://processmaker.atlassian.net/browse/FOUR-12977
=> FIX/FOUR-12977: Removed 'version saved' message on Modeler save

.github/workflows/deploy-pm4.yml
=> FIX delete instance

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Models/Process.php, resources/js/processes-catalogue/components/CardProcess.vue
Process in category inactive are listed in All Processes>> Launchpad
- List only the processes related to the category = ACTIVE
1. Log in PM4
3. Create a category
4. Assign the process to category
5. Inactive the category created
6. Go to Launchpad
7. Click on All Processes
8. Search the process in category inactive
- https://processmaker.atlassian.net/browse/FOUR-13321
ci:next
ci:deploy
=> FOUR-13321: Process in category inactive are listed in All Processes>> Launchpad

resources/js/components/shared/ModalSaveVersion.vue
- Extra space between dropdown and title FIXED
- Select Chart Dropdown has an internal scrollbar in case of too many charts
- Create many SAved Search Charts
- Go to Process Launchpad
- Open in Launchpad
- Check "Chart List"
https://processmaker.atlassian.net/browse/FOUR-13324
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-13324: The Select Chart title has a little separation than the other controls

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Steps to Reproduce
Have many categories in process
Go to Launchpad
Scroll down the categories
Try scrolling up to see the first category
Scroll infinite It's not working up in Launchpad
**Expected Behavior** 
Infinite scroll should work upwards
https://processmaker.atlassian.net/browse/FOUR-13325
ci:next
ci:deploy
=> bugfix/FOUR-13325 : Scroll infinite It's not working up in Launchpad

resources/js/components/templates/TemplateSearch.vue, resources/js/components/templates/TemplateSelectCard.vue
This PR addresses the extra space between guided templates when multiple templates are listed. The solution involves adding the col-3 class to the template select card container.
2. Open your inspector panel.
3. Locate the div with the class template-select-card-container.
4. Duplicate the div so that more than one guided template is displayed.
5. Ensure the spacing between the divs matches the spacing in the mockup.
- [https://processmaker.atlassian.net/browse/FOUR-13357](https://processmaker.atlassian.net/browse/FOUR-13357)
ci:next
=> Reduce Spacing Between Guided Templates

resources/js/processes/categories/components/CategoriesListing.vue, resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
Up and down buttons do not reset after selecting the button in another column
reset the up and down buttons properties after another column is selected
We added the solution for the templates and categories tabs, the processes and archived processes tabs solution are on the ticket FOUR-13307 to avoid conflicts
https://processmaker.atlassian.net/browse/FOUR-13168
ci:next
=> observation/FOUR-13168-B up and down buttons do not reset after selecting the button in another column 

resources/js/components/templates/TemplateSearch.vue
1. Go to Launch Pad
2. Click on Guided templates 
3. Click on Search engine of templates
There is not clear option in the search engine for templates
https://processmaker.atlassian.net/browse/FOUR-13338
ci:next
ci:deploy
=> bugfix/FOUR-13338: There is not clear option in the search engine for templates

ProcessMaker/Http/Controllers/Api/UserController.php
When clearing a given user's avatar (whether your own or another user's) after saving, a broken image continued to show everywhere the user's avatar would appear instead of the default initials.
1. Log in as a user with profile editing permissions
2. Navigate to edit your profile
3. Upload a photo for your avatar and save your profile
4. Notice your avatar update across the site, including on the same page
5. Now go back to edit your profile and clear your avatar and save
6. Notice the broken image(s) appearing everywhere your avatar is. This should be the default of the user's first and last initials as displayed in the preview.
The `avatar` column in the `users` table was not being emptied and persisted after the avatar image was removed from the filesystem. The fix was simple, to empty …
=> FOUR-13316: Properly clear the user's avatar when saved

resources/js/processes/components/ProcessesListing.vue
Server Error when sort option is used in the last column in the Processes page
Add a sort validation on process list
https://processmaker.atlassian.net/browse/FOUR-13368
ci:deploy
ci:next
=> observation/FOUR-13368 Server Error when sort option is used in the last column in the Processes page

resources/js/admin/settings/components/SettingText.vue, resources/js/admin/settings/components/SettingsListing.vue
After filtering any of the settings tables, when you attempt to clear the filter, the settings do not return. Instead, multiple  exceptions are thrown due to properties being called which don't exist, halting the entire components functionality.
1. Set core to this branch `bugfix/FOUR-13601` (and all enterprise packages set to their `next` branch)
2. Set package-auth to [`bugfix/FOUR-13601`](https://github.com/ProcessMaker/package-auth/pull/96)
3. Log in as an administrator and navigate to the settings page
4. Click on any of the tabs and attempt to filter with a string of text which yields no results (e.g. `asdadfkj`) and hit enter
5. Attempt to clear the filter to reset the settings
6. Notice the settings do not return and multiple exceptions are thrown
- Tweaking the logic of when to …
=> FOUR-13601: Settings not returning after clearing filter

resources/js/processes/components/ProcessMixin.js, resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
When the filter is used, the page stays with the last one that was changed.
- Switch to the first page when using the filter.
- Have multiple pages of process templates.
- change to another page other than the first.
- When the search is performed it should change to the first page.
- [https://processmaker.atlassian.net/browse/FOUR-13247](FOUR-13247)
ci:next
=> The pager in templates does not work correctly when you do a non-existent search

resources/js/bootstrap.js, resources/js/processes/screen-builder/screen.vue, resources/js/requests/components/screenDetail.vue
The css wasn't being applied when looking at a screen in a process (running)
- Importing the CSS globally instead of per page
- https://processmaker.atlassian.net/browse/FOUR-13919
ci:next
ci:deploy
=> FOUR-13919 Importing the screen builder css globally instead of per page

resources/js/bootstrap.js
Screen Builder exports wasn't available when using an external package.
- Requiring the whole screen builder package instead of the default export
- https://processmaker.atlassian.net/browse/FOUR-13932
ci:next
ci:deploy
=> Making Screen Builder export globally available, the right way

resources/js/tasks/components/TasksList.vue
The status of a task self service is shown as in progress
Fix the condition for the Self Service status badge badge
Log in 
Have a process that the second task goes to Self Service
Start a new case
Go to tab task
Click on self service option
https://processmaker.atlassian.net/browse/FOUR-13907
ci:deploy
ci:next
=> observation/FOUR-13907 The status of a task self service is shown as in progress

resources/js/processes/designer/RecentAssets.vue
The Title should change from RECENT ASSETS FROM MY PROJECTS to RECENT ASSETS
The Recent Assets section should show all the recent Assets edited by the user not only the Assets of the Projects
- [FOUR-13378](https://processmaker.atlassian.net/browse/FOUR-13378)
ci:deploy
ci:next
[FOUR-13378]: https://processmaker.atlassian.net/browse/FOUR-13378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13378:Recent Assets Section for Designer Welcome Screen

resources/js/components/shared/FilterTable.vue, resources/js/processes/categories/components/CategoriesListing.vue, resources/js/processes/components/ArchivedProcessList.vue, resources/js/processes/components/ProcessesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
**Steps to reproduced:**
- Go to process
- Click on ellipsis of any process
- Shrink the screen a little
- View the ellipsis options
You can no longer see all the ellipsis options.
You should be able to see all the options even if the screen is reduced.
- Added max height and scrollbars to the menu.
https://github.com/ProcessMaker/processmaker/assets/90727999/1800843b-286a-4410-9d15-e57c1325363b
Open the ellipsis menu and verify a scrollbar is added for larger menus
- FOUR-13815
ci:deploy
=> Observation/FOUR-13815: Ellipsis options are not shown if the screen is reduced in process

resources/js/bootstrap.js, resources/js/processes/categories/components/CategoriesListing.vue, resources/js/processes/components/ArchivedProcessList.vue, resources/js/processes/components/ProcessesListing.vue, resources/lang/en.json
See https://processmaker.atlassian.net/browse/FOUR-13938
ci:next
=> Fix translations

ProcessMaker/Http/Controllers/TemplateController.php, resources/js/components/templates/TemplateAssetsView.vue, resources/js/components/templates/mixins/wizardHelperProcessModal.js, resources/js/templates/assets.js, resources/views/templates/assets.blade.php
Currently, when the Guided Templates process is completed and "Save and Finish" is clicked, it redirects to the assets page. However, the assets do not load and an error `window.history.state is undefined` appears in the console.
- The problem is related to the use of `history.pushState`. Redirecting causes these data to be lost.
- The suggested solution is to use localStorage instead.
- Other adjustments are formatting changes made by eslint and php-cs-fixer.
- Update your Guided Templates with the latest version from the 2023-winter branch.
- Run the "Guided invoice approval" wizard.
- Ensure that the existing assets are correctly displayed on the /template/assets screen.
- Check that the "continue" button functions properly and that the template is created without issues.
- …
=> FOUR-13361: Incorrect Redirection After Completing a Guided Template Process

resources/js/processes/categories/components/CategoriesListing.vue, resources/js/templates/components/ProcessTemplatesListing.vue
**Steps to reproduced:** 
- Go to processes
- Click on template tab
- Sort a column ascendingly or descendingly
- Click on option to sort ascending or descending of the unlabeled column.
The option option to sort ascending or descending is displayed and when you click it, a server error is displayed.
This ascendingly or descendingly option should not be displayed in this column.
- Check if column is sortable in templates and categories.
- [FOUR-13960](https://processmaker.atlassian.net/browse/FOUR-13960)
[FOUR-13960]: https://processmaker.atlassian.net/browse/FOUR-13960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ci:next
ci:deploy
=> Observation/FOUR-13960: Server error when using sort ascending or descending in taps, process categories, templates

ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Traits/ProjectAssetTrait.php
Ticket: [FOUR-13834](https://processmaker.atlassian.net/browse/FOUR-13834)
After adding assets to a project, removing assets from a project, or duplicating assets within a project, the 'Modified' date is not updated in the Projects Listing.
Add a method to the `ProjectAssetTrait.php` file called `updateProjectUpdatedAt`. This method updates the `updated_at` database field for projects. The method is called within the `syncProjectAssets` function, as many project assets utilize this function when they are updated. For any endpoints where project assets are being updated, but the `syncProjectAssets` method is not being called, the `updateProjectUpdatedAt` method is called directly in that asset's controller.
1. Go to branch `observation/FOUR-13834` in `processmaker`.
2. Go to branch …
=> FOUR-13834 | The Modified Date in Projects Isn’t Updated After Making Changes to the Project

ProcessMaker/Http/Middleware/SessionControlBlock.php, ProcessMaker/Http/Middleware/SessionControlKill.php, ProcessMaker/Models/UserSession.php
The application is only logged in again when we log in with browser 1, which was the one that had the session.
Check all active sessions in block session by device
1. login with a user with device 1 
2. have the "Block duplicate session" option in device restriction enabled
3. I will open another device 2
4. try to log in with the same username from the other browser (this is correct)
5. We go to device 1 and log out
6. We return to device 2 and try to log in again
[FOUR-13910](https://processmaker.atlassian.net/browse/FOUR-13910)
ci:next
ci:deploy
[FOUR-13910]: https://processmaker.atlassian.net/browse/FOUR-13910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13910 block duplicate session in device restriction only works when the initial browser has the session open

resources/sass/app.scss
When dealing with flash messages and the string is too long, it's causing it to overflow the container and display the content outside of the alertBox.
-  Include `word-wrap: break-word` and `overflow-wrap: break-word` within the `.flash-message` to ensure that long words are broken and wrapped to the next line. 
- Create a project with a long name and without spaces.
- Open the project
- Add an asset to the Project
Please ensure that the message within the alert box does NOT overflow the container.
- Ticket: [FOUR-13473](https://processmaker.atlassian.net/browse/FOUR-13473)
[FOUR-13473]: https://processmaker.atlassian.net/browse/FOUR-13473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13473: Fix overflow string in the alertBox when the message is too long

resources/js/processes/designer/Assets.vue, resources/js/processes/designer/MyProject.vue, resources/js/processes/designer/RecentAssets.vue, resources/sass/app.scss
The Type of letter of the section’s title don’t look the same as Figma:
- Apply the same styles defined in figma
Login and Go to Designer
- [FOUR-13376](https://processmaker.atlassian.net/browse/FOUR-13376)
ci:deploy
ci:next
[FOUR-13376]: https://processmaker.atlassian.net/browse/FOUR-13376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13376:Type of letter of the square’s title are not the same as figma in Designer Welcome Screen

ProcessMaker/ProcessTranslations/ProcessTranslation.php
- Import attached process
- Confirm Spanish translation is set for Step 1 and 2 screens
- Click on web entry and copy URL
- Task is an anonymous web entry one, no need to set users.
- Open the URL in an Spanish browser (so ProcessMaker picks the language)
- Submit screen
At this point you will see that although the screen in the web entry was correctly shown in Spanish (from the browser), the one in the task didn’t, English labels were shown.
- Fix an issue searching the key in the array of languages.
- Fix an issue validating there are not user (when user is not logged in, anonymous user is used instead)
https://github.com/ProcessMaker/processmaker/assets/90727999/dfd4763e-0198-4ecf-868b-95baf5643771
- When a user is logged (or WE is authenticated) …
=> Observation/FOUR-12695: 35992 Screens in anonymous web entry tasks are not being translated

resources/js/components/templates/TemplateAssetsView.vue, resources/js/processes/components/CreateProcessModal.vue
When initiating a new Process from a Template, if the assets specified in the process already exist within the system, the expected behavior is to redirect the user to the AssetsTable page, where these pre-existing assets should be displayed. Currently, the redirection occurs as expected, but the assets themselves do not appear in the AssetsTable. This issue seems to suggest a loading or retrieval problem where the AssetsTable fails to fetch or render the existing assets in the context of the new Process creation
- The problem is related to the use of history.pushState. Redirecting causes these data to be lost.
- The suggested solution is to use localStorage instead.
- Navigate to Designer->Processes 
- Create a Process from a Template
- Navigate back to Designer->Processes 
- Create a …
=> FOUR-13995: Incorrect Redirection After Creating ProcessTemplate

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
This PR resolves issues with directing to the guided template modal via URL parameters. The parameters were being removed from the URL when loading, preventing the modal from appearing. The removal of the parameters was due to an outdated conditional that ran on deprecated code.
The solution is to update the conditional to only remove the parameters when the 'selectCategory' method has an 'undefined' value. This undefined value indicates that the user manually accessed the guided templates and did not load it directly from a URL.
2. Select a template.
3. Copy the URL.
4. Open a new tab/window.
5. Paste the copied URL.
6. Ensure the selected guided template modal appears.
ci:next
ci:deploy
- …
=> Fix URL Parameters for Guided Template Modals

resources/views/admin/users/edit.blade.php, resources/views/components/categorized_resource.blade.php
- login in the server https://next-qa.processmaker.net/
- Create a normal user
- Assign these permissions to normal user
- Create Processes
- Edit Processes
- View Processes
- Login with the new user
- Go to Designer > Processes
- Open the Categies tab
After sync with Claudia Iriarte, an user that have access to create/edit a process should view process categories.
I noticed two issues: 
The tabs in the top are getting the wrong labels because a problem with the indexes of the tabs after introduce the Templates feature (notice that you didn’t added permissions for templates, and you can see a Templates tab, but after clicking the templates tab, the list showing is the list of Categories instead of Templates. The same happens with the Categories tab, that should be Archived processes tab. …
=> Observation/FOUR-13323: Category is displayed without the correct permission

resources/js/components/templates/AssetLoadingModal.vue
Ticket: [FOUR-14010](https://processmaker.atlassian.net/browse/FOUR-14010)
The Cancel button in the AssetLoadingModal is not working.
- Change the `@hidden` property on the modal to `@close`.
1. Go to branch `observation/FOUR-14010` in `processmaker`.
2. Go to Designer → Processes. Create a Process from a Template.
3. Create another Process from the same Template so that you are taken to `/template/assets`.
4. Select 'Continue'.
5. Select 'Cancel' in the Confirmation modal.
- The modal should close when 'Cancel' is selected.
ci:next
[FOUR-14010]: https://processmaker.atlassian.net/browse/FOUR-14010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14010 | Fix Cancel Button for Selecting Existing Imported Assets 

resources/js/components/shared/PmqlInput.vue
The `pmql` field at Saved search inspector in screen builder is not being updated.
- Fix the reactivity of the inspector property and the pmql input control.
https://github.com/ProcessMaker/processmaker/assets/8028650/bc2dff70-5593-4b1b-8c73-a8f567bebba1
- Create a display screen and add a couple of Saved Search Charts
- Setup the pmql for each chart.
- Check that the pmql defined is stored for each control.
- https://processmaker.atlassian.net/browse/FOUR-14004
ci:deploy
ci:next
ci:package-savedsearch:bugfix/FOUR-14004
=> FOUR-14004 Fix Query of Saved Search Chart doesn't update correctly

ProcessMaker/ImportExport/Exporters/ExporterBase.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/ImportExport/Importer.php, ProcessMaker/Templates/ProcessTemplate.php
Ticket: [FOUR-13219](https://processmaker.atlassian.net/browse/FOUR-13219)
When creating a process from a template, the category assigned in the modal, 'Default Templates', is not assigned when the process is created.
Ensure that the user's selected category is not overwritten by the template manifest's category when the process is created from a template.
1. Go to branch `observation/FOUR-13219` in `processmaker`.
2. Go to Designer → Processes. 
3. Create a Process from a Template. Take note of the selected category.
4. Go to the Processes listing and view your created process.
5. The category associated with the Process should be the category that was selected in the Create Process Modal.
ci:next
[FOUR-13219]: https://processmaker.atlassian.net/browse/FOUR-13219?atlOrigin=eyJpIjoiNWRkNTl …
=> FOUR-13219 | The Processes Created From a Template Are Being Created With the Uncategorized Category

ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/SessionControlKill.php
The Kill existing session option in device restriction is not working correctly.
There are times when both browsers are in session, sometimes if the existing session is checked
- Run session control kill middleware before the `BROWSER_CACHE` middleware
1. Log in 
2. Go to Admin
3. Click on Settings
4. Enter Session Control
5. In Device Restriction choose the option `Kill existing session`
6. Login in a browser with a user
7. Login with the same user in another browser
8. We return to the first browser
9. We refresh or enter an option in the application
- [FOUR-13942](https://processmaker.atlassian.net/browse/FOUR-13942)
ci:next
ci:deploy
[FOUR-13942]: https://processmaker.atlassian.net/browse/FOUR-13942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
=> FOUR-13942 the kill existing session in device restriction is not working correctly

resources/js/components/templates/TemplateAssetTable.vue
After completing the steps, the message [Vue warn]: Duplicate keys detected: 'unknown' is displayed. This may cause an update error.
1. Click on Process tab
2. Click on Guide template
3. Click on any guide template
4. Click on Get Started
5. Complete Skip
- Currently, in the for loops, the keys were using the asset's name as a unique identifier. Now, this has been changed to use the `uuid` instead, which resolves the issues caused by having assets with the same name.
- Similarly, the name of the radio button has been updated to provide clear differentiation and enhance its usability.
Follow the reproduction steps of above.
- [FOUR-13586](https://processmaker.atlassian.net/browse/FOUR-13586)
[FOUR-13586]: https://processmaker.atlassian.net/browse/FOUR-13586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> FOUR-13586: Error in console after creating a guide template

resources/js/components/shared/PmqlInput.vue
This PR addresses an issue with the PMQL input component encountering an error related to the OpenAI endpoint. The problem stemmed from the component utilizing a deprecated endpoint `openai/nlq-to-pmql`. This PR resolves the issue by updating the endpoint to the new one.
- Update deprecated endpoint in favor of new endpoint
1. Create a new screen.
2. Add a select list component.
3. Configure the select list to utilize either a data source or collection.
4. In the PMQL input field, enter a command such as where.
5. Press Enter.
6. Verify that no errors are displayed.
[FOUR-14058](https://processmaker.atlassian.net/browse/FOUR-14058)
ci:next
[FOUR-14058]: https://processmaker.atlassian.net/browse/FOUR-14058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
=> Resolve OpenAI Endpoint Error in PMQL Input Component

resources/js/components/templates/WizardHelperProcessModal.vue, resources/js/components/templates/mixins/wizardHelperProcessModal.js, resources/js/processes-catalogue/components/ProcessOptions.vue
This PR adds a new property process_launchpad_id in the Helper Process request data object. This property will enable the PLG team to reference the process/launchpad id in which the re-run wizard helper process was initiated.
- Add `process_launchpad_id` property to request data for Guided Template Helper Processes
1. Run a Guided Template helper process.
2. Upon completion, select the 'Re-run wizard' link in the launchpad.
3. Close the modal to cancel the request, go to 'Requests -> All Requests'.
4. Locate the recently canceled request.
5. View the summary tab.
6. Ensure the property `process_launchpad_id` is present.
7. In the URL, update the URL to navigate to `/processes-catalogue/[PROCESS_LAUNCHPAD_ID]`.
8. Ensure the id corresponds to the correct launchpad. …
=> Add process_launchpad_id Property to Helper Process Request Data

ProcessMaker/Console/Commands/BuildScriptExecutors.php, ProcessMaker/Exception/InvalidDockerImageException.php
Fix for [FOUR-11513](https://processmaker.atlassian.net/browse/FOUR-11513)
ci:deploy
[FOUR-11513]: https://processmaker.atlassian.net/browse/FOUR-11513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-11513: Error integrating sdk-java

resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue
When launching a process from LaunchPad the insterstitials are not taking the user to the initial screen
- When we start a case we need to use the following flag `fromTriggerStartEvent`
- Create a process with a start - insterstitials
- Create a process with a start - without insterstitials
- Both use cases needs to have the same behaviour when you start a Request from the button 
- https://processmaker.atlassian.net/browse/FOUR-14056
ci:deploy
ci:next
=> FOUR-14056: When launching a process from LaunchPad the insterstitials are not taking the user to the initial screen

ProcessMaker/Templates/ProcessTemplate.php, resources/js/components/templates/mixins/wizardHelperProcessModal.js
This PR adds a new attribute helperProcessRequestId to the processes properties object. This attribute will enable the PLG team to reference the helper process request id that initiated the creation of the guided template process.
1. Run a Guided Template helper process.
2. Upon completion, check the database for the newly created process in the `processes` table.
3. Navigate to the `'properties'` column.
4. Ensure in the object a new `helperProcessRequestId` is set.
5. Take note of the newly created process id.
6. In your environment, create a new PHP script.
7. Paste the below provided code snippet.
8. Replace the `[NEW_PROCESS_ID]` placeholder in the `$guzzleApi` variable with the actual newly created process id.
9. Run the script.
10. Ensure the `helperProcessRequestId` is returned. …
=> Add helperProcessRequestId Attribute to Processes Properties

resources/js/processes/designer/ProjectsLastModifiedListing.vue
Correct the size of the column Modified
-` width: "auto"`
Go to designer
Create a project
see the Recent Projects
- [FOUR-14043](https://processmaker.atlassian.net/browse/FOUR-14043)
ci:deploy
ci:next
[FOUR-14043]: https://processmaker.atlassian.net/browse/FOUR-14043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14043:My Project: the column Modified increase the width

upgrades/2024_02_07_113706_web_entry_url_fixer.php
Previously, when a process was created from a template, the import process incorrectly generated the web entry URL, as it omitted the application URL. This issue was due to the use of `getenv('APP_URL')` instead of `config('app.url')`.
This PR resolves instances where the web entry URL does not include the application URL.
1. Have a process with web entry imported or created from a previous version.
2. Review the link `webentryRouteConfig.entryUrl`.  
3. For backward compatibilities is important to create a script to correct the entryUrl for all processes.
- An upgrade script has been developed to modify the web entry URL for all affected processes, but only when necessary, i.e., when the current web entry URL is not a valid URL.
Run the script.
Review in process-catalogue.
Before …
=> FOUR-14069: Create a script to correct the broken links related to the Web Entry

ProcessMaker/Providers/AuthServiceProvider.php, ProcessMaker/Traits/ProjectAssetTrait.php, resources/views/processes/screens/edit.blade.php, resources/views/processes/scripts/edit.blade.php
- Create a user with project permissions only.
- Create a project and assign it to the previously created user.
- Log in with the created user.
- Create a process from scratch. The process must contain tasks and scripts.
- Generate the process's assets using the AI Asset Generator.
-  Try to use the preview feature in one of the script of the created process.
A screen with an "Unauthorized" message is displayed
Process assets created for a process that pertains to a project must be accessible to users of the project, even if the users don't have the "view-scripts" and "view-screens" permissions.
https://processmaker.atlassian.net/browse/FOUR-14078
Related PR https://github.com/ProcessMaker/package-ai/pull/77
=> FOUR-14078: When creating scripts with AI, I find permissions issues preventing me from previewing them in the Preview Pane.

resources/views/components/categorized_resource.blade.php
- Log in
- Go to Designer 
- Click on Data Connectors
- Click on Log options
The categories tab in data connectors is not present, and when entering the Logs tab the categories of data connectors are being displayed
The categories tab should be shown in the data options connectors, and the Logs tab should show the logs, not the categories.
- Verify permissions and route for data connector and show the correct tags
- Follow steps above.
- Use different permissions for the user to activate/deactivate different tabs
- [FOUR-14044](https://processmaker.atlassian.net/browse/FOUR-14044)
- [package-data-sources PR](https://github.com/ProcessMaker/package-data-sources/pull/349)
[FOUR-14044]: https://processmaker.atlassian.net/browse/FOUR-14044?atlOrigi …
=> Observation/FOUR-14044: The Log option is showing the categories of data connectors, and the categories tab is not present in the options

ProcessMaker/ImportExport/Exporters/ExporterBase.php
In certain circumstances, running the `php artisan package-pm-blocks:sync-pm-blocks` artisan command would fail by throwing an uncaught exception (see output below). This was not consistent across instances as it would work for most, but a handful threw this exception.
```
Illuminate\Database\Eloquent\ModelNotFoundException 
No query results for model [ProcessMaker\Models\ProcessCategory].
at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:619
615▕         if (! is_null($model = $this->first($columns))) {
616▕             return $model;
617▕         }
618▕ 
➜ 619▕         throw (new ModelNotFoundException)->setModel(get_class($this->model));
620▕     }
621▕ 
622▕     /**
623▕      * Execute the query and get the first result or call a callback.
1 …
```
=> FOUR-13983: Ensure "Uncategorized" process category exists during import

resources/lang/en.json
- Login into PM
- Go to the /designer url
- Hover the Screens button
The translations has been fixed
https://processmaker.atlassian.net/browse/FOUR-14089
=> FOUR-14089: Assets view displays wrong label in the Screens button

composer.json, composer.lock, package-lock.json, package.json, resources/js/components/shared/FilterTableBodyMixin.js, resources/js/requests/components/RequestsListing.vue, resources/js/tasks/components/TasksList.vue
- Filters with UTC vonversion were applied to custom columns with datetime and date data type
- Complete a process with date and datetime fields in the screen
- Add custom date and datetime columns to a saved search.
https://processmaker.atlassian.net/browse/FOUR-14061
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-14061: Saved search custom date columns showing wrong date/time

ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Http/Controllers/TaskController.php, resources/views/requests/index.blade.php, resources/views/tasks/index.blade.php
Use `edit-screens` as permission to setup Requests and Tasks permissions.
- Use `edit-screens` as permission to setup Requests and Tasks permissions.
1. Create a user with permissions:
- edit-screens
- view-users
- view-groups
2. Login the that User
3. This User will have enabled a gear to configure the Columns of Requests and Tasks List
- https://processmaker.atlassian.net/browse/FOUR-13922
ci:deploy
ci:next
ci:package-savedsearch:FOUR-13922
.
=> FOUR-13922 Configurable Requests and Tasks columns

ProcessMaker/Listeners/LoginListener.php, ProcessMaker/Models/User.php
The "Last Login" column for the user list found in the admin dashboard was incorrectly parsing the datetime causing it to show a different date and time than when the user actually logged in.
1. Log in to the admin dashboard (be sure your user account has permissions to view all users).
2. Update your timezone in your user profile to be non-UTC +0 timezone.
3. Log out and log back in.
4. Navigate to the user list in the admin dashboard.
5. Sort by last logged in.
6. Notice the date/time differences between when you logged in and the date/time it displays.
The `loggedin_at` attribute had to be cast to `datetime` in the `ProcessMaker\Models\User` model.
With the fix, the correct date and time should now display for the "Last Login" column in the user listing.
ci:deploy
ci:next …
=> FOUR-10278: Display and parse correct date/time for "Last Login" user column

resources/js/processes/screen-builder/typeDisplay.js, resources/js/processes/screen-builder/typeForm.js
The Avatar is not the same in Home Option and Designer Option, since is the same user that was login.
- https://processmaker.atlassian.net/browse/FOUR-13370
https://github.com/ProcessMaker/screen-builder/pull/1531
ci:next
ci:deploy
ci:screen-builder:feature/FOUR-13370
=> feature/FOUR-13370: The Avatar is not working correctly as Participant and Designer

ProcessMaker/Providers/AuthServiceProvider.php
- Create a user with project permissions only.
- Create a project and assign it to the previously created user.
- Log in with the created user.
- Create a process from scratch. The process must contain tasks and scripts.
- Generate the process's assets using the AI Asset Generator.
-  Try to use the preview feature in one of the script of the created process.
A screen with an "Unauthorized" message is displayed
Process assets created for a process that pertains to a project must be accessible to users of the project, even if the users don't have the "view-scripts" and "view-screens" permissions.
https://processmaker.atlassian.net/browse/FOUR-14078
Related PR https://github.com/ProcessMaker/package-ai/pull/77
ci:next
=> FOUR-10478: When creating scripts with AI, I find permissions issues preventing me from previewing them in the Preview Pane.

ProcessMaker/ImportExport/Importer.php
This PR removes deprecated code responsible for reassociating data source scripts with the imported script. The deprecated code caused a 'Duplicate entry` error when associating the data_source_scripts from the guided template. The reassociation functionality is now handled in the data source ProcessExporterExtension file.
1. Ensure your instance has Guided Templates synced `php artisan processmaker:sync-guided-templates`
2. Select the guided template and run the process
3. Upon first completion of the guided template, you will be redirected to the launchpad, but to trigger the error you will need to run the guided template again to create another process
4. Upon completion of the second guided template, you will be navigated to the 'existing assets' page.
5. Select 'Continue'
6. Select …
=> Remove Deprecated Code for Reassociating Data Source Scripts

ProcessMaker/ImportExport/Exporters/ScriptExporter.php
This PR addresses an issue discovered during the import of scripts from Guided Templates where scripts lacking a `run_as_user_id` caused a `A user is required to run scripts`. error when running the Re-run Wizard process. To resolve this, the PR implements setting the admin user as the default `run_as_user_id` when importing such scripts.
1. Ensure your environment has the latest Guided Templates synced `php artisan processmaker:sync-guided-templates`.
2. Create a process from the Guided Template.
3. Navigate to that process's Launchpad.
4. Select "Re-run Wizard."
5. Complete the wizard.
6. Navigate to "Requests -> All Requests."
7. Select the recently completed request (the status may initially show as "cancelled").
8. View the summary data.
9. Ensure no errors such as …
=> Set Admin User as Default run_as_user_id When Importing Scripts

tests/Feature/ImportExport/Exporters/ScriptExporterTest.php
This PR resolves a failing 'ScriptExecutorTest'. The error occurred due to the admin user now being set as the default run_script_as_user when importing scripts. The solution was to update the tests to ensure an admin user was created in the database as well as asserting the run_script_as_user matched that of the admin user.
1. Run the test `phpunit tests/Feature/ImportExport/Exporters/ScriptExecutorTest.php`.
2. Ensure all tests pass without errors.
ci:next
=> Fix failing 'ScriptExecutorsTest' 

resources/js/components/shared/FilterTable.vue
The column length becomes blank if the screen size is manipulated.
We adjusted the content when the window is resize
Steps to reproduced:
1.Have a process with Case title
2.Create a requests
3.Go to requests/tasks
4.Move window size
5.Click on the column between Case title and process
https://processmaker.atlassian.net/browse/FOUR-14080
ci:deploy
ci:next
=> observation/FOUR-14080 The column length becomes blank if the screen size is manipulated.

ProcessMaker/Models/ProcessRequestToken.php
- Log in 
- create a process  
- in the first task create a file upload (use a loop with variable name loop_1)
- in the second task create a preview file
- the second task must be configured with multiple parallel (using Request Variable Array = loop_1)
- start a new case
- upload an image in file upload
- add two users for multiple task
-  Open the task
- verification of null and array index existence.
https://processmaker.atlassian.net/browse/FOUR-13354
ci:next
=> FOUR-13354: File preview in a second task, with multiple parallel, does not show the uploaded file

resources/js/processes/modeler/components/inspector/TaskAssignment.vue
When we want to configure a multi parallel task, and put an assignment of the Process Variable type with the SelfService option.
- remove SelfService of option process_variable
When we want to configure a multiparallel task, and put an assignment of type Process Variable, the selfservice option should not be seen.
- [https://processmaker.atlassian.net/browse/FOUR-13994](FOUR-13994)
ci:next
ci:deploy
ci:processmaker:observation/FOUR-13994
=> Tasks of the multiple task parallel type with self service do not reach the self service tray

resources/js/common/PMColumnFilterPopoverCommonMixin.js, resources/js/requests/components/RequestsListing.vue
Steps to reproduced:
- Log in
- Go to request/all
- Select a process/status/start filter
- Perform a search that has more than one page
- Apply the filter
- Click on pagination-button
- Add a flag to not go to first page when using navigate
https://github.com/ProcessMaker/processmaker/assets/90727999/fde9526e-8c79-46bc-9237-1663d815293b
- Also test it's working the scenario described here: https://processmaker.atlassian.net/browse/FOUR-14155
- [FOUR-14185](https://processmaker.atlassian.net/browse/FOUR-14185)
ci:next
[FOUR-14185]: https://processmaker.atlassian.net/browse/FOUR-14185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-14185: Pagination does not work if we have a filter with more than one page.

resources/js/processes-catalogue/components/ProcessesCarousel.vue
Launchpad carosuel does not show correct the image
Create a Process
Go to Launchpad Settings
Upload the image uploaded in the ticket  launchpad-slide1.png
See the carusel
Go to Processes and upload a image in the Process Launchpad
- [FOUR-14195](https://processmaker.atlassian.net/browse/FOUR-14195)
ci:deploy
ci:next
[FOUR-14195]: https://processmaker.atlassian.net/browse/FOUR-14195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14195:Launchpad carosuel does not show correct the image

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Jobs/SyncGuidedTemplates.php, ProcessMaker/Templates/ProcessTemplate.php
This PR introduces a temporary solution for generating Guided Template Launchpad carousel images. Due to limitations in the current system where launchpad images are not exported alongside process configurations, this temporary solution utilizes the [wizard-templates GitHub repo](https://github.com/ProcessMaker/wizard-templates/pull/16) to store images related to the guided template. Upon importing the process created from the guided template, the images are synced to the newly imported process.
The changes include updates to the `SyncGuidedTemplates` job to handle storing the launchpad images and modifications to the import method for importing a process from a process template to add the guided template images to the process`image_carousel` media collection.
1. Ensure your environment …
=> Implement Temporary Solution for Generating Guided Template Launchpad Carousel Images

ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Http/Controllers/TaskController.php, resources/js/common/advancedFilterStatusMixin.js, resources/js/common/setDefaultAdvancedFilterStatus.js, resources/js/components/shared/PmqlInput.vue, resources/js/requests/components/RequestsListing.vue, resources/js/requests/index.js, resources/js/tasks/components/TasksList.vue, resources/js/tasks/index.js, resources/lang/en.json
This PR fixes several issues
- It uses advanced filters instead of PMQL for the default status for requests and tasks pages. Fixes [13931](https://processmaker.atlassian.net/browse/FOUR-13931)
These other issues were found and fixed:
- Fixes an problem where column sorting broke when a default task and request pages are converted to system saved searches
- Fixes translations by only translating when the string is displayed
Requires: https://github.com/ProcessMaker/package-savedsearch/pull/415
ci:next
=> Use advanced filter for defaults and fix translations

ProcessMaker/Jobs/BuildScriptExecutor.php
This PR addresses BuildScriptExecutor errors encountered when importing a process containing multiple custom script executors. The issue stemmed from building the imported script executors simultaneously, leading to Docker errors such as `error 137` and the `/generator container already running` error upon the second attempt to build the script executor.
The solution involves implementing [Laravel's WithoutOverlapping middleware](https://laravel.com/docs/10.x/queues#preventing-job-overlaps) to the BuildScriptExecutor Job. This middleware prevents jobs from overlapping and ensures they run consecutively, resolving the errors encountered during the process import.
1. Import the provided process template containing multiple custom …
=> Resolve BuildScriptExecutor Errors During Process Import with Multiple Custom Script Executors

ProcessMaker/SanitizeHelper.php
When there are variables containing html in a rich text component, these variables are sanitized.
- Review component FormHtmlViewer for variable mustache
steps in ticket
- [https://processmaker.atlassian.net/browse/FOUR-12993](FOUR-12993)
ci:next
=> [34945] html is being sanitized in PDF connector

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/InboxRules/ApplyAction.php, ProcessMaker/InboxRules/MatchingTasks.php, ProcessMaker/Jobs/SmartInbox.php, ProcessMaker/Jobs/SmartInboxExistingTasks.php, ProcessMaker/Models/InboxRule.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, database/factories/ProcessMaker/Models/InboxRuleFactory.php, database/migrations/2024_02_14_195724_create_inbox_rules_table.php, tests/Jobs/SmartInboxTest.php, tests/unit/ProcessMaker/InboxRules/ApplyActionTest.php, tests/unit/ProcessMaker/InboxRules/MatchingTasksTest.php
- A Listener for the ActivityAssigned event in ProcessMaker/Providers/ProcessMakerServiceProvider.php was added in registerEvents method
- A Dispatch method for SmartInbox job was added.
- Create Inbox Rules
- Start a new request
https://processmaker.atlassian.net/browse/FOUR-14120
ci:deploy
=> Feature/FOUR-14120b: Backend - Fire job when task is assigned to a user

ProcessMaker/Http/Controllers/Process/ScreenController.php, resources/views/components/categorized_resource.blade.php, resources/views/processes/screens/index.blade.php
Ticket: [FOUR-13478](https://processmaker.atlassian.net/browse/FOUR-13478)
As a user, I want to find a Screen Template option in the Screen section via the following flow:
- Login as Designer
- Navigate to the Designer section
- Find the Screen option
- Find the following new tab: **My Templates**
1. Go to branch `task/FOUR-13478` in `processmaker`.
3. The 'My Templates' tab should display.
ci:next
[FOUR-13478]: https://processmaker.atlassian.net/browse/FOUR-13478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13478 | Add a New Tab Labeled “My Templates” in the Screen Section

ProcessMaker/Http/Controllers/Process/ScreenController.php, resources/views/components/categorized_resource.blade.php, resources/views/processes/screens/index.blade.php
Ticket: [FOUR-13479](https://processmaker.atlassian.net/browse/FOUR-13479)
As a user, I want to find a Screen Template option in the Screen section via the following flow:
- Login as Designer
- Navigate to the Designer section
- Find the Screen option
- Find the following new tab: **Public Templates**
1. Go to branch `task/FOUR-13479` in `processmaker`.
3. The 'Public Templates' tab should display.
ci:next
[FOUR-13479]: https://processmaker.atlassian.net/browse/FOUR-13479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13479 | Add a New Tab Labeled “Public Templates” in the Screen Section

ProcessMaker/ImportExport/Utils.php
Error on artisan processmaker:upgrade - web entry url fixer.
This happens when the environment has a process that has a namespace prefix for `http://www.omg.org/spec/BPMN/20100524/MODEL` different to "**bpmn**"
- Register at Utils.php the prefix `bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"`
1. Import the attached process.
[test.json](https://github.com/ProcessMaker/processmaker/files/14386276/test.json)
2. Make sure the `2024_02_07_113706_web_entry_url_fixer` was not previously executed (remove it from DB if necessary)
3. Run the upgrade command `php artisan upgrade`
- https://processmaker.atlassian.net/browse/FOUR-14228
ci:next
=> FOUR-14228 fIX Error on artisan processmaker:upgrade - web entry url fixer

resources/js/processes/scripts/components/ScriptEditor.vue
When package ai is not installed the feature is showing in modeler and scripts:
- Check if package ai is installed
- Install and uninstall package-ai and verify the ai features are correctly shown hidden
- [FOUR-14232](https://processmaker.atlassian.net/browse/FOUR-14232)
- [Modeler PR](https://github.com/ProcessMaker/modeler/pull/1800)
ci:next 
[FOUR-14232]: https://processmaker.atlassian.net/browse/FOUR-14232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14232: When package ai is not installed the feature is showing in modeler and scripts

ProcessMaker/Http/Controllers/Api/GroupMemberController.php
Previously, if you searched for users to add to a group which have very similar names, it would be difficult to find the specific user you were searching for. In this scenario, it would make sense to search by username since usernames must be unique, however the search did not consider the username column and the search result would be empty.
Please following the reproduction steps in the [related FOUR ticket](https://processmaker.atlassian.net/browse/FOUR-12844).
- Add the username column to be one of the searched columns when searching for a user to add to a group.
You should now be able to type in the username of a given user not in a group on the screen where you add users to a group (which aren't already in the group).
- [FOUR-12844](https://processmaker.atlassian.net/browse/FOUR-1284 …
=> FOUR-12844: Add username to searched columns when searching for users to add to a group 

ProcessMaker/InboxRules/ApplyAction.php, ProcessMaker/InboxRules/MatchingTasks.php, ProcessMaker/Jobs/SmartInboxExistingTasks.php, tests/Jobs/SmartInboxExistingTasksTest.php, tests/unit/ProcessMaker/InboxRules/MatchingTasksTest.php
- New tests for MatchingTasks class and SmartInboxExistingTasks Job
https://processmaker.atlassian.net/browse/FOUR-14120
ci:deploy
=> Feature/FOUR-14120c: Backend - Fire job when task is assigned to a user

ProcessMaker/Templates/ProcessTemplate.php
This PR enhances the export process to prevent redundant entries for process categories in the export process template manifest. By checking if a category already exists in the database before importing, duplicate entries are avoided, resulting in a cleaner import process.
The solution involves modifying the export process template manifest to unset the ProcessCategory dependency in the exported manifest if the category already exists in the database.
1. Ensure that guided templates are available in your environment by running `php artisan processmaker:sync-guided-templates`.
2. Navigate to the Processes section and verify the presence of at least one existing 'Finance' category or keep track of the count of 'Finance' categories.
3. Initiate a guided template under Processes > Guided …
=> Exclude Existing Process Categories from Process Template Export Manifest

ProcessMaker/Models/User.php, resources/views/processes/list.blade.php
1. Create a process that contains a start timer event
2. Publish the process
3. Go to the process list
4. Find the process
5. Click on the process' ellipsis
6. Notice the "Pause Start Timer" menu option is missing
- Add the missing permission name to the view
- [FOUR-14234](https://processmaker.atlassian.net/browse/FOUR-14234)
[FOUR-14234]: https://processmaker.atlassian.net/browse/FOUR-14234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14234: Fix permissions issue preventing user from seeing "Start Timer Event" menu item

resources/js/components/templates/mixins/wizardHelperProcessModal.js
This PR addresses a 500 error encountered when running a Guided Template for the first time. The error occurred due to attempting to import the process template twice while the import process was still ongoing.
The solution introduces an `importingProcess` status to indicate when the process template is being imported. Before retrying the import, the system checks against this status to avoid duplicate imports.
Note: This issue only replicated during the first run of a guided template. 
1. Ensure you have a clean instance to sync the guided templates `php artisan processmaker:sync-guided-templates`
2. Navigate to Processes -> Guided Template
3. Initiate a Guided Template process.
4. Verify that the process runs without encountering a 500 error.
5. Repeat the process initiation step to …
=> Resolve 500 Error During Guided Template Execution 

ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Models/Template.php, ProcessMaker/Templates/ScreenTemplate.php, database/factories/ProcessMaker/Models/ScreenTemplatesFactory.php, database/migrations/2024_02_28_212635_add_is_public_to_screen_templates_table.php, routes/api.php, tests/Feature/Templates/Api/ScreenTemplateTest.php
This PR introduces unit tests to verify the functionality of the "Publish Screen Templates" permission. Additionally, it implements the ability to publish a screen template when the user has the necessary permissions.
- Implement migration to add the `is_public` column to the `screen_templates` table
- Created unit tests in `ScreenTemplateTest.php` to validate the behavior of the "Publish Screen Templates" permission.
- Implemented the logic to allow users with the appropriate permissions to publish a screen template.
1. Run `php artisan migrate` to run the new migration
2. Run `phpunit tests/Feature/Templates/Api/ScreenTemplateTest.php`
3. Verify that all tests pass without any failures or errors.
- [FOUR-13551](https://processmaker.atlassian.net/browse/FOUR-13551)
ci:next
. …
=> Implement Unit Tests for Publish Screen Templates Permission

config/services.php
This PR introduces the necessary service configurations to facilitate the synchronization of Screen Templates from the screen-templates GitHub repository into a ProcessMaker instance.
Added a new property named `screen_templates_github` to the `services.php` array, enabling the integration with the `screen-templates` GitHub repository.
- [FOUR-13617](https://processmaker.atlassian.net/browse/FOUR-13617)
ci:next
[FOUR-13617]: https://processmaker.atlassian.net/browse/FOUR-13617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement Services Configuration for Syncing Screen Templates from GitHub Repo

resources/js/components/common/mixins/datatable.js
An error is displayed when entering to some lists like: script executor, Collections, users, ...
- Fix `database.js` to validate if the record has owner or category to format them.
Open the lists:
- User
- Groups
- Executor Script
- Collections
- https://processmaker.atlassian.net/browse/FOUR-14302
- https://processmaker.atlassian.net/browse/FOUR-14301
ci:next
ci:deploy
=> FOUR-14302 Fix error when rendering lists

ProcessMaker/Http/Controllers/Process/ModelerController.php, config/app.php, resources/js/processes/scripts/components/ScriptEditor.vue, resources/views/processes/edit.blade.php, resources/views/processes/modeler/index.blade.php
Hide all AI features when the package-ai is uninstalled
Add an extra env variable `OPEN_AI_PROCESS_TRANSLATIONS_ENABLED=false` to hide process translations
- [Modeler PR](https://github.com/ProcessMaker/modeler/pull/1801)
- https://processmaker.atlassian.net/browse/FOUR-14286
ci:4.8.3
ci:modeler:FOUR-14286
ci:deploy
ci:next
=> FOUR-14286: Add a variable to hide AI for Fall and Winter

ProcessMaker/ProcessTranslations/ProcessTranslation.php, resources/js/processes/translations/components/CreateProcessTranslationModal.vue, resources/js/processes/translations/components/ProcessTranslationListing.vue
Implements the next features:
- Retry missing translations
- Filtering out image fields, so they aren't translated
- Now the front end sends the nonce and promptSessionId needed by the microservice endpoints
- Open a process and go to its configuration.
- Select a language and use the AI to translate it.
https://processmaker.atlassian.net/browse/FOUR-14246
ci: next
=> FOUR-14246: Backend - Remove images from html (improvement)

ProcessMaker/Managers/DataManager.php
The information of magic variable _user is present when task is SelfService
- Remove _user when the task is SelfService
1. Create process
2. Assign to administrator group or current user to SelfService
3. Create a new Request
4. Proceed to the next task, which is Self service
5. Open the request created
6. Go to the "Data" tab
7. review variable _user
- [https://processmaker.atlassian.net/browse/FOUR-13045](FOUR-13045)
ci:deploy
=> [34697] Ellucian - _user magic variable generates for Self Service Tasks

resources/js/components/templates/mixins/wizardHelperProcessModal.js
This PR addresses the problem of the guided template helper process reinitializing when completing a guided template, leading to unexpected behavior in the process launchpad redirection. The issue stemmed from an improper conditional statement prematurely closing the "active" helper process.
- Updated the conditional statement to properly handle the closure of the "active" helper process.
The conditional now checks if the completed process is not currently being imported and is not supposed to be imported before closing the helper process. This ensures that the process helper is only hidden when relaunching the wizard template from the process launchpad.
1. Perform guided template processes and ensure completion.
2. Verify that the guided template helper process does not reinitialize …
=> Fix Guided Template Helper Process Reinitialization Issue

config/app.php, resources/views/processes/edit.blade.php
Add an extra env variable `OPEN_AI_PROCESS_TRANSLATIONS_ENABLED=false` to hide process translations
- https://processmaker.atlassian.net/browse/FOUR-14286
ci:develop
ci:deploy
=> FOUR-14286: Add a variable to hide AI for Fall and Winter 

upgrades/2024_02_07_113706_web_entry_url_fixer.php
The upgrade never finishes because it gets stuck in the web entry URL fixer migration.
This is caused because all the processes are being refreshed unnecessarily
There are 3 process observers in all ProcessMaker:
- In core to: update events, self service, conditionals and bpmn validation
- In data-sources: to disable non used Webhooks
- In Ellucian: to updateEthosEvents
Non of them changes when the `webentryRouteConfig.entryUrl` is updated.
Based on that analysis the solution is:
- Save process without firing events, as the `webentryRouteConfig.entryUrl` does not needed any additional update.
- Run the WebEntryUrlFixer upgrade `php artisan upgrade`
- https://processmaker.atlassian.net/browse/FOUR-14342
ci:deploy
=> FOUR-14342 Update process quietly in WebEntryUrlFixer upgrade

resources/views/requests/show.blade.php
An empty tab appears in the table of a request
- Not all the Request addons includes a tab, then a validation was added to check if the addon has a tab title
- Open any request in progress
- Check there is no an empty tab at the end
- https://processmaker.atlassian.net/browse/FOUR-14339
ci:deploy
ci:next
=> FOUR-14339 Fix An empty tab appears in the table of a request

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Models/Setting.php, ProcessMaker/Models/SettingsMenus.php, upgrades/2024_02_29_131833_populate_update_settings_menu.php
The API settings/menu-groups needs to return the groups related
- Return information about the groups related to the menu_groups
`API GET https://SERVER/api/1.0/settings/menu-groups`
- https://processmaker.atlassian.net/browse/FOUR-14331
ci:next
ci:develop
=> FOUR-14331: The API settings/menu-groups needs to return the groups related

resources/js/admin/settings/components/AdditionalDriverConnectionProperties.vue, resources/js/admin/settings/components/SettingDriverAuthorization.vue, resources/js/admin/settings/components/cdata/BamboohrConnectionProperties.vue, resources/js/admin/settings/components/cdata/DocusignConnectionProperties.vue, resources/js/admin/settings/components/cdata/ExcelConnectionProperties.vue, resources/js/admin/settings/components/cdata/GmailConnectionProperties.vue, resources/js/admin/settings/components/cdata/NoneConnectionProperties.vue, resources/js/admin/settings/components/cdata/OauthConnectionProperties.vue, resources/js/admin/settings/components/cdata/PasswordConnectionProperties.vue, resources/js/admin/settings/components/cdata/SapHanaConnectionProperties.vue
The CDATA package currently focuses on drivers with OAuth authentication. The goal is to expand the supported drivers to include new drivers using alternative authentication methods.
- Now, when editing a driver, fields are loaded based on its AuthScheme and if necessary, other unique fields for that specific driver will be loaded.
Conduct manual testing of the drivers' authorization:
- BambooHR
- [FOUR-14137](https://processmaker.atlassian.net/browse/FOUR-14137)
- [Package CData](https://github.com/ProcessMaker/package-cdata/pull/29)
- [Package CData Docker Executor](https://github.com/ProcessMaker/docker-executor-cdata/pull/11)
ci:package-cdata:task/FOUR-12942
ci:docker-executor-cdata:task/FOUR-12942
[FOUR-14137]: https://processmaker.atlassian.net/browse/FOUR-14137?atlOrigin=eyJpIjoiNWR …
=>  FOUR-14137 - Enable External Integration with BambooHR (develop)

ProcessMaker/Facades/FormalExpression.php, ProcessMaker/Facades/WorkflowManager.php, ProcessMaker/Jobs/BpmnAction.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/RollbackProcessRequest.php, ProcessMaker/Traits/HasVersioning.php
Implements the enable alternative feature
- https://processmaker.atlassian.net/browse/FOUR-11455
ci:deploy
ci:next
ci:package-ab-testing:feature/FOUR-11455
=> FOUR-11455 STORY Enable Alternatives

ProcessMaker/Managers/ModelerManager.php, ProcessMaker/Traits/PluginServiceProviderTrait.php, resources/views/processes/modeler/index.blade.php
- Add params support for scripts tags 
- install the ab testing package branch feature/FOUR-14399 
- open the modeler 
- the variable window.HolaMundo must be present in the modeler
- https://processmaker.atlassian.net/browse/FOUR-14399
=> FOUR-14399: Fix problem with vite configuration in ab-testing project

ProcessMaker/Http/Controllers/Process/ModelerController.php
STORY Alternative Tabs in Modeler
- Decouple the modeler show controller to reuse in the packages
- Open the modeler
- https://processmaker.atlassian.net/browse/FOUR-11456
=> FOUR-11456: STORY Alternative Tabs in Modeler

ProcessMaker/Providers/AuthServiceProvider.php
This error occurs when the `package-projects` is not installed and a non-administrator user account is used.
Currently, there is a check to determine if the projects table exists in the database schema. The proposed solution is:
- If the projects table does not exist, then the Gate will return false by default.
The other changes are related to SonarQube. 
- The function inside the Gate had more than 4 returns
- The before() function had the error: "Vote methods should return at least once a negative response".
Since deploying a CI Server without the projects package is not possible, the best option for a functional test is to do it manually.
- [FOUR-14395](https://processmaker.atlassian.net/browse/FOUR-14395)
[FOUR-14395]: https://processmaker.atlassian.net/browse/FOUR-14395?atlOrigin=eyJp …
=> FOUR-14395: Database Error: Table not found: 'project_assets' doesn't exist

config/mail.php
When using an SMTP configuration, it gives a certificate problem.
New parameters were added to the default mailer, to allow sending emails.
- New parameters were added to the default mailer, to allow sending emails.
To test, you need an SMTP with a white list of servers since it gives an error 5.7.1 which does not allow sending email.
- [https://processmaker.atlassian.net/browse/FOUR-14203](FOUR-14203)
ci:develop
ci:connector-send-email:bugfix/FOUR-14203
ci:deploy
=> [35775] SMTP configuration without TLS and authentication showing the error: Unable to connect with STARTTLS

resources/js/admin/settings/components/SettingDriverAuthorization.vue
There is a validation error when trying to authorize the BambooHR driver.
1. Go to admin - settings.
2. Add the Bamboo driver.
3. Click on the edit and authorize buttons.
Solution
- This error occurs in drivers using the CData API driver.
- Since the API driver operates in the background, only the driver's name or API profile should be sent from the UI. In this case, `api` should not be sent, but rather `BambooHR`. Therefore, the change from driver to name was made.
- Follow the steps described above; you should not encounter any problems when authorizing the BambooHR driver.
It can be tested on the CI Server.
- [FOUR-14497](https://processmaker.atlassian.net/browse/FOUR-14497)
ci:deploy
[FOUR-14497]: https://processmaker.atlassian.net/browse/FOUR-14497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
=> FOUR-14497: BambooHR Driver Authorization Error

resources/js/processes-catalogue/components/ProcessesCarousel.vue
Option to render the Launchpad images of carousel in Launchap
- Height: 400 pixels
- Width: 800 pixels
- Aligned Centered
- Background color: #edf1f6
Go to Processes
Open a process and review the carousel
- https://processmaker.atlassian.net/browse/FOUR-14478
ci:deploy
=> FOUR-14478: Option to render the Launchpad images of carousel in Launchap

resources/js/processes/screen-templates/components/MyTemplatesListing.vue, resources/js/processes/screen-templates/components/PublicTemplatesListing.vue, resources/js/processes/screen-templates/mixins/fieldsMixin.js, resources/js/processes/screen-templates/mixins/navigationMixin.js
Screen templates cannot be deleted.
1. Go to the designer - screens - my templates or public templates tab.
2. Click on the ellipsis menu.
3. Select 'Delete'.
- Missing code has been added to enable the deletion of screen templates.
https://github.com/ProcessMaker/processmaker/assets/90741874/20312f94-408e-4a59-9ec7-70a5ae45f80a
- Follow the mentioned steps to test on a CI server.
- There is currently a PHP unit test that supports this functionality `php artisan test --filter ScreenTemplateTest::testDeleteScreenTemplate`.
- [FOUR-14492](https://processmaker.atlassian.net/browse/FOUR-14492)
ci:next
ci:deploy
[FOUR-14492]: https://processmaker.atlassian.net/browse/FOUR-14492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14492: Not able to delete a template

ProcessMaker/ProcessTranslations/ProcessTranslation.php, resources/js/processes/translations/components/CreateProcessTranslationModal.vue, resources/js/processes/translations/components/ProcessTranslationListing.vue
This PR resolves the following observations:
- Translate all strings in modal not working
- Translate empty strings in modal not working
- Percentage number in translations not showing
- Added code to support translations of just empty strings.
- Install package-ai
- Create a process with some tasks and screens
- Go to the process configurations and select the "Translations" tab.
- Add an automatic translation
- Edit the generated translation and press over the "Translating Options" button
- Test using Translate All and Translate just Empty translations.
- https://processmaker.atlassian.net/browse/FOUR-14380
- https://processmaker.atlassian.net/browse/FOUR-14379
- https://processmaker.atlassian.net/browse/FOUR-14378
ci:next
=> FOUR-14380: Translate all strings in modal not working

ProcessMaker/Traits/HasAuthorization.php
when you have the following assignment
User1 => without permissions.
Group1 => User1 assigned to the group, and the group has permission to Create-update Users.
Group2 => Group1 assigned to the group, and the group has permission to Create-Update processes.
The user does not have all permissions assigned.
-  review recursively assigned groups.
create
User1 => without permissions.
Group1 => User1 assigned to the group, and the group has permission to Create-update Users.
Group2 => Group1 assigned to the group, and the group has permission to Create-Update processes.
loggin with user and review permissions
- [FOUR-12843](https://processmaker.atlassian.net/browse/FOUR-12843)
[FOUR-12843]: https://processmaker.atlassian.net/browse/FOUR-12843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
=> [35205] Permissions not applying to groups assigned to group

resources/js/components/Menu.vue, resources/js/processes/screen-builder/screen.vue
Save as template is not in the option menu of screen builder.
1. Create a new  screen 
2. Inside the screen click on the op menu
- Added new "Save as Template" menu item in `screen-builder` section.
- Please test following the reproduction steps on the deployed CI Server.
ci:next
ci:deploy
- [FOUR-14545](https://processmaker.atlassian.net/browse/FOUR-14545)
[FOUR-14545]: https://processmaker.atlassian.net/browse/FOUR-14545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14545: Save as template is not present inside the screen

ProcessMaker/Templates/ScreenTemplate.php
When creating a Template from a screen that contains several elements, an error will occur that would not allow me to continue.
1. Create a screen with several elements or import the Screen attached.
2. Save the Screen as a Template 
3. Click on My Templates and this error will appear.
- Instead of selecting all columns from the "screen_templates" table, all are chosen except the `manifest` column, as it is not relevant in the 3 endpoints where it's used. This modification optimizes the query and prevents the 500 error.
Import the Screen with many fields and test in the deployed server.
ci:next
ci:deploy
- [FOUR-14519](https://processmaker.atlassian.net/browse/FOUR-14519)
[FOUR-14519]: https://processmaker.atlassian.net/browse/FOUR-14519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
=> FOUR-14519: Memory allocation error in a big Screen Template

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Managers/DataManager.php, ProcessMaker/Models/ProcessRequest.php, composer.json, resources/js/requests/components/RequestsListing.vue
ProcessMaker platform will automatically set the version (A or B ) in the metadata of the request
- Add alternative info to DataManager
- Add an alternative column to Request list
- Add support to alternative filtering, sorting, and PMQL 
[FOUR-13419](https://processmaker.atlassian.net/browse/FOUR-13419)
ci:next
ci:package-ab-testing:feature/FOUR-11361
[FOUR-13419]: https://processmaker.atlassian.net/browse/FOUR-13419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-13419 STORY Tag each request with the alternative identifier

resources/js/tasks/components/PreviewMixin.js
When you enter from the default dashboard, a redirect is made to a task that is not defined.
- It is validated that a task ID exists to perform the redirect.
login and view home dashboard by default
- [FOUR-14572](https://processmaker.atlassian.net/browse/FOUR-14572)
ci:next
ci:deploy
[FOUR-14572]: https://processmaker.atlassian.net/browse/FOUR-14572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Redirection error when logging into the application

resources/js/processes/screen-templates/components/MyTemplatesListing.vue, resources/js/processes/screen-templates/components/PublicTemplatesListing.vue
The pagination controls of my template and public template is very close to the edge of the frame.
1. Click on Designer
2. Click on Screens
3. Click on My Template and Public Template
- Removed non necessary classes from the div.
- Manual testing or deployed server.
ci:next
ci:deploy
- [FOUR-14553](https://processmaker.atlassian.net/browse/FOUR-14553)
[FOUR-14553]: https://processmaker.atlassian.net/browse/FOUR-14553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14553: The pagination controls of my templates is on the edge of the frame

ProcessMaker/Templates/ScreenTemplate.php, resources/js/components/shared/ellipsisMenuActions.js, resources/js/components/templates/CreateTemplateModal.vue, resources/js/processes/screen-templates/mixins/navigationMixin.js, routes/api.php, tests/Feature/Templates/Api/ScreenTemplateTest.php
The "Make Public" menu option doesn't work.
1. have a screen 
2. create a screen template 
3. click on menu options
4. click on "make public"
1. Fixed conflict in the route `'template/{type}/{id}'`, which was conflicting with `'template/{type}/{processId}'`. To differentiate them, the route was updated to: `'template/{type}/{id}/update'` and corresponding references were updated. 
2. Added unit test for functionality of making a template public. Added tweaks in the frontend to make this API call.
https://github.com/ProcessMaker/processmaker/assets/90741874/2fdcffe8-b6e6-4bc1-a33f-f9cd23b8bce1
- Test on the deployed server / all tests should pass.
ci:next
ci:deploy
- [FOUR-14554](https://processmaker.atlassian.net/browse/FOUR-14554)
[FOUR-14554]: …
=> FOUR-14554: The make public option from my template does not work

resources/js/tasks/components/TasksHome.vue
Open Preview Task (eye icon) is open the screen in the Task tab
This action show an empty form then redirect to the Task tab
Login
Go to Home
My Task → Click in the eye icon
https://processmaker.atlassian.net/browse/FOUR-14580
ci:deploy
ci:next
=> bugfix/FOUR-14580 Changed openTask call

ProcessMaker/Filters/Filter.php, ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/js/tasks/components/TasksHome.vue, resources/views/processes/modeler/index.blade.php
https://processmaker.atlassian.net/browse/FOUR-13420
A process designer that is testing a process, I want to control which alternative is tested and perform a test that represents how my process alternative will conduct.
If I dont define anything explicit, the test should execute following the same AB distribution that would apply during runtime (be it A or B ) . As tester, I should be able to identify immediately which alternative is executing.
Conversely, as a tester I can define which alternative to test explicitly with any given scenario, overriding any AB distribution setting. That way I can force test both alternatives with any scenario.
=> FOUR-13420 Alternative Testing

ProcessMaker/Models/Setting.php, resources/js/admin/settings/components/SettingsMain.vue, resources/js/admin/settings/components/SettingsMenuCollapse.vue
The content to Config options in Admin Settings is not the same like figma
- Apply the styles defined in the figma
2. Go to Admin Settings 
3. Select any option on the Left Menu
4. Check the container to configuration
- https://processmaker.atlassian.net/browse/FOUR-14579
ci:deploy
ci:next
=> FOUR-14579: The content to Config options in Admin Settings is not the same like figma

ProcessMaker/Helpers/ScreenTemplateHelper.php, ProcessMaker/Templates/ScreenComponents.php
This PR improves the behavior of creating screens from templates by refining the functionality of template options such as 'CSS', 'Layout', and 'Fields'. It addresses issues related to exclusion and duplication of components when applying specific template options, ensuring a more accurate and streamlined screen creation process.
- Added missing field components for AI-generated components and Rich Text to the Screen Components array.
- Removed duplicated code responsible for parsing and adding related screen fields, preventing the occurrence of duplicated field inputs.
1. Create a screen with AI-generated and Rich Text components.
2. Save the screen as a template.
3. Create a new screen.
4. Select the created template and access the 'Template Preview'.
5. Test each option for 'CSS', …
=> Enhance Behavior of Creating Screens from Templates with Template Options

resources/js/components/templates/TemplateSelectCard.vue
This PR addresses a console error occurring when navigating to the Guided Template listing page. The error stemmed from a failing `v-else` conditional, causing a component that should be hidden to render during the loading of Guided Templates.
- Resolved the failing `v-if` conditional on the `screen-templates-card` component by replacing it with `v-else-if`.
1. Open your browser console.
2. Navigate to the Processes section.
3. Select 'Guided Templates'.
4. Verify that no console errors are displayed upon loading the Guided Template listing page.
- [FOUR-14594](https://processmaker.atlassian.net/browse/FOUR-14594)
ci:next
ci:deploy
[FOUR-14594]: https://processmaker.atlassian.net/browse/FOUR-14594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Console Error in Guided Template Listing Page

ProcessMaker/Models/ProcessRequest.php
When you have a process with multiple thread levels and interstitial enabled, the interstitial is loaded twice.
- remove event 
In order to reproduce the problem you need to add a 2 second sleep to the file
ProcessMaker/Models/ProcessRequest.php
in the notifyProcessUpdated function before sending the event.
In this way a delay is created in the sending of the events.
create a case and then derive it to check that the interstitial is not loaded twice.
note:
1. interstitial in a single process (enable interstitial in multiple assigned tasks)
2. interstitial in a SubProcess (multiple levels in SubProcesses and enable interstitial in multiple assigned tasks)
3. interstitial with WebEntry (enable interstitial on multiple assigned tasks)
4. verification in the display of tasks …
=> [36258 ]Interstitial pages load twice

ProcessMaker/ImportExport/Exporters/UserExporter.php
Install the Ethos PM Block provided by the PLG Team upon package installation.
- This PR is part of the Ellucian Ethos package PR and involves installing a PM Block during the package installation.
- The PM Block is installed using an exported file and through the import function.
- Run `php artisan package-ellucian-ethos:install`. The PM Block should be installed with all its dependencies.
- [FOUR-14639](https://processmaker.atlassian.net/browse/FOUR-14639)
- [Package Ellucian Ethos PR](https://github.com/ProcessMaker/package-ellucian-ethos/pull/111)
[FOUR-14639]: https://processmaker.atlassian.net/browse/FOUR-14639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14639: Create a seeder for Ethos PM Block

.github/workflows/deploy-pm4.yml, ProcessMaker/Console/Commands/ProcessMakerLicenseRemove.php
Requires https://github.com/ProcessMaker/pm4-k8s-distribution/pull/107
We need to remove the license in CICD so the test environment and unit tests have access to all installed packages
ci:next
=> Add a force flag to remove license for CICD

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, routes/api.php
API return the information for show the status
- Create a new API `requests/24/default-chart` in order to return the information for show the chart
- https://processmaker.atlassian.net/browse/FOUR-14443
ci:next
ci:deploy
=> FOUR-14443: API return the information for show the status

resources/js/components/templates/ScreenTemplateCard.vue
This PR removes the "Preview Template" option for blank templates in the New Screen Modal interface. Previously, even for blank templates, users could access the "Preview Template" feature, which was unnecessary as blank templates don't have any content to preview.
- Implemented a computed property to determine if the template is blank.
- Conditionally render the "Preview Template" option based on whether the template is blank.
1. Navigate to the Screen Designer interface.
2. Click on the "+ Screen" button to create a new screen.
3. Ensure that for all screen types and template types (My Templates, Public Templates),  the  blank template "Preview Template" option is not available.
- [FOUR-14697](https://processmaker.atlassian.net/browse/FOUR-14697)
ci:next
ci:deploy
[FOUR-14697]: …
=> Remove 'Preview Template' action for Blank Templates

ProcessMaker/Http/Controllers/Api/ScreenController.php
When updating a Screen Template, the changes are not being reflected
1. Create a Screen Template.
2. Navigate to the Template section.
3. Select the desired template and click on "Edit Template".
4. Apply the necessary modifications and click "Save" to update the template.
5. Create a new Screen using the recently updated template.
Please note: Despite following these steps, you may observe that the alterations to the template have not been applied to the new Screen. This indicates a potential issue with the template update process that needs to be addressed.
Implemented a new function, `updateScreenTemplate`, within the screen's update method to facilitate template updates.
Please follow the reproduction steps and ensure that the Screen template updates are reflected when creating a new …
=> FOUR-14582: Updating a Screen Template

ProcessMaker/Templates/ScreenTemplate.php
This PR refines the query to retrieve non-public screen templates created by the logged-in user. Previously, there was a loophole where non-public templates created by one user were visible to other users, including the admin. This PR ensures that only the creator of a non-public template can view and access it.
- Improved the query to specifically fetch templates created by the authenticated user.
1. Create two users and enable all user permissions for both.
2. Log in as User A.
3. Create a non-public screen template.
4. Log in as User B.
5. Navigate to the "My Templates" tab.
6. Ensure that the screen template created by User A is not visible to User B.
7. Log in as an admin.
8. Ensure that the screen template created by User A is not visible to the admin.
- …
=> Refine Query to Retrieve User-Specific Non-Public Screen Templates

ProcessMaker/Models/ScreenTemplates.php, ProcessMaker/Templates/ScreenTemplate.php
When a Screen Template is deleted, it is crucial to ensure the associated editing screen is also removed to maintain data integrity and system cleanliness.
1. Create a Screen Template
2. Navigate to the Template
3. Click on Edit Template
4. In the `screen_templates table`, you’ll notice that we now include the editing_screen_uuid of the Editing Screen
5. In the `screens` table, you’ll notice the new screen with a uuid === to the editing_screen_uuid and is_template as 1
- Added a boot() function to the ScreenTemplates Model to Listen for the deleting event on a ScreenTemplate instance and delete any associated Screen if exists.
Please follow the listed reproduction steps carefully and ensure that the screen associated with the Editing Screen Template is also deleted.
- Ticket: …
=> FOUR-14583: Deleting any associate Screen when deleting a Screen Template

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Templates/ScreenTemplate.php, resources/js/processes/screens/components/CreateScreenModal.vue
This PR resolves an issue where setting the Default Template does not persist in the database and the UI. The problem stemmed from the returned templates not including the `is_default_template column`, as well as an improper conditional preventing the setting of the default template from being stored in the request data for the POST method.
- Updated the query in the index method to return the `is_default_template` column along with other template data.
- Refactored the conditional logic for creating screens based on selected or default templates or a blank screen.
- Improved the conditional logic to prevent the erasure of the default template when selecting a blank template.
1. Create a screen template.
2. Navigate to 'Screen -> Designer'.
3. Select '+ Screen'.
4. Ensure the Blank …
=> Fix Default Template Persistence Issue

resources/js/requests/components/RequestsListing.vue
The field ID no longer has the URL to open the request.
-  Add URL to field ID
crear una búsqueda guardada y verificar que el campo del ID tiene la URL.
- [FOUR-14368](https://processmaker.atlassian.net/browse/FOUR-14368)
ci:next
ci:deploy
[FOUR-14368]: https://processmaker.atlassian.net/browse/FOUR-14368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 36561 RIght-click to open in new tab in saved searches no longer available

ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Http/Resources/Task.php
- Log in to ProcessMaker.
- Navigate to the Designer tab.
- Create a form screen and a display screen.
- Develop a process, assigning the form screen to a task and the display screen as an interstitial for the initial event and also to an end event as a summary screen.
- Choose the created process for translation.
- Add a New translation.
- Select a screen and proceed to translate.
- Review Screen translated
Added code to translate interstitials and summary screens.
- https://processmaker.atlassian.net/browse/FOUR-14381
ci:next
=> FOUR-14381: Translation not working in dropdown fields options, interstitials and summaries

ProcessMaker/Http/Controllers/Process/ModelerController.php, resources/views/processes/modeler/index.blade.php
- Add required helpers to complete the functionality
- Add the missing functionality related to alternatives
- Open modeler and try to run test
- Select the alternative before test
- https://processmaker.atlassian.net/browse/FOUR-14704
ci:next
ci:deploy
ci:package-testing:FOUR-14704
ci:package-ab-testing:FOUR-14704
=> FOUR-14704 AB Testing Integration - Run Test in Modeler based on the Alternative FE helpers (required by FOUR-13423)

resources/js/processes/scripts/components/AiTab.vue, resources/js/processes/scripts/components/GenerateScriptTextPrompt.vue, resources/js/processes/translations/components/ProcessTranslationListing.vue, resources/lang/en.json
Descripción
In sync with @Claudia Iriarte some modifications in the error messages are required:
Instead of showing the Server error alert message in all the pages all time when AI micro service is down, show the message in the console as error.
We need to show a more user friendly alert message ProcessMaker AI is currently offline. Please try again later. just when the user performs an specific AI action like:
- Clicks on generate process from text button
- Clicks on generate process from image button
- Clicks on generate script from text button
- Clicks on document script button
- Clicks on clean script button
- Clicks on explain script button
- Clicks on generate process assets button in modeler
- Clicks on generate form button in screen builder
By the other hand we need an …
=> FOUR-14799: Improve error messaging for AI 

resources/js/processes-catalogue/components/BaseChart.vue
The new chart selected in chart launchpad  is not update , it is necessary reload the page 
- https://processmaker.atlassian.net/browse/FOUR-14812
ci:next
ci:deploy
=> feature/FOUR-14812: The Chart is not update after config in Launchpad settings

ProcessMaker/Jobs/SyncScreenTemplates.php, ProcessMaker/Models/ScreenTemplates.php, resources/js/components/templates/PreviewTemplate.vue, resources/js/components/templates/ScreenTemplateCard.vue
This PR updates the screen sync command `php artisan processmaker:sync-guided-templates` to support the refined file structure of the `screen-template` GitHub repository. Additionally, it adds support for displaying the template thumbnail and preview thumbnail.
.
- Dynamically set specific template details from the exported screen template payload, such as `screen_type` and `screen_custom_css`.
- Properly handle the displaying of the `thumbnail` and `previewThumbs` media in the Create Screen Modal.
1. Run the command php artisan processmaker:sync-guided-templates.
2. Verify that the command synchronizes the screen templates correctly, including their updated file structure.
3. Open the Create Screen Modal and confirm that the template thumbnail and preview thumbnails are displayed …
=> Update Screen Sync Command to Support Refined File Structure

resources/js/components/shared/ModalSaveVersion.vue
Launchpad modal is not displayey when AB tetsing is not installed.
- Validation changed, is not required to have AB testing installed to display Launchpad.
In an environment without AB testing create a new process and publish the same.
- https://processmaker.atlassian.net/browse/FOUR-14817
ci:next
ci:deploy
=> FOUR-14817 The Launchpad Setting in the modal is not showing when the AB testing is not installed

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
Chart in launchpad confuses request In progress by completed
- Change the variables
- Create process
- Start some requests in order to the process have in progress requests
- Go to process-browser
- Open the process 
- Check the Chart colors  
- https://processmaker.atlassian.net/browse/FOUR-14807
ci:next
ci:deploy
=> FOUR-14807: Chart in launchpad confuses request In progress by completed

ProcessMaker/ImportExport/Exporters/ExporterBase.php, ProcessMaker/ImportExport/Exporters/MediaExporter.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/ImportExport/Exporters/ProcessLaunchpadExporter.php, ProcessMaker/Models/ProcessLaunchpad.php, database/factories/ProcessMaker/Models/ProcessLaunchpadFactory.php, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php, tests/Feature/ImportExport/Exporters/ProcessLaunchpadExporterTest.php
Create the ProcessLaunchpadExporter in order to export the Models related to the process_launchpad table
- A new exporter has been added for the ProcessLaunchpad table.
- A function has been introduced to increment numbers in columns with a unique constraint.
- Execute manual tests.
ci:next
ci:deploy
- [FOUR-14573](https://processmaker.atlassian.net/browse/FOUR-14573)
[FOUR-14573]: https://processmaker.atlassian.net/browse/FOUR-14573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14573: Export process_launchpad table related with process

ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, resources/views/processes-catalogue/index.blade.php
Saved Search Chart is not visible in Screen Launcher Launchpad
- Adding variables required for the show a save search
1. Create a Screen display type
2. Add Saved search chart
3. Save the changes
4. Go to process-browser
5. Select a process
6. Config the Process Launch pad
7. Select the screen created in Screen Launcher
8. Refresh the page
- [FOUR-14788](https://processmaker.atlassian.net/browse/FOUR-14788)
ci:deploy
ci:next
[FOUR-14788]: https://processmaker.atlassian.net/browse/FOUR-14788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14788:Saved Search Chart is not visible in Screen Launcher Launchpad

resources/js/processes/screen-templates/components/MyTemplatesListing.vue, resources/js/processes/screen-templates/components/PublicTemplatesListing.vue
This PR addresses an issue where the sorting functionality in the My Template and Public Template tabs was not working. The problem arose due to the inadvertent removal of the `@click` handler method for the sorting carets.
- Added back the `@click` handler method for sorting carets to ensure proper sorting functionality.
1. Navigate to the My Templates or Public Templates tab.
2. Attempt to sort the tables by different columns.
3. Verify that the data is sorted correctly.
4. Confirm that no errors occur during the sorting process.
- [FOUR-14831](https://processmaker.atlassian.net/browse/FOUR-14831)
ci:next
ci:deploy
[FOUR-14831]: https://processmaker.atlassian.net/browse/FOUR-14831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Resolve Sorting Issue in My Template and Public Template Tabs

resources/views/processes/screens/import.blade.php
Ticket: [FOUR-14385](https://processmaker.atlassian.net/browse/FOUR-14385)
When navigating to the Screen Importer, you're able to see dynamic content showing up before the page is fully loaded:
You are about to import a Screen.
You are about to import {{ fileName }}.
- Add a v-cloak to the "You are about to import {{ fileName }}" text.
1. Go to branch `observation/FOUR-14835` in `processmaker`.
3. Select 'Import'.
4. When the Import page loads, only one line of text should appear:
- You are about to import a Screen.
5. Once you've selected a file to import, the line of text should change to:
- You are about to import {{ fileName }}.
ci:next
ci:deploy
[FOUR-14385]: https://processmaker.atlassian.net/browse/FOUR-14385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> FOUR-14835 | Dynamic Text Shows Up on the Screen Import Page

resources/js/tasks/components/PreviewMixin.js, resources/js/tasks/components/TasksPreview.vue
When actions are performed quickly, the data is not saved
Added a delay and disable the task navigation buttons and and change the user Interact flag after a Clear Draft
https://processmaker.atlassian.net/browse/FOUR-14768
ci:deploy
ci:next
=> observation/FOUR-14768-A Drafts don't save when switching tasks in task preview
