ProcessMaker/processmaker

ProcessMaker/Helpers/ScreenTemplateHelper.php
This PR addresses an issue where the `$filteredColumnItems` array was being overwritten incorrectly, leading to the loss of data, especially when processing multi-column items. The problem arose due to incorrect array assignment within the if-else block.
- Updated the array assignment to ensure that all filtered column items are properly stored in the array without overwriting previous data.
1. Create a screen template that contains multicolumns and form inputs.
2. Navigate to Designer > Screen.
3. Select '+ Screen'.
4. Choose 'Preview Template' for the created screen template.
5. Ensure that only the 'Fields' option is selected.
6. Create the screen.
7. Verify that all fields in the multicolumn are included in the screen without any loss of data.
- …
=> Fix Overwriting Issue with $filteredColumnItems Array

ProcessMaker/LicensedPackageManifest.php, composer.json
- CloudOps added the ab-testing to the license for PM^4.10
- Remove the forced deploy of ab-testing for testing purposes
- https://processmaker.atlassian.net/browse/SCO-22193
ci:next
ci:deploy
=> SCO-22193 Remove force AB Testing deploy and enabled

resources/js/processes/screen-templates/components/CreateScreenTemplateForm.vue, resources/js/processes/screens/components/ScreenTypeDropdown.vue, resources/js/templates/components/ScreenTemplateConfigurations.vue, resources/sass/app.scss
Ticket: [FOUR-14815](https://processmaker.atlassian.net/browse/FOUR-14815)
- In the Screen Template Configurations, the content of the Screen Type Dropdown does not fit inside of the multiselect container.
- In the Create Screen Template modal, the multiselect arrow on the Screen Type Dropdown does not fit the height of the multiselect container.
- Update the Screen Type Dropdown styles in the Screen Template Configurations page and the Create Screen Template modal
1. Go to branch `observation/FOUR-14815` in `processmaker`.
3. Hover over a Screen and select 'Save as Template' from the tooltip menu.
4. In the Create Screen Template modal, the Screen Type Dropdown arrow should fit the height of its container.
5. Go to the 'My Templates' tab.
6. Hover over a …
=> FOUR-14815 | Screen Type Dropdown is Distorted in Screen Template Configurations

resources/js/app-layout.js, resources/js/components/Confirm.vue, resources/js/components/shared/EllipsisMenu.vue, resources/views/layouts/navbar.blade.php
Some elements don't have the `data-test` attribute in the modeler when AB Testing is enabled
- Add missing `data-test` attribute
[FOUR-14875](https://processmaker.atlassian.net/browse/FOUR-14875)
https://github.com/ProcessMaker/package-ab-testing/pull/33
https://github.com/ProcessMaker/package-testing/pull/62
ci:next
ci:deploy
ci:package-ab-testing:FOUR-14875
ci:package-testing:FOUR-14875
[FOUR-14875]: https://processmaker.atlassian.net/browse/FOUR-14875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14875 add data-test attribute in modeler for AB testing

resources/views/components/categorized_resource.blade.php
This PR introduces an `onLoad` functionality to enhance the loading behavior of tabs within the Designer > Processes & Designer > Screens. Previously, tabs might display prematurely, leading to potential rendering issues and console errors when selected before the content was fully loaded. By incorporating an event listener for the window load event, the script now ensures that the categorized list element is displayed only after the page has fully loaded. This prevents potential issues and enhances the user experience by ensuring that tabs are fully loaded before they are interacted with.
- Added an event listener for the window load event to ensure proper tab loading.
- Implemented logic to display the categorized list element only after the page has fully loaded.
1. Set the Network to …
=> Implement onLoad Functionality to Ensure Proper Tab Loading

resources/js/components/shared/ModalSaveVersion.vue, resources/lang/de.json, resources/lang/es.json, resources/lang/fr.json
- publish modal is not disappear after saved
- sometime the LaunchPad does not appears
- Fix the logic to show LaunchPad and Alternative Publish.
- Publish a New Process without Alternative A or B
- Publish a New Process with Alternative A
- Publish a New Process with Alternative B
- Publish a New Process with Alternative AB
- After each case the LaunchPad should be displayed only the first time the process is published.
- https://processmaker.atlassian.net/browse/FOUR-14892
- https://processmaker.atlassian.net/browse/FOUR-14833
ci:next
ci:package-ab-testing:bugfix/FOUR-14892
=> FOUR-14892 Publish Version Modal combined with LaunchPad

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
Chart in launchpad confuses request In progress by completed
- Change the variables
- Create process
- Start some requests in order to the process have in progress requests
- Go to process-browser
- Open the process 
- Check the Chart colors  
- https://processmaker.atlassian.net/browse/FOUR-14807
ci:next
ci:deploy
=> FOUR-14807

resources/js/components/shared/LaunchpadSettingsModal.vue, resources/lang/en.json, resources/lang/es.json
Incorrect message is showing
- Update the message to: `The launchpad settings were saved.`
2. Publish the process 
3. Configure launchpad and save
- https://processmaker.atlassian.net/browse/FOUR-14897
ci:next
ci:deploy
=> FOUR-14897

ProcessMaker/Http/Controllers/Api/ImportController.php, ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Models/ScreenTemplates.php, ProcessMaker/Models/Template.php, ProcessMaker/Templates/ProcessTemplate.php, ProcessMaker/Templates/ScreenTemplate.php, resources/views/templates/import-screen.blade.php, routes/api.php, tests/Feature/Templates/Api/ScreenTemplateTest.php
This pull request addresses the issue of encountering a `500 duplicate error` when uploading the same template multiple times in the Public Template tab. This problem stemmed from the screen template's `editing_screen_uuid` column not being cleared upon screen template import. 
Additionally, this PR standardizes the import functionality for both Process Templates and Screen Templates by integrating them into the TemplateController. This consolidation enhances manageability and ensures uniformity across template imports.
- Moved Process Template and Screen Template import functionality from `ImportController` to `TemplateController`.
- Implemented the `importTemplate` method for each asset within the Templates interface.
- Updated the payload for screen and process templates to clear …
=> Standardize Template Imports and Fix Duplicate Error Issue

resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue
Message Anon Web Entry-Authenticated is visible in a we assigned to a user
1. Login with super admin user
2. Create a userA
3. Create a process with WE Authenticated
4. Assign the WE to userA
5. Go to Process-catalogue
6. Search the process
7. Copy the link of WE assigned to userA
Create a web entry authenticated and copy the link from processes
- [FOUR-14329](https://processmaker.atlassian.net/browse/FOUR-14329)
ci:deploy
ci:next
[FOUR-14329]: https://processmaker.atlassian.net/browse/FOUR-14329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14329:Message Anon Web Entry-Authenticated is visible in a we assigned to a user

resources/js/components/PMBadgesFilters.vue, resources/js/inbox-rules/components/InboxRuleFilters.vue
We are hacking resources/js/components/shared/PmqlInput.vue with the resources/js/common/advancedFilterStatusMixin.js
I want to make this an entirely separate component that correctly displays the badges for the advanced filters. Should show all filters and all sub-filters under or in the advanced filter json
Any PMQL should just be it’s own, single badge like [PMQL = ….]
=> FOUR-14625 Refactor column filter badges

resources/js/components/shared/PaginationTable.vue
The size of the pagination input is small and when the page reaches two digits, the second digit is not shown.
1. Have more than 10 pages in My template or Public template.
2. Go to the following pages until you reach 10.
- Since adjusting the width of the input field based on the content of the placeholder is not natively possible, used JS to measure the width of the placeholder text and then apply that same width to the input field.
- Test in the QA server.
ci:next
ci:deploy
- [FOUR-14903](https://processmaker.atlassian.net/browse/FOUR-14903)
[FOUR-14903]: https://processmaker.atlassian.net/browse/FOUR-14903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14903: When the pager has a second digit, the entire last digit is not displayed

ProcessMaker/Templates/ScreenTemplate.php, database/factories/ProcessMaker/Models/ScreenTemplatesFactory.php, resources/js/processes/screens/components/CreateScreenModal.vue, tests/Feature/Templates/Api/ScreenTemplateTest.php
When a default template is selected, but the user opts to use another template by selecting the thumbnail or configuring options in the PreviewTemplate, the template referenced to create the screen is the configured default template, rather than the template the user selected. This behavior results in screens being created based on the default template, regardless of the user's selection.
- Following the expected behavior: `The created screen should be based on the selected screen template, regardless of the default template configuration.`. Removed the code that forced the use of the defaultTemplate for screen creation. 
- Added a unit test to cover these cases. 
- The default option in the mounted section of the CreateScreenModal.vue file has been set to a blank screen.
You can do …
=> FOUR-14863: Incorrect Screen Template Referenced When Creating Screen from PreviewTemplate

ProcessMaker/Templates/ScreenTemplate.php, database/migrations/2024_04_10_174318_update_publish_templates_permission_name.php, resources/js/components/shared/ellipsisMenuActions.js, resources/js/processes/screen-templates/components/CreateScreenTemplateForm.vue, resources/js/processes/screen-templates/components/PublicTemplatesListing.vue, resources/js/processes/screen-templates/mixins/navigationMixin.js, resources/js/processes/screens/components/CreateScreenModal.vue, resources/js/processes/screens/components/ScreenTemplateOptions.vue, resources/js/processes/screens/components/TemplateTypeDropdown.vue, resources/js/templates/components/ScreenTemplateConfigurations.vue, resources/views/components/categorized_resource.blade.php, resources/views/processes/screens/index.blade.php, tests/Feature/Templates/Api/ScreenTemplateTest.php
This PR updates all references of "Public Templates" to "Shared Templates" and "Make Public" to "Share Template" to better reflect the intended meaning and improve clarity within the application.
- Replaced occurrences of "Public Templates" with "Shared Templates" throughout the codebase.
- Replaced occurrences of "Make Public" with "Shared Template" throughout the codebase.
1. Navigate to the screen where "Public Templates" were referenced.
2. Verify that all instances now display "Shared Templates".
3. Check for consistency in terminology across different sections of the application.
4. Ensure that functionality related to shared templates remains unaffected.
- [FOUR-14872](https://processmaker.atlassian.net/browse/FOUR-14872)
ci:next
ci:deploy
[FOUR-14872]: …
=> Update Terminology: Public Templates to Shared Templates

resources/js/admin/settings/components/SettingsListing.vue, resources/js/admin/settings/components/SettingsMenuCollapse.vue
After delete the MAIL DRIVER the page is not redirect to Email default Settings 
Go to Settings
Create a new Email 
Delete the new email
- https://processmaker.atlassian.net/browse/FOUR-14541
ci:deploy
ci:connector-send-email:feature/FOUR-14541
ci:next
=> feature/FOUR-14541: When a new +MAIL DRIVER is deleted, this is not redirected to Email default Settigns tab

resources/js/admin/settings/components/SettingsListing.vue
External Integration are not update when a new one is added
- The new Integrations added should be sync, these should be listed on the Integrations list without the need to refresh the screen 
2. Go to Admin Settings 
3. Click on Integrations category
4. Click on External Integration menu
5. Add a new integration 
6. Verify if the new external integrations was added in the table
- [FOUR-14694](https://processmaker.atlassian.net/browse/FOUR-14694)
ci:deploy
ci:next
[FOUR-14694]: https://processmaker.atlassian.net/browse/FOUR-14694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14694:External Integration are not update when a new one is added

resources/js/processes/screen-templates/components/MyTemplatesListing.vue, resources/js/processes/screen-templates/components/PublicTemplatesListing.vue, resources/js/processes/screen-templates/components/ScreenTemplatesTooltip.vue
Ticket: [FOUR-14916](https://processmaker.atlassian.net/browse/FOUR-14916)
The tooltip menu for My Templates and Public Templates is larger than the table rows.
- Adjust tooltip height
- Center elements inside of tooltip
1. Go to branch `observation/FOUR-14916` in `processmaker`.
2. Go to Designer → Screens → My Templates or Public Templates.
3. Hover over a Template.
4. The tooltip menus should not be larger than their rows.
ci:next
ci:deploy
[FOUR-14916]: https://processmaker.atlassian.net/browse/FOUR-14916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14916 | Screen Templates Tooltip Overflows Table Rows

resources/js/components/shared/PmqlInput.vue
- Log in to Processmaker
- Go to Admin Setting
- In the search engine type “Failed“
- Press enter
- Url encoding of PMQL query
https://processmaker.atlassian.net/browse/FOUR-14517
ci:next
=> FOUR-14517: 400 Error in Search engine with "Failed" as parameter

resources/js/admin/settings/components/SettingsListing.vue
Redirecting the page for a + MAIL Driver does not redirect to the last one in Admin Settings
- The page should be redirected to last MAIL DRIVER that was created, like the previous version 
2. Go to Admin Settings
3. Click on Email Default Settings 
4. Click on +MAIL DRIVER more that one time(Exe: 3 times)
5. Check where the page was redirected
- [FOUR-14754](https://processmaker.atlassian.net/browse/FOUR-14754)
ci:deploy
ci:next
[FOUR-14754]: https://processmaker.atlassian.net/browse/FOUR-14754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14754:Redirecting the page for a + MAIL Driver does not redirect to the last one in Admin Settings

resources/js/components/shared/InputImageCarousel.vue
The input embed URL is not cleared after pressing cancel button in Launch pad 
- https://processmaker.atlassian.net/browse/FOUR-14891
ci:next
ci:deploy
=> feature/FOUR-14891: The input embed URL is not cleared after pressing cancel button in Launch pad

resources/js/processes-catalogue/components/BaseChart.vue
The Chart is not update after config in Launchpad settings
The new chart selected in chart launchpad should be update like the images in the carousel 
2. Create Chart in a saved search
3. Open process-browser
4. Edit LaunchPad settings 
5. Change the default chart to another saved search chart
6. Saved the configurations
7. 
- [FOUR-14812](https://processmaker.atlassian.net/browse/FOUR-14812)
ci:deploy
ci:next
[FOUR-14812]: https://processmaker.atlassian.net/browse/FOUR-14812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14812:The Chart is not update after config in Launchpad settings

resources/js/processes-catalogue/components/RequestTab.vue, resources/js/processes-catalogue/components/TaskTab.vue
Remove the search bar, this was moved from the PRD
- https://processmaker.atlassian.net/browse/FOUR-14806
ci:next
ci:deploy
=> feature/FOUR-14806: Remove the search bar

resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksListCounter.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php
Inbox, Priority and Drafts tabs are not having counters
Added a new component to show the tab count
https://processmaker.atlassian.net/browse/FOUR-14712
ci:deploy
ci:next
=> observation/FOUR-14712-A Inbox, Priority and Drafts tabs are not having counters

resources/js/admin/settings/components/SettingsListing.vue, resources/js/components/shared/PmqlInput.vue
Description
- Create or import a process
- Go to designer tab
- Go to search field
- Type name of process
- Type enter
Current behavior:
An error appears when performing the search and the process is not shown in the table
The error should not appear when performing the search and the process should be displayed in the table
- There was a double HTML encoding and it has been removed
https://processmaker.atlassian.net/browse/FOUR-14981
https://processmaker.atlassian.net/browse/FOUR-14986
ci:next
=> FOUR-14981: Error when searching for a process in process list

resources/js/processes/modeler/index.js
The elements are cloned in both alternatives
"Another user is working on this object, please wait until you finish making changes" message appears when clicking an item
- add DOMContentLoaded event because packages require DOM initialization 
[clone.webm](https://github.com/ProcessMaker/processmaker/assets/1401911/508b687c-8832-4570-bf43-637f73ead165)
2. Add control to modeler
3. Click on Publish button
4. Click on Publish
5. Close Launchpad modal
6. Enable alternative B
7. Add some controls to modeler
8. Review antother alternative
- https://processmaker.atlassian.net/browse/FOUR-14890
ci:next
=> FOUR-14890: The elements are cloned in both alternatives

ProcessMaker/ImportExport/Exporters/EmbedExporter.php, ProcessMaker/ImportExport/Exporters/MediaExporter.php, ProcessMaker/ImportExport/Exporters/ProcessLaunchpadExporter.php, ProcessMaker/Models/Embed.php, ProcessMaker/Models/Media.php, ProcessMaker/Models/ProcessLaunchpad.php
Error appear in Import process when the launch pad is deselected in the exportation
2. Configure The launch pad setup with Icon 
3. Save the configuration 
4. Export the process with all configuration 
5. Import the process
6. Select custom importation 
7. Unchecked the Launchpad setup
8. Check the configurations launch pad
- https://processmaker.atlassian.net/browse/FOUR-14842
ci:next
ci:deploy
=> Bugfix/FOUR-14842: Error appear in Import process when the launch pad is deselected in the exportation

resources/views/requests/show.blade.php
Like in previous version the intercom icon should hide, when the comment is open
- https://processmaker.atlassian.net/browse/FOUR-14377
ci:next
ci:deploy
=> feature/FOUR-14377: Intercom icon not hidden when comments modal is opened

resources/js/components/shared/LaunchpadSettingsModal.vue
The description should be saved in export a process, if it was modified from launch pad and also it should be matched in process config 
- https://processmaker.atlassian.net/browse/FOUR-14874
ci:next
ci:deploy
=> feature/FOUR-14874: Description fields is not saved from launch pad

resources/views/layouts/navbar.blade.php
A condition used by package dynamic-ui was removed in the feature https://processmaker.atlassian.net/browse/FOUR-11380
Added the missing condition inthe template
1. Access ProcessMaker
2. Access the Admin Section
3. Access Groups → Group Details → Visibility Settings → Global Search Bar Toggle
4. Turn off the Global Search Bar Toggle
5. Log out
6. Log in
7. The Global Search Bar still shows
https://processmaker.atlassian.net/browse/FOUR-14898
ci:next
ci:deploy
=> FOUR-14898 Can't hide the AI Global Search in the Platform using the visibility toggle

resources/js/components/shared/ModalSaveVersion.vue
Modal content is different when AB testing is not enabled
- the label was updated so the button is working as design
[label publish.webm](https://github.com/ProcessMaker/processmaker/assets/1401911/dd2846a0-0a38-4e21-97d5-206359c2639f)
2. Click on Publish button
- https://processmaker.atlassian.net/browse/FOUR-14964
ci:next
=> FOUR-14964: Modal content is different when AB testing is not enabled

ProcessMaker/Http/Controllers/Api/BookmarkController.php
he icons selected showed in the list MY BOOKMARKS is not showed
2. Define a different icon
3. Mark as Bookmark
4. list the My Bookmarks
- [FOUR-14999](https://processmaker.atlassian.net/browse/FOUR-14999)
ci:next
[FOUR-14999]: https://processmaker.atlassian.net/browse/FOUR-14999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14999:The icons selected showed in the list MY BOOKMARKS is not showed

resources/js/components/shared/ModalSaveVersion.vue
Version name is not saved.
1. Have any process
2. Publish the process
3. Name the version
4. Check it in version history in Configuration
- Added a check for when the `alternativeData` object is undefined, allowing the subject and description from the input to be used. This ensures the name and description of the version are stored correctly.
Test in the deployed QA server.
ci:deploy
ci:next
- [FOUR-15000](https://processmaker.atlassian.net/browse/FOUR-15000)
[FOUR-15000]: https://processmaker.atlassian.net/browse/FOUR-15000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR:15000: Version Name is Not Saved

resources/js/components/common/Pagination.vue
- Go to admin
- Click on users
- Scroll to pagination
- Click on groups
- Scroll to pagination
The list of users/groups does not match the pagination selection option, more than 10 user/groups are shown.
As in previous versions, the list should be shown with the correct pagination
- The pagination has been configured to use by default groups of 15, 30 and 50 items
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-14972)
ci:next
=> FOUR-14972: The list of users/groups does not match the pagination selection option.

ProcessMaker/Http/Controllers/Api/InboxRulesController.php
- Go to PM4 environment 
- Create a userA
- Login with userA
- Go to tasks/rules
- Create a inboxRule named test1_A
- Create a userB
- Login with userB
- Go to tasks/rules
- Create a inboxRule named test1_A
https://processmaker.atlassian.net/browse/FOUR-15011
ci:deploy
ci:next
=> QA Observation Bugfix/FOUR-15011: Different user cannot create an Inbox Rule with the same name

resources/js/processes/screens/components/ScreenListing.vue
We see that the pager in screens does not have the same UI as other pagers.
Changed the pagination component
1. Log in 
2. Click on Desginer
3. Click on Screens 
4. See the pager
5. Click on the other screens tabs My template, category, or public template
6. Click on Process 
7. see the pager of the process tabs
https://processmaker.atlassian.net/browse/FOUR-14549
ci:deploy
ci:next
=> observation/FOUR-14549 The screens pager is not the same as the other process pagers

resources/js/processes/modeler/components/ModelerApp.vue
Error message displayed when try to copy alternative diagram
Only if exist a defined "from" version tries to copy the diagram.
1. Enable alternative B
2. Go to menu option
3. Click on Discard draft
4. Add task to alternative A
5. Go to alternative 
6. Click on replace button
- [FOUR-14957](https://processmaker.atlassian.net/browse/FOUR-14957)
ci:next
ci:package-ab-testing:FOUR-14957
[FOUR-14957]: https://processmaker.atlassian.net/browse/FOUR-14957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14957 Server error replacing alternative A with B

ProcessMaker/Models/Setting.php
Refactor the table in order to detect the menu y submenus
- Populate new column **settings.group_id**
- Go to Settings
- Integrations -> Plaid
- https://processmaker.atlassian.net/browse/FOUR-15025
ci:next
ci:deploy
ci:package-plaid:bugfix/FOUR-15025
=> bugfix/FOUR-15025: Adding the category Integrations in Plaid

resources/js/processes-catalogue/components/menuCatologue.vue
The default list in Processes is all Processes but this is not selected
- Add the selected in the default list
1. Go to Processes
2. Per default we can see the All Processes
3. 
- [FOUR-15036](https://processmaker.atlassian.net/browse/FOUR-15036)
ci:deploy
ci:next
[FOUR-15036]: https://processmaker.atlassian.net/browse/FOUR-15036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15036:The default list in Processes is all Processes but this is not selected

ProcessMaker/Http/Controllers/Api/ProcessController.php
- Go to process
- Open any process that does not have all screens assigned
- Click on "auto validate"
The first time auto validate doesn't work.
As in previous versions it should work the first time.
- Added a request parameter to improve the speed of returning the list of processes
https://processmaker.atlassian.net/browse/FOUR-14958
ci:next
ci:modeler:observation/FOUR-14958
.
=> FOUR-14958: First time "auto validate" not working

ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/views/processes-catalogue/index.blade.php
After reload process by launchpad the Uncategorized is selected in categories
1. Create process categories
3. Go to Processes
4. Open a process with a category
5. Open a process without category
- [FOUR-14893](https://processmaker.atlassian.net/browse/FOUR-14893)
ci:deploy
ci:next
[FOUR-14893]: https://processmaker.atlassian.net/browse/FOUR-14893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-14893:After reload process by launchpad the Uncategorized is selected in categories

resources/js/components/shared/PmqlInput.vue
1.Go to requests
2.Copy name Any process
3.Paste in search and enter
4.Click on PMQL
5.Click on icon copy
6.Clear and paste in search
7.Enter
https://processmaker.atlassian.net/browse/FOUR-15053
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-15053: Copy-icon does not copy the pmql correctly

resources/js/processes/screens/components/ScreenTemplateOptions.vue
This PR introduces API request cancellation for multiple requests using Axios's CancelToken feature. It addresses the issue of unintended data changes when multiple requests to retrieve "Shared Templates" and "My Templates" are triggered, especially on slower networks. With this implementation, only the latest request will be executed, improving the overall user experience.
- Introduced API request cancellation using Axios's CancelToken feature.
1. Ensure you have templates created for both "My Templates" and "Shared Templates".
2. Navigate to Designer > Screen.
3. Open your Network panel and, if needed, update your network to use 'Slow 3G' to mimic a slower network.
4. Select the '+ Screen' button.
5. Before the templates are loaded, change the template type from "Shared Templates" to …
=> Implement API Request Cancellation for Multiple Requests for Screen Templates

resources/js/processes-catalogue/components/ProcessOptions.vue
- [FOUR-15080](https://processmaker.atlassian.net/browse/FOUR-15080)
ci:deploy
ci:next
[FOUR-15080]: https://processmaker.atlassian.net/browse/FOUR-15080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15080:Re Run Wizard does not align correctly when is a ipad

resources/js/tasks/components/TasksList.vue
- Create a process with large name
- Create a request 
- Complete the request entering some values in the form 
- Create another request 
- Click on Quick Fill button
- Check on the list 
- Hover on the right  side of the row
- Check the eye button
https://processmaker.atlassian.net/browse/FOUR-15040
ci:deploy
ci:next
=> QA Observation Bugfix/four 15040: The eye view button overflows from the row in Quick fill list

resources/js/common/advancedFilterStatusMixin.js, resources/js/common/setDefaultAdvancedFilterStatus.js, resources/js/requests/index.js
See https://processmaker.atlassian.net/browse/FOUR-15083
Fixes the default requests "My Requests" page showing all requests that the user participated in.
Solution was to add the current user to the default advanced filter for that page
ci:next
=> Fix requests page default advanced filter

resources/js/processes/screens/components/CreateScreenModal.vue
This PR resolves an issue where clicking the back arrow button in the Preview Template modal of the Create Screen modal reset the selected template type from "My Templates" to "Shared Templates". 
The solution involves changing the `v-if` directive to `v-show`, ensuring that the select list and template options remain intact when navigating back from the Preview Template modal.
1. Navigate to Designer > Screen.
2. Select the '+ Screen' button.
3. Update the template type from "Shared Templates" to "My Templates".
4. Select "Preview Template" for any template.
5. Click the back arrow button.
6. Ensure that the template type remains unchanged and is still "My Templates".
- [FOUR-15120](https://processmaker.atlassian.net/browse/FOUR-15120)
ci:next
ci:deploy
[FOUR-15120]: …
=> Preserve Selected Template Type on Preview Template Back Button

ProcessMaker/ImportExport/Exporters/ScreenTemplatesExporter.php, resources/views/processes/screens/myTemplates.blade.php, resources/views/processes/screens/publicTemplates.blade.php, tests/Feature/Templates/Api/ScreenTemplateTest.php
Missing Import Button for Screen Templates for Users with Full Permissions
An issue has been identified where the Import button is not visible for Screen Templates. This occurs for users who have been granted full permissions. (NOT AN ADMIN USER)
1. Create a new user account and assign full permissions.
2. Login with the newly created user.
3. Navigate to Designer -> Screens.
4. Access both the 'My Templates' and 'Shared Templates' tabs.
5. Observe that the Import button is missing from the interface in both tabs.
Users with full permissions should have access to the Import button in the Screen Templates section, allowing them to import screen templates seamlessly. This button should be visible and functional in both the 'My Templates' and 'Shared Templates' tabs.
Investigate and resolve …
=> FOUR-15098: Fix Missing Import Button for Screen Templates of Users with Full Permissions

resources/js/tasks/index.js, resources/views/tasks/index.blade.php
Inbox, Priority and Drafts tabs should not have counters
removed tabs counters
https://processmaker.atlassian.net/browse/FOUR-14712
ci:next
=> observation/FOUR-14712-B Inbox, Priority and Drafts tabs should not have counters

ProcessMaker/PackageHelper.php, resources/js/components/templates/SelectTemplateModal.vue, resources/js/processes/components/CreateProcessModal.vue, resources/js/processes/modeler/components/ModelerApp.vue, resources/views/processes/list.blade.php
**Steps to reproduced:**
- Go to process
- Create a new process from AI
- Generate a process and use model
- Complete name process and save
The modeler is loaded twice.
- Verify if AB testing is installed and redirect to AB testing URL version
- [FOUR-15118](https://processmaker.atlassian.net/browse/FOUR-15118)
- [package-ai PR](https://github.com/ProcessMaker/package-ai/pull/148)
- [core PR](https://github.com/ProcessMaker/processmaker/pull/6722)
ci:next
[FOUR-15118]: https://processmaker.atlassian.net/browse/FOUR-15118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Observation/FOUR-15118: When generating a process from AI, modeler is loaded twice.

resources/js/components/shared/FilterTable.vue
Table column widths not reset after resize the screen 
Added a Zoom adjust to calculate the width of the columns
https://processmaker.atlassian.net/browse/FOUR-15029
ci:deploy
ci:next
=> observation/FOUR-15029 Table column widths not reset after resize the screen 

resources/js/components/shared/LaunchpadSettingsModal.vue
Control modal's are overflow with resize of the screen
- Control modal's  should not be overflow with resize of the screen
1. Create a process 
2. Add alternatives
3. Click on publish to pen the modal
4. Wait to launchpad modal will be open 
5. Resize the screen 
- [FOUR-15117](https://processmaker.atlassian.net/browse/FOUR-15117)
ci:deploy
ci:next
[FOUR-15117]: https://processmaker.atlassian.net/browse/FOUR-15117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15117:Control modal's  are overflow with resize of the screen

resources/js/components/templates/ScreenTemplateCard.vue, resources/js/processes/screens/components/CreateScreenModal.vue
When creating a blank screen with a default template other than the blank template configured, the default template is referenced instead of the blank template.
Expected Behavior: 
- A blank screen should be created when selected, regardless of the default template configuration.
- A screen referencing the default template is created instead of the selected blank screen.
- The UI interactions have been improved to determine when to create from a template and when to create from a Blank Template.
Conduct manual tests. Everything should work as expected, including the addition of the use case mentioned in this ticket.
ci:deploy
ci:next
- [FOUR-15151](https://processmaker.atlassian.net/browse/FOUR-15151)
[FOUR-15151]: …
=> FOUR-15151: Incorrect Template Reference When Creating Blank Screen with Default Template Configured

database/migrations/2024_04_22_203320_create_alternatives_table.php
There is a problem when the package ab testing is installed but not enabled in license.
Please consider to move the alternatives table into core to keep the schema consistency required for the Process model and its relationship with Alternative model.
[FOUR-15214](https://processmaker.atlassian.net/browse/FOUR-15214)
https://github.com/ProcessMaker/package-ab-testing/pull/52
ci:next
ci:deploy
ci:package-ab-testing:FOUR-15214
[FOUR-15214]: https://processmaker.atlassian.net/browse/FOUR-15214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15214 Move ab-testing alternatives table migration into core

resources/js/processes/components/CreateProcessModal.vue
- Collaborative not working
- Launch Pad not opened
- Fix modeler URL when a Process is created
- Create a new process
- Publish the process
Workaround: Fix the modeler URL after a process is created.
- https://processmaker.atlassian.net/browse/FOUR-15203
- https://processmaker.atlassian.net/browse/FOUR-14910
ci:next
ci:deploy
ci:package-ab-testing:bugfix/FOUR-15203
=> FOUR-15203 Fix problems caused by an incorrect modeler URL when creating an new Process

ProcessMaker/Http/Controllers/Api/BookmarkController.php, ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, routes/api.php
The default lis Processes -> All process is taking time, improve the time of response
- Create a new function isolated with the columns required to show the cards in Proceses
- Have a lot of process more than 800
- https://processmaker.atlassian.net/browse/FOUR-15124
ci:next
ci:deploy
=> FOUR-15124

ProcessMaker/Http/Controllers/Api/GroupController.php, resources/js/admin/groups/components/GroupsInGroupListing.vue, resources/js/admin/groups/components/UsersInGroupListing.vue
The id of the assigning users and groups do not show the correct ID.
The search is not performed by fullname
- Change attr id to member_id
Assign users or groups to a group and check that it has the correct ID.
In the users section, search by fullname
- [FOUR-5817](https://processmaker.atlassian.net/browse/FOUR-5817)
ci:next
ci:deploy
[FOUR-5817]: https://processmaker.atlassian.net/browse/FOUR-5817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Error in Group/Users

ProcessMaker/Http/Controllers/Api/BookmarkController.php
The bookmark list does not work correctly with the pagination
1. Go to Processes
2. Go to Bookmkark List
3. Have more than 12 processes bookmarked
The bookmark needs to enable the pagination
- https://processmaker.atlassian.net/browse/FOUR-15217
ci:next
ci:deploy
=> FOUR-15217

resources/js/components/SelectFromApi.vue, resources/views/tasks/edit.blade.php
Inactive users are displayed in the list of users to reassign.
- add the query parameter status in the reassign section.
create a process, set a task allow reassign.
create a case.
in task reassign y review the list of users all are of status active.
- [FOUR-7633](https://processmaker.atlassian.net/browse/FOUR-7633)
ci:next
[FOUR-7633]: https://processmaker.atlassian.net/browse/FOUR-7633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [31012] Inactive users are listed when reassigning task

ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, resources/js/processes-catalogue/components/mixins/ProcessesMixin.js
After the refresh the bookmark is enable but the process was not bookmarked
ci:deploy
ci:next
=> FOUR-15233: When select a Screen Launchpad the process appears bookmarked

resources/js/processes-catalogue/components/ProcessesCarousel.vue, resources/sass/app.scss
The  lines that pass through the carousel slides are too thin, they need to be adjusted as figma desig:
figma design:
Actual Design:
- Add styles to indicators in the carousel. 
NOTE: this change will be affect styles related  with carousel in all plataform
- [FOUR-15220](https://processmaker.atlassian.net/browse/FOUR-15220)
ci:next
[FOUR-15220]: https://processmaker.atlassian.net/browse/FOUR-15220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15220: Adjust the lines that pass through the carousel slides

ProcessMaker/Http/Controllers/Api/TemplateController.php
When attempting to modify the description within the configuration of a Screen Template, the system does not allow changes to be made. A validation error message appears, preventing the update.
1. Navigate to the screen list.
2. Create a new screen form.
3. Save the created screen as a template.
4. Go to the template list.
5. Search for and select the template created.
6. Open the configuration of the template.
7. Attempt to make changes to the template. DO NOT CHANGE THE NAME
8. Save the new configuration.
It is currently not possible to change the configuration of a screen template. Upon attempting to save the updated configuration, the following error message is displayed:  
`The template name must be unique.`
Users should be able to change the configuration of a screen template …
=> FOUR-15207: Fix Screen Template config update

resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue
There should not be a scroll if it is not necessary in Guide Templates
- https://processmaker.atlassian.net/browse/FOUR-15231
ci:deploy
ci:next
=> feature/FOUR-15231: There is a botton scroll in Guide Templates

resources/js/processes/screen-templates/components/CreateScreenTemplateForm.vue, resources/views/processes/screen-builder/screen.blade.php
The "Share Template" option does not appear in the modal template from the Save as Template Option in the Modeler. This issue affects users with designer roles trying to share templates directly from the screen editing interface.
1. Log in with a designer user.
2. Navigate to 'Screens'.
3. Create a new screen.
4. Add some controls to the screen.
5. Save the changes.
6. Click on 'Options'.
7. Select 'Save as Template'.
The "Share Template" option does not appear in the template modal opened from screen edit.
The "Share Template" option should appear in the template modal open from screen edit if the user is the owner of the template.
- Please follow the Steps to Reproduce and ensure that the Current Behavior is met.
- Ticket: [FOUR-15227](https://processmaker.atlassian.net/browse/FOUR-15227 …
=> FOUR-15227: Fix Shared Template option

resources/js/components/templates/ScreenTemplateCard.vue, resources/js/processes/screens/components/CreateScreenModal.vue, resources/js/processes/screens/components/ScreenTypeDropdown.vue, resources/js/processes/screens/components/TemplateTypeDropdown.vue
Ticket: [FOUR-15228](https://processmaker.atlassian.net/browse/FOUR-15228)
The Create Screen Modal is missing data-cy attributes that are necessary for testing.
- Add data-cy attributes to the Screen Template Card, Screen Type Dropdown, and Template Type Dropdown components.
1. Go to branch `observation/FOUR-15228` in `processmaker`.
2. Go to Designer → Screens → +SCREEN.
3. Open your console to view the data-cy attributes that have been added to the modal elements listed above.
ci:next
[FOUR-15228]: https://processmaker.atlassian.net/browse/FOUR-15228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15228 | Add Data Test Attributes to Create Screen Modal

resources/views/requests/show.blade.php
Comments is disable in Request and Task
- The comments tab should be enable to put comments to users in Request and Task
1. Log in with Super admin user
2. Import a process
3. Create a request
4. Go to comments tab
- [FOUR-15156](https://processmaker.atlassian.net/browse/FOUR-15156)
ci:next
ci:deploy
ci:package-comments:bugfix/FOUR-15156
[FOUR-15156]: https://processmaker.atlassian.net/browse/FOUR-15156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15156: Comments is disable in Request and Task

ProcessMaker/Templates/ScreenTemplate.php, tests/Feature/Templates/Api/ScreenTemplateTest.php
When accessing the configuration of a shared screen template with the ADMIN user who did not originally create it, if you update the screen template, the ownership of the screen template is changed.
Since only an update is being performed on a preexisting template, there is no need to modify the user_id of the template.
- Follow the reproduction steps in the QA server.
ci:deploy
ci:next
- [FOUR-15232](https://processmaker.atlassian.net/browse/FOUR-15232)
[FOUR-15232]: https://processmaker.atlassian.net/browse/FOUR-15232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15232: When the admin updates a screen template, the ownership of the screen template is changed

resources/js/processes/screens/components/CreateScreenModal.vue
The red box of required fields is lost with screen Template in Screen modal 
Added the required validation when a template is selected
1. Go to Screens
2. Click on + Screen 
3. Select one template
4. Do not fill out the required fields
5. Press Save button
https://processmaker.atlassian.net/browse/FOUR-15275
ci:deploy
ci:next
=> observation/FOUR-15275 The red box of required fields is lost 

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Ticket: [FOUR-15218](https://processmaker.atlassian.net/browse/FOUR-15218)
When navigating to Guided Templates by pasting a url into the browser, i.e. `https://next-qa.processmaker.net/process-browser?guided_templates=true&template=invoice_approval`, the link redirects to `/process-browser`.
- In `ProcessCatalogue.vue`, added a method `hasTemplateParams()` to evaluate if the current URL contains `&template=`.
- In the `selectCategorie()` method, we are calling `window.history.replaceState()`, which redirects to `/process-browser`.
- If the current URL `hasTemplateParams` or `hasGuidedTemplateParamsOnly`, we do not `replaceState()`.
1. Go to branch `observation/FOUR-15218` in `processmaker`.
2. Go to Processes. Click on a Guided Template. When the Help Process Modal opens, copy the link.
- …
=> FOUR-15218 | Guided Templates: Process Helper Direct Link Not Working

ProcessMaker/JsonColumnIndex.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Traits/Indexable.php, config/database.php
- And index is incorrectly applied to the process_request_tokens table
- Add and environment variable to enable/disable json data index.
- Fix the table used to index the json data when a Tasks Saved Search is created/updated
- Improve some queries
- Create a Saved Search from Tasks
- Add or change the pmql to include filter by a data variable. E.g. `data.form_input_1="test"`
- Test this two steps with `ENABLE_INDEXED_JSON_COLUMNS=false` in .env
- Test this two steps with `ENABLE_INDEXED_JSON_COLUMNS=true` in .env
- https://processmaker.atlassian.net/browse/FOUR-15274
ci:next
ci:deploy
=> FOUR-15274 Fix ALTER table for adding INDEX based on the pmql is affecting the DataBase performance

resources/js/components/templates/TemplateSearch.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/utils/SearchCards.vue
- Go to Process Calatogue
- Click on All process
- Check the spaces in search engine of process
https://processmaker.atlassian.net/browse/FOUR-15288
ci:deploy
ci:next
=> QA Observation bugfix/FOUR-15288: The search process in Launchpad is very close to the top of the screen

ProcessMaker/Http/Controllers/Api/ProcessTranslationController.php, ProcessMaker/ProcessTranslations/ProcessTranslation.php, resources/js/processes/translations/components/ProcessTranslationListing.vue
- Go to a process configuration
- Add a translation
To fix:
- Character a is concatenating in the translation name in the list of translations every time we get a callback response in Process Translations
- There is an error when deleting a translation
- Percentage styles
- Reactivity issue updating percentage
- Removed debug character in the translation name
- Fix deleting issue
- Fixed style for percentage number
- Fix reactivity issue when updating progress
- [FOUR-15299](https://processmaker.atlassian.net/browse/FOUR-15299)
- [package-ai PR](https://github.com/ProcessMaker/package-ai/pull/152)
- [core PR](https://github.com/ProcessMaker/processmaker/pull/6784)
ci:next
ci:package-ai:observation/FOUR-15299
[FOUR-15299]: https://processmaker.atlassian.net/browse/FOUR-15299?atlOrigin=eyJpI …
=> https://processmaker.atlassian.net/browse/FOUR-15299: Character a is concatenating every time we get a callback response in Process Translations

resources/js/tasks/components/ListMixin.js, resources/js/tasks/index.js
When loading the Tasks page, it it calling two times the fetch of the table during the components mount.
- Debounce the fetch.
- In a ci-deploy or qa environment go to Tasks page
- https://processmaker.atlassian.net/browse/FOUR-15305
ci:next
ci:deploy
=> FOUR-15305 Prevent to call multiple consecutive times the tables fetch

database/migrations/2024_04_26_183624_add_index_to_case_number_column_in_process_requests_table.php
This PR adds a database migration which adds an index to the `case_number` column to the `process_requests` table to improve the performance. Without the index, the performance of the tasks index API endpoint suffers.
ci:next
1. Login to your instance
2. Have 500+ tasks
3. Navigate to the "Tasks" page
4. Notice the slow response (2+ seconds)
- Added the index in a migration file
- [FOUR-15306](https://processmaker.atlassian.net/browse/FOUR-15306)
- [FOUR-15287](https://processmaker.atlassian.net/browse/FOUR-15287)
[FOUR-15306]: https://processmaker.atlassian.net/browse/FOUR-15306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-15287]: …
=> FOUR-15306: Add index to `case_number` column for the `process_requests` table

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Traits/TaskControllerIndexMethods.php
See FOUR ticket: https://processmaker.atlassian.net/browse/FOUR-15314
ci:next
ci:deploy
=> [FOUR-15314] Bypass handleOrderByRequestName method in API Task Controller

ProcessMaker/Http/Controllers/HomeController.php, routes/web.php
- Configure SAML on your environment
- Enable the option Default SSO Login to use SAML
- Prepare a process for using web entry (with authentication mode) in the start event
- Use the web entry link (you can use an incognito window to confirm you do not have any session)
- At this point, you will be redirected to the home page instead of the screen of the web entry.
The web entry link is redirected to the home page after logging in with the SAML authentication instead of showing the screen. You have to see the video to understand the behavior.
The web entry link for start events or tasks should be redirected to the screen when using SAML authentication.
The SAML authentication providers calls the acs endpoint with no  cookie data, so a new …
=> FOUR-13976: Web entry link not redirecting to the screen when using default SSO SAML authentication

ProcessMaker/Http/Controllers/Api/FileController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Http/Controllers/Api/TaskDraftController.php, ProcessMaker/Models/Media.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/TaskDraft.php, resources/js/modules/autosave/draftFileUploadMixin.js, resources/js/tasks/components/PreviewMixin.js, resources/js/tasks/components/TasksPreview.vue, resources/js/tasks/show.js, resources/views/tasks/edit.blade.php
See https://processmaker.atlassian.net/browse/FOUR-15242
When saving drafts, we didn't consider how to handle file uploads, which is a tricky process given our current file handling architecture.
This PR associates files to a TaskDraft first. Only when the task is saved, it moves the files from TaskDraft to be associated with a ProcessRequest. There is also additional handling for deleting files in drafts.
This also solves a long standing issue in production. Previously, if a user edits a task and changes a file, but does not complete the task, the changed file is still saved in the processes request. This PR fixes that. If the user clear's their draft, the original file will be restored.
Also tested in web entry, even though web entry does not support drafts.
- Create a 2 task process …
=> Correctly handle files in drafts

ProcessMaker/Models/CallActivity.php, ProcessMaker/Models/Process.php
- Use getPublishedVersion to get the next subprocess version
- Create a process with sub process
- The sub process must be published with two versions A/B
- Run the process, the sub process must follow the A/B configuration
- https://processmaker.atlassian.net/browse/FOUR-15325
ci:next
ci:deploy
=> FOUR-15325 Use getPublishedVersion to get the next subprocess version

resources/js/components/common/mixins/datatable.js, resources/js/tasks/components/QuickFillPreview.vue
This is a race-case issue, with 2 competing API calls to tasks endpoint.
Please take a look to this comment for better understanding of the problem.
https://processmaker.atlassian.net/browse/FOUR-15321?focusedCommentId=398240
- Added a prop `fetchOnCreated` to datatables mixin
- Set `fetchOnCreated` to `false` when calling from **Quick Fill**
- Have tasks from different requests
- Create a request and in a task open the Quick Fill feature
- Open the browser inspector in network tab, and take a look to the api call to tasks endpoint, you should see only one api call.
- [FOUR-15321](https://processmaker.atlassian.net/browse/FOUR-15321)
ci:next
ci:deploy
[FOUR-15321]: https://processmaker.atlassian.net/browse/FOUR-15321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> Observation/FOUR-15321: review the filters of a Task in Smart Inbox

ProcessMaker/Http/Middleware/TwoFactorAuthentication.php
When the user logs in using SSO, the 2FA authentication method must not be enabled.
- Validate if the user was logged by SSO.
Configure SSO Login and Authentication 2FA.
loggin by SSO
the method of authentication 2FA must not be enabled.
- [FOUR-15329](https://processmaker.atlassian.net/browse/FOUR-15329)
ci:next
ci:deploy
[FOUR-15329]: https://processmaker.atlassian.net/browse/FOUR-15329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SSO not working with 2FA

ProcessMaker/Http/Controllers/Api/ScreenController.php
CSS Preview not working when a screen template is edited and CSS is updated.
1. Edit an existing screen template
2. Add CSS
3. Save the screen template
4. Preview the CSS of that template
- When a Screen Template is updated, only the associated screen is updated. The proposed solution is to also update the `custom_css` field in the screen_templates table.
- Follow the reproduction steps on deployed QA server.
ci:next
ci:deploy
- [FOUR-15350](https://processmaker.atlassian.net/browse/FOUR-15350)
[FOUR-15350]: https://processmaker.atlassian.net/browse/FOUR-15350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15350: Screen Template CSS Preview not working

ProcessMaker/Http/Controllers/TaskController.php, ProcessMaker/Http/Resources/Task.php, ProcessMaker/Models/TaskDraft.php, ProcessMaker/Traits/TaskResourceIncludes.php, config/app.php, resources/js/components/common/DataLoading.vue, resources/js/components/common/mixins/apiDataLoading.js, resources/js/modules/autosave/autosaveMixin.js, resources/js/tasks/components/PreviewMixin.js, resources/js/tasks/components/TasksPreview.vue, resources/js/tasks/index.js, resources/views/tasks/edit.blade.php, resources/views/tasks/index.blade.php, resources/views/tasks/preview.blade.php
We anticipate some clients will not want to use the task drafts feature
- Allow disabling drafts by setting `TASK_DRAFTS_ENABLED` to false
This CI instance has drafts disabled. Ensure drafts are not being saved or loaded
- https://processmaker.atlassian.net/browse/FOUR-15349
ci:next
ci:TASK_DRAFTS_ENABLED=false
=> Allow disabling task drafts with env var setting

ProcessMaker/Http/Controllers/Api/TaskController.php
Sorting for saved searches with a large results (generally 1000+ tasks) are slow (3+ secs) when sorted.
1. Log in 
2. Go to Tasks page
3. Have 1000 or more tasks
4. Filters works to status column
5. Create a saved search
6. Use Filters to status column
There were duplicate queries for selecting and counting the results of the saved search query, deduplicating them improve performance.
Resort the same saved search and notice the improved speed.
- [FOUR-15339](https://processmaker.atlassian.net/browse/FOUR-15339)
- [package-savedsearch PR](https://github.com/ProcessMaker/package-savedsearch/pull/438)
ci:next
ci:deploy
ci:package-savedsearch:bugfix/FOUR-15339
.
[FOUR-15339]: https://processmaker.atlassian.net/browse/FOUR-15339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> FOUR-15339: Improve saved search sorting performance

resources/js/tasks/components/QuickFillPreview.vue, resources/js/tasks/components/TasksList.vue
Quick fill, the columns from preview are cut
The size of the tasks list columns is independent from the quickfill preview 
https://processmaker.atlassian.net/browse/FOUR-15405
ci:deploy
ci:next
=> bugfix/FOUR-15405 Quick fill, the columns from preview are cut

resources/js/inbox-rules/components/InboxRuleEdit.vue, resources/js/inbox-rules/components/InboxRules.vue
Deactivation dates were changing when clicking back when editing an inbox rule.
- Refactor deactivation dates component to better handle timezones.
- Set your user's timezone to UTC
- Reproduce steps in the jira issue
- https://processmaker.atlassian.net/browse/FOUR-15398
ci:next
=> Fix deactivation date selector for inbox rules

resources/js/components/shared/PaginationTable.vue
1.Go to /process-browser
2.Find a process with more than 15 requests created (eg: Verify Message Events)
3.Click on the process and see the requests
4.Go to the second page of the requests
5.Select 30 or 50 items
The list of requests disappears.
- [FOUR-15401](https://processmaker.atlassian.net/browse/FOUR-15401)
ci:next
ci:deploy
[FOUR-15401]: https://processmaker.atlassian.net/browse/FOUR-15401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15401:The request list disappears with the selection of 30 or 50 items per page, LaunchPad

ProcessMaker/Http/Controllers/ProcessController.php
The page Processes is not displayed.
- Remove unnecessary calls ProcesTemplate and Process
visit url /processes
The page Processes must be displayed correctly.
- [FOUR-15432](https://processmaker.atlassian.net/browse/FOUR-15432)
ci:next
ci:deploy
[FOUR-15432]: https://processmaker.atlassian.net/browse/FOUR-15432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Server error displayed when opening processes in sidebar menu

resources/js/processes-catalogue/components/utils/Card.vue
1. Create a process with many words 
2. Go to launch pad 
3. Search the card of the process created
The words break anywhere, inside the card in launch pad
- [FOUR-15421](https://processmaker.atlassian.net/browse/FOUR-15421)
ci:deploy
ci:next
[FOUR-15421]: https://processmaker.atlassian.net/browse/FOUR-15421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15421:The words break inside the launch pad card

resources/js/processes-catalogue/components/CardProcess.vue
The search engine does not filter processes that are found on other pages except page 1
- https://processmaker.atlassian.net/browse/FOUR-15435
ci:deploy
ci:next
=> Search does not work when changing pagination in LaunchPad

ProcessMaker/Exception/HttpABTestingException.php, ProcessMaker/Jobs/BpmnAction.php, ProcessMaker/Traits/HasVersioning.php
1. Import attached process
2. Search process and edit
3. Enable alternative B
4. Click on publish button
5. Click on A+B Alternatives
6. Go to A/B Settings
7. Type `age>21` in Expression field
8. Click on save and publish button
9. Go to +Case button
10. Type name of process 
11. Click on Start button
We get the next error: `Undefined variable "age". Variable "age" is not valid around position 1 for expression age>21`.
- The alternative B is required when the age is over 21. However, when the process starts, the "age" variable is not present in the request data, causing the server error.
- The proposed solution shows the error message.
Follow the reproduction steps of above.
ci:next
ci:deploy
ci:package-ab-testing:observation/FOUR-15341
- …
=> FOUR-15341 Server error to create case with configuration in expression to publish process in AB Settings - Final solution

resources/js/common/advancedFilterStatusMixin.js, resources/js/components/shared/PmqlInputFilters.vue, resources/js/tasks/index.js, resources/views/tasks/index.blade.php
The pmql to filter by the current user was missing in the initial task load so we were showing all tasks to the admin user.
- Do not load tasks when the component is created. Instead do it on mounted and wait for the nextTick to ensure all the pmql-input filters have been parsed.
- Remove unnecessary doNotFetchOnPmqlChange flag
- Remove unnecessary call to onSearch() to prevent duplicate task calls.
- Follow the steps in the jira issue
- Additionally, re-test https://processmaker.atlassian.net/browse/FOUR-14325
- https://processmaker.atlassian.net/browse/FOUR-15444
- Re-test: https://processmaker.atlassian.net/browse/FOUR-14325
ci:next
ci:deploy
=> Fix task requests running without specifying user

resources/js/components/shared/AddToProjectModal.vue
1. Go to Screen list
2. Assign a project show the message
3. Assign the same project before and show the message
4. The message for new assign or update the project is the same
- Review if the asset was assigned into the project in order to define the action: update or create
1. Go to Screen list
2. Assign a project show the message `Asset successfully assigned in the following project(s): PaosProject`
3. Assign the same project before and show the message `The asset was updated to the following project(s): PaosProject`
- https://processmaker.atlassian.net/browse/FOUR-15390
ci:next
ci:deploy
=> FOUR-15390

resources/views/tasks/editQuickFill.blade.php
https://processmaker.atlassian.net/browse/FOUR-15433
Quick field: `Task` Column is empty
1. Create a Request
2. Open task
3. Press Quick Fill button
The Task column is empty.
ci:next
=> FOUR-15433 Quick field: `Task` Column is empty

ProcessMaker/Models/ProcessTemplates.php, ProcessMaker/Templates/ProcessTemplate.php, ProcessMaker/Templates/ScreenTemplate.php, ProcessMaker/Templates/TemplateRequestHelperTrait.php, tests/Feature/Templates/Api/ProcessTemplateTest.php
When we have more than 100 templates, when entering the Templates tab, it takes a while to enter the list of templates.
1. Click on Designer 
2. Click on Processes 
3. Click on Templates
- The columns `svg` and `manifest` were excluded from the API index endpoint because their use is not necessary and they contain large amounts of data, which made the load excessive.
- Conduct tests with a large number of records in process_templates, both with and without the changes; you will notice that the response time of the request is considerably lower.
- [FOUR-15465](https://processmaker.atlassian.net/browse/FOUR-15465)
ci:next
ci:deploy
[FOUR-15465]: https://processmaker.atlassian.net/browse/FOUR-15465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15465: When we enter the Templates tab, the more templates we have created, the longer it takes to show the list

ProcessMaker/Http/Resources/Task.php, ProcessMaker/Traits/TaskResourceIncludes.php, resources/js/components/PMBadgesFilters.vue, resources/js/inbox-rules/components/InboxRuleFilters.vue, resources/js/tasks/components/TasksList.vue, resources/lang/en.json
- Status column was showing when creating a new inbox rule. Its unnecessary and confusing because only In Progress tasks can have an inbox rule.
- Wording was incorrect on Inbox Rule when there were no results
- Filter badges were not user friendly
- Refactor to fix the above issues
- Ensure there is no Status column when creating a new inbox rule from a Task or Saved Search
- Ensure the badges look correct
- Ensure the no-results text that displays is correct
- https://processmaker.atlassian.net/browse/FOUR-15450
ci:next
=> Remove status column, update copy, and fix badges on inbox rules

ProcessMaker/Http/Controllers/Process/ModelerController.php
This PR addresses a regression where PM Blocks with the 'Inactive' status were still appearing in the Modeler left PM Block rail. The issue stemmed from a missing request parameter `status=active` when retrieving the PM Block list, causing inactive PM Blocks to be included in the response.
To resolve this, the missing request parameter `status=active` has been added to ensure that only active PM Blocks are retrieved and displayed in the Modeler left rail.
1. Create a PM Block.
2. Configure the PM Block and update the status to 'INACTIVE'.
3. Save the configurations.
4. Open a process in Modeler.
5. Select 'PM Blocks' in the left rail menu.
6. Ensure that the inactive PM Block is not displayed in the left rail.
7. Repeat the test with multiple inactive PM Blocks to confirm consistent …
=> Fix Regression: Hide Inactive PM Blocks in Modeler Left Rail

resources/js/requests/index.js
1.Log in
2.Go to requests
Requester is shown twice.
- [FOUR-15462](https://processmaker.atlassian.net/browse/FOUR-15462)
ci:deploy
ci:next
[FOUR-15462]: https://processmaker.atlassian.net/browse/FOUR-15462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15462:Requester is shown twice in "My requests"

resources/js/components/requests/requestModal.vue, resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json, resources/views/requests/show.blade.php
Login into ProcessMaker
The actual Tab Request should change to Cases
Message when user Creates a Case: The actual message “We’ve made it easy for you to start a Case for the following Processes. Select a Process to start your Case” to “Select a Process below to get started”
Message when user Creates a Case: The actual message “Finding a Request available to you…” should change to “Finding you Processes”
https://processmaker.atlassian.net/browse/FOUR-16252
ci:deploy
ci:next
=> FOUR-16252: FOUR-15539: Update Label Request in 3 places added in Change control

config/services.php, resources/views/auth/newLogin.blade.php, resources/views/layouts/layout.blade.php, resources/views/layouts/minimal.blade.php, resources/views/shared/userway.blade.php
This PR implements detection for the accessibility package and integrates UserWay when the package is installed. The integration includes loading the appropriate scripts to display the UserWay accessibility icon on all pages, including the login page. If the accessibility package is uninstalled, the UserWay icon will no longer be displayed.
- Add a check for the accessibility package.
- Include UserWay scripts if the accessibility package is detected.
ci:next
Test Case A: Verifying UserWay Integration
1. Ensure you have a UserWay account configured.
2. Ensure the accessibility package is installed.
3. Install the accessibility package if not already installed.
4. Navigate to any page within the application, including the login page.
5. The UserWay accessibility icon should be visible on …
=> Implement Package Detection for Accessibility Integration with Userway

composer.json, composer.lock
When installing the `phrity/websocket` package within the IDP Connector, an error in versioning occurs. 
```
phrity/websocket[2.1.0, ..., 2.1.3] require psr/log ^1.0 | ^2.0 -> found psr/log[1.0.0, ..., 1.1.4, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match.
```
- Downgrade require psr/log to version ^2.0
- Ensure that the IDP Connector is properly installed with no errors.
- Ensure that psr 2.0 is installed `composer require psr/log:^2.0`
- Ensure no errors occur when running `composer install` in Core.
- Ticket: [FOUR-13564](https://processmaker.atlassian.net/browse/FOUR-13564)
- [IDP Package](https://github.com/ProcessMaker/connector-idp/pull/35)
- ci:next
[FOUR-13564]: …
=> FOUR-13564: POC for Notification Integration

ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, ProcessMaker/Providers/RouteServiceProvider.php, routes/v1_1/api.php
This PR refactors the API route definitions for version 1.1 of our application. The changes include:
- Grouping `use` statements together for better organization.
- Applying middleware to the entire route group, making it clearer and easier to manage.
- Improving route naming conventions for better readability and consistency.
- Adding detailed comments to provide better context and understanding of the code.
1. Create a minimilized middleware for the v1.1 endpoints.
2. Defined a route group with middleware to apply it to all relevant routes within the group.
3. Create a first simple `tasks.index`
- Try the endpoint `/api/1.1/tasks`
- https://processmaker.atlassian.net/browse/FOUR-15867
ci:next
=> FOUR-15867 Refactor API Route Definitions for Version 1.1

ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, routes/v1_1/api.php
- Implement task endpoint in v1.1 middleware
- Try the endpoint `/api/1.1/tasks`
- https://processmaker.atlassian.net/browse/FOUR-15868
ci:next
ci:deploy
ci:api-test
ci:pm4-api-testing:FOUR-15868
.
=> FOUR-15868 Optimize Task Endpoint for Speed and Efficiency

ProcessMaker/Helpers/MobileHelper.php, ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, ProcessMaker/Models/Process.php, resources/js/app-layout.js, resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/js/processes-catalogue/components/utils/Card.vue, resources/lang/en.json, resources/sass/_variables.scss, resources/views/layouts/navbarMobile.blade.php, resources/views/processes-catalogue/mobile.blade.php, webpack.mix.js
https://processmaker.atlassian.net/browse/FOUR-16140
This is just a WIP commit so we can close the sprint. Research only. Feature will be implemented in Mobile Process Browser option-v2
=> FOUR-16140: Start on Mobile Process Browser option

ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, ProcessMaker/Http/Resources/V1_1/TaskScreen.php, ProcessMaker/Traits/TaskResourceIncludes.php, ProcessMaker/Traits/TaskScreenResourceTrait.php, routes/v1_1/api.php, tests/Feature/Api/V1_1/Fixtures/nested_screen_process.json, tests/Feature/Api/V1_1/TaskControllerTest.php, tests/Feature/Shared/RequestHelper.php
- Implement a faster endpoint to get the screen configuration for a task
Try the endpoint `/api/1.1/tasks/{taskId}/screen`
- https://processmaker.atlassian.net/browse/FOUR-15872
ci:deploy
ci:next
ci:pm4-api-testing:FOUR-15872
=> FOUR-15872 Implement task screen endpoint

resources/js/components/shared/EllipsisMenu.vue, resources/js/processes-catalogue/components/scss/processes.css
As a user, I want a streamlined way to access additional actions and settings without overwhelming the interface, so that I can efficiently navigate through information and focus on completing my work.
Changed the ellipsis menu style in tables  and in launchpad
https://processmaker.atlassian.net/browse/FOUR-15727
https://processmaker.atlassian.net/browse/FOUR-15728
ci:next
ci:deploy
=> [SUMMER] feature/FOUR-15727 Options Ellipsis on tasks page and Launchpad

resources/js/processes/scripts/components/ScriptListing.vue
Scripts tab does not display the new pagination. However, categories tab displays the new U
Changed the pagination component for scripts list
https://processmaker.atlassian.net/browse/FOUR-16542
ci:next
ci:deploy
=> [SUMMER] observation/FOUR-16542 Changed the pagination component for scripts list

ProcessMaker/ImportExport/Exporters/ProcessLaunchpadExporter.php
Processes created before 4.10.0 and that don’t have launchpad configured can’t be exported, a 500 error is returned.
- Prevent the "Undefined array key" error when working with arrays that might not have certain keys, using null coalesce operator to provide a default value if the key does not exist.
1. Have processes created before 4.10.0.
2. Make sure they don’t have the`process_launchpad` configured.
3. Try to export the process and see the 500 error.
`php artisan test --filter ProcessLaunchpadExporterTest` should pass as well.
- [FOUR-15845](https://processmaker.atlassian.net/browse/FOUR-15845)
ci:next
ci:deploy
[FOUR-15845]: https://processmaker.atlassian.net/browse/FOUR-15845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15845: 500 error exporting Processes, LaunchPad as the root cause

ProcessMaker/Templates/ProcessTemplate.php, tests/Feature/Templates/Api/ProcessTemplateTest.php
Ticket: [FOUR-16117](https://processmaker.atlassian.net/browse/FOUR-16117)
When creating a new Process by selecting a Process Template, the preview image associated with the template is not displayed in the `SelectTemplateModal`. This makes it difficult for users to visually identify the desired template during selection.
- Update the Process Templates query (see `ProcessTemplate.php`) to fetch `process_templates.svg` for UI rendering.
1. Go to branch `observation/FOUR-16117` in `processmaker`.
2. Go to Designer → Process → +PROCESS → Select a Template.
3. In the Template Details, the Template Preview should display.
ci:next
ci:deploy
[FOUR-16117]: https://processmaker.atlassian.net/browse/FOUR-16117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> FOUR-16117 | When Creating Processes From a Template, the Process View is Not Displayed

resources/js/processes/scripts/components/GenerateScriptTextPrompt.vue
- Go to scripts
- Create a script
- Click on generate script from text
- Click on "Give me inspiration"
This option does not show any type of suggestion, you see a blank space.
- Fix on apply suggestion method
Follow steps above. 
- Also click on a suggestion and the suggestion should replace the textarea content.
- [FOUR-15054](https://processmaker.atlassian.net/browse/FOUR-15054)
- [Microservice PR](https://github.com/ProcessMaker/pm4_ai/pull/13)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/6909)
ci:next
[FOUR-15054]: https://processmaker.atlassian.net/browse/FOUR-15054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-15054: "Give me inspiration" in AI scripts does not show anything

ProcessMaker/Providers/ProcessMakerServiceProvider.php, config/app.php
When migrating from the Classic Load Balancer to the Application Load Balancer, mixed content issues arose, which were resolved by using `URL::forceScheme('https');`. 
- This PR adds a way to configure this setting from the .env file. 
- This also solves issues related to SSO. 
- The force_https variable will be enabled as true by default.
- There should be no issues with mixed content or SSO on servers with the Application Load Balancer.
- [FOUR-16287](https://processmaker.atlassian.net/browse/FOUR-16287)
- [FOUR-16286](https://processmaker.atlassian.net/browse/FOUR-16286)
ci:next
ci:deploy
[FOUR-16287]: https://processmaker.atlassian.net/browse/FOUR-16287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-16286]: …
=> FOUR-16287: Forcing HTTPS

ProcessMaker/Http/Controllers/Api/ProcessController.php, ProcessMaker/Http/Controllers/ProcessController.php, resources/lang/en.json, resources/views/processes/edit.blade.php
- Create a new process.
- Add some elements to the process (such as a start event, a couple of tasks, and an end event).
- You can refresh your screen to validate that your changes are still there.
- Go to the process configuration and change the name of the process.
All the changes will be lost
The draft with the recent changes should still be there after renaming.
**Notes for QA:**
The information lost only occurs on unpublished versions. However, these changes exist in the version history as drafts before renaming the process.
- When saving in configuration, now we get the last version of the process and we update the BPMN.
- The button in configuration changed from **Save** to **Save and publish**
- If a draft exist for the process, when …
=> Bugfix/FOUR-14265: Drafts being lost after renaming the process

resources/js/processes/modeler/components/inspector/TaskDueIn.vue
Make UI changes to enable the mustache variable and save
- [FOUR-15681](https://processmaker.atlassian.net/browse/FOUR-15681)
https://github.com/ProcessMaker/processmaker-bpmn-moddle/pull/59
ci:deploy
ci:next
ci:processmaker-bpmn-moddle:feature/FOUR-15681
[FOUR-15681]: https://processmaker.atlassian.net/browse/FOUR-15681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15681:Make UI changes to enable the mustache variable and save

composer.json
Add in the composer.json the specific branch to use the package-slideshow
- https://processmaker.atlassian.net/browse/FOUR-16367
ci:deploy
ci:next
ci:package-slideshow:feature/FOUR-15522
=> FOUR-16367: Add in the composer.json the specific branch to use the package-slideshow

ProcessMaker/Http/Resources/Task.php, ProcessMaker/Models/ProcessRequest.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Traits/TaskResourceIncludes.php
ent event must redirect to another process if have this configuration
- add another process redirect feature for end event
https://github.com/ProcessMaker/processmaker/assets/1401911/165fccb7-6aee-494c-a372-ffbab294c465
- create the process A
- create the process B
- assign to both process the same user to the first task
- in process A create a end event 
- add end event redirection as process
- select the process B
- select the start event B
- run the process
-  https://processmaker.atlassian.net/browse/FOUR-15859
- https://github.com/ProcessMaker/screen-builder/pull/1609 
ci:next
=> FOUR-15859: On Process End - Start a request for another selected process

resources/js/components/templates/SelectTemplateModal.vue, resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessListing.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/js/processes-catalogue/components/utils/Card.vue, resources/js/processes-catalogue/index.js
https://processmaker.atlassian.net/browse/FOUR-14053
All Templates section (UI change)
1. Login into processMaker
2. Open Lounchpad Browser
3. Open All Templates option (should have the same design of process cards)
4. User should see a new design for all templates available
5. When user select a template, a modal that we have for templates should appear
6. User will use a template anda create a process
=> FOUR-14053 All Templates section (UI change)

resources/js/components/shared/FilterTable.vue, resources/js/components/shared/index.js
Introducing "Welcome Screens" can streamline the onboarding process.
Welcome Screens provide a structured introduction to the product or service.
They guide users through key features and functionalities, ensuring a smoother start.
**PRD:** https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3337584641/Welcome+Screens+V2
**My Request Items Show Participation and Initiations:**
This feature enhances the "My Request" section to display requests in which the user has participated as well as those they have initiated. 
It provides a comprehensive view of the user's involvement in requests, whether they've initiated them or joined them later.
Users can easily track the progress and status of requests they're actively involved in, regardless of whether they initiated them or joined as …
=> FOUR-15529: [Summer24] Participant (Home) Welcome Screens V2 

resources/js/processes/screen-builder/typeForm.js
Create a new control link like a button button in the Email Screen
- [FOUR-15820](https://processmaker.atlassian.net/browse/FOUR-15820)
ci:deploy
ci:next
ci:screen-builder:feature/FOUR-15820
ci:connector-send-email/FOUR-15820
[FOUR-15820]: https://processmaker.atlassian.net/browse/FOUR-15820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-15820: Create a new control link 

ProcessMaker/Console/Commands/BuildScriptExecutors.php, ProcessMaker/Models/ScriptDockerNayraTrait.php, ProcessMaker/ScriptRunners/Base.php, config/script-runners.php, docker-services/nayra/Dockerfile, resources/js/processes/scripts/components/ScriptEditor.vue, upgrades/2024_06_12_150527_create_nayra_script_executor.php
- Go to the script executors
- Build and deploy the Nayra-PHP Executor
- Create a PHP-Nayra Script
- Add some php code to test
- Run it!
- https://processmaker.atlassian.net/browse/FOUR-15875
ci:next
ci:deploy
=> FOUR-15875 Optimize Script Tasks Execution with Nayra Engine

ProcessMaker/Http/Resources/Task.php, ProcessMaker/Http/Resources/V1_1/TaskResource.php, ProcessMaker/Traits/TaskResourceIncludes.php, resources/js/bootstrap.js
- https://processmaker.atlassian.net/browse/FOUR-16001
ci:next
=> FOUR-16001 Implement resources and apiClient to use v1.1 in charts

ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, ProcessMaker/Models/Process.php, resources/js/processes-catalogue/components/Bookmark.vue, resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/Process.vue, resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessHeader.vue, resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/ProcessScreen.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/js/processes-catalogue/components/mixins/ProcessesMixin.js, resources/js/processes-catalogue/components/scss/processes.css, resources/js/processes-catalogue/components/utils/Card.vue, resources/js/processes-catalogue/index.js, resources/views/processes-catalogue/index.blade.php, resources/views/processes-catalogue/mobile.blade.php
Bookmarks not working on launchpad mobile.
- Refactor launchpad bookmarks to work on mobile.
See PRD and Figmas
- https://processmaker.atlassian.net/browse/FOUR-16326
- https://processmaker.atlassian.net/browse/FOUR-16616
=> Launchpad mobile bookmarks

resources/js/components/shared/LaunchpadSettingsModal.vue
Chart searcher stop to work in launch pad
Assign the default value when the API give errors
- Create chart in saved search
- Go to Process catalog
- Open Edit launchpad settings 
- Write in the input to chart search 
- Wait to search is completed
- https://processmaker.atlassian.net/browse/FOUR-15982
ci:deploy
=> FOUR-15982: Chart searcher stop to work in launchpad

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Traits/TaskControllerIndexMethods.php
See https://processmaker.atlassian.net/browse/FOUR-16632
Pagination was not working on task saved searches. We use task saved searches extensively for default in-progress and completed tasks lists.
We had done some refactoring to improve performance but a number of these changes introduced antipatterns and broke the saved search paginations.
- https://github.com/ProcessMaker/package-savedsearch/pull/435/files
- https://github.com/ProcessMaker/package-savedsearch/pull/437/files
- https://github.com/ProcessMaker/package-savedsearch/pull/438/files
- https://github.com/ProcessMaker/processmaker/pull/6806/files
- https://github.com/ProcessMaker/processmaker/pull/6823/files
It turns out, the performance issue actually came from a code change made many years ago where we replaced `paginate()` …
=> Add query-based pagination to tasks controller

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Traits/TaskControllerIndexMethods.php
https://github.com/ProcessMaker/processmaker/pull/6948 for next
Requires https://github.com/ProcessMaker/package-savedsearch/pull/450
ci:next
ci:bugfix/FOUR-16632-next
=> Add query-based pagination to tasks controller [next]

ProcessMaker/Repositories/TokenRepository.php, tests/Feature/Api/TaskAssignmentExecutionTest.php, tests/Feature/Api/processes/TaskConfiguredCustomDueIn.bpmn
FOUR-15508: Test the Variable Due In
- Add test
- https://processmaker.atlassian.net/browse/FOUR-16354
ci:deploy
ci:next
=> FOUR-16354: FOUR-15508: Test the Variable Due In

database/migrations/2024_06_27_180810_add_is_actionbyemail_column_for_process_request_tokens_table.php
API related to case history return the column process_request_tokens.is_actionbyemail
- create a new column `process_request_tokens.is_actionbyemail`
- https://processmaker.atlassian.net/browse/FOUR-15985
ci:next
=> FOUR-15985: API related to case history return the column process_request_tokens.is_actionbyemail

ProcessMaker/Models/ProcessRequest.php
Method "ProcessRequest::getScreensRequested" not optimal
Parse definitions from the BPMN for each token is not optimal, only parse BPMN once for each process related to the token
Open a request that have a lot of tokens in completed status.
https://processmaker.atlassian.net/browse/FOUR-16002
=> FOUR-16002 Improve show request complete view

ProcessMaker/Http/Resources/ProcessRequests.php, ProcessMaker/Models/ProcessRequest.php, resources/js/requests/components/RequestsListing.vue
- Add alternative as selectable column
- By default Alternative is not present
- Edit the configuration of Requests
- Add Alternative column
- https://processmaker.atlassian.net/browse/FOUR-16564
ci:next
ci:package-savedsearch:FOUR-16564N
=> FOUR-16564 Fix When a new instance is created, the column alternative shows up by default

ProcessMaker/Http/Resources/Task.php, ProcessMaker/Models/Process.php
Visibility Issue with 'Rule Expression' and 'Self Service' Assigned Tasks
- Improve getConsolidatedUsers method and use in self service.
- Create a Process with a Simple Task and a SelfService Task with Assignment Rules.
- Add an assignment rule to assign the second task to a group
- Submit
- Login with a user (could be non admin) that belongs to the group
- User must see the request In progress and in the All Request default saved search
- User can open the request
- User can claim the self service task
- https://processmaker.atlassian.net/browse/FOUR-14690
ci:next
=> FOUR-14690 Fix Visibility Issue with 'Rule Expression' and 'Self Service' Assigned Tasks

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/RequestController.php, resources/js/requests/components/RequestScreens.vue, resources/js/requests/components/screenDetail.vue, resources/views/requests/show.blade.php, routes/api.php
When there are too many tokens in a request, the information cannot be opened.
- The way information is obtained from closed forms has been changed
Steps in ticket
- [FOUR-16639](https://processmaker.atlassian.net/browse/FOUR-16639)
ci:next
[FOUR-16639]: https://processmaker.atlassian.net/browse/FOUR-16639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The summary screen of a request is not displayed V2

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Models/ProcessRequest.php, resources/js/requests/components/RequestScreens.vue, resources/js/requests/components/screenDetail.vue, resources/views/requests/show.blade.php, routes/api.php
- Remove preloading of filled screens (Requires: FOUR-16639)
- Limit the number of errors to show in the summary
- Create a process with a loop
- Generate tens of thousands of loops
- Open the request (or go to the request summary) 
- https://processmaker.atlassian.net/browse/FOUR-16637
ci:next
=> FOUR-16637 Fix The summary screen of a request is not displayed

database/factories/ProcessMaker/Models/UserFactory.php
This caused some tests to fail.
- Fix admin user factory, must be administrator, enabling the `is_administrator` property.
Run the tests.
- https://processmaker.atlassian.net/browse/FOUR-16993
ci:next
=> FOUR-16993 Fix admin user factory, must be administrator

ProcessMaker/Mail/TaskActionByEmail.php, ProcessMaker/Repositories/TokenRepository.php
Send an ABE Email when the row in the process_request_tokens is created
2. Configure an action by email for some task
3. Run a request
4. Review the email
- https://processmaker.atlassian.net/browse/FOUR-15823
ci:deploy
ci:next
ci:screen-builder:feature/FOUR-15510
ci:connector-send-email:feature/FOUR-15510
ci:processmaker-bpmn-moddle:feature/FOUR-15510
=> feature/FOUR-15823: Send an ABE Email when the row in the process_request_tokens was created

ProcessMaker/Http/Resources/Task.php
A server error is displayed
- add validation to definition for Rule expression and Self Service assigned tasks
1. Import attached process
2. Go to second task and assign other user
3. Click on publish button
4. Create a request of process
5. Go to designer page
6. Search process and edit
7. Disable interstitial(Display Next Assigned Task to Task Assignee)in start event
8. Click on publish button
9. Create a request of process
[FOUR-16996](https://processmaker.atlassian.net/browse/FOUR-16996)
ci:next
[FOUR-16996]: https://processmaker.atlassian.net/browse/FOUR-16996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-16996 Server error when creating a case after disabling the start event insterstitial

ProcessMaker/Mail/TaskActionByEmail.php, ProcessMaker/Repositories/TokenRepository.php
When you create a Screen Email some controls can have MUSTACHE VARIABLES and SOME URL are waiting for values like:
We need to user the following magic variable {{_request.id}} 
We need to create a custom magic variable {{_task.id}}
- https://processmaker.atlassian.net/browse/FOUR-16807
ci:deploy
ci:connector-send-email:feature/FOUR-15510
ci:next
=> feature/FOUR-16807: Parser the mustache and data for the Email Screen defined in Action By email used in the EMAIL

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Jobs/GenerateUserRecommendations.php, ProcessMaker/Jobs/SmartInbox.php, ProcessMaker/Models/RecommendationUser.php, ProcessMaker/Providers/RecommendationsServiceProvider.php, ProcessMaker/RecommendationEngine.php, database/factories/ProcessMaker/Models/RecommendationUserFactory.php, resources/js/tasks/components/TasksList.vue, resources/views/admin/users/edit.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/users/sidebar.blade.php, tests/Feature/Api/UsersTest.php, tests/unit/ProcessMaker/RecommendationEngineTest.php
See https://processmaker.atlassian.net/browse/FOUR-13468
Adds enable/disable on `profile/edit` and `admin/users/{user_id}/edit`
When disabled, no recommendation engine jobs should be run for that user and any existing recommendations should be deleted.
See recommendations engine testing instructions in https://github.com/ProcessMaker/processmaker/pull/6999
ci:next
=> FOUR-13468: Allow users to disable recommendations engine

ProcessMaker/Managers/MenuManager.php
This PR is part of: https://github.com/ProcessMaker/package-analytics-reporting/pull/71
- Dispatch menu created event in order to add the Analytics menu item into the top navigation menu.
- [FOUR-17047](https://processmaker.atlassian.net/browse/FOUR-17047)
- [FOUR-16604](https://processmaker.atlassian.net/browse/FOUR-16604)
ci:next
ci:package-analytics-reporting:task/FOUR-16604-next
[FOUR-17047]: https://processmaker.atlassian.net/browse/FOUR-17047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-16604]: https://processmaker.atlassian.net/browse/FOUR-16604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17047: Add an Analytics Tab to the ProcessMaker Platform (next)

ProcessMaker/Http/Middleware/GenerateMenus.php
Cases link is not marked as active when Cases page is visited 
- https://processmaker.atlassian.net/browse/FOUR-16649
ci:next
=> feature/FOUR-16649: Cases link is not marked as active when Cases page is visited

resources/js/processes/modeler/components/ProcessMap.vue, resources/js/processes/modeler/components/ProcessMapTooltip.vue, resources/js/processes/modeler/process-map.js
1.Create a  process
2.Open in modeler
3.Click on options
4.Click on documentation
5.Move the mouse to the pop-up
- Added flags in ProcessMap to know if it is used in documenting.
Reproduce the steps above
- https://processmaker.atlassian.net/browse/FOUR-17077
ci:next
=> FOUR-17077: The documentation of the elements are not shown in the doc-circle modal

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/utils/Card.vue
- Left space was added to Cards section
- Separator for inifinite scroll bar was improved
- When there are only 12 cards, separator is not shown anymore
- Login to PM
- Go to processes and check cards visualization
https://processmaker.atlassian.net/browse/FOUR-16888
ci:next
=> QA Observation Bugfix/FOUR-16888: Launchpad > there is not a space between cards and collapsed sidebar

resources/js/processes/modeler/components/inspector/TaskDueIn.vue, resources/lang/en.json
1. Create a screen 
2. Add a date picker 
3. Click on configuration
4. Go to Minimum Date
5. Try to add a variable not mustache (There is a validation)
6. Create a process 
7. Add task 
8. Go to variable due date
Variable task due date does not validate that value will be a mustache syntax 
- Variable task in due data of a task should validate the syntax of mustache like date picker in Screens 
- [FOUR-16725](https://processmaker.atlassian.net/browse/FOUR-16725)
ci:next
ci:deploy
[FOUR-16725]: https://processmaker.atlassian.net/browse/FOUR-16725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-16725:Variable task due date does not validate that value will be a mustache syntax

resources/js/components/shared/ellipsisMenuActions.js
1.Go to Process
3.Click on ellipsis
4.Select View Documentation
The documentation is not implemented.
It should redirect to the documentation for generation with AI
- Added code that detects if package-ai is installed. If so, the pacakge-ai documentaion UI is used.
Resolves:
- https://processmaker.atlassian.net/browse/FOUR-16877
- https://processmaker.atlassian.net/browse/FOUR-16878
ci:next
=> FOUR-16877: The "View documentation" option from the process list is not updated.

resources/js/processes-catalogue/components/ProcessOptions.vue, resources/js/processes-catalogue/components/scss/processes.css
- Process Info page was adjust to have figma design when screen is greater than 2560px width
- Go to Processes menu
- Click over some process
- Open browser dev tools (F12)
- Select Emulator for Mobile and select responsive mode. Set width with 2560px
- The right and left space between Carousel images should be added.
https://processmaker.atlassian.net/browse/FOUR-16891
ci:next
=> QA Observation Bugfix/FOUR-16891: Launchpad > Process Info does not have the same design when the screen size is greater than 2560px

resources/js/processes-catalogue/components/utils/Card.vue
https://processmaker.atlassian.net/browse/FOUR-17013
Icon for templates card does not have the correct size
Normal size is 40x48 
Mobile size is 24x24
ci:next
=> FOUR-17013 Icon for templates card does not have the correct size

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, tests/Feature/Api/ProcessRequestsTest.php
When we click on the cell that corresponds to the RPA in the process completed in FORMS, we get an error in the console.
- Records related to RPA were removed, specifically, any record that does not have an associated screen. This way, an empty record will not appear in the Forms tab.
https://github.com/user-attachments/assets/75f6f715-fb1d-40a1-83ed-d1a7c8aafc62
Follow the reproduction steps from the JIRA ticket.
- [FOUR-17089](https://processmaker.atlassian.net/browse/FOUR-17089)
ci:next
[FOUR-17089]: https://processmaker.atlassian.net/browse/FOUR-17089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17089: Errors appear in the console when we click on the RPA from Forms

resources/js/processes-catalogue/components/ProcessOptions.vue
- Chart section was fixed moviving below Details section when screen reaches 768px or less according mockup.
-Go to Processes
-Select some process
-Open process in a window with 653px like issue is reported by QA.
https://processmaker.atlassian.net/browse/FOUR-16889
ci:next
=> QA Observation Bugfix/FOUR-16889: launchpad > Process Chart is not in the correct site

resources/js/tasks/components/TasksList.vue
Hover options are not displayed in the empty column
added the option column if that column does not exists
Go to Tasks page
Hover in the row
Scroll right 
https://processmaker.atlassian.net/browse/FOUR-17156
ci:next
=> observation/FOUR-17156 Hover options are not displayed in the empty column

ProcessMaker/Models/ScriptDockerNayraTrait.php, config/app.php
When the executor is deployed the first time it can not connect to queue jobs.
- By default the value for "nayra_docker_network" is now "host".
- When try to get the IPs from the docker the command to use is different for "host" value
Create a script using executor "php-nayra"
https://processmaker.atlassian.net/browse/FOUR-17233
ci:next
ci:deploy
=> FOUR-17233 Nayra Executor can not connect in next-qa deployment

config/services.php
GITHUB_TOKEN is being set by docker to an empty string in QA environments. This should actually be its own variable scoped to the recommendations repository. 
- Change the env var name
- Set a RECOMMENDATIONS_GITHUB_TOKEN in your .env to a working github token
- run `php artisan optimize`
- run `php artisan processmaker:sync-recommendations`
- Should complete without errors
- https://processmaker.atlassian.net/browse/FOUR-17236
ci:next
=> Update env var name

ProcessMaker/Models/Process.php, database/migrations/2024_07_19_152418_add_updated_by_column_to_processes.php
To Implement FOUR-16695 it is necessary to track the last user that updated a process.
- Added a new column "updated_by" to the processes table
- https://processmaker.atlassian.net/browse/FOUR-16695
ci:next
=> FOUR-16695: "Updated" does not show the correct update in the documentation

resources/js/components/shared/PmqlInput.vue
Please see https://processmaker.atlassian.net/browse/FOUR-15004
To reproduce:
- Create a screen 
- Add an input with a default and name it **user** (you can use your custom example)
- Add a select list of type data connector (you can use the users endpoint)
- Configure Options Variable: response.data
- Type of Value Returned: Object
- Content {{data.username}}
- Data connector: Users
- Endpoint ListAll
- Add a PMQL: **data.username="{{user}}"** (user is the name of the input you added before)
- Go to preview and type some valid user in the input to make the pmql trigger and change the option list of the select
https://github.com/ProcessMaker/processmaker/assets/90727999/2fa1ce60-a5e5-44b8-9d45-4389aa603c6a
- Fix PMQL render and code refactor for dataconnector
- Fix issue …
=> Bugfix/FOUR-15004: PMQL in record list doesnt work with pm variables:

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/Process/ScreenController.php, resources/views/processes/screens/edit.blade.php
- Create a new screen.
- Add some elements to the screen 
- You can refresh your screen to validate that your changes are still there.
- Go to the screen configuration and change the name of the screen.
All the changes will be lost
The draft with the recent changes should still be there after renaming.
**Notes for QA:**
The information lost only occurs on unpublished versions. However, these changes exist in the version history as drafts before renaming the screen.
- When saving in configuration, now we get the last version of the screen and we update the BPMN.
- The button in configuration changed from **Save** to **Save and publish**
- If a draft exist for the screen, when clicking in Save and publish, we show a confirmation modal to let the …
=> Bugfix/FOUR-16548: Drafts being lost after renaming the screen

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/ProcessesCatalogue.vue, resources/js/processes-catalogue/components/utils/Card.vue, resources/js/processes-catalogue/components/utils/SearchCards.vue, resources/js/processes-catalogue/index.js
Some categories were not showing in the search results because we load them all at once (limit 100) and then filter only on those.
- Refactor to use backend filtering for categories.
- Have a category that does not show up in the initial list of 20 categories in launchpad
- Try to find that category using the search field
- https://processmaker.atlassian.net/browse/FOUR-16884
ci:next
=> FOUR-16884 Fix launchpad category filtering

resources/js/admin/settings/components/SettingSelect.vue, resources/js/admin/settings/components/SettingText.vue, resources/js/admin/settings/mixins/setting.js
This PR is part of https://github.com/ProcessMaker/package-rpa/pull/17
When clicking the button to delete a setting and then reopening the modal, the previous value is still visible.
- The proposed solution is to update the “transformed” value used in the v-model when the “value” prop changes.
- The remaining changes are eslint formatting adjustments.
1.	Go to settings and enter a value in a text input or select.
2.	Delete the value by clicking the trashcan button.
3.	Reopen the modal.
4.	There should be no value in the input or select.
- [FOUR-17133](https://processmaker.atlassian.net/browse/FOUR-17133)
- [RPA PR](https://github.com/ProcessMaker/package-rpa/pull/17)
ci:next
[FOUR-17133]: https://processmaker.atlassian.net/browse/FOUR-17133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> FOUR-17133: Clear out Folders When Other Configurations Are Deleted in Admin Settings

ProcessMaker/Http/Controllers/HomeController.php
This PR resolves an issue where users were redirected to the `/requests` page on mobile devices, even when a custom dashboard was assigned. The root cause was a conditional redirect specific to mobile devices. This update removes that conditional, allowing users to be redirected to their custom dashboard upon login, regardless of the device used.
Note: This change does not affect the redirect functionality when switching to the mobile version of the site.
- Removed the mobile redirect conditional that forced a redirect to `/requests`.
1. Assign a custom dashboard to a user.
2. On a mobile device, log in as the user.
3. Verify that you are redirected to the assigned custom dashboard.
4. Ensure that the redirect functionality works correctly when switching to the mobile version of the site, …
=> Develop: Resolve Mobile Redirect Issue for Custom Dashboard Assignment

ProcessMaker/ImportExport/Exporters/ProcessLaunchpadExporter.php
While working on FOUR-16302, I encountered an additional issue when importing the process referred to in the ticket. This issue was related to the ProcessLaunchpadExporter.
1. Import the Process within the [ticket](https://processmaker.atlassian.net/browse/FOUR-16302?focusedCommentId=409119).
2. Create a new Project
3. Add the imported Process to the Project.
4. See the error below
An error occurs when trying to add a Process that contains signals to a Project.
```
"ProcessMaker\\ImportExport\\Exporters\\ExporterBase::addDependent(): Argument #2 ($dependentModel) must be of type Illuminate\\Database\\Eloquent\\Model|ProcessMaker\\ImportExport\\Psudomodels\\Psudomodel, null given, called in /Users/estebangallego/www/processmaker/ProcessMaker/ImportExport/Exporters/ProcessLaunchpadExporter.p …
```
=> FOUR-16302: Resolve error with ProcessLaunchpadExporter

ProcessMaker/Models/Process.php
Assignment is only allowed to users with ACTIVE status when an assignment is a process variable.
- It is now allowed to assign users with the out_of_office status and assign them to the user that is available for delegation.
Steps in ticket.
- [FOUR-15164](https://processmaker.atlassian.net/browse/FOUR-15164)
[FOUR-15164]: https://processmaker.atlassian.net/browse/FOUR-15164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Process variable assignment not working when target user is set as out of office with delegation user configured

ProcessMaker/Models/User.php
When a user is deleted, his status is still set to 'ACTIVE'
Current behavior:
The user gets into the “deleted users” list, but remains active.
Expected behavior
The user gets into the “deleted users” list and is inactive.
- Added logic for setting a user status as INACTIVE when deleted and ACTIVE when restored.
- https://processmaker.atlassian.net/browse/FOUR-14051
ci:develop
=> FOUR-14051: When deleting users, they don't get inactivated (For develop branch)

ProcessMaker/Http/Controllers/TaskController.php, resources/js/tasks/components/QuickFillPreview.vue, resources/views/tasks/editQuickFill.blade.php, resources/views/tasks/preview.blade.php
- In Quickfill option, signatures will no longer be taken into account
- Have a process with Form with signature component
- Use Quickfill option with process has signatures into their Form
https://processmaker.atlassian.net/browse/FOUR-16559
ci:deploy
=> Bugfix/FOUR-16559: When I Quick-Fill a task, the signature is also filled and it is observed by the audit.

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/RecommendationEngine.php, tests/unit/ProcessMaker/RecommendationEngineTest.php
Recommendations are deleted when a user disables recommendations, however, they are not regenerated when the user enables recommendations.
- Trigger the generate recommendations job when the user enables recommendations
- Generate recommendations
- Disable recommendations in the user profile settings - the recommendations should no longer display on the tasks page
- Enable recommendations
- Wait a minute for the job to complete
- Ensure the recommendations are visible again on the tasks page
- https://processmaker.atlassian.net/browse/FOUR-17114
ci:next
=> FOUR-17114 Regenerate when the user enables recommendations

ProcessMaker/ApplyRecommendation.php, ProcessMaker/Events/TasksUpdated.php, resources/js/components/Recommendations.vue, resources/js/tasks/components/ListMixin.js, resources/lang/en.json, tests/unit/ProcessMaker/ApplyRecommendationTest.php
The users task list was not reloading when a recommendation was applied.
- Keep the modal open with a spinner to show the recommendation is working
- Send a websocket event to reload the users taks when it completes
Reassign or mark-as-priority any recommendation. Ensure the task list reloads when its finished.
- https://processmaker.atlassian.net/browse/FOUR-17113
ci:next
ci:deploy
=> FOUR-17113 Reload the users task lists when recommendation is applied

resources/views/tasks/edit.blade.php
The Case and Request section are displaying the process name twice
Show case title in the edit task case section
Run a Case
Open the Task
https://processmaker.atlassian.net/browse/FOUR-17168
ci:next
=> observation/FOUR-17168 Duplicated name when a Task is opened

resources/js/processes-catalogue/components/utils/Card.vue, resources/views/layouts/mobile.blade.php
Minimum with should be 360px for launchpad process list in mobile. When the screen is smaller than 360 the list should not condense and instead overflow off screen.
- Update CSS
- Login with a mobile device/emulator and switch to mobile view
- Go to the processes tab. Resize to less than 360px
- At 360px, the cards should not get smaller and start to overflow off screen
ci:next
=> Make minimum width 360px for mobile

resources/js/components/common/mixins/datatable.js
- Log in to PM4
- Go to Request or Task
- Open any saved search  in left menu
See the error attached in the ticket
- When is object return the values.
- [FOUR-16291](https://processmaker.atlassian.net/browse/FOUR-16291)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/6943)
- [Package savedsearch PR](https://github.com/ProcessMaker/package-savedsearch/pull/448)
- [Package Collections](https://github.com/ProcessMaker/package-collections/pull/388)
ci:package-savedsearch:bugfix/FOUR-16291
ci:package-collections:bugfix/FOUR-16291
ci:deploy
[FOUR-16291]: https://processmaker.atlassian.net/browse/FOUR-16291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-16291: Error in Saved search configuration 

resources/js/components/common/mixins/datatable.js
- Log in to PM4
- Go to Request or Task
- Open any saved search  in left menu
See the error attached in the ticket
- When is object return the values.
- [FOUR-16291](https://processmaker.atlassian.net/browse/FOUR-16291)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/7114)
- [Package savedsearch PR](https://github.com/ProcessMaker/package-savedsearch/pull/456)
- [Package Collections](https://github.com/ProcessMaker/package-collections/pull/390)
ci:package-savedsearch:bugfix/FOUR-16291-next
ci:package-collections:bugfix/FOUR-16291-next
ci:next
[FOUR-16291]: https://processmaker.atlassian.net/browse/FOUR-16291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-16291: Error in Saved search configuration

resources/views/processes/edit.blade.php
The buttons were placed outside a </div> close.
Also there is a problem when activating the configuration tab when the page is refreshed.
- Fix the position of buttons.
- Fix the activation rule of the Config tab.
- Open a process configuration
- Go to any tab, before the fix you will see a CANCEL and SAVE button in every tab
- With the fix the buttons are placed properly in the bottom of the config and not in every tab.
- Go to the Configuration tab
- Refresh the page 
- https://processmaker.atlassian.net/browse/FOUR-17003
ci:next
=> FOUR-17003 Fix position of buttons CANCEL and SAVE

resources/js/processes-catalogue/components/ProcessesCarousel.vue
- Arrow buttons are hidden by default and only when cursor Hover Carouse lmages, arrows are shown.
- Login to PM
- Go to processes and select some Process
- Hover on Carousel Images
https://processmaker.atlassian.net/browse/FOUR-17024
ci:next
=> QA Observation Bugfix/FOUR-17024: Launchpad > navigation arrow buttons are not interactive and not work on hover

resources/js/requests/components/RequestDetailMobile.vue, resources/views/requests/showMobile.blade.php
- Removing search and filters component from view
- Sending parameters to Tasks Card
- Login to PM in Mobile Mode
- Go to Cases Tab
- Select some case
- Below the screen, in Tasks Tab, none Search or Filter must be displayed
https://processmaker.atlassian.net/browse/FOUR-17196
ci:next
=> QA Observation bugfix/FOUR-17196: Mobile > Filters and search field are displayed inside Case Details

resources/js/components/templates/mixins/wizardHelperProcessModal.js
When navigating through the Guided Templates interface, closing the modal results in a 405 error.
1. Access the Process tab
2. Access the Guided Template Categorie
3. Select any Guided Template
4. Click on Start and start navigating the helper process
5. Attempt to close the Modal before ending the navigation
A 405 error is displayed when attempting to close the modal.
The modal should close without errors, and the interface should return to the previous state.
- Set processRequestId with the correct value when closing the Modal
Please follow the reproduction steps and make sure that nor errors are been display.
- Ticket [FOUR-17218](https://processmaker.atlassian.net/browse/FOUR-17218)
- ci:next
- ci:deploy
[FOUR-17218]: https://processmaker.atlassian.net/browse/FOUR-17218?atlOrigin=eyJpI …
=> FOUR-17218: Fix 405 error when closing the guided template model

resources/sass/_variables.scss
Launchpad change to mobile view when browser's screen is 640px
changed the mobile breakpoint to 640px
Go to processes page
change the browser’s screen size to 640px
https://processmaker.atlassian.net/browse/FOUR-16890
ci:next
=> observation/FOUR-16890 Launchpad change to mobile view when browser's screen is 640px

resources/js/components/shared/IconDropdown.vue
Launchpad icon field does not display correctly its label
- [FOUR-17244](https://processmaker.atlassian.net/browse/FOUR-17244)
ci:next
[FOUR-17244]: https://processmaker.atlassian.net/browse/FOUR-17244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17244:Launchpad icon field does not display correctly its label

resources/js/processes-catalogue/components/CreateSavedSearchTab.vue, resources/lang/en.json
- Correct name was assigned to Saved Search when name is invalid
- Go to processes
- Select any process
- Try to add a new saved search and sabe without a name (empty field)
https://processmaker.atlassian.net/browse/FOUR-17282
ci:next
=> QA Observation bugfix/FOUR-17282: Invalid message when saved search is created as a tab

ProcessMaker/Models/Setting.php
Define a value when the config is `Email Server 1, 2...`
1. Create a Email Server more than one
2. Update the settings.group_id = null (database)
3. Run the command
Execute this command `php artisan processmaker:update-settings-group-id`
- https://processmaker.atlassian.net/browse/FOUR-17008
=> FOUR-17008: [develop] Define a value when the config is Email Server 1, 2

ProcessMaker/Models/Setting.php
Define a value when the config is `Email Server 1, 2...`
- FOUR-17008
ci:next
=> FOUR-17008: [next] Define a value when the config is Email Server 1, 2

ProcessMaker/ImportExport/Exporters/GroupExporter.php
It is not possible to import a pm block
It should be possible to import a pm block 
- Add a validation for non-group permissions on import
https://github.com/user-attachments/assets/277e864a-ba2d-46eb-8b8d-67c59885f934
1. Create a pm block 
2. Export the pmblock 
3. Try to import the pmblock
[FOUR-16119](https://processmaker.atlassian.net/browse/FOUR-16119)
ci:next
[FOUR-16119]: https://processmaker.atlassian.net/browse/FOUR-16119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-16119 it is not possible to import pmblock

resources/js/admin/settings/components/SettingsListing.vue
- data-cy tag for CLEAR option was added (Edit and Copy already had)
- Login
- Go to Admin -> Settings -> Integrations
- Open DevTools and select some Trash Icon to confirm tag data-cy="clear-rpa.organization_name"
https://processmaker.atlassian.net/browse/FOUR-15496
ci:next
=> QA Observation Bugfix/FOUR-15496: Add attributes to edit, copy and delete options in RPA configurations

ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, ProcessMaker/Http/Resources/V1_1/TaskResource.php, resources/views/tasks/edit.blade.php
If we do not have interstitial enabled in the tasks, we should not jump to the next form
As we see, the tasks are shown alone without opening in the Form Task
- Validate interstitial on redirect to the next task
https://github.com/user-attachments/assets/81945b02-3a49-48ec-84d9-5468e0dc7a2d
1. Log in 
2. Create a process with a task 
3. Verify that the tasks and the start event are not configured with interstitial
4. Start a new  case
[FOUR-17160](https://processmaker.atlassian.net/browse/FOUR-17160)
[FOUR-17272](https://processmaker.atlassian.net/browse/FOUR-17272)
https://github.com/ProcessMaker/screen-builder/pull/1654
ci:next
ci:screen-builder:bugfix/FOUR-17272
[FOUR-17160]: https://processmaker.atlassian.net/browse/FOUR-17160?atlOrigin=eyJpIjoiNWR …
=> FOUR-17272 tasks in a process without interstitial automatically skip to the next task

ProcessMaker/Models/ProcessVersion.php
The SVG for process versions was being sent with the requests API results.
NOTE: Even after excluding the svg, [the change made here](https://github.com/ProcessMaker/processmaker/commit/ea1e35278aa923e915c4a23e0347a3074cd56c12#diff-3bee9c69cb7d9684799f1bb151bca48778a2a022d6a2f82abd8bf82e4b4a947cR171) more than doubles the payload size. I think we should only include process_versions when they are explicitly included in the `include` param.
- Exclude it by default
Look for a smaller payload when getting the requests from `api/1.0/requests`
- https://processmaker.atlassian.net/browse/FOUR-17264
ci:next
=> Exclude the svg field by default

database/migrations/2024_07_19_152418_add_updated_by_column_to_processes.php
1. Create a user (userA)
2. Create a Process with userA
3. Delete userA 
4. Run the ProcessMaker migration
- Now we check if the user exists, if not, the udpated_by column is set to null.
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-17313)
ci:next
=> FOUR-17313: When a user is removed from the database, the migration that created the "updated_by" column fails

resources/js/processes/modeler/components/ProcessMap.vue
RPA type tasks do not have target information in overview
1. Create a process with RPA 
2. Start a case  
3. Complete the process
4. Open in overview
5. Click on the RPA type task
- The tool-tip has been enabled for Service Task nodes, such as an RPA task. This allows the information to be viewed in the process map.
https://github.com/user-attachments/assets/186b5325-fd05-4850-8de5-f0e17e8932a4
Follow the reproduction steps of above.
- [FOUR-17270](https://processmaker.atlassian.net/browse/FOUR-17270)
ci:next
[FOUR-17270]: https://processmaker.atlassian.net/browse/FOUR-17270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17270: RPA type tasks do not have target information in overview

resources/js/components/shared/EllipsisMenu.vue, resources/js/processes/translations/components/ProcessTranslationListing.vue
The message "Translation in progress" is not displayed correctly
- [FOUR-17033](https://processmaker.atlassian.net/browse/FOUR-17033)
ci:next
[FOUR-17033]: https://processmaker.atlassian.net/browse/FOUR-17033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17033:The message "Translation in progress" is not displayed correctly

ProcessMaker/Models/Media.php
3. Add a task form
5. Open the task configurations
7. Upload an image in the task form 
9. Open console developer
13. It is not possible to upload image to slide show configuration in the modeler
- The file_name can not defined from FE
like steps
- [FOUR-17334](https://processmaker.atlassian.net/browse/FOUR-17334)
ci:next
[FOUR-17334]: https://processmaker.atlassian.net/browse/FOUR-17334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17334: 400 Error  in Upload image in slide show configuration

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Models/ProcessMakerModel.php, resources/views/tasks/edit.blade.php, sonar-project.properties, tests/Feature/Api/ScreenTest.php
When a webentry is opened, it does not count with request or task, this caused error in the Task component new changes. Also the screen kept disabled because of that.
Also there is a problem in the screens endpoint when selecting an screen.
- Fix the initialization of the Task considering it could not have a request
- Disable the screen at the begining only when a request is present
- Fix screen endpoint and add some tests to validate it.
https://github.com/user-attachments/assets/25661c71-5648-4dde-ba8c-9aa8e2ed7b5c
- Create a process with an anonnymous webentry
- Variations: With interstitial screen
- Variation: Without interstitial screen
- Open the web entry
- Complete the form
- https://processmaker.atlassian.net/browse/FOUR-17258
ci:next
ci:deploy
=> FOUR-17258 Fix Task Initialization in Webentries

ProcessMaker/Enums/ExporterMap.php
FlowGenie is not exported from the project
- add asset flowGenie
Export/import Project with asset FlowGenie
- [FOUR-17426](https://processmaker.atlassian.net/browse/FOUR-17426)
Related PR
- https://github.com/ProcessMaker/package-projects/pull/133
- https://github.com/ProcessMaker/package-ai/pull/275
ci:next
ci:package-project:bugfix/FOUR-17426
ci:package-ai:bugfix/FOUR-17426
[FOUR-17426]: https://processmaker.atlassian.net/browse/FOUR-17426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> When I import an exported project that contains flow genie, the flow genies are not imported

ProcessMaker/Http/Controllers/Api/WizardTemplateController.php, resources/js/processes-catalogue/components/WizardTemplates.vue
Optimize initial Launchpad generation time
removed double api call and unnecessary join
https://processmaker.atlassian.net/browse/FOUR-15427
ci:next
=> observation/FOUR-15427 Optimize initial Launchpad generation time

resources/sass/_variables.scss
Launchpad change to mobile view when browser's screen is 640px
changed the mobile breakpoint to 640px
Go to processes page
change the browser’s screen size to 640px
https://processmaker.atlassian.net/browse/FOUR-16890
ci:next
=> observation/FOUR-16890-2 Launchpad change to mobile view when browser's screen is 640px

resources/views/processes/modeler/index.blade.php
The links are not blue color in Processmaker
- [FOUR-17380](https://processmaker.atlassian.net/browse/FOUR-17380)
ci:next
[FOUR-17380]: https://processmaker.atlassian.net/browse/FOUR-17380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17380:The links are not blue color in Processmaker

resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Mobile Launchpad > A space is covering the card list
Fixed the processes info style in the mobile view
Login mobile version
Press processes tab
Search and open a process
Press My Cases or My tasks tab
Scroll down
https://processmaker.atlassian.net/browse/FOUR-17341
ci:next
=> observation/FOUR-17341 Mobile Launchpad > A space is covering the card list

ProcessMaker/Providers/AuthServiceProvider.php
This PR refactors the existence check from a database table (projects) to a package (package-projects). This change is to improve performance issues. 
- Replaced Schema::hasTable('projects') with hasPackage('package-projects') to determine if the package exists.
- [FOUR-17455](https://processmaker.atlassian.net/browse/FOUR-17455)
ci:next
ci:deploy
[FOUR-17455]: https://processmaker.atlassian.net/browse/FOUR-17455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor Table Existence Check to Package Existence Check

resources/js/processes/designer/ProjectsLastModifiedListing.vue
Actual behavior: Ellipsis inside a project is too far from the edge of the screen
- Ellipsis was adjusted to fit correctly in Projects Section
NOTE: This fix is related with package-projects changes
- Login PM as Admin
- Review ellipsis My Projects section
- Click on some project abd review ellipsis
- https://processmaker.atlassian.net/browse/FOUR-17413
ci:next
=> QA Observation bugfix/FOUR-17413: Ellipsis inside a project is too far from the edge of the screen

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, resources/js/processes/modeler/components/ProcessMap.vue, resources/js/processes/modeler/components/ProcessMapTooltip.vue, tests/Feature/Api/ProcessRequestsTest.php
1. Go to the Overview tab of a process.
2. Select a sequence flow or a task and mark it as highlighted (try dragging it).
3. Click on another task.
You will notice that the tooltip of the last task does not open and you have to double-click to display it. This behavior is unusual.
- You should be able to click between tasks and sequence flows without any issues and view the tooltip without bugs.
- The solution was to add a next tick in the modeler to ensure that the correct highlighted node is emitted.
- The changes in the core are just a small refactor to improve the readability and maintainability of the component.
https://github.com/user-attachments/assets/77c9e11d-020e-4951-9f05-06b39be94163
- Perform the reproduction steps of above.
- …
=> FOUR-16868: Inflight view process: when the lane is selected the user can not select any task

ProcessMaker/Jobs/ImportProcess.php, ProcessMaker/Jobs/ImportScreen.php, database/migrations/2024_07_30_120225_modify_watchers_column_in_screens_table.php
Server error when saving a screen with too many watchers and too many resources in data connectors
- Add a migration to change the `watchers` column type in `screens` and `screen_versions` tables
- Handle exceptions in the import screen
1. Have/Create a Data Connector that has many endpoints
2. Create a screen 
3. Add many watchers to the screen using the Data Connector 
4. At the moment we continue adding watchers, at some point, we receive a Server error
[FOUR-16179](https://processmaker.atlassian.net/browse/FOUR-16179)
ci:next
[FOUR-16179]: https://processmaker.atlassian.net/browse/FOUR-16179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-16179 server error when saving a screen with too many watchers and too many resources in data connectors

resources/js/processes-catalogue/components/Process.vue
The option menu, rises to the top when we edit the lounchpad
fixed dropdown menu
Log in
Have a process created
Click on Processes menu 
Search the process 
Open whit  lounchpad 
Click on Options
Click on Edit  Lounchpad 
Edit the  screen lounch pad 
Save 
Clik on Porcesses  again
Click on options menu by process
https://processmaker.atlassian.net/browse/FOUR-17475
ci:next
=> observation/FOUR-17475 The option menu, rises to the top when we edit the lounchpad§

ProcessMaker/Filters/Filter.php
The advance filter is case-sensitive even when the operator is “contains“
When the "where" section is builded forJSON data, for "like" operator we're casting the value to CHAR in order to make the comparison insensitive.
Create a Saved Search and include a custom column that uses a process request variable set a filter by using the three “dots” button with “contains” as the operator.
https://processmaker.atlassian.net/browse/FOUR-16901
ci:next
=> FOUR-16901 Advanced filters on saved search columns are case-sensitive

ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, resources/js/components/templates/TemplateSearch.vue, resources/js/components/templates/WizardTemplateDetails.vue
Guided template direct links not working
added  template id and guided_template params to the new guided templates URL
copy the link /process-browser/?categoryId=guided_templates&guided_templates=true&template=nonpo_invoice_approval
https://processmaker.atlassian.net/browse/FOUR-17364
ci:next
ci:deploy
=> observation/FOUR-17364 added  template id and guided_template params to the url

resources/js/Mobile/Card.vue, resources/js/requests/components/MobileRequests.vue, resources/js/tasks/components/MobileTasks.vue
Tasks and Cases are not the same between mobile and desktop views
ix the tasks and cases data format after applying a filter in the mobile view
Log in
Create a USER_A
Create a simple process (start event - task -task - end event)
Assign all Tasks to USER_A
Start some Cases  from ADMIN USER
logout
login with USER_A from mobile view
Open some cases and sent to next task
Go to Tasks tab
Go to Cases tab
https://processmaker.atlassian.net/browse/FOUR-17495
ci:next
=> observation/FOUR-17495 Tasks and Cases are not the same between mobile and desktop views

resources/js/notifications/components/NotificationsList.vue
We see that it shows us a canceled message, wanting to sort the notification columns
- https://processmaker.atlassian.net/browse/FOUR-17027
ci:deploy
ci:next
=> feature/FOUR-17027: A "cancelled" error is displayed when clicking on the ascending and descending options in notifications

resources/js/components/shared/EllipsisMenu.vue, resources/js/components/shared/FilterTable.vue
- Ellipsis button fits the screen based on window size
-Login PM as admin
-Go to Designer->All processes
-Click on Ellipsis button and dropdown Processes list scrollbar
-Ellipsis option list should have scrollbar
https://processmaker.atlassian.net/browse/FOUR-17507
ci:next
=> QA Observation bugfix/FOUR-17507: The ellipsis options in processes are not responsive.

resources/js/processes-catalogue/components/CardProcess.vue
- Some media queries were added with new range of screen dimensions
- Login PM
- Collapse left side bar and navigate
- Separator and cards should fix correctly in the screen
https://processmaker.atlassian.net/browse/FOUR-16886
ci:next
ci:deploy
=> QA Observation bugfix/FOUR-16886-b : Launchpad > pagination in the infinite scroll does not cover all screen width 

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/CatalogueEmpty.vue, resources/js/processes-catalogue/components/ProcessListing.vue, resources/js/processes-catalogue/components/menuCatologue.vue
**Steps to reproduced:**
- Create a userA without permissions
- Log In with userA
- Click on processes
- Click on My bookmarks
- Click on "Show me My templates"
- Added a emit to trigger the correct redirect
https://github.com/user-attachments/assets/1a834d66-555b-4d3e-afa7-4a30e638c5d9
- https://processmaker.atlassian.net/browse/FOUR-17565
ci:next
=> Observation/FOUR-17565: "Show me My templates" button does not work in process-browser for a user without permissions

ProcessMaker/Filters/Filter.php, ProcessMaker/Models/ProcessRequest.php, resources/js/common/PMColumnFilterPopoverCommonMixin.js, resources/js/requests/components/RequestsListing.vue
There should be no errors when filtering by the alternative column, after creating a Saved Search
It shows us a server error when trying to filter by the alternative column in a Saved Search
- Add filtering support for process alternative column
- Convert the alternative filter into a select
https://github.com/user-attachments/assets/ca4b63b6-4786-4879-b402-bb6ed73113aa
1. Log in 
2. Create a new Saved Search 
3. The alternative column is enabled
4. Filter by the alternative column
[FOUR-17524](https://processmaker.atlassian.net/browse/FOUR-17524)
https://github.com/ProcessMaker/package-savedsearch/pull/463
ci:next
ci:package-savedsearch:bugfix/FOUR-17524
ci:deploy
[FOUR-17524]: https://processmaker.atlassian.net/browse/FOUR-17524?atlOrigin=eyJpIjoiNWR …
=> FOUR-17524 server error when i want to filter by alternative column

resources/js/components/shared/ellipsisMenuActions.js
A process can be exported as XML even when only view permissions are set.
- Go to the **Admin** tab.
- Create a Test User.
- Navigate to **Groups**.
- Create a new group.
- Set up the group with only View permissions.
- Add the Test User to the new group
- Log in as the Test User.
- Go to the **Designer** tab.
- Navigate to **Processes**.
- Select any process.
- Click on the Ellipsis menu **Options**.
- Select **Download BPMN**.
- ![Screenshot 2024-08-02 at 3 41 51 PM](https://github.com/user-attachments/assets/08c4e1d4-fe13-4b7a-9edf-1cf9e67d4dd2)
- The BPMN file can be downloaded even though the user’s group has only View permissions.
- The Export BPMN button is accessible within the Ellipsis Menu.
- The BPMN button should not be visible if the user or group is not configured with the …
=> FOUR-16620: Adjust permissions of export-processes within the  Ellipsis menu

ProcessMaker/ImportExport/Exporters/ExporterBase.php, ProcessMaker/ImportExport/Exporters/MediaExporter.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, ProcessMaker/ImportExport/Psudomodels/Psudomodel.php, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php
The importer automatically increments the process_id of ProcessLaunchpad because it must be unique. But the new ID was not seen by the import logic that happens later so it was attempting to save using the old (non-unique) id.
- Run refresh() on the model before running the import logic.
See steps in jira issue
- https://processmaker.atlassian.net/browse/FOUR-16751
ci:next
.
=> Fix PM blocks launchpad import issue

resources/js/admin/users/components/SecurityLogsListing.vue
- Go to Security logs tab, and search with any critera.
https://processmaker.atlassian.net/browse/FOUR-17562
ci:next
=> QA Observation Bugfix/FOUR-17562: A `Server error` message when a criteria is added in the search field in the Security Logs tab

ProcessMaker/Http/Controllers/Process/ScriptController.php, ProcessMaker/Models/Script.php, ProcessMaker/Models/ScriptExecutor.php, resources/views/processes/scripts/edit.blade.php
When an script task was created with php language, then it cannot be changed to use php-nayra to improve its performance. This is because the Script Configuration screen does not allow to change to other language. We need to allow change php ↔︎ php-nayra for any case.
Added "php-nayra" in the dropdpwn when a script configuration is edited
Create a Scrip Task PHP Executor
Save it
Go to scripts lists
Edit the Configuration of the created script
Try to change the executor to PHP-NAYRA
https://processmaker.atlassian.net/browse/FOUR-17531
ci:next
.
=> FOUR-17531 Can not change Scripts with PHP to PHP-NAYRA

ProcessMaker/Http/Controllers/Process/ModelerController.php
PM Blocks are not visible in slide show preview mode
- [FOUR-17543](https://processmaker.atlassian.net/browse/FOUR-17543)
ci:deploy
ci:next
ci:package-slideshow:bugfix/FOUR-17543
[FOUR-17543]: https://processmaker.atlassian.net/browse/FOUR-17543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17543:PM Blocks are not visible in slide show preview mode

resources/js/components/shared/FilterTable.vue
The Home My Cases - The ellipisis is not showed.
- [FOUR-17354](https://processmaker.atlassian.net/browse/FOUR-17354)
ci:next
ci:screen-builder:bugfix/FOUR-17354
[FOUR-17354]: https://processmaker.atlassian.net/browse/FOUR-17354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17354:The Home My Cases - The ellipisis is not showed

resources/js/processes-catalogue/components/CreateSavedSearchTab.vue, resources/js/processes-catalogue/components/ProcessTab.vue
Launchpad > Added Saved Search is not working correctly.
- The rows in the new tab should be displayed according to filters.
Please, it is important to edit or add new saved searches in the tabs of the Launchpad to see the effects.
- https://processmaker.atlassian.net/browse/FOUR-17648
ci:next
=> FOUR-17648 Launchpad > Added Saved Search is not working correctly

ProcessMaker/Http/Middleware/SessionControlBlock.php, ProcessMaker/Listeners/UserSession.php, ProcessMaker/Managers/SessionControlManager.php
When users SAML to log-in they and PM has configured the setting "Device Restriction", this setting is not working. Users can log-in from multiple devices.
Log in
Configure  Sesiin control with Bock duplciate session
Login with other borwser with  saml user
- Added to Package-Auth the logic to control session by devices
- Refactored in PM core the code that controls the session policies so that the same logic can be used in package-auth.
Log in
Configure  Sesiin control with Bock duplciate session
Login with other borwser with  saml user
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-17626)
ci:package-auth:observation/FOUR-17626
ci:next
=> FOUR-17626: block duplicate session does not work with saml user

ProcessMaker/Console/Commands/UnlockExecutorBuilder.php, ProcessMaker/Jobs/BuildScriptExecutor.php
- Set an expire timeout for the job lock.
- Improve the lock logic of the job
- Add an artisan command to manually unlock the executor builder
If there is a lock of the Executor builder you can run the command:
```
php artisan processmaker:unlock-executor-builder
```
- https://processmaker.atlassian.net/browse/FOUR-17298
ci:next
.
=> FOUR-17298 Artisan command to unlock Executor Builder

resources/views/processes/modeler/index.blade.php
The Sidebar icons and text are not displaying with the correct color when navigating to the Designer/Modeler, causing them to be invisible.
- Navigate to the Designer.
- Open any Process.
- Click on "Expand Sidebar."
- ![Screenshot 2024-08-14 at 2 46 54 PM](https://github.com/user-attachments/assets/149b3462-2d44-45e3-b545-4e8ed0e13ef6)
The Sidebar icons and text should be properly displayed and visible when accessed from the Modeler.
- Remove the !important of the links within the modeler file
Please follow the reproduction steps and make sure that the Expected behavior is met.
- Ticket: [FOUR-17867](https://processmaker.atlassian.net/browse/FOUR-17867)
- ci:next
[FOUR-17867]: https://processmaker.atlassian.net/browse/FOUR-17867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> FOUR-17867: Fix issue with the Sidebar not showing the proper color within the icons and text

resources/views/tasks/edit.blade.php
When Task Source (default) is selected, the Task should be opened and displayed on the screen with the Claim message
The next task is not displayed and a loop displays the completed task message 
- Add a session variable to identify when a Task has been claimed
https://github.com/user-attachments/assets/96ae4684-0308-4f8d-baf7-77814deb1a5f
See the ticket
[FOUR-17911](https://processmaker.atlassian.net/browse/FOUR-17911)
https://github.com/ProcessMaker/screen-builder/pull/1671
ci:next
ci:screen-builder:bugfix/FOUR-17911
[FOUR-17911]: https://processmaker.atlassian.net/browse/FOUR-17911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-17911 loop created between two tasks with self service

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/utils/Card.vue
Launchpad Mobile > Process Name is not truncated
Added a text-overflow style for the process title in the mobile view
Go to server
Create a simple process with a long name
Login (mobile view)
Press to Processes tab
Search and open the process
https://processmaker.atlassian.net/browse/FOUR-17889
ci:next
=> observation/FOUR-17889 Launchpad Mobile Process Name is not truncated

resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue
Verify that truncated text is displayed
25 characters limit, only one line of text for starting event, after that, is truncated with three dots (...)
show the complete text in a tooltip
25 characters limit, only one line of text for starting event, after that, is truncated with three dots (...)
show the complete text in a tooltip
https://processmaker.atlassian.net/browse/FOUR-17021
ci:next
=> FOUR-17021-A Verify that truncated text is displayed

resources/js/processes-catalogue/components/ProcessInfo.vue
Launchpad change to mobile view when browser's screen is 640px
changed the mobile breakpoint to 640px
Go to processes page
change the browser’s screen size to 640px
https://processmaker.atlassian.net/browse/FOUR-16890
ci:next
=> observation/FOUR-16890-3 Launchpad change to mobile view when browser's screen is 640px

resources/js/processes-catalogue/components/optionsMenu/ProcessCounter.vue
Launchpad > Metrics are having different values when process info is collapsed
Fix the collapse process info values
Go to server
login with a user
Go to process-browser page
Search and open a process
Check the metrics
Collapse process info
https://processmaker.atlassian.net/browse/FOUR-17985
ci:next
=> observation/FOUR-17985 Launchpad > Metrics are having different values when process info is collapsed

resources/js/processes-catalogue/components/ProcessTab.vue
Make Tasks the first tab and show it opened in the Launchpad
changed the order of the tabs
Open a Launchpad.
Find the My Tasks section in the first tab
My Cases should go after the My Tasks tab
https://processmaker.atlassian.net/browse/FOUR-18176
ci:next
=> observation/FOUR-18176 Make Tasks the first tab and show it opened in the Launchpad

ProcessMaker/Events/RedirectToEvent.php, ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Jobs/BpmnAction.php, ProcessMaker/Listeners/HandleActivityAssignedInterstitialRedirect.php, ProcessMaker/Listeners/HandleActivityCompletedRedirect.php, ProcessMaker/Listeners/HandleEndEventRedirect.php, ProcessMaker/Listeners/HandleRedirectListener.php, ProcessMaker/Providers/EventServiceProvider.php, resources/views/tasks/edit.blade.php
Fix Processes that are started with another thread do not display the screen
- Use an specific event to handle the redirection.
Review the steps in ticket: https://processmaker.atlassian.net/browse/FOUR-17581
- https://processmaker.atlassian.net/browse/FOUR-17581
ci:next
ci:screen-builder:bugfix/FOUR-17581b
=> FOUR-17581 Fix Processes that are started with another thread do not display the screen

ProcessMaker/ImportExport/Exporters/EnvironmentVariableExporter.php, ProcessMaker/Models/ScriptDockerNayraTrait.php, ProcessMaker/Nayra/Managers/WorkflowManagerRabbitMq.php, ProcessMaker/ScriptRunners/Base.php, tests/Feature/ImportExport/Exporters/ScriptExporterTest.php
The nayra executor fails to run when exists env variables with spaces.
- Replace space by undescore before to send the env variables to the executor
- Fix the ImportExport class for EnvVariables to use "_" instead of " "
- Add a test to validate the solution
- Export a process with a script task that use environment variables
- Import it to the same server
- Choose the option as a copy
- https://processmaker.atlassian.net/browse/FOUR-17836
ci:next
=> FOUR-17836 Fix error executing script with env variables with spaces

ProcessMaker/Events/ProcessCompleted.php
This PR introduces a temporary solution to address the redirect issue when a guided helper process is completed. The issue arises from the Element Destination configuration, which incorrectly redirects the user to the Summary page instead of the desired launchpad location. The solution involves differentiating the behavior for guided helper processes and redirecting the user to the Launchpad of the newly created process.
- Temporary Redirect Fix
- Implement a conditional check for `processRequest->process->asset_type` to determine if the `asset_type` is `GUIDED_HELPER_PROCESS`
- If the `asset_type` is not `GUIDED_HELPER_PROCESS` , the existing endEvent destination logic is executed.
- If the `asset_type` is `GUIDED_HELPER_PROCESS` ,  the logic to import the process template and redirect …
=> Temporary Fix for Redirecting After Completion of Guided Helper Processes

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/ImportExport/Exporters/ScreenExporter.php, ProcessMaker/Jobs/SyncGuidedTemplates.php, resources/js/processes/modeler/components/inspector/ScreenSelect.vue, upgrades/2024_08_26_205409_remove_interstitial_keys.php
See issue https://processmaker.atlassian.net/browse/FOUR-18820
- Remove 'interstitial' key when importing and cloning
- Add an upgrade script to clear all other 'interstitial' keys
See issue
- https://processmaker.atlassian.net/browse/FOUR-18820
ci:next
=> Remove and prevent duplicate default interstitials

ProcessMaker/Listeners/HandleActivityAssignedInterstitialRedirect.php
The redirect to next task was working only with interstitial enabled
This PR is required by: https://github.com/ProcessMaker/screen-builder/pull/1678
- Enable redirect to next task when the next assigned user is the same of the current task as defined in the PRD
- https://processmaker.atlassian.net/browse/FOUR-18860
ci:next
=> FOUR-18860 Fix User completes a task and is assigned the next one is not redirected to form the next task

ProcessMaker/ImportExport/Exporters/ProcessExporter.php
The element destination configuration with a custom dashboard is not imported
Element destination field contains `Task Source(Default)`
Element destination field should contain `Custom Dashboard`
- Remove the htmlspecialchars fn from the elementDestination data due to the DB encoding
https://github.com/user-attachments/assets/99a8481f-5daf-403f-a509-75e0a7cbd8f9
see the ticket
[FOUR-18163](https://processmaker.atlassian.net/browse/FOUR-18163)
ci:next
[FOUR-18163]: https://processmaker.atlassian.net/browse/FOUR-18163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-18163 the element destination configuration with custom dashboard is not imported

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Traits/TaskControllerIndexMethods.php, storage/api-docs/api-docs.json, tests/Feature/Api/TasksTest.php
See https://processmaker.atlassian.net/browse/FOUR-18842
Return all tasks types by adding all_tasks=true, for example
`/api/1.0/tasks?pmql=process_request_id%20%3D%202&all_tasks=true`
ci:next
=> Add all_tasks property to tasks endpoint

resources/js/tasks/components/TaskSaveNotification.vue, resources/js/tasks/show.js, resources/views/tasks/edit.blade.php
Add the component auto save instead the notification in Web
- https://processmaker.atlassian.net/browse/FOUR-18184
ci:deploy
ci:next
=> FOUR-18184:Add the component auto save instead the notification in Web

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, resources/lang/en.json
1. Login and visit the next URL file-manager/public.
2. Upload the next PDF file
[pdfgarlito.pdf](https://github.com/user-attachments/files/16849360/pdfgarlito.pdf)
3. Open the uploaded file and press over the direct link of the file:
When opening the file a JavaScript alert will be displayed
PDF files with dangerous content should be controlled.
- File upload endpoint (in PM Core) now validates if a PDF file has JavaScript included
- file-upload component in Screen Builder now adds file upload error handling
- When the file upload of a PDF file fails, a message is displayed.
Use the reproduction steps
Ticket: https://processmaker.atlassian.net/browse/FOUR-16700
PRs …
=> FOUR-16700: XSS via PDF File Upload (for 4.10.2)

resources/js/processes/screen-builder/screen.vue
This PR adds a 'Templates' button to the navigation menu within the screen builder. It updates the existing options array in screen.vue to accommodate the new button.
- Updated the `options` array in `screen.vue` to include a new 'Templates' button in the screen builder navigation menu.
1. Navigate to the screen builder in the application.
2. Ensure the 'Templates' button is now present in the screen builder navigation menu.
[FOUR-18284](https://processmaker.atlassian.net/browse/FOUR-18284)
ci:next
[FOUR-18284]: https://processmaker.atlassian.net/browse/FOUR-18284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add 'Templates' Button to Screen Builder Navigation Menu

resources/js/processes/screen-builder/screen.vue
This PR adds a new section in the screen builder that dynamically populates with templates when the 'Templates' button is selected. It fetches both user-specific and shared templates via API calls and displays the results in the right panel of the screen builder.
- Implemented API calls to retrieve both "My Templates" and "Shared Templates" data from the backend.
- Added a new section in the right panel of the screen builder to display the retrieved templates when the 'Templates' button is clicked.
1. Navigate to the screen builder interface.
2. In the screen builder navigation menu, click the 'Templates' button to trigger the template loading process.
3. Ensure that API calls are made to fetch "My Templates" and "Shared Templates" correctly.
4. Once the templates are retrieved, confirm …
=> Add Screen Templates Section in Screen Builder

resources/js/processes/import/components/ImportPIModal.vue, resources/lang/en.json
- https://processmaker.atlassian.net/browse/FOUR-18763
- Added new route on api.php for importing PI Processes
- Added new method on PackageAiController to send the pseudocode to the microservice
- https://github.com/ProcessMaker/package-ai/pull/292
ci:next
=> FOUR-18763: Implemented BE for PI Process import

resources/lang/de.json
Wrong german label for Elementziel
- Fix the label.
1. With a user with German language
2. Open a process in modeler
3. Select a Task or End Event
4. Note the Elementziel has a sign „
5. 
- https://processmaker.atlassian.net/browse/FOUR-18876
ci:next
=> FOUR-18876 Fix Wrong german label for Elementziel

database/seeders/PermissionSeeder.php
FOUR-18973: Create a new Permission “View All Cases”, this should be disable as default.
- https://processmaker.atlassian.net/browse/FOUR-18977
ci:deploy
ci:next
=> feature/FOUR-18977: Create a new Permission “View All Cases”, this should be disable as default

ProcessMaker/Traits/ForUserScope.php
The query could be found when using the '/requests' endpoint, and the user is a non-admin user and also has selfservice assignments.
It could be found that several subqueries are performed to verify the user's data, such as:
- the user has participated
- the user has selfServiceTask (users and groups)
- the user can edit (EDIT_DATA)
This query is time-consuming the more information is in the process_request_tokens table.
- The change is to remove the subqueries and execute them in different queries than the original.
It is a difficult environment to test, you need to have a large database and a user who presents the slowness problem. (preferably a client database)
Perform searches in the requests.
- [FOUR-18182](https://processmaker.atlassian.net/browse/FOUR-18182)
ci:next
[FOUR-18182]: …
=> Query too slow, when using request endpoint

ProcessMaker/Http/Controllers/TaskController.php, ProcessMaker/Models/TaskDraft.php, resources/views/tasks/edit.blade.php
The Auto save date is updated without making any changes
- Send the updated_at field to view, by default this field it was empty
- [FOUR-18903](https://processmaker.atlassian.net/browse/FOUR-18903)
ci:next
[FOUR-18903]: https://processmaker.atlassian.net/browse/FOUR-18903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-18903: The Auto save date is updated without making any changes

config/l5-swagger.php
Currently by default swaggers is accessible without a valid session.
- Add an environment variable to require a valid login to use and access swagger routes (docs and api) assets and oauth_callback must be public.
https://github.com/user-attachments/assets/5be84705-9e27-45a1-8be9-c035ca545c04
Configure the env variable:
```
SWAGGER_AUTH_REQUIRED=true
```
- https://processmaker.atlassian.net/browse/FOUR-18004
ci:next
=> FOUR-18004 Add a env variable SWAGGER_AUTH_REQUIRED to enable the auth for swagger routes

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php, resources/lang/en.json
1. Login and visit the next URL file-manager/public.
2. Upload the next PDF file
[pdfgarlito.pdf](https://github.com/user-attachments/files/16849360/pdfgarlito.pdf)
3. Open the uploaded file and press over the direct link of the file:
When opening the file a JavaScript alert will be displayed
PDF files with dangerous content should be controlled.
- File upload endpoint (in PM Core) now validates if a PDF file has JavaScript included
- file-upload component in Screen Builder now adds file upload error handling
- When the file upload of a PDF file fails, a message is displayed.
Use the reproduction steps
Ticket: https://processmaker.atlassian.net/browse/FOUR-16700
PRs
Screen Builder - …
=> FOUR-16700: XSS via PDF File Upload

ProcessMaker/ScriptRunners/Base.php
$_SERVER['HOST_URL'] in being encoded incorrectly for nayara executor.
- Fix the encoding of the variable
Run a Script Task (php-nayra)
```
<?php
return [
'host' => $_SERVER['HOST_URL'], 
];
```
This must return
```
{
"output": {
"host": "https://server.location.without.single.quotes"
}
}
```
- https://processmaker.atlassian.net/browse/FOUR-18920
ci:next
=> FOUR-18920 Fix environment variable encoding for nayra executor

ProcessMaker/Listeners/HandleActivityCompletedRedirect.php
Redirect to Summary Screen from End Event with Multiple Tasks Parallel Assigned
Task TCP4-4247-A completed should redirect to Task List
Task TCP4-4247-B completed should redirect to Welcome Screen
Task TCP4-4247-C completed should redirect to Summary Screen
Task TCP4-4247-A completed is not redirected according to the Element Destination configuration
Task TCP4-4247-B completed is not redirected according to the Element Destination configuration 
- Verify if the request is active once the parallel task is completed
https://github.com/user-attachments/assets/38663ece-3443-42d6-b47f-20e777153329
see the ticket
[FOUR-18984](https://processmaker.atlassian.net/browse/FOUR-18984)
https://github.com/ProcessMaker/screen-builder/pull/1689
ci:next …
=> FOUR-18984 Parallel Task is not redirected according element destination configuration once completed

ProcessMaker/Console/Commands/BuildScriptExecutors.php, ProcessMaker/Models/ScriptExecutor.php, ProcessMaker/ScriptRunners/Base.php, config/script-runners.php, tests/ScriptExecutors/BuildScriptExecutorsTest.php
The executor builder were installing the composer librearies to the app folder instead to the executor folder.
- Configure properly the paths when building the executor.
- Add some composer libraries like:
```
RUN composer require clegginabox/pdf-merger:dev-master
RUN composer require setasign/fpdf
RUN composer require setasign/fpdi
RUN composer require setasign/fpdi-fpdf &&\
apt-get update && \
apt-get install -y \
libzip-dev \
&& docker-php-ext-install zip
```
- Rebuild the nayra executor.
- https://processmaker.atlassian.net/browse/FOUR-19081
ci:next
=> FOUR-19081 Fix default paths for nayra docker container

ProcessMaker/Models/ScriptDockerBindingFilesTrait.php, upgrades/2024_08_26_220829_remove_old_script_files.php
This cause the disk get filled during the time and when there are lots of scripts failing.
- Remove the temporal fails even if script task fails, since the log and data is available in the DB
- Remove old temporal files
- Update the environment (php artisan upgrade).
- Check that the `config('app.processmaker_scripts_home')` folder is empty unless it have pending script for a window of 1 hour.
- Run an script with an exception. e.g.
```
<?php 
sleep(5);
throw new Exception("!!");
return [];
```
- Check that the `config('app.processmaker_scripts_home')` folder is empty
- https://processmaker.atlassian.net/browse/FOUR-17278
ci:next
=> FOUR-17278 Remove temporal files from failing script tasks

resources/js/components/shared/ellipsisMenuActions.js
FOUR-18152 Change permissions of ellipsis documentation option (considering the permissions in case of ai documentation)
- https://processmaker.atlassian.net/browse/FOUR-18241
ci:deploy
ci:next
=> feature/FOUR-18241: Change permissions of ellipsis documentation option

ProcessMaker/Http/Resources/V1_1/TaskResource.php
The new task resource only had some user attributes returned with the magic `_user` variable.
- Add most user attributes back to the task resource to match the previous resource
See jira issues
- https://processmaker.atlassian.net/browse/FOUR-19027
ci:next
=> Add missing user attributes

ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, routes/api.php
- When the process run, it ends before the request page is loaded
- The page missed all the redirection events so it stays in white
- Catch when the process ends during the Task component mounting and execute the end event redirection.
- Requires: Screen Builder: https://github.com/ProcessMaker/screen-builder/pull/1699
- Run the processes described in the ticket
- The script could something like:
```
<?php
return [];
```
- Usa nayra executor (runs a bit faster that php executor)
- https://processmaker.atlassian.net/browse/FOUR-19102
ci:next
ci:connector-idp:bugfix/FOUR-19124
=> FOUR-19102 Fix Redirect when the process ends before load the request

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Jobs/BpmnAction.php
- Redirect event were sent twisse in next-qa
- package-advanced-manager-user were affecting the redirect to when assignment event is triggered
- Fix when the Redirect must be triggered.
Run the process described in the ticket.
- https://processmaker.atlassian.net/browse/FOUR-19115
ci:next
ci:connector-idp:bugfix/FOUR-19124
=> FOUR-19115 Fix when the Redirect must be triggered

ProcessMaker/Models/ProcessRequestToken.php
1.	Start the import process for a Guided Template (e.g., Expense Report).
2.	Complete the required steps.
3.	Observe the redirect after the import is completed.
- Set elementDestination to null for taskSource case at ProcessMaker/Models/ProcessRequestToken.php
Follow the reproduction steps.
- [FOUR-19210](https://processmaker.atlassian.net/browse/FOUR-19210)
ci:next
ci:deploy
[FOUR-19210]: https://processmaker.atlassian.net/browse/FOUR-19210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19210: Error when Importing Guided Template

ProcessMaker/Managers/PackageManager.php
- https://processmaker.atlassian.net/browse/FOUR-18687
- Added `deleteLanguageFile` function to delete a language file from all currently installed packages
- https://github.com/ProcessMaker/package-translations/pull/97
Use this URL on Postman to test: (depending on your pm4 installation)
- Make sure you already have a language installed (`it`, `ar`, `ca`, etc.)
`http://processmaker.test/api/1.0/languages/ar/uninstall`
ci:next
=> task/FOUR-18687: Added function to delete language file from packages

ProcessMaker/Helpers/ScreenTemplateHelper.php, ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Models/Template.php, ProcessMaker/Templates/ScreenTemplate.php, routes/api.php
Tickets:
[FOUR-18326](https://processmaker.atlassian.net/browse/FOUR-18326)
[FOUR-18328](https://processmaker.atlassian.net/browse/FOUR-18328)
[FOUR-18329](https://processmaker.atlassian.net/browse/FOUR-18329)
This PR introduces logic for Applying Layouts and Fields to Screens via the Screen Templates Panel in `screen-builder`.
When a user chooses to only apply the layout from a template to their screen:
- The layout is added to the bottom of the screen, enabling the user to arrange the existing information as needed.
- When the screen has more than one page, the changes will be added to the bottom of the current page.
When a user applies only the fields:
- The fields are added to the bottom of the screen, providing the user with flexibility to reposition them as required.
- When the …
=> FOUR-18326 | Implement Layout Application Logic

ProcessMaker/Helpers/ScreenTemplateHelper.php, ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Models/Template.php, ProcessMaker/Templates/ScreenTemplate.php, routes/api.php
Ticket: [FOUR-18323](https://processmaker.atlassian.net/browse/FOUR-18323)
This PR introduces logic for Applying CSS to Screens via the Screen Templates Panel in `screen-builder`.
When a user chooses to only apply CSS from a template to their screen:
- If the template introduces CSS elements, they will be added to the existing screen CSS.
- If the template has the same CSS elements as the existing screen, it will replace them with the  CSS elements from the template.
- If both, screen and template, share CSS elements but the template adds new styles or properties, they should be added to the existing screen individually. 
1. Go to branch `task/FOUR-18323` in `screen-builder` and `processmaker`.
2. Ensure you have a Screen Template with Custom CSS in your environment.
3. Create a new …
=> FOUR-18323 | Implement CSS Application Logic

ProcessMaker/Http/Controllers/CasesController.php, resources/jscomposition/cases/casesDetail/api/data.js, resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/TabHistory.vue, resources/jscomposition/cases/casesDetail/config/columns.js, resources/jscomposition/cases/casesDetail/edit.js, resources/views/cases/edit.blade.php
Create the view for show the summary related to the case - History Tab
- https://processmaker.atlassian.net/browse/FOUR-18970
ci:deploy
ci:next
=> FOUR-18970: Create the view for show the summary related to the case - History Tab

resources/jscomposition/base/buttons/OutlineButton.vue, resources/jscomposition/base/form/Dropdown.vue, resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/base/table/THeader.vue, resources/jscomposition/base/ui/AppPopover.vue, resources/jscomposition/cases/casesDetail/config/columns.js, resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/cases/casesMain/CasesMain.vue, resources/jscomposition/cases/casesMain/config/columns.js, resources/jscomposition/system/table/FilterableTable.vue, resources/jscomposition/system/table/cell/CaseTitleCell.vue, resources/jscomposition/system/table/cell/ParticipantsCell.vue, resources/jscomposition/system/table/filter/FilterColumn.vue, resources/jscomposition/system/table/filter/FooterButtons.vue, resources/jscomposition/system/table/filter/SortingButtons.vue, resources/jscomposition/system/table/filter/index.js, resources/jscomposition/system/table/filter/operator/BetweenOperator.vue, resources/jscomposition/system/table/filter/operator/DateBetweenOperator.vue, resources/jscomposition/system/table/filter/operator/DateOperator.vue, resources/jscomposition/system/table/filter/operator/FilterOperator.vue, resources/jscomposition/system/table/filter/operator/InOperator.vue, resources/jscomposition/system/table/filter/operator/InputOperator.vue, resources/jscomposition/system/table/filter/operator/index.js, resources/jscomposition/system/table/filter/operator/operatorConfig.js, resources/jscomposition/system/table/index.js
- https://processmaker.atlassian.net/browse/FOUR-19003
ci:next
=> FOU-19003 : Create a NEW VIEW for cases Part Filters

ProcessMaker/Http/Controllers/Api/TaskController.php, routes/api.php, tests/Feature/Api/TaskControllerTest.php
Create an API to return the "Task" related with the case
- https://processmaker.atlassian.net/browse/FOUR-18636
ci:next
=> FOUR-18636

ProcessMaker/Contracts/CaseRepositoryInterface.php, ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Jobs/CaseStore.php, ProcessMaker/Jobs/CaseUpdate.php, ProcessMaker/Jobs/CaseUpdateStatus.php, ProcessMaker/Models/CaseParticipated.php, ProcessMaker/Models/CaseStarted.php, ProcessMaker/Repositories/CaseParticipatedRepository.php, ProcessMaker/Repositories/CaseRepository.php, ProcessMaker/Repositories/ExecutionInstanceRepository.php, ProcessMaker/Repositories/TokenRepository.php, composer.json, composer.lock, database/migrations/2024_09_09_181717_create_cases_started_table.php, database/migrations/2024_09_12_172734_create_cases_participated_table.php
Every time a new request without a case is started create a new started case and participated case
- Add Case and CaseParticipated repositories
- Add CaseStore, CaseUpdate and CaseUpdateStatus queues
- Add the laravel/pail library
[FOUR-18599](https://processmaker.atlassian.net/browse/FOUR-18599)
ci:next
[FOUR-18599]: https://processmaker.atlassian.net/browse/FOUR-18599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-18599 populate cases_started, cases_participated tables (main flow)

ProcessMaker/Traits/HasScreenFields.php
- HasScreenFields trait was modified to show fields from new component CollectionRecordControl
https://processmaker.atlassian.net/browse/FOUR-18353
ci:next
=> FOUR-18107 - feature/FOUR-18103:  Support for drafts (hidden variable in screen data)

resources/jscomposition/base/form/Dropdown.vue, resources/jscomposition/base/table/Pagination.vue, resources/jscomposition/base/table/TCell.vue, resources/jscomposition/base/table/index.js, resources/jscomposition/base/ui/AppAvatar.vue, resources/jscomposition/base/ui/AppPopover.vue, resources/jscomposition/cases/casesDetail/components/RequestTable.vue, resources/jscomposition/cases/casesDetail/components/TaskTable.vue, resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/cases/casesMain/api/index.js, resources/jscomposition/cases/casesMain/config/columns.js, resources/jscomposition/cases/casesMain/utils/counters.js, resources/jscomposition/system/table/Pagination.vue, resources/jscomposition/system/table/cell/LinkCell.vue, resources/jscomposition/system/table/cell/ParticipantsCell.vue, resources/jscomposition/system/table/cell/TruncatedOptionsCell.vue, resources/jscomposition/system/table/cell/index.js
- https://processmaker.atlassian.net/browse/FOUR-19237
=> FOUR-19237: Cases list "Pagination"

ProcessMaker/Repositories/CaseRepository.php, database/migrations/2024_09_09_181717_create_cases_started_table.php, database/migrations/2024_09_12_172734_create_cases_participated_table.php, tests/Feature/Api/V1_1/CaseControllerTest.php, tests/Feature/Cases/CaseParticipatedTest.php, tests/Feature/Cases/CaseStartedTest.php, tests/Feature/Cases/CasesJobTest.php
When a process runs an automated task (Script Task, Service Task) it must update the following fields:
- The User starts a process that has assigned.
- The cases_started table is populated with the cases started by the User.
- The process goes into automated tasks (like script tasks, data-connector)
- The system updates all cases_started fields that changed except: tasks_ids, tasks_titles, since this columns stores only User and Manual Tasks
[FOUR-18600](https://processmaker.atlassian.net/browse/FOUR-18600)
ci:next
[FOUR-18600]: https://processmaker.atlassian.net/browse/FOUR-18600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-18600 populate cases_started, cases_participated tables automated tasks 

tests/Feature/Api/PermissionsTest.php
- https://processmaker.atlassian.net/browse/FOUR-19377
ci:next
=> FOUR-19377

ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
Create a screen with a file upload feature.
Integrate the screen into a process.
Upload the next PDF
[student.pdf](https://github.com/user-attachments/files/17138471/student.pdf)
Current behavior:
The PDF is blocked
Expected behavior
PDFs that don't have Javascript should be uploaded to ProcessMaker
- Modified the conditions to validate a PDF
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-19373)
ci:next
ci:deploy
=> FOUR-19373: Incorrect validation - Error uploading PDF file: Dangerous content of PDF file

ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, resources/views/tasks/edit.blade.php
- Have cases running in a process.
- edit one of the screens that is used in those cases' process.
- save and publish the changes on the screen.
- Changes are reflected only in new cases.
- Changes applied on a screen and published are only reflected in new cases. in 4.10 the changes were reflected in new and also ongoing cases
- Change should be reflected in ongoing cases.
- Added a version parameter (screen_version) to screen URLs, generated based on the latest published id of the screen.
- This approach forces the browser to treat each updated published screen as a new resource, preventing the use of outdated cached versions.
- Verify that screen updates generate new URLs with different version parameters, ensuring that changes are correctly …
=> FOUR-19110: [40531] changes on screen are not reflected in ongoing cases

ProcessMaker/Models/Process.php, tests/unit/ProcessMaker/Models/ProcessTest.php
Tasks with nested groups assigned were throwing an error.
- Fix a incorrect method call, probably happened in a refactor
- Add test
See reproduction steps in jira issue
- https://processmaker.atlassian.net/browse/FOUR-19390
ci:next
ci:deploy
.
=> FOUR-19390 Fix call to missing method

ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Policies/ProcessRequestTokenPolicy.php, database/factories/ProcessMaker/Models/UserFactory.php, tests/Feature/Api/ProcessRequestTokenPolicyTest.php
Admin users should always be allowed to reassign tasks
- Move reassign permission check to policy
Attempt to reassign a usertask using the API as an admin user
- https://processmaker.atlassian.net/browse/FOUR-19002
ci:next
ci:deploy
.
=> Allow admin users to reassign any user task

ProcessMaker/Repositories/TokenRepository.php
- When the variable used in self_service_groups is a list of integer IDs it cause the webentry could not find the tasks self service assigned to the logged user.
- Cast the self_service_groups variable types to array of strings.
- Import the process described in the ticket
- Run the webentry with a logged user
- Check that the second task does not show the self service task
- Try to do a refresh and the problem persists
With the fix
- Import the process described in the ticket
- Run the webentry with a logged user
- Check that the second task now shows a self service task
- Try to do a refresh and self service remains
- https://processmaker.atlassian.net/browse/FOUR-19402
ci:next
ci:deploy
=> FOUR-19402 Fix self_service_groups variable types

ProcessMaker/Models/Clipboard.php, resources/js/processes/screen-builder/screen.vue, resources/views/processes/screen-builder/screen.blade.php
- Open multiple pages and screens
- Add/Select some elements
- Add them to the clipboard
- Paste the items to different pages or screens
https://github.com/user-attachments/assets/1ac558ad-8993-4f6e-a0ae-1f69d0d01f38
- https://processmaker.atlassian.net/browse/FOUR-13443
ci:next
=> FOUR-13443 Implement Clipboard usage between pages or separate screens

ProcessMaker/Http/Controllers/Api/UserConfigurationController.php, ProcessMaker/Models/UserConfiguration.php, database/migrations/2024_09_26_131232_create_user_configuration.php, routes/api.php, tests/Feature/Api/UserConfigurationTest.php
Create the new table user_configuration to save the configuration, review the ticket related https://processmaker.atlassian.net/browse/FOUR-18560
Create a new API’s to save the information in this table
```
Route::get('users/configuration', [UserConfigurationController::class, 'index'])->name('users.configuration.show');
Route::put('users/configuration', [UserConfigurationController::class, 'store'])->name('users.configuration.update'); 
```
- https://processmaker.atlassian.net/browse/FOUR-18629
ci:next
=> feature/FOUR-18629: BE: The API needs to consider save the collapse pero user and feature

resources/js/tasks/components/TasksList.vue, resources/js/tasks/components/TasksPreview.vue
As the Process Manager I want to view the tasks related to the processes I manage so that I can understand the current workload and prioritize task assignments efficiently.
Tech notes: Make this an advanced filter. We will need to send that advanced filter to the backend when the users selects the icon
Should include both unclaimed self-service tasks and and in-progress tasks for all the manager’s running cases
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-18099)
ci:next
=> feature/FOUR-18099 STORY Tasks from Processes I manage section

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/ProcessTranslations/ProcessTranslation.php, resources/js/components/Menu.vue, resources/js/processes/screen-builder/screen.vue, routes/api.php
Apply translations to a screen
- A new endpoint that translate a screen config has been created.
- In this PR the UI uses a simple "translate" button that will be replaced with the flag in tickets FOUR-18709
- This PR resolves:
https://processmaker.atlassian.net/browse/FOUR-18715
https://processmaker.atlassian.net/browse/FOUR-18716
ci:next
=> FOUR-18716, FOUR-18715: Apply translations to screen

ProcessMaker/Http/Controllers/Auth/LoginController.php
The problem is described in the next video:
https://github.com/user-attachments/assets/20dc1a61-79fa-45df-ada4-7afabc8c3b8c
https://drive.google.com/file/d/1ZrFNuWyK-gioGwM9XXtV9dixT398KWks/view
- As part of the logout, the Laravel cookie is removed, so it can't be used again.
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-16704)
ci:next
=> FOUR-16704: Session Token Not Invalidated on Logout

ProcessMaker/Http/Controllers/Api/V1_1/CaseController.php, ProcessMaker/Repositories/CaseApiRepository.php, routes/v1_1/api.php, tests/Feature/Api/V1_1/CaseControllerTest.php
- Requires new endpoint with counters for cases improvements.
- Implemented new endpoint "get_my_cases_counters".
Create cases and process request and call to new endpoint "get_my_cases_counters".
https://processmaker.atlassian.net/browse/FOUR-18605
ci:next
=> FOUR-18605 Count the cases and requests by user and status (EP)

ProcessMaker/Http/Controllers/Admin/UserController.php, ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Http/Controllers/ProfileController.php, resources/views/admin/users/edit.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/users/profile.blade.php, tests/Feature/Api/UsersTest.php
Reverts ProcessMaker/processmaker#7368 due to QA observations and possible regressions.
=> Revert "observation/FOUR-16703 Insecure email change mechanism"

resources/js/print-layout.js, resources/views/layouts/print.blade.php, webpack.mix.js
- https://processmaker.atlassian.net/browse/FOUR-18749
- https://processmaker.atlassian.net/browse/FOUR-18748
- Added a layout for the print PDF feature
- https://github.com/ProcessMaker/package-ai/pull/311
ci:next
=> task/FOUR-18749: Added print-pdf Blade layout

ProcessMaker/Http/Controllers/Api/V1_1/CaseController.php, ProcessMaker/Http/Resources/V1_1/CaseResource.php, ProcessMaker/Repositories/CaseApiRepository.php, ProcessMaker/Repositories/CaseRepository.php, database/factories/CaseParticipatedFactory.php, database/factories/CaseStartedFactory.php, tests/Feature/Api/V1_1/CaseControllerTest.php, tests/Feature/Cases/CaseStartedTest.php
Instead of populating this field in the cases tables (started and participated), store only the IDs and do a post-processing to complete the required information
[FOUR-19397](https://processmaker.atlassian.net/browse/FOUR-19397)
ci:next
[FOUR-19397]: https://processmaker.atlassian.net/browse/FOUR-19397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19397 populate the participants column with user data

resources/js/components/Menu.vue, resources/js/processes/screen-builder/screen.vue
- Disable screen toolbar when Clipboard Tab is active
- Open an screen
- Add some elements to clipboard
- Open the clipboard from the pages dropdown
- You can add or remove elements from the clipboard
- Note the toolbar is disabled
- https://processmaker.atlassian.net/browse/FOUR-18059
ci:next
ci:screen-builder:FOUR-18059
ci:deploy
=> FOUR-18059 Implement Clipboard Tab

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/ProcessTranslations/ProcessTranslation.php, resources/js/processes/screen-builder/screen.vue, routes/api.php
Implements https://processmaker.atlassian.net/browse/FOUR-18718
- Evaluates mustache before translating a screen
- https://processmaker.atlassian.net/browse/FOUR-18718
ci:next
=> FOUR-8718: Render mustaches, maybe a re render

ProcessMaker/Models/CaseStarted.php, ProcessMaker/Repositories/CaseApiRepository.php, ProcessMaker/Repositories/CaseParticipatedRepository.php, ProcessMaker/Repositories/CaseRepository.php, ProcessMaker/Repositories/CaseSyncRepository.php, ProcessMaker/Repositories/CaseUtils.php, database/factories/CaseParticipatedFactory.php, database/factories/CaseStartedFactory.php, tests/Feature/Api/V1_1/CaseControllerSearchTest.php, tests/Feature/Api/V1_1/CaseControllerTest.php
Implement a Text match search and filters based on the following document: ([Improve My Cases | Full Text Search Examples with cases_started](https://processmaker.atlassian.net/wiki/spaces/ARB/pages/3597762650/Improve+My+Cases#Full-Text-Search-Examples-with-cases_started) ) 
For sorting options consider:
Sort available only for the following fields
case_number
case_title (low performance because of full scan)
status (low performance because of full scan)
initiated_at (low performance because of full scan)
completed_at (low performance because of full scan)
[FOUR-18610](https://processmaker.atlassian.net/browse/FOUR-18610)
ci:next
[FOUR-18610]: https://processmaker.atlassian.net/browse/FOUR-18610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-18610 combine search text and filters

ProcessMaker/Http/Controllers/Auth/LoginController.php
When the option to block double session is set for ProcessMaker, the session is locked and the state is not allowed to change.
- Change order to disable sessions
Steps in the ticket
review ticket FOUR-16704, as well.
- [FOUR-19466](https://processmaker.atlassian.net/browse/FOUR-19466)
- [FOUR-16704](https://processmaker.atlassian.net/browse/FOUR-16704)
ci:next
[FOUR-19466]: https://processmaker.atlassian.net/browse/FOUR-19466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-16704]: https://processmaker.atlassian.net/browse/FOUR-16704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The Block duplicate session in IP Restriction option only works the first time

ProcessMaker/Http/Controllers/Api/CommentController.php, ProcessMaker/Http/Controllers/Api/ProcessRequestController.php, ProcessMaker/Listeners/BpmnSubscriber.php, ProcessMaker/Listeners/CommentsSubscriber.php, ProcessMaker/Models/Comment.php, ProcessMaker/RetryProcessRequest.php, ProcessMaker/RollbackProcessRequest.php, tests/Feature/Api/CommentTest.php
- https://processmaker.atlassian.net/browse/FOUR-19490
ci:package-webentry:feature/FOUR-19490
ci:connector-send-email:feature/FOUR-19490
ci:package-comments:feature/FOUR-19490
=> FOUR-19490: The store comments needs to consider populate the comments.case_number

ProcessMaker/Exception/MissingScreenPageException.php, ProcessMaker/Templates/ScreenTemplate.php
This PR addresses the 500 error encountered when attempting to apply a template to a screen page that has not been stored in the database. The root cause was the absence of the newly created screen page in the screens table during the query for the screen configuration.
- Implemented a query using the `screens_versions` table, which retains the 'draft' version of the screen.
- Added a fallback mechanism to handle cases where the `screens_versions` table is unavailable. When this occurs, an error message prompts the user to save the screen.
1. Ensure screen templates are created and available.
2. Open or create a new screen in Screen Builder.
3. Add a new page within the screen.
4. Go to the newly created page.
5. Select 'Templates' in the navigation bar.
6. Choose a template and apply all …
=> Fix 500 Error When Applying Templates to Unsaved Screen Pages

ProcessMaker/Traits/TaskControllerIndexMethods.php, tests/Feature/Api/ProcessRequestsTest.php
/api/1.0/tasks endpoint failed becuase an exception in DataManager.
Cause: Missing scenario when task endpoint was improved in FOUR-16575 https://github.com/ProcessMaker/processmaker/pull/7123
- Consider the parameter `includes=data` to load the request data.
Call the api `/api/1.0/task?include=data`
- https://processmaker.atlassian.net/browse/FOUR-18912
=> FOUR-18912 [FALL] Fix get data in tasks endpoint

resources/js/processes-catalogue/components/CardProcess.vue, resources/js/processes-catalogue/components/menuCatologue.vue, resources/js/processes-catalogue/components/utils/SearchCards.vue
Ticket: [FOUR-19482](https://processmaker.atlassian.net/browse/FOUR-19482)
In the Process LaunchPad, the placeholder text in the templates search bar should read "Search Templates" instead of "Search Categories and Processes". 
- Pass `processSelected` and `templateSelected` props to `SearchCards.vue`. 
- Update `b-form-input` placeholder in `SearchCards.vue` based on whether or not a Process or Template has been selected.
1. Go to branch `FOUR-19482` in `processmaker`.
2. Go to Processes.
3. Select 'All Templates' from the 'Add From Templates' dropdown.
- The search bar text should read 'Search Templates'.
4. Select a Process Category under 'Available Processes'.
- The search bar text should read 'Search Categories and Processes'.
ci:next
ci:deploy
[FOUR-19482]: …
=> FOUR-19482 | Placeholder Text for All Templates Search Is Not Correct in LaunchPad

ProcessMaker/ImportExport/Exporters/EmbedExporter.php, ProcessMaker/ImportExport/Exporters/ProcessExporter.php, database/factories/ProcessMaker/Models/EmbedFactory.php, tests/Feature/ImportExport/Exporters/ProcessExporterTest.php, tests/Feature/ImportExport/Exporters/ProcessLaunchpadExporterTest.php
When importing a Process as a Template it appears that it does not include the LaunchPad embedded links.
- Update code to save embed models associated with the process.
- In `ProcessExporter.php`, added code to save the `model_id` attribute of embed models associated with the process.
- In `ProcessExporterTest.php`, added tests to verify the saving and deletion of embed models associated with the process.
- Import the attached template process. (see JIRA)
- Go to processes
- The new imported process should have embed YouTube link.
- [FOUR-19287](https://processmaker.atlassian.net/browse/FOUR-19287)
[FOUR-19287]: https://processmaker.atlassian.net/browse/FOUR-19287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19287: Incorrect model_id assignment during Import in ProcessExporter importEmbed

ProcessMaker/Http/Controllers/Auth/LoginController.php
Add a parameter for URL to login without force SAML
1. Configure other type of login
2. Force to login using this config
3. Add in the login the new parameter to avoid the login config
`?showLogin=true`
- https://processmaker.atlassian.net/browse/FOUR-19276
ci:next
ci:deploy
=> FOUR-19276: Add parameter in the login

resources/views/requests/show.blade.php
FOUR-19272 : CSS style is not rendering in Summary section
- Add the missing variable in the vue component vue-form-renderer
Go to the screen in end event
- https://processmaker.atlassian.net/browse/FOUR-19272
ci:next
ci:deploy
=> FOUR-19272: CSS style is not rendering in Summary section

ProcessMaker/Http/Controllers/Api/TaskDraftController.php
FOUR-17680: [39200] AutoSave feature does not save correctly for New Line
##STEPS TO REPRODUCE
1. Create a new screen
2. add a text area
3. set textarea configuration to rich text
4. add line input
5. publish (Screenshot attached ) 
6. Run a request and fill the text area with multiple lines.
7. Make sure the autosave saves the form and then reload the page.
8. Notice that the content in the text area is not the same.
- Into the  ProcessMaker/Http/Controllers/Api/TaskDraftController.php in the update method , we added a validation to sanitize the data
-  https://processmaker.atlassian.net/browse/FOUR-17680
ci:next
ci:deploy
=> FOUR-17680: [39200] AutoSave feature does not save correctly for New Line

ProcessMaker/BuildSdk.php
This is a bug in OpenAPI Generator https://github.com/OpenAPITools/openapi-generator/issues/8943
It was apparently fixed in v6 but we are locked into 5.1.1 because, as far as I remember, in more recent versions the CSharp SDK was broken.
Even with 5.1.1 we are patching some code and this fix patches more code.
The OpenAPI Generator project has continued to have problems and we should consider depreciating its usage. We could just replace it with a pre-built guzzle client.
- Patch the generated code.
- Verify you can see the problem in the jira ticket using the script editor
- Checkout this branch and rebuild the executor `php artisan processmaker:build-script-executor php --rebuild`
- Try it again and it should work
ci:next
- https://processmaker.atlassian.net/browse/FOUR-17328
=> FOUR-17328 Patch generated SDK code to fix error

ProcessMaker/Console/Commands/ProcessmakerClearRequests.php, tests/Feature/ClearRequestsTest.php
The cases are listed after execute the command to clear requests.
Added code to clean new tables.
Create some requests, after execute the artisan command: `php artisan processmaker:clear-requests` 
https://processmaker.atlassian.net/browse/FOUR-19591
=> FOUR-19591 API related to cases is showing cases after the execution of 'processmaker:clear-requests'

ProcessMaker/Http/Controllers/Api/V1_1/CaseController.php
The API not return a value different to null when is an administrator.
The user can have the property "is_administrator" enabled.
Consume the endpoint "GET /api/1.1/cases/get_my_cases_counters"
https://processmaker.atlassian.net/browse/FOUR-19523
=> FOUR-19523 API getAllCasesCounter does not considered the new permissions for 'admin' user

resources/js/processes-catalogue/components/mixins/ProcessesMixin.js, resources/views/processes-catalogue/index.blade.php
1. Create a participant user
2. Go to Permissions 
3. Enable documentation permissions
4. Enable launch pad permissions
5. Save the changes
6. Login with the user created 
7. Go to process browser
8. Open a process
9. Go to options
- https://processmaker.atlassian.net/browse/FOUR-19171
ci:deploy
ci:release-2024-fall
=> FOUR-19171:View documentation option is not visible to Participant user from Launch pad

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Repositories/CaseSyncRepository.php, ProcessMaker/Repositories/ExecutionInstanceRepository.php, ProcessMaker/Repositories/TokenRepository.php, tests/Feature/Cases/CasesJobTest.php
The creation and refresh of case status have caused a significant delay.
- Make the Cases jobs synchronous
- Store only the participant ID on cases:sync
1. Create a process with one task
2. Start the case
3. Go to the Cases list
4. When the queue was delayed, the case was not created immediately
5. The user views the cases and the cases do not appears
6. User Refresh page
[FOUR-19696](https://processmaker.atlassian.net/browse/FOUR-19696)
[FOUR-19696]: https://processmaker.atlassian.net/browse/FOUR-19696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19696 creation and refresh of case status has a significant delay

resources/js/components/shared/ellipsisMenuActions.js, resources/views/processes/list.blade.php
- https://processmaker.atlassian.net/browse/FOUR-19146
ci:deploy
ci:release-2024-fall
ci:package-process-documenter:bugfix/FOUR-19146
=> Users with process permissions does not have access documentation by default

ProcessMaker/Http/Controllers/Admin/DevLinkController.php, ProcessMaker/Http/Controllers/Api/DevLinkController.php, ProcessMaker/Models/DevLink.php, resources/js/admin/devlink/components/Index.vue, resources/js/admin/devlink/components/Status.vue, resources/lang/en.json
Add a "reconnect" button to an instance that can not connect.
- From Instance A, add a new instance to Instance B. Make sure you are logged out of Instance B
- This will redirect you to the login page for Instance B
- Instead of logging in, go back to Instance A DevLinks. Notice the instance is not connected. You should see the "Reconnect" button
- Click the button and log in. Verify that it works now.
- https://processmaker.atlassian.net/browse/FOUR-19519
=> Add reconnect feature to devlink

ProcessMaker/Managers/PackageManager.php
When a new language is installed and the folder lang.orig exists, the language should be created in this folder as well.
- add method to load json translations registered
- [FOUR-19690](https://processmaker.atlassian.net/browse/FOUR-19690)
ci:package-translations:observation/FOUR-19690
[FOUR-19690]: https://processmaker.atlassian.net/browse/FOUR-19690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add lang.orig for new installed languages for reset to default

ProcessMaker/Repositories/CaseRepository.php, tests/Feature/Cases/CaseParticipatedTest.php
The case title formatted was not being updated after the creation.
- Update case title formatted on case update.
- Create a process with case title configured that includes a case variable like:
```
New Expense report for {{name}}
```
And a task to update the used variable
- Update the process variable used in the title
- Review the case title formatted were updated
- https://processmaker.atlassian.net/browse/FOUR-19599
=> FOUR-19599 Fix The "Case Title" is empty in the caseList

tailwind.config.js
The padding of the footer in the template card details needs to be increased.
- Disabled Tailwind's Preflight in the tailwind.config.js to prevent unwanted margin and padding resets on native HTML elements (e.g., hr, h1-h6, etc.).
- Bootstrap already provides normalization for HTML elements, making Preflight redundant and potentially conflicting.
- Run `npm run dev` and check the Edit Screen -> Templates section.
- The `hr` tag should not have any tailwind.css rules.
- [FOUR-19659](https://processmaker.atlassian.net/browse/FOUR-19659)
[FOUR-19659]: https://processmaker.atlassian.net/browse/FOUR-19659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19659: Footer Padding Issue in Template Card Details

ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Managers/PackageManager.php, resources/.gitignore, resources/js/app-login.js, resources/js/bootstrap.js, resources/lang/.gitignore
This PR contains observation fixes for the epic
[Core](https://github.com/ProcessMaker/processmaker/pull/7606)
[Package Translations](https://github.com/ProcessMaker/package-translations/pull/140)
[Package AI](https://github.com/ProcessMaker/package-ai/pull/330)
[Package WebEntry](https://github.com/ProcessMaker/package-webentry/pull/259)
ci:package-translations:epic/FOUR-18042
ci:package-ai:epic/FOUR-18042
ci:package-webentry:epic/FOUR-18042
=> Epic/FOUR-18042: Admin Managed Platform AI Translations

resources/sass/tailwind.css
1. Open the tab Cases in processmaker
2. Check the UI table styles
- Add preconfig in tailwind css
Check the UI tables in route /cases
- https://processmaker.atlassian.net/browse/FOUR-19738
ci:deploy
=> FOUR-19738: UI: When a case is open some styles are broken

ProcessMaker/Models/Template.php, database/factories/ProcessMaker/Models/ScreenTemplatesFactory.php
There is no enforced height limit on the thumbnail or character limit on the description for templates, resulting in inconsistent display and layout issues within the template card. Per the PRD the description should have a 100 character limit
- Ensured 'description' field has a max length of 100 characters.
- Perform a manual test.
- [FOUR-19662](https://processmaker.atlassian.net/browse/FOUR-19662)
- [Screen Builder PR](https://github.com/ProcessMaker/screen-builder/pull/1752)
[FOUR-19662]: https://processmaker.atlassian.net/browse/FOUR-19662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19662: Enforce Height Limit on Thumbnail and Character Limit on Description in Template Card

resources/jscomposition/cases/casesDetail/components/CompletedForms.vue, resources/jscomposition/cases/casesDetail/components/RequestTable.vue, resources/jscomposition/cases/casesDetail/components/TaskTable.vue
Go to Cases
Open a case 
Order by task name
The order is not apply correctly
The order needs to apply in the taskNames
- the value correct for orderBy is order_by
- https://processmaker.atlassian.net/browse/FOUR-19779
=> FOUR-19779

ProcessMaker/Http/Controllers/Api/ProcessController.php
webentry reset cookie
- Add cache for LANGUAGE_ANON_WEBENTRY
- Set the default language for anonymous Webentry
- Review Webentry and change the language several times
- Finally, change the default language for Webentry and review the web entry page.
- [FOUR-19789](https://processmaker.atlassian.net/browse/FOUR-19789)
[FOUR-19789]: https://processmaker.atlassian.net/browse/FOUR-19789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> webentry reset cookie

ProcessMaker/Http/Controllers/Api/DevLinkController.php, ProcessMaker/Models/DevLink.php, resources/js/admin/devlink/components/BundleAssets.vue, resources/js/admin/devlink/components/Instance.vue, resources/js/admin/devlink/components/LocalBundles.vue, resources/js/admin/devlink/components/UpdateBundle.vue, resources/lang/en.json, tests/Model/DevLinkTest.php
The Reinstall bundle button is not working
- Add logic to button
- Refactor to dry up code
- Add missing translations
Ensure you can reinstall a bundle from the button on the bundle assets page
- https://processmaker.atlassian.net/browse/FOUR-19797
=> Fix reinstall button and refactor

ProcessMaker/Templates/ScreenTemplate.php
When selecting only the "Fields" option to apply to a screen, both the fields and the layout from the template are applied. The expected behavior is that only the fields should be applied.
- Create a screen template with both fields and a specific layout.
- Create a new screen.
- Use the "Apply Template" option and select only the "Fields" to apply.
**Observe that both the fields and layout are applied to the screen.**
When selecting the "Fields" option, only the fields from the selected template should be applied to the screen.
Selecting "Fields" applies both the fields and the layout of the template.
- Implement removeFormMultiColumns function that will remove all components === 'FormMultiColumn' 
Please follow the reproduction steps and make sure that the expected behavior is met.
- …
=> FOUR-19671:  Selection Applies Both Fields and Layout to Screen

ProcessMaker/Repositories/CaseRepository.php, ProcessMaker/Repositories/CaseSyncRepository.php, ProcessMaker/Repositories/CaseUtils.php, tests/Feature/Api/V1_1/CaseUtilsTest.php
When I start a case and route to the next task with the same user the "In Progress" cases list is empty
- Store the correct status in the instance updating
https://github.com/user-attachments/assets/3b4f4885-ab17-456e-abfd-4af0c1f3dfeb
1. Create a cases with Admin user
2. Route to the next task
3. Review the data in the My Cases and In progress list
[FOUR-19816](https://processmaker.atlassian.net/browse/FOUR-19816)
[FOUR-19816]: https://processmaker.atlassian.net/browse/FOUR-19816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19816 when I start a case and route to the next task with the same user the "In Progress" cases list is empty

ProcessMaker/Http/Controllers/Auth/LoginController.php
Log in 
Configure suer  SAML 
log in with SAML
log out 
It is necessary to logout twice.
- https://processmaker.atlassian.net/browse/FOUR-19530
=> FOUR-19530 (C) : (summer-2024) The application logs out the second time, when using a SAML user 

tests/Feature/CasesControllerTest.php
- https://processmaker.atlassian.net/browse/FOUR-19820
=> FOUR-19820

ProcessMaker/Http/Controllers/Api/DevLinkController.php, ProcessMaker/Jobs/DevLinkInstall.php, ProcessMaker/Models/Bundle.php, ProcessMaker/Models/DevLink.php, resources/js/admin/devlink/components/BundleAssets.vue, resources/js/admin/devlink/components/LocalBundles.vue, resources/js/admin/devlink/components/UpdateBundle.vue, resources/js/admin/devlink/components/VersionCheck.vue, resources/js/components/shared/AddToBundle.vue, resources/js/components/shared/ellipsisMenuActions.js, resources/js/processes/components/ProcessesListing.vue, resources/lang/en.json, routes/api.php, tests/Model/BundleTest.php, tests/Model/DevLinkTest.php
Reinstalling a bundle is getting current assets from the remote instance. It should use the assets as they were when the bunde was first installed or last upgraded.
- Save a copy of the payload and replay it when reinstalling
ci:k8s-branch:upgrade-alpine
ci:deploy
..
- https://processmaker.atlassian.net/browse/FOUR-19812
=> FOUR-19812 Fix reisntall functionality

resources/js/templates/components/ProcessTemplatesListing.vue
- Got to processes list
-  Click on tab "templates"
- Select any template
- Click on view documentation
AI documentation and PDF buttons not showing
- That condition that hid documentation when viewing a template has been removed (introduced in FOUR-18944)
- When AI is not installed the URL of package-process-documenter is used.
- https://processmaker.atlassian.net/browse/FOUR-19821
=> FOUR-19821: AI documentation and PDF button not showing in template documentation.

routes/api.php
Normal user can not see all public files from Preview pane
Changed Logs permissions
Login with admin
Create a new user
Check View settings option in the Settings accordion on the Permissions tab 
Go to Admin > file manager page 
Select public option
Upload five files
Login with the new user
Go to Admin > file manager page 
Select public option
Press preview button to first file
https://processmaker.atlassian.net/browse/FOUR-19802
=> observation/FOUR-19802 Changed Logs permissions

resources/jscomposition/cases/casesMain/config/columns.js
When a user go to InProgress and Completed list the column status does not have a use because per default the filter by status was apply
- https://processmaker.atlassian.net/browse/FOUR-19881
=> FOUR-19881 : Remove status column from In Progress and Completed

ProcessMaker/Http/Resources/V1_1/CaseResource.php, ProcessMaker/Models/CaseParticipated.php, ProcessMaker/Models/CaseStarted.php, tests/Feature/Api/V1_1/CaseControllerTest.php
Some tests fails when some test dates have different timezones and the format is not the same.
- Use ISO 8601 date format `c`.
- Fix the resource format
- https://processmaker.atlassian.net/browse/FOUR-19882
ci:processmaker:release-2024-fall
=> FOUR-19882 Fix flaky tests

resources/lang/de.json, resources/lang/en.json, resources/lang/es.json, resources/lang/fr.json
- Go to screen designer
- Add or edit a line input field
- Enable "encrypted" in "Advanced" section
Should be displayed the label "Users/Groups to View Encrypted Fields"
Is displayed the label "Users/Groups to View"
Update label
https://processmaker.atlassian.net/browse/FOUR-19749
=> FOUR-19749 Missed label 'Users/Groups to View Encrypted Fields'

resources/views/requests/show.blade.php
The button GO TO CASE needs to open the case in the same page NOT OPEN A NEW TAB
- https://processmaker.atlassian.net/browse/FOUR-19892
=> FOUR-19892:The GO TO CASE needs to refresh the same page instead of open a new tab

ProcessMaker/Http/Controllers/CasesController.php, resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/variables/index.js, resources/views/cases/edit.blade.php
As a user when I open a case the Request tab needs to Hide if the case has only one Request and show when the request has more >= 2 
- https://processmaker.atlassian.net/browse/FOUR-19891
=> FOUR-19891:The tab Request needs to show only when the case has more than 1 request

resources/sass/collapseDetails.scss, resources/views/tasks/edit.blade.php
- Have a process
- Create a case
- Open the task
- Open comments
In bottom comments there is an scroll 
- https://processmaker.atlassian.net/browse/FOUR-19884
=> FOUR-19884: There is an scroll in task comments

ProcessMaker/Console/Commands/UpdateCommentsCaseNumber.php, upgrades/2024_10_08_113301_populate_comments_case_number.php
The upgrade procedure with customer backups is given an error: Column 'id' in where clause is ambiguous
- The chunckById use the ID to apply some order but this query has two columns id 
Execute the commands:
`php artisan upgrade
php artisan processmaker:update-comments-case-number`
- https://processmaker.atlassian.net/browse/FOUR-19920
=> FOUR-19920: The upgrade procedure with customer backups is given an error: Column 'id' in where clause is ambiguous

resources/views/requests/show.blade.php
FOUR-19272 : CSS style is not rendering in Summary section
- Add the missing variable in the vue component vue-form-renderer
Go to the screen in end event
- https://processmaker.atlassian.net/browse/FOUR-19272
ci:deploy
=> FOUR-19272 : CSS style is not rendering in Summary section

resources/jscomposition/system/table/cell/TruncatedOptionsCell.vue
- Go to Cases
- See the list of cases
- Mouse over the links
When a mouse is over the link, is not possible to see the link to open:
- https://processmaker.atlassian.net/browse/FOUR-19815
=> FOUR-19815:UI: The mouse over the links does not show the link

resources/views/cases/casesMain.blade.php
##Steps to Reproduce
2. Go to Cases page
3. Check the title
##Current Behavior
The title in Cases page is empty
- https://processmaker.atlassian.net/browse/FOUR-19924
ci:deploy
=> FOUR-19924 : Title in cases pages is empty

ProcessMaker/Templates/ScreenComponents.php
- The new component Control Record List was added to ScreenComponents.php file
- Create a new screen in the Screen Builder.
- Add a Collection Record Control to the screen.
- Convert the screen to a template.
- Create a new screen from the saved template or apply the template to an existing screen.
https://processmaker.atlassian.net/browse/FOUR-19663
=> bugfix/FOUR-19663: Collection Record Control Not Persisting in Screen Templates

ProcessMaker/Repositories/CaseParticipatedRepository.php, ProcessMaker/Repositories/CaseRepository.php, ProcessMaker/Repositories/CaseSyncRepository.php, ProcessMaker/Repositories/CaseUtils.php, tests/Feature/Cases/CaseParticipatedTest.php, tests/Feature/Cases/CaseStartedSubProcessTest.php, tests/Feature/Cases/CaseStartedTest.php, tests/Feature/Cases/CaseSyncRepositoryTest.php, upgrades/2024_10_09_152947_populate_cases_participated.php
Cases participated does not have all the participations updated
- Refactor of the cases_participated population
- [FOUR-19928](https://processmaker.atlassian.net/browse/FOUR-19928)
[FOUR-19928]: https://processmaker.atlassian.net/browse/FOUR-19928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-19928 cases participated does not have all the participations updated

resources/views/layouts/navbar.blade.php
- Login in ProcessMaker and change the view to mobile
- Use the tab key to navigate between interactive elements
- In the mobile view the hamburger menu in the top right is not focused when the tab key is pressed
The hamburger menu is nos focused when the tab key is used 
**Expected Behavior:*
The hamburger menu should be focused when the user navigates using the tab key
- Add styles to focused toggler button
- [FOUR-19832](https://processmaker.atlassian.net/browse/FOUR-19832)
[FOUR-19832]: https://processmaker.atlassian.net/browse/FOUR-19832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/FOUR-19832: Focus is not visible in the hamburger menu (mobile view)

resources/js/components/requests/card.vue
Login to Sena Cloud Environment
click on on the Green Request button to start a new Request
- Fix the css
- https://processmaker.atlassian.net/browse/FOUR-13941
ci:deploy
=> FOUR-13941 : Inconsistent Button on Starting Request Layout

resources/views/tasks/edit.blade.php
1. Create userA without permission 
3. Assign the userA in the start event
4. Save the changes
5. Log in with userA
6. Create a case
7. Open the task
This action is Unauthorized appears with users without permission when open a case assigned 
- https://processmaker.atlassian.net/browse/FOUR-19939
=> FOUR-19939:This action is Unauthorized appears with users without permission when open a case assigned

ProcessMaker/Repositories/TokenRepository.php
currently the Self Service assignment is not getting the users from the internal variable of each element of the array assigned to the multi-instance task.
- https://processmaker.atlassian.net/browse/FOUR-19863
=> FOUR-19863 Use the right context of data to evaluate parallel task self service assignment

resources/jscomposition/cases/casesDetail/components/DisplayForm.vue
1. Open Cases
2. Open a Case
3. Go to Completed &Form
3. Open a completed Task by clicking in the Task
4. The completed Task should display in Read Only Mode
- https://processmaker.atlassian.net/browse/FOUR-19956
ci:deploy
=> FOUR-19956:Completed Task should show the form in Read only mode

resources/js/notifications/components/notification-message.vue
- Style background color was modified to make visible
1. Create a simple process
2. Create a request
3. Add a comment to mention for a @user
4. Scenario A
- Open the notification from bell icon
5. Scenario B
- Open the notification page
https://processmaker.atlassian.net/browse/FOUR-19967
=> bugfix/FOUR-19967: background color is not displayed in a notification

ProcessMaker/Http/Controllers/Api/TaskController.php, ProcessMaker/Traits/TaskControllerIndexMethods.php, resources/js/tasks/components/ListMixin.js, resources/js/tasks/components/TasksList.vue
`Process Manager` user can not see all Tasks
The user assigned in as process manager can not see all requests.
The user assigned as process manager should see all tasks without any permission.
https://processmaker.atlassian.net/browse/FOUR-19940
=> FOUR-19940 `Process Manager` user can not see all Tasks

resources/js/processes/scripts/components/AiTab.vue
- Go to designer
- Create a new scripts
- Click on AI assistant
- Click on generate
The message "ProcessMaker AI is currently offline. Please try again later." is displayed
A message indicating that there is no description should be displayed in the prompt.
- Handle errors when calling ai script actions
- FOUR-19985
=> Observation/FOUR-19985: Improvement, AI assistant Scripts improvement in the response message of the prompt without a description.

upgrades/2024_10_09_152947_populate_cases_participated.php
The migration of cases_participated crashes in dev clone
- Refactor populate cases participated upgrade script
run `php artisan upgrade`
- https://processmaker.atlassian.net/browse/FOUR-19950
=> FOUR-19950: The migration of cases_participated crashes in dev clone

resources/jscomposition/base/table/BaseTable.vue
1.Log In
2.Perform some searches
3.Go to cases tab
4.Click on AI search
- https://processmaker.atlassian.net/browse/FOUR-19989
ci:deploy
=> FOUR-19989 : The cases table overlays recent searches.

resources/jscomposition/cases/casesMain/config/columns.js, resources/jscomposition/system/table/cell/TruncatedOptionsCell.vue
"Task" column should be display the last task (or tasks if are possible), Currently is displaying always the first task.
In the next process the token is in the third task the previous two tasks were completed. The name of the first task is displayed always.
'status' => 'ACTIVE',
1. Go to cases
2 check the columns tasks
- https://processmaker.atlassian.net/browse/FOUR-19807
ci:deploy
=> FOUR-19807 : Task column should be display the last active task (or tasks if are possible)

resources/js/components/shared/PaginationTable.vue, resources/js/tasks/components/TasksList.vue, resources/jscomposition/system/table/Pagination.vue, resources/jscomposition/system/table/cell/StatusCell.vue
- Go to Tasks page
- Delete all filters (in order to check all statuses)
- Press flag icon
- Select Spanish option
status column and pagination are not translated
- Added the translation for statuses and pagination table.
https://processmaker.atlassian.net/browse/FOUR-19984
=> FOUR-19984: Status and Pagination translation does not work

resources/js/processes/import/components/ImportManagerView.vue
Instead of showing the password prompt, an error message was displayed.
- Check for only the first part of the returned error message to see if a password is required.
Import a process that was exported with a password
- https://processmaker.atlassian.net/browse/FOUR-19954
=> Fix import password prompt

ProcessMaker/Templates/ScreenTemplate.php
Ticket: [FOUR-19955](https://processmaker.atlassian.net/browse/FOUR-19955)
When attempting to apply a Screen Template to a Screen via the Screen Builder, after receiving the 'Template Successfully Applied' message, the page refreshes and the screen is still empty. The cause of this issue is that the screen version was being updated and saved in the database, however the screen was not being updated and saved in some cases.
- In the `applyTemplate` function in `ScreenTemplate.php`, when applying a template to a screen version (if `package-versions` is installed), ensure that the changes to the current screen are saved.
1. Go to branch `observation/FOUR-19955` in `processmaker`.
3. Create a new Screen.
4. Open the Screen to edit. Select 'Templates' from the top …
=> FOUR-19955 | Template Is Not Consistently Applied to Screen

ProcessMaker/ImportExport/Exporters/ScreenExporter.php, tests/Feature/ImportExport/Exporters/ScreenExporterTest.php, upgrades/2024_11_07_222831_fix_interstitial_key.php
Importing a process with in update mode was erasing the default screen interstitial key
- When importing, do not set to null unless there is already another screen with the interstitial key
- Create an upgrade script to fix instances where the key was erased
- Run `php artisan upgrade`
- In the DB, ensure you have one screen with the `interstitial` key
- Create a process with a task using the default screen interstitial
- Export the process
- Import the process, using "Basic" mode and the "update" button
- Ensure the same screen still has the `interstitial` key
- https://processmaker.atlassian.net/browse/FOUR-20043
=> Fix screen interstitial null key

resources/js/processes/import/components/ImportManagerView.vue
Log in 
G to Designr
CLcik on Process
Have a process. with contains a script
import the process
we cannot import a process that contains a script, we get a message on the screen
- The problem was not related to processes with scripts. The problem was  that the event that notifies the UI about the need of a password to import changed its format. This has been fixed
The issue was introduced with the fix for https://processmaker.atlassian.net/browse/FOUR-19520
- Export a process (use the option to use a password)
- Import the process
https://processmaker.atlassian.net/browse/FOUR-20058
=> FOUR-20058: It is not possible to import a process that contains script

resources/js/components/AvatarImage.vue
_PRocesses | manage > `unclaimed` status is not displayed_
The assign column does not display the unclaimed tag for Tasks with self service status
https://processmaker.atlassian.net/browse/FOUR-20005
=> FOUR-20005 PRocesses | manage > `unclaimed` status is not displayed

resources/js/Mobile/Card.vue
At mobile view the card was showing the Request ID, this cause confusion about the tasks.
- Show case_number instead of process_request.id for tasks.
- https://processmaker.atlassian.net/browse/FOUR-20052
=> FOUR-20052 Show case_number instead of process_request.id for tasks

resources/jscomposition/system/table/filter/defaultFilter/FilterColumn.vue
1. Create a cases
2. Go to cases all {{server_url}}/cases/all
3. Create a filter in one column like status
4. Check the column
- Add method to show different icons
- https://processmaker.atlassian.net/browse/FOUR-20047
ci:deploy
=> FOUR-20047 : No difference is made if a filter was made in the case list

ProcessMaker/Http/Middleware/GenerateMenus.php, resources/views/tasks/index.blade.php
1. Go to tasks
2. Mark any task as priority
3. Right click on the priority tab
4. Select "Open link in a new tab"
This PR addresses an issue in the tab navigation where multiple tabs (Inbox, Priority, Drafts) appeared as active simultaneously when accessing /tasks#inbox. The issue was caused by the href="#inbox" attribute in each tab link, which attempted to link to a specific anchor in the URL. This behavior confused the browser, especially when there was no element with id="inbox" in the DOM, causing multiple tabs to remain in an active state.
- Changed the href="#inbox" attribute to href="#" in each tab link to prevent the browser from attempting to scroll to a specific anchor, allowing Vue to control the active state of the tabs without browser interference.
- This change ensures that …
=> FOUR-20049: In task two tabs are highlighted

resources/views/requests/show.blade.php
- Create a case attach an image/file
- Click on File manager
- Click on preview
- Click on GO TO CASE
Ops! Page not found is displayed
- https://processmaker.atlassian.net/browse/FOUR-20031
ci:deploy
=> FOUR-20031:"Page not found" when selecting GO TO CASE

resources/jscomposition/base/table/TCell.vue
1. Create a process with large name
2. Start a case
3. Go to cases list
4. Open a case and go to task
5. Review the processName
- https://processmaker.atlassian.net/browse/FOUR-20109
ci:deploy
=> FOUR-20109 : The Task tab when open a case/{caseId}/ does not show correclty the process name

ProcessMaker/Http/Controllers/RequestController.php, tests/Feature/RequestTest.php
1. Create a process with Action by email like:
2. Create a case
3. Route to action by email task
4. Go to request main 
5. Click on open child action by email
- It is not possible to open child request of Action by Email, and the request of action by email is not listed in case main
- https://processmaker.atlassian.net/browse/FOUR-19990
ci:deploy
ci:next
=> FOUR-19990

ProcessMaker/Http/Controllers/Admin/UserController.php, ProcessMaker/Http/Controllers/Api/UserController.php, ProcessMaker/Http/Controllers/ProfileController.php, resources/views/admin/users/edit.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/users/profile.blade.php, tests/Feature/Api/UsersTest.php
- Implement the same [solution](https://github.com/ProcessMaker/processmaker/pull/7463) for summer version 
https://github.com/user-attachments/assets/2a1c851e-6d0e-4b23-a70c-1632d97227f8
See the ticket
[FOUR-20103](https://processmaker.atlassian.net/browse/FOUR-20103)
[FOUR-20103]: https://processmaker.atlassian.net/browse/FOUR-20103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20103 confirm identity validation does not work when email field is updated

resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/views/cases/edit.blade.php
2. Create a case
3. Open the case 
4. Click on : (Overview | Completed & Form | File Manager)
5. Refresh the page with the route {{server}}/cases//{{number_case}}/{{route}}
6. Check the content after the refresh 
After refreshing the page, the selected option is not displayed, it always shows task by default 
- https://processmaker.atlassian.net/browse/FOUR-20010
ci:deploy
=> FOUR-20010: The link does not show the correct location after refreshing the page in Cases options

resources/js/processes/import/components/ImportPIModal.vue, resources/lang/en.json
- https://processmaker.atlassian.net/browse/FOUR-20094
- Added a message on error
- Added translation to `en.json`
- https://github.com/ProcessMaker/package-ai/pull/347
=> observation/FOUR-20094: Added error message for PI Process import modal

resources/js/components/PMDropdownSuggest.vue
The reassignment list user overlap the screen does not have scroll
Fixed the height and overflow of the reassign dropdown
To have many users
Add task
Configure the task with allow reassignment
Create a case
Open the task
Click on reassignment button
Check the user list
https://processmaker.atlassian.net/browse/FOUR-20116
=> observation/FOUR-20116 The reassignment list user overlap the screen does not have scroll

ProcessMaker/Http/Controllers/Api/ScreenController.php, ProcessMaker/Http/Controllers/CasesController.php, ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Http/Resources/ScreenVersion.php, ProcessMaker/Http/Resources/V1_1/TaskScreen.php, ProcessMaker/ProcessTranslations/ScreenTranslation.php, ProcessMaker/Traits/TaskResourceIncludes.php
Ticket: [FOUR-20013](https://processmaker.atlassian.net/browse/FOUR-20013)
When a cancelled Request with a configured 'Cancel Screen' is opened, an 'Undefined array key `screen_id`' error is shown.
- It is observed that the applyTranslations function parameter needs to be normalized and ScreenVersions used for all calls.
1. Go to branch `observation/FOUR-20013` in `processmaker`.
2. Go to Designer → Screens. Create a Display Screen.
3. Go to Designer → Processes. Create a Process.
4. Configure your Screen as the 'Cancel Screen'.
5. Add a Start Event, Task, and End Event to the Process. Configure the Task. (It does not matter what Screen is used for the Task.)
6. Start a Case.
7. Cancel the Case.
8. Open the Request.
- The 'Cancel Screen' should display in the Request Summary. There should …
=> FOUR-20013: Apply Translation Error When a ‘Cancel Screen’ is Configured

ProcessMaker/Http/Middleware/GenerateMenus.php
Script executors option is not displayed in the left sidebar
- Restore the `Script executors` option in the sidebar
See the ticket
[FOUR-20158](https://processmaker.atlassian.net/browse/FOUR-20158)
[FOUR-20158]: https://processmaker.atlassian.net/browse/FOUR-20158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20158 script executors option is not displayed in the left sidebar

resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/ErrorsTab.vue, resources/jscomposition/cases/casesDetail/variables/index.js
When the case has an error, the Error tab should appear and display the errors detected.
If the Case has more than  one Request, it should show all the errors like actually does when you open the request:
- https://processmaker.atlassian.net/browse/FOUR-20108
ci:deploy
=> FOUR-20108:Review estimate the errors tab is no longer displayed in the case details

resources/views/requests/show.blade.php
Ticket: [FOUR-20060](https://processmaker.atlassian.net/browse/FOUR-20060)
When a Request Detail Screen is configured in a Process, users are unable to see the intended styling on completed Request Detail Screens due to missing custom CSS.
- Update the `screenRequestDetail` computed property in `/resources/views/requests/show.blade.php`. The property was only returning the `request_detail_screen.config`. Now it returns the `config` and the `custom_css`.
- Update the props passed to `vue-form-renderer` for Request Detail Screens
- `config` prop is now `screenRequestDetail.config`
- `custom-css` prop is now `screenRequestDetail.custom_css`
1. Go to branch `observation/FOUR-20060` in `processmaker`.
2. Go to Designer → Screens. Create a Screen with Custom CSS.
3. Go to Designer → Processes. …
=> FOUR-20060 | The Custom CSS Style Configured in the Request Detail Screen Is Not Rendering

ProcessMaker/Http/Controllers/Auth/LoginController.php, config/samlidp.php, tests/Feature/AuthTest.php
The logout flow was being aborted by a saml listener.
- Fix the logout flow.
- Configure SAML.
- Test login with SAML.
- Logout
- Verify the SAML logout also logs out from ProcessMaker
- Test login with normal ProcessMaker login
- Logout
- Verify the user log out
- https://processmaker.atlassian.net/browse/FOUR-20087
=> FOUR-20087 Fix logout flow

ProcessMaker/Console/Commands/TranslateEmptyStrings.php
This PR implements a command to translate missing strings with AI
The command allows you to translate all the empty strings for all the .json files found in resources/lang for **core** and **packages**.
You can also pass a parameter to translate a specific language using the language code.
The translations are performed in chunks of 100 elements.
**Translate for core and package all languages** 
`php artisan processmaker:translate-empty-strings`
**Translate for core and packages a specific language passing the language code (af for afrikaans)**
`php artisan processmaker:translate-empty-strings --lang=af`
**Verbosity**
To debug you can use the flag `--verbose`
=> Task/FOUR-20188: Add command to translate with AI

ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Models/Script.php
SDK does not allow sync=true parameter
- Add it
Script 1
```
return ['foo' => 'bar'];
```
Script 2
```
$response = $api->scripts()->executeScript(1, ['sync' => true]);
return ['response' => $response['output']];
```
Change the first argument to `executeScript` above to the Script 1 ID
Run Script 2 and ensure we get the response from script 1: `['response' => ['foo' => 'bar']];`
- https://processmaker.atlassian.net/browse/FOUR-17328
ci:deploy
=> Allow the SDK to get sync script responses

ProcessMaker/Http/Controllers/CasesController.php, ProcessMaker/Http/Controllers/RequestController.php, tests/Feature/RequestTest.php, tests/Fixtures/process_summary_screen_is_showed_when_the_request_is_completed.bpmn
Summary screen is not displayed (completed)
- Validate class summary screen
- Import the process upload
- Create a case
- Complete the request
- Open the Completed request
- [FOUR-20202](https://processmaker.atlassian.net/browse/FOUR-20202)
[FOUR-20202]: https://processmaker.atlassian.net/browse/FOUR-20202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Complete request is showing an error when has configured a Summary Screen

ProcessMaker/Http/Controllers/Auth/LoginController.php, ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/IgnoreMapFiles.php, config/samlidp.php, tests/Feature/AuthTest.php, tests/Feature/LoginRedirectTest.php
When user opens devtools, and the map files from frontend assets are missing (in public/), it causes ProcessMaker try to return a map file registering its URL as the intended URL when user tries to login.
- Ignore map files in ProcessMaker routes
- Open chrome devtools
- Without session, open a processmaker path like `/requests`
- Login
- Once fixed it will go to the `/requests` route
- https://processmaker.atlassian.net/browse/FOUR-20098
- Requires: https://github.com/ProcessMaker/processmaker/pull/7734
=> FOUR-20098 Fix redirect problem after login

ProcessMaker/Managers/PackageManager.php
the file gitignore not exists
- Verify if exists file
create a new language
- [FOUR-20248](https://processmaker.atlassian.net/browse/FOUR-20248)
[FOUR-20248]: https://processmaker.atlassian.net/browse/FOUR-20248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cannot add languages ​​in translations

database/migrations/2024_02_20_193849_create_task_drafts_table.php, database/migrations/2024_11_15_122455_add_index_to_task_id_column_for_task_drafts_table.php
- A new migration file was created to add the INDEX to task_id column in task_drafts table after this table is created. Notice this index was not added into create migration file for task_drafts table, because this table might already exist in some environments.
This INDEX was created following the suggestion in ticket mentioned below FOUR-17731.
- Verify indexes in table task_drafts in database before execute migrations command (there should not be Index for task_id column)
- Execute: php artisan migrate
- Verify a new INDEX called taskId was created for task_id column in task_drafts table
https://processmaker.atlassian.net/browse/FOUR-17731
=> bugfix/FOUR-17731: 39399 -Missing INDEX for task_drafts table

resources/js/components/AvatarImage.vue, resources/js/components/shared/FilterTableBodyMixin.js, resources/js/templates/components/ProcessTemplatesListing.vue
This PR resolves a regression where the default template author was incorrectly displayed as 'Unclaimed' instead of 'ProcessMaker'. The issue stemmed from the implementation of [FOUR-20005](https://processmaker.atlassian.net/browse/FOUR-20005), which inadvertently updated the 'ProcessMaker' label to 'Unclaimed'.
- Introduced a new flag, userDefaultPmLabel, to conditionally render the correct label.
- If `userDefaultPmLabel` is true, the label displays as 'ProcessMaker'.
- If `userDefaultPmLabel` is false and no user is assigned, the label defaults to 'Unclaimed'.
1. Ensure default process templates are available in your environment by running: 
`php artisan processmaker:sync-default-templates`
2. Navigate to Processes > Templates in the ProcessMaker UI.
3. Confirm that default templates …
=> Fix Default Template Author Display Regression

ProcessMaker/Repositories/CaseApiRepository.php, tests/Feature/Api/V1_1/CaseControllerSearchTest.php
The cases list does not search correctly when the case_title has an underscore
- Accept underscores on case_title for the FullText search
See the ticket
[FOUR-20218](https://processmaker.atlassian.net/browse/FOUR-20218)
[FOUR-20218]: https://processmaker.atlassian.net/browse/FOUR-20218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20218 the cases list does not search correctly when the case_title has an underscore

tests/Feature/Screens/ScreenCompiledManagerTest.php
…dding Cache
As a developer I want to improve test coverage for tests/Feature/Screens/ScreenCompiledManagerTest.php test
- refactor get key test
- add exception tests
- add empty compile content test
- add clear assets when the directory does not exist
run the next command s
`
// run the test
php artisan test --filter=ScreenCompiledManagerTest
// check coverage
vendor/bin/phpunit --coverage-html coverage-report tests/Feature/Screens/ScreenCompiledManagerTest.php
`
- https://processmaker.atlassian.net/browse/FOUR-20912
=> FOUR-20912:  Enhance Test Coverage for Screens Functionality Before Adding Cache

tests/Feature/Api/SettingAuthTest.php, tests/Feature/Api/SettingLogInOptionsTest.php, tests/Feature/Api/SettingSessionControlTest.php
Complete the Test coverage of Settings by adding at least the following one:
- Security Logging: Testing the security logging functionality when changing Settings
- Format Handling: Testing different data format support (could be saml or email,…)
- Validation: Fix, update or remove the skipped tests
- Add missing tests for core settings
- Add missing tests for security logs when a setting is updated
- Add missing tests for setting formats
- Run `php artisan test --filter 'SettingLogInOptionsTest|SettingSessionControlTest|SettingAuthTest'`
[FOUR-20504](https://processmaker.atlassian.net/browse/FOUR-20504)
[FOUR-20504]: https://processmaker.atlassian.net/browse/FOUR-20504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20504 enhance test coverage for settings functionality before adding cache

ProcessMaker/Http/Controllers/Api/SecurityLogController.php, tests/Feature/Api/SecurityLogControllerTest.php
ApiCollection class is getting all records in order to count the records.
The count is made using the query object instead the ApiCollection class.
1. Go to API SWAGER: https:/<server>/api/documentation#/Security%20Logs/getSecurityLogs 
2. Go to Authorize and paste the Bearer Token attached.
3. Select SecurityLogs
4. Select GET /security-logs  Returns all security logs
5. Set the parameters per_page to 100 or 10
6. Or use postman and test the same API
https://processmaker.atlassian.net/browse/FOUR-18935
=> FOUR-18935 Ecobank - ERROR 404 ON SECURITY LOGS SWAGGER

ProcessMaker/Filters/BaseFilter.php, ProcessMaker/Traits/TaskControllerIndexMethods.php
No process name filter exists in the backend for process name (only for Case name)
- Add the process name filter
- Fix one other issues where a query should be 'and' instead of 'or'
- Remove the "Reassign" button since it does not work on that page
See jira issue
- https://processmaker.atlassian.net/browse/FOUR-20045
- Requires: https://github.com/ProcessMaker/package-savedsearch/pull/487
ci:package-savedsearch:bugfix/FOUR-20045
=> 20045 - Fix process name filter in "Processes I Manage"

ProcessMaker/Jobs/RunServiceTask.php, tests/TestCase.php
Wrong modifying exception messages in RunServiceTask
- Improve modifying exception messages in RunServiceTask.
- https://processmaker.atlassian.net/browse/FOUR-20266
=> FOUR-20266 Improve modifying exception messages in RunServiceTask

.cursorrules, ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php, config/l5-swagger.php, routes/v1_1/api.php, tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
- tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
- GET /api/1.1/processes/variables?processIds=1,2,3
- https://processmaker.atlassian.net/browse/FOUR-20526
=> FOUR-20526 Define Swagger Schema for Server Service 

ProcessMaker/Enums/ExporterMap.php
devLink > Server error message is displayed when a Collection is downloaded
Added the collection model to the exporterMap
The two servers must have the solution
Go to server A
Create Collection
Go to admin > devlink > Shared Assets
check collection option
Go to server B 
Go to Admin > devlink > linked instances
Press Add instance button and connect with the server A
Select the instances
Select Assets tab
Press View button in the Collection
Select a collection
Press cloud download icon
Press ok button
https://processmaker.atlassian.net/browse/FOUR-21138
=> observation/FOUR-21138 devLink > Server error message is displayed when a Collection is downloaded

database/seeders/PermissionSeeder.php, tests/Feature/Api/PermissionsTest.php, upgrades/2024_11_28_154502_assign_user_permission_view_my_request.php
The users needs to have per default the permissions "View My Request"
1. Have a server with users
2. Apply the version 4.12
3. All the old users needs to have the permission “View My Request“ enable per default
Execute the command
`php artisan upgrade`
- https://processmaker.atlassian.net/browse/FOUR-21130
ci:deploy
=> FOUR-21130: The users needs to have per default the permissions "View My Request"

ProcessMaker/Cache/Screens/LegacyScreenCacheAdapter.php, ProcessMaker/Cache/Screens/ScreenCacheFacade.php, ProcessMaker/Cache/Screens/ScreenCacheFactory.php, ProcessMaker/Cache/Screens/ScreenCacheInterface.php, ProcessMaker/Cache/Screens/ScreenCacheManager.php, ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php, config/screens.php, tests/Feature/Api/V1_1/TaskControllerTest.php, tests/unit/ProcessMaker/Cache/Screens/LegacyScreenCacheAdapterTest.php, tests/unit/ProcessMaker/Cache/Screens/ScreenCacheFactoryTest.php, tests/unit/ProcessMaker/Cache/Screens/ScreenCacheManagerTest.php
- Create screen cache manage
- Create screen cache factory
- add screen cache facade
- create legacy screen adapter
- run 
`php artisan test`
- https://processmaker.atlassian.net/browse/FOUR-20911
=> FOUR-20911: Caching Screens

ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php, tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
- Use Virtual Scrolling to optimize page loading time
- Load more items in background so user can find more variables
- Mock new endpoint to get variables
https://github.com/user-attachments/assets/d5f7271d-7910-4c33-816d-65046527a6ce
- https://processmaker.atlassian.net/browse/FOUR-20521
ci:package-savedsearch:FOUR-20521
=> FOUR-20521 [ACTIVE COLUMNS] Optimize Rendering with Virtual Scrolling 

ProcessMaker/Http/Middleware/Etag/HandleEtag.php, ProcessMaker/Http/Resources/Caching/EtagManager.php, ProcessMaker/Http/Resources/V1_1/TaskResource.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, ProcessMaker/Providers/RouteServiceProvider.php, ProcessMaker/Traits/TaskResourceIncludes.php, routes/api.php, routes/engine.php, routes/v1_1/api.php, tests/Feature/Etag/HandleEtagTest.php
This PR implements ETag caching for all GET and HEAD requests, enhancing performance and reducing bandwidth usage by leveraging HTTP conditional requests. The middleware is now applied globally, ensuring consistent ETag handling across endpoints.
1. Global ETag Middleware:
- Applied the ETag middleware to all GET API requests to ensure consistency and avoid redundant implementation for individual routes.
- Middleware calculates and validates ETags based on the response or a configurable sources of truth (optional).
2. Exclude active_at Field:
- Removed the active_at field from TaskResource and requestor serialization to prevent ETag inconsistencies.
3. Introduce Configurable ETag Source:
- updated_at: Default method using database timestamps to determine the latest update for relevant …
=> FOUR-20944: Implement ETag Caching for Task and Case Data

ProcessMaker/Cache/Settings/SettingCacheManager.php, ProcessMaker/Observers/SettingObserver.php, tests/Feature/Cache/SettingCacheTest.php
Invalidate Cache on Event
- Add `invalidate` method to `SettingCacheManager`
[FOUR-20909](https://processmaker.atlassian.net/browse/FOUR-20909)
[FOUR-20909]: https://processmaker.atlassian.net/browse/FOUR-20909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20909 invalidate cache on event

devhub/pm-font/svg/expand.svg, devhub/pm-font/svg/minimize.svg
Ticket: [FOUR-20786](https://processmaker.atlassian.net/browse/FOUR-20786)
This PR introduces UI Updates to the VarFinder panel, adding:
- Search bar to Filter through Latest Assets
- List view for Latest Assets
- Assets can be expanded to display variables
- Users can 'Show All Variables' or 'Show Less'
- 'Collapse All' button to collapse expanded Assets
- 'Jump Back Up' button to scroll back to the top of the Assets and Variables list.
1. Go to branch `task/FOUR-20786` in `processmaker` and in `package-variable-finder`.
2. From any screen, click 'Cmd + Shift + v' to open the VarFinder panel.
3. There should be a search bar and a list of Latest Assets in the VarFinder panel.
- Click on the arrow beside all of the Assets to expand and see Variables
4. Click on the 'Show All Variables' …
=> FOUR-20786 | Create a Layout to Display the 5 Most Recently Edited Assets

ProcessMaker/Events/SessionStarted.php, ProcessMaker/Http/Controllers/Auth/LoginController.php, ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/VerifyActiveSession.php, routes/api.php
Follow the instructions in the video "Screen Recording on 2024-12-03 at 12-00-33.mp4" of the ticket https://processmaker.atlassian.net/browse/FOUR-16704
- Cache de status of logged in/logged out of a user
https://processmaker.atlassian.net/browse/FOUR-16704
- Login/logout in one device --> OK
- Login/logout in multiple devices --> OK
- Socialite authentication (used SAML) --> OK
- Endpoint called using Postman or similar -> OK
ci:deploy
=> FOUR-16704: Session Token Not Invalidated on Logout (for version 4.11.6)

ProcessMaker/Http/Controllers/CasesController.php, ProcessMaker/Http/Controllers/RequestController.php, ProcessMaker/Traits/ProcessMapTrait.php, resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/NewOverview.vue, resources/jscomposition/cases/casesDetail/variables/index.js, resources/views/cases/edit.blade.php, resources/views/requests/show.blade.php
Implement the perfomance In-flight in Request and Cases
[FOUR-20534](https://processmaker.atlassian.net/browse/FOUR-20534)
ci:deploy
[FOUR-20534]: https://processmaker.atlassian.net/browse/FOUR-20534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20534: Implement the perfomance In-flight in Request and Cases

ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/ServerTimingMiddleware.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, ProcessMaker/Traits/PluginServiceProviderTrait.php, tests/Feature/ServerTimingMiddlewareTest.php
As a developer, I want to add support for Server Timing headers in the API responses so that we can collect and view detailed timing information for requests directly in the browser and in LogRocket.
- Add Service Provider timing execution
- Add DB query timing execution
- Add Controller timing execution
- Add Package Service Provider timing execution
[FOUR-20462](https://processmaker.atlassian.net/browse/FOUR-20462)
[FOUR-20462]: https://processmaker.atlassian.net/browse/FOUR-20462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20462 add support for server timing headers

resources/js/requests/show.js, resources/jscomposition/cases/casesDetail/components/MapLegend.vue, resources/jscomposition/cases/casesDetail/components/NewOverview.vue
Review the general status of the process
- Implement the general status 
- https://processmaker.atlassian.net/browse/FOUR-20544
=> FOUR-20544: Review the general status of the process

resources/js/components/shared/FilterTableBodyMixin.js, resources/js/processes/screens/components/ScreenListing.vue, resources/js/processes/scripts/components/ScriptListing.vue
When assigning two categories to screens/scripts/decision tables the category disappears
- Add a callback to display all assigned categories
https://github.com/user-attachments/assets/a767fef4-ee56-4d48-a5e9-178616822639
[FOUR-21125](https://processmaker.atlassian.net/browse/FOUR-21125)
https://github.com/ProcessMaker/package-decision-engine/pull/148
https://github.com/ProcessMaker/package-data-sources/pull/375
[FOUR-21125]: https://processmaker.atlassian.net/browse/FOUR-21125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-21125 When assigning two categories to screens/scripts/decision tables the category disappears

ProcessMaker/Console/Commands/RevokeOauthAccessTokens.php
Please see the description in the ticket: https://processmaker.atlassian.net/browse/FOUR-21198
This pull request introduces a new console command `RevokeOauthAccessTokens` to the ProcessMaker application. The command is designed to revoke OAuth access tokens based on specified criteria.
`php artisan processmaker:revoke-oauth-access-tokens {--name=} {--after=} {--client_id=} {--no-interaction|-n}`
- `--name=`: Specify the name(s) of the token(s) to revoke. Multiple names can be separated by commas.
- `--after=`: Revoke tokens created after a specified date. The date should be in `Y-m-d` format.
- `--client_id=`: Specify the client ID(s) associated with the tokens to revoke. Multiple client IDs can be separated by commas.
- `--no-interaction|-n`: Run the command without any interactive …
=> Task/FOUR-21198: Create command to revoke specified API tokens

ProcessMaker/Http/Middleware/ServerTimingMiddleware.php, ProcessMaker/Providers/ProcessMakerServiceProvider.php, ProcessMaker/Traits/PluginServiceProviderTrait.php, config/app.php
As a support agent, I want to view the Server Timing headers in LogRocket, So that I can analyze detailed timing information for API requests when investigating performance issues reported by users.
- Improve the Server Timing headers
- Ensure the Server Timing headers are displayed in LogRocket
[FOUR-20464](https://processmaker.atlassian.net/browse/FOUR-20464)
[FOUR-20464]: https://processmaker.atlassian.net/browse/FOUR-20464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-20464 view server timing data in LogRocket

ProcessMaker/Http/Resources/Caching/EtagManager.php, tests/Feature/Etag/HandleEtagCacheInvalidationTest.php, tests/Feature/Etag/HandleEtagTest.php
This PR adds a test to ensure that cache invalidation works correctly for routes using the etag middleware with the etag_tables configuration. The existing functionality correctly handled ETag generation and cache invalidation, but there was no explicit test coverage for the scenarios where changes in updated_at in the specified tables should trigger cache invalidation.
1. Define a route using the etag middleware and specify etag_tables in the route’s defaults.
2. Perform an initial request to retrieve the ETag.
3. Update the updated_at column in the database for the specified table.
4. Expect the ETag to change and invalidation to occur.
- Introduced a new test case to verify cache invalidation when the updated_at field in the specified tables changes.
- Ensured the test validates that …
=> FOUR-20950: Handle Cache Invalidation for ETags

ProcessMaker/Services/MetricsService.php, README.md, config/app.php, metrics/compose.yaml, metrics/prometheus/prometheus.yml, tests/unit/MetricsServiceTest.php
I already
- Set the namespace in the config (needed by cloudops)
- removed unused code
- updated the readme
- made grafana development docker compose anonymous (no username/password needed)
We need to
- Add the logic to MetricService to support Metrics::counter and Metrics::guage (and histogram the same way)
- Use the metric name (first argument) as the 2nd argument (description) if not provided
- Use config('app.prometheus_namespace') to set the namespace
- use the library’s getOrRegister*** methods
- Remove any additional unused code
https://processmaker.atlassian.net/browse/FOUR-21074
=> Update readme and add namespace config

ProcessMaker/Http/Middleware/Etag/HandleEtag.php, config/etag.php, docs/etag-caching.md, tests/k6/etag/config.js, tests/k6/etag/detect-dynamic-endpoints.js, tests/k6/etag/long-duration-test.js, tests/k6/etag/performance-test.js
This PR adds metric tests using K6 to validate the performance and stability of the implemented ETag caching middleware.
- Introduced K6 tests to measure ETag middleware efficiency:
- Dynamic Endpoint Detection: Identifies endpoints where caching is not applicable.
- Performance Test: Measures average response time for endpoints under load.
- Long Duration Test: Evaluates response time stability and error rate during prolonged usage.
- Tests are located in `tests/k6/etag/`.
Add an API token in tests/k6/etag/config.js and run the following command:
```
k6 run tests/k6/etag/detect-dynamic-endpoints.js
k6 run tests/k6/etag/performance-test.js
k6 run tests/k6/etag/long-duration-test.js
```
- [FOUR-20954](https://processmaker.atlassian.net/browse/FOUR-20954)
[FOUR-20954]: …
=> FOUR-20954: Monitor ETag Caching Performance

resources/jscomposition/cases/casesDetail/components/NewOverview.vue
1. Create a case
2. Open the case
3. Go to overview
4. Select one element of the process
5. Go to Summary
6. Return to overview
When we return to overview the second time is possible to move the elements
- https://processmaker.atlassian.net/browse/FOUR-21372
=> FOUR-21372:We can move the elements of the process in the Request - Overview

ProcessMaker/Http/Controllers/TaskController.php, ProcessMaker/Traits/HasScreenFields.php, tests/unit/ProcessMaker/HasScreenFieldsTest.php
Improve screen cache usage.
- https://processmaker.atlassian.net/browse/FOUR-21383
- https://processmaker.atlassian.net/browse/FOUR-21379
=> FOUR-21383 Improve screen cache usage 

ProcessMaker/Http/Middleware/ServerTimingMiddleware.php
Add boot timing to Server-Timing header
- https://processmaker.atlassian.net/browse/FOUR-21382
=> FOUR-21382 Add boot timing to Server-Timing header

ProcessMaker/Traits/TaskControllerIndexMethods.php, resources/js/tasks/components/ListMixin.js, resources/js/tasks/components/ParticipantHomeScreen.vue
- After user logs in PM4, new Participant Home Screen Inbox will show Tasks related to Last Process.
- When User clicks on INBOX button, all tasks will be shown
- Login PM4
- Check in tasks list only for tasks related to last process
https://processmaker.atlassian.net/browse/FOUR-20300
=> Feature/FOUR-20300: Inbox in Home Page - Implement General Inbox features-part 1

ProcessMaker/Http/Controllers/Api/UserController.php, tests/Feature/Api/UsersTest.php
Create a new Api to save, update and delete the configurations per user
- We will use the following API to Save and Get filters for the cases lists:
```
users/store_filter_configuration/casesFilter
users/store_filter_configuration/casesFilter|in_progress
users/store_filter_configuration/casesFilter|completed
users/store_filter_configuration/casesFilter|all
```
```
GET users/get_filter_configuration/{name}
PUT users/store_filter_configuration/{name}
```
- https://processmaker.atlassian.net/browse/FOUR-20590
=> FOUR-20590: Create a new Api to save, update and delete the configurations per user

ProcessMaker/Models/User.php, database/migrations/2025_01_09_210416_add_email_task_notification_to_users_table.php
Create a migration to add a new column in the table users
- https://processmaker.atlassian.net/browse/FOUR-20688
ci:processmaker-bpmn-moddle:release-2024-fall
=> FOUR-20688: Create a migration to add a new column in the table users

resources/js/processes/modeler/components/inspector/TaskInterstitial.vue, resources/js/processes/modeler/initialLoad.js
When "Next Assigned Task" is selected, the "Screen Interstitial" option appears.
- Add the Next Assigned Task  option to element destination
https://github.com/user-attachments/assets/5e7ccf8d-8a12-4ea5-9cf0-62de3032e63c
- create a new process
- add a task or manual task
- select the task
- open the inspector
- go to element destination
- Select Next AssignedTask
- https://processmaker.atlassian.net/browse/FOUR-20487
=> FOUR-20487: Display "Screen Interstitial" Option

ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Repositories/TokenRepository.php, database/migrations/2025_01_10_183851_add_is_emailsent_column_for_process_request_tokens_table.php
Create a new column to know if an email was sent
- https://processmaker.atlassian.net/browse/FOUR-20673
ci:deploy
=> FOUR-20673: Create a new column to know if an email was sent

ProcessMaker/Cache/Monitoring/CacheMetricsDecorator.php, ProcessMaker/Cache/Monitoring/CacheMetricsInterface.php, ProcessMaker/Cache/Monitoring/PrometheusMetricsManager.php, ProcessMaker/Cache/Monitoring/RedisMetricsManager.php, ProcessMaker/Cache/Screens/ScreenCache.php, ProcessMaker/Contracts/PrometheusMetricInterface.php, ProcessMaker/Facades/Metrics.php, ProcessMaker/Jobs/CompleteActivity.php, ProcessMaker/Models/Screen.php, ProcessMaker/Models/ScreenVersion.php, ProcessMaker/Models/Setting.php, ProcessMaker/Services/MetricsService.php, ProcessMaker/Traits/HasScreenFields.php, tests/Feature/Metrics/TaskMetricsTest.php, tests/unit/ProcessMaker/Cache/Monitoring/CacheMetricsDecoratorTest.php
- https://processmaker.atlassian.net/browse/FOUR-21032
ci:processmaker-bpmn-moddle:release-2024-fall
=> FOUR-21032 Task Execution Time Metrics Collection

ProcessMaker/Casts/MillisecondsToDateCast.php, ProcessMaker/Listeners/BpmnSubscriber.php, ProcessMaker/Models/ProcessRequestToken.php, ProcessMaker/Observers/ProcessRequestTokenObserver.php, README.md, database/migrations/2025_01_13_212522_add_timestamps_ms_to_process_request_tokens_table.php, resources/grafana/MainDashboard.json
- https://processmaker.atlassian.net/browse/FOUR-21035
=> FOUR-21035 Implement Task Execution Time by Customer

resources/grafana/MainDashboard.json
- https://processmaker.atlassian.net/browse/FOUR-21037
=> FOUR-21037 Summary Charts for Task Execution

ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php, tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
https://github.com/user-attachments/assets/767f75e3-e4d3-4432-8b99-c11635e91c5d
- https://processmaker.atlassian.net/browse/FOUR-21522
ci:package-savedsearch:FOUR-21522
=> FOUR-21522 Fix Get variable list without VarFinder package was not implemented

ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php, tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
Default Columns not being listed in the available columns
- Get process variables including available columns
[FOUR-21495](https://processmaker.atlassian.net/browse/FOUR-21495)
https://github.com/ProcessMaker/package-savedsearch/pull/500
ci:package-savedsearch:FOUR-21495
ci:package-variable-finder:epic/FOUR-20417
[FOUR-21495]: https://processmaker.atlassian.net/browse/FOUR-21495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-21495 default columns not being listed in the available columns

resources/lang/en.json
- Create a new screen
- Use the Select List component in the screen
- Configure the aria-label in Advanced property
The same aria-label is repeated for each option in the Select List. This is causing that the screen readers for disabilities reads the label question every time. This behavior is unexpected for the customer.
ProcessMaker should allow configure the aria-label for each option in the aria-label property. One for the label and one for each option in the Select List component for the screen readers.
- Added area label option for checkbox renderAs mode, for provide data, request data, data connectors and collections.
- [FOUR-19875](https://processmaker.atlassian.net/browse/FOUR-19875)
- …
=> Task/FOUR-19875: aria-label property is the same in all options in the select list component generating unexpected behaviors for screen readers

resources/js/processes/designer/Assets.vue, resources/js/processes/designer/RecentAssets.vue
This PR implements https://processmaker.atlassian.net/browse/FOUR-20032
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/7706)
- [Package Projects PR](https://github.com/ProcessMaker/package-projects/pull/155)
=> Task/FOUR-20032-fall: Hide FlowGenie from Ellucian's servers

resources/views/tasks/edit.blade.php
Data tab was not updating when a task changed
- Call the function that initializes data after the task changes
See Jira issue
- https://processmaker.atlassian.net/browse/FOUR-21203
=> Reload the data tab when the task changes

ProcessMaker/Http/Controllers/Admin/UserController.php, ProcessMaker/Http/Controllers/ProfileController.php
A modal is displayed to validate the changes and save the email field by password confirmation. The issue is caused by the users synchronized by AD or SAML not having a known password.
- Checks for SAML and LDAP users on email update
See the ticket
[FOUR-21445](https://processmaker.atlassian.net/browse/FOUR-21445)
[FOUR-21445]: https://processmaker.atlassian.net/browse/FOUR-21445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-21445 email field cannot be updated for users imported from AD or SAML

ProcessMaker/Http/Controllers/Api/TemplateController.php, ProcessMaker/Models/Template.php
Users are unable to create processes from guided templates. Upon selecting a template, the process creation flow fails. This issue is observed in version 4.12.0 and did not occur in previous versions.
- Navigate to the Designer/Processes.
- Select Guide Template from the available options.
- Attempt to create a new process using any of the available guided templates.
- Restore the Template::rules
- Expand the description field to allow more than 100 characters to ensure that  [FOUR-20102](https://processmaker.atlassian.net/browse/FOUR-20102) is also resolved.
Please follow the Steps to Reproduce and ensure that the Guided Template is fully generated and functioning as expected.
- Ticket: https://processmaker.atlassian.net/browse/FOUR-21290
[FOUR-20102]: …
=> FOUR-21290: Fix Unable to Create Processes from Guided Templates

resources/js/bootstrap.js, resources/js/components/Session.vue, resources/js/timeout.js
1. Log in into the lastest version of ProcessMaker 4 (4.9.3)
2. Go to Admin Section
3. Go to Settings
4. Set “Session Inactivity“ to 5 minutes
5. Now, go to Designer
6. Import the Process “TestMB“
7. Open a new request TestMB
In this case, at the moment of filling out the form, a "Session Warning" message appears, and I attach a reference video of the process:
- https://processmaker.atlassian.net/browse/FOUR-15298
ci:deploy
=> FOUR-15298: [37189] Session Inactivity Option

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/base/table/TCell.vue, resources/jscomposition/base/table/THeader.vue, resources/jscomposition/base/table/composables/columnComposable.js, resources/jscomposition/cases/casesDetail/components/TaskTable.vue, resources/jscomposition/cases/casesDetail/config/columns.js, resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/cases/casesMain/config/columns.js, resources/jscomposition/system/table/FilterableTable.vue, resources/jscomposition/system/table/SortTable.vue
- https://processmaker.atlassian.net/browse/FOUR-20598
ci:deploy
=> FOUR-20598: Horizontal adaptation define a minimum width of the columns

ProcessMaker/Mail/TaskActionByEmail.php, ProcessMaker/Repositories/TokenRepository.php, database/processes/screens/default-email-task-notification.json, database/seeders/ScreenSystemSeeder.php
Send an email when the task and taskManual has an assignee and the toogle in users is enable and register
- https://processmaker.atlassian.net/browse/FOUR-20680
ci:deploy
=> FOUR-20680: Send an email when the task and taskManual has an assignee and the toogle in users is enable and register

ProcessMaker/Http/Controllers/Api/ScriptExecutorController.php, ProcessMaker/Models/Script.php, ProcessMaker/Models/ScriptExecutor.php
Hide deprecated languages and prevent saving new scripts and executors
- Ensure R and LUA are not available in lists of available languages
- Ensure you can not save new scripts or executors that attempt to use them
- https://processmaker.atlassian.net/browse/FOUR-21490
=> FOUR-21490 - Hide Lua and R Script Executors

composer.json
For local development on mac, you may need to:
- `valet use 8.3` or the herd equivalent
- `brew install librdkafka`
- `sudo pecl install rdkafka`
- Specify the library path from the brew install command. In my case it was `/opt/homebrew/Cellar/librdkafka/2.8.0`
- `sudo pecl install redis` You can use all default options
- `brew tap kabel/php-ext && brew install php@8.3-imap`
- Finally, `valet restart` and restart horizon
ci:k8s-branch:fall-php83
...
=> FOUR-21469 - Upgrade to php 8.3

resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/cases/casesMain/components/BadgesSection.vue, resources/jscomposition/cases/casesMain/config/columns.js, resources/jscomposition/system/table/FilterableTable.vue, resources/jscomposition/system/table/filter/defaultFilter/FilterColumn.vue, resources/lang/en.json, resources/lang/es.json
- https://processmaker.atlassian.net/browse/FOUR-20639
ci:deploy
=> FOUR-20639: S7: Add a Reset Table in the modal

ProcessMaker/Enums/ScriptExecutorType.php, ProcessMaker/Events/ScriptResponseEvent.php, ProcessMaker/Http/Controllers/Api/ScriptController.php, ProcessMaker/Http/Controllers/Api/ScriptExecutorController.php, ProcessMaker/Jobs/RunScriptTask.php, ProcessMaker/Jobs/TestScript.php, ProcessMaker/Models/Script.php, ProcessMaker/Models/ScriptExecutor.php, ProcessMaker/Models/ScriptExecutorVersion.php, ProcessMaker/Models/ScriptVersion.php, ProcessMaker/ScriptRunners/Base.php, ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php, ProcessMaker/ScriptRunners/ScriptRunner.php, ProcessMaker/Services/ScriptMicroserviceService.php, config/script-runner-microservice.php, database/migrations/2024_10_15_182703_add_type_column_to_script_executor_versions_table.php, database/migrations/2024_10_15_182703_add_type_column_to_script_executors_table.php, phpunit.xml, routes/api.php, tests/Feature/Api/ScriptsTest.php
Change class name of script microservice runner
Add config for microservice ruuner
Add callback route
Remove send first response in TestScript
Add version script in env file
Move callback to api
Implement script microservice in runscripttask.php
Remove config of script-runners
Adding type column to script executor table
Change int for bool to sync variable
fix composer.json file
Fix api environment variables
Fix script language capitalize
Fix null version field
Change output name in json callback
Remove json_decode in output response
Add script executor enabled flag
Rollback _fonts.scss file …
=> Implement script runner microservice

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/base/table/THeader.vue, resources/jscomposition/base/table/composables/columnComposable.js, resources/jscomposition/cases/casesMain/CasesDataSection.vue, resources/jscomposition/system/table/cell/CaseTitleCell.vue, resources/jscomposition/system/table/cell/LinkCell.vue, resources/jscomposition/system/table/cell/ParticipantsCell.vue, resources/jscomposition/system/table/cell/TruncatedColumn.vue, resources/jscomposition/system/table/cell/truncatedGroupOptionsCell/TruncatedGroupOptionsCell.vue, resources/jscomposition/system/table/filter/defaultFilter/FilterColumn.vue
- https://processmaker.atlassian.net/browse/FOUR-20635
- https://processmaker.atlassian.net/browse/FOUR-20634
ci:deploy
=> FOUR-20635: Ui update border of the table

config/broadcasting.php, resources/grafana/MainDashboard.json
- https://processmaker.atlassian.net/browse/FOUR-21018
=> FOUR-21018 Add Script Task Completion Time series to MainDashboard

tests/Feature/Api/UsersTest.php, tests/Feature/TaskControllerTest.php, tests/Fixtures/email_task_notification_process.bpmn
Create the PHP Unit test
- https://processmaker.atlassian.net/browse/FOUR-20687
ci:connector-docusign:release-2024-fall
ci:package-webentry:release-2024-fall
=> FOUR-20687: Create the PHP Unit test

ProcessMaker/Jobs/ErrorHandling.php, ProcessMaker/Jobs/RunScriptTask.php, ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php, ProcessMaker/Traits/TaskControllerIndexMethods.php
See https://processmaker.atlassian.net/browse/FOUR-21497
Note this PR also fixes a unit test failure in core where the query [condition parentheses](https://github.com/ProcessMaker/processmaker/commit/9c4e5cd955ffb8be3dd56ce641ef08645a3aa3e4#diff-b5b31261a18689534ed57c3753fdb2dca3348d12d6ff51fbd3eb1a4fabb85a46R164-R168) were not correct. This did not surface as a failure until [a different change](https://github.com/ProcessMaker/processmaker/commit/9e9f638008e7aeade79801f70696d83c6283af3f#diff-ea22510c52122a86c40e9d839b6baeda845a03ffcb64d9c4d90afdbb428f1ec7R152-R153) was merged.
=> Fix retries and run microservice requests synchronously

composer.json, resources/views/admin/auth-clients/index.blade.php, resources/views/admin/groups/edit.blade.php, resources/views/admin/groups/index.blade.php, resources/views/admin/users/edit.blade.php, resources/views/admin/users/list.blade.php, resources/views/auth/passwords/change.blade.php, resources/views/categories/list.blade.php, resources/views/processes/edit.blade.php, resources/views/processes/environment-variables/edit.blade.php, resources/views/processes/screens/edit.blade.php, resources/views/processes/scripts/edit.blade.php, resources/views/processes/signals/edit.blade.php, resources/views/processes/signals/index.blade.php, resources/views/profile/edit.blade.php, resources/views/shared/input.blade.php, resources/views/shared/users/profile.blade.php, resources/views/shared/users/sidebar.blade.php, resources/views/tasks/edit.blade.php, resources/views/templates/configure.blade.php
This pull request includes the changes for migrating from the `laravelcollective/html` package to the `spatie/laravel-html` package. Feel free to commit any additional changes to the `shift-138348` branch.
**Before merging**, you need to:
- Checkout the `shift-138348` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, try with `--no-scripts`)
- Clear any view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))
If you need help with your migration, check out the [Human Shifts](https://laravelshift.com/human-shifts).
=> Migrate to `spatie/laravel-html`

resources/js/components/shared/LaunchpadSettingsModal.vue
1. Create process
2. Go to Launchpad button
3. See the modal
4. Publish the process
5. Click again in the Launchpad button
After publish the process the Launchpad button needs to redirect to launchpad
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-21508)
ci:deploy
ci:modeler:bugfix/FOUR-21508
=> FOUR-21508:When I publish the process the launchpad button is showing the modal

ProcessMaker/Http/Controllers/TemplateController.php, resources/js/components/shared/ellipsisMenuActions.js, resources/js/processes/screen-templates/mixins/navigationMixin.js, resources/views/processes/screen-builder/showTemplate.blade.php, routes/web.php
Ticket: [FOUR-21667](https://processmaker.atlassian.net/browse/FOUR-21667)
When right-clicking on the "Edit Template" link within the Ellipsis Menu for Screen Templates (located on both "My Templates" and "Shared Templates" listing pages), the link incorrectly redirects to the Screens listing page instead of the Screen Builder. This prevents users from editing templates in a new browser tab.
- Add `screen-template/{id}/edit` web route that opens a Screen Template in Screen Builder
- Add href link to the new route in `ellipsisMenuActions.js`
- Remove `goToScreenBuilder()` method used in `navigationMixin.js`
1. Go to branch `bugfix/FOUR-21667` in `processmaker`.
2. Ensure you have Screen Templates in your environment.
3. Go to Designer → Screens → My Templates.
- Open the Ellipsis Menu and …
=> FOUR-21667 |  "Edit Template” Link for Screen Templates Does Not Redirect to Edit Page in Screen Builder

resources/js/processes/screen-templates/components/PublicTemplatesListing.vue
Resolves an issue where screen templates without an owner displayed 'unclaimed' instead of the default 'ProcessMaker' text.
The screen template listing page was using the default **datatable.js** `transform` method which had `usePmDefaultLabel` set to `false`. This caused ownerless templates to display as 'unclaimed' instead of the desired default text 'ProcessMaker'.
- Added a custom `transform` method in the screen template listing component
- Enabled `usePmDefaultLabel` property to ensure proper owner text formatting
1. Populate the 'Shared Templates' tab:
```
php artisan processmaker:sync-screen-templates
```
2. Navigate to Designer > Screens > Shared Templates tab
3. Verify the 'Owner' column displays correctly
**Expected Results**
- Screen templates without an assigned owner should …
=> Fix Screen Template Owner Display

ProcessMaker/Repositories/TokenRepository.php, package-lock.json
Errors when creating a new case in the branch feature/FOUR-20332:
Carbon\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in /Users/user/srv/http/processmaker4/vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 356
https://processmaker.atlassian.net/browse/FOUR-21688
=> FOUR-21688 Wrong argument when starting a new case

ProcessMaker/Http/Controllers/Api/DevLinkController.php, resources/js/admin/devlink/components/BundleSettingsModal.vue, resources/js/admin/devlink/components/CreateDevLinkModal.vue, resources/js/admin/devlink/components/Index.vue
Add clear user errors for Instance connections
changed the create devlink front end to handle connection errors
https://processmaker.atlassian.net/browse/FOUR-20314
=> feature/FOUR-20314 Add clear user errors for Instance connections

resources/js/components/AvatarImage.vue, resources/js/components/shared/FilterTableBodyMixin.js, resources/js/processes/components/ProcessMixin.js
- Fixed Column Owner in Processes List
-Go to server: https://release-2024-fall-qa.processmaker.net/
-ProcessMaker Platform Winter 2025 Version 4.12.2 (Build #2c11d2de)
Server A
-Create a new user (e.g. user_id = 123) (this user needs all permissions to create processes)
- login with new user and create a process
- Export a process
Server B (no user should exist with a user_id = 123)
- Go to Processes page
- Import the process
- Go to Process page
- Search the imported process
- Column Owner should show "ProcessMaker" instead of "Unclaimed"
https://processmaker.atlassian.net/browse/FOUR-21504
=> Bugfix/FOUR-21504: Owner default name is not displayed in the Processes page

resources/js/processes/screen-builder/typeForm.js
The field assigned to display the data of the select list is not shown from the web entry.
- Register the `multiselect` component in screen builder
1. Create a screen with a select list
2. Create a simple process
3. Enable web entry
4. Assign the screen created with the select list to the web entry
5. Save the process
6. Copy the URL and paste it into another window
[FOUR-21631](https://processmaker.atlassian.net/browse/FOUR-21631)
[FOUR-21631]: https://processmaker.atlassian.net/browse/FOUR-21631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-21631 select list does not show the field assigned to its data in web entry

resources/js/processes/screen-builder/screen.vue, resources/js/tasks/edit.js, resources/views/tasks/edit.blade.php
1. Import the attached screen file.
2. Preview the screen.
3. Navigate to the second page of the screen.
When the customer builds a button in a form that navigates to a new screen, the following page opens at the same point where the previous page was left off. This means the subsequent page opens about halfway down.
The new page should open from the top, not at the same point where the previous page was left off.
- https://processmaker.atlassian.net/browse/FOUR-17551
ci:screen-builder:bugfix/FOUR-17551
=> FOUR-17551:Scrollbar Position Issue When Navigating to Next Page

resources/views/tasks/edit.blade.php
The value for "window.ProcessMaker.taskDraftsEnabled" by default "false", the template is not setting this value according to the configuration in the ".env" file
Set the correct value for variable "window.ProcessMaker.taskDraftsEnabled" when the template "tasks/edit" is loaded
Create process
Create a case
Open the task
Search for clear draft in task details
Ensure that the environment variable "TASK_DRAFTS_ENABLED" is set to "TRUE"
https://processmaker.atlassian.net/browse/FOUR-21624
=> FOUR-21624 There is not Clear draft in task detail

resources/grafana/MainDashboard.json
- https://processmaker.atlassian.net/browse/FOUR-21020
=> FOUR-21020 Add "Top Slowest Script Tasks" gauge to MainDashboard

ProcessMaker/Jobs/RunScriptTask.php, resources/grafana/MainDashboard.json
- https://processmaker.atlassian.net/browse/FOUR-21019
=> FOUR-21019 Chart to show script tasks completion count by task and process

ProcessMaker/Http/Controllers/AboutController.php, resources/views/about/microservices.blade.php
Adds a status to the about page
https://processmaker.atlassian.net/browse/FOUR-21696
=> Add script microservice status to about page

database/migrations/2025_01_29_205842_add_index_process_id_status_user_id_to_process_requests_table.php
When the table "process_requests" have more than 100,000 records, the endpoints that returns the totals takes more than 2 seconds to respond.
Added a new index for "process_requests" for the fields: 'process_id', 'status', 'user_id', with this new index the response takes 300-400 ms in my local server
Go to "My Requests" lists and check the server timing for endpoint: `https://127.0.0.1/api/1.0/requests?total=true&pmql=(status%20=%20%22In%20Progress%22)%20AND%20(requester%20=%20%22admin%22)`
https://processmaker.atlassian.net/browse/FOUR-21555
=> FOUR-21555 Performance backend improvements

ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php
Argument #1 ($url) must be of type string, null given, called in processmaker/ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php on line 34
- https://processmaker.atlassian.net/browse/FOUR-21690
=> FOUR-21690 An error is displayed when a script is executed

storage/skins/base/.gitignore
When running the command 'php artisan optimize', I get the error: "processmaker/storage/skins/base" directory does not exist.
- https://processmaker.atlassian.net/browse/FOUR-21793
=> FOUR-21793 When running the command 'php artisan optimize', I get the error: "processmaker/storage/skins/base" directory does not exist.

ProcessMaker/Http/Kernel.php, ProcessMaker/Http/Middleware/FileSizeCheck.php, config/app.php, tests/unit/FileSizeCheckTest.php
Ticket: [FOUR-21235](https://processmaker.atlassian.net/browse/FOUR-21235)
This PR implements `FileSizeCheck` middleware to enforce file upload limits for chunked uploads processed by `vue-simple-uploader` and `laravel-chunk-upload`. The middleware compares the file size against user-specific limits set in `app.php`.
- Implement `FileCheckMiddleware` in `processmaker`
- Set maximum file size limits in `app.php`
1. Go to branch `task/FOUR-21235` in `processmaker`.
2. Attempt to hit any of the following routes with a file size that exceeds your max file size limits in `app.php`:
- Create a Screen with a File Upload component → Add the Screen to a Process Task → Run the Process → Upload a File
- `https://processmaker.test/api/1.0/requests/{request}/files`
- Import a Process
- …
=> FOUR-21235 | Enforce File Upload Limit When Using Chunked File Upload Component

resources/views/tasks/edit.blade.php
- Fix was applied to edit.blade.php creating global variable for screenFields.
- Log in PM4
- Have o create a process with web entry  or without web entry
- Make test by copying WebEntry URL and with simple Case run
- Open devTools in new browser. 
- Fill fields in some form. The error with screenFields should no longer appear
https://processmaker.atlassian.net/browse/FOUR-21700
=> Bugfix/FOUR-21700: When filling any field from . web entry , we see an error in the console

resources/jscomposition/cases/casesDetail/config/columns.js
1. Create a process with self service
2. Start a case
3. Route to the task with self service
4. Open by case
5. Check the assigned field
Current Behavior
The assigned field in case page has an undefined avatar with self service which if we click on the avatar it redirects to an erroneous screen
- Show label SelfService
- https://processmaker.atlassian.net/browse/FOUR-21669
ci:deploy
=> FOUR-21669: Assigned field in case detail has an empty avatar in self service

ProcessMaker/Http/Controllers/Api/CssOverrideController.php
1. Go to server https://release-2025-winter-qa.processmaker.net/
2. Select Admin > Customize UI
3. upload new images and select different values in all fields
4. Press Save button
5. Press Reset button
6. Open the Customize UI page again
Some fields are not resetting
- Changing from destroy to delete resolved the issue because it affected how the cache was managed in Redis.
- Follow the steps
- https://processmaker.atlassian.net/browse/FOUR-21657
ci:deploy
=> FOUR-21657: Dynamic UI > Reset button does not work

tests/Sdk/BuildSdkTest.php
Build Sdk (Tests\Sdk\BuildSdk)
With unsupported language
Error: Call to undefined method Tests\Sdk\BuildSdkTest::setOutputCallback()   /opt/processmaker/tests/Sdk/BuildSdkTest.php:12
/opt/processmaker/tests/TestCase.php:40
https://processmaker.atlassian.net/browse/FOUR-21803
=> FOUR-21803 Fix failing unit tests

resources/jscomposition/cases/casesDetail/components/NewOverview.vue
1. Import a process or create a process with big history
2. Create a case
3. Complete the case
4. Go to request complete
5. Click on Overview
6. Move the scroll bar of the browser screen
7. Check the title of the process
The process title slides down across the screen in the request overview 
- use absolute instead of fixed
- https://processmaker.atlassian.net/browse/FOUR-21806
ci:deploy
=> FOUR-21806: The process title slides down across the screen in the request overview

ProcessMaker/Http/Controllers/CasesController.php, resources/views/cases/edit.blade.php
1. Login in a winter version
2. Go to cases
3. Open a case
4. Per default the Task is open
The following console log error is showing
modeler.js?id=5436ca…0fb712a5993379b27:1 Uncaught ReferenceError: ScreenBuilder is not defined at modeler.js?id=5436ca…a5993379b27:1:18249 at modeler.js?id=5436ca…a5993379b27:1:45230 at modeler.js?id=5436ca…a5993379b27:1:45234
Avoid error in the console
- https://processmaker.atlassian.net/browse/FOUR-21704
ci:deploy
ci:connector-pdf-print:bugfix/FOUR-21706
=> FOUR-21704: When we open a case the following error is showing 'Screen nBuilder is not defined'

database/migrations/2025_02_05_141451_add_index_process_request_id_status_to_process_request_tokens_table.php
The suggested new index is as follows:
`alter table process_request_tokens add index process_request_tokens_procid_status(process_request_id,status);`
- Add the suggested index by DBA
[FOUR-21709](https://processmaker.atlassian.net/browse/FOUR-21709)
[FOUR-21709]: https://processmaker.atlassian.net/browse/FOUR-21709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-21709 create index for table process_request_tokens

resources/js/next/libraries/processesCatalogueComponents.js, resources/js/next/libraries/processesComponents.js, resources/js/next/libraries/screensComponents.js, resources/js/next/libraries/scriptsComponents.js, resources/js/next/setupMain.js
1. Login in a winter version
2. Go to cases
3. Open a case
4. Per default the Task is open
Current  Behavior
The following console log error is showing
- https://processmaker.atlassian.net/browse/FOUR-21707
ci:deploy
=> FOUR-21707:When we open a case the following error is showing 'ProcessesComponents is not defined'

resources/js/tasks/index.js
In the task list, the tasks were displayed without filtering the current user
- change the component loading method
Review the task list, filtering by CaseNumber
=> The filter by cases in the TASK tab does not work correctly

resources/js/next/components/index.js, resources/js/next/setupMain.js
Some components were loading after that are required in Firefox browser
Some components are loading at the end of the setup
- Create a group
- Add View Users permission to the new group
- Create a simple process (start event - task - task - end event)
- Assign a created group in the start permissions accordion
- Active allow reassignment option for both tasks
- Open Firefox browser
- Login and run a Case 
- Try to reassign
https://processmaker.atlassian.net/browse/FOUR-21808
ci:deploy
=> FOUR-21808  modal is not displayed the users

ProcessMaker/Traits/TaskResourceIncludes.php
- Using a PM < 4.13, Create a process with start signal 
image-20250129-152432.png
- Configure the start signal with create record in collection
- Go to Collection
- Create a new record 
- Go to Cases
- Switch to PM 4.13
- Open the process started by signal
- Open the task
* If it is not possible to switch PM versions, the request can be created in 4.13 and the request user can be set to null via API.
- Validate is user exists to hide active_at
Follow the reproduction steps
- https://processmaker.atlassian.net/browse/FOUR-21860
=> FOUR-21860: Requests created by signals in versions < 4.13, show an empty screen

ProcessMaker/Http/Controllers/ProcessesCatalogueController.php, ProcessMaker/Http/Controllers/TaskController.php, ProcessMaker/Traits/SearchAutocompleteTrait.php, ProcessMaker/Traits/TaskControllerIndexMethods.php, resources/js/components/shared/LaunchpadSettingsModal.vue, resources/views/tasks/index.blade.php
- The Error 404 is no longer displayed.
- Go to new INBOX Participant Home Screen
- Open some Process
- Go to Ellipsis and select Edit Launchpad
- Click on "Edit Task Column"
- When modal window is opened no error should appear
https://processmaker.atlassian.net/browse/FOUR-21804
=> Bugfix/FOUR-21804: Error 404 on Available Columns in Launchpad settings

ProcessMaker/Traits/ProcessMapTrait.php, tests/Feature/CasesControllerTest.php
1. Create a process with a single task 
2. Start a CASE
3. Review the overview
4. Update the process Adding more task
5. Open the CASE created with version 1
- https://processmaker.atlassian.net/browse/FOUR-21893
ci:deploy
=> FOUR-21893: Overview does not show the correct version of proccess

ProcessMaker/Repositories/CaseRepository.php, tests/Feature/Cases/CaseExceptionTest.php
- https://processmaker.atlassian.net/browse/FOUR-21966
=> FOUR-21966 Do not log error case log when system like processes without case are updated

resources/js/common/PMColumnFilterPopoverCommonMixin.js
The tasks are not displayed and there are several error messages in the console.
- add the missed method
Described in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-21958
=> FOUR-21958: inbox rules does not show the filter selected from the requests save search.

ProcessMaker/Http/Controllers/RequestController.php, resources/jscomposition/cases/casesDetail/loader.js, resources/views/cases/edit.blade.php, resources/views/requests/show.blade.php
1. Create a process 
2. Convert the process to pmblock 
3. Create another process
4. Add the pmblock in the process
5. Crate a case
6. Complete the request of the pmblock
7. Go to Case
8. Click on Overview
9. Check the pmbcok in the canvas modeler
Overview does not show the pmblocks in Cases
PMblock should be displayed in Overview in Cases like  PM 4.12.2
- https://processmaker.atlassian.net/browse/FOUR-21880
ci:deploy
...
=> FOUR-21880:Overview does not show the pmblocks in Cases

tests/Feature/Cache/SettingCacheTest.php
There are problems running tests in the SettingCacheTest file
- Re-adapting Settings cache invalidation unit tests according to changes in the PR https://github.com/ProcessMaker/processmaker/pull/8008
[FOUR-21949](https://processmaker.atlassian.net/browse/FOUR-21949)
[FOUR-21949]: https://processmaker.atlassian.net/browse/FOUR-21949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-21949 there are problems running tests in the SettingCacheTest file

ProcessMaker/Repositories/TokenRepository.php
Create a Send Email before the Form task
Make sure that the user assigned in the Form Task has enable the Email Task Notification
Create a CASE
Review the email
- https://processmaker.atlassian.net/browse/FOUR-21718
- https://processmaker.atlassian.net/browse/FOUR-21713
=> FOUR-21718: When the previous element is a element without user the text  does not make sense

ProcessMaker/Repositories/TokenRepository.php, database/processes/screens/default-email-task-notification.json, database/seeders/DatabaseSeeder.php, database/seeders/ScreenEmailSeeder.php
After solved the conflicts in the database/seeders/ScreenSystemSeeder.php we need todo:
Create other seeder and use the new function getScreenByKey
Use the key default-email-task-notification to get the screen related
The Default Email is marked with system in this way this will not listed in the Screens List
- https://processmaker.atlassian.net/browse/FOUR-22068
ci:deploy
=> FOUR-22068: After the conflict need review the seeders for create default-email-task-notification

ProcessMaker/PackageHelper.php
The following PR's fixes the following observation https://processmaker.atlassian.net/browse/FOUR-22079
Also fixes:
- Issue trying to validate if package collections was installed in service provider
- Issue trying to delete a collection record when the record does not have a file id attached
- Issue when trying to add a file in rag records, related with appends attributes 'title', and 'uri_key'
- [Package AI](https://github.com/ProcessMaker/package-ai/pull/377)
- [Package Collections](https://github.com/ProcessMaker/package-collections/pull/427)
- [Core](https://github.com/ProcessMaker/processmaker/pull/8051)
=> Observation/FOUR-22079: Add drag drop feature for files in RAG

tests/Feature/Api/TaskAssignmentExecutionTest.php, tests/Feature/Api/processes/TaskConfiguredCustomDueIn.bpmn
- Double bracket was removed form BPMN file since Laravel 11 is more strict with XML notation.
- Run TEST with Laravel 11:  tests/Feature/Api/TaskAssignmentExecutionTest.php
https://processmaker.atlassian.net/browse/FOUR-22090
=> observation/FOUR-22090: Fix for TaskAssignmentExecutionTest

ProcessMaker/Models/ProcessRequestToken.php
Unable to reassign when Assignment rule is based on expressions
fix assignment rule when task instance is null
Create a Process:
Create a new process and add a form task.
Set the task's assignment rule to Regular Expression.
Configure Task Assignment:
Define the assignee based on the regular expression condition.
Specify a default task assignee.
Enable the options for Task Reassignment and Lock Assignment.
Test the Process:
Start a new case for the created process.
Navigate to the request and attempt to reassign the task.
https://processmaker.atlassian.net/browse/FOUR-21511
=> bugfix/FOUR-21511 Unable to reassign when Assignment rule is based on expressions

resources/views/requests/show.blade.php
Preview file is not visible in form in a request completed
- load manager scripts
- Create process with upload, preview file | Import the process
- Create a case
- Upload a file
- Wait until this will be preview in preview file control
- Click on submit button
- Go to request complete
- Go to form 
- Check the screen completed
- Check the preview file control
- [FOUR-22096](https://processmaker.atlassian.net/browse/FOUR-22096)
[FOUR-22096]: https://processmaker.atlassian.net/browse/FOUR-22096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Preview file is not visible in form in a request completed

resources/jscomposition/system/table/cell/CollapseFormCell.vue, resources/views/cases/edit.blade.php
Download file is not displayed in form completed cases
- add request-id to head html tag because is required for file download file field
- described in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-22097
=> FOUR-22097: download file is not displayed in form completed cases

resources/js/tasks/components/TaskListRowButtons.vue, resources/js/tasks/components/TasksList.vue
Floating buttons have a strange behavior when the cursor is over them in Firefox
- Use `display: inline-block` instead of `math` since it's not compatible with Firefox
- Use `getBoundingClientRect` instead of `offsetWidth` to get a more accurate width of the parent node
See the ticket
[FOUR-22048](https://processmaker.atlassian.net/browse/FOUR-22048)
[FOUR-22048]: https://processmaker.atlassian.net/browse/FOUR-22048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-22048 floating buttons have a strange behavior when the cursor is over them

resources/js/admin/users/index.js
- Variables that store data from fields have been reset with empty values when modal window is hidden
- Go to user page
- Click on +User button
- Create an user existent
- Click on Save (User could not be saved because user already exists)
- Click on Cance
- Fill some data in some fields (enter new data) but leave at least one mandatory field empty
- Click on save (Validation should be displayed because some required fields are empty)
- Press Cancel button
- Click on +User button
- Check the Create user form SHOULD BE EMPTY.
https://processmaker.atlassian.net/browse/FOUR-21980
=> bugfix/FOUR-21980: Cancel button does not clear the data in Create user form

resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/views/cases/edit.blade.php, routes/web.php
1. Create a process with upload files or pdf generator
2. Create a case
3. Upload a file or generated a pdf document
4. Complete the case
5. Open the case
6. Go to File manager
7. Open the file 
8. Refresh the page
9. Check the page
- https://processmaker.atlassian.net/browse/FOUR-22103
ci:deploy
ci:package-files:bugfix/FOUR-22103
=> FOUR-22103: Oops! page not found appears when refreshing the browser in files cases

resources/views/requests/show.blade.php, resources/views/tasks/edit.blade.php
1. Log in 
2. Go to Admin
3. Clcik on Integrations
4. Click on Docusign
5. COnfigure docusign
6. Click on Grant Docusign Access
7. Click on Open Process launchpad 
- When the process is related to the system the link to launchpad needs to hide in **Task view**
- https://processmaker.atlassian.net/browse/FOUR-21934
ci:deploy
=> FOUR-21934: Oopss page when entering "Open Process Launchpad" in Docusign Authorization

ProcessMaker/Http/Controllers/RequestController.php
1. Create a screen with record list or any control to save data
2. Create a process with two task
3. Save the process 
4. Create a case
5. Fill the screen in the task 1
6. Route to the following task
7. Open the task 2
8. Fill another data in the task 2
9. Complete the request
10. Go to form completed in request 
11. In request this show data that was completed in each task
12. Go to case
13. Go to form completed
14. Check the forms in each task
Completed forms in Cases do not show the data that was filled out in tasks, always show the last data 
- https://processmaker.atlassian.net/browse/FOUR-5991
=> FOUR-21957: Completed forms  in Cases do not show the data that was filled out in task

ProcessMaker/Http/Controllers/Api/ProcessController.php
Currently, when the API returns a 404 Not Found response for a process that does not exist, a popup message is displayed in the UI. However, this issue is part of a deeper problem where the Modeler component is being mounted twice, leading to duplicate API calls.
1. Open the Modeler and select a sub-process.
2. Observe that the API call to GET /api/1.0/processes/{processId} is made twice.
3. If the process does not exist, a 404 response is returned twice, triggering an error popup in the UI.
- Modified the show(int $processId) method in ProcessController.php to return a 204 response without a message, preventing the UI from displaying an error popup.
- The core issue of the Modeler mounting twice and causing duplicate API calls remains unresolved and requires further investigation and …
=> FOUR-21936: Error 404 when importing old processes with sub processes

resources/views/tasks/index.blade.php
- Validation for package-savedsearch was added
- In Spring version Login to PM4
- No error message should be displayed
- https://processmaker.atlassian.net/browse/FOUR-22387
=> observation/FOUR-22387: Route [package.savedsearch.defaults.edit] not defined

resources/jscomposition/cases/casesDetail/components/NewOverview.vue
1. Steps to reproduced:
2. Go to requests page
3. Open any completed request
4. Click Overview tab
5. Click the space key
If the request has scrolling, it will scroll to the bottom of the screen, and the "Pan Tool" is no longer displayed when you return to the paper with the mouse.
- https://processmaker.atlassian.net/browse/FOUR-23123
ci:modeler:bugfix/FOUR-23123
=> FOUR-23123:The "Pan Tool" disappears when you press the keyboard "space" in the overview.

ProcessMaker/Providers/ProcessMakerServiceProvider.php, ProcessMaker/Repositories/SettingsConfigRepository.php
See jira issue. Package auth provider was checking if it was enabled by looking at the Settings DB table but the config proxy wasn't allowing Settings DB calls until the application was fully booted.
- Only need to wait for DB instead of full app booted
- https://processmaker.atlassian.net/browse/FOUR-23139
- Others too
=> FOUR-23139 - Fix SAML configuration

ProcessMaker/Http/Controllers/Api/ProcessController.php, tests/Feature/Api/ProcessControllerTest.php
The searcher of the process in the start case or start request is not working, This does not filter the process searched 
The searcher of the process in the start case should filter the process typed
- Improve the where conditions according to the latest version of the framework 
See the ticket
[FOUR-22499](https://processmaker.atlassian.net/browse/FOUR-22499)
[FOUR-22499]: https://processmaker.atlassian.net/browse/FOUR-22499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
.
=> FOUR-22499 the searcher and pagination of the start new case are not working

ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php, resources/js/tasks/components/ProcessesDashboardsMenu.vue, routes/api.php
- List was modified to show Participant's Processes
- Login with a Admin user
- Create a normal userA and assign Process Catalog permission
- Create a process with Admin process (start event - task - task - end event)
- Assign the userA in the first task
- Create a Case with Admin user
- Login with userA
- Go to Home page
Test Scenario 2
- Login with Admin
- Create more than 10 simple Processes and start one of them at least once
- Check List of Processes in Home page. All processes greater than 10 should be displayed.
https://processmaker.atlassian.net/browse/FOUR-22497
=> Observation/FOUR-22497: Processes list is not displayed in the home page

resources/js/notifications/components/notification-item.vue
1. login in the server https://release-2025-spring-qa.processmaker.net/
2. ProcessMaker Platform Spring 2025 Version 4.14.0+beta-1 (Build #131e867d)
3. Create a simple process (start event - task - taks - end event)
4. Configure Notification accordion in both tasks 
5. Open this pages in the same browser
6. /modeler/{{id}}
7. /process-browser/?categoryId=recent
8. /cases
9. /tasks
10. /designer
11. /admin/users
12. /requests/199/files/Gemini_Generated_Image_5qgqwu5qgqwu5qgq.jpeg
13. /requests/199
14. /designer/screen-builder/518/edit
15. /tasks/644/edit
16. /file-manager
18. Create a Case
19. Wait until arrived notification
20. Open the notification in each page
- https://processmaker.atlassian.net/browse/FOUR-23124
ci:deploy
=> FOUR-23124 : Notification messages are not displayed correctly in different pages

tests/Feature/Cache/SettingCacheTest.php
Ticket: [FOUR-23425](https://processmaker.atlassian.net/browse/FOUR-23425)
In `SettingCacheTest.php`, the `testClearByPatternWithFailedDeletion()` test is failing on CI/CD but passing locally. 
- The test has been marked as skipped and will be reviewed later.
1. Run PHPUnit tests for `processmaker`, specifically in the `SettingCacheTest.php` file.
- `testClearByPatternWithFailedDeletion()` should be skipped.
[FOUR-23425]: https://processmaker.atlassian.net/browse/FOUR-23425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-23425 | Resolve Failing SettingCacheTest

database/migrations/2025_03_17_142216_add_default_value_for_properties_in_process_launchpad_table.php
1. Import the process
2. Select custom option
3. Uncheck launch pad configuration 
4. Try to import the process
- Define a default value
- https://processmaker.atlassian.net/browse/FOUR-23374
=> FOUR-23374

resources/js/components/shared/LaunchpadSettingsModal.vue
2. Add some elements
3. Create an alternative B
4. Click on publish button 
5. Configure the Launch pad settings 
6. Go to alternative B 
7. Click on Open Launch pad 
Open launch pad remains stuck in alternatives even though Launch pad settings have already been configured 
There should be possible to launch pad in alternatives after configure the launch pad
- https://processmaker.atlassian.net/browse/FOUR-22425
ci:deploy
=> FOUR-22425:Open launch pad remains stuck in alternatives even though Launch pad settings have already been configured

resources/js/admin/auth-clients/components/AuthClientsListing.vue, resources/js/components/shared/AddToBundle.vue
Different message is displayed instead of `Added successfully to bundle`
Changed the add to bundle message displayed and removed the add to bundle from auth clients
Go to server
ProcessMaker Platform Spring 2025 version 4.14.0+beta-1 (Build #131e867d)
Go to Admin > devlink > local bundle
Create a bundle
Go to Admin/users page or any page where an asset can be added to a bundle
Select the bundle
Press Save button
Wait for the message
https://processmaker.atlassian.net/browse/FOUR-23373
=> observation/FOUR-23373 Different message is displayed instead of `Added successfully to bundle`

resources/js/tasks/edit.js
- Create an user with manager in USER configuration
- Add Start Event → Task → End Event
- Configure the task form with "Assignee manager escalation"
- Create a cases
- Route to the task open the task 
- Click on ESCALATE TO MANAGER button 
It is not possible to Escalate to manager with "Assignee Manager Escalation"
The way the script elements are loaded has changed, so the corresponding missing definition is added.
https://processmaker.atlassian.net/browse/FOUR-22703
=> FOUR-22703

config/queue.php
Long running scripts are re-running clobbering each other even though the timeout was set high (or unlimited)
From the laravel docs
> The --timeout value should always be at least several seconds shorter than your retry_after configuration value. This will ensure that a worker processing a frozen job is always terminated before the job is retried. If your --timeout option is longer than your retry_after configuration value, your jobs may be processed twice.
Our timeouts are variable and there's no documentation on what happens if retry_after is set to null or 0 so I set it to a reasonable maximum of 1 day.
- Increase the redis retry_after setting to 1 day
Run a script with a 700 second sleep and a 900 second timeout. Look at the logs. Make sure it doesn't re-run after 630 seconds like it …
=> FOUR-23418 - Update "retry_after" for redis queue

ProcessMaker/Http/Controllers/Api/TemplateController.php
This PR resolves an issue where creating a process from a template containing a signal event resulted in errors.
The errors occurred due to:
- Attempting to check for existing assets using a UUID on a BPMN signal, which it did not contain.
- Running a `where` query on a Signal model that doesn't exist.
Signals are now treated as assets to skip during the validation process. This bypasses unnecessary checks, allowing the process creation to proceed without errors.
1. Import the provided process template.
2. Create a process using the imported template.
3. Verify that no errors occur during the process creation.
4. Confirm that the process is created successfully and behaves as expected. …
=> Resolve Process Creation Error for Templates with Signal Events

ProcessMaker/Models/Process.php, resources/js/processes/modeler/components/inspector/TaskNotifications.vue
1. Create a process 
2. Add task form 
3. Click on form task 
4. Click on Notifications 
5. Unchecked (Assigned and Due), Could select other 
6. Clone or copy the element
7. Check the notifications of the element cloned
8. Refresh and review the values
- https://processmaker.atlassian.net/browse/FOUR-22636
ci:deploy
=> FOUR-22636: Cloned tasks with notifications have Assigned and due by default, even when these have been modified

resources/js/processes/components/CreateProcessModal.vue
The menu to generate assets is not displayed because the ai=true flag is not present in the URL.
- Validate parameter ai Generated
steps in the ticket
- [FOUR-22817](https://processmaker.atlassian.net/browse/FOUR-22817)
[FOUR-22817]: https://processmaker.atlassian.net/browse/FOUR-22817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The "Create your missing assets with AI" message is not displayed when a process is generated with AI Assistant from a project.

resources/js/components/shared/AddToBundle.vue
`Add to bundle` option is not displayed in the Dashboards and Menus tabs
Added the add-to-bundle listener on mounted
Go to server 
ProcessMaker Platform Spring 2025 version 4.14.0+beta-2 (Build #dfc96dcd)
Go to Admin > Customize UI > Dashboards or Admin > Customize UI > Menus
Open the ellipsis
https://processmaker.atlassian.net/browse/FOUR-23376
=> observation/FOUR-23376 `Add to bundle` option is not displayed in the Dashboards and Menus tabs

ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
"data." is not set by default in variables of process in columns of saved search. So the value of the variables is not visible in the list.
Change the query used when the package "variable-finder" is enabled.
2. Create some cases
3. Create a saved search of the process 
4. Go to saved search configuration 
5. Click on columns 
6. Add values of the process like dataA that belong to variable of the process 
7. Check the value of the column (It is is without data.) So the value is not show in the list 
https://processmaker.atlassian.net/browse/FOUR-23512
=> FOUR-23512 Data in 'Available columns' is saved without 'data.' in Saved search by default

ProcessMaker/Cache/CacheManagerBase.php, ProcessMaker/Cache/Settings/SettingCacheManager.php, tests/Feature/Cache/CacheManagerBaseTest.php, tests/Feature/Cache/SettingCacheTest.php
SettingCache for null values is reading the database instead of the cache when reading the content.
- Check if the setting key exists in the cache
[FOUR-22377](https://processmaker.atlassian.net/browse/FOUR-22377)
[FOUR-22377]: https://processmaker.atlassian.net/browse/FOUR-22377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-22377 SettingCache for null values

resources/js/admin/devlink/components/AssetListing.vue
DevLink > Search icon is overlapped by the word in the search field
add a left padding in the search input
Go to server
Go to Admin > devLink 
Connect to Instance
Open the instance
Select Assets tab
Press view button
Search a asset
https://processmaker.atlassian.net/browse/FOUR-23561
=> observation/FOUR-23561 DevLink > Search icon is overlapped by the word in the search field

resources/js/processes-catalogue/components/BaseChart.vue
- Info button was fixed to show charts correctly
- Login PM4
- Open Process
- Go to Edit in Launchpad
- Select a Chart from dropdown list
- Save launchpad settings
- Click Info Button  several times to collapse and decollapse info section
- Chart selected should not change
https://processmaker.atlassian.net/browse/FOUR-23536
=> Observation/FOUR-23536: Chart configured in launchpad settings is lost after pressing Info button

ProcessMaker/Http/Controllers/Api/UserConfigurationController.php, resources/jscomposition/cases/casesMain/CasesDataSection.vue
- Log in  → https://release-2025-spring-qa.processmaker.net/
- Click on CASES tab 
- Click on My Cases, In progress, Completed, All Cases 
Additional Test:
- In the table of user_configuration, remove some indexes in ui_configuration like tasks_inbox.
As we see in the attached video, when we click on Cases, we get an error in the console, and we can't see the list of cad in one of the columns of cases.
- Merge default configuration with user configuration when some key is missing
- When columns is null return an empty object in frontend
- [FOUR-23621](https://processmaker.atlassian.net/browse/FOUR-23621)
[FOUR-23621]: https://processmaker.atlassian.net/browse/FOUR-23621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> Bugfix/FOUR-23621: Error in console when clicking on the Cases tab; no cases displayed

ProcessMaker/Cache/Settings/SettingCacheManager.php, tests/Feature/Cache/SettingCacheTest.php
When we enable or disable the Git Hub tab, it is not lost. It is not currently enabled, and there is no way to lose it. Disabling the option
- add Invalidates the cache for all service settings during the SSO enable/disable user actions
https://github.com/user-attachments/assets/dd7f1187-4709-46b9-8313-f10fdf9010bf
Detailed in the related ticket
-  https://processmaker.atlassian.net/browse/FOUR-23552
ci:deploy
ci:package-auth:bugfix/FOUR-23552
=> FOUR-23552: Checking some SSO options is not working correctly.

database/factories/ProcessMaker/Models/ProcessVersionFactory.php, tests/Feature/Api/ScreenTest.php
Some tests are failing when var finder is parsing the assets.
- Updated JSON encoding to native array format for better data handling.
- https://processmaker.atlassian.net/browse/FOUR-23649
ci:package-variable-finder:move-to-queued-job
.
=> FOUR-23649: Updated JSON encoding to native array format for better data handling.

ProcessMaker/Templates/ProcessTemplate.php
1. Create a process 
2. Save the process with some element
3. Save the process launchpad configuration
4. Search the process
5. Create a template in base to the process
6. Search the template 
7. Edit the template
8. Do this exercise twice (Step 6, Step 7)
- Solve the issue with `Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails`
- https://processmaker.atlassian.net/browse/FOUR-22470
ci:deploy
=> FOUR-22470: It is not possible to reopen a template that was created in base a process with launch pad

ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php
I identified an issue with the script microservice’s timeout behavior during testing. It appears that the service fails if the execution time exceeds 30 seconds, rather than waiting for a longer period. This issue may impact processes that require extended execution times.
- The `timeout` must be set on the HTTP client according to the [documentation](https://laravel.com/docs/11.x/http-client#timeout).
See the ticket
https://github.com/user-attachments/assets/d3dbd644-47cd-42bf-8dd2-3c11710866e9
[FOUR-23518](https://processmaker.atlassian.net/browse/FOUR-23518)
[FOUR-23518]: https://processmaker.atlassian.net/browse/FOUR-23518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-23518 timeout issue in script microservice fails after 30 seconds

resources/js/components/shared/ColumnChooser.vue
- Adjusting Height to fit better Column Modal in Edit Task Column (Launchpad Option)
- Open the process by launchpad
- Edit launchpad settings
- Click on Edit task columns (The form It is a normal size)
- Return to launchpad settings
- Set a screen in Launch Screen
- Save the changes
- Click on Edit task columns
- Check the form 
- https://processmaker.atlassian.net/browse/FOUR-23548
=> Observation/FOUR-23548: Edit Task Column form grows in length when a screen is set to launchpad

composer.json, composer.lock
Our package `package-plaid` depends on the package `tomorrow-ideas/plaid-sdk-php` but that package hasn't been updated in a while and depends on older packages. Down the chain of dependencies on those old packages, we reach `psr/http-message` where it can only work with version `^1.0` and the newest version is `2`.
Many packages rely on psr/http-message and most are fine with using `^1.0`... except `aws/aws-sdk-php`, which is used by `league/flysystem-aws-s3-v3` to communicate with s3
The requirement for version `^2` was [only added a few versions ago](https://github.com/aws/aws-sdk-php/pull/3061/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) in `3.338.0` and released on Jan 22
So this PR locks to the version just before that - `3.337.3`, which is a downgrade …
=> Set specific versions to allow for package-plaid

resources/views/layouts/layoutnext.blade.php
The VarFinder Panel does not open on the Cases or Analytics pages when using the shortcut **Shift + Space**.
1. Navigate to the **Cases** or **Analytics** pages.
2. Attempt to open the **VarFinder Panel** using **Shift + Space**.
- Added Blade directive, this ensures the view is included only when the package is available in the layout.
1. Navigate to the Cases or Analytics pages.
2. Press Shift + Space.
3. Confirm that the VarFinder Panel now opens correctly.
4. Ensure no errors are thrown if the package-variable-finder package is not installed.
🔎 **Note:** On the **/analytics/process-intelligence** page, most of the content is rendered inside an `<iframe>`, so keyboard shortcuts like **Shift + Space** will **not work inside that iframe**. 
- …
=> FOUR-23556: VarFinder Panel Not Displaying on Cases and Analytics Pages

resources/jscomposition/base/table/BaseTable.vue, resources/jscomposition/cases/casesMain/config/columns.js
1. Go to cases 
2. Click on Case Title
3. Look for “Reset Table“ option
#Current Behavior
Case title column does not have the Reset table option
- https://processmaker.atlassian.net/browse/FOUR-23140
ci:deploy
=> FOUR-23140: Case title column does not have the Reset table option

ProcessMaker/Http/Controllers/HomeController.php
1. Login using mobile
- The mobile needs to redirect task instead  inbox because there are not a INBOX version for mobile
- https://processmaker.atlassian.net/browse/FOUR-23520
ci:deploy
=> FOUR-23520: Mobile view - Headers are not displayed in the first login

resources/js/components/shared/AddToBundle.vue
- Login PM4
- Go to designer->Decision Tables
- Open Decision Table list
- Click on ellipsis and Add To Bundle
- The name for decision Table should be correct
- https://processmaker.atlassian.net/browse/FOUR-23662
=> observation/FOUR-23662: `Add asset to Bundle` modal does not display the correct name for a Decision Table

tests/unit/ProcessMaker/Listeners/HandleEndEventRedirectTest.php
- Create the test units
Run the command
` sudo XDEBUG_MODE=xdebug vendor/bin/phpunit  --testsuite Unit tests/unit/ProcessMaker/Listeners/HandleEndEventRedirectTest.php`
- https://processmaker.atlassian.net/browse/FOUR-23384
=> FOUR-23384: Implement test that replicates the issue

resources/js/processes/modeler/components/inspector/TaskNotifications.vue, resources/js/processes/modeler/initialLoad.js, resources/js/processes/modeler/modelerInit.js
1. Import an old process or Open a old processes
2. When check the a Task Properties
3. The toogle Assigne and Due are enable
- https://processmaker.atlassian.net/browse/FOUR-23563
ci:deploy
=> FOUR-23563: When the user import a process or open and old processes the toogle Assigne and Due is enable per default

resources/js/tasks/components/QuickFillPreview.vue
Quick Fill is not working for requests from Launch pad
Added a dynamic import of the tasks list component
Create a process with screen 
The screen have at lest one control like line input
Create request and fill the line input with some value
Open a request 
Open the process by launch pad 
Open the task
Click on Quick fill button
https://processmaker.atlassian.net/browse/FOUR-23365
=> observation/FOUR-23365 Quick Fill is not working for requests from Launch pad

resources/js/tasks/api/index.js, resources/js/tasks/loaderPreview.js, resources/js/tasks/preview.js, resources/js/tasks/utils/index.js, resources/js/tasks/variables/index.js
1. Log in 
2. Have a process with collection record control
3. start a new case 
4. edit collection record control 
5. Go to collections 
6. open collections 
7. open the collection and see the record number
8. the collection was edited correctly
9. go to Processes
10. Search for the process
11. open it from launchpad
12. go to the started case
13. click on preview
14. edit the collection
15. go to designer/ collections
- https://processmaker.atlassian.net/browse/FOUR-22407
ci:deploy
=> FOUR-22407: Collection record control not updating when editing from launchpad preview

database/migrations/2025_02_26_194048_modify_client_secret_in_dev_links_table.php
When the migration ran, there was a record in  dev_links with client_secret in null.
- Fix the migration that convert the column to text.
Migrate an environment with a dev link configured without client_secret (null).
- https://processmaker.atlassian.net/browse/FOUR-23643
=> FOUR-23643 Fix migration issue

ProcessMaker/Http/Controllers/HomeController.php, tests/Feature/HomeControllerTest.php
User/groups > Home Page field does not works correctly when URL Redirect is selected
- Consider DASHBOARD AND URL REDIRECT in login redirect.
https://github.com/user-attachments/assets/92d46836-29d5-45e3-a52b-deb9ac4533cd
- Setup User Home Page to REDIRECT URL
- Set a URL
- Save config
- Logout
- Login with the configured User
- https://processmaker.atlassian.net/browse/FOUR-23699
=> FOUR-23699 Fix User/groups > Home Page field does not works correctly when URL Redirect is selected

ProcessMaker/Jobs/CompileSass.php, ProcessMaker/Repositories/SettingsConfigRepository.php, helpers.php, tests/Repositories/SettingsConfigRepositoryTest.php
See jira issue
- Make the refactored settings config repository work with dot notation for values stored in settings
- Also, add a `--quiet` flag to the sass compiler to get rid of the deprecation warnings that we can't fix because they are part of the bootstrap sass library
Change the primary color and make sure the sidebar background changes
- https://processmaker.atlassian.net/browse/FOUR-23658
=> FOUR-24658 - Fix css config overrides

ProcessMaker/Models/Bundle.php, tests/Model/DevLinkTest.php
when settings configurations were added without any asset in the bundle then reinstall or update are not working.
fix the reinstall bundle feature when the bundle only has settings
Create a bundle without assets and settings and publish
on the other instance install the bundle
after installing go to the bundle and reinstall the bundle
https://processmaker.atlassian.net/browse/FOUR-23694
=> observation/FOUR-23694 when settings configurations were added without any asset in the bundle then reinstall or update are not working.

ProcessMaker/Listeners/HandleRedirectListener.php, ProcessMaker/Models/ProcessRequest.php
added an new param for redirectListener with active tokes to validate the redirection
Steps to Reproduce: 
import the attached process
Assign the users per each task
create a new case for the new process
run the case in parallel thread in the same time (with different users and browsers)
submit the first task
h5. Current Behavior: 
We have two scenarios: 
The task is set to "Task Source (Default)" in the Task Destination. Submitting one thread reloads the other and redirects to the request page (see the attached video on the parallel problem).
The task is set to "Show Next Assigned Task" in the Task Destination. Submitting one thread reloads the other and …
=> bugfix/FOUR-23723 added an new param for redirectListener

ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php
The error was caused by https://github.com/ProcessMaker/processmaker/pull/8141
The fix was intended to solve a problem where the script was failing after 30 seconds even though the microservice had not yet finished running the script. This was because laravel's HTTP client had a default timeout of 30 seconds
The problem is that some scripts (like the one configured for the PDF generator) had a null timeout. This means unlimited and it worked fine with the docker engine. However, the laravel HTTP client can not take null and must have a value set for it's timeout.
- Set a theoretical maximum of 1 day for the laravel client only. The actual timeout will be handled by the microservice, which correctly interprets `null` as unlimited.
Configure your environment to use the script microservice. …
=> Fix HTTP client timeout

ProcessMaker/Providers/AuthServiceProvider.php
…l passport
Response error with API calls using Password Grant authentication
explicitly enable password grant is required in new version of laravel Passport
Log in  
Go to Admin
Click on Auth Clients 
Create an auth client
Enter a name and enable the "Enable Password Grant" option.
Save
Copy the generated client secret.
place. with your domain data, id password as follows. curl
curl -X "POST" "{server domain}/oauth/token" \
-H 'Content-Type: application/json; charset=utf-8' \
-d $'{
"client_id": "1",
"username": "admin",
"password": "admin",
"client_secret": "{client_secret}",
"grant_type": "password"
}'
https://processmaker.atlassian.net/browse/FOUR-23761
=> observation/FOUR-23761 Response error with API calls using Password Grant authentication

ProcessMaker/Models/Setting.php, resources/js/admin/settings/components/SettingChoice.vue, resources/js/admin/settings/components/SettingsMain.vue, resources/views/admin/settings/index.blade.php
Add Email Listener by default
- Improve the settings management functionality in the application.
- The changes focus on enhancing the data retrieval process, adding new dependencies, and integrating additional components conditionally.
- Added a script tag to include the email listener JavaScript file if the `package-email-start-event` package is present.
[FOUR-22970](https://processmaker.atlassian.net/browse/FOUR-22970)
[FOUR-22970]: https://processmaker.atlassian.net/browse/FOUR-22970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-22970 add Email Listener by default

ProcessMaker/Http/Controllers/Api/SettingController.php, tests/Feature/Api/SettingsTest.php
Update the message error when the name exists
- Catch the error and show a specific message
1. Go to Settings - Iframe With List
2. Add the same Name URL
- https://processmaker.atlassian.net/browse/FOUR-23765
ci:deploy
=> FOUR-23765: Update the message error when the name exists

ProcessMaker/Models/Setting.php, resources/js/admin/settings/components/SettingsMain.vue, resources/views/admin/settings/index.blade.php
Test for CRUD for Email Listeners
- Enhance settings uiI to support new setting key for email listener
[FOUR-22972](https://processmaker.atlassian.net/browse/FOUR-22972)
[FOUR-22972]: https://processmaker.atlassian.net/browse/FOUR-22972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-22972 CRUD for Email Listeners

resources/js/components/shared/Column.vue, resources/js/components/shared/ColumnChooser.vue, resources/js/components/shared/LaunchpadSettingsModal.vue
1. Log in 
3. Click on Publish 
4. View  the Launchpad settings 
5. click on “Edit Task Column“
As we see the columns in Available Column of launchpad settings of a process, all are displayed
Edit Task Column should maintain the normal size even if it has more data. Only the scroll should grow and not the form.
- https://processmaker.atlassian.net/browse/FOUR-23814
=> FOUR-23814: Available Columns, in Edit Task Column, in Launchpad Settings shows all columns in bulk at the bottom

ProcessMaker/Models/DataSourceIntegrations.php, database/migrations/2025_04_17_164205_create_data_source_integrations_table.php
This PR adds the initial implementation for storing configured data source integrations in the database. It includes:
- Creation of the `data_source_integrations` table
- The `DataSourceIntegration` Eloquent model
`id` - int- Primary key 
`name` - string - Display name of the integration
`key` - string - Unique id of the integration (`pitchbook`)
`auth_type` - string - Authentication type (api_key, oauth, token etc..)
`base_url` - string - API base URL
`credentials` - text - Encrypted credentials (token or object)
1. Run `php artisan migrate`
2. A new table `data_source_integrations` should be created in your database
3. Run `php artisan migrate:rollback --step=1`
4. The `data_source_integrations` table should be dropped.
- [FOUR-23909](https://processmaker.atlassian.net/browse/FOUR-23909) …
=> Create Data Source Integrations Database Schema

ProcessMaker/Http/Controllers/Api/DataSourceIntegrationsController.php, ProcessMaker/Models/DataSourceIntegrations.php, database/factories/DataSourceIntegrationsFactory.php, database/migrations/2025_04_17_164205_create_data_source_integrations_table.php, routes/api.php, tests/Feature/Api/DataSourceIntegrationsTest.php
This PR introduces a new API endpoint `POST /api/1.0/data-source-integrations` to allow the creation and storage of data source integrations. It also includes the creation of the `DataSourceIntegrationsController` and corresponding tests to validate the endpoint behavior.
- `DataSourceIntegrationsController` to handle creation requests
- Endpoint registration for `POST /api/1.0/data-source-integrations`
- Validation logic for required fields
- Unit tests under `tests/Feature/Api/DataSourceIntegrationsTest.php`
1. Run the tests
`phpunit  tests/Feature/Api/DataSourceIntegrationsTest.php`
2. Confirm all tests pass
1. Make a `POST` request to:
`/api/1.0/data-source-integrations`
2. Example request body:
```
{
"name": "Test Integration",
"key": "test-integration",
"auth_type": "token", …
```
=> Add POST Endpoint to Create Data Source Integrations

ProcessMaker/Jobs/SyncDefaultTemplates.php
This PR addresses an error encountered during the upgrade command, specifically when running the 2023_08_15_183028_remove_seeded_default_templates migration.
The issue occurs when the SyncDefaultTemplates job attempts to fetch raw templates from GitHub, resulting in an exception such as:
```
Unable to fetch default template Purchase Order.
```
The relative_path for each template (e.g., ./accounting-and-finance/purchase-order.json) was used directly to build the raw GitHub URL. While this worked in local environments, CI/CD environments reported a 404 error for one specific template.
Interestingly, only the 5th template in the list (Purchase Order) failed, which suggests the possibility of an edge case such as:
- The file being temporarily unavailable in the 2023-fall branch during the …
=> FOUR-24213: Errors related to templates in builds and CICD

ProcessMaker/Traits/MakeHttpRequests.php
Data connectors fails by default in dev environments.
- Disable SSL on local environments.
=> Disable SSL on local environments

resources/js/processes/screen-builder/typeDisplay.js, resources/js/processes/screen-builder/typeForm.js, resources/views/cases/edit.blade.php
Add in the display screen a New control - Case Progress Bar
- https://processmaker.atlassian.net/browse/FOUR-24227
https://github.com/ProcessMaker/screen-builder/pull/1815
ci:deploy
ci:screen-builder:feature/FOUR-24227
=> FOUR-24227: Add in the display screen a New control - Case Progress Bar

ProcessMaker/Jobs/SyncDefaultTemplates.php, tests/Jobs/SyncDefaultTemplatesTest.php
During the upgrade process, the job SyncDefaultTemplates was failing with the following error:
```
PHP Fatal error:  Uncaught Exception: Unable to fetch default template Payment request form.
```
This only occurred intermittently during CI/CD pipelines, while working fine locally. The issue was caused by transient failures when fetching template files from GitHub (e.g., timeouts, rate limiting, or connectivity issues).
See error here: https://github.com/ProcessMaker/processmaker/actions/runs/15070208108/job/42366062358?pr=8234
- Added timeout(10) to avoid indefinite hanging during GitHub requests.
- Replaced throw new Exception() with a Log::warning() and continue if a template file cannot be fetched.
- Ensures the job will continue processing the next templates even if one fails.
- This …
=> FOUR-24430: CI Unit Test are given error SyncDefaultTemplates.php:79

ProcessMaker/Http/Controllers/Api/CaseController.php, routes/api.php, tests/Feature/CasesControllerTest.php
Consider use cases for return Default Stages per Case and Case_number not required
- Update the API to return a Default stages when the case_number does not exist
- https://processmaker.atlassian.net/browse/FOUR-24448
ci:deploy
ci:screen-builder:feature/FOUR-24448
=> FOUR-24448: Consider use cases for return Default Stages per Case and case_number not required

database/migrations/2025_05_19_205653_add_index_stage_id_for_requests_cases_and_tokens.php
Add indexes to improve the queries about stage_id
- Add index to filter per stage:
```
process_request_token.stage_id
process_request. last_stage_id
case_participant. last_stage_id
case_started. last_stage_id
```
- https://processmaker.atlassian.net/browse/FOUR-24450
=> FOUR-24450: Add indexes to improve the queries about stage_id

ProcessMaker/Http/Controllers/Api/ProcessController.php, tests/Feature/ProcessHtmlTest.php, tests/Fixtures/process_with_html.bpmn
- Add support to html entities in bpmn documents
- https://processmaker.atlassian.net/browse/FOUR-23865
- https://github.com/ProcessMaker/nayra/pull/230
ci:nayra:bugfix/FOUR-23865
ci:deploy
ci:package-savedsearch:bugfix/FOUR-23865
ci:k8s-branch:task/FOUR-24126
....
=> FOUR-23865: Fix loading tasks in saved search with process with html entities

resources/js/tasks/components/taskPreview/TaskPreviewAssignment.vue
1. Go to task or Process I Manager
2. Open Preview from a request in order to Reassing
3. select a person 
4. Add a comment
5. Click assign more than one time
- https://processmaker.atlassian.net/browse/FOUR-23891
ci:deploy
=> FOUR-23891: UI: The Assign button needs to block for avoid send the comments a more than one time

ProcessMaker/Http/Controllers/Api/CaseController.php, tests/Feature/Api/ProcessLaunchpadTest.php
Error is showing in the API: api/1.0/cases/stages_bar/2
- https://processmaker.atlassian.net/browse/FOUR-24636
ci:deploy
=> FOUR-24636: Error is showing in the API: api/1.0/cases/stages_bar/2

resources/js/admin/settings/components/ModalWhiteList.vue
1. Login as Admin
2. Go to Admin Settings
3. Click on IFrame White list
4. Click on ADD URL
5. In site name type space in blank
6. Tyep a valid URl
7. Save the changes
- https://processmaker.atlassian.net/browse/FOUR-23828
=> FOUR-23828: It is possible to create Site name with blank spaces in IFrame white list

upgrades/2025_03_31_140424_add_menu_frame_whitelist_default.php
1. Go to server https://develop-qa.processmaker.net/admin/settings
3. Review the menu IFrame Whitelist Config
The menu is not visible
The menus needs to display
- https://processmaker.atlassian.net/browse/FOUR-24545
ci:deploy
=> FOUR-24545

resources/js/tasks/components/TasksPreview.vue, resources/js/tasks/components/taskPreview/TaskPreviewAssignment.vue
1. Go to home
2. Search a task in progress
3. Click on preview button 
4. Click on reassignment option 
5. Check the (Cancel and Assign) buttons on the top
Cancel and Assignment buttons are not in the correct position in the Reassignment form 
Cancel button should be on the left
Assign button should be on the right 
- https://processmaker.atlassian.net/browse/FOUR-24105
=> FOUR-24105:Cancel and Assignment buttons are not in the correct position in the Reassignment form

config/ai.php, resources/views/layouts/layout.blade.php
Resolves tickets:
https://processmaker.atlassian.net/browse/FOUR-24559
https://processmaker.atlassian.net/browse/FOUR-24259
Axios timeout after 60000ms in Flow Genie
The RAG collection type is not visible, but Genie does show the selection option.
- Added an environment variable (AI_GENIE_CLIENT_TIMEOUT) for avoid the hardcoded 60000 ms.
- Read the env. variable AI_RAG_COLLECTIONS_ENABLED to hide/show rag collections from configuration
Follow the instructions of the related tickets
https://processmaker.atlassian.net/browse/FOUR-24559
https://processmaker.atlassian.net/browse/FOUR-24259
=> Axios timeour after 60000ms in Flow Genie

ProcessMaker/Http/Controllers/Api/DevLinkController.php, ProcessMaker/Models/Bundle.php, resources/js/admin/devlink/components/BundleSettingsModal.vue
devLink > options are not synchronized
fixed the add settings API when changing the settings from a bundle
Go to serverA
Create a bundle
Go to Settings page (/admin/settings)
configure settings (Email settings, Log-in & Auth, User Settings, integrations and UI Settings)
Add each setting to bundle
Publish the bundle
Go to serverB
Create a instance to serverA
Download the bundle
Open the bundle
Search the cards related to settings  (Email settings, Log-in & Auth, User Settings, integrations and UI Settings)
Press gear icon
Check the options
Go to serverA
Open the bundle
Check the options
https://processmaker.atlassian.net/browse/FOUR-23820
=> observation/FOUR-23820 devLink > options are not synchronized

ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
Log in 
Have a collection
Create a save search 
Create a save search for that collection
Open the save search
Click on save search settings
Click on columns
Add any column
Re-enter save search settings
As we see, every time we enter the save search configuration, the added columns are displayed again, so we can add them again. With this behavior, we can add columns multiple times.
When entering Columns in the save search settings, it should not be duplicated.
- Keep the logic of filtering available columns when a saved search is used
- https://processmaker.atlassian.net/browse/FOUR-24546
=> FOUR-24546L The columns available in a save search can be duplicated each time we enter the save search configuration.

ProcessMaker/Http/Controllers/Api/SettingController.php, helpers.php, tests/Feature/Admin/SettingsControllerTest.php
Go to admin
Click on IFrame Whitelist
Add a new URL
Set a name
Set URL
Save the changes
Delete the url
Click on edit set a wrong url like an string or number Save the changes
The edit whitelist does not validate the correct values
Edit form in whitelist should validate correct values entered
https://processmaker.atlassian.net/browse/FOUR-24684
=> FOUR-24684 It is possible to set an invalid URL in Iframe white list.

database/migrations/2025_06_05_151344_add_index_case_number_to_cases_participated.php
Regarding to a new slow query identified which involve new table cases_participated.
This new index could significantly enhance this query.
The following is the slow query:
`update `cases_participated` set `case_status` = 'ERROR', `cases_participated`.`updated_at` = '2025-05-20 09:38:09' where `case_number` = 9588`
`php artisan migrate`
- https://processmaker.atlassian.net/browse/FOUR-24522
=> FOUR-24522: Create Index to Improve Slow Query on cases_participated

resources/js/processes/modeler/components/inspector/StageItem.vue, resources/js/processes/modeler/components/inspector/StageList.vue, resources/js/processes/modeler/components/inspector/StageManager.vue
In the Stages  configuration of the modeler we need to update the following
Remove the checklist
To select the stage of the sequence flow user should make one click
To remove the Stage of the sequence flow user should make two clicks
When a stage is selected, the stage name should be highlighted in blue to indicate its active.
- https://processmaker.atlassian.net/browse/FOUR-24707
ci:deploy
=> FOUR-24707: Stages - Update the Checklist design with click option

resources/views/profile/edit.blade.php
Display Slack Notification errors to users in UI
[FOUR-23394](https://processmaker.atlassian.net/browse/FOUR-23394)
[Slack Connector PR](https://github.com/ProcessMaker/connector-slack/pull/33)
[FOUR-23394]: https://processmaker.atlassian.net/browse/FOUR-23394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FOUR-23394 | Handle UI State Changes

ProcessMaker/Console/Commands/MultitenancyCreate.php
There's a bug in the MultitenancyCreate.php file at line 97 - it's trying to use an undefined constant
- update this line
run the command 
`php artisan multitenancy:create --name="Another Tenant" --database=another_tenant --url=http://another-tenant.test --username=test --password=test
`
- n/a
=> fix  trying to use an undefined constant

ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
1. Create Saved search in Request or Task
2. Open the saved search
3. Click on RESET TO DEFAULT button
4. Open the columns agains
5. Move one variables of available columns to active columns
6. Save the changes
7. Open the columns agains
The variables are duplicated in Available columns in task and request Saved search 
The variables should not be duplicated in Available columns in task and request Saved search
- https://processmaker.atlassian.net/browse/FOUR-23812
=> FOUR-23812:The variables are duplicated in Available columns in TASK and REQUEST Saved search

ProcessMaker/Helpers/DefaultColumns.php, ProcessMaker/Http/Controllers/TaskController.php, resources/js/tasks/components/ListMixin.js, resources/views/tasks/index.blade.php, tests/unit/ProcessMaker/Helpers/DefaultColumnsTest.php
The API task needs to load the 'data' only if is necesary
1. Go to Task List
2. Review the API called `https://dev.cloud.processmaker.net/api/1.0/tasks?page=1&include=process,processRequest,processRequest.user,user,data`
When the task List is not using a custom Columns the data is not necesary to call. 
We need to call data only if the list requires this information
- Detect if the data is necesary to add
- https://processmaker.atlassian.net/browse/FOUR-24946
ci:deploy
=> FOUR-24946: The API task needs to load the 'data' only if is necesary

ProcessMaker/Traits/TaskControllerIndexMethods.php, resources/js/tasks/components/ListMixin.js, resources/js/tasks/components/ParticipantHomeScreen.vue, resources/js/tasks/router.js
1. Log in
2. Click the Inbox button
3. Filter the "completed" status and apply
4. Click "reload this page"
- https://processmaker.atlassian.net/browse/FOUR-23617
ci:deploy
=> FOUR-23617: When reloading the page, the completed status filter show all clear

resources/js/processes-catalogue/components/ProcessInfo.vue, resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue, resources/js/processes-catalogue/components/progressBar/ProgressInfo.vue, resources/js/processes/modeler/components/inspector/StageItem.vue
2. Add Start Event → Task form 
3. Select sequence flow 
4. Go to Stages 
5. Set a stage with large name
6. Press enter key 
7. Check the stage 
When the stage is too long it is displayed on several lines.
When the stage is too long, only two or one lines should be displayed; the rest should be shown with dots.
- https://processmaker.atlassian.net/browse/FOUR-24773
- https://processmaker.atlassian.net/browse/FOUR-24771
=> FOUR-24773:One or two lines should be visible in stages name configuration

tests/Feature/Api/EnvironmentVariablesTest.php
The enviroment variable METRICS_API_ENDPOINT does not show
- https://processmaker.atlassian.net/browse/FOUR-24803
ci:deploy
=> FOUR-24803

resources/js/processes-catalogue/components/home/CustomHomeTableSection/CustomHomeTableSection.vue, resources/jscomposition/base/table/TCell.vue
1. Import the process Related process_grant_radar (2).json 
2. Execute a case
3. Populate the variables in the form 
4. Go to Inbox
5. Select the process and use Grants View
Current Behavior
The columns does not display the information returned by the API
- https://processmaker.atlassian.net/browse/FOUR-24778
=> FOUR-24778: The columns data.someFields does not show the correct information

resources/jscomposition/cases/casesDetail/components/CaseDetail.vue, resources/jscomposition/cases/casesDetail/components/Tabs.vue
1. Import or created a process with more than one page
2. Create a case 
3. Complete all the task 
4. Go to cases
5. Click on “Completed & Forms“
6. Displays all completed screens
There is not scroll in "Completed & Form" Cases, so it is not possible all data of screens
The scroll should be enabled in cases where there are many screens like previous versions
- https://processmaker.atlassian.net/browse/FOUR-24972
=> FOUR-24972: There is not scroll in "Completed & Form" Cases

resources/js/processes/modeler/components/inspector/StageList.vue, resources/js/processes/modeler/components/inspector/StageManager.vue
2. Add Start Event  → Task form → End Event
3. Select the first flow 
4. Add 8 stages
5. Select the second flow
6. Click on “+“ button 
7. Add ninth stage
loading stages takes time to render, So it is possible to add more than 8 stage 
The “+“ button should be blocked until all stages are rendered
- wait for the stages to load
- https://processmaker.atlassian.net/browse/FOUR-24983
ci:deploy
=> FOUR-24983: It is possible to add more than 8 stages in modeler 

ProcessMaker/Http/Controllers/Api/SettingController.php, ProcessMaker/Repositories/SettingsConfigRepository.php, tests/Repositories/SettingsConfigRepositoryTest.php
Endpoint to get all records from a collection is very slow
Improvement in the local cache for settings
Use the endpoint: 
`http://<server>/api/1.0/collections/<collection_id>/records`
with a collection with 1500 records at least
https://processmaker.atlassian.net/browse/FOUR-25078
=> FOUR-25078 Response time in data connector resources has increased afer the upgrade to version 4.14

ProcessMaker/Models/Screen.php, database/processes/screens/default-email-task-notification.json, database/seeders/ScreenEmailSeeder.php, tests/unit/ScreenEmailSeederTest.php, upgrades/2025_07_08_151252_update_default_email_task_notification_screen_category.php
Then create an migration to update this value and remove the screen system flag
- Display the screen DEFAULT_EMAIL_TASK_NOTIFICATION in the Screen List
Please execute the following commands:
- For the old enviroments to Update the Default Email Task Notification  `php artisan upgrade`
- For the new enviroments to Create the Default Email Task Notification `php artisan db:seed`
- https://processmaker.atlassian.net/browse/FOUR-25243
ci:deploy
=> FOUR-25243: Show the Email Screen in the Screen list

ProcessMaker/Http/Controllers/Api/ScreenController.php
Prevent deletion of DEFAULT_EMAIL_TASK_NOTIFICATION
- The following message is showed when the **Default Email Task Notification** is tried to delete
- https://processmaker.atlassian.net/browse/FOUR-25242
=> FOUR-25242: Prevent deletion of DEFAULT_EMAIL_TASK_NOTIFICATION

resources/js/tasks/components/ParticipantHomeScreen.vue, resources/js/tasks/mixins/TasksMixin.js
1. Log in 
2. Have cases in Tab Inbox/ Priority and Draft 
3. Click on Tab Priority 
4. Click on Reloaded this page to browser
- https://processmaker.atlassian.net/browse/FOUR-25042
ci:deploy
=> FOUR-25042: The Priority and Draft tab are moved to the Inbox, when you click the browser's reloaded this page

ProcessMaker/Models/Process.php
Total cases does not match with cases started in launchpad to Grant chart
- Consider the ERROR and CANCELED
- https://processmaker.atlassian.net/browse/FOUR-25271
ci:deploy
=> FOUR-25271: Total cases does not match with cases started in launchpad to Grant chart

ProcessMaker/Repositories/CaseParticipatedRepository.php, ProcessMaker/Repositories/CaseRepository.php
UI: the progress Bar needs work when the stages are the defaults
- https://processmaker.atlassian.net/browse/FOUR-25306
ci:deploy
=> FOUR-24887: UI: the progress Bar needs work when the stages are the defaults

ProcessMaker/Repositories/TokenRepository.php, tests/Feature/TaskControllerTest.php
Delete the Backend changes related to the Task Notification Email
- https://processmaker.atlassian.net/browse/FOUR-25246
ci:package-actions-by-email:feature/FOUR-25228
=> FOUR-25246: Delete the Backend changes related to the Task Notification Email

resources/js/processes-catalogue/components/ProcessCollapseInfo.vue, resources/js/processes-catalogue/components/ProcessInfo.vue
2. Go to process launchpad
3. Open the process created 
4. Click on “i“ button
5. Close the process info form 
- https://processmaker.atlassian.net/browse/FOUR-25222
ci:deploy
=> FOUR-25222: There is no synchronization with the 'i' button and the form process info when it is open or closed

ProcessMaker/Models/Process.php, resources/js/processes-catalogue/components/home/TceDistributionGrants.vue, tests/Feature/Api/ProcessControllerTest.php
1 Create a process without stages
2. Add Start Event → Task → End Event
3. Create so,e request
4. Go to process launchpad
5. Open the process
6. Click on Edit launchpad 
7. Select the “Grant“ in screen launcher
8. Save the changes
9. Click on “IN progress“ card
10. Click on “IN Completed“ card
- https://processmaker.atlassian.net/browse/FOUR-25269
ci:deploy
=> FOUR-25269: In Grant chart the tabs In progress and Completed does not listed any request

ProcessMaker/Models/Setting.php, upgrades/2025_07_23_114259_add_menu_translations_to_users_settings.php
Add setting to enable translations and language type
- Added an upgrade command to add the translation setting to users menu
- https://processmaker.atlassian.net/browse/FOUR-25275
=> Task/FOUR-25275: Add setting to enable translations and language type

resources/js/components/Menu.vue, resources/views/auth/newLogin.blade.php, resources/views/layouts/navbar.blade.php
This PR changes the flag icon with a language code. Also there are some UI adjustments.
- UI Adjustments for language code
- Show language code instead flag icon
https://github.com/user-attachments/assets/8d70e91f-8725-4b61-b54f-7959f2280d2c
- https://processmaker.atlassian.net/browse/FOUR-25276
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/8384)
- [Package Translations PR](https://github.com/ProcessMaker/package-translations/pull/179)
=> Task/FOUR-25276: Modify PM Core layout to show the language code instead flag icon: Login, screen builder, nav bar

resources/views/layouts/ai-qr-mobile.blade.php, resources/views/layouts/layout.blade.php, resources/views/layouts/layoutnext.blade.php, resources/views/layouts/print.blade.php
- Add is translations enable setting to meta tags.
- Use the setting value to show or hide the language button
https://github.com/user-attachments/assets/4e9d3aef-3ff7-4389-8840-35af0235571a
- https://processmaker.atlassian.net/browse/FOUR-25277
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/8385)
- [Package WebEntry PR](https://github.com/ProcessMaker/package-webentry/pull/274)
- [Package Translations PR](https://github.com/ProcessMaker/package-translations/pull/180)
=> Task/FOUR-25277: Refactor packages and core

ProcessMaker/Http/Controllers/CasesController.php
The Stage for the End Event is not registered and the progress is not showing correctly
- https://processmaker.atlassian.net/browse/FOUR-24578
ci:deploy
=> FOUR-24578: The Stage for the End Event is not registered and the progress is not showing correctly

resources/js/processes/modeler/components/inspector/StageManager.vue
2. Add Start Event → Task A → Task B → End Event
3. Create two stages
4. Configure the flow in the task with stages
5. Publish the process
6. Delete all stages
7. Check the labels in the flows
Labels in stage flows are not lost after deleting all stages 
All labels in the flow should be cleared if stages were deleted
- https://processmaker.atlassian.net/browse/FOUR-25273
=> FOUR-25273: Labels in stage flows are not lost after deleting all stages.

resources/js/processes/modeler/components/inspector/AgregationProperty.vue
2. Add Start Event → Task form → End Event
3. Click on one flow
4. Go to Aggregation section
5. Put the following variables 
6. Variable that start with a number
7. reserved words such as (if, where)
8. Special characters
9. Variables with blank spaces 
- https://processmaker.atlassian.net/browse/FOUR-25426
ci:deploy
=> FOUR-25426:UI: There is no validation of variables in Stage Aggregation

resources/views/auth/newLogin.blade.php
- Go to Admin settings
- Click on user settings
- Enable translations toggle
- Log out
- In the login page
There is not translation button in login page, after the translation was enables from admin settings
**Expected Behavior** 
There should be a translation button in login page like previous version 4.14.2 
- Make the translations settings available in login page to show/hide the language selector button
https://github.com/user-attachments/assets/c709beb7-9cdb-4a4c-9423-3251e081d0de
- https://processmaker.atlassian.net/browse/FOUR-25472
=> Bugfix/FOUR-25472: There is not translation button in login page
